#!/usr/bin/env python3
"""Fill TOEIC-L4 (241 words)"""
import json, glob

DICT13 = {
    "asleep":        ("/əˈsliːp/", "형용사", "잠든", "The baby is asleep.", "아기가 잠들었다."),
    "carton":        ("/ˈkɑːrtən/", "명사", "카톤, 상자", "A carton of milk.", "우유 한 팩."),
    "compatible":    ("/kəmˈpætɪbəl/", "형용사", "호환되는", "Compatible software.", "호환 가능한 소프트웨어."),
    "consumption":   ("/kənˈsʌmpʃən/", "명사", "소비", "Energy consumption.", "에너지 소비."),
    "conveniently":  ("/kənˈviːniəntli/", "부사", "편리하게", "Conveniently located.", "편리하게 위치하다."),
    "cosmetic":      ("/kɒzˈmɛtɪk/", "명사", "화장품", "Cosmetic surgery.", "성형 수술."),
    "courtesy":      ("/ˈkɜːrtəsi/", "명사", "예의, 정중함", "Common courtesy.", "기본 예의."),
    "creativity":    ("/ˌkriːeɪˈtɪvɪti/", "명사", "창의성", "Encourage creativity.", "창의성을 장려하세요."),
    "disagreement":  ("/ˌdɪsəˈɡriːmənt/", "명사", "불일치, 의견 차이", "Resolve the disagreement.", "의견 차이를 해결하세요."),
    "disappointment":("/ˌdɪsəˈpɔɪntmənt/", "명사", "실망", "Express disappointment.", "실망을 표현하세요."),
    "dissatisfy":    ("/dɪsˈsætɪsfaɪ/", "동사", "불만족스럽게 하다", "Don't dissatisfy customers.", "고객을 불만족하게 하지 마세요."),
    "enjoyable":     ("/ɪnˈdʒɔɪəbəl/", "형용사", "즐거운", "An enjoyable experience.", "즐거운 경험."),
    "faculty":       ("/ˈfækəlti/", "명사", "교수진, 능력", "Faculty meeting.", "교수진 회의."),
    "favorable":     ("/ˈfeɪvərəbəl/", "형용사", "유리한, 긍정적인", "Favorable conditions.", "유리한 조건."),
    "foreman":       ("/ˈfɔːrmən/", "명사", "현장 감독", "Site foreman.", "현장 감독."),
    "forum":         ("/ˈfɔːrəm/", "명사", "포럼, 토론회", "Online forum.", "온라인 포럼."),
    "founder":       ("/ˈfaʊndər/", "명사", "설립자", "Company founder.", "회사 설립자."),
    "fundraise":     ("/ˈfʌndreɪz/", "동사", "기금을 모으다", "Fundraise for charity.", "자선을 위해 기금을 모으세요."),
    "graphics":      ("/ˈɡræfɪks/", "명사", "그래픽스", "Computer graphics.", "컴퓨터 그래픽스."),
    "handy":         ("/ˈhændi/", "형용사", "편리한, 손재주 있는", "Come in handy.", "유용하게 쓰이다."),
    "hazardous":     ("/ˈhæzərdəs/", "형용사", "위험한", "Hazardous waste.", "위험 폐기물."),
    "healthcare":    ("/ˈhɛlθkɛər/", "명사", "의료, 보건", "Healthcare system.", "의료 시스템."),
    "humidity":      ("/hjuːˈmɪdɪti/", "명사", "습도", "High humidity.", "높은 습도."),
    "influential":   ("/ˌɪnfluˈɛnʃəl/", "형용사", "영향력 있는", "Influential leader.", "영향력 있는 리더."),
    "nationwide":    ("/ˌneɪʃənˈwaɪd/", "형용사", "전국적인", "Nationwide campaign.", "전국 캠페인."),
    "pad":           ("/pæd/", "명사", "패드, 메모지", "Notepad.", "메모지."),
    "paraphrase":    ("/ˈpærəfreɪz/", "동사", "다시 쓰다, 바꿔 쓰다", "Paraphrase the sentence.", "문장을 바꿔 쓰세요."),
    "placement":     ("/ˈpleɪsmənt/", "명사", "배치, 취업 알선", "Job placement.", "취업 알선."),
    "postal":        ("/ˈpoʊstəl/", "형용사", "우편의", "Postal code.", "우편 번호."),
    "publicity":     ("/pʌˈblɪsɪti/", "명사", "홍보, 광고", "Public publicity.", "공공 홍보."),
    "renter":        ("/ˈrɛntər/", "명사", "임차인", "Tenant or renter.", "세입자."),
    "repairperson":  ("/rɪˈpɛərpɜːrsən/", "명사", "수리공", "Call the repairperson.", "수리공을 부르세요."),
    "repeatedly":    ("/rɪˈpiːtɪdli/", "부사", "반복적으로", "Asked repeatedly.", "반복적으로 요청했다."),
    "restroom":      ("/ˈrɛstruːm/", "명사", "화장실", "Restroom break.", "화장실 휴식."),
    "silently":      ("/ˈsaɪləntli/", "부사", "조용히", "Work silently.", "조용히 일하세요."),
    "spa":           ("/spɑː/", "명사", "스파, 온천", "Relaxing spa.", "편안한 스파."),
    "spreadsheet":   ("/ˈsprɛdʃiːt/", "명사", "스프레드시트", "Update the spreadsheet.", "스프레드시트를 업데이트하세요."),
    "stapler":       ("/ˈsteɪplər/", "명사", "스테이플러", "Use a stapler.", "스테이플러를 사용하세요."),
    "streamline":    ("/ˈstriːmlaɪn/", "동사", "간소화하다", "Streamline the process.", "과정을 간소화하세요."),
    "substantially": ("/səbˈstænʃəli/", "부사", "상당히", "Substantially improved.", "상당히 개선됐다."),
    "teller":        ("/ˈtɛlər/", "명사", "은행 창구직원", "Bank teller.", "은행 창구직원."),
    "tidy":          ("/ˈtaɪdi/", "형용사", "깔끔한, 정돈된", "Keep things tidy.", "정돈 상태를 유지하세요."),
    "toll":          ("/toʊl/", "명사", "통행료, 피해", "Pay the toll.", "통행료를 내세요."),
    "toner":         ("/ˈtoʊnər/", "명사", "토너", "Replace the toner.", "토너를 교체하세요."),
    "urgently":      ("/ˈɜːrdʒəntli/", "부사", "긴급하게", "Respond urgently.", "긴급하게 응답하세요."),
    "walkway":       ("/ˈwɔːkweɪ/", "명사", "통로, 보행로", "Covered walkway.", "덮인 통로."),
    "absorb":        ("/əbˈzɔːrb/", "동사", "흡수하다", "Absorb new information.", "새로운 정보를 흡수하세요."),
    "administer":    ("/ədˈmɪnɪstər/", "동사", "관리하다, 투여하다", "Administer the test.", "시험을 관리하세요."),
    "ample":         ("/ˈæmpəl/", "형용사", "충분한, 풍부한", "Ample time.", "충분한 시간."),
    "antique":       ("/ænˈtiːk/", "명사", "골동품", "Antique furniture.", "골동품 가구."),
    "bean":          ("/biːn/", "명사", "콩", "Coffee bean.", "커피 원두."),
    "browse":        ("/braʊz/", "동사", "검색하다, 훑어보다", "Browse the internet.", "인터넷을 검색하세요."),
    "bye":           ("/baɪ/", "감탄사", "안녕히 가세요", "Bye for now.", "지금은 안녕히 가세요."),
    "careless":      ("/ˈkɛərləs/", "형용사", "부주의한", "Don't be careless.", "부주의하지 마세요."),
    "collector":     ("/kəˈlɛktər/", "명사", "수집가", "Antique collector.", "골동품 수집가."),
    "conform":       ("/kənˈfɔːrm/", "동사", "따르다, 순응하다", "Conform to standards.", "기준에 따르세요."),
    "congestion":    ("/kənˈdʒɛstʃən/", "명사", "혼잡, 정체", "Traffic congestion.", "교통 혼잡."),
    "contradiction": ("/ˌkɒntrəˈdɪkʃən/", "명사", "모순", "A clear contradiction.", "명확한 모순."),
    "contrary":      ("/ˈkɒntrəri/", "형용사", "반대의, 대조적인", "On the contrary.", "반대로."),
    "diploma":       ("/dɪˈploʊmə/", "명사", "학위증, 졸업장", "High school diploma.", "고등학교 졸업장."),
    "distributor":   ("/dɪˈstrɪbjʊtər/", "명사", "유통업자", "Authorized distributor.", "공식 유통업자."),
    "dive":          ("/daɪv/", "동사", "뛰어들다, 다이빙하다", "Dive into the work.", "업무에 뛰어드세요."),
    "energetic":     ("/ˌɛnərˈdʒɛtɪk/", "형용사", "활기찬", "Energetic team.", "활기찬 팀."),
    "environmentally":("/ɪnˌvaɪrənˈmɛntəli/", "부사", "환경적으로", "Environmentally friendly.", "환경 친화적."),
    "escalator":     ("/ˈɛskəleɪtər/", "명사", "에스컬레이터", "Take the escalator.", "에스컬레이터를 타세요."),
    "exotic":        ("/ɪɡˈzɒtɪk/", "형용사", "이국적인", "Exotic destination.", "이국적인 목적지."),
    "fabric":        ("/ˈfæbrɪk/", "명사", "직물, 천", "Soft fabric.", "부드러운 직물."),
    "generalization":("/ˌdʒɛnərəlaɪˈzeɪʃən/", "명사", "일반화", "Avoid generalization.", "일반화를 피하세요."),
    "guidance":      ("/ˈɡaɪdəns/", "명사", "지도, 안내", "Career guidance.", "직업 안내."),
    "gum":           ("/ɡʌm/", "명사", "껌, 잇몸", "Chewing gum.", "껌."),
    "hesitant":      ("/ˈhɛzɪtənt/", "형용사", "망설이는", "Hesitant to speak.", "말하기를 망설이는."),
    "indicator":     ("/ˈɪndɪkeɪtər/", "명사", "지표", "Economic indicator.", "경제 지표."),
    "individually":  ("/ˌɪndɪˈvɪdʒuəli/", "부사", "개별적으로", "Address individually.", "개별적으로 다루세요."),
    "junior":        ("/ˈdʒuːniər/", "형용사", "하급의, 주니어의", "Junior employee.", "주니어 직원."),
    "lifestyle":     ("/ˈlaɪfstaɪl/", "명사", "생활 방식", "Healthy lifestyle.", "건강한 생활 방식."),
    "likewise":      ("/ˈlaɪkwaɪz/", "부사", "마찬가지로", "Likewise, I agree.", "마찬가지로 동의합니다."),
    "morale":        ("/məˈrɑːl/", "명사", "사기, 의욕", "Boost employee morale.", "직원 사기를 높이세요."),
    "orchestra":     ("/ˈɔːrkɪstrə/", "명사", "오케스트라", "Symphony orchestra.", "심포니 오케스트라."),
    "organizational":("/ˌɔːrɡənaɪˈzeɪʃənəl/", "형용사", "조직의", "Organizational skills.", "조직 능력."),
    "outlook":       ("/ˈaʊtlʊk/", "명사", "전망, 관점", "Positive outlook.", "긍정적인 전망."),
    "physics":       ("/ˈfɪzɪks/", "명사", "물리학", "Study physics.", "물리학을 공부하세요."),
    "pole":          ("/poʊl/", "명사", "장대, 극", "North Pole.", "북극."),
    "puzzle":        ("/ˈpʌzəl/", "명사", "퍼즐, 수수께끼", "Solve the puzzle.", "퍼즐을 푸세요."),
    "reflexive":     ("/rɪˈflɛksɪv/", "형용사", "반사적인, 재귀적인", "Reflexive response.", "반사적인 반응."),
    "snowy":         ("/ˈsnoʊi/", "형용사", "눈이 오는", "Snowy weather.", "눈이 오는 날씨."),
    "steak":         ("/steɪk/", "명사", "스테이크", "Order a steak.", "스테이크를 주문하세요."),
    "sticker":       ("/ˈstɪkər/", "명사", "스티커", "Put a sticker.", "스티커를 붙이세요."),
    "telecommunication":("/ˌtɛlɪkəˌmjuːnɪˈkeɪʃən/", "명사", "통신", "Telecommunication network.", "통신망."),
    "timely":        ("/ˈtaɪmli/", "형용사", "때 맞는, 시기 적절한", "Timely delivery.", "시기 적절한 배달."),
    "uncomfortable": ("/ʌnˈkʌmftəbəl/", "형용사", "불편한", "Uncomfortable chair.", "불편한 의자."),
    "amenity":       ("/əˈmiːnɪti/", "명사", "편의 시설", "Hotel amenities.", "호텔 편의 시설."),
    "approximate":   ("/əˈprɒksɪmɪt/", "형용사", "대략적인", "Approximate cost.", "대략적인 비용."),
    "await":         ("/əˈweɪt/", "동사", "기다리다, 기대하다", "Await the results.", "결과를 기다리세요."),
    "barbecue":      ("/ˈbɑːrbɪkjuː/", "명사", "바베큐", "Have a barbecue.", "바베큐를 하세요."),
    "beginner":      ("/bɪˈɡɪnər/", "명사", "초보자", "Suitable for beginners.", "초보자에게 적합한."),
    "biology":       ("/baɪˈɒlədʒi/", "명사", "생물학", "Biology class.", "생물학 수업."),
    "blanket":       ("/ˈblæŋkɪt/", "명사", "담요", "Warm blanket.", "따뜻한 담요."),
    "chairperson":   ("/ˈtʃɛərpɜːrsən/", "명사", "의장", "Board chairperson.", "이사회 의장."),
    "charitable":    ("/ˈtʃærɪtəbəl/", "형용사", "자선의", "Charitable organization.", "자선 단체."),
    "checkup":       ("/ˈtʃɛkʌp/", "명사", "건강 검진", "Annual checkup.", "연간 건강 검진."),
    "cooler":        ("/ˈkuːlər/", "명사", "냉각기, 아이스박스", "Pack food in the cooler.", "음식을 아이스박스에 넣으세요."),
    "crane":         ("/kreɪn/", "명사", "크레인, 두루미", "Construction crane.", "건설 크레인."),
    "dealership":    ("/ˈdiːlərʃɪp/", "명사", "대리점", "Car dealership.", "자동차 대리점."),
    "dependable":    ("/dɪˈpɛndəbəl/", "형용사", "믿을 수 있는", "Dependable service.", "믿을 수 있는 서비스."),
    "disconnect":    ("/ˌdɪskəˈnɛkt/", "동사", "연결을 끊다", "Disconnect the cable.", "케이블 연결을 끊으세요."),
    "dispose":       ("/dɪˈspoʊz/", "동사", "처분하다, 처리하다", "Dispose of waste.", "폐기물을 처리하세요."),
    "disrupt":       ("/dɪsˈrʌpt/", "동사", "방해하다, 혼란시키다", "Don't disrupt the meeting.", "회의를 방해하지 마세요."),
    "enthusiastically":("/ɪnˌθjuːziˈæstɪkli/", "부사", "열정적으로", "Respond enthusiastically.", "열정적으로 응답하세요."),
    "freelance":     ("/ˈfriːlɑːns/", "형용사", "프리랜서의", "Freelance work.", "프리랜서 작업."),
    "grill":         ("/ɡrɪl/", "동사", "그릴에 굽다", "Grill the chicken.", "닭고기를 그릴에 구우세요."),
    "habitual":      ("/həˈbɪtʃuəl/", "형용사", "습관적인", "Habitual behavior.", "습관적인 행동."),
    "internationally":("/ˌɪntərˈnæʃənəli/", "부사", "국제적으로", "Known internationally.", "국제적으로 알려진."),
    "invaluable":    ("/ɪnˈvæljuəbəl/", "형용사", "매우 귀중한", "Invaluable experience.", "매우 귀중한 경험."),
    "messenger":     ("/ˈmɛsɪndʒər/", "명사", "메신저, 심부름꾼", "Messenger service.", "메신저 서비스."),
    "paperback":     ("/ˈpeɪpərbæk/", "명사", "페이퍼백", "Buy the paperback.", "페이퍼백을 구매하세요."),
    "rebate":        ("/ˈriːbeɪt/", "명사", "환급금, 할인", "Mail-in rebate.", "우편 환급."),
    "recur":         ("/rɪˈkɜːr/", "동사", "재발하다", "The issue recurred.", "문제가 재발했다."),
    "reproduce":     ("/ˌriːprəˈdjuːs/", "동사", "복제하다, 번식하다", "Reproduce the document.", "문서를 복제하세요."),
    "spray":         ("/spreɪ/", "동사", "분무하다", "Spray water.", "물을 분무하세요."),
    "staple":        ("/ˈsteɪpəl/", "동사", "스테이플로 찍다", "Staple the papers.", "서류에 스테이플을 찍으세요."),
    "strategic":     ("/strəˈtiːdʒɪk/", "형용사", "전략적인", "Strategic planning.", "전략적 계획."),
    "stripe":        ("/straɪp/", "명사", "줄무늬", "Blue and white stripes.", "파랑과 흰 줄무늬."),
    "teen":          ("/tiːn/", "명사", "십 대", "Teen fashion.", "십 대 패션."),
    "tempt":         ("/tɛmpt/", "동사", "유혹하다", "Tempt with offers.", "제안으로 유혹하다."),
    "timer":         ("/ˈtaɪmər/", "명사", "타이머", "Set a timer.", "타이머를 설정하세요."),
    "unload":        ("/ʌnˈloʊd/", "동사", "내리다, 짐을 풀다", "Unload the truck.", "트럭을 내리세요."),
    "unusually":     ("/ʌnˈjuːʒuəli/", "부사", "특이하게", "Unusually cold.", "특이하게 춥다."),
    "vacate":        ("/vəˈkeɪt/", "동사", "비우다, 떠나다", "Vacate the room.", "방을 비우세요."),
    "whale":         ("/weɪl/", "명사", "고래", "See a whale.", "고래를 보다."),
    "wisely":        ("/ˈwaɪzli/", "부사", "현명하게", "Choose wisely.", "현명하게 선택하세요."),
    "amateur":       ("/ˈæmətər/", "명사", "아마추어", "Amateur photographer.", "아마추어 사진가."),
    "ambassador":    ("/æmˈbæsədər/", "명사", "대사", "Brand ambassador.", "브랜드 대사."),
    "anew":          ("/əˈnjuː/", "부사", "다시, 새로", "Start anew.", "새로 시작하세요."),
    "architectural": ("/ˌɑːrkɪˈtɛktʃərəl/", "형용사", "건축의", "Architectural design.", "건축 디자인."),
    "attain":        ("/əˈteɪn/", "동사", "달성하다, 얻다", "Attain success.", "성공을 달성하세요."),
    "balloon":       ("/bəˈluːn/", "명사", "풍선", "Blow up a balloon.", "풍선을 불어요."),
    "blueprint":     ("/ˈbluːprɪnt/", "명사", "청사진", "Review the blueprint.", "청사진을 검토하세요."),
    "bug":           ("/bʌɡ/", "명사", "버그, 곤충", "Fix the bug.", "버그를 수정하세요."),
    "cautious":      ("/ˈkɔːʃəs/", "형용사", "조심스러운", "Be cautious.", "조심하세요."),
    "circuit":       ("/ˈsɜːrkɪt/", "명사", "회로", "Short circuit.", "단락 회로."),
    "clap":          ("/klæp/", "동사", "박수 치다", "Clap your hands.", "박수를 치세요."),
    "commerce":      ("/ˈkɒmɜːrs/", "명사", "상업, 무역", "E-commerce.", "전자상거래."),
    "convey":        ("/kənˈveɪ/", "동사", "전달하다", "Convey the message.", "메시지를 전달하세요."),
    "cord":          ("/kɔːrd/", "명사", "코드, 끈", "Power cord.", "전원 코드."),
    "counselor":     ("/ˈkaʊnsələr/", "명사", "상담사", "Career counselor.", "진로 상담사."),
    "debit":         ("/ˈdɛbɪt/", "명사", "직불, 차변", "Debit card.", "직불 카드."),
    "delicate":      ("/ˈdɛlɪkɪt/", "형용사", "섬세한, 민감한", "Delicate situation.", "민감한 상황."),
    "dependence":    ("/dɪˈpɛndəns/", "명사", "의존", "Reduce dependence.", "의존도를 줄이세요."),
    "distraction":   ("/dɪˈstrækʃən/", "명사", "주의 분산", "Avoid distraction.", "주의 분산을 피하세요."),
    "downsize":      ("/ˈdaʊnsaɪz/", "동사", "축소하다", "Downsize the team.", "팀을 축소하세요."),
    "elephant":      ("/ˈɛlɪfənt/", "명사", "코끼리", "African elephant.", "아프리카 코끼리."),
    "enthusiasm":    ("/ɪnˈθjuːziæzəm/", "명사", "열정, 열의", "Show enthusiasm.", "열정을 보여주세요."),
    "enthusiast":    ("/ɪnˈθjuːziæst/", "명사", "열성가, 팬", "Car enthusiast.", "자동차 열성가."),
    "evident":       ("/ˈɛvɪdənt/", "형용사", "명백한, 분명한", "Evident improvement.", "명백한 개선."),
    "flexibility":   ("/ˌflɛksɪˈbɪlɪti/", "명사", "유연성", "Work flexibility.", "업무 유연성."),
    "flextime":      ("/ˈflɛkstaɪm/", "명사", "유연 근무제", "Flextime policy.", "유연 근무 정책."),
    "fortunately":   ("/ˈfɔːrtʃənɪtli/", "부사", "다행히도", "Fortunately, no one was hurt.", "다행히도 부상자가 없었다."),
    "freighter":     ("/ˈfreɪtər/", "명사", "화물선", "Cargo freighter.", "화물선."),
    "generator":     ("/ˈdʒɛnəreɪtər/", "명사", "발전기", "Backup generator.", "비상 발전기."),
    "hallway":       ("/ˈhɔːlweɪ/", "명사", "복도", "Wait in the hallway.", "복도에서 기다리세요."),
    "hamburger":     ("/ˈhæmbɜːrɡər/", "명사", "햄버거", "Order a hamburger.", "햄버거를 주문하세요."),
    "hazard":        ("/ˈhæzərd/", "명사", "위험, 위험 요소", "Fire hazard.", "화재 위험."),
    "homeowner":     ("/ˈhoʊmoʊnər/", "명사", "집주인", "Homeowner insurance.", "주택 보험."),
    "imperative":    ("/ɪmˈpɛrətɪv/", "형용사", "필수적인, 명령적인", "It is imperative.", "필수적이다."),
    "inflate":       ("/ɪnˈfleɪt/", "동사", "팽창시키다, 부풀리다", "Inflate the balloon.", "풍선을 부풀리세요."),
    "insert":        ("/ɪnˈsɜːrt/", "동사", "삽입하다", "Insert the card.", "카드를 삽입하세요."),
    "lecturer":      ("/ˈlɛktʃərər/", "명사", "강사", "Guest lecturer.", "초청 강사."),
    "memorize":      ("/ˈmɛməraɪz/", "동사", "암기하다", "Memorize the words.", "단어를 암기하세요."),
    "merchant":      ("/ˈmɜːrtʃənt/", "명사", "상인", "Online merchant.", "온라인 상인."),
    "occupant":      ("/ˈɒkjʊpənt/", "명사", "거주자", "Building occupants.", "건물 거주자."),
    "overcharge":    ("/ˌoʊvərˈtʃɑːrdʒ/", "동사", "과금하다", "Don't overcharge.", "과금하지 마세요."),
    "oversee":       ("/ˌoʊvərˈsiː/", "동사", "감독하다", "Oversee the project.", "프로젝트를 감독하세요."),
    "petition":      ("/pɪˈtɪʃən/", "명사", "청원", "Sign the petition.", "청원서에 서명하세요."),
    "pillow":        ("/ˈpɪloʊ/", "명사", "베개", "Soft pillow.", "부드러운 베개."),
    "popcorn":       ("/ˈpɒpkɔːrn/", "명사", "팝콘", "Movie night popcorn.", "영화의 밤 팝콘."),
    "pottery":       ("/ˈpɒtəri/", "명사", "도자기", "Pottery class.", "도자기 수업."),
    "professionally":("/prəˈfɛʃənəli/", "부사", "전문적으로", "Behave professionally.", "전문적으로 행동하세요."),
    "publicize":     ("/ˈpʌblɪsaɪz/", "동사", "홍보하다", "Publicize the event.", "행사를 홍보하세요."),
    "ray":           ("/reɪ/", "명사", "광선", "A ray of sunlight.", "햇살."),
    "redecorate":    ("/ˌriːˈdɛkəreɪt/", "동사", "재장식하다", "Redecorate the room.", "방을 재장식하세요."),
    "refinery":      ("/rɪˈfaɪnəri/", "명사", "정제소", "Oil refinery.", "석유 정제소."),
    "refresh":       ("/rɪˈfrɛʃ/", "동사", "새로 고침하다, 기분 전환하다", "Refresh the page.", "페이지를 새로 고침하세요."),
    "refundable":    ("/rɪˈfʌndəbəl/", "형용사", "환불 가능한", "Fully refundable.", "전액 환불 가능."),
    "reimbursement": ("/ˌriːɪmˈbɜːrsmənt/", "명사", "상환, 환급", "Expense reimbursement.", "비용 상환."),
    "reliability":   ("/rɪˌlaɪəˈbɪlɪti/", "명사", "신뢰성", "Service reliability.", "서비스 신뢰성."),
    "reluctant":     ("/rɪˈlʌktənt/", "형용사", "내키지 않는", "Reluctant to change.", "변화에 내키지 않는."),
    "sewer":         ("/ˈsoʊər/", "명사", "하수구", "Sewer pipe.", "하수관."),
    "skate":         ("/skeɪt/", "동사", "스케이트를 타다", "Skate on ice.", "얼음 위에서 스케이트를 타세요."),
    "skateboard":    ("/ˈskeɪtbɔːrd/", "명사", "스케이트보드", "Ride a skateboard.", "스케이트보드를 타세요."),
    "sleepy":        ("/ˈsliːpi/", "형용사", "졸린", "Feeling sleepy.", "졸리다."),
    "tailor":        ("/ˈteɪlər/", "명사", "재봉사", "Custom tailor.", "맞춤 재봉사."),
    "termination":   ("/ˌtɜːrmɪˈneɪʃən/", "명사", "종료, 해고", "Contract termination.", "계약 종료."),
    "theft":         ("/θɛft/", "명사", "도난, 절도", "Report theft.", "도난을 신고하세요."),
    "thunderstorm":  ("/ˈθʌndərstɔːrm/", "명사", "뇌우", "Severe thunderstorm.", "심한 뇌우."),
    "transmit":      ("/trænsˈmɪt/", "동사", "전송하다", "Transmit the data.", "데이터를 전송하세요."),
    "unused":        ("/ʌnˈjuːzd/", "형용사", "사용하지 않은", "Unused tickets.", "사용하지 않은 티켓."),
    "waive":         ("/weɪv/", "동사", "포기하다, 면제하다", "Waive the fee.", "수수료를 면제하다."),
    "yen":           ("/jɛn/", "명사", "엔화", "Pay in yen.", "엔화로 지불하세요."),
    "activate":      ("/ˈæktɪveɪt/", "동사", "활성화하다", "Activate the account.", "계정을 활성화하세요."),
    "additionally":  ("/əˈdɪʃənəli/", "부사", "추가적으로", "Additionally, include notes.", "추가적으로 메모를 포함하세요."),
    "affirmative":   ("/əˈfɜːrmətɪv/", "형용사", "긍정적인", "Affirmative answer.", "긍정적인 답변."),
    "baker":         ("/ˈbeɪkər/", "명사", "제빵사", "The baker made bread.", "제빵사가 빵을 만들었다."),
    "brainstorm":    ("/ˈbreɪnstɔːrm/", "동사", "브레인스토밍하다", "Brainstorm ideas.", "아이디어를 브레인스토밍하세요."),
    "cage":          ("/keɪdʒ/", "명사", "우리", "A bird cage.", "새장."),
    "cinema":        ("/ˈsɪnɪmə/", "명사", "영화관", "Go to the cinema.", "영화관에 가세요."),
    "collaboration": ("/kəˌlæbəˈreɪʃən/", "명사", "협력, 협업", "Team collaboration.", "팀 협업."),
    "condominium":   ("/ˌkɒndəˈmɪniəm/", "명사", "콘도미니엄", "Buy a condominium.", "콘도미니엄을 구매하세요."),
    "consecutive":   ("/kənˈsɛkjʊtɪv/", "형용사", "연속적인", "Consecutive wins.", "연속 우승."),
    "cordless":      ("/ˈkɔːrdləs/", "형용사", "무선의", "Cordless phone.", "무선 전화기."),
    "deluxe":        ("/dɪˈlʌks/", "형용사", "고급의", "Deluxe suite.", "고급 스위트룸."),
    "desirable":     ("/dɪˈzaɪərəbəl/", "형용사", "바람직한", "Desirable outcome.", "바람직한 결과."),
    "discrepancy":   ("/dɪˈskrɛpənsi/", "명사", "불일치, 차이", "Discrepancy in accounts.", "계좌 불일치."),
    "dispatch":      ("/dɪˈspætʃ/", "동사", "발송하다", "Dispatch the order.", "주문을 발송하세요."),
    "drawback":      ("/ˈdrɔːbæk/", "명사", "단점, 결점", "One drawback is cost.", "한 가지 단점은 비용이다."),
    "dull":          ("/dʌl/", "형용사", "지루한, 흐린", "A dull day.", "지루한 날."),
    "evenly":        ("/ˈiːvənli/", "부사", "고르게", "Spread evenly.", "고르게 펴세요."),
    "excellence":    ("/ˈɛksələns/", "명사", "우수함", "Excellence award.", "우수상."),
    "exclusively":   ("/ɪkˈskluːsɪvli/", "부사", "독점적으로", "Exclusively available.", "독점적으로 이용 가능."),
    "farewell":      ("/ˌfɛərˈwɛl/", "명사", "작별, 이별", "Farewell party.", "작별 파티."),
    "fatigue":       ("/fəˈtiːɡ/", "명사", "피로", "Mental fatigue.", "정신적 피로."),
    "fiscal":        ("/ˈfɪskəl/", "형용사", "재정의", "Fiscal year.", "회계 연도."),
    "fleet":         ("/fliːt/", "명사", "함대, 차량", "Delivery fleet.", "배달 차량."),
    "flour":         ("/flaʊər/", "명사", "밀가루", "Add flour.", "밀가루를 넣으세요."),
    "fog":           ("/fɒɡ/", "명사", "안개", "Thick fog.", "짙은 안개."),
    "formally":      ("/ˈfɔːrmli/", "부사", "공식적으로", "Formally announce.", "공식적으로 발표하세요."),
    "gram":          ("/ɡræm/", "명사", "그램", "100 grams.", "100그램."),
    "handbook":      ("/ˈhændbʊk/", "명사", "핸드북, 안내서", "Employee handbook.", "직원 안내서."),
    "headphone":     ("/ˈhɛdfoʊn/", "명사", "헤드폰", "Wireless headphones.", "무선 헤드폰."),
    "heater":        ("/ˈhiːtər/", "명사", "히터", "Turn on the heater.", "히터를 켜세요."),
    "helmet":        ("/ˈhɛlmɪt/", "명사", "헬멧", "Wear a helmet.", "헬멧을 쓰세요."),
    "hiker":         ("/ˈhaɪkər/", "명사", "하이커", "Mountain hiker.", "산악 하이커."),
    "homeless":      ("/ˈhoʊmləs/", "형용사", "노숙자의", "Help the homeless.", "노숙자를 도우세요."),
    "lighter":       ("/ˈlaɪtər/", "명사", "라이터", "Use a lighter.", "라이터를 사용하세요."),
    "loudly":        ("/ˈlaʊdli/", "부사", "크게, 큰 소리로", "Speak loudly.", "크게 말하세요."),
    "loyalty":       ("/ˈlɔɪəlti/", "명사", "충성도, 충성심", "Customer loyalty.", "고객 충성도."),
    "microwave":     ("/ˈmaɪkrəweɪv/", "명사", "전자레인지", "Heat in the microwave.", "전자레인지에 데우세요."),
    "misidentify":   ("/ˌmɪsaɪˈdɛntɪfaɪ/", "동사", "잘못 인식하다", "Don't misidentify.", "잘못 인식하지 마세요."),
    "neat":          ("/niːt/", "형용사", "깔끔한", "Neat handwriting.", "깔끔한 필체."),
    "nomination":    ("/ˌnɒmɪˈneɪʃən/", "명사", "지명, 추천", "Award nomination.", "시상 후보 지명."),
    "officially":    ("/əˈfɪʃəli/", "부사", "공식적으로", "Officially announced.", "공식적으로 발표됐다."),
    "outfit":        ("/ˈaʊtfɪt/", "명사", "옷차림, 의상", "Casual outfit.", "캐주얼 의상."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT13:
                    pron, pos, meaning, ex_en, ex_ko = DICT13[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more13.py ===\n")
    patch_files()
