#!/usr/bin/env python3
"""Fifth-pass fill: freq-L4 remaining (179) + TOEIC-L1 remaining (68)."""
import json, glob

DICT5 = {
    # =========================================================
    # freq-L4 remaining (179)
    # =========================================================
    "property":    ("/ˈprɒpərti/", "명사", "재산, 부동산", "This is private property.", "이것은 사유 재산입니다."),
    "previous":    ("/ˈpriːviəs/", "형용사", "이전의, 앞의", "Check the previous page.", "이전 페이지를 확인하세요."),
    "dark":        ("/dɑːrk/", "형용사", "어두운, 암흑의", "It gets dark early in winter.", "겨울에는 일찍 어두워집니다."),
    "okay":        ("/ˌoʊˈkeɪ/", "형용사", "괜찮은, 좋은", "Is everything okay?", "모든 것이 괜찮나요?"),
    "earn":        ("/ɜːrn/", "동사", "벌다, 얻다", "She earns a good salary.", "그녀는 좋은 급여를 받습니다."),
    "daughter":    ("/ˈdɔːtər/", "명사", "딸", "His daughter is a doctor.", "그의 딸은 의사입니다."),
    "post":        ("/poʊst/", "명사", "게시물, 우편", "Post this on the board.", "이것을 게시판에 올리세요."),
    "define":      ("/dɪˈfaɪn/", "동사", "정의하다", "Please define the term.", "그 용어를 정의해 주세요."),
    "conclusion":  ("/kənˈkluːʒən/", "명사", "결론", "What is your conclusion?", "결론이 무엇인가요?"),
    "clock":       ("/klɒk/", "명사", "시계", "Check the clock.", "시계를 확인하세요."),
    "everybody":   ("/ˈɛvriˌbɒdi/", "대명사", "모든 사람", "Everybody is welcome.", "모든 사람을 환영합니다."),
    "weekend":     ("/ˈwiːkɛnd/", "명사", "주말", "What are you doing this weekend?", "이번 주말에 무엇을 하실 예정인가요?"),
    "perform":     ("/pərˈfɔːrm/", "동사", "수행하다, 공연하다", "She will perform tonight.", "그녀는 오늘 밤 공연을 합니다."),
    "mine":        ("/maɪn/", "대명사", "나의 것", "That car is mine.", "저 자동차는 제 것입니다."),
    "debate":      ("/dɪˈbeɪt/", "명사", "토론, 논쟁", "The debate was heated.", "토론이 뜨거웠습니다."),
    "memory":      ("/ˈmɛməri/", "명사", "기억, 메모리", "I have good memories of childhood.", "어린 시절의 좋은 기억이 있습니다."),
    "green":       ("/ɡriːn/", "형용사", "초록색의, 친환경적인", "Go green for the environment.", "환경을 위해 친환경적으로 사세요."),
    "song":        ("/sɒŋ/", "명사", "노래", "She sang a beautiful song.", "그녀는 아름다운 노래를 불렀습니다."),
    "object":      ("/ˈɒbdʒɪkt/", "명사", "물체, 목적어", "What is this object?", "이 물체가 무엇인가요?"),
    "credit":      ("/ˈkrɛdɪt/", "명사", "신용, 공적", "She deserves the credit.", "그녀가 공을 인정받아야 합니다."),
    "ring":        ("/rɪŋ/", "명사", "반지, 울림", "She wears a diamond ring.", "그녀는 다이아몬드 반지를 낍니다."),
    "discover":    ("/dɪˈskʌvər/", "동사", "발견하다", "She discovered a new method.", "그녀는 새로운 방법을 발견했습니다."),
    "dead":        ("/dɛd/", "형용사", "죽은, 사망한", "The battery is dead.", "배터리가 다 됐습니다."),
    "afternoon":   ("/ˌɑːftərˈnuːn/", "명사", "오후", "Good afternoon!", "안녕하세요!(오후 인사)"),
    "extend":      ("/ɪkˈstɛnd/", "동사", "연장하다, 늘리다", "We need to extend the deadline.", "마감 기한을 연장해야 합니다."),
    "possibility": ("/ˌpɒsɪˈbɪlɪti/", "명사", "가능성", "There is a possibility.", "가능성이 있습니다."),
    "facility":    ("/fəˈsɪlɪti/", "명사", "시설, 편의 시설", "The facility is excellent.", "시설이 훌륭합니다."),
    "variety":     ("/vəˈraɪɪti/", "명사", "다양성, 종류", "There is a great variety.", "다양성이 풍부합니다."),
    "daily":       ("/ˈdeɪli/", "형용사", "매일의, 일상적인", "Daily exercise is important.", "매일 운동이 중요합니다."),
    "clothes":     ("/kloʊðz/", "명사", "옷, 의류", "She bought new clothes.", "그녀는 새 옷을 샀습니다."),
    "screen":      ("/skriːn/", "명사", "화면, 스크린", "The screen is too bright.", "화면이 너무 밝습니다."),
    "track":       ("/træk/", "명사", "경로, 트랙", "Stay on track.", "경로를 유지하세요."),
    "dance":       ("/dɑːns/", "동사", "춤추다", "She loves to dance.", "그녀는 춤추는 것을 좋아합니다."),
    "completely":  ("/kəmˈpliːtli/", "부사", "완전히, 전혀", "I completely agree.", "완전히 동의합니다."),
    "female":      ("/ˈfiːmeɪl/", "형용사", "여성의, 암컷의", "The female students excelled.", "여학생들이 뛰어났습니다."),
    "original":    ("/əˈrɪdʒɪnəl/", "형용사", "원래의, 독창적인", "This is the original version.", "이것이 원본입니다."),
    "sister":      ("/ˈsɪstər/", "명사", "언니/누나/여동생", "My sister is a teacher.", "제 언니는 선생님입니다."),
    "rock":        ("/rɒk/", "명사", "바위, 돌", "The rock is heavy.", "바위가 무겁습니다."),
    "dream":       ("/driːm/", "명사", "꿈", "Follow your dreams.", "꿈을 좇으세요."),
    "nor":         ("/nɔːr/", "접속사", "~도 아니다", "Neither here nor there.", "여기도 저기도 아닙니다."),
    "easily":      ("/ˈiːzɪli/", "부사", "쉽게, 수월하게", "She learned easily.", "그녀는 쉽게 배웠습니다."),
    "agency":      ("/ˈeɪdʒənsi/", "명사", "기관, 대리점", "Contact the agency.", "기관에 연락하세요."),
    "dollar":      ("/ˈdɒlər/", "명사", "달러", "It costs five dollars.", "5달러입니다."),
    "garden":      ("/ˈɡɑːrdən/", "명사", "정원", "She grows flowers in her garden.", "그녀는 정원에서 꽃을 기릅니다."),
    "fix":         ("/fɪks/", "동사", "고치다, 해결하다", "Can you fix this?", "이것을 고칠 수 있나요?"),
    "ahead":       ("/əˈhɛd/", "부사", "앞에, 앞으로", "Go ahead.", "앞으로 가세요."),
    "cross":       ("/krɒs/", "동사", "건너다, 교차하다", "Cross the street carefully.", "조심스럽게 길을 건너세요."),
    "yeah":        ("/jɛə/", "부사", "응, 맞아", "Yeah, that's right.", "응, 맞아요."),
    "weight":      ("/weɪt/", "명사", "무게, 체중", "Lose some weight.", "체중을 줄이세요."),
    "legal":       ("/ˈliːɡəl/", "형용사", "법적인, 합법적인", "Is this legal?", "이것이 합법인가요?"),
    "proposal":    ("/prəˈpoʊzəl/", "명사", "제안, 청혼", "She submitted a proposal.", "그녀는 제안서를 제출했습니다."),
    "version":     ("/ˈvɜːrʃən/", "명사", "버전, 판", "Download the latest version.", "최신 버전을 다운로드하세요."),
    "conversation":("/ˌkɒnvərˈseɪʃən/", "명사", "대화, 회화", "We had a good conversation.", "우리는 좋은 대화를 나눴습니다."),
    "somebody":    ("/ˈsʌmbɒdi/", "대명사", "누군가, 어떤 사람", "Somebody left a message.", "누군가가 메시지를 남겼습니다."),
    "pound":       ("/paʊnd/", "명사", "파운드(화폐/무게)", "It weighs five pounds.", "5파운드 무게입니다."),
    "shape":       ("/ʃeɪp/", "명사", "형태, 모양", "What shape is it?", "형태가 어떻게 생겼나요?"),
    "sea":         ("/siː/", "명사", "바다, 해", "The sea is calm today.", "오늘 바다가 잔잔합니다."),
    "immediately": ("/ɪˈmiːdiətli/", "부사", "즉시, 당장", "Please respond immediately.", "즉시 응답해 주세요."),
    "welcome":     ("/ˈwɛlkəm/", "동사", "환영하다", "Welcome to our company.", "우리 회사에 오신 것을 환영합니다."),
    "smile":       ("/smaɪl/", "동사", "미소 짓다", "Always smile.", "항상 미소를 지으세요."),
    "communication":("/kəˌmjuːnɪˈkeɪʃən/", "명사", "소통, 의사소통", "Good communication is key.", "좋은 소통이 핵심입니다."),
    "agent":       ("/ˈeɪdʒənt/", "명사", "대리인, 요원", "Contact your agent.", "대리인에게 연락하세요."),
    "traditional": ("/trəˈdɪʃənəl/", "형용사", "전통적인", "Traditional food is delicious.", "전통 음식이 맛있습니다."),
    "judge":       ("/dʒʌdʒ/", "명사", "판사, 심사위원", "The judge made a decision.", "판사가 결정을 내렸습니다."),
    "herself":     ("/hɜːrˈsɛlf/", "대명사", "그녀 자신", "She did it herself.", "그녀 혼자 했습니다."),
    "generation":  ("/ˌdʒɛnəˈreɪʃən/", "명사", "세대, 발생", "The younger generation.", "젊은 세대."),
    "estimate":    ("/ˈɛstɪmɪt/", "명사", "추정, 견적", "Give me an estimate.", "견적을 내주세요."),
    "favorite":    ("/ˈfeɪvərɪt/", "형용사", "가장 좋아하는", "What is your favorite food?", "가장 좋아하는 음식이 무엇인가요?"),
    "difficulty":  ("/ˈdɪfɪkəlti/", "명사", "어려움, 곤란", "The difficulty is manageable.", "어려움은 관리할 수 있습니다."),
    "shoot":       ("/ʃuːt/", "동사", "쏘다, 촬영하다", "Shoot the ball!", "공을 쏘세요!"),
    "announce":    ("/əˈnaʊns/", "동사", "발표하다, 공표하다", "We will announce the results.", "결과를 발표할 것입니다."),
    "unless":      ("/ənˈlɛs/", "접속사", "~하지 않으면", "Unless you hurry, you'll be late.", "서두르지 않으면 늦을 것입니다."),
    "independent": ("/ˌɪndɪˈpɛndənt/", "형용사", "독립적인", "She is independent.", "그녀는 독립적입니다."),
    "recommend":   ("/ˌrɛkəˈmɛnd/", "동사", "추천하다", "I recommend this book.", "이 책을 추천합니다."),
    "survey":      ("/ˈsɜːrveɪ/", "명사", "설문조사, 조사", "Please fill out the survey.", "설문조사를 작성해 주세요."),
    "majority":    ("/məˈdʒɒrɪti/", "명사", "대다수, 과반수", "The majority agreed.", "대다수가 동의했습니다."),
    "stick":       ("/stɪk/", "동사", "붙다, 고수하다", "Stick to the plan.", "계획을 고수하세요."),
    "request":     ("/rɪˈkwɛst/", "명사", "요청, 부탁", "Please send a request.", "요청을 보내 주세요."),
    "rich":        ("/rɪtʃ/", "형용사", "부유한, 풍부한", "He is a rich man.", "그는 부유한 사람입니다."),
    "wind":        ("/wɪnd/", "명사", "바람", "The wind is strong today.", "오늘 바람이 강합니다."),
    "none":        ("/nʌn/", "대명사", "아무것도 없는", "None of them came.", "그들 중 아무도 오지 않았습니다."),
    "exchange":    ("/ɪksˈtʃeɪndʒ/", "동사", "교환하다", "Can I exchange this?", "이것을 교환할 수 있나요?"),
    "famous":      ("/ˈfeɪməs/", "형용사", "유명한, 저명한", "She is a famous singer.", "그녀는 유명한 가수입니다."),
    "blood":       ("/blʌd/", "명사", "피, 혈액", "Blood is thicker than water.", "피는 물보다 진합니다."),
    "appropriate": ("/əˈproʊpriɪt/", "형용사", "적절한, 적합한", "This is not appropriate.", "이것은 적절하지 않습니다."),
    "block":       ("/blɒk/", "명사", "블록, 구획", "Walk one block north.", "북쪽으로 한 블록 걸으세요."),
    "warm":        ("/wɔːrm/", "형용사", "따뜻한", "The weather is warm.", "날씨가 따뜻합니다."),
    "count":       ("/kaʊnt/", "동사", "세다, 중요하다", "Every vote counts.", "모든 표가 중요합니다."),
    "scene":       ("/siːn/", "명사", "장면, 현장", "It was a beautiful scene.", "아름다운 장면이었습니다."),
    "writer":      ("/ˈraɪtər/", "명사", "작가, 작사가", "She is a professional writer.", "그녀는 전문 작가입니다."),
    "content":     ("/ˈkɒntɛnt/", "명사", "내용, 콘텐츠", "The content is excellent.", "내용이 훌륭합니다."),
    "safe":        ("/seɪf/", "형용사", "안전한", "This area is safe.", "이 지역은 안전합니다."),
    "invite":      ("/ɪnˈvaɪt/", "동사", "초대하다", "I'd like to invite you.", "당신을 초대하고 싶습니다."),
    "mix":         ("/mɪks/", "동사", "섞다, 혼합하다", "Mix the ingredients.", "재료를 섞으세요."),
    "element":     ("/ˈɛlɪmənt/", "명사", "요소, 원소", "This is a key element.", "이것은 핵심 요소입니다."),
    "effective":   ("/ɪˈfɛktɪv/", "형용사", "효과적인, 유효한", "This method is very effective.", "이 방법은 매우 효과적입니다."),
    "correct":     ("/kəˈrɛkt/", "형용사", "올바른, 정확한", "Your answer is correct.", "답이 맞습니다."),
    "beat":        ("/biːt/", "동사", "이기다, 때리다", "They beat the record.", "그들은 기록을 깼습니다."),
    "telephone":   ("/ˈtɛlɪfoʊn/", "명사", "전화기", "Answer the telephone.", "전화를 받으세요."),
    "copy":        ("/ˈkɒpi/", "명사", "사본, 복사", "Make a copy of this.", "이것의 사본을 만드세요."),
    "committee":   ("/kəˈmɪti/", "명사", "위원회", "The committee approved it.", "위원회가 승인했습니다."),
    "advice":      ("/ədˈvaɪs/", "명사", "조언, 충고", "May I give you some advice?", "조언을 드려도 될까요?"),
    "handle":      ("/ˈhændəl/", "동사", "다루다, 처리하다", "I can handle it.", "처리할 수 있습니다."),
    "glass":       ("/ɡlɑːs/", "명사", "유리, 안경", "Please pass the glass.", "유리잔을 건네 주세요."),
    "trial":       ("/ˈtraɪəl/", "명사", "시험, 재판", "It's a free trial.", "무료 체험판입니다."),
    "stress":      ("/strɛs/", "명사", "스트레스, 강세", "Try to reduce stress.", "스트레스를 줄이려고 노력하세요."),
    "radio":       ("/ˈreɪdioʊ/", "명사", "라디오", "I listen to the radio.", "라디오를 듣습니다."),
    "administration":("/ədˌmɪnɪˈstreɪʃən/", "명사", "행정, 경영", "The administration approved.", "행정부가 승인했습니다."),
    "text":        ("/tɛkst/", "명사", "문자, 텍스트", "Send me a text.", "문자 메시지를 보내 주세요."),
    "context":     ("/ˈkɒntɛkst/", "명사", "맥락, 문맥", "Read in context.", "맥락 속에서 읽으세요."),
    "ride":        ("/raɪd/", "동사", "타다, 이동하다", "Let's ride the bus.", "버스를 타자."),
    "directly":    ("/dɪˈrɛktli/", "부사", "직접적으로, 곧장", "Contact us directly.", "저희에게 직접 연락하세요."),
    "heavy":       ("/ˈhɛvi/", "형용사", "무거운, 심한", "The bag is very heavy.", "가방이 매우 무겁습니다."),
    "remove":      ("/rɪˈmuːv/", "동사", "제거하다, 없애다", "Remove all obstacles.", "모든 장애물을 제거하세요."),
    "conduct":     ("/ˈkɒndʌkt/", "명사", "행동, 수행", "Good conduct is expected.", "좋은 행동이 기대됩니다."),
    "equipment":   ("/ɪˈkwɪpmənt/", "명사", "장비, 설비", "Check the equipment.", "장비를 확인하세요."),
    "otherwise":   ("/ˈʌðərwaɪz/", "부사", "그렇지 않으면, 달리", "Otherwise, we'll be late.", "그렇지 않으면 늦을 것입니다."),
    "title":       ("/ˈtaɪtəl/", "명사", "제목, 칭호", "What is the title?", "제목이 무엇인가요?"),
    "extra":       ("/ˈɛkstrə/", "형용사", "추가의, 여분의", "I need an extra copy.", "사본이 하나 더 필요합니다."),
    "executive":   ("/ɪɡˈzɛkjətɪv/", "명사", "임원, 간부", "She is a senior executive.", "그녀는 고위 임원입니다."),
    "chair":       ("/tʃɛər/", "명사", "의자, 위원장", "Please take a chair.", "의자를 가져가세요."),
    "expensive":   ("/ɪkˈspɛnsɪv/", "형용사", "비싼, 고가의", "That watch is expensive.", "저 시계는 비쌉니다."),
    "sample":      ("/ˈsɑːmpəl/", "명사", "샘플, 견본", "Try a free sample.", "무료 샘플을 사용해 보세요."),
    "deliver":     ("/dɪˈlɪvər/", "동사", "배달하다, 전달하다", "We deliver within 2 days.", "2일 이내에 배달합니다."),
    "video":       ("/ˈvɪdioʊ/", "명사", "비디오, 영상", "Watch the video.", "영상을 보세요."),
    "connection":  ("/kəˈnɛkʃən/", "명사", "연결, 관계", "There is a strong connection.", "강한 연결이 있습니다."),
    "primary":     ("/ˈpraɪməri/", "형용사", "주요한, 기본적인", "Primary education is important.", "초등 교육이 중요합니다."),
    "weather":     ("/ˈwɛðər/", "명사", "날씨", "The weather is nice.", "날씨가 좋습니다."),
    "inform":      ("/ɪnˈfɔːrm/", "동사", "알리다, 통보하다", "Please inform me of changes.", "변경 사항을 알려 주세요."),
    "principle":   ("/ˈprɪnsɪpəl/", "명사", "원칙, 원리", "Follow the principles.", "원칙을 따르세요."),
    "straight":    ("/streɪt/", "형용사", "직선의, 곧은", "Go straight ahead.", "직진하세요."),
    "appeal":      ("/əˈpiːl/", "동사", "호소하다, 매력적이다", "The design appeals to me.", "디자인이 마음에 듭니다."),
    "highly":      ("/ˈhaɪli/", "부사", "매우, 높이", "I highly recommend it.", "강력히 추천합니다."),
    "trust":       ("/trʌst/", "명사", "신뢰, 믿음", "Trust is important.", "신뢰가 중요합니다."),
    "wonderful":   ("/ˈwʌndərfəl/", "형용사", "훌륭한, 멋진", "What a wonderful day!", "정말 멋진 날이네요!"),
    "flat":        ("/flæt/", "형용사", "평평한, 단조로운", "The road is flat.", "도로가 평평합니다."),
    "absolutely":  ("/ˈæbsəluːtli/", "부사", "완전히, 전혀", "I absolutely agree.", "완전히 동의합니다."),
    "flow":        ("/floʊ/", "동사", "흐르다", "The water flows smoothly.", "물이 부드럽게 흐릅니다."),
    "fair":        ("/fɛər/", "형용사", "공정한, 적당한", "That's fair.", "그것은 공정합니다."),
    "farm":        ("/fɑːrm/", "명사", "농장", "She grew up on a farm.", "그녀는 농장에서 자랐습니다."),
    "collection":  ("/kəˈlɛkʃən/", "명사", "수집, 컬렉션", "She has a book collection.", "그녀는 책 컬렉션을 가지고 있습니다."),
    "hang":        ("/hæŋ/", "동사", "걸다, 매달다", "Hang the picture on the wall.", "그림을 벽에 걸으세요."),
    "band":        ("/bænd/", "명사", "밴드, 그룹", "The band played great music.", "밴드가 훌륭한 음악을 연주했습니다."),
    "relative":    ("/ˈrɛlətɪv/", "명사", "친척, 친족", "She visited her relatives.", "그녀는 친척들을 방문했습니다."),
    "tour":        ("/tʊər/", "명사", "여행, 투어", "Take a guided tour.", "가이드 투어를 하세요."),
    "alternative": ("/ɔːlˈtɜːrnətɪv/", "명사", "대안, 선택지", "Is there an alternative?", "대안이 있나요?"),
    "software":    ("/ˈsɒftweər/", "명사", "소프트웨어", "Install the software.", "소프트웨어를 설치하세요."),
    "pair":        ("/pɛər/", "명사", "한 쌍, 짝", "A pair of shoes.", "신발 한 켤레."),
    "ship":        ("/ʃɪp/", "명사", "배, 선박", "The ship arrived.", "배가 도착했습니다."),
    "attitude":    ("/ˈætɪtjuːd/", "명사", "태도, 자세", "Have a positive attitude.", "긍정적인 태도를 가지세요."),
    "cheap":       ("/tʃiːp/", "형용사", "저렴한, 싼", "This is cheap.", "이것은 저렴합니다."),
    "double":      ("/ˈdʌbəl/", "형용사", "두 배의, 이중의", "I'd like a double room.", "더블룸을 원합니다."),
    "leg":         ("/lɛɡ/", "명사", "다리", "She has a sore leg.", "다리가 아픕니다."),
    "observe":     ("/əbˈzɜːrv/", "동사", "관찰하다", "Observe and learn.", "관찰하고 배우세요."),
    "sentence":    ("/ˈsɛntəns/", "명사", "문장, 형벌", "Write a complete sentence.", "완전한 문장을 쓰세요."),
    "print":       ("/prɪnt/", "동사", "인쇄하다", "Print this document.", "이 문서를 인쇄하세요."),
    "progress":    ("/ˈprɒɡrɛs/", "명사", "진전, 발전", "We are making progress.", "진전을 이루고 있습니다."),
    "truth":       ("/truːθ/", "명사", "진실, 사실", "Tell the truth.", "진실을 말하세요."),
    "nobody":      ("/ˈnoʊˌbɒdi/", "대명사", "아무도 ~않다", "Nobody knows.", "아무도 모릅니다."),
    "examine":     ("/ɪɡˈzæmɪn/", "동사", "검사하다, 살피다", "Please examine the document.", "문서를 검토해 주세요."),
    "lay":         ("/leɪ/", "동사", "놓다, 눕히다", "Lay the book on the table.", "책을 테이블에 놓으세요."),
    "speed":       ("/spiːd/", "명사", "속도", "Drive at a safe speed.", "안전한 속도로 운전하세요."),
    "politics":    ("/ˈpɒlɪtɪks/", "명사", "정치", "She is interested in politics.", "그녀는 정치에 관심이 있습니다."),
    "reply":       ("/rɪˈplaɪ/", "동사", "답하다, 회신하다", "Please reply soon.", "빨리 회신해 주세요."),
    "display":     ("/dɪˈspleɪ/", "동사", "표시하다, 전시하다", "Display the information.", "정보를 표시하세요."),
    "perfect":     ("/ˈpɜːrfɪkt/", "형용사", "완벽한", "That's perfect!", "완벽합니다!"),
    "slightly":    ("/ˈslaɪtli/", "부사", "약간, 조금", "It's slightly warmer today.", "오늘 약간 더 따뜻합니다."),
    "overall":     ("/ˌoʊvərˈɔːl/", "형용사", "전반적인, 전체적인", "The overall result is good.", "전반적인 결과가 좋습니다."),
    "intend":      ("/ɪnˈtɛnd/", "동사", "의도하다, ~할 작정이다", "What do you intend to do?", "무엇을 하려고 합니까?"),
    "user":        ("/ˈjuːzər/", "명사", "사용자, 유저", "The user is satisfied.", "사용자가 만족합니다."),
    "respond":     ("/rɪˈspɒnd/", "동사", "반응하다, 응답하다", "Please respond promptly.", "신속하게 응답해 주세요."),
    "dinner":      ("/ˈdɪnər/", "명사", "저녁 식사", "What's for dinner?", "저녁 메뉴가 무엇인가요?"),
    "slow":        ("/sloʊ/", "형용사", "느린, 천천히", "Drive slow in this area.", "이 구역에서는 천천히 운전하세요."),
    "regular":     ("/ˈrɛɡjələr/", "형용사", "정기적인, 규칙적인", "Attend regular meetings.", "정기 회의에 참석하세요."),
    "apart":       ("/əˈpɑːrt/", "부사", "떨어져, 별도로", "Set it apart from the rest.", "나머지와 구별하세요."),
    "suit":        ("/suːt/", "명사", "정장, 소송", "He wore a business suit.", "그는 정장을 입었습니다."),
    "federal":     ("/ˈfɛdərəl/", "형용사", "연방의", "This is a federal law.", "이것은 연방 법입니다."),
    "reveal":      ("/rɪˈviːl/", "동사", "드러내다, 밝히다", "Reveal the truth.", "진실을 밝히세요."),
    # =========================================================
    # TOEIC-L1 remaining (68)
    # =========================================================
    "oval":        ("/ˈoʊvəl/", "형용사", "타원형의", "The oval mirror is beautiful.", "타원형 거울이 아름답습니다."),
    "contradict":  ("/ˌkɒntrəˈdɪkt/", "동사", "모순되다, 반박하다", "Your actions contradict your words.", "행동이 말과 모순됩니다."),
    "inference":   ("/ˈɪnfərəns/", "명사", "추론, 추정", "Draw an inference.", "추론을 도출하세요."),
    "compact":     ("/ˈkɒmpækt/", "형용사", "소형의, 간결한", "I prefer a compact car.", "소형차를 선호합니다."),
    "precede":     ("/prɪˈsiːd/", "동사", "앞서다, 선행하다", "Please precede me.", "먼저 가세요."),
    "replacement": ("/rɪˈpleɪsmənt/", "명사", "교체, 대체품", "We need a replacement.", "교체품이 필요합니다."),
    "cabinet":     ("/ˈkæbɪnɪt/", "명사", "캐비닛, 내각", "The files are in the cabinet.", "파일은 캐비닛에 있습니다."),
    "explanatory": ("/ɪkˈsplænətɔːri/", "형용사", "설명적인", "Read the explanatory notes.", "설명 노트를 읽으세요."),
    "media":       ("/ˈmiːdiə/", "명사", "미디어, 매체", "The media reported the news.", "미디어가 뉴스를 보도했습니다."),
    "underline":   ("/ˌʌndərˈlaɪn/", "동사", "밑줄 긋다, 강조하다", "Underline the key words.", "핵심 단어에 밑줄을 그으세요."),
    "electrical":  ("/ɪˈlɛktrɪkəl/", "형용사", "전기의", "There is an electrical problem.", "전기 문제가 있습니다."),
    "airplane":    ("/ˈɛərpleɪn/", "명사", "비행기", "The airplane lands at 3 PM.", "비행기는 오후 3시에 착륙합니다."),
    "attendee":    ("/ˌætɛnˈdiː/", "명사", "참석자", "Each attendee will receive a badge.", "각 참석자는 배지를 받을 것입니다."),
    "birthday":    ("/ˈbɜːrθdeɪ/", "명사", "생일", "Happy birthday!", "생일 축하합니다!"),
    "café":        ("/kæˈfeɪ/", "명사", "카페", "Let's meet at the café.", "카페에서 만나자."),
    "comprehension":("/ˌkɒmprɪˈhɛnʃən/", "명사", "이해, 독해", "Reading comprehension is important.", "독해가 중요합니다."),
    "sandwich":    ("/ˈsænwɪdʒ/", "명사", "샌드위치", "I'll have a sandwich.", "샌드위치를 먹겠습니다."),
    "mini":        ("/ˈmɪni/", "형용사", "소형의, 미니", "Get the mini version.", "미니 버전을 구매하세요."),
    "inconvenience":("/ˌɪnkənˈviːniəns/", "명사", "불편함", "We apologize for any inconvenience.", "불편을 드려 죄송합니다."),
    "banquet":     ("/ˈbæŋkwɪt/", "명사", "연회, 만찬", "The banquet starts at 7.", "연회는 7시에 시작합니다."),
    "closet":      ("/ˈklɒzɪt/", "명사", "옷장", "Hang it in the closet.", "옷장에 걸어 두세요."),
    "folder":      ("/ˈfoʊldər/", "명사", "폴더", "Save it in the correct folder.", "올바른 폴더에 저장하세요."),
    "photocopy":   ("/ˈfoʊtəkɒpi/", "동사", "복사하다", "Photocopy the document.", "문서를 복사하세요."),
    "renovate":    ("/ˈrɛnəveɪt/", "동사", "보수하다, 개조하다", "We plan to renovate the office.", "사무실을 개조할 계획입니다."),
    "sunny":       ("/ˈsʌni/", "형용사", "맑은, 화창한", "It's a sunny day.", "화창한 날입니다."),
    "copier":      ("/ˈkɒpiər/", "명사", "복사기", "Use the copier down the hall.", "복도에 있는 복사기를 사용하세요."),
    "hungry":      ("/ˈhʌŋɡri/", "형용사", "배고픈", "I'm hungry.", "배가 고픕니다."),
    "inspection":  ("/ɪnˈspɛkʃən/", "명사", "검사, 점검", "A safety inspection is due.", "안전 점검이 예정되어 있습니다."),
    "recipient":   ("/rɪˈsɪpiənt/", "명사", "수신자, 수령인", "The recipient was notified.", "수신자에게 알렸습니다."),
    "inspect":     ("/ɪnˈspɛkt/", "동사", "검사하다, 점검하다", "Please inspect the goods.", "물품을 검사해 주세요."),
    "soccer":      ("/ˈsɒkər/", "명사", "축구", "He plays soccer every weekend.", "그는 매 주말 축구를 합니다."),
    "ingredient":  ("/ɪnˈɡriːdiənt/", "명사", "재료, 성분", "List all ingredients.", "모든 재료를 나열하세요."),
    "rewrite":     ("/ˌriːˈraɪt/", "동사", "다시 쓰다", "Please rewrite the report.", "보고서를 다시 써 주세요."),
    "architect":   ("/ˈɑːrkɪtɛkt/", "명사", "건축가", "She is a talented architect.", "그녀는 재능 있는 건축가입니다."),
    "eligible":    ("/ˈɛlɪdʒɪbəl/", "형용사", "자격이 있는", "Are you eligible to vote?", "투표 자격이 있나요?"),
    "indoor":      ("/ˈɪndɔːr/", "형용사", "실내의", "It's an indoor activity.", "실내 활동입니다."),
    "dial":        ("/ˈdaɪəl/", "동사", "다이얼을 돌리다, 전화를 걸다", "Dial the number.", "번호를 누르세요."),
    "container":   ("/kənˈteɪnər/", "명사", "용기, 컨테이너", "Put it in a container.", "용기에 담으세요."),
    "drawer":      ("/ˈdrɔːər/", "명사", "서랍", "Check the drawer.", "서랍을 확인하세요."),
    "lab":         ("/læb/", "명사", "실험실, 연구소", "The lab results are ready.", "실험실 결과가 준비되었습니다."),
    "submission":  ("/səbˈmɪʃən/", "명사", "제출", "Deadline for submission is Friday.", "제출 마감일은 금요일입니다."),
    "bulletin":    ("/ˈbʊlɪtɪn/", "명사", "게시판, 공지", "Check the bulletin board.", "게시판을 확인하세요."),
    "respondent":  ("/rɪˈspɒndənt/", "명사", "응답자", "Survey respondents were satisfied.", "설문 응답자들이 만족했습니다."),
    "skim":        ("/skɪm/", "동사", "훑어 읽다, 훑다", "Skim through the report.", "보고서를 훑어 읽으세요."),
    "logo":        ("/ˈloʊɡoʊ/", "명사", "로고, 상징", "The logo is eye-catching.", "로고가 눈에 띕니다."),
    "cartridge":   ("/ˈkɑːrtrɪdʒ/", "명사", "잉크 카트리지", "Replace the printer cartridge.", "프린터 카트리지를 교체하세요."),
    "shopper":     ("/ˈʃɒpər/", "명사", "쇼핑객", "The shoppers were busy.", "쇼핑객들이 붐볐습니다."),
    "tag":         ("/tæɡ/", "명사", "태그, 가격표", "Check the price tag.", "가격표를 확인하세요."),
    "announcer":   ("/əˈnaʊnsər/", "명사", "아나운서", "The announcer read the news.", "아나운서가 뉴스를 읽었습니다."),
    "cart":        ("/kɑːrt/", "명사", "카트, 수레", "Put it in the cart.", "카트에 담으세요."),
    "delicious":   ("/dɪˈlɪʃəs/", "형용사", "맛있는", "This food is delicious.", "이 음식은 맛있습니다."),
    "ink":         ("/ɪŋk/", "명사", "잉크", "The printer is out of ink.", "프린터 잉크가 떨어졌습니다."),
    "cleaner":     ("/ˈkliːnər/", "명사", "청소부, 세탁소", "The cleaner comes weekly.", "청소부가 매주 옵니다."),
    "developer":   ("/dɪˈvɛləpər/", "명사", "개발자", "She is a software developer.", "그녀는 소프트웨어 개발자입니다."),
    "headquarter": ("/ˈhɛdˌkwɔːrtər/", "명사", "본사", "The headquarters is in London.", "본사는 런던에 있습니다."),
    "alike":       ("/əˈlaɪk/", "형용사", "비슷한, 같은", "They look alike.", "그들은 비슷하게 생겼습니다."),
    "administrative":("/ədˈmɪnɪstrətɪv/", "형용사", "행정의, 관리의", "Handle administrative tasks.", "행정 업무를 처리하세요."),
    "authorize":   ("/ˈɔːθəraɪz/", "동사", "승인하다, 허가하다", "Please authorize the payment.", "결제를 승인해 주세요."),
    "commonly":    ("/ˈkɒmənli/", "부사", "일반적으로, 흔히", "This word is commonly used.", "이 단어는 흔히 사용됩니다."),
    "sofa":        ("/ˈsoʊfə/", "명사", "소파", "Sit on the sofa.", "소파에 앉으세요."),
    "flu":         ("/fluː/", "명사", "독감", "She has the flu.", "그녀는 독감에 걸렸습니다."),
    "trainer":     ("/ˈtreɪnər/", "명사", "트레이너, 강사", "The trainer was helpful.", "트레이너가 도움이 되었습니다."),
    "complimentary":("/ˌkɒmplɪˈmɛntəri/", "형용사", "무료의, 칭찬의", "This drink is complimentary.", "이 음료는 무료입니다."),
    "incomplete":  ("/ˌɪnkəmˈpliːt/", "형용사", "불완전한, 미완성의", "The form is incomplete.", "양식이 불완전합니다."),
    "baseball":    ("/ˈbeɪsbɔːl/", "명사", "야구", "He plays baseball.", "그는 야구를 합니다."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT5:
                    pron, pos, meaning, ex_en, ex_ko = DICT5[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more4.py ===\n")
    patch_files()
