#!/usr/bin/env python3
"""Patch fallback entries: business-L2 (168) + business-L3 (191)"""
import json, glob

DICT16 = {
    # business-L2
    "missile": ("/ˈmɪsaɪl/", "명사", "미사일", "The missile hit its target.", "미사일이 목표물을 맞혔다."),
    "accordance": ("/əˈkɔːrdəns/", "명사", "일치, 따름", "In accordance with the rules.", "규칙에 따라."),
    "parliamentary": ("/ˌpɑːrləˈmentəri/", "형용사", "의회의", "Parliamentary debate began.", "의회 토론이 시작됐다."),
    "vertical": ("/ˈvɜːrtɪkəl/", "형용사", "수직의", "The vertical axis shows growth.", "수직축은 성장을 보여준다."),
    "activist": ("/ˈæktɪvɪst/", "명사", "활동가", "Human rights activists protested.", "인권 활동가들이 항의했다."),
    "node": ("/noʊd/", "명사", "노드, 교점", "The network node failed.", "네트워크 노드가 고장났다."),
    "consultancy": ("/kənˈsʌltənsi/", "명사", "컨설팅 회사", "She works for a consultancy.", "그녀는 컨설팅 회사에서 일한다."),
    "classification": ("/ˌklæsɪfɪˈkeɪʃən/", "명사", "분류", "Tax classification changed.", "세금 분류가 바뀌었다."),
    "utilize": ("/ˈjuːtɪlaɪz/", "동사", "활용하다", "We must utilize resources efficiently.", "우리는 자원을 효율적으로 활용해야 한다."),
    "upward": ("/ˈʌpwərd/", "형용사", "상향의, 위로", "Prices moved upward.", "가격이 상향 이동했다."),
    "charter": ("/ˈtʃɑːrtər/", "명사", "헌장, 허가", "The company charter was amended.", "회사 헌장이 개정됐다."),
    "vulnerable": ("/ˈvʌlnərəbəl/", "형용사", "취약한", "Small firms are vulnerable to recession.", "소기업은 경기침체에 취약하다."),
    "dominant": ("/ˈdɒmɪnənt/", "형용사", "지배적인", "They hold a dominant market position.", "그들은 지배적인 시장 지위를 보유한다."),
    "citation": ("/saɪˈteɪʃən/", "명사", "인용, 표창", "The research requires proper citation.", "연구에는 적절한 인용이 필요하다."),
    "lessee": ("/leˈsiː/", "명사", "임차인", "The lessee signed the contract.", "임차인이 계약에 서명했다."),
    "communist": ("/ˈkɒmjʊnɪst/", "명사", "공산주의자", "Communist policies changed markets.", "공산주의 정책이 시장을 바꿨다."),
    "bust": ("/bʌst/", "명사", "불황, 파산", "The boom turned into a bust.", "호황이 불황으로 바뀌었다."),
    "execution": ("/ˌeksɪˈkjuːʃən/", "명사", "실행, 집행", "Strategy execution is key.", "전략 실행이 핵심이다."),
    "sensitivity": ("/ˌsensɪˈtɪvɪti/", "명사", "민감성", "Price sensitivity varies by region.", "가격 민감성은 지역마다 다르다."),
    "rally": ("/ˈræli/", "명사", "집회, 반등", "Markets rallied after the news.", "소식 이후 시장이 반등했다."),
    "intangible": ("/ɪnˈtændʒɪbəl/", "형용사", "무형의", "Brand is an intangible asset.", "브랜드는 무형 자산이다."),
    "successor": ("/səkˈsesər/", "명사", "후임자, 후계자", "She named her successor.", "그녀는 후임자를 지명했다."),
    "exempt": ("/ɪɡˈzempt/", "형용사", "면제된", "Charities are tax exempt.", "자선단체는 세금이 면제된다."),
    "globalization": ("/ˌɡloʊbəlaɪˈzeɪʃən/", "명사", "세계화", "Globalization reshaped trade.", "세계화가 무역을 재편했다."),
    "elasticity": ("/ˌɪlæˈstɪsɪti/", "명사", "탄력성", "Price elasticity measures demand.", "가격 탄력성은 수요를 측정한다."),
    "weaken": ("/ˈwiːkən/", "동사", "약화시키다", "Rising costs weaken margins.", "비용 상승이 마진을 약화시킨다."),
    "accrue": ("/əˈkruː/", "동사", "발생하다, 누적되다", "Interest accrues monthly.", "이자가 매월 발생한다."),
    "interim": ("/ˈɪntərɪm/", "형용사", "임시의, 중간의", "An interim report was issued.", "중간 보고서가 발행됐다."),
    "payout": ("/ˈpeɪaʊt/", "명사", "지급, 배당", "The payout ratio increased.", "지급 비율이 증가했다."),
    "suppress": ("/səˈpres/", "동사", "억압하다, 억제하다", "Inflation was suppressed.", "인플레이션이 억제됐다."),
    "electoral": ("/ɪˈlektərəl/", "형용사", "선거의", "Electoral reform was debated.", "선거 개혁이 논의됐다."),
    "jurisdiction": ("/ˌdʒʊərɪsˈdɪkʃən/", "명사", "관할권", "This falls under federal jurisdiction.", "이는 연방 관할권에 해당한다."),
    "ambition": ("/æmˈbɪʃən/", "명사", "야망, 포부", "His ambition drove him forward.", "그의 야망이 그를 앞으로 이끌었다."),
    "systematic": ("/ˌsɪstəˈmætɪk/", "형용사", "체계적인", "A systematic approach is needed.", "체계적인 접근이 필요하다."),
    "outsider": ("/ˌaʊtˈsaɪdər/", "명사", "외부인", "An outsider was appointed CEO.", "외부인이 CEO로 임명됐다."),
    "prevail": ("/prɪˈveɪl/", "동사", "우세하다, 만연하다", "Market forces prevailed.", "시장 원리가 우세했다."),
    "virtual": ("/ˈvɜːrtʃuəl/", "형용사", "가상의", "Virtual meetings are now standard.", "가상 회의가 이제 표준이다."),
    "observer": ("/əbˈzɜːrvər/", "명사", "관찰자, 옵서버", "Observers noted the trend.", "관찰자들이 동향을 주목했다."),
    "algorithm": ("/ˈælɡərɪðəm/", "명사", "알고리즘", "The algorithm optimizes pricing.", "알고리즘이 가격을 최적화한다."),
    "horizon": ("/həˈraɪzən/", "명사", "지평선, 전망", "Investment horizons vary.", "투자 지평이 다양하다."),
    "quantitative": ("/ˈkwɒntɪtətɪv/", "형용사", "정량적인", "Quantitative analysis revealed trends.", "정량적 분석이 동향을 드러냈다."),
    "counterpart": ("/ˈkaʊntərpɑːrt/", "명사", "상대방, 대응물", "She met her counterpart.", "그녀는 상대방을 만났다."),
    "diminish": ("/dɪˈmɪnɪʃ/", "동사", "줄어들다, 약화되다", "Returns diminished over time.", "수익이 시간이 지나며 줄어들었다."),
    "collective": ("/kəˈlektɪv/", "형용사", "집단적인", "Collective bargaining began.", "단체 교섭이 시작됐다."),
    "repayment": ("/rɪˈpeɪmənt/", "명사", "상환", "Loan repayment is due.", "대출 상환 기한이 됐다."),
    "offshore": ("/ˈɒfʃɔːr/", "형용사", "역외의", "Offshore accounts were found.", "역외 계좌가 발견됐다."),
    "marketplace": ("/ˈmɑːrkɪtpleɪs/", "명사", "시장, 거래소", "The marketplace is competitive.", "시장이 경쟁적이다."),
    "comparable": ("/ˈkɒmpərəbəl/", "형용사", "비교 가능한", "No comparable data exists.", "비교 가능한 데이터가 없다."),
    "proxy": ("/ˈprɒksi/", "명사", "대리인, 위임장", "Vote by proxy is allowed.", "대리 투표가 허용된다."),
    "politically": ("/pəˈlɪtɪkli/", "부사", "정치적으로", "The decision was politically motivated.", "그 결정은 정치적으로 동기 부여됐다."),
    "municipal": ("/mjuːˈnɪsɪpəl/", "형용사", "지방 자치의", "Municipal bonds were issued.", "지방채가 발행됐다."),
    "hostile": ("/ˈhɒstaɪl/", "형용사", "적대적인", "A hostile takeover was attempted.", "적대적 인수가 시도됐다."),
    "tonne": ("/tʌn/", "명사", "미터법 톤", "Output rose by one tonne.", "생산이 1톤 증가했다."),
    "barrel": ("/ˈbærəl/", "명사", "배럴, 통", "Oil price is per barrel.", "유가는 배럴당이다."),
    "accelerate": ("/əkˈseləreɪt/", "동사", "가속하다", "Growth accelerated last quarter.", "지난 분기에 성장이 가속됐다."),
    "mandate": ("/ˈmændeɪt/", "명사", "위임, 명령", "The CEO has a mandate to cut costs.", "CEO는 비용 절감 권한을 받았다."),
    "donor": ("/ˈdoʊnər/", "명사", "기부자, 공여자", "Donors funded the charity.", "기부자들이 자선단체를 후원했다."),
    "gamble": ("/ˈɡæmbəl/", "명사", "도박, 모험", "Investing in startups is a gamble.", "스타트업 투자는 도박이다."),
    "norm": ("/nɔːrm/", "명사", "규범, 기준", "Industry norms must be followed.", "업계 규범을 따라야 한다."),
    "tighten": ("/ˈtaɪtən/", "동사", "강화하다, 조이다", "Regulators tightened rules.", "규제 당국이 규정을 강화했다."),
    "amend": ("/əˈmend/", "동사", "개정하다, 수정하다", "The law was amended.", "법이 개정됐다."),
    "squeeze": ("/skwiːz/", "명사", "압박, 압착", "Margins are under squeeze.", "마진이 압박을 받고 있다."),
    "ultimate": ("/ˈʌltɪmɪt/", "형용사", "최종의, 궁극적인", "The ultimate goal is profitability.", "궁극적인 목표는 수익성이다."),
    "neutral": ("/ˈnjuːtrəl/", "형용사", "중립의", "Switzerland remained neutral.", "스위스는 중립을 유지했다."),
    "axis": ("/ˈæksɪs/", "명사", "축", "The x-axis shows time.", "x축은 시간을 보여준다."),
    "scrap": ("/skræp/", "동사", "폐기하다", "Old policies were scrapped.", "구식 정책이 폐기됐다."),
    "petrol": ("/ˈpetrəl/", "명사", "휘발유, 가솔린", "Petrol prices rose sharply.", "휘발유 가격이 급격히 올랐다."),
    "uncertain": ("/ʌnˈsɜːrtən/", "형용사", "불확실한", "The outlook remains uncertain.", "전망이 여전히 불확실하다."),
    "pipeline": ("/ˈpaɪplaɪn/", "명사", "파이프라인", "New products are in the pipeline.", "신제품이 준비 중이다."),
    "suicide": ("/ˈsuːɪsaɪd/", "명사", "자살", "Financial suicide was avoided.", "재정적 자살이 방지됐다."),
    "terror": ("/ˈterər/", "명사", "공포, 테러", "Terror attacks disrupted markets.", "테러 공격이 시장을 혼란시켰다."),
    "quota": ("/ˈkwoʊtə/", "명사", "쿼터, 할당량", "Import quotas were imposed.", "수입 할당량이 부과됐다."),
    "trustee": ("/trʌˈstiː/", "명사", "수탁자, 이사", "The trustee managed the fund.", "수탁자가 펀드를 관리했다."),
    "frontier": ("/frʌnˈtɪər/", "명사", "국경, 개척지", "Frontier markets offer high returns.", "개척 시장은 높은 수익을 제공한다."),
    "seize": ("/siːz/", "동사", "장악하다, 압수하다", "Authorities seized assets.", "당국이 자산을 압수했다."),
    "beneficiary": ("/ˌbenɪˈfɪʃieri/", "명사", "수익자, 수혜자", "The beneficiary received funds.", "수익자가 자금을 받았다."),
    "comparative": ("/kəmˈpærətɪv/", "형용사", "비교의, 상대적인", "Comparative advantage drives trade.", "비교 우위가 무역을 이끈다."),
    "capitalism": ("/ˈkæpɪtəlɪzəm/", "명사", "자본주의", "Capitalism promotes competition.", "자본주의는 경쟁을 촉진한다."),
    "readily": ("/ˈredɪli/", "부사", "쉽게, 기꺼이", "Information is readily available.", "정보를 쉽게 이용할 수 있다."),
    "fraction": ("/ˈfrækʃən/", "명사", "분수, 일부", "Only a fraction sold.", "일부만 팔렸다."),
    "solely": ("/ˈsoʊlli/", "부사", "오로지, 단독으로", "Profits depend solely on sales.", "수익은 오로지 매출에 달려있다."),
    "capitalization": ("/ˌkæpɪtəlaɪˈzeɪʃən/", "명사", "자본화, 시가총액", "Market capitalization rose.", "시가총액이 상승했다."),
    "pioneer": ("/ˌpaɪəˈnɪər/", "명사", "선구자, 개척자", "She pioneered e-commerce.", "그녀는 전자상거래를 개척했다."),
    "diplomat": ("/ˈdɪpləmæt/", "명사", "외교관", "Diplomats negotiated the deal.", "외교관들이 협상을 진행했다."),
    "endorse": ("/ɪnˈdɔːrs/", "동사", "지지하다, 배서하다", "The union endorsed the proposal.", "노조가 제안을 지지했다."),
    "cheque": ("/tʃek/", "명사", "수표", "Pay by cheque is less common now.", "수표 결제는 이제 덜 일반적이다."),
    "intent": ("/ɪnˈtent/", "명사", "의도", "The intent was to reduce costs.", "목적은 비용 절감이었다."),
    "lessor": ("/ˈlesɔːr/", "명사", "임대인", "The lessor raised the rent.", "임대인이 임대료를 올렸다."),
    "affiliate": ("/əˈfɪlieɪt/", "명사", "제휴사", "An affiliate company was formed.", "제휴사가 설립됐다."),
    "statutory": ("/ˈstætʃutɔːri/", "형용사", "법정의, 법률에 의한", "Statutory requirements must be met.", "법적 요건을 충족해야 한다."),
    "exporter": ("/ɪkˈspɔːrtər/", "명사", "수출업자, 수출국", "The exporter shipped goods abroad.", "수출업자가 해외에 물건을 선적했다."),
    "prosecutor": ("/ˈprɒsɪkjuːtər/", "명사", "검사, 기소자", "The prosecutor filed charges.", "검사가 혐의를 제기했다."),
    "slump": ("/slʌmp/", "명사", "침체, 급락", "Sales slumped this quarter.", "이번 분기 매출이 급락했다."),
    "lag": ("/læɡ/", "명사", "지연, 뒤처짐", "Economic recovery lagged behind.", "경제 회복이 뒤처졌다."),
    "volatile": ("/ˈvɒlətaɪl/", "형용사", "불안정한, 변동성 있는", "Markets are volatile this week.", "이번 주 시장이 불안정하다."),
    "enforcement": ("/ɪnˈfɔːrsmənt/", "명사", "집행, 단속", "Law enforcement took action.", "법 집행이 조치를 취했다."),
    "sack": ("/sæk/", "동사", "해고하다", "The manager was sacked.", "매니저가 해고됐다."),
    "obstacle": ("/ˈɒbstəkəl/", "명사", "장애물", "Trade obstacles were removed.", "무역 장애물이 제거됐다."),
    "render": ("/ˈrendər/", "동사", "제공하다, 만들다", "Services were rendered promptly.", "서비스가 신속히 제공됐다."),
    "coup": ("/kuː/", "명사", "쿠데타, 성공", "A business coup was achieved.", "사업적 성공이 이루어졌다."),
    "bundle": ("/ˈbʌndəl/", "명사", "묶음", "Products were bundled together.", "제품이 묶음으로 판매됐다."),
    "issuance": ("/ˈɪʃuəns/", "명사", "발행", "Bond issuance was approved.", "채권 발행이 승인됐다."),
    "capitalist": ("/ˈkæpɪtəlɪst/", "명사", "자본가", "The capitalist invested wisely.", "자본가가 현명하게 투자했다."),
    "capitalize": ("/ˈkæpɪtəlaɪz/", "동사", "활용하다, 자본화하다", "Capitalize on the opportunity.", "기회를 활용하세요."),
    "contractual": ("/kənˈtræktʃuəl/", "형용사", "계약상의", "Contractual obligations must be met.", "계약상 의무를 이행해야 한다."),
    "differential": ("/ˌdɪfəˈrenʃəl/", "명사", "차등, 격차", "Wage differentials persist.", "임금 격차가 지속된다."),
    "amortization": ("/əˌmɔːrtɪzˈeɪʃən/", "명사", "상각", "Goodwill amortization reduced profits.", "영업권 상각이 수익을 줄였다."),
    "unfair": ("/ʌnˈfeər/", "형용사", "불공정한", "Unfair competition hurts markets.", "불공정 경쟁이 시장을 해친다."),
    "inter": ("/ˈɪntər/", "접두사", "상호 간의", "Inter-bank rates fluctuated.", "은행 간 금리가 변동했다."),
    "induce": ("/ɪnˈdjuːs/", "동사", "유도하다, 야기하다", "Low rates induce borrowing.", "낮은 금리가 차입을 유도한다."),
    "elite": ("/ɪˈliːt/", "명사", "엘리트", "The financial elite gathered.", "금융 엘리트들이 모였다."),
    "nationalist": ("/ˈnæʃənəlɪst/", "명사", "민족주의자", "Nationalist sentiment grew.", "민족주의 정서가 강해졌다."),
    "simultaneously": ("/ˌsɪməlˈteɪniəsli/", "부사", "동시에", "Stocks fell simultaneously.", "주가가 동시에 하락했다."),
    "broadly": ("/ˈbrɔːdli/", "부사", "광범위하게, 대체로", "Broadly speaking, growth slowed.", "대체로 보면 성장이 둔화됐다."),
    "demographic": ("/ˌdeməˈɡræfɪk/", "형용사", "인구통계학적인", "Demographics shifted significantly.", "인구통계가 크게 바뀌었다."),
    "conglomerate": ("/kənˈɡlɒmərɪt/", "명사", "재벌, 복합기업", "The conglomerate diversified.", "복합기업이 다각화했다."),
    "sustainable": ("/səˈsteɪnəbəl/", "형용사", "지속 가능한", "Sustainable growth is the goal.", "지속 가능한 성장이 목표이다."),
    "credibility": ("/ˌkredɪˈbɪlɪti/", "명사", "신뢰성", "Central bank credibility matters.", "중앙은행 신뢰성이 중요하다."),
    "simulation": ("/ˌsɪmjʊˈleɪʃən/", "명사", "시뮬레이션", "Computer simulation was run.", "컴퓨터 시뮬레이션이 실행됐다."),
    "senator": ("/ˈsenətər/", "명사", "상원의원", "The senator opposed the bill.", "상원의원이 법안에 반대했다."),
    "adoption": ("/əˈdɒpʃən/", "명사", "채택, 입양", "Technology adoption increased.", "기술 채택이 증가했다."),
    "standardize": ("/ˈstændərdaɪz/", "동사", "표준화하다", "Processes were standardized.", "프로세스가 표준화됐다."),
    "consolidation": ("/kənˌsɒlɪˈdeɪʃən/", "명사", "통합, 강화", "Industry consolidation continued.", "산업 통합이 계속됐다."),
    "sensible": ("/ˈsensɪbəl/", "형용사", "합리적인, 현명한", "A sensible investment strategy is needed.", "합리적인 투자 전략이 필요하다."),
    "headline": ("/ˈhedlaɪn/", "명사", "헤드라인, 주요 뉴스", "The headline figure surprised analysts.", "주요 수치가 분석가들을 놀라게 했다."),
    "deploy": ("/dɪˈplɔɪ/", "동사", "배치하다, 활용하다", "Capital was deployed wisely.", "자본이 현명하게 배치됐다."),
    "macroeconomic": ("/ˌmækroʊˌiːkəˈnɒmɪk/", "형용사", "거시경제적인", "Macroeconomic conditions worsened.", "거시경제 여건이 악화됐다."),
    "concession": ("/kənˈseʃən/", "명사", "양보, 인정", "A trade concession was made.", "무역 양보가 이루어졌다."),
    "contingent": ("/kənˈtɪndʒənt/", "형용사", "조건부의", "Payment is contingent on delivery.", "지급은 배달에 조건부이다."),
    "diverse": ("/daɪˈvɜːrs/", "형용사", "다양한", "The portfolio is diverse.", "포트폴리오가 다양하다."),
    "privately": ("/ˈpraɪvɪtli/", "부사", "사적으로, 민간으로", "The company is privately held.", "회사가 민간 소유이다."),
    "guerrilla": ("/ɡəˈrɪlə/", "명사", "게릴라", "Guerrilla marketing tactics work.", "게릴라 마케팅 전술이 효과적이다."),
    "repurchase": ("/ˌriːˈpɜːrtʃɪs/", "명사", "자사주 매입", "Share repurchases increased.", "자사주 매입이 증가했다."),
    "inequality": ("/ˌɪnɪˈkwɒlɪti/", "명사", "불평등", "Income inequality grew.", "소득 불평등이 심화됐다."),
    "plunge": ("/plʌndʒ/", "동사", "급락하다", "Stocks plunged sharply.", "주가가 급락했다."),
    "intensive": ("/ɪnˈtensɪv/", "형용사", "집중적인", "Intensive training was required.", "집중 훈련이 필요했다."),
    "nonetheless": ("/ˌnʌnðəˈles/", "부사", "그럼에도 불구하고", "Risks remain; nonetheless, invest.", "위험이 있지만, 그럼에도 불구하고 투자한다."),
    "horizontal": ("/ˌhɒrɪˈzɒntəl/", "형용사", "수평의", "Horizontal integration occurred.", "수평적 통합이 이루어졌다."),
    "legally": ("/ˈliːɡəli/", "부사", "법적으로", "The deal is legally binding.", "거래가 법적으로 구속력이 있다."),
    "installment": ("/ɪnˈstɔːlmənt/", "명사", "할부, 분할", "Pay in monthly installments.", "월별 할부로 납부하세요."),
    "revive": ("/rɪˈvaɪv/", "동사", "되살리다, 회복하다", "Efforts to revive growth failed.", "성장 회복 노력이 실패했다."),
    "inevitable": ("/ɪnˈevɪtəbəl/", "형용사", "불가피한", "A merger seemed inevitable.", "합병이 불가피해 보였다."),
    "array": ("/əˈreɪ/", "명사", "배열, 다양한", "A wide array of products.", "다양한 제품들."),
    "ballot": ("/ˈbælət/", "명사", "투표, 선거", "Workers cast their ballot.", "근로자들이 투표했다."),
    "treasury": ("/ˈtreʒəri/", "명사", "재무부, 국고", "Treasury bonds are safe.", "국채는 안전하다."),
    "intermediary": ("/ˌɪntəˈmiːdieri/", "명사", "중개인", "A financial intermediary was used.", "금융 중개인이 활용됐다."),
    "boast": ("/boʊst/", "동사", "자랑하다, 보유하다", "The firm boasts strong results.", "회사가 강력한 실적을 자랑한다."),
    "militant": ("/ˈmɪlɪtənt/", "명사", "투사, 강경파", "Militant unions demanded wage hikes.", "강경 노조가 임금 인상을 요구했다."),
    "discourage": ("/dɪsˈkɜːrɪdʒ/", "동사", "억제하다, 낙담시키다", "High taxes discourage investment.", "높은 세금이 투자를 억제한다."),
    "hierarchy": ("/ˈhaɪərɑːrki/", "명사", "위계질서", "Corporate hierarchy is flat.", "기업 위계가 수평적이다."),
    "fate": ("/feɪt/", "명사", "운명", "The company's fate was sealed.", "회사의 운명이 결정됐다."),
    "widen": ("/ˈwaɪdən/", "동사", "넓히다, 확대되다", "The trade deficit widened.", "무역 적자가 커졌다."),
    "transformation": ("/ˌtrænsfəˈmeɪʃən/", "명사", "변환, 전환", "Digital transformation accelerated.", "디지털 전환이 가속됐다."),
    "qualitative": ("/ˈkwɒlɪtətɪv/", "형용사", "정성적인", "Qualitative research was conducted.", "정성적 연구가 수행됐다."),
    "gang": ("/ɡæŋ/", "명사", "조직, 갱단", "A gang of traders cooperated.", "트레이더 조직이 협력했다."),
    "curb": ("/kɜːrb/", "동사", "억제하다, 규제하다", "Spending was curbed.", "지출이 억제됐다."),
    "robust": ("/roʊˈbʌst/", "형용사", "견고한, 강력한", "Robust growth continued.", "견고한 성장이 계속됐다."),
    "brokerage": ("/ˈbroʊkərɪdʒ/", "명사", "중개업, 중개 수수료", "Brokerage fees were reduced.", "중개 수수료가 줄었다."),
    "tolerance": ("/ˈtɒlərəns/", "명사", "허용 한도, 관용", "Risk tolerance varies.", "위험 허용 한도가 다양하다."),
    "devise": ("/dɪˈvaɪz/", "동사", "고안하다", "A new strategy was devised.", "새로운 전략이 고안됐다."),
    "speculation": ("/ˌspekjʊˈleɪʃən/", "명사", "투기, 추측", "Market speculation increased.", "시장 투기가 증가했다."),
    "incremental": ("/ˌɪŋkrɪˈmentəl/", "형용사", "점진적인", "Incremental changes were made.", "점진적인 변화가 이루어졌다."),
    "fighter": ("/ˈfaɪtər/", "명사", "전투기, 투사", "A fighter jet contract was won.", "전투기 계약을 수주했다."),
    "grip": ("/ɡrɪp/", "명사", "장악, 파악", "Inflation has a grip on the economy.", "인플레이션이 경제를 장악했다."),
    "mathematical": ("/ˌmæθəˈmætɪkəl/", "형용사", "수학적인", "Mathematical models forecast trends.", "수학적 모델이 추세를 예측한다."),
    "assert": ("/əˈsɜːrt/", "동사", "주장하다, 확언하다", "Analysts asserted the view.", "분석가들이 견해를 주장했다."),
    "underwrite": ("/ˌʌndərˈraɪt/", "동사", "인수하다, 보증하다", "Banks underwrote the bond issue.", "은행들이 채권 발행을 인수했다."),
    "differentiate": ("/ˌdɪfəˈrenʃieɪt/", "동사", "차별화하다", "Products must differentiate.", "제품은 차별화해야 한다."),
    # business-L3
    "slowdown": ("/ˈsloʊdaʊn/", "명사", "경기 둔화", "Global slowdown worries analysts.", "세계 경기 둔화가 분석가들을 걱정시킨다."),
    "adverse": ("/ˈædvɜːrs/", "형용사", "불리한", "Adverse conditions hit earnings.", "불리한 조건이 수익을 타격했다."),
    "suspicion": ("/səˈspɪʃən/", "명사", "의심, 혐의", "Suspicion arose over the deal.", "거래에 대한 의심이 생겼다."),
    "virtue": ("/ˈvɜːrtʃuː/", "명사", "덕목, 미덕", "Patience is a virtue.", "인내는 덕목이다."),
    "flee": ("/fliː/", "동사", "도망가다", "Investors fled the market.", "투자자들이 시장에서 도망갔다."),
    "bureaucracy": ("/bjʊˈrɒkrəsi/", "명사", "관료제", "Bureaucracy slows decisions.", "관료제가 의사결정을 늦춘다."),
    "threshold": ("/ˈθreʃhoʊld/", "명사", "한계점, 임계값", "The threshold was not met.", "한계점에 도달하지 못했다."),
    "wholesale": ("/ˈhoʊlseɪl/", "형용사", "도매의", "Wholesale prices fell sharply.", "도매 가격이 급격히 떨어졌다."),
    "legitimate": ("/lɪˈdʒɪtɪmɪt/", "형용사", "합법적인", "A legitimate business must comply.", "합법적인 사업은 준수해야 한다."),
    "privacy": ("/ˈprɪvəsi/", "명사", "개인 정보 보호", "Data privacy laws apply.", "개인 정보 보호법이 적용된다."),
    "behavioral": ("/bɪˈheɪvjərəl/", "형용사", "행동의", "Behavioral economics studies choices.", "행동 경제학은 선택을 연구한다."),
    "tangible": ("/ˈtændʒɪbəl/", "형용사", "유형의, 실질적인", "Tangible assets include buildings.", "유형 자산에는 건물이 포함된다."),
    "dump": ("/dʌmp/", "동사", "투매하다, 덤핑하다", "Investors dumped the shares.", "투자자들이 주식을 투매했다."),
    "discharge": ("/ˈdɪstʃɑːrdʒ/", "동사", "방출하다, 변제하다", "Debt was discharged.", "부채가 변제됐다."),
    "breakdown": ("/ˈbreɪkdaʊn/", "명사", "세부 내역, 붕괴", "A cost breakdown was provided.", "비용 세부 내역이 제공됐다."),
    "span": ("/spæn/", "명사", "기간, 범위", "The project spans three years.", "프로젝트가 3년에 걸쳐 있다."),
    "bail": ("/beɪl/", "동사", "구제하다", "The government bailed out banks.", "정부가 은행을 구제했다."),
    "incumbent": ("/ɪnˈkʌmbənt/", "형용사", "현직의", "The incumbent CEO resigned.", "현직 CEO가 사임했다."),
    "outflow": ("/ˈaʊtfloʊ/", "명사", "유출", "Capital outflows increased.", "자본 유출이 증가했다."),
    "albeit": ("/ɔːlˈbiːɪt/", "접속사", "비록 ~이지만", "Progress was made, albeit slowly.", "비록 느리지만 진전이 있었다."),
    "tricky": ("/ˈtrɪki/", "형용사", "까다로운", "Negotiations proved tricky.", "협상이 까다롭다는 것이 드러났다."),
    "spokesman": ("/ˈspoʊksmən/", "명사", "대변인", "A spokesman issued a statement.", "대변인이 성명을 발표했다."),
    "contingency": ("/kənˈtɪndʒənsi/", "명사", "비상사태, 우발 사항", "A contingency fund was set up.", "비상 자금이 마련됐다."),
    "surrender": ("/səˈrendər/", "동사", "포기하다, 항복하다", "They surrendered market share.", "그들이 시장 점유율을 포기했다."),
    "judicial": ("/dʒuˈdɪʃəl/", "형용사", "사법의, 재판의", "Judicial review was requested.", "사법 심사가 요청됐다."),
    "certainty": ("/ˈsɜːrtənti/", "명사", "확실성", "Certainty reduces risk.", "확실성이 위험을 줄인다."),
    "mainstream": ("/ˈmeɪnstriːm/", "명사", "주류", "The idea entered the mainstream.", "아이디어가 주류로 진입했다."),
    "rebuild": ("/ˌriːˈbɪld/", "동사", "재건하다", "The economy is being rebuilt.", "경제가 재건되고 있다."),
    "corrupt": ("/kəˈrʌpt/", "형용사", "부패한", "Corrupt officials were arrested.", "부패한 공무원들이 체포됐다."),
    "integrity": ("/ɪnˈteɡrɪti/", "명사", "청렴, 무결성", "Financial integrity is essential.", "재무적 청렴이 필수적이다."),
    "proposition": ("/ˌprɒpəˈzɪʃən/", "명사", "제안, 명제", "A business proposition was offered.", "사업 제안이 제시됐다."),
    "litigation": ("/ˌlɪtɪˈɡeɪʃən/", "명사", "소송", "Litigation costs were high.", "소송 비용이 높았다."),
    "amid": ("/əˈmɪd/", "전치사", "~가운데, 속에서", "Profits rose amid uncertainty.", "불확실성 속에서 수익이 올랐다."),
    "bold": ("/boʊld/", "형용사", "대담한", "A bold strategy was announced.", "대담한 전략이 발표됐다."),
    "straightforward": ("/ˌstreɪtˈfɔːrwərd/", "형용사", "간단한, 솔직한", "The process is straightforward.", "절차가 간단하다."),
    "handful": ("/ˈhændfʊl/", "명사", "소수, 한 줌", "Only a handful of firms survived.", "소수의 회사만 살아남았다."),
    "unchanged": ("/ʌnˈtʃeɪndʒd/", "형용사", "변하지 않은", "Rates remained unchanged.", "금리가 변하지 않았다."),
    "queue": ("/kjuː/", "명사", "줄, 대기열", "Buyers queued for shares.", "구매자들이 주식을 사려고 줄을 섰다."),
    "bidder": ("/ˈbɪdər/", "명사", "입찰자", "The highest bidder won.", "최고 입찰자가 낙찰됐다."),
    "respective": ("/rɪˈspektɪv/", "형용사", "각각의", "Each in their respective roles.", "각자 자신의 역할을 담당했다."),
    "deliverable": ("/dɪˈlɪvərəbəl/", "명사", "납품물, 산출물", "Project deliverables were met.", "프로젝트 납품물이 충족됐다."),
    "depict": ("/dɪˈpɪkt/", "동사", "묘사하다, 나타내다", "Charts depict growth trends.", "차트가 성장 추세를 나타낸다."),
    "odds": ("/ɒdz/", "명사", "가능성, 확률", "The odds of success are slim.", "성공 가능성이 낮다."),
    "allegation": ("/ˌælɪˈɡeɪʃən/", "명사", "혐의, 주장", "Fraud allegations emerged.", "사기 혐의가 제기됐다."),
    "redemption": ("/rɪˈdempʃən/", "명사", "상환, 구제", "Bond redemption was completed.", "채권 상환이 완료됐다."),
    "downward": ("/ˈdaʊnwərd/", "형용사", "하향의", "Prices moved in a downward trend.", "가격이 하향 추세로 움직였다."),
    "grid": ("/ɡrɪd/", "명사", "격자, 전력망", "The power grid failed.", "전력망이 고장났다."),
    "depreciate": ("/dɪˈpriːʃieɪt/", "동사", "감가상각하다", "Assets depreciate over time.", "자산은 시간이 지나면 감가상각된다."),
    "interface": ("/ˈɪntərfeɪs/", "명사", "인터페이스", "The user interface was redesigned.", "사용자 인터페이스가 재설계됐다."),
    "digit": ("/ˈdɪdʒɪt/", "명사", "숫자, 자릿수", "Double-digit growth was achieved.", "두 자릿수 성장이 달성됐다."),
    "hybrid": ("/ˈhaɪbrɪd/", "명사", "혼합형", "A hybrid approach was chosen.", "혼합형 접근 방식이 선택됐다."),
    "provoke": ("/prəˈvoʊk/", "동사", "유발하다, 자극하다", "The policy provoked protests.", "정책이 시위를 유발했다."),
    "inevitably": ("/ɪnˈevɪtəbli/", "부사", "불가피하게", "Costs inevitably rose.", "비용이 불가피하게 올랐다."),
    "dilemma": ("/dɪˈlemə/", "명사", "딜레마", "A moral dilemma was faced.", "도덕적 딜레마에 직면했다."),
    "info": ("/ˈɪnfoʊ/", "명사", "정보", "More info was requested.", "더 많은 정보가 요청됐다."),
    "secular": ("/ˈsekjʊlər/", "형용사", "세속적인, 장기적인", "Secular trends drive change.", "장기적인 추세가 변화를 이끈다."),
    "cease": ("/siːs/", "동사", "중단하다", "Operations ceased temporarily.", "영업이 일시적으로 중단됐다."),
    "distress": ("/dɪˈstres/", "명사", "고통, 재정난", "Financial distress was evident.", "재정난이 명백했다."),
    "withhold": ("/wɪðˈhoʊld/", "동사", "보류하다, 원천징수하다", "Tax was withheld at source.", "세금이 원천 징수됐다."),
    "sterling": ("/ˈstɜːrlɪŋ/", "명사", "파운드 스털링", "Sterling fell against the dollar.", "파운드가 달러 대비 떨어졌다."),
    "legacy": ("/ˈleɡəsi/", "명사", "유산, 레거시", "Legacy systems slow digital shift.", "레거시 시스템이 디지털 전환을 늦춘다."),
    "thrive": ("/θraɪv/", "동사", "번창하다", "The startup thrived.", "스타트업이 번창했다."),
    "autonomy": ("/ɔːˈtɒnəmi/", "명사", "자율성, 자치권", "Subsidiaries have financial autonomy.", "자회사는 재무 자율성을 가진다."),
    "commander": ("/kəˈmɑːndər/", "명사", "지휘관, 최고 책임자", "The market leader commanded strategy.", "시장 지배자가 전략을 이끌었다."),
    "accountability": ("/əˌkaʊntəˈbɪlɪti/", "명사", "책임", "Corporate accountability improved.", "기업 책임이 향상됐다."),
    "incorporation": ("/ɪnˌkɔːrpəˈreɪʃən/", "명사", "법인 설립", "Company incorporation was completed.", "회사 법인 설립이 완료됐다."),
    "batch": ("/bætʃ/", "명사", "배치, 묶음", "Process in batches.", "묶음으로 처리하다."),
    "essence": ("/ˈesəns/", "명사", "본질, 핵심", "The essence of business is profit.", "사업의 본질은 이익이다."),
    "invasion": ("/ɪnˈveɪʒən/", "명사", "침략", "Market invasion by foreign firms.", "외국 기업의 시장 침략."),
    "bondholder": ("/ˈbɒndhoʊldər/", "명사", "채권 보유자", "Bondholders received full payment.", "채권 보유자들이 전액을 받았다."),
    "unveil": ("/ʌnˈveɪl/", "동사", "공개하다, 발표하다", "Plans were unveiled today.", "계획이 오늘 공개됐다."),
    "intrinsic": ("/ɪnˈtrɪnsɪk/", "형용사", "내재적인", "Intrinsic value was low.", "내재 가치가 낮았다."),
    "continent": ("/ˈkɒntɪnənt/", "명사", "대륙", "The company expanded across the continent.", "회사가 대륙 전체로 확장됐다."),
    "computation": ("/ˌkɒmpjʊˈteɪʃən/", "명사", "계산", "Tax computation was complex.", "세금 계산이 복잡했다."),
    "diplomatic": ("/ˌdɪpləˈmætɪk/", "형용사", "외교적인", "Diplomatic channels were used.", "외교 채널이 활용됐다."),
    "formerly": ("/ˈfɔːrməli/", "부사", "이전에", "Formerly known as ABC Corp.", "이전에 ABC Corp로 알려졌다."),
    "optimization": ("/ˌɒptɪmaɪˈzeɪʃən/", "명사", "최적화", "Process optimization cut costs.", "프로세스 최적화가 비용을 절감했다."),
    "spectrum": ("/ˈspektrəm/", "명사", "스펙트럼, 범위", "A spectrum of options exists.", "다양한 옵션이 존재한다."),
    "tuple": ("/ˈtjuːpəl/", "명사", "튜플", "Data as a tuple was stored.", "데이터가 튜플로 저장됐다."),
    "magnitude": ("/ˈmæɡnɪtjuːd/", "명사", "규모, 크기", "The magnitude of the loss was large.", "손실의 규모가 컸다."),
    "validity": ("/vəˈlɪdɪti/", "명사", "유효성, 타당성", "Data validity was questioned.", "데이터 유효성이 의문시됐다."),
    "interact": ("/ˌɪntərˈækt/", "동사", "상호작용하다", "Markets interact globally.", "시장이 글로벌하게 상호작용한다."),
    "intervene": ("/ˌɪntərˈviːn/", "동사", "개입하다", "The central bank intervened.", "중앙은행이 개입했다."),
    "halt": ("/hɔːlt/", "동사", "중단하다", "Trading was halted.", "거래가 중단됐다."),
    "niche": ("/niːʃ/", "명사", "틈새", "A niche market was found.", "틈새 시장이 발견됐다."),
    "shed": ("/ʃed/", "동사", "줄이다, 떨쳐버리다", "Jobs were shed.", "일자리가 줄었다."),
    "motive": ("/ˈmoʊtɪv/", "명사", "동기, 의도", "The motive was profit.", "동기는 이익이었다."),
    "whereby": ("/weərˈbaɪ/", "부사", "그에 따라", "A system whereby taxes apply.", "세금이 적용되는 시스템."),
    "median": ("/ˈmiːdɪən/", "명사", "중앙값", "Median income rose.", "중위 소득이 상승했다."),
    "wholly": ("/ˈhoʊlli/", "부사", "전적으로", "The firm is wholly owned.", "회사가 전적으로 소유됐다."),
    "supposedly": ("/səˈpoʊzɪdli/", "부사", "추정상", "It was supposedly profitable.", "그것은 수익성이 있다고 추정됐다."),
    "crude": ("/kruːd/", "형용사", "원유의, 가공하지 않은", "Crude oil prices rose.", "원유 가격이 올랐다."),
    "commissioner": ("/kəˈmɪʃənər/", "명사", "위원장", "The EU commissioner commented.", "EU 위원장이 논평했다."),
    "sufficiently": ("/səˈfɪʃəntli/", "부사", "충분히", "The fund is sufficiently capitalized.", "펀드가 충분히 자본화됐다."),
    "protocol": ("/ˈproʊtəkɒl/", "명사", "프로토콜, 규약", "Security protocols were updated.", "보안 프로토콜이 업데이트됐다."),
    "constrain": ("/kənˈstreɪn/", "동사", "제한하다", "Budgets constrain growth.", "예산이 성장을 제한한다."),
    "blank": ("/blæŋk/", "형용사", "공백의, 빈", "A blank check was given.", "백지 수표가 주어졌다."),
    "legislature": ("/ˈledʒɪslətʃər/", "명사", "입법부", "The legislature passed the bill.", "입법부가 법안을 통과시켰다."),
    "punish": ("/ˈpʌnɪʃ/", "동사", "처벌하다", "Regulators punished violations.", "규제 당국이 위반을 처벌했다."),
    "predictable": ("/prɪˈdɪktəbəl/", "형용사", "예측 가능한", "Returns are predictable.", "수익이 예측 가능하다."),
    "liquidation": ("/ˌlɪkwɪˈdeɪʃən/", "명사", "청산", "Liquidation was ordered.", "청산이 명령됐다."),
    "chaos": ("/ˈkeɪɒs/", "명사", "혼돈", "Market chaos followed.", "시장 혼돈이 이어졌다."),
    "impairment": ("/ɪmˈpeərmənt/", "명사", "손상차손", "Goodwill impairment was recorded.", "영업권 손상차손이 기록됐다."),
    "harvest": ("/ˈhɑːrvɪst/", "명사", "수확, 수익화", "Profits were harvested.", "수익이 실현됐다."),
    "migrant": ("/ˈmaɪɡrənt/", "명사", "이주자", "Migrant workers filled roles.", "이주 노동자들이 역할을 채웠다."),
    "objection": ("/əbˈdʒekʃən/", "명사", "이의 제기", "Objections were raised.", "이의가 제기됐다."),
    "macroeconomics": ("/ˌmækroʊˌiːkəˈnɒmɪks/", "명사", "거시경제학", "Macroeconomics informs policy.", "거시경제학이 정책에 정보를 제공한다."),
    "accrual": ("/əˈkruːəl/", "명사", "발생 기준, 누적", "Accrual accounting applies.", "발생 기준 회계가 적용된다."),
    "confront": ("/kənˈfrʌnt/", "동사", "직면하다", "Companies confront new challenges.", "기업들이 새로운 도전에 직면한다."),
    "punishment": ("/ˈpʌnɪʃmənt/", "명사", "처벌", "Stiff punishment deters fraud.", "엄한 처벌이 사기를 억제한다."),
    "passive": ("/ˈpæsɪv/", "형용사", "수동적인", "Passive income is tax-efficient.", "수동적 소득은 세금 효율적이다."),
    "conditional": ("/kənˈdɪʃənəl/", "형용사", "조건부의", "Approval is conditional.", "승인이 조건부이다."),
    "scrutiny": ("/ˈskruːtɪni/", "명사", "면밀한 조사", "The deal faced scrutiny.", "거래가 면밀한 조사를 받았다."),
    "exile": ("/ˈeksaɪl/", "명사", "망명, 추방", "The executive went into exile.", "임원이 망명했다."),
    "inherent": ("/ɪnˈhɪərənt/", "형용사", "내재된", "Inherent risk must be managed.", "내재된 위험을 관리해야 한다."),
    "explicitly": ("/ɪkˈsplɪsɪtli/", "부사", "명시적으로", "Rules were explicitly stated.", "규정이 명시적으로 기술됐다."),
    "clever": ("/ˈklevər/", "형용사", "영리한", "A clever strategy was devised.", "영리한 전략이 고안됐다."),
    "payback": ("/ˈpeɪbæk/", "명사", "회수 기간, 보복", "The payback period is 3 years.", "회수 기간이 3년이다."),
    "sacrifice": ("/ˈsækrɪfaɪs/", "명사", "희생, 포기", "Short-term profits were sacrificed.", "단기 수익이 희생됐다."),
    "semi": ("/ˈsemi/", "접두사", "반~", "Semi-annual reports required.", "반기 보고서가 필요하다."),
    "feasible": ("/ˈfiːzɪbəl/", "형용사", "실현 가능한", "The plan is financially feasible.", "계획이 재무적으로 실현 가능하다."),
    "conviction": ("/kənˈvɪkʃən/", "명사", "유죄 판결, 신념", "His conviction was overturned.", "그의 유죄 판결이 뒤집혔다."),
    "continuously": ("/kənˈtɪnjuəsli/", "부사", "지속적으로", "Revenue grew continuously.", "수익이 지속적으로 증가했다."),
    "tier": ("/tɪər/", "명사", "계층, 티어", "A three-tier pricing model.", "3단계 가격 모델."),
    "transparency": ("/trænsˈpærənsi/", "명사", "투명성", "Financial transparency is required.", "재무 투명성이 요구된다."),
    "inadequate": ("/ɪnˈædɪkwɪt/", "형용사", "부적절한", "Funding was inadequate.", "자금이 부적절했다."),
    "acre": ("/ˈeɪkər/", "명사", "에이커", "The company owns 100 acres.", "회사가 100에이커를 소유한다."),
    "levy": ("/ˈlevi/", "명사", "세금, 부과금", "A tax levy was imposed.", "세금이 부과됐다."),
    "freely": ("/ˈfriːli/", "부사", "자유롭게", "Capital flows freely.", "자본이 자유롭게 흐른다."),
    "reliance": ("/rɪˈlaɪəns/", "명사", "의존", "Reliance on foreign oil rose.", "외국 석유 의존이 증가했다."),
    "covenant": ("/ˈkʌvənənt/", "명사", "약정, 서약", "Loan covenants were breached.", "대출 약정이 위반됐다."),
    "prosecute": ("/ˈprɒsɪkjuːt/", "동사", "기소하다", "Violators were prosecuted.", "위반자들이 기소됐다."),
    "materially": ("/məˈtɪərɪəli/", "부사", "중요하게, 실질적으로", "Results improved materially.", "결과가 실질적으로 개선됐다."),
    "convict": ("/kənˈvɪkt/", "동사", "유죄 판결을 내리다", "The executive was convicted.", "임원이 유죄 판결을 받았다."),
    "procurement": ("/prəˈkjʊərmənt/", "명사", "조달", "Procurement costs were reduced.", "조달 비용이 절감됐다."),
    "clash": ("/klæʃ/", "동사", "충돌하다", "Investors clashed with management.", "투자자들이 경영진과 충돌했다."),
    "deter": ("/dɪˈtɜːr/", "동사", "억제하다, 막다", "High fines deter misconduct.", "높은 벌금이 비위를 억제한다."),
    "prosecution": ("/ˌprɒsɪˈkjuːʃən/", "명사", "기소, 검찰", "Prosecution was initiated.", "기소가 시작됐다."),
    "nasty": ("/ˈnɑːsti/", "형용사", "불쾌한, 심각한", "A nasty dispute emerged.", "불쾌한 분쟁이 발생했다."),
    "condemn": ("/kənˈdem/", "동사", "비난하다", "The practice was condemned.", "관행이 비난받았다."),
    "operative": ("/ˈɒpərətɪv/", "형용사", "작동 중인", "The plan is now operative.", "계획이 현재 작동 중이다."),
    "privatize": ("/ˈpraɪvɪtaɪz/", "동사", "민영화하다", "State assets were privatized.", "국가 자산이 민영화됐다."),
    "endure": ("/ɪnˈdjʊər/", "동사", "견디다", "Markets endured volatility.", "시장이 변동성을 견뎌냈다."),
    "doctrine": ("/ˈdɒktrɪn/", "명사", "교리, 원칙", "Free market doctrine prevailed.", "자유 시장 원칙이 우세했다."),
    "distort": ("/dɪˈstɔːrt/", "동사", "왜곡하다", "Subsidies distort markets.", "보조금이 시장을 왜곡한다."),
    "triple": ("/ˈtrɪpəl/", "동사", "세 배가 되다", "Revenue tripled.", "수익이 세 배가 됐다."),
    "textile": ("/ˈtekstaɪl/", "명사", "섬유, 직물", "Textile exports grew.", "섬유 수출이 증가했다."),
    "manipulate": ("/məˈnɪpjʊleɪt/", "동사", "조작하다", "Prices were manipulated.", "가격이 조작됐다."),
    "unity": ("/ˈjuːnɪti/", "명사", "통일, 단합", "Team unity drives success.", "팀 단합이 성공을 이끈다."),
    "alpha": ("/ˈælfə/", "명사", "알파, 초과 수익", "The fund generates alpha.", "펀드가 초과 수익을 창출한다."),
    "refine": ("/rɪˈfaɪn/", "동사", "정제하다, 개선하다", "Strategy was refined.", "전략이 개선됐다."),
    "deflation": ("/dɪˈfleɪʃən/", "명사", "디플레이션", "Deflation harmed consumption.", "디플레이션이 소비를 해쳤다."),
    "antitrust": ("/ˈæntɪtrʌst/", "형용사", "반독점의", "Antitrust laws were applied.", "반독점법이 적용됐다."),
    "practitioner": ("/præktɪˈʃənər/", "명사", "실무자", "Financial practitioners met.", "금융 실무자들이 모였다."),
    "prosperity": ("/prɒˈsperɪti/", "명사", "번영", "Economic prosperity followed.", "경제적 번영이 뒤따랐다."),
    "riot": ("/ˈraɪət/", "명사", "폭동", "Worker riots disrupted output.", "근로자 폭동이 생산을 방해했다."),
    "align": ("/əˈlaɪn/", "동사", "일치시키다, 정렬하다", "Incentives were aligned.", "인센티브가 일치됐다."),
    "reinvest": ("/ˌriːɪnˈvest/", "동사", "재투자하다", "Profits were reinvested.", "수익이 재투자됐다."),
    "provincial": ("/prəˈvɪnʃəl/", "형용사", "지방의", "Provincial governments acted.", "지방 정부가 행동했다."),
    "concede": ("/kənˈsiːd/", "동사", "인정하다, 양보하다", "Officials conceded the error.", "당국자들이 오류를 인정했다."),
    "controversy": ("/ˈkɒntrəvɜːrsi/", "명사", "논란", "The merger caused controversy.", "합병이 논란을 일으켰다."),
    "fierce": ("/fɪərs/", "형용사", "치열한", "Fierce competition exists.", "치열한 경쟁이 존재한다."),
    "veto": ("/ˈviːtoʊ/", "명사", "거부권", "The CEO vetoed the plan.", "CEO가 계획에 거부권을 행사했다."),
    "instant": ("/ˈɪnstənt/", "형용사", "즉각적인", "Instant payment was offered.", "즉각적인 결제가 제공됐다."),
    "ceasefire": ("/ˈsiːsfaɪər/", "명사", "휴전", "A trade ceasefire was declared.", "무역 휴전이 선언됐다."),
    "handset": ("/ˈhændset/", "명사", "핸드셋, 휴대폰", "New handsets boosted revenue.", "새 핸드셋이 수익을 높였다."),
    "sentiment": ("/ˈsentɪmənt/", "명사", "심리, 감정", "Market sentiment turned positive.", "시장 심리가 긍정적으로 전환됐다."),
    "vest": ("/vest/", "동사", "부여하다", "Stock options vest over time.", "스톡옵션이 시간이 지나며 부여된다."),
    "beef": ("/biːf/", "동사", "강화하다", "Firms beefed up security.", "회사들이 보안을 강화했다."),
    "combat": ("/ˈkɒmbæt/", "동사", "싸우다, 대응하다", "Measures combat inflation.", "조치들이 인플레이션에 대응한다."),
    "parity": ("/ˈpærɪti/", "명사", "동등성, 평가", "Pay parity was achieved.", "급여 평등이 달성됐다."),
    "centralize": ("/ˈsentrəlaɪz/", "동사", "중앙 집중화하다", "Decisions were centralized.", "의사결정이 중앙 집중화됐다."),
    "sovereign": ("/ˈsɒvrɪn/", "형용사", "주권의", "Sovereign debt rose sharply.", "국가 채무가 급격히 올랐다."),
    "estimation": ("/ˌestɪˈmeɪʃən/", "명사", "추정", "Cost estimation was revised.", "비용 추정이 수정됐다."),
    "lucrative": ("/ˈluːkrətɪv/", "형용사", "수익성 높은", "A lucrative contract was signed.", "수익성 높은 계약이 체결됐다."),
    "stabilize": ("/ˈsteɪbɪlaɪz/", "동사", "안정시키다", "Rates were stabilized.", "금리가 안정됐다."),
    "molecule": ("/ˈmɒlɪkjuːl/", "명사", "분자", "Molecules were analyzed.", "분자가 분석됐다."),
    "variability": ("/ˌveərɪəˈbɪlɪti/", "명사", "변동성, 가변성", "High variability risks returns.", "높은 변동성이 수익을 위험에 빠뜨린다."),
    "strive": ("/straɪv/", "동사", "노력하다", "Firms strive for excellence.", "회사들이 탁월함을 위해 노력한다."),
    "cure": ("/kjʊər/", "명사", "해결책, 치료", "No cure for inflation exists.", "인플레이션의 해결책이 없다."),
    "bribe": ("/braɪb/", "명사", "뇌물", "Officials accepted bribes.", "공무원들이 뇌물을 받았다."),
    "militia": ("/mɪˈlɪʃə/", "명사", "민병대", "The militia seized assets.", "민병대가 자산을 압수했다."),
    "wisdom": ("/ˈwɪzdəm/", "명사", "지혜", "Conventional wisdom was wrong.", "통념이 틀렸다."),
    "enact": ("/ɪˈnækt/", "동사", "제정하다, 시행하다", "New laws were enacted.", "새 법이 제정됐다."),
    "controller": ("/kənˈtroʊlər/", "명사", "감사, 재무 책임자", "The controller reviewed accounts.", "감사가 회계를 검토했다."),
    "shield": ("/ʃiːld/", "동사", "보호하다", "Hedges shield against loss.", "헤지가 손실을 보호한다."),
    "pact": ("/pækt/", "명사", "협정", "A trade pact was signed.", "무역 협정이 체결됐다."),
    "discretion": ("/dɪˈskreʃən/", "명사", "재량, 신중함", "Use discretion when investing.", "투자 시 재량을 발휘하세요."),
    "supervision": ("/ˌsuːpərˈvɪʒən/", "명사", "감독, 감시", "Financial supervision tightened.", "금융 감독이 강화됐다."),
    "dictate": ("/ˈdɪkteɪt/", "동사", "지시하다, 결정하다", "Markets dictate prices.", "시장이 가격을 결정한다."),
    "purely": ("/ˈpjʊərli/", "부사", "순전히, 전적으로", "Purely financial motives exist.", "순전히 재무적인 동기가 존재한다."),
}


def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT16:
                    pron, pos, meaning, ex_en, ex_ko = DICT16[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")


if __name__ == "__main__":
    print("=== Patching with fill_more16.py ===\n")
    patch_files()
