#!/usr/bin/env python3
"""Third-pass fill: covers freq-L3 remaining + L4 + TOEIC/BSL/NAWL top words."""
import json, glob

DICT3 = {
    # =========================================================
    # freq-L3 remaining (173 words)
    # =========================================================
    "pretty":      ("/ˈprɪti/", "부사", "꽤, 상당히", "It's pretty cold today.", "오늘 꽤 춥습니다."),
    "affect":      ("/əˈfɛkt/", "동사", "영향을 미치다", "Weather affects my mood.", "날씨가 내 기분에 영향을 미칩니다."),
    "drop":        ("/drɒp/", "동사", "떨어지다, 내리다", "Temperatures will drop tonight.", "오늘 밤 기온이 내려갈 것입니다."),
    "relate":      ("/rɪˈleɪt/", "동사", "관련되다, 이해하다", "How does this relate to our work?", "이것이 우리 일과 어떻게 관련됩니까?"),
    "art":         ("/ɑːrt/", "명사", "예술, 미술", "She studies fine art.", "그녀는 미술을 공부합니다."),
    "campaign":    ("/kæmˈpeɪn/", "명사", "캠페인, 운동", "The campaign was successful.", "캠페인이 성공적이었습니다."),
    "private":     ("/ˈpraɪvɪt/", "형용사", "사적인, 개인의", "This is a private matter.", "이것은 사적인 문제입니다."),
    "pause":       ("/pɔːz/", "동사", "멈추다, 잠시 쉬다", "Please pause the video.", "비디오를 잠시 멈춰 주세요."),
    "everyone":    ("/ˈɛvriˌwʌn/", "대명사", "모두, 모든 사람", "Everyone is welcome.", "모두 환영합니다."),
    "forget":      ("/fərˈɡɛt/", "동사", "잊다, 잊어버리다", "Don't forget your umbrella.", "우산을 잊지 마세요."),
    "page":        ("/peɪdʒ/", "명사", "페이지, 쪽", "Please turn to page 10.", "10페이지로 넘겨 주세요."),
    "worry":       ("/ˈwʌri/", "동사", "걱정하다", "Don't worry about it.", "그것에 대해 걱정하지 마세요."),
    "summer":      ("/ˈsʌmər/", "명사", "여름", "Summer is my favorite season.", "여름은 제가 가장 좋아하는 계절입니다."),
    "drink":       ("/drɪŋk/", "동사", "마시다", "Would you like something to drink?", "마실 것이 드릴까요?"),
    "park":        ("/pɑːrk/", "명사", "공원, 주차하다", "Let's have lunch in the park.", "공원에서 점심을 먹자."),
    "represent":   ("/ˌrɛprɪˈzɛnt/", "동사", "대표하다, 나타내다", "She represents our company.", "그녀는 우리 회사를 대표합니다."),
    "key":         ("/kiː/", "명사", "열쇠, 핵심", "Communication is the key.", "소통이 핵심입니다."),
    "inside":      ("/ˈɪnsaɪd/", "전치사", "안에, 내부에", "Please come inside.", "안으로 들어오세요."),
    "manager":     ("/ˈmænɪdʒər/", "명사", "관리자, 매니저", "Please speak to the manager.", "관리자에게 이야기해 주세요."),
    "international":("/ˌɪntərˈnæʃənəl/", "형용사", "국제적인", "This is an international event.", "이것은 국제 행사입니다."),
    "contain":     ("/kənˈteɪn/", "동사", "포함하다, 담다", "This bag contains my lunch.", "이 가방에는 제 점심이 들어 있습니다."),
    "notice":      ("/ˈnoʊtɪs/", "동사", "알아채다, 주목하다", "Did you notice the sign?", "표지판을 알아챘나요?"),
    "wonder":      ("/ˈwʌndər/", "동사", "궁금해하다, 이상하게 여기다", "I wonder what time it is.", "몇 시인지 궁금합니다."),
    "nature":      ("/ˈneɪtʃər/", "명사", "자연, 본성", "I love spending time in nature.", "저는 자연에서 시간을 보내는 것을 좋아합니다."),
    "section":     ("/ˈsɛkʃən/", "명사", "부분, 구역", "Go to the sports section.", "스포츠 구역으로 가세요."),
    "myself":      ("/maɪˈsɛlf/", "대명사", "나 자신, 스스로", "I did it myself.", "저 혼자 했습니다."),
    "plant":       ("/plænt/", "명사", "식물, 공장", "She waters the plants daily.", "그녀는 매일 식물에 물을 줍니다."),
    "paint":       ("/peɪnt/", "동사", "그리다, 칠하다", "She loves to paint.", "그녀는 그림 그리기를 좋아합니다."),
    "worker":      ("/ˈwɜːrkər/", "명사", "근로자, 직원", "The workers are on strike.", "근로자들이 파업 중입니다."),
    "press":       ("/prɛs/", "동사", "누르다, 압박하다", "Press the button.", "버튼을 누르세요."),
    "whatever":    ("/wɒtˈɛvər/", "대명사", "무엇이든, 어떤 것이든", "Do whatever you want.", "원하는 것은 무엇이든 하세요."),
    "region":      ("/ˈriːdʒən/", "명사", "지역, 지방", "This region is famous for wine.", "이 지역은 와인으로 유명합니다."),
    "growth":      ("/ɡroʊθ/", "명사", "성장, 증가", "The growth rate is impressive.", "성장률이 인상적입니다."),
    "influence":   ("/ˈɪnfluəns/", "명사", "영향, 영향력", "She has a great influence.", "그녀는 큰 영향력을 가지고 있습니다."),
    "respect":     ("/rɪˈspɛkt/", "명사", "존중, 경의", "I have great respect for you.", "저는 당신을 매우 존중합니다."),
    "catch":       ("/kætʃ/", "동사", "잡다, 타다", "Catch the ball!", "공을 잡으세요!"),
    "thus":        ("/ðʌs/", "부사", "따라서, 그러므로", "Thus, we can conclude...", "따라서, 우리는 ~라고 결론 지을 수 있습니다."),
    "skill":       ("/skɪl/", "명사", "기술, 능력", "Communication is an important skill.", "소통은 중요한 기술입니다."),
    "attempt":     ("/əˈtɛmpt/", "동사", "시도하다, 시도", "Please attempt the problem.", "문제를 시도해 보세요."),
    "son":         ("/sʌn/", "명사", "아들", "His son is five years old.", "그의 아들은 다섯 살입니다."),
    "simple":      ("/ˈsɪmpəl/", "형용사", "단순한, 간단한", "The solution is simple.", "해결책은 간단합니다."),
    "medium":      ("/ˈmiːdiəm/", "형용사", "중간의, 보통의", "I'd like a medium coffee.", "중간 사이즈 커피를 주세요."),
    "average":     ("/ˈævərɪdʒ/", "명사", "평균", "The average score is 75.", "평균 점수는 75점입니다."),
    "stock":       ("/stɒk/", "명사", "주식, 재고", "Stock prices went up.", "주가가 올랐습니다."),
    "management":  ("/ˈmænɪdʒmənt/", "명사", "경영, 관리", "Good management is key.", "좋은 경영이 핵심입니다."),
    "character":   ("/ˈkærɪktər/", "명사", "성격, 등장인물", "She has a strong character.", "그녀는 강한 성격을 가지고 있습니다."),
    "bed":         ("/bɛd/", "명사", "침대", "I need to go to bed.", "잠을 자러 가야 합니다."),
    "hit":         ("/hɪt/", "동사", "치다, 맞히다", "The ball hit the window.", "공이 창문을 쳤습니다."),
    "establish":   ("/ɪˈstæblɪʃ/", "동사", "설립하다, 확립하다", "The company was established in 1990.", "그 회사는 1990년에 설립되었습니다."),
    "indeed":      ("/ɪnˈdiːd/", "부사", "실제로, 정말로", "It is indeed a problem.", "그것은 실제로 문제입니다."),
    "final":       ("/ˈfaɪnəl/", "형용사", "마지막의, 최종의", "This is the final answer.", "이것이 최종 답입니다."),
    "economy":     ("/ɪˈkɒnəmi/", "명사", "경제", "The economy is growing.", "경제가 성장하고 있습니다."),
    "fit":         ("/fɪt/", "형용사", "건강한, 맞는", "These shoes fit perfectly.", "이 신발이 딱 맞습니다."),
    "guy":         ("/ɡaɪ/", "명사", "남자, 녀석", "He's a nice guy.", "그는 좋은 사람입니다."),
    "function":    ("/ˈfʌŋkʃən/", "명사", "기능, 역할", "What is the function of this?", "이것의 기능이 무엇인가요?"),
    "yesterday":   ("/ˈjɛstərdeɪ/", "부사", "어제", "I saw her yesterday.", "저는 어제 그녀를 봤습니다."),
    "image":       ("/ˈɪmɪdʒ/", "명사", "이미지, 이미지", "The image is clear.", "이미지가 선명합니다."),
    "size":        ("/saɪz/", "명사", "크기, 사이즈", "What size do you need?", "어떤 사이즈가 필요하신가요?"),
    "behavior":    ("/bɪˈheɪvjər/", "명사", "행동, 행동거지", "His behavior is polite.", "그의 행동이 예의 바릅니다."),
    "addition":    ("/əˈdɪʃən/", "명사", "추가, 더하기", "In addition, we need to...", "게다가, 우리는 ~해야 합니다."),
    "determine":   ("/dɪˈtɜːrmɪn/", "동사", "결정하다, 알아내다", "We need to determine the cause.", "원인을 알아내야 합니다."),
    "station":     ("/ˈsteɪʃən/", "명사", "역, 방송국", "The train station is nearby.", "기차역이 근처에 있습니다."),
    "population":  ("/ˌpɒpjʊˈleɪʃən/", "명사", "인구", "The city's population is 3 million.", "그 도시의 인구는 300만입니다."),
    "fail":        ("/feɪl/", "동사", "실패하다, 불합격하다", "Don't be afraid to fail.", "실패를 두려워하지 마세요."),
    "production":  ("/prəˈdʌkʃən/", "명사", "생산, 제작", "Production has increased.", "생산이 증가했습니다."),
    "player":      ("/ˈpleɪər/", "명사", "선수, 플레이어", "She's a great player.", "그녀는 훌륭한 선수입니다."),
    "comment":     ("/ˈkɒmɛnt/", "명사", "댓글, 의견", "Please leave a comment.", "댓글을 남겨 주세요."),
    "occur":       ("/əˈkɜːr/", "동사", "발생하다, 일어나다", "When did the accident occur?", "사고가 언제 발생했나요?"),
    "alone":       ("/əˈloʊn/", "형용사", "혼자의, 홀로", "I live alone.", "저는 혼자 삽니다."),
    "drug":        ("/drʌɡ/", "명사", "약, 마약", "Take this drug twice daily.", "이 약을 하루에 두 번 복용하세요."),
    "wall":        ("/wɔːl/", "명사", "벽, 담", "The picture is on the wall.", "그림이 벽에 있습니다."),
    "series":      ("/ˈsɪəriːz/", "명사", "시리즈, 연속", "It's a popular TV series.", "그것은 인기 있는 TV 시리즈입니다."),
    "direct":      ("/dɪˈrɛkt/", "형용사", "직접적인, 직행의", "Take the direct route.", "직행 경로를 이용하세요."),
    "tomorrow":    ("/təˈmɒroʊ/", "부사", "내일", "See you tomorrow!", "내일 봐요!"),
    "director":    ("/dɪˈrɛktər/", "명사", "이사, 감독", "The director made a great film.", "그 감독은 훌륭한 영화를 만들었습니다."),
    "clearly":     ("/ˈklɪərli/", "부사", "명확하게, 분명히", "Please speak clearly.", "명확하게 말씀해 주세요."),
    "lack":        ("/læk/", "명사", "부족, 결핍", "There is a lack of water.", "물 부족이 있습니다."),
    "review":      ("/rɪˈvjuː/", "명사", "검토, 리뷰", "Please review this document.", "이 문서를 검토해 주세요."),
    "depend":      ("/dɪˈpɛnd/", "동사", "의존하다, ~에 달려 있다", "It depends on the weather.", "날씨에 달려 있습니다."),
    "race":        ("/reɪs/", "명사", "경주, 인종", "She won the race.", "그녀가 경주에서 이겼습니다."),
    "department":  ("/dɪˈpɑːrtmənt/", "명사", "부서, 학과", "Which department do you work in?", "어느 부서에서 일하시나요?"),
    "gain":        ("/ɡeɪn/", "동사", "얻다, 증가하다", "She gained valuable experience.", "그녀는 귀중한 경험을 얻었습니다."),
    "tree":        ("/triː/", "명사", "나무", "There's a big tree in the garden.", "정원에 큰 나무가 있습니다."),
    "college":     ("/ˈkɒlɪdʒ/", "명사", "대학, 전문대학", "She goes to college.", "그녀는 대학에 다닙니다."),
    "argue":       ("/ˈɑːrɡjuː/", "동사", "주장하다, 다투다", "They argued about the price.", "그들은 가격에 대해 다퉜습니다."),
    "board":       ("/bɔːrd/", "명사", "이사회, 판자", "The board approved the plan.", "이사회가 계획을 승인했습니다."),
    "holiday":     ("/ˈhɒlɪdeɪ/", "명사", "휴일, 공휴일", "Tomorrow is a public holiday.", "내일은 공휴일입니다."),
    "mark":        ("/mɑːrk/", "명사", "표시, 점수", "She got full marks.", "그녀는 만점을 받았습니다."),
    "church":      ("/tʃɜːrtʃ/", "명사", "교회", "The church is downtown.", "교회는 시내에 있습니다."),
    "machine":     ("/məˈʃiːn/", "명사", "기계, 장치", "The machine is broken.", "기계가 고장났습니다."),
    "item":        ("/ˈaɪtəm/", "명사", "항목, 품목", "This item is out of stock.", "이 품목은 품절입니다."),
    "prove":       ("/pruːv/", "동사", "증명하다, 입증하다", "Can you prove it?", "그것을 증명할 수 있나요?"),
    "cent":        ("/sɛnt/", "명사", "센트", "It costs fifty cents.", "50센트입니다."),
    "season":      ("/ˈsiːzən/", "명사", "계절, 시즌", "Spring is my favorite season.", "봄은 제가 가장 좋아하는 계절입니다."),
    "stuff":       ("/stʌf/", "명사", "물건, 것들", "What is all this stuff?", "이 모든 것들이 뭔가요?"),
    "wide":        ("/waɪd/", "형용사", "넓은, 폭넓은", "The road is very wide.", "도로가 매우 넓습니다."),
    "anyone":      ("/ˈɛniˌwʌn/", "대명사", "누구나, 아무도", "Is anyone home?", "집에 누구 있나요?"),
    "election":    ("/ɪˈlɛkʃən/", "명사", "선거", "The election is next month.", "선거가 다음 달입니다."),
    "military":    ("/ˈmɪlɪtəri/", "형용사", "군사의, 군의", "He served in the military.", "그는 군에서 복무했습니다."),
    "hotel":       ("/hoʊˈtɛl/", "명사", "호텔", "We stayed at a nice hotel.", "우리는 좋은 호텔에 묵었습니다."),
    "club":        ("/klʌb/", "명사", "클럽, 동아리", "She joined the book club.", "그녀는 독서 클럽에 가입했습니다."),
    "movie":       ("/ˈmuːvi/", "명사", "영화", "Let's watch a movie.", "영화를 봅시다."),
    "doctor":      ("/ˈdɒktər/", "명사", "의사, 박사", "I need to see a doctor.", "의사에게 진찰받아야 합니다."),
    "discussion":  ("/dɪˈskʌʃən/", "명사", "토론, 의논", "Let's have a discussion.", "토론을 합시다."),
    "sorry":       ("/ˈsɒri/", "형용사", "미안한, 유감스러운", "I'm sorry for the delay.", "지연에 대해 죄송합니다."),
    "challenge":   ("/ˈtʃælɪndʒ/", "명사", "도전, 과제", "Every challenge is an opportunity.", "모든 도전은 기회입니다."),
    "nation":      ("/ˈneɪʃən/", "명사", "나라, 국가", "The whole nation celebrated.", "온 나라가 축하했습니다."),
    "nearly":      ("/ˈnɪərli/", "부사", "거의, 대략", "It's nearly midnight.", "거의 자정입니다."),
    "statement":   ("/ˈsteɪtmənt/", "명사", "진술, 성명", "Please make a statement.", "진술해 주세요."),
    "link":        ("/lɪŋk/", "명사", "연결, 링크", "Click the link below.", "아래 링크를 클릭하세요."),
    "introduce":   ("/ˌɪntrəˈdjuːs/", "동사", "소개하다, 도입하다", "Let me introduce myself.", "제 소개를 하겠습니다."),
    "advantage":   ("/ədˈvɑːntɪdʒ/", "명사", "유리함, 이점", "There are many advantages.", "많은 이점이 있습니다."),
    "marry":       ("/ˈmæri/", "동사", "결혼하다", "They married last summer.", "그들은 지난 여름에 결혼했습니다."),
    "strike":      ("/straɪk/", "동사", "치다, 파업하다", "Workers went on strike.", "근로자들이 파업을 했습니다."),
    "mile":        ("/maɪl/", "명사", "마일(거리 단위)", "It's only a mile away.", "겨우 1마일 거리입니다."),
    "seek":        ("/siːk/", "동사", "찾다, 추구하다", "We seek your feedback.", "여러분의 피드백을 구합니다."),
    "ability":     ("/əˈbɪlɪti/", "명사", "능력, 재능", "She has great ability.", "그녀는 뛰어난 능력을 가지고 있습니다."),
    "unit":        ("/ˈjuːnɪt/", "명사", "단위, 유닛", "Please complete unit 3.", "3단원을 완성하세요."),
    "card":        ("/kɑːrd/", "명사", "카드", "Do you have a business card?", "명함이 있으신가요?"),
    "hospital":    ("/ˈhɒspɪtəl/", "명사", "병원", "She was taken to the hospital.", "그녀는 병원에 이송되었습니다."),
    "quickly":     ("/ˈkwɪkli/", "부사", "빨리, 신속하게", "Please respond quickly.", "빨리 응답해 주세요."),
    "interview":   ("/ˈɪntərvjuː/", "명사", "인터뷰, 면접", "I have a job interview today.", "오늘 취업 면접이 있습니다."),
    "agreement":   ("/əˈɡriːmənt/", "명사", "합의, 동의", "We reached an agreement.", "우리는 합의에 도달했습니다."),
    "release":     ("/rɪˈliːs/", "동사", "발표하다, 공개하다", "They will release a new album.", "그들은 새 앨범을 발표할 것입니다."),
    "tax":         ("/tæks/", "명사", "세금", "The tax rate is 10%.", "세율은 10%입니다."),
    "solution":    ("/səˈluːʃən/", "명사", "해결책, 해답", "We need a solution.", "해결책이 필요합니다."),
    "capital":     ("/ˈkæpɪtəl/", "명사", "수도, 자본", "Seoul is the capital of Korea.", "서울은 한국의 수도입니다."),
    "beautiful":   ("/ˈbjuːtɪfəl/", "형용사", "아름다운", "What a beautiful view!", "정말 아름다운 경치네요!"),
    "fear":        ("/fɪər/", "명사", "두려움, 공포", "She overcame her fear.", "그녀는 두려움을 극복했습니다."),
    "aim":         ("/eɪm/", "명사", "목표, 목적", "What is your aim?", "목표가 무엇인가요?"),
    "television":  ("/ˈtɛlɪvɪʒən/", "명사", "텔레비전, TV", "I watch television every evening.", "저는 매일 저녁 텔레비전을 봅니다."),
    "target":      ("/ˈtɑːrɡɪt/", "명사", "목표, 대상", "We met our sales target.", "판매 목표를 달성했습니다."),
    "degree":      ("/dɪˈɡriː/", "명사", "학위, 정도, 도", "She has a degree in medicine.", "그녀는 의학 학위가 있습니다."),
    "pull":        ("/pʊl/", "동사", "당기다, 끌다", "Pull the door open.", "문을 당겨 여세요."),
    "red":         ("/rɛd/", "형용사", "빨간, 붉은", "She wore a red dress.", "그녀는 빨간 드레스를 입었습니다."),
    "husband":     ("/ˈhʌzbənd/", "명사", "남편", "Her husband is a teacher.", "그녀의 남편은 선생님입니다."),
    "movement":    ("/ˈmuːvmənt/", "명사", "운동, 움직임", "The peace movement grew.", "평화 운동이 성장했습니다."),
    "treat":       ("/triːt/", "동사", "대하다, 치료하다", "Treat others with respect.", "다른 사람을 존중하는 태도로 대하세요."),
    "identify":    ("/aɪˈdɛntɪfaɪ/", "동사", "확인하다, 식별하다", "Can you identify the problem?", "문제를 확인할 수 있나요?"),
    "loss":        ("/lɒs/", "명사", "손실, 상실", "The company reported a loss.", "회사가 손실을 보고했습니다."),
    "shall":       ("/ʃæl/", "조동사", "~할 것이다, ~하겠다", "Shall we begin?", "시작할까요?"),
    "modern":      ("/ˈmɒdərn/", "형용사", "현대의, 현대적인", "She prefers modern design.", "그녀는 현대적인 디자인을 선호합니다."),
    "pressure":    ("/ˈprɛʃər/", "명사", "압력, 부담", "He works well under pressure.", "그는 압박 속에서도 잘 일합니다."),
    "bus":         ("/bʌs/", "명사", "버스", "The bus is on time.", "버스가 제때 옵니다."),
    "treatment":   ("/ˈtriːtmənt/", "명사", "치료, 처우", "The treatment was effective.", "치료가 효과적이었습니다."),
    "yourself":    ("/jɔːrˈsɛlf/", "대명사", "당신 자신, 스스로", "Do it yourself.", "스스로 하세요."),
    "supply":      ("/səˈplaɪ/", "명사", "공급, 물자", "The supply is limited.", "공급이 제한적입니다."),
    "village":     ("/ˈvɪlɪdʒ/", "명사", "마을, 촌", "She grew up in a small village.", "그녀는 작은 마을에서 자랐습니다."),
    "worth":       ("/wɜːrθ/", "형용사", "~의 가치가 있는", "It's worth the effort.", "노력할 가치가 있습니다."),
    "express":     ("/ɪkˈsprɛs/", "동사", "표현하다, 나타내다", "How do you express gratitude?", "감사를 어떻게 표현하나요?"),
    "attend":      ("/əˈtɛnd/", "동사", "참석하다, 다니다", "Please attend the meeting.", "회의에 참석해 주세요."),
    "brother":     ("/ˈbrʌðər/", "명사", "형제, 남자 형제", "My brother lives in Busan.", "제 형제는 부산에 삽니다."),
    "investment":  ("/ɪnˈvɛstmənt/", "명사", "투자", "This is a good investment.", "이것은 좋은 투자입니다."),
    "score":       ("/skɔːr/", "명사", "점수, 스코어", "What was the final score?", "최종 점수가 어떻게 됐나요?"),
    "organize":    ("/ˈɔːrɡənaɪz/", "동사", "정리하다, 조직하다", "I need to organize my files.", "파일을 정리해야 합니다."),
    "trip":        ("/trɪp/", "명사", "여행, 출장", "We're planning a trip.", "여행을 계획하고 있습니다."),
    "beyond":      ("/bɪˈɒnd/", "전치사", "~너머, ~을 초월하여", "It's beyond my understanding.", "제 이해를 넘어서는 일입니다."),
    "sleep":       ("/sliːp/", "동사", "자다, 수면하다", "I need to sleep.", "자야 합니다."),
    "fish":        ("/fɪʃ/", "명사", "물고기, 생선", "I like grilled fish.", "저는 생선구이를 좋아합니다."),
    "promise":     ("/ˈprɒmɪs/", "명사", "약속", "I promise to be there.", "거기 있을 것을 약속합니다."),
    "potential":   ("/pəˈtɛnʃəl/", "명사", "잠재력, 가능성", "She has great potential.", "그녀는 큰 잠재력이 있습니다."),
    "energy":      ("/ˈɛnərdʒi/", "명사", "에너지, 활력", "I have a lot of energy today.", "오늘 에너지가 넘칩니다."),
    "trouble":     ("/ˈtrʌbəl/", "명사", "어려움, 문제", "I'm in trouble.", "저는 어려움에 처해 있습니다."),
    "relation":    ("/rɪˈleɪʃən/", "명사", "관계, 관련", "What is his relation to you?", "그는 당신과 어떤 관계인가요?"),
    "touch":       ("/tʌtʃ/", "동사", "만지다, 감동시키다", "Don't touch the exhibit.", "전시품을 만지지 마세요."),
    "file":        ("/faɪl/", "명사", "파일, 서류", "Please send me the file.", "파일을 보내 주세요."),
    "middle":      ("/ˈmɪdəl/", "명사", "중간, 가운데", "She sat in the middle.", "그녀는 가운데에 앉았습니다."),
    "bar":         ("/bɑːr/", "명사", "바, 막대기", "Let's meet at the bar.", "바에서 만납시다."),
    "suffer":      ("/ˈsʌfər/", "동사", "고통받다, 겪다", "Many people suffer from allergies.", "많은 사람들이 알레르기로 고통받습니다."),
    "deep":        ("/diːp/", "형용사", "깊은, 심오한", "The lake is very deep.", "호수가 매우 깊습니다."),
    "except":      ("/ɪkˈsɛpt/", "전치사", "~을 제외하고", "Everyone came except Tom.", "톰을 제외한 모든 사람이 왔습니다."),
    "clean":       ("/kliːn/", "형용사", "깨끗한, 청결한", "Please keep this area clean.", "이 구역을 깨끗하게 유지해 주세요."),
    "tend":        ("/tɛnd/", "동사", "경향이 있다, 돌보다", "I tend to wake up early.", "저는 일찍 일어나는 경향이 있습니다."),
    # =========================================================
    # freq-L4 + L5 additional common words
    # =========================================================
    "award":       ("/əˈwɔːrd/", "명사", "상, 수여", "She won an award.", "그녀가 상을 받았습니다."),
    "share":       ("/ʃɛər/", "동사", "공유하다, 나누다", "Please share your ideas.", "아이디어를 공유해 주세요."),
    "society":     ("/səˈsaɪəti/", "명사", "사회", "Society is changing.", "사회가 변화하고 있습니다."),
    "speak":       ("/spiːk/", "동사", "말하다", "Can you speak English?", "영어를 할 수 있나요?"),
    "run":         ("/rʌn/", "동사", "달리다, 운영하다", "I run every morning.", "저는 매일 아침 달립니다."),
    "international":("/ˌɪntərˈnæʃənəl/", "형용사", "국제적인", "This is an international company.", "이것은 국제 회사입니다."),
    "suddenly":    ("/ˈsʌdənli/", "부사", "갑자기, 갑작스럽게", "It suddenly started to rain.", "갑자기 비가 내리기 시작했습니다."),
    "foreign":     ("/ˈfɒrɪn/", "형용사", "외국의", "I like foreign films.", "저는 외국 영화를 좋아합니다."),
    "concern":     ("/kənˈsɜːrn/", "명사", "걱정, 관심사", "This is a concern.", "이것이 걱정입니다."),
    "prevent":     ("/prɪˈvɛnt/", "동사", "막다, 예방하다", "Exercise can prevent disease.", "운동이 질병을 예방할 수 있습니다."),
    "difference":  ("/ˈdɪfərəns/", "명사", "차이, 다름", "What's the difference?", "차이가 뭔가요?"),
    "across":      ("/əˈkrɒs/", "전치사", "가로질러, 건너", "Walk across the street.", "길을 건너세요."),
    "conference":  ("/ˈkɒnfərəns/", "명사", "회의, 학회", "I have a conference call.", "컨퍼런스 콜이 있습니다."),
    "protect":     ("/prəˈtɛkt/", "동사", "보호하다, 지키다", "We must protect the environment.", "환경을 보호해야 합니다."),
    "success":     ("/səkˈsɛs/", "명사", "성공", "I wish you success.", "성공을 빕니다."),
    "admit":       ("/ədˈmɪt/", "동사", "인정하다, 입장을 허가하다", "He admitted his mistake.", "그는 실수를 인정했습니다."),
    "basic":       ("/ˈbeɪsɪk/", "형용사", "기본적인, 기초적인", "These are basic rules.", "이것들은 기본 규칙입니다."),
    "challenge":   ("/ˈtʃælɪndʒ/", "명사", "도전, 과제", "This is a great challenge.", "이것은 큰 도전입니다."),
    "option":      ("/ˈɒpʃən/", "명사", "선택, 옵션", "You have two options.", "두 가지 선택지가 있습니다."),
    "language":    ("/ˈlæŋɡwɪdʒ/", "명사", "언어", "Learning a new language is fun.", "새로운 언어를 배우는 것은 재미있습니다."),
    "science":     ("/ˈsaɪəns/", "명사", "과학", "She loves science.", "그녀는 과학을 좋아합니다."),
    "healthy":     ("/ˈhɛlθi/", "형용사", "건강한", "Eat healthy food.", "건강한 음식을 드세요."),
    "office":      ("/ˈɒfɪs/", "명사", "사무실, 직무", "I work in an office.", "저는 사무실에서 일합니다."),
    "internet":    ("/ˈɪntərˌnɛt/", "명사", "인터넷", "The internet is very useful.", "인터넷은 매우 유용합니다."),
    "begin":       ("/bɪˈɡɪn/", "동사", "시작하다", "Let's begin.", "시작합시다."),
    "send":        ("/sɛnd/", "동사", "보내다", "Please send me an email.", "이메일을 보내 주세요."),
    "wait":        ("/weɪt/", "동사", "기다리다", "Please wait a moment.", "잠시 기다려 주세요."),
    "understand":  ("/ˌʌndərˈstænd/", "동사", "이해하다", "I understand your concern.", "당신의 걱정을 이해합니다."),
    "report":      ("/rɪˈpɔːrt/", "명사", "보고서, 보도", "Submit the report by Friday.", "금요일까지 보고서를 제출하세요."),
    "newspaper":   ("/ˈnjuːzˌpeɪpər/", "명사", "신문", "I read the newspaper every morning.", "저는 매일 아침 신문을 읽습니다."),
    "accept":      ("/əkˈsɛpt/", "동사", "받아들이다, 수락하다", "I accept your offer.", "제안을 수락합니다."),
    "leader":      ("/ˈliːdər/", "명사", "지도자, 리더", "She is a natural leader.", "그녀는 타고난 지도자입니다."),
    "customer":    ("/ˈkʌstəmər/", "명사", "고객", "Satisfy your customers.", "고객을 만족시키세요."),
    "environment": ("/ɪnˈvaɪrənmənt/", "명사", "환경", "Protect the environment.", "환경을 보호하세요."),
    "moment":      ("/ˈmoʊmənt/", "명사", "순간, 잠깐", "Just a moment, please.", "잠깐만요."),
    "toward":      ("/tɔːrd/", "전치사", "~쪽으로", "Move toward the door.", "문 쪽으로 이동하세요."),
    "include":     ("/ɪnˈkluːd/", "동사", "포함하다", "Please include your name.", "이름을 포함해 주세요."),
    "produce":     ("/prəˈdjuːs/", "동사", "생산하다", "We produce high-quality goods.", "저희는 고품질 상품을 생산합니다."),
    "partner":     ("/ˈpɑːrtnər/", "명사", "파트너, 동료", "She is my business partner.", "그녀는 제 사업 파트너입니다."),
    "allow":       ("/əˈlaʊ/", "동사", "허용하다, 허락하다", "Please allow me to explain.", "설명할 수 있도록 허락해 주세요."),
    "expect":      ("/ɪkˈspɛkt/", "동사", "예상하다, 기대하다", "I expect a positive result.", "긍정적인 결과를 기대합니다."),
    "offer":       ("/ˈɒfər/", "동사", "제공하다, 제안하다", "Let me offer some advice.", "조언을 드리겠습니다."),
    "past":        ("/pɑːst/", "명사", "과거, 지난날", "Let's learn from the past.", "과거로부터 배웁시다."),
    "suddenly":    ("/ˈsʌdənli/", "부사", "갑자기", "It suddenly rained.", "갑자기 비가 왔습니다."),
    "technology":  ("/tɛkˈnɒlədʒi/", "명사", "기술", "Technology is advancing fast.", "기술이 빠르게 발전하고 있습니다."),
    "build":       ("/bɪld/", "동사", "짓다, 구축하다", "We will build a new office.", "새 사무실을 지을 것입니다."),
    "relationship":("/rɪˈleɪʃənʃɪp/", "명사", "관계", "Build good relationships.", "좋은 관계를 구축하세요."),
    "physical":    ("/ˈfɪzɪkəl/", "형용사", "신체적인, 물리적인", "Physical exercise is important.", "신체 운동이 중요합니다."),
    "provide":     ("/prəˈvaɪd/", "동사", "제공하다", "We provide support.", "저희는 지원을 제공합니다."),
    "reach":       ("/riːtʃ/", "동사", "도달하다, 닿다", "We need to reach our goal.", "목표에 도달해야 합니다."),
    "government":  ("/ˈɡʌvərmənt/", "명사", "정부", "The government announced new policies.", "정부가 새 정책을 발표했습니다."),
    "program":     ("/ˈproʊɡræm/", "명사", "프로그램", "This program is very helpful.", "이 프로그램이 매우 유용합니다."),
    "number":      ("/ˈnʌmbər/", "명사", "숫자, 번호", "What is your phone number?", "전화번호가 무엇인가요?"),
    "street":      ("/striːt/", "명사", "거리, 길", "She lives on this street.", "그녀는 이 거리에 삽니다."),
    "light":       ("/laɪt/", "명사", "빛, 빛나다", "The light is too bright.", "빛이 너무 밝습니다."),
    "different":   ("/ˈdɪfərənt/", "형용사", "다른, 여러 가지의", "We are all different.", "우리는 모두 다릅니다."),
    "speak":       ("/spiːk/", "동사", "말하다", "Please speak slowly.", "천천히 말씀해 주세요."),
    "amount":      ("/əˈmaʊnt/", "명사", "양, 금액", "The total amount is $100.", "총 금액은 100달러입니다."),
    "entire":      ("/ɪnˈtaɪər/", "형용사", "전체의, 완전한", "The entire team worked hard.", "팀 전체가 열심히 일했습니다."),
    "strong":      ("/strɒŋ/", "형용사", "강한, 튼튼한", "Be strong!", "강해지세요!"),
    "medical":     ("/ˈmɛdɪkəl/", "형용사", "의료의, 의학적인", "I need medical attention.", "의료 조치가 필요합니다."),
    "cost":        ("/kɒst/", "명사", "비용, 원가", "What is the cost?", "비용이 얼마인가요?"),
    "mind":        ("/maɪnd/", "명사", "마음, 생각", "Keep an open mind.", "열린 마음을 가지세요."),
    "leader":      ("/ˈliːdər/", "명사", "지도자", "A good leader listens.", "좋은 지도자는 경청합니다."),
    "community":   ("/kəˈmjuːnɪti/", "명사", "공동체", "Community support is essential.", "지역사회 지원이 필수적입니다."),
    "answer":      ("/ˈɑːnsər/", "명사", "답, 대답", "What is the answer?", "정답이 무엇인가요?"),
    "picture":     ("/ˈpɪktʃər/", "명사", "사진, 그림", "Take a picture here.", "여기서 사진을 찍으세요."),
    "carry":       ("/ˈkæri/", "동사", "나르다, 가지고 다니다", "Can you carry this bag?", "이 가방을 들 수 있나요?"),
    "class":       ("/klɑːs/", "명사", "수업, 학급", "The class starts at 9.", "수업은 9시에 시작합니다."),
    "decision":    ("/dɪˈsɪʒən/", "명사", "결정", "Make a wise decision.", "현명한 결정을 내리세요."),
    "spend":       ("/spɛnd/", "동사", "쓰다, 소비하다", "Don't spend too much.", "너무 많이 쓰지 마세요."),
    "concern":     ("/kənˈsɜːrn/", "명사", "걱정, 관심", "That's my main concern.", "그것이 주된 걱정입니다."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT3:
                    pron, pos, meaning, ex_en, ex_ko = DICT3[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more2.py ===\n")
    patch_files()
