#!/usr/bin/env python3
"""Eighth-pass fill: freq-L6 last 3 + freq-L7 (266 words)."""
import json, glob

DICT8 = {
    # freq-L6 last 3
    "sexual":      ("/ˈsɛkʃuəl/", "형용사", "성적인, 성별의", "Respect sexual boundaries.", "성적 경계를 존중하세요."),
    "import":      ("/ˈɪmpɔːrt/", "동사", "수입하다", "We import goods from Asia.", "우리는 아시아에서 물건을 수입합니다."),
    "cast":        ("/kɑːst/", "동사", "던지다, 배역을 맡기다", "Cast a wide net.", "범위를 넓히세요."),
    # =========================================================
    # freq-L7 (266 words)
    # =========================================================
    "passenger":   ("/ˈpæsɪndʒər/", "명사", "승객", "All passengers must board.", "모든 승객이 탑승해야 합니다."),
    "justice":     ("/ˈdʒʌstɪs/", "명사", "정의, 재판관", "Seek justice.", "정의를 추구하세요."),
    "phase":       ("/feɪz/", "명사", "단계, 국면", "We are in phase two.", "2단계에 있습니다."),
    "thin":        ("/θɪn/", "형용사", "얇은, 마른", "The wall is thin.", "벽이 얇습니다."),
    "rush":        ("/rʌʃ/", "동사", "서두르다, 급히 가다", "Don't rush.", "서두르지 마세요."),
    "formal":      ("/ˈfɔːrməl/", "형용사", "공식적인, 격식 있는", "Wear formal attire.", "정장을 착용하세요."),
    "religion":    ("/rɪˈlɪdʒən/", "명사", "종교", "Respect all religions.", "모든 종교를 존중하세요."),
    "employer":    ("/ɪmˈplɔɪər/", "명사", "고용주", "She is a fair employer.", "그녀는 공정한 고용주입니다."),
    "reject":      ("/rɪˈdʒɛkt/", "동사", "거부하다, 거절하다", "Don't reject new ideas.", "새로운 아이디어를 거부하지 마세요."),
    "latter":      ("/ˈlætər/", "형용사", "후자의, 마지막의", "I prefer the latter option.", "후자를 선호합니다."),
    "plate":       ("/pleɪt/", "명사", "접시, 판", "Pass me the plate.", "접시를 건네 주세요."),
    "ban":         ("/bæn/", "동사", "금지하다", "Smoking is banned here.", "여기서는 흡연이 금지됩니다."),
    "steal":       ("/stiːl/", "동사", "훔치다", "Don't steal.", "훔치지 마세요."),
    "protest":     ("/ˈproʊtɛst/", "동사", "항의하다, 반대하다", "They protested the decision.", "그들은 결정에 항의했습니다."),
    "index":       ("/ˈɪndɛks/", "명사", "색인, 지수", "Check the index.", "색인을 확인하세요."),
    "sad":         ("/sæd/", "형용사", "슬픈, 안타까운", "She looked sad.", "그녀는 슬퍼 보였습니다."),
    "frequently":  ("/ˈfriːkwəntli/", "부사", "자주, 빈번히", "She travels frequently.", "그녀는 자주 여행합니다."),
    "circle":      ("/ˈsɜːrkəl/", "명사", "원, 그룹", "Draw a circle.", "원을 그리세요."),
    "helpful":     ("/ˈhɛlpfəl/", "형용사", "도움이 되는", "Your advice was helpful.", "조언이 도움이 되었습니다."),
    "command":     ("/kəˈmɑːnd/", "명사", "명령, 지휘", "Give a command.", "명령을 내리세요."),
    "attractive":  ("/əˈtræktɪv/", "형용사", "매력적인", "She is very attractive.", "그녀는 매우 매력적입니다."),
    "sick":        ("/sɪk/", "형용사", "아픈, 병든", "She is sick.", "그녀는 아픕니다."),
    "impression":  ("/ɪmˈprɛʃən/", "명사", "인상, 영향", "Make a good impression.", "좋은 인상을 남기세요."),
    "unable":      ("/ʌnˈeɪbəl/", "형용사", "할 수 없는", "I'm unable to attend.", "참석할 수 없습니다."),
    "joke":        ("/dʒoʊk/", "명사", "농담", "That was a good joke.", "좋은 농담이었습니다."),
    "sky":         ("/skaɪ/", "명사", "하늘", "The sky is blue.", "하늘이 파랗습니다."),
    "column":      ("/ˈkɒləm/", "명사", "컬럼, 기둥", "Read the opinion column.", "의견 컬럼을 읽으세요."),
    "electronic":  ("/ɪˌlɛkˈtrɒnɪk/", "형용사", "전자의", "Electronic payments are easy.", "전자 결제가 쉽습니다."),
    "impose":      ("/ɪmˈpoʊz/", "동사", "부과하다, 강요하다", "Don't impose your views.", "견해를 강요하지 마세요."),
    "criminal":    ("/ˈkrɪmɪnəl/", "명사", "범죄자", "The criminal was caught.", "범죄자가 잡혔습니다."),
    "besides":     ("/bɪˈsaɪdz/", "부사", "게다가, ~외에도", "Besides, there is another option.", "게다가 다른 선택지도 있습니다."),
    "properly":    ("/ˈprɒpərli/", "부사", "제대로, 적절하게", "Do it properly.", "제대로 하세요."),
    "ancient":     ("/ˈeɪnʃənt/", "형용사", "고대의, 오래된", "An ancient temple.", "고대 사원."),
    "coast":       ("/koʊst/", "명사", "해안, 해변", "We drove along the coast.", "해안을 따라 운전했습니다."),
    "ill":         ("/ɪl/", "형용사", "아픈, 병든", "He is seriously ill.", "그는 심각하게 아픕니다."),
    "kick":        ("/kɪk/", "동사", "차다", "Kick the ball.", "공을 차세요."),
    "closely":     ("/ˈkloʊsli/", "부사", "가깝게, 면밀히", "Watch closely.", "주의 깊게 보세요."),
    "multiple":    ("/ˈmʌltɪpəl/", "형용사", "복수의, 다중의", "Multiple options available.", "여러 가지 선택지가 있습니다."),
    "yield":       ("/jiːld/", "동사", "산출하다, 양보하다", "Yield to the right.", "오른쪽에 양보하세요."),
    "via":         ("/ˈvaɪə/", "전치사", "~을 통해, 경유하여", "Send it via email.", "이메일로 보내세요."),
    "legislation": ("/ˌlɛdʒɪˈsleɪʃən/", "명사", "입법, 법률", "New legislation was passed.", "새 법률이 통과되었습니다."),
    "county":      ("/ˈkaʊnti/", "명사", "카운티, 주", "She lives in the county.", "그녀는 카운티에 삽니다."),
    "unlike":      ("/ʌnˈlaɪk/", "전치사", "~와 달리", "Unlike others, she is calm.", "다른 사람들과 달리 그녀는 침착합니다."),
    "mobile":      ("/ˈmoʊbaɪl/", "형용사", "이동식의, 휴대용의", "Use mobile banking.", "모바일 뱅킹을 이용하세요."),
    "assistant":   ("/əˈsɪstənt/", "명사", "조수, 보조원", "My assistant handled it.", "제 보조원이 처리했습니다."),
    "chart":       ("/tʃɑːrt/", "명사", "차트, 도표", "Read the chart.", "차트를 읽으세요."),
    "attach":      ("/əˈtætʃ/", "동사", "첨부하다, 붙이다", "Attach the file.", "파일을 첨부하세요."),
    "everywhere":  ("/ˈɛvrɪwɛər/", "부사", "어디에나, 도처에", "She is known everywhere.", "그녀는 어디서나 알려져 있습니다."),
    "advise":      ("/ədˈvaɪz/", "동사", "조언하다, 권고하다", "I advise you to rest.", "쉬라고 조언드립니다."),
    "household":   ("/ˈhaʊshoʊld/", "명사", "가구, 가정", "Average household income.", "평균 가구 소득."),
    "reward":      ("/rɪˈwɔːrd/", "명사", "보상, 포상", "You deserve a reward.", "보상을 받을 자격이 있습니다."),
    "hat":         ("/hæt/", "명사", "모자", "Wear a hat in the sun.", "햇볕에는 모자를 쓰세요."),
    "academic":    ("/ˌækəˈdɛmɪk/", "형용사", "학문적인, 교육적인", "Academic performance improved.", "학업 성취가 향상되었습니다."),
    "voter":       ("/ˈvoʊtər/", "명사", "유권자", "All voters must register.", "모든 유권자는 등록해야 합니다."),
    "meanwhile":   ("/ˈmiːnwaɪl/", "부사", "그 동안에, 한편", "Meanwhile, she waited.", "한편 그녀는 기다렸습니다."),
    "accuse":      ("/əˈkjuːz/", "동사", "고발하다, 비난하다", "Don't accuse without proof.", "증거 없이 고발하지 마세요."),
    "scientific":  ("/ˌsaɪənˈtɪfɪk/", "형용사", "과학적인", "Scientific research is important.", "과학적 연구가 중요합니다."),
    "wage":        ("/weɪdʒ/", "명사", "임금, 급여", "Raise the minimum wage.", "최저 임금을 올리세요."),
    "absence":     ("/ˈæbsəns/", "명사", "부재, 결석", "Her absence was noticed.", "그녀의 부재가 눈에 띄었습니다."),
    "construct":   ("/kənˈstrʌkt/", "동사", "건설하다, 구성하다", "Construct a plan.", "계획을 세우세요."),
    "remark":      ("/rɪˈmɑːrk/", "명사", "발언, 언급", "He made an interesting remark.", "그는 흥미로운 발언을 했습니다."),
    "professor":   ("/prəˈfɛsər/", "명사", "교수", "The professor explained clearly.", "교수가 명확하게 설명했습니다."),
    "rare":        ("/rɛər/", "형용사", "드문, 희귀한", "This is a rare opportunity.", "이것은 드문 기회입니다."),
    "intention":   ("/ɪnˈtɛnʃən/", "명사", "의도, 목적", "My intention is good.", "제 의도는 선합니다."),
    "dozen":       ("/ˈdʌzən/", "명사", "12개, 다스", "A dozen eggs.", "달걀 한 다스."),
    "settlement":  ("/ˈsɛtəlmənt/", "명사", "합의, 정착", "They reached a settlement.", "합의에 도달했습니다."),
    "gap":         ("/ɡæp/", "명사", "차이, 격차", "Bridge the gap.", "격차를 줄이세요."),
    "widely":      ("/ˈwaɪdli/", "부사", "널리, 광범위하게", "This is widely known.", "이것은 널리 알려져 있습니다."),
    "minimum":     ("/ˈmɪnɪməm/", "명사", "최소, 최저", "Keep costs to a minimum.", "비용을 최소화하세요."),
    "northern":    ("/ˈnɔːrðərn/", "형용사", "북쪽의, 북방의", "She lives in the northern part.", "그녀는 북쪽 지역에 삽니다."),
    "estate":      ("/ɪˈsteɪt/", "명사", "부동산, 재산", "He inherited an estate.", "그는 재산을 물려받았습니다."),
    "equally":     ("/ˈiːkwəli/", "부사", "동등하게, 마찬가지로", "Treat everyone equally.", "모든 사람을 동등하게 대우하세요."),
    "expose":      ("/ɪkˈspoʊz/", "동사", "드러내다, 노출하다", "Expose the truth.", "진실을 드러내세요."),
    "alive":       ("/əˈlaɪv/", "형용사", "살아 있는", "Stay alive.", "살아 있어요."),
    "shut":        ("/ʃʌt/", "동사", "닫다, 잠그다", "Please shut the door.", "문을 닫아 주세요."),
    "victory":     ("/ˈvɪktəri/", "명사", "승리", "Celebrate the victory.", "승리를 축하하세요."),
    "resolve":     ("/rɪˈzɒlv/", "동사", "해결하다, 결심하다", "Resolve the conflict.", "갈등을 해결하세요."),
    "critic":      ("/ˈkrɪtɪk/", "명사", "비평가, 비판자", "She is a famous critic.", "그녀는 유명한 비평가입니다."),
    "enormous":    ("/ɪˈnɔːrməs/", "형용사", "거대한, 막대한", "There was enormous pressure.", "엄청난 압박이 있었습니다."),
    "sweet":       ("/swiːt/", "형용사", "달콤한", "The dessert is sweet.", "디저트가 달콤합니다."),
    "permanent":   ("/ˈpɜːrmənənt/", "형용사", "영구적인, 영속하는", "Is this permanent?", "이것이 영구적인가요?"),
    "emotion":     ("/ɪˈmoʊʃən/", "명사", "감정, 정서", "Express your emotions.", "감정을 표현하세요."),
    "pursue":      ("/pərˈsjuː/", "동사", "추구하다, 쫓다", "Pursue your dreams.", "꿈을 추구하세요."),
    "tall":        ("/tɔːl/", "형용사", "키가 큰", "She is tall.", "그녀는 키가 큽니다."),
    "urge":        ("/ɜːrdʒ/", "동사", "촉구하다, 강력히 권하다", "I urge you to reconsider.", "재고해 주시길 촉구합니다."),
    "enemy":       ("/ˈɛnəmi/", "명사", "적, 적군", "Keep your enemies close.", "적을 가까이 두세요."),
    "appoint":     ("/əˈpɔɪnt/", "동사", "임명하다", "She was appointed as director.", "그녀는 이사로 임명되었습니다."),
    "milk":        ("/mɪlk/", "명사", "우유", "Drink your milk.", "우유를 마시세요."),
    "talent":      ("/ˈtælənt/", "명사", "재능, 능력", "She has a natural talent.", "그녀는 타고난 재능이 있습니다."),
    "smell":       ("/smɛl/", "동사", "냄새를 맡다", "It smells good.", "좋은 냄새가 납니다."),
    "priority":    ("/praɪˈɒrɪti/", "명사", "우선순위", "Safety is a top priority.", "안전이 최우선입니다."),
    "online":      ("/ˈɒnlaɪn/", "형용사", "온라인의", "Shop online.", "온라인으로 쇼핑하세요."),
    "phrase":      ("/freɪz/", "명사", "구, 표현", "Use the correct phrase.", "올바른 표현을 사용하세요."),
    "pilot":       ("/ˈpaɪlɪt/", "명사", "조종사, 파일럿", "The pilot landed safely.", "조종사가 안전하게 착륙했습니다."),
    "stable":      ("/ˈsteɪbəl/", "형용사", "안정된, 견고한", "The economy is stable.", "경제가 안정되어 있습니다."),
    "merely":      ("/ˈmɪərli/", "부사", "단지, 그저", "I merely suggest.", "저는 그저 제안할 뿐입니다."),
    "resolution":  ("/ˌrɛzəˈluːʃən/", "명사", "결의, 해결책", "Make a New Year's resolution.", "새해 결심을 세우세요."),
    "communicate": ("/kəˈmjuːnɪkeɪt/", "동사", "의사소통하다", "Communicate clearly.", "명확하게 소통하세요."),
    "injury":      ("/ˈɪndʒəri/", "명사", "부상, 상해", "She recovered from injury.", "그녀는 부상에서 회복했습니다."),
    "vast":        ("/vɑːst/", "형용사", "광대한, 막대한", "A vast amount of data.", "막대한 양의 데이터."),
    "exhibition":  ("/ˌɛksɪˈbɪʃən/", "명사", "전시회, 박람회", "Visit the exhibition.", "전시회를 방문하세요."),
    "producer":    ("/prəˈdjuːsər/", "명사", "제작자, 생산자", "She is a TV producer.", "그녀는 TV 제작자입니다."),
    "regional":    ("/ˈriːdʒənəl/", "형용사", "지역의, 지방의", "Regional differences exist.", "지역적 차이가 있습니다."),
    "immediate":   ("/ɪˈmiːdiɪt/", "형용사", "즉각적인", "We need immediate action.", "즉각적인 조치가 필요합니다."),
    "incident":    ("/ˈɪnsɪdənt/", "명사", "사건, 사고", "Report the incident.", "사건을 보고하세요."),
    "childhood":   ("/ˈtʃaɪldˌhʊd/", "명사", "어린 시절", "Happy childhood memories.", "행복한 어린 시절 기억."),
    "draft":       ("/drɑːft/", "명사", "초안, 초고", "Send me the draft.", "초안을 보내 주세요."),
    "slip":        ("/slɪp/", "동사", "미끄러지다, 빠져나가다", "Watch your step, don't slip.", "발밑을 조심하세요."),
    "accompany":   ("/əˈkʌmpəni/", "동사", "동행하다, 수반하다", "Please accompany me.", "함께 가 주세요."),
    "politician":  ("/ˌpɒlɪˈtɪʃən/", "명사", "정치인", "She is an experienced politician.", "그녀는 경험 많은 정치인입니다."),
    "angry":       ("/ˈæŋɡri/", "형용사", "화난, 성난", "He was angry.", "그는 화가 났습니다."),
    "knock":       ("/nɒk/", "동사", "두드리다, 노크하다", "Knock before entering.", "들어가기 전에 노크하세요."),
    "seed":        ("/siːd/", "명사", "씨앗", "Plant a seed.", "씨앗을 심으세요."),
    "salary":      ("/ˈsæləri/", "명사", "급여, 연봉", "What is your salary?", "급여가 얼마인가요?"),
    "illustrate":  ("/ˈɪləstreɪt/", "동사", "설명하다, 그림을 그리다", "Let me illustrate this.", "이것을 설명해 드리겠습니다."),
    "imply":       ("/ɪmˈplaɪ/", "동사", "암시하다, 의미하다", "What does this imply?", "이것이 무엇을 의미하나요?"),
    "breakfast":   ("/ˈbrɛkfəst/", "명사", "아침 식사", "Eat a healthy breakfast.", "건강한 아침 식사를 하세요."),
    "temporary":   ("/ˈtɛmpərəri/", "형용사", "일시적인, 임시의", "This is temporary.", "이것은 임시적입니다."),
    "liberal":     ("/ˈlɪbərəl/", "형용사", "자유주의적인, 진보적인", "She has liberal views.", "그녀는 진보적인 견해를 가지고 있습니다."),
    "lake":        ("/leɪk/", "명사", "호수", "Let's swim in the lake.", "호수에서 수영하자."),
    "qualify":     ("/ˈkwɒlɪfaɪ/", "동사", "자격이 있다, 충족시키다", "Do you qualify?", "자격이 있나요?"),
    "competitive": ("/kəmˈpɛtɪtɪv/", "형용사", "경쟁적인", "The market is competitive.", "시장이 경쟁적입니다."),
    "truly":       ("/ˈtruːli/", "부사", "진정으로, 정말로", "I truly appreciate it.", "정말로 감사드립니다."),
    "hi":          ("/haɪ/", "감탄사", "안녕, 하이", "Hi, how are you?", "안녕하세요, 어떠세요?"),
    "yellow":      ("/ˈjɛloʊ/", "형용사", "노란, 황색의", "The sun is yellow.", "태양은 노랗습니다."),
    "habit":       ("/ˈhæbɪt/", "명사", "습관, 버릇", "Build good habits.", "좋은 습관을 기르세요."),
    "core":        ("/kɔːr/", "명사", "핵심, 중심부", "Core values matter.", "핵심 가치가 중요합니다."),
    "emotional":   ("/ɪˈmoʊʃənəl/", "형용사", "감정적인, 정서적인", "She is emotionally intelligent.", "그녀는 정서 지능이 높습니다."),
    "aircraft":    ("/ˈɛərkrɑːft/", "명사", "항공기", "The aircraft landed safely.", "항공기가 안전하게 착륙했습니다."),
    "self":        ("/sɛlf/", "명사", "자아, 자기 자신", "Know yourself.", "자신을 알아야 합니다."),
    "metal":       ("/ˈmɛtəl/", "명사", "금속", "The frame is made of metal.", "프레임은 금속으로 만들어졌습니다."),
    "existence":   ("/ɪɡˈzɪstəns/", "명사", "존재, 실존", "Question your existence.", "존재에 대해 생각해 보세요."),
    "bone":        ("/boʊn/", "명사", "뼈", "She broke a bone.", "그녀는 뼈가 부러졌습니다."),
    "panel":       ("/ˈpænəl/", "명사", "패널, 위원단", "A panel of experts.", "전문가 패널."),
    "prime":       ("/praɪm/", "형용사", "주요한, 최상의", "This is the prime location.", "이곳이 최적의 위치입니다."),
    "appointment": ("/əˈpɔɪntmənt/", "명사", "약속, 임명", "I have a doctor's appointment.", "진찰 예약이 있습니다."),
    "emphasize":   ("/ˈɛmfəsaɪz/", "동사", "강조하다", "Emphasize the key points.", "핵심 사항을 강조하세요."),
    "maximum":     ("/ˈmæksɪməm/", "명사", "최대, 최고", "Work at maximum capacity.", "최대한 능력을 발휘하세요."),
    "effectively": ("/ɪˈfɛktɪvli/", "부사", "효과적으로", "Communicate effectively.", "효과적으로 소통하세요."),
    "elsewhere":   ("/ˌɛlsˈwɛər/", "부사", "다른 곳에", "Look elsewhere.", "다른 곳을 찾아보세요."),
    "bother":      ("/ˈbɒðər/", "동사", "신경 쓰다, 방해하다", "Don't bother me.", "방해하지 마세요."),
    "initiative":  ("/ɪˈnɪʃɪətɪv/", "명사", "계획, 주도권", "Take the initiative.", "주도권을 잡으세요."),
    "sharp":       ("/ʃɑːrp/", "형용사", "날카로운, 영리한", "She has a sharp mind.", "그녀는 예리한 두뇌를 가지고 있습니다."),
    "diet":        ("/ˈdaɪɪt/", "명사", "식이요법, 식단", "Follow a healthy diet.", "건강한 식단을 따르세요."),
    "motion":      ("/ˈmoʊʃən/", "명사", "동작, 움직임", "In slow motion.", "슬로우 모션으로."),
    "gray":        ("/ɡreɪ/", "형용사", "회색의", "The sky turned gray.", "하늘이 회색으로 변했습니다."),
    "plastic":     ("/ˈplæstɪk/", "명사", "플라스틱", "Reduce plastic use.", "플라스틱 사용을 줄이세요."),
    "complicate":  ("/ˈkɒmplɪkeɪt/", "동사", "복잡하게 만들다", "Don't complicate things.", "복잡하게 만들지 마세요."),
    "discipline":  ("/ˈdɪsɪplɪn/", "명사", "훈련, 규율", "Self-discipline is key.", "자기 규율이 핵심입니다."),
    "disappoint":  ("/ˌdɪsəˈpɔɪnt/", "동사", "실망시키다", "Don't disappoint me.", "저를 실망시키지 마세요."),
    "boss":        ("/bɒs/", "명사", "상사, 보스", "My boss is strict.", "제 상사는 엄격합니다."),
    "assumption":  ("/əˈsʌmpʃən/", "명사", "가정, 전제", "Don't make assumptions.", "가정하지 마세요."),
    "freeze":      ("/friːz/", "동사", "얼다, 멈추다", "The pipe froze.", "파이프가 얼었습니다."),
    "extreme":     ("/ɪkˈstriːm/", "형용사", "극단적인, 극도의", "Avoid extreme measures.", "극단적인 조치를 피하세요."),
    "passage":     ("/ˈpæsɪdʒ/", "명사", "통로, 지문", "Read the passage.", "지문을 읽으세요."),
    "reputation":  ("/ˌrɛpjʊˈteɪʃən/", "명사", "명성, 평판", "Protect your reputation.", "명성을 보호하세요."),
    "forth":       ("/fɔːrθ/", "부사", "앞으로, 이후", "And so forth.", "기타 등등."),
    "negotiation": ("/nɪˌɡoʊʃɪˈeɪʃən/", "명사", "협상", "Negotiations were successful.", "협상이 성공적이었습니다."),
    "mechanism":   ("/ˈmɛkənɪzəm/", "명사", "메커니즘, 장치", "Understand the mechanism.", "메커니즘을 이해하세요."),
    "coat":        ("/koʊt/", "명사", "코트, 외투", "Wear a warm coat.", "따뜻한 코트를 입으세요."),
    "democracy":   ("/dɪˈmɒkrəsi/", "명사", "민주주의", "Democracy is valuable.", "민주주의는 소중합니다."),
    "pocket":      ("/ˈpɒkɪt/", "명사", "주머니", "Check your pocket.", "주머니를 확인하세요."),
    "lucky":       ("/ˈlʌki/", "형용사", "운이 좋은", "I feel lucky.", "운이 좋다고 느낍니다."),
    "crash":       ("/kræʃ/", "동사", "충돌하다, 폭락하다", "The system crashed.", "시스템이 충돌했습니다."),
    "observation": ("/ˌɒbzəˈveɪʃən/", "명사", "관찰, 소견", "Make an observation.", "관찰 의견을 말하세요."),
    "meat":        ("/miːt/", "명사", "고기", "I prefer vegetarian to meat.", "저는 고기보다 채식을 선호합니다."),
    "concentration":("/ˌkɒnsənˈtreɪʃən/", "명사", "집중, 농도", "Good concentration is needed.", "좋은 집중력이 필요합니다."),
    "implication": ("/ˌɪmplɪˈkeɪʃən/", "명사", "함의, 영향", "Consider the implications.", "함의를 고려하세요."),
    "deserve":     ("/dɪˈzɜːrv/", "동사", "받을 자격이 있다", "You deserve the best.", "최고를 받을 자격이 있습니다."),
    "unusual":     ("/ʌnˈjuːʒuəl/", "형용사", "특이한, 이례적인", "That's unusual.", "특이합니다."),
    "defend":      ("/dɪˈfɛnd/", "동사", "방어하다, 변호하다", "Defend your position.", "자신의 입장을 방어하세요."),
    "classic":     ("/ˈklæsɪk/", "형용사", "고전적인, 전통적인", "It's a classic example.", "고전적인 예입니다."),
    "king":        ("/kɪŋ/", "명사", "왕", "The king ruled wisely.", "왕은 현명하게 통치했습니다."),
    "interaction": ("/ˌɪntərˈækʃən/", "명사", "상호 작용", "Positive interaction is key.", "긍정적인 상호 작용이 핵심입니다."),
    "repair":      ("/rɪˈpɛər/", "동사", "수리하다, 고치다", "Repair the damage.", "손상을 수리하세요."),
    "collapse":    ("/kəˈlæps/", "동사", "붕괴하다, 쓰러지다", "The structure collapsed.", "구조물이 붕괴했습니다."),
    "borrow":      ("/ˈbɒroʊ/", "동사", "빌리다", "Can I borrow your pen?", "펜을 빌려도 될까요?"),
    "fundamental": ("/ˌfʌndəˈmɛntəl/", "형용사", "근본적인, 기초적인", "This is fundamental.", "이것은 근본적인 것입니다."),
    "dish":        ("/dɪʃ/", "명사", "접시, 요리", "Try this dish.", "이 요리를 드셔 보세요."),
    "abroad":      ("/əˈbrɔːd/", "부사", "해외에, 외국에", "She studied abroad.", "그녀는 해외에서 공부했습니다."),
    "soul":        ("/soʊl/", "명사", "영혼, 정신", "She has a kind soul.", "그녀는 착한 마음을 가지고 있습니다."),
    "capable":     ("/ˈkeɪpəbəl/", "형용사", "유능한, ~할 수 있는", "She is capable of anything.", "그녀는 무엇이든 할 수 있습니다."),
    "defeat":      ("/dɪˈfiːt/", "동사", "물리치다, 패배시키다", "Never accept defeat.", "결코 패배를 받아들이지 마세요."),
    "enhance":     ("/ɪnˈhɑːns/", "동사", "향상시키다, 강화하다", "Enhance your skills.", "기술을 향상시키세요."),
    "proud":       ("/praʊd/", "형용사", "자랑스러운", "I'm proud of you.", "당신이 자랑스럽습니다."),
    "emergency":   ("/ɪˈmɜːrdʒənsi/", "명사", "응급, 비상사태", "Call emergency services.", "응급 서비스에 연락하세요."),
    "distinguish": ("/dɪˈstɪŋɡwɪʃ/", "동사", "구별하다", "Distinguish between the two.", "두 가지를 구별하세요."),
    "substantial": ("/səbˈstænʃəl/", "형용사", "상당한, 실질적인", "A substantial improvement.", "상당한 개선."),
    "nearby":      ("/ˌnɪərˈbaɪ/", "형용사", "근처의, 인근의", "Is there a hotel nearby?", "근처에 호텔이 있나요?"),
    "manufacturer":("/ˌmænjʊˈfæktʃərər/", "명사", "제조업체, 제조사", "Contact the manufacturer.", "제조사에 연락하세요."),
    "slide":       ("/slaɪd/", "동사", "미끄러지다", "Slide the card.", "카드를 밀어 넣으세요."),
    "valuable":    ("/ˈvæljuəbəl/", "형용사", "귀중한", "This is valuable information.", "이것은 귀중한 정보입니다."),
    "personally":  ("/ˈpɜːrsənəli/", "부사", "개인적으로", "I personally disagree.", "개인적으로 동의하지 않습니다."),
    "cope":        ("/koʊp/", "동사", "대처하다, 견디다", "Learn to cope with stress.", "스트레스에 대처하는 법을 배우세요."),
    "approximately":("/əˈprɒksɪmɪtli/", "부사", "약, 대략", "Approximately 100 people attended.", "약 100명이 참석했습니다."),
    "accommodation":("/əˌkɒməˈdeɪʃən/", "명사", "숙소, 숙박시설", "Find accommodation.", "숙소를 찾으세요."),
    "highlight":   ("/ˈhaɪlaɪt/", "동사", "강조하다, 하이라이트하다", "Highlight the key points.", "핵심 사항을 강조하세요."),
    "reporter":    ("/rɪˈpɔːrtər/", "명사", "기자, 리포터", "She is a news reporter.", "그녀는 뉴스 기자입니다."),
    "climate":     ("/ˈklaɪmɪt/", "명사", "기후", "Climate change is urgent.", "기후 변화가 시급합니다."),
    "shirt":       ("/ʃɜːrt/", "명사", "셔츠", "He wore a white shirt.", "그는 흰 셔츠를 입었습니다."),
    "exception":   ("/ɪkˈsɛpʃən/", "명사", "예외", "There is an exception.", "예외가 있습니다."),
    "corporation": ("/ˌkɔːrpəˈreɪʃən/", "명사", "기업, 회사", "She works for a corporation.", "그녀는 기업에서 일합니다."),
    "chip":        ("/tʃɪp/", "명사", "칩, 조각", "A computer chip.", "컴퓨터 칩."),
    "winner":      ("/ˈwɪnər/", "명사", "승자, 우승자", "The winner is...", "승자는..."),
    "encounter":   ("/ɪnˈkaʊntər/", "동사", "만나다, 직면하다", "Encounter new challenges.", "새로운 도전에 직면하세요."),
    "brown":       ("/braʊn/", "형용사", "갈색의", "She has brown eyes.", "그녀는 갈색 눈을 가지고 있습니다."),
    "breathe":     ("/briːð/", "동사", "숨쉬다, 호흡하다", "Breathe deeply.", "깊게 숨을 쉬세요."),
    "excuse":      ("/ɪkˈskjuːs/", "명사", "핑계, 변명", "Stop making excuses.", "변명을 그만하세요."),
    "partly":      ("/ˈpɑːrtli/", "부사", "부분적으로, 어느 정도", "It was partly my fault.", "어느 정도는 제 잘못입니다."),
    "urban":       ("/ˈɜːrbən/", "형용사", "도시의", "Urban life is fast.", "도시 생활은 빠릅니다."),
    "massive":     ("/ˈmæsɪv/", "형용사", "거대한, 대규모의", "A massive change occurred.", "거대한 변화가 일어났습니다."),
    "install":     ("/ɪnˈstɔːl/", "동사", "설치하다", "Install the software.", "소프트웨어를 설치하세요."),
    "calculate":   ("/ˈkælkjʊleɪt/", "동사", "계산하다", "Calculate the total.", "합계를 계산하세요."),
    "upper":       ("/ˈʌpər/", "형용사", "위쪽의, 상위의", "Use the upper floor.", "위층을 이용하세요."),
    "creation":    ("/kriˈeɪʃən/", "명사", "창작, 창조물", "This is her latest creation.", "이것이 그녀의 최신 작품입니다."),
    "occupy":      ("/ˈɒkjʊpaɪ/", "동사", "차지하다, 점령하다", "Occupy your time wisely.", "시간을 현명하게 활용하세요."),
    "outline":     ("/ˈaʊtlaɪn/", "명사", "개요, 윤곽", "Create an outline.", "개요를 작성하세요."),
    "sufficient":  ("/səˈfɪʃənt/", "형용사", "충분한", "Is this sufficient?", "이것이 충분한가요?"),
    "update":      ("/ˈʌpdeɪt/", "동사", "업데이트하다", "Update the software.", "소프트웨어를 업데이트하세요."),
    "luck":        ("/lʌk/", "명사", "행운", "Good luck!", "행운을 빕니다!"),
    "preserve":    ("/prɪˈzɜːrv/", "동사", "보존하다, 유지하다", "Preserve the environment.", "환경을 보존하세요."),
    "split":       ("/splɪt/", "동사", "나누다, 분리하다", "Split the bill.", "계산서를 나눠서 내세요."),
    "swing":       ("/swɪŋ/", "동사", "흔들다, 스윙하다", "Swing your arms.", "팔을 흔들어 보세요."),
    "illness":     ("/ˈɪlnɪs/", "명사", "병, 질환", "She recovered from her illness.", "그녀는 병에서 회복했습니다."),
    "journalist":  ("/ˈdʒɜːrnəlɪst/", "명사", "기자", "He is a journalist.", "그는 기자입니다."),
    "sudden":      ("/ˈsʌdən/", "형용사", "갑작스러운", "A sudden change occurred.", "갑작스러운 변화가 일어났습니다."),
    "advertisement":("/ˌædvəˈtaɪzmənt/", "명사", "광고", "The advertisement was creative.", "광고가 창의적이었습니다."),
    "consistent":  ("/kənˈsɪstənt/", "형용사", "일관된", "Be consistent.", "일관성을 유지하세요."),
    "originally":  ("/əˈrɪdʒɪnəli/", "부사", "원래, 처음에", "It was originally designed for...", "원래 ~를 위해 설계되었습니다."),
    "aside":       ("/əˈsaɪd/", "부사", "옆으로, 한쪽에", "Set it aside.", "한쪽에 두세요."),
    "comfort":     ("/ˈkʌmfərt/", "명사", "편안함, 위로", "Find comfort in music.", "음악에서 위안을 찾으세요."),
    "severe":      ("/sɪˈvɪər/", "형용사", "심각한, 엄격한", "The problem is severe.", "문제가 심각합니다."),
    "gene":        ("/dʒiːn/", "명사", "유전자", "Genes determine traits.", "유전자가 특성을 결정합니다."),
    "prospect":    ("/ˈprɒspɛkt/", "명사", "전망, 가능성", "The prospects are good.", "전망이 좋습니다."),
    "snow":        ("/snoʊ/", "명사", "눈", "It will snow tomorrow.", "내일 눈이 올 것입니다."),
    "plot":        ("/plɒt/", "명사", "줄거리, 음모", "The plot is interesting.", "줄거리가 흥미롭습니다."),
    "neck":        ("/nɛk/", "명사", "목", "She has a sore neck.", "그녀는 목이 아픕니다."),
    "criteria":    ("/kraɪˈtɪəriə/", "명사", "기준들", "What are the criteria?", "기준이 무엇인가요?"),
    "primarily":   ("/ˈpraɪmɛrɪli/", "부사", "주로, 우선적으로", "It is primarily for safety.", "주로 안전을 위한 것입니다."),
    "integrate":   ("/ˈɪntɪɡreɪt/", "동사", "통합하다", "Integrate the systems.", "시스템을 통합하세요."),
    "criticism":   ("/ˈkrɪtɪsɪzəm/", "명사", "비판, 비평", "Accept criticism gracefully.", "비판을 감사히 받아들이세요."),
    "convention":  ("/kənˈvɛnʃən/", "명사", "관행, 대회", "Break with convention.", "관행을 깨세요."),
    "bet":         ("/bɛt/", "동사", "내기하다", "I bet you're right.", "당신이 맞는 것 같습니다."),
    "retain":      ("/rɪˈteɪn/", "동사", "유지하다, 보유하다", "Retain the information.", "정보를 유지하세요."),
    "sequence":    ("/ˈsiːkwəns/", "명사", "순서, 연속", "Follow the sequence.", "순서를 따르세요."),
    "plain":       ("/pleɪn/", "형용사", "단순한, 명확한", "Speak in plain language.", "평이한 언어로 말씀하세요."),
    "volunteer":   ("/ˌvɒlənˈtɪər/", "동사", "자원봉사하다", "Volunteer your time.", "시간을 자원봉사에 쓰세요."),
    "rural":       ("/ˈrʊərəl/", "형용사", "농촌의, 시골의", "She lives in a rural area.", "그녀는 시골 지역에 삽니다."),
    "calm":        ("/kɑːm/", "형용사", "침착한, 고요한", "Stay calm.", "침착하게 있으세요."),
    "abandon":     ("/əˈbændən/", "동사", "포기하다, 버리다", "Never abandon hope.", "희망을 절대 포기하지 마세요."),
    "examination": ("/ɪɡˌzæmɪˈneɪʃən/", "명사", "시험, 검사", "Pass the examination.", "시험에 합격하세요."),
    "silence":     ("/ˈsaɪləns/", "명사", "침묵", "Silence is golden.", "침묵은 금입니다."),
    "tennis":      ("/ˈtɛnɪs/", "명사", "테니스", "She plays tennis.", "그녀는 테니스를 칩니다."),
    "confuse":     ("/kənˈfjuːz/", "동사", "혼동하다, 혼란스럽게 하다", "Don't confuse the two.", "두 가지를 혼동하지 마세요."),
    "southern":    ("/ˈsʌðərn/", "형용사", "남쪽의, 남방의", "She is from the southern region.", "그녀는 남쪽 지역 출신입니다."),
    "output":      ("/ˈaʊtpʊt/", "명사", "생산량, 출력", "Increase the output.", "생산량을 늘리세요."),
    "beauty":      ("/ˈbjuːti/", "명사", "아름다움, 미", "Beauty is in the eye of the beholder.", "아름다움은 보는 사람의 눈에 있습니다."),
    "mouse":       ("/maʊs/", "명사", "마우스, 쥐", "Click the mouse.", "마우스를 클릭하세요."),
    "mathematics": ("/ˌmæθəˈmætɪks/", "명사", "수학", "She loves mathematics.", "그녀는 수학을 좋아합니다."),
    "creation":    ("/kriˈeɪʃən/", "명사", "창조", "A new creation.", "새로운 창조물."),
    "secondly":    ("/ˈsɛkəndli/", "부사", "두 번째로", "Secondly, we need to...", "두 번째로, 우리는 ~해야 합니다."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT8:
                    pron, pos, meaning, ex_en, ex_ko = DICT8[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more7.py ===\n")
    patch_files()
