#!/usr/bin/env python3
"""Fill TOEIC-L3 (240 words)"""
import json, glob

DICT12 = {
    "lawn":          ("/lɔːn/", "명사", "잔디밭", "Mow the lawn.", "잔디를 깎으세요."),
    "microscope":    ("/ˈmaɪkrəskoʊp/", "명사", "현미경", "Look through the microscope.", "현미경으로 보세요."),
    "mislead":       ("/mɪsˈliːd/", "동사", "오도하다, 잘못 이끌다", "Don't mislead customers.", "고객을 오도하지 마세요."),
    "misplace":      ("/mɪsˈpleɪs/", "동사", "잘못 두다, 분실하다", "Misplace important documents.", "중요한 서류를 잘못 두다."),
    "newsstand":     ("/ˈnjuːzstænd/", "명사", "신문 판매대", "Buy a magazine at the newsstand.", "신문 판매대에서 잡지를 사세요."),
    "rack":          ("/ræk/", "명사", "선반, 걸이", "Put clothes on the rack.", "옷을 옷걸이에 걸어두세요."),
    "remodel":       ("/riːˈmɒdəl/", "동사", "개조하다, 리모델링하다", "Remodel the kitchen.", "주방을 개조하세요."),
    "statistics":    ("/stəˈtɪstɪks/", "명사", "통계학, 통계", "Interpret the statistics.", "통계를 해석하세요."),
    "tunnel":        ("/ˈtʌnəl/", "명사", "터널", "Drive through the tunnel.", "터널을 통과해 운전하세요."),
    "unlimited":     ("/ʌnˈlɪmɪtɪd/", "형용사", "무제한의", "Unlimited data plan.", "무제한 데이터 요금제."),
    "vitamin":       ("/ˈvaɪtəmɪn/", "명사", "비타민", "Take daily vitamins.", "매일 비타민을 복용하세요."),
    "zoo":           ("/zuː/", "명사", "동물원", "Visit the zoo.", "동물원을 방문하세요."),
    "alert":         ("/əˈlɜːrt/", "동사", "경고하다, 알리다", "Alert the staff.", "직원들에게 알리세요."),
    "auditorium":    ("/ˌɔːdɪˈtɔːriəm/", "명사", "강당", "Meet in the auditorium.", "강당에서 만나세요."),
    "celebrity":     ("/sɪˈlɛbrɪti/", "명사", "유명인, 연예인", "A famous celebrity.", "유명한 연예인."),
    "deduct":        ("/dɪˈdʌkt/", "동사", "공제하다, 빼다", "Deduct taxes.", "세금을 공제하세요."),
    "disruption":    ("/dɪsˈrʌpʃən/", "명사", "방해, 혼란", "Minimize disruption.", "방해를 최소화하세요."),
    "electrician":   ("/ɪˌlɛkˈtrɪʃən/", "명사", "전기공", "Call an electrician.", "전기공을 부르세요."),
    "enthusiastic":  ("/ɪnˌθjuːziˈæstɪk/", "형용사", "열정적인", "An enthusiastic team.", "열정적인 팀."),
    "graduation":    ("/ˌɡrædʒuˈeɪʃən/", "명사", "졸업", "Attend graduation ceremony.", "졸업식에 참석하세요."),
    "icy":           ("/ˈaɪsi/", "형용사", "빙판의, 차가운", "Icy roads.", "빙판길."),
    "irregular":     ("/ɪˈrɛɡjʊlər/", "형용사", "불규칙한", "Irregular schedule.", "불규칙한 일정."),
    "login":         ("/ˈlɒɡɪn/", "명사", "로그인", "Enter your login details.", "로그인 정보를 입력하세요."),
    "managerial":    ("/ˌmænɪˈdʒɪəriəl/", "형용사", "관리의", "Managerial position.", "관리직."),
    "mineral":       ("/ˈmɪnərəl/", "명사", "미네랄, 광물", "Mineral water.", "미네랄 워터."),
    "motorcycle":    ("/ˈmoʊtərˌsaɪkəl/", "명사", "오토바이", "Ride a motorcycle.", "오토바이를 타세요."),
    "necessity":     ("/nɪˈsɛsɪti/", "명사", "필수품, 필요성", "A basic necessity.", "기본 필수품."),
    "planner":       ("/ˈplænər/", "명사", "플래너, 계획자", "Use a daily planner.", "일일 플래너를 사용하세요."),
    "programmer":    ("/ˈproʊɡræmər/", "명사", "프로그래머", "She is a skilled programmer.", "그녀는 숙련된 프로그래머이다."),
    "proofread":     ("/ˈpruːfriːd/", "동사", "교정하다", "Proofread the document.", "문서를 교정하세요."),
    "recruiter":     ("/rɪˈkruːtər/", "명사", "채용 담당자", "Contact the recruiter.", "채용 담당자에게 연락하세요."),
    "remainder":     ("/rɪˈmeɪndər/", "명사", "나머지", "Divide the remainder.", "나머지를 나누세요."),
    "statue":        ("/ˈstætʃuː/", "명사", "조각상", "The Statue of Liberty.", "자유의 여신상."),
    "steadily":      ("/ˈstɛdɪli/", "부사", "꾸준히", "Progress steadily.", "꾸준히 발전하세요."),
    "stockholder":   ("/ˈstɒkhoʊldər/", "명사", "주주", "Stockholder meeting.", "주주 회의."),
    "vacant":        ("/ˈveɪkənt/", "형용사", "빈, 비어있는", "A vacant position.", "공석인 자리."),
    "accessory":     ("/əkˈsɛsəri/", "명사", "액세서리, 부속품", "Fashion accessories.", "패션 액세서리."),
    "assembly":      ("/əˈsɛmbli/", "명사", "조립, 집회", "Assembly line.", "조립 라인."),
    "basket":        ("/ˈbɑːskɪt/", "명사", "바구니", "Put it in the basket.", "바구니에 넣으세요."),
    "certification": ("/ˌsɜːrtɪfɪˈkeɪʃən/", "명사", "자격증, 인증", "Get a certification.", "자격증을 취득하세요."),
    "closure":       ("/ˈkloʊʒər/", "명사", "폐쇄, 종결", "Road closure.", "도로 폐쇄."),
    "dislike":       ("/dɪsˈlaɪk/", "동사", "싫어하다", "I dislike delays.", "지연을 싫어한다."),
    "downstairs":    ("/ˌdaʊnˈstɛərz/", "부사", "아래층으로", "Come downstairs.", "아래층으로 내려오세요."),
    "expiration":    ("/ˌɛkspɪˈreɪʃən/", "명사", "만료, 만기", "Check the expiration date.", "만료일을 확인하세요."),
    "headache":      ("/ˈhɛdeɪk/", "명사", "두통", "I have a headache.", "두통이 있다."),
    "jam":           ("/dʒæm/", "명사", "잼, 교통 체증", "Traffic jam.", "교통 체증."),
    "nail":          ("/neɪl/", "명사", "못, 손톱", "Hammer the nail.", "못을 박으세요."),
    "optimistic":    ("/ˌɒptɪˈmɪstɪk/", "형용사", "낙관적인", "Be optimistic.", "낙관적으로 생각하세요."),
    "pedestrian":    ("/pɪˈdɛstriən/", "명사", "보행자", "Pedestrian crossing.", "횡단보도."),
    "projection":    ("/prəˈdʒɛkʃən/", "명사", "예상, 투영", "Sales projections.", "판매 예상치."),
    "sleeve":        ("/sliːv/", "명사", "소매", "Roll up your sleeves.", "소매를 걷으세요."),
    "suburb":        ("/ˈsʌbɜːrb/", "명사", "교외, 외곽 지역", "Live in the suburbs.", "교외에 살다."),
    "takeover":      ("/ˈteɪkoʊvər/", "명사", "인수합병", "Hostile takeover.", "적대적 인수합병."),
    "unsure":        ("/ʌnˈʃʊər/", "형용사", "확실하지 않은", "I am unsure.", "확실하지 않다."),
    "upstairs":      ("/ˌʌpˈstɛərz/", "부사", "위층으로", "Go upstairs.", "위층으로 올라가세요."),
    "verbal":        ("/ˈvɜːrbəl/", "형용사", "말로 하는, 구두의", "Verbal agreement.", "구두 합의."),
    "visa":          ("/ˈviːzə/", "명사", "비자", "Apply for a visa.", "비자를 신청하세요."),
    "wildlife":      ("/ˈwaɪldlaɪf/", "명사", "야생 생물", "Protect wildlife.", "야생 생물을 보호하세요."),
    "workforce":     ("/ˈwɜːrkfɔːrs/", "명사", "노동력, 직원", "Train the workforce.", "직원들을 교육하세요."),
    "absent":        ("/ˈæbsənt/", "형용사", "결석한, 부재인", "She is absent today.", "그녀는 오늘 결석했다."),
    "accumulate":    ("/əˈkjuːmjʊleɪt/", "동사", "축적하다, 모으다", "Accumulate savings.", "저축을 축적하세요."),
    "appraisal":     ("/əˈpreɪzəl/", "명사", "평가, 감정", "Annual performance appraisal.", "연간 성과 평가."),
    "apprentice":    ("/əˈprɛntɪs/", "명사", "견습생", "Hire an apprentice.", "견습생을 채용하세요."),
    "businessman":   ("/ˈbɪznɪsmæn/", "명사", "사업가, 기업인", "A successful businessman.", "성공한 사업가."),
    "ceiling":       ("/ˈsiːlɪŋ/", "명사", "천장", "High ceiling.", "높은 천장."),
    "colorful":      ("/ˈkʌlərfʊl/", "형용사", "화려한, 다채로운", "Colorful design.", "화려한 디자인."),
    "compensate":    ("/ˈkɒmpɛnseɪt/", "동사", "보상하다", "Compensate for the loss.", "손실을 보상하세요."),
    "costume":       ("/ˈkɒstjuːm/", "명사", "의상, 복장", "Halloween costume.", "할로윈 의상."),
    "editorial":     ("/ˌɛdɪˈtɔːriəl/", "명사", "사설, 편집의", "Editorial team.", "편집팀."),
    "effectiveness": ("/ɪˈfɛktɪvnɪs/", "명사", "효과성", "Measure effectiveness.", "효과성을 측정하세요."),
    "facilitate":    ("/fəˈsɪlɪteɪt/", "동사", "용이하게 하다, 촉진하다", "Facilitate communication.", "소통을 촉진하세요."),
    "firefighter":   ("/ˈfaɪərfaɪtər/", "명사", "소방관", "Brave firefighters.", "용감한 소방관들."),
    "gasoline":      ("/ˈɡæsəliːn/", "명사", "가솔린, 휘발유", "Fill up with gasoline.", "휘발유를 채우세요."),
    "inappropriate": ("/ˌɪnəˈproʊpriɪt/", "형용사", "부적절한", "Inappropriate behavior.", "부적절한 행동."),
    "landlord":      ("/ˈlændlɔːrd/", "명사", "집주인", "Pay rent to the landlord.", "집주인에게 임대료를 내세요."),
    "layout":        ("/ˈleɪaʊt/", "명사", "레이아웃, 배치", "Page layout.", "페이지 레이아웃."),
    "lunchtime":     ("/ˈlʌntʃtaɪm/", "명사", "점심시간", "Meet at lunchtime.", "점심 시간에 만나세요."),
    "payroll":       ("/ˈpeɪroʊl/", "명사", "급여 대장", "Process the payroll.", "급여를 처리하세요."),
    "pharmaceutical":("/ˌfɑːrməˈsuːtɪkəl/", "형용사", "제약의", "Pharmaceutical company.", "제약 회사."),
    "plausible":     ("/ˈplɔːzɪbəl/", "형용사", "그럴듯한, 타당한", "Plausible explanation.", "그럴듯한 설명."),
    "safely":        ("/ˈseɪfli/", "부사", "안전하게", "Drive safely.", "안전하게 운전하세요."),
    "simplify":      ("/ˈsɪmplɪfaɪ/", "동사", "단순화하다", "Simplify the process.", "과정을 단순화하세요."),
    "specialty":     ("/ˈspɛʃəlti/", "명사", "전문, 특기", "Medical specialty.", "의료 전문 분야."),
    "tech":          ("/tɛk/", "명사", "기술, 테크", "High-tech industry.", "첨단 기술 산업."),
    "unexpected":    ("/ˌʌnɪkˈspɛktɪd/", "형용사", "예상치 못한", "Unexpected costs.", "예상치 못한 비용."),
    "unspecified":   ("/ʌnˈspɛsɪfaɪd/", "형용사", "명시되지 않은", "Unspecified amount.", "명시되지 않은 금액."),
    "adhere":        ("/ədˈhɪər/", "동사", "고수하다, 준수하다", "Adhere to the rules.", "규칙을 준수하세요."),
    "bankrupt":      ("/ˈbæŋkrʌpt/", "형용사", "파산한", "The company went bankrupt.", "회사가 파산했다."),
    "caution":       ("/ˈkɔːʃən/", "명사", "주의, 경고", "Proceed with caution.", "주의를 기울여 진행하세요."),
    "clip":          ("/klɪp/", "명사", "클립, 집게", "Use a paper clip.", "종이 클립을 사용하세요."),
    "diner":         ("/ˈdaɪnər/", "명사", "식당", "Eat at a diner.", "식당에서 드세요."),
    "duplicate":     ("/ˈdjuːplɪkɪt/", "동사", "복사하다, 복제하다", "Duplicate the file.", "파일을 복사하세요."),
    "economist":     ("/ɪˈkɒnəmɪst/", "명사", "경제학자", "The economist predicted growth.", "경제학자가 성장을 예측했다."),
    "embassy":       ("/ˈɛmbəsi/", "명사", "대사관", "Visit the embassy.", "대사관을 방문하세요."),
    "fasten":        ("/ˈfæsən/", "동사", "채우다, 고정하다", "Fasten the seatbelt.", "안전벨트를 채우세요."),
    "harmful":       ("/ˈhɑːrmfʊl/", "형용사", "해로운", "Harmful chemicals.", "해로운 화학물질."),
    "informative":   ("/ɪnˈfɔːrmətɪv/", "형용사", "유익한", "Very informative session.", "매우 유익한 세션."),
    "institute":     ("/ˈɪnstɪtjuːt/", "명사", "기관, 연구소", "Research institute.", "연구기관."),
    "kit":           ("/kɪt/", "명사", "키트, 도구 세트", "First aid kit.", "응급 처치 키트."),
    "locally":       ("/ˈloʊkəli/", "부사", "지역적으로", "Buy locally produced goods.", "지역 생산 제품을 구매하세요."),
    "mentor":        ("/ˈmɛntɔːr/", "명사", "멘토", "Find a good mentor.", "좋은 멘토를 찾으세요."),
    "nominate":      ("/ˈnɒmɪneɪt/", "동사", "추천하다, 지명하다", "Nominate a candidate.", "후보를 지명하세요."),
    "opt":           ("/ɒpt/", "동사", "선택하다", "Opt for the better plan.", "더 좋은 계획을 선택하세요."),
    "parade":        ("/pəˈreɪd/", "명사", "퍼레이드", "Watch the parade.", "퍼레이드를 보세요."),
    "physician":     ("/fɪˈzɪʃən/", "명사", "의사", "Consult your physician.", "주치의에게 상담하세요."),
    "polish":        ("/ˈpɒlɪʃ/", "동사", "닦다, 광택 내다", "Polish your shoes.", "신발을 닦으세요."),
    "postage":       ("/ˈpoʊstɪdʒ/", "명사", "우편 요금", "Prepaid postage.", "선불 우편 요금."),
    "recreational":  ("/ˌrɛkriˈeɪʃənəl/", "형용사", "레크리에이션의", "Recreational activities.", "레크리에이션 활동."),
    "rehearse":      ("/rɪˈhɜːrs/", "동사", "연습하다, 리허설하다", "Rehearse the presentation.", "발표 리허설을 하세요."),
    "removal":       ("/rɪˈmuːvəl/", "명사", "제거, 이동", "Waste removal.", "폐기물 제거."),
    "satisfactory":  ("/ˌsætɪsˈfæktəri/", "형용사", "만족스러운", "Satisfactory result.", "만족스러운 결과."),
    "separately":    ("/ˈsɛpərɪtli/", "부사", "별도로", "Bill separately.", "별도로 청구하세요."),
    "unnecessary":   ("/ʌnˈnɛsɪsəri/", "형용사", "불필요한", "Avoid unnecessary costs.", "불필요한 비용을 피하세요."),
    "accordingly":   ("/əˈkɔːrdɪŋli/", "부사", "따라서, 그에 맞게", "Act accordingly.", "그에 맞게 행동하세요."),
    "apple":         ("/ˈæpəl/", "명사", "사과", "An apple a day.", "하루에 사과 하나."),
    "applicable":    ("/ˈæplɪkəbəl/", "형용사", "해당하는, 적용 가능한", "Applicable rules.", "적용 가능한 규칙."),
    "auction":       ("/ˈɔːkʃən/", "명사", "경매", "Online auction.", "온라인 경매."),
    "balcony":       ("/ˈbælkəni/", "명사", "발코니", "Sit on the balcony.", "발코니에 앉으세요."),
    "basement":      ("/ˈbeɪsmənt/", "명사", "지하층", "Store it in the basement.", "지하층에 보관하세요."),
    "beforehand":    ("/bɪˈfɔːrhænd/", "부사", "미리, 사전에", "Prepare beforehand.", "미리 준비하세요."),
    "culinary":      ("/ˈkʌlɪnəri/", "형용사", "요리의", "Culinary arts.", "요리 예술."),
    "documentary":   ("/ˌdɒkjʊˈmɛntəri/", "명사", "다큐멘터리", "Watch a documentary.", "다큐멘터리를 보세요."),
    "downturn":      ("/ˈdaʊntɜːrn/", "명사", "하락, 침체", "Economic downturn.", "경기 침체."),
    "earthquake":    ("/ˈɜːrθkweɪk/", "명사", "지진", "Earthquake preparedness.", "지진 대비."),
    "elegant":       ("/ˈɛlɪɡənt/", "형용사", "우아한", "Elegant design.", "우아한 디자인."),
    "excessive":     ("/ɪkˈsɛsɪv/", "형용사", "과도한", "Excessive spending.", "과도한 지출."),
    "generic":       ("/dʒɪˈnɛrɪk/", "형용사", "일반적인, 비상표의", "Generic medicine.", "비상표 의약품."),
    "jazz":          ("/dʒæz/", "명사", "재즈", "Jazz music.", "재즈 음악."),
    "lifetime":      ("/ˈlaɪftaɪm/", "명사", "일생, 평생", "A lifetime warranty.", "평생 보증."),
    "massage":       ("/ˈmæsɑːʒ/", "명사", "마사지", "Get a massage.", "마사지를 받으세요."),
    "maximize":      ("/ˈmæksɪmaɪz/", "동사", "최대화하다", "Maximize profits.", "이익을 최대화하세요."),
    "mild":          ("/maɪld/", "형용사", "순한, 온화한", "Mild flavor.", "순한 맛."),
    "ongoing":       ("/ˈɒnɡoʊɪŋ/", "형용사", "진행 중인", "Ongoing project.", "진행 중인 프로젝트."),
    "periodically":  ("/ˌpɪəriˈɒdɪkli/", "부사", "주기적으로", "Check periodically.", "주기적으로 확인하세요."),
    "pie":           ("/paɪ/", "명사", "파이", "Bake a pie.", "파이를 구우세요."),
    "plug":          ("/plʌɡ/", "명사", "플러그", "Pull the plug.", "플러그를 뽑으세요."),
    "recruitment":   ("/rɪˈkruːtmənt/", "명사", "채용", "Recruitment process.", "채용 과정."),
    "referee":       ("/ˌrɛfəˈriː/", "명사", "심판, 추천인", "The referee blew the whistle.", "심판이 호루라기를 불었다."),
    "referral":      ("/rɪˈfɜːrəl/", "명사", "추천, 의뢰", "Employee referral.", "직원 추천."),
    "renown":        ("/rɪˈnaʊn/", "명사", "명성", "World renown.", "세계적인 명성."),
    "runner":        ("/ˈrʌnər/", "명사", "달리는 사람, 심부름꾼", "Marathon runner.", "마라톤 선수."),
    "sock":          ("/sɒk/", "명사", "양말", "Wear matching socks.", "짝이 맞는 양말을 신으세요."),
    "spam":          ("/spæm/", "명사", "스팸", "Block spam emails.", "스팸 이메일을 차단하세요."),
    "surf":          ("/sɜːrf/", "동사", "서핑하다, 인터넷을 검색하다", "Surf the internet.", "인터넷을 검색하세요."),
    "timetable":     ("/ˈtaɪmteɪbəl/", "명사", "시간표", "Check the train timetable.", "기차 시간표를 확인하세요."),
    "vase":          ("/vɑːz/", "명사", "꽃병", "Put flowers in the vase.", "꽃병에 꽃을 꽂으세요."),
    "aboard":        ("/əˈbɔːrd/", "부사", "배에 타고", "All aboard!", "모두 탑승하세요!"),
    "advancement":   ("/ədˈvɑːnsmənt/", "명사", "발전, 진급", "Career advancement.", "경력 발전."),
    "advertiser":    ("/ˈædvərtaɪzər/", "명사", "광고주", "Partner with advertisers.", "광고주와 협력하세요."),
    "alternatively": ("/ɔːlˈtɜːrnətɪvli/", "부사", "대안으로", "Alternatively, use another method.", "대안으로 다른 방법을 사용하세요."),
    "amuse":         ("/əˈmjuːz/", "동사", "즐겁게 하다, 재미있게 하다", "The show amused us.", "공연이 우리를 즐겁게 했다."),
    "attorney":      ("/əˈtɜːrni/", "명사", "변호사", "Consult an attorney.", "변호사에게 상담하세요."),
    "authorization": ("/ˌɔːθərɪˈzeɪʃən/", "명사", "허가, 승인", "Get authorization.", "허가를 받으세요."),
    "campus":        ("/ˈkæmpəs/", "명사", "캠퍼스", "Meet on campus.", "캠퍼스에서 만나세요."),
    "candy":         ("/ˈkændi/", "명사", "사탕", "Share candy with friends.", "친구들과 사탕을 나누세요."),
    "certify":       ("/ˈsɜːrtɪfaɪ/", "동사", "증명하다, 인증하다", "Certify the document.", "문서를 인증하세요."),
    "checkout":      ("/ˈtʃɛkaʊt/", "명사", "체크아웃, 계산대", "Fast checkout.", "빠른 체크아웃."),
    "chemistry":     ("/ˈkɛmɪstri/", "명사", "화학", "Chemistry lab.", "화학 실험실."),
    "circulation":   ("/ˌsɜːrkjʊˈleɪʃən/", "명사", "순환, 유통", "Improve blood circulation.", "혈액 순환을 개선하세요."),
    "concierge":     ("/ˌkɒnsiˈɛərʒ/", "명사", "컨시어지", "Ask the concierge.", "컨시어지에게 물어보세요."),
    "consent":       ("/kənˈsɛnt/", "명사", "동의, 허락", "Get written consent.", "서면 동의를 받으세요."),
    "consistently":  ("/kənˈsɪstəntli/", "부사", "일관되게", "Perform consistently.", "일관되게 수행하세요."),
    "cookie":        ("/ˈkʊki/", "명사", "쿠키", "Bake cookies.", "쿠키를 구우세요."),
    "deck":          ("/dɛk/", "명사", "갑판, 데크", "Meet on the deck.", "데크에서 만나세요."),
    "descriptive":   ("/dɪˈskrɪptɪv/", "형용사", "묘사적인", "Descriptive writing.", "묘사적인 글쓰기."),
    "detach":        ("/dɪˈtætʃ/", "동사", "분리하다", "Detach the cable.", "케이블을 분리하세요."),
    "documentation": ("/ˌdɒkjʊmɛnˈteɪʃən/", "명사", "문서화", "Proper documentation.", "적절한 문서화."),
    "entrepreneur":  ("/ˌɒntrəprəˈnɜːr/", "명사", "기업가", "A successful entrepreneur.", "성공한 기업가."),
    "exceptional":   ("/ɪkˈsɛpʃənəl/", "형용사", "탁월한, 예외적인", "Exceptional performance.", "탁월한 성과."),
    "familiarize":   ("/fəˈmɪliəraɪz/", "동사", "익숙하게 하다", "Familiarize yourself.", "익숙해지세요."),
    "hotline":       ("/ˈhɒtlaɪn/", "명사", "핫라인", "Call the hotline.", "핫라인에 전화하세요."),
    "intonation":    ("/ˌɪntəˈneɪʃən/", "명사", "억양", "Natural intonation.", "자연스러운 억양."),
    "invention":     ("/ɪnˈvɛnʃən/", "명사", "발명", "A remarkable invention.", "놀라운 발명."),
    "irritate":      ("/ˈɪrɪteɪt/", "동사", "짜증나게 하다", "Don't irritate others.", "다른 사람을 짜증나게 하지 마세요."),
    "locker":        ("/ˈlɒkər/", "명사", "사물함", "Use the locker.", "사물함을 사용하세요."),
    "overlook":      ("/ˌoʊvərˈlʊk/", "동사", "간과하다, 내려다보다", "Don't overlook details.", "세부 사항을 간과하지 마세요."),
    "patent":        ("/ˈpeɪtənt/", "명사", "특허", "Apply for a patent.", "특허를 신청하세요."),
    "payable":       ("/ˈpeɪəbəl/", "형용사", "지불해야 할", "Payable on receipt.", "수령 시 지불."),
    "preliminary":   ("/prɪˈlɪmɪnəri/", "형용사", "예비의, 초보의", "Preliminary results.", "예비 결과."),
    "salesman":      ("/ˈseɪlzmən/", "명사", "영업사원, 판매원", "Top salesman.", "최고 영업사원."),
    "sauna":         ("/ˈsɔːnə/", "명사", "사우나", "Relax in the sauna.", "사우나에서 쉬세요."),
    "smoothly":      ("/ˈsmuːðli/", "부사", "매끄럽게, 순조롭게", "Run smoothly.", "순조롭게 진행하세요."),
    "sunshine":      ("/ˈsʌnʃaɪn/", "명사", "햇살", "Enjoy the sunshine.", "햇살을 즐기세요."),
    "tow":           ("/toʊ/", "동사", "끌다, 견인하다", "Tow the car.", "차를 견인하세요."),
    "translator":    ("/trænsˈleɪtər/", "명사", "번역가", "Hire a translator.", "번역가를 고용하세요."),
    "tuition":       ("/tjuːˈɪʃən/", "명사", "수업료", "Pay tuition fees.", "수업료를 납부하세요."),
    "unavailable":   ("/ˌʌnəˈveɪləbəl/", "형용사", "이용할 수 없는", "Service unavailable.", "서비스 이용 불가."),
    "violation":     ("/ˌvaɪəˈleɪʃən/", "명사", "위반", "Traffic violation.", "교통 위반."),
    "webpage":       ("/ˈwɛbpeɪdʒ/", "명사", "웹페이지", "Visit the webpage.", "웹페이지를 방문하세요."),
    "acceptance":    ("/əkˈsɛptəns/", "명사", "수락, 합격", "Letter of acceptance.", "합격 통지서."),
    "allocate":      ("/ˈæləkeɪt/", "동사", "할당하다", "Allocate resources.", "자원을 할당하세요."),
    "ambitious":     ("/æmˈbɪʃəs/", "형용사", "야망 있는", "She is ambitious.", "그녀는 야망이 있다."),
    "appendix":      ("/əˈpɛndɪks/", "명사", "부록, 맹장", "See the appendix.", "부록을 참조하세요."),
    "booth":         ("/buːð/", "명사", "부스, 칸막이 좌석", "Phone booth.", "전화 부스."),
    "clarify":       ("/ˈklærɪfaɪ/", "동사", "명확히 하다", "Clarify the instructions.", "지침을 명확히 하세요."),
    "classmate":     ("/ˈklɑːsmeɪt/", "명사", "반 친구, 동기", "My classmate.", "내 반 친구."),
    "compile":       ("/kəmˈpaɪl/", "동사", "수집하다, 편찬하다", "Compile the data.", "데이터를 수집하세요."),
    "correction":    ("/kəˈrɛkʃən/", "명사", "수정, 교정", "Make corrections.", "수정을 하세요."),
    "customize":     ("/ˈkʌstəmaɪz/", "동사", "맞춤 제작하다", "Customize your settings.", "설정을 맞춤화하세요."),
    "dedication":    ("/ˌdɛdɪˈkeɪʃən/", "명사", "헌신, 전념", "Hard work and dedication.", "노력과 헌신."),
    "discontinue":   ("/ˌdɪskənˈtɪnjuː/", "동사", "중단하다, 폐지하다", "Discontinue the service.", "서비스를 중단하세요."),
    "dishwasher":    ("/ˈdɪʃwɒʃər/", "명사", "식기세척기", "Load the dishwasher.", "식기세척기에 넣으세요."),
    "drought":       ("/draʊt/", "명사", "가뭄", "Severe drought.", "심각한 가뭄."),
    "economize":     ("/ɪˈkɒnəmaɪz/", "동사", "절약하다", "Economize on electricity.", "전기를 절약하세요."),
    "entrée":        ("/ˈɒntreɪ/", "명사", "주요리, 앙트레", "Order the entrée.", "주요리를 주문하세요."),
    "firework":      ("/ˈfaɪərwɜːrk/", "명사", "불꽃놀이", "Watch fireworks.", "불꽃놀이를 보세요."),
    "freight":       ("/freɪt/", "명사", "화물", "Freight delivery.", "화물 배달."),
    "fry":           ("/fraɪ/", "동사", "튀기다, 볶다", "Fry the eggs.", "달걀을 볶으세요."),
    "gallon":        ("/ˈɡælən/", "명사", "갤런", "Buy a gallon of milk.", "우유 한 갤런을 사세요."),
    "gardener":      ("/ˈɡɑːrdənər/", "명사", "정원사", "Hire a gardener.", "정원사를 고용하세요."),
    "ideally":       ("/aɪˈdiːəli/", "부사", "이상적으로", "Ideally, we would start now.", "이상적으로는 지금 시작하겠습니다."),
    "inclusive":     ("/ɪnˈkluːsɪv/", "형용사", "포괄적인", "All-inclusive package.", "올인클루시브 패키지."),
    "insufficient":  ("/ˌɪnsəˈfɪʃənt/", "형용사", "불충분한", "Insufficient funds.", "불충분한 자금."),
    "introductory":  ("/ˌɪntrəˈdʌktəri/", "형용사", "입문의, 서론의", "Introductory price.", "입문 가격."),
    "junk":          ("/dʒʌŋk/", "명사", "쓰레기, 불필요한 물건", "Throw away junk.", "쓰레기를 버리세요."),
    "mileage":       ("/ˈmaɪlɪdʒ/", "명사", "주행 거리", "Check the car's mileage.", "차의 주행 거리를 확인하세요."),
    "noisy":         ("/ˈnɔɪzi/", "형용사", "시끄러운", "Noisy environment.", "시끄러운 환경."),
    "pan":           ("/pæn/", "명사", "팬, 냄비", "Heat the pan.", "팬을 달구세요."),
    "parcel":        ("/ˈpɑːrsəl/", "명사", "소포", "Deliver the parcel.", "소포를 배달하세요."),
    "pasta":         ("/ˈpæstə/", "명사", "파스타", "Cook pasta.", "파스타를 요리하세요."),
    "periodical":    ("/ˌpɪəriˈɒdɪkəl/", "명사", "정기 간행물", "Academic periodical.", "학술 정기 간행물."),
    "pill":          ("/pɪl/", "명사", "알약", "Take the pill.", "알약을 복용하세요."),
    "portable":      ("/ˈpɔːrtəbəl/", "형용사", "휴대용의", "Portable charger.", "휴대용 충전기."),
    "punctual":      ("/ˈpʌŋktʃuəl/", "형용사", "시간을 지키는", "Be punctual.", "시간을 지키세요."),
    "recreation":    ("/ˌrɛkriˈeɪʃən/", "명사", "여가, 오락", "Recreation area.", "여가 공간."),
    "relieve":       ("/rɪˈliːv/", "동사", "완화하다, 교대하다", "Relieve stress.", "스트레스를 완화하세요."),
    "reminder":      ("/rɪˈmaɪndər/", "명사", "알림, 리마인더", "Set a reminder.", "알림을 설정하세요."),
    "rumor":         ("/ˈruːmər/", "명사", "소문", "Ignore the rumor.", "소문을 무시하세요."),
    "scarf":         ("/skɑːrf/", "명사", "스카프", "Wear a warm scarf.", "따뜻한 스카프를 두르세요."),
    "seaside":       ("/ˈsiːsaɪd/", "명사", "해변가", "Relax at the seaside.", "해변가에서 쉬세요."),
    "shorten":       ("/ˈʃɔːrtən/", "동사", "줄이다, 단축하다", "Shorten the deadline.", "마감 기한을 단축하세요."),
    "specially":     ("/ˈspɛʃəli/", "부사", "특별히", "Specially prepared.", "특별히 준비됐다."),
    "spill":         ("/spɪl/", "동사", "쏟다, 엎지르다", "Spill the coffee.", "커피를 쏟다."),
    "spouse":        ("/spaʊs/", "명사", "배우자", "My spouse.", "내 배우자."),
    "subtract":      ("/səbˈtrækt/", "동사", "빼다, 차감하다", "Subtract the discount.", "할인액을 빼세요."),
    "tablet":        ("/ˈtæblɪt/", "명사", "태블릿", "Use a tablet.", "태블릿을 사용하세요."),
    "ton":           ("/tʌn/", "명사", "톤", "One ton.", "1톤."),
    "vend":          ("/vɛnd/", "동사", "판매하다, 팔다", "Vend the product.", "제품을 판매하다."),
    "yoga":          ("/ˈjoʊɡə/", "명사", "요가", "Practice yoga daily.", "매일 요가를 하세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT12:
                    pron, pos, meaning, ex_en, ex_ko = DICT12[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more12.py ===\n")
    patch_files()
