#!/usr/bin/env python3
"""
Fill word data for all source-list wordbooks (frequency, toeic, business, academic).
Uses embedded dictionary + suffix-based fallback for words not in dict.
"""
import json, os, re, hashlib

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, "src", "data")

# ---------------------------------------------------------------------------
# Master dictionary: word → (pronunciation, part_of_speech_ko, meaning_ko,
#                             example_en, example_ko)
# ---------------------------------------------------------------------------
DICT = {
# ─── Most frequent English words (NGSL Level 1) ──────────────────────────
"the": ("/ðə/","관사","그, 그것의","The book is on the table.","그 책은 테이블 위에 있습니다."),
"be": ("/biː/","동사","~이다, 있다","She wants to be a doctor someday.","그녀는 언젠가 의사가 되고 싶다."),
"and": ("/ænd/","접속사","그리고, ~와","I ordered coffee and a sandwich.","나는 커피와 샌드위치를 주문했다."),
"of": ("/ɒv/","전치사","~의, ~에 관한","This is a map of the city.","이것은 도시의 지도입니다."),
"to": ("/tuː/","전치사","~에, ~으로","I need to go to the airport.","공항에 가야 합니다."),
"a": ("/eɪ/","관사","하나의, 어떤","I need a pen, please.","펜 하나가 필요합니다."),
"in": ("/ɪn/","전치사","~안에, ~에서","She lives in Seoul.","그녀는 서울에 살고 있습니다."),
"have": ("/hæv/","동사","가지다, 있다","I have a reservation for tonight.","오늘 밤 예약이 있습니다."),
"it": ("/ɪt/","대명사","그것","It is very cold today.","오늘 날씨가 매우 춥습니다."),
"you": ("/juː/","대명사","당신, 너","Can you help me, please?","좀 도와주실 수 있나요?"),
"he": ("/hiː/","대명사","그","He is the manager of this hotel.","그는 이 호텔의 매니저입니다."),
"for": ("/fɔːr/","전치사","~을 위해, ~ 동안","I booked this room for three nights.","이 방을 3박으로 예약했습니다."),
"they": ("/ðeɪ/","대명사","그들","They are waiting in the lobby.","그들은 로비에서 기다리고 있습니다."),
"not": ("/nɒt/","부사","~아닌, ~하지 않는","I did not receive my luggage.","짐을 받지 못했습니다."),
"that": ("/ðæt/","대명사","그것, 저것","That is the building I mentioned.","저것이 내가 말한 건물입니다."),
"we": ("/wiː/","대명사","우리","We need two tickets for the tour.","투어 티켓 두 장이 필요합니다."),
"on": ("/ɒn/","전치사","~위에, ~에","The flight leaves on Monday.","항공편은 월요일에 출발합니다."),
"with": ("/wɪð/","전치사","~와 함께","Come with me to the station.","나와 함께 역으로 가요."),
"she": ("/ʃiː/","대명사","그녀","She checked in this morning.","그녀는 오늘 아침에 체크인했습니다."),
"do": ("/duː/","동사","하다","Do you accept credit cards?","신용카드를 받으시나요?"),
"this": ("/ðɪs/","대명사","이것, 이","This is my passport.","이것은 내 여권입니다."),
"but": ("/bʌt/","접속사","그러나, 하지만","The room was clean but small.","방은 깨끗했지만 작았다."),
"his": ("/hɪz/","대명사","그의","His luggage was lost at the airport.","그의 짐이 공항에서 분실되었습니다."),
"from": ("/frɒm/","전치사","~에서, ~로부터","I am from Korea.","저는 한국에서 왔습니다."),
"say": ("/seɪ/","동사","말하다","What did the announcement say?","안내 방송에서 무슨 말을 했나요?"),
"at": ("/æt/","전치사","~에, ~에서","Meet me at the gate at 10 a.m.","오전 10시에 탑승구에서 만납시다."),
"what": ("/wɒt/","대명사","무엇, 어떤","What time does the train leave?","기차는 몇 시에 출발하나요?"),
"her": ("/hɜːr/","대명사","그녀의, 그녀를","Her reservation was confirmed.","그녀의 예약이 확인되었습니다."),
"all": ("/ɔːl/","형용사","모든, 전부의","All passengers must board now.","모든 승객은 지금 탑승해야 합니다."),
"will": ("/wɪl/","동사","~할 것이다","The bus will arrive in five minutes.","버스가 5분 안에 도착할 것입니다."),
"one": ("/wʌn/","명사","하나, 1","I need one more ticket.","티켓이 한 장 더 필요합니다."),
"about": ("/əˈbaʊt/","전치사","~에 대하여, 약","The tour takes about two hours.","투어는 약 두 시간 걸립니다."),
"if": ("/ɪf/","접속사","만약 ~라면","Let me know if you need anything.","필요한 것이 있으면 알려주세요."),
"would": ("/wʊd/","동사","~할 텐데, ~해주시겠어요","Would you like a window seat?","창가 좌석으로 하시겠어요?"),
"which": ("/wɪtʃ/","대명사","어느, 어떤 것","Which platform does the train leave from?","기차가 어느 플랫폼에서 출발하나요?"),
"me": ("/miː/","대명사","나를, 나에게","Can you show me the way?","길을 알려주실 수 있나요?"),
"make": ("/meɪk/","동사","만들다","Can I make a reservation here?","여기서 예약할 수 있나요?"),
"can": ("/kæn/","동사","~할 수 있다","Can you help me with my bag?","가방 드는 것을 도와주실 수 있나요?"),
"like": ("/laɪk/","동사","좋아하다, ~처럼","I'd like a room with a view.","전망 좋은 방을 원합니다."),
"no": ("/noʊ/","부사","아니오, 없는","There are no available rooms tonight.","오늘 밤 이용 가능한 방이 없습니다."),
"just": ("/dʒʌst/","부사","단지, 바로","I just arrived at the hotel.","방금 호텔에 도착했습니다."),
"him": ("/hɪm/","대명사","그를, 그에게","Please give him the room key.","그에게 객실 키를 주세요."),
"know": ("/noʊ/","동사","알다","Do you know where the nearest ATM is?","가장 가까운 ATM이 어디 있는지 아세요?"),
"take": ("/teɪk/","동사","가져가다, 걸리다","It takes 30 minutes to reach the city center.","도심까지 30분이 걸립니다."),
"people": ("/ˈpiːpəl/","명사","사람들","Many people visit this museum every day.","매일 많은 사람들이 이 박물관을 방문합니다."),
"into": ("/ˈɪntə/","전치사","~안으로","Please come into the office.","사무실 안으로 들어오세요."),
"come": ("/kʌm/","동사","오다","When does the next bus come?","다음 버스는 언제 오나요?"),
"could": ("/kʊd/","동사","~할 수 있었다, ~해주실 수 있나요","Could you repeat that, please?","다시 한 번 말씀해 주실 수 있나요?"),
"now": ("/naʊ/","부사","지금, 현재","You can check in now.","지금 체크인할 수 있습니다."),
"than": ("/ðæn/","접속사","~보다","This hotel is cheaper than the other one.","이 호텔이 다른 곳보다 저렴합니다."),
"other": ("/ˈʌðər/","형용사","다른, 그 밖의","Are there other options available?","다른 선택지가 있나요?"),
"time": ("/taɪm/","명사","시간, 때","What time is check-out?","체크아웃 시간이 몇 시인가요?"),
"very": ("/ˈvɛri/","부사","매우, 아주","The service here is very good.","여기 서비스가 매우 좋습니다."),
"when": ("/wɛn/","접속사","~할 때, 언제","When does the tour start?","투어는 언제 시작하나요?"),
"who": ("/huː/","대명사","누구","Who should I contact for assistance?","도움을 받으려면 누구에게 연락해야 하나요?"),
"them": ("/ðɛm/","대명사","그들을","Tell them we will be late.","우리가 늦을 거라고 그들에게 말해줘."),
"some": ("/sʌm/","형용사","몇몇의, 어떤","I need some local currency.","현지 화폐가 조금 필요합니다."),
"there": ("/ðɛər/","부사","거기에, 그곳에","Is there a pharmacy nearby?","근처에 약국이 있나요?"),
"so": ("/soʊ/","접속사","그래서, 매우","The queue was so long!","줄이 정말 길었어요!"),
"think": ("/θɪŋk/","동사","생각하다","I think I left my bag on the train.","기차에 가방을 두고 온 것 같아요."),
"my": ("/maɪ/","대명사","나의","My flight is at seven o'clock.","내 항공편은 7시에 있습니다."),
"up": ("/ʌp/","부사","위로, 위에","The restaurant is up on the third floor.","레스토랑은 3층에 있습니다."),
"go": ("/ɡoʊ/","동사","가다","How do I go to the airport from here?","여기서 공항까지 어떻게 가나요?"),
"their": ("/ðɛər/","대명사","그들의","Their reservation was for two nights.","그들의 예약은 2박이었습니다."),
"then": ("/ðɛn/","부사","그때, 그러고 나서","Check in first, then leave your bags.","먼저 체크인하고 나서 짐을 맡기세요."),
"see": ("/siː/","동사","보다","Can I see your passport, please?","여권을 보여주실 수 있나요?"),
"also": ("/ˈɔːlsoʊ/","부사","또한, ~도","The hotel also offers airport transfers.","호텔에서는 공항 셔틀도 제공합니다."),
"way": ("/weɪ/","명사","방법, 길","Is there any way to get a discount?","할인받을 방법이 있나요?"),
"look": ("/lʊk/","동사","보다, 찾다","Let me look for your reservation.","예약을 찾아보겠습니다."),
"only": ("/ˈoʊnli/","부사","단지, 오직","We only have smoking rooms available.","흡연실만 이용 가능합니다."),
"well": ("/wɛl/","부사","잘, 충분히","Everything went well during the trip.","여행 중 모든 것이 잘 진행됐습니다."),
"should": ("/ʃʊd/","동사","~해야 한다","You should arrive two hours early.","두 시간 일찍 도착해야 합니다."),
"how": ("/haʊ/","부사","어떻게","How do I get to the old town?","구시가지까지 어떻게 가나요?"),
"because": ("/bɪˈkɒz/","접속사","왜냐하면","I was late because of traffic.","교통 체증 때문에 늦었습니다."),
"get": ("/ɡɛt/","동사","얻다, 가져오다","Where can I get a taxi?","택시는 어디서 탈 수 있나요?"),
"an": ("/æn/","관사","하나의 (모음 앞)","Can I have an extra blanket?","담요를 하나 더 주실 수 있나요?"),
"or": ("/ɔːr/","접속사","또는","Cash or card?","현금인가요 아니면 카드인가요?"),
"use": ("/juːz/","동사","사용하다","Can I use this card here?","여기서 이 카드를 사용할 수 있나요?"),
"its": ("/ɪts/","대명사","그것의","The hotel is known for its excellent service.","그 호텔은 훌륭한 서비스로 유명합니다."),
"two": ("/tuː/","명사","둘, 2","I need two single rooms.","싱글룸 두 개가 필요합니다."),
"more": ("/mɔːr/","형용사","더 많은","Do you have any more rooms available?","이용 가능한 방이 더 있나요?"),
"these": ("/ðiːz/","대명사","이것들","Can I have these items gift-wrapped?","이것들을 선물 포장해 주실 수 있나요?"),
"want": ("/wɒnt/","동사","원하다","I want a room on a higher floor.","높은 층의 방을 원합니다."),
"first": ("/fɜːrst/","형용사","첫 번째의","Take the first left turn.","첫 번째 왼쪽으로 도세요."),
"give": ("/ɡɪv/","동사","주다","Please give me your luggage tag.","짐표를 주세요."),
"most": ("/moʊst/","형용사","가장 많은","Most tourists visit in summer.","대부분의 관광객은 여름에 방문합니다."),
"find": ("/faɪnd/","동사","찾다, 발견하다","I can't find my booking confirmation.","예약 확인서를 찾을 수 없어요."),
"here": ("/hɪər/","부사","여기에","Please sign here.","여기에 서명해 주세요."),
"thing": ("/θɪŋ/","명사","것, 물건","Is there anything I should know?","알아야 할 것이 있나요?"),
"many": ("/ˈmɛni/","형용사","많은","There are many things to see here.","여기에는 볼 것들이 많이 있습니다."),
"those": ("/ðoʊz/","대명사","저것들","Those bags belong to me.","저 가방들이 제 것입니다."),
"tell": ("/tɛl/","동사","말하다, 알려주다","Can you tell me where to find the bus stop?","버스 정류장이 어디 있는지 알려주실 수 있나요?"),
"day": ("/deɪ/","명사","날, 하루","What time does the museum open each day?","박물관은 매일 몇 시에 문을 여나요?"),
"may": ("/meɪ/","동사","~해도 된다, ~일지도","May I see your passport?","여권을 봐도 될까요?"),
"after": ("/ˈɑːftər/","전치사","~후에","After check-in, head to the pool.","체크인 후 수영장으로 가세요."),
"back": ("/bæk/","명사","뒤, 등","I'll be back in ten minutes.","10분 후에 돌아올게요."),
"new": ("/njuː/","형용사","새로운","Is there a new route to the airport?","공항으로 가는 새로운 경로가 있나요?"),
"good": ("/ɡʊd/","형용사","좋은","Have a good trip!","좋은 여행 되세요!"),
"year": ("/jɪər/","명사","년, 해","This hotel has been open for over 50 years.","이 호텔은 50년 넘게 운영되었습니다."),
"right": ("/raɪt/","형용사","올바른, 오른쪽의","Turn right at the next intersection.","다음 교차로에서 오른쪽으로 도세요."),
"still": ("/stɪl/","부사","여전히, 아직","The flight is still delayed.","항공편이 여전히 지연되고 있습니다."),
"work": ("/wɜːrk/","동사","일하다, 작동하다","The air conditioning doesn't work.","에어컨이 작동하지 않습니다."),
"our": ("/aʊər/","대명사","우리의","Our room has a great view of the sea.","우리 방은 바다 전망이 훌륭합니다."),
"as": ("/æz/","접속사","~로서, ~처럼","As a hotel guest, you get free breakfast.","호텔 투숙객으로서 무료 조식을 이용할 수 있습니다."),
"out": ("/aʊt/","부사","밖으로","Let's head out to explore the city.","도시를 탐방하러 나가봅시다."),
"over": ("/ˈoʊvər/","전치사","~위에, ~이상","The flight is over six hours long.","항공편은 6시간 이상입니다."),
"too": ("/tuː/","부사","너무, 또한","The room is too noisy.","방이 너무 시끄럽습니다."),
"need": ("/niːd/","동사","필요하다","I need help with my luggage.","짐에 도움이 필요합니다."),
"great": ("/ɡreɪt/","형용사","훌륭한, 대단한","The food here is great!","여기 음식이 정말 훌륭해요!"),
"much": ("/mʌtʃ/","형용사","많은","How much does the tour cost?","투어 비용이 얼마인가요?"),
"even": ("/ˈiːvən/","부사","심지어, ~조차","Even small rooms have a safe.","작은 방에도 금고가 있습니다."),
"own": ("/oʊn/","형용사","자신의","I have my own car rental.","제 렌터카가 있습니다."),
"each": ("/iːtʃ/","형용사","각각의","Each room has its own bathroom.","각 방에는 개인 욕실이 있습니다."),
"where": ("/wɛər/","부사","어디에","Where is the nearest pharmacy?","가장 가까운 약국이 어디인가요?"),
"any": ("/ˈɛni/","형용사","어떤, 아무","Is there any luggage storage nearby?","근처에 짐 보관 서비스가 있나요?"),
"must": ("/mʌst/","동사","~해야 한다","You must show ID at check-in.","체크인 시 신분증을 제시해야 합니다."),
"same": ("/seɪm/","형용사","같은, 동일한","I'd like the same room as before.","이전과 같은 방을 원합니다."),
"old": ("/oʊld/","형용사","오래된, 나이 든","The old town is full of history.","구시가지는 역사로 가득합니다."),
"long": ("/lɒŋ/","형용사","긴, 오래된","The queue was very long.","줄이 매우 길었습니다."),
"while": ("/waɪl/","접속사","~하는 동안","Please wait here while I check.","확인하는 동안 여기서 기다려 주세요."),
"both": ("/boʊθ/","형용사","둘 다의","Both options are available.","두 가지 옵션 모두 이용 가능합니다."),
"between": ("/bɪˈtwiːn/","전치사","~사이에","The hotel is between the park and the station.","호텔은 공원과 역 사이에 있습니다."),
"through": ("/θruː/","전치사","~을 통해","Go through the main entrance.","정문을 통해 들어가세요."),
"before": ("/bɪˈfɔːr/","전치사","~전에","Arrive at the airport before 8 a.m.","오전 8시 전에 공항에 도착하세요."),
"might": ("/maɪt/","동사","~일지도 모른다","The bus might be late today.","오늘 버스가 늦을 수도 있습니다."),
"another": ("/əˈnʌðər/","형용사","또 다른","Can I get another towel?","수건을 하나 더 받을 수 있나요?"),
"last": ("/lɑːst/","형용사","마지막의, 지난","This is the last stop before the terminal.","이것이 터미널 전 마지막 정류장입니다."),
"down": ("/daʊn/","부사","아래로","The restaurant is down on the ground floor.","레스토랑은 1층 아래에 있습니다."),
"keep": ("/kiːp/","동사","유지하다, 계속하다","Keep your boarding pass safe.","탑승권을 잘 보관하세요."),
"call": ("/kɔːl/","동사","부르다, 전화하다","Please call reception if you need anything.","필요한 것이 있으면 리셉션에 전화하세요."),
"put": ("/pʊt/","동사","놓다, 두다","Put your luggage on the conveyor belt.","짐을 컨베이어 벨트에 올리세요."),
"never": ("/ˈnɛvər/","부사","결코 ~않다","I have never tried this local dish before.","이 현지 요리를 먹어본 적이 없습니다."),
"such": ("/sʌtʃ/","형용사","그러한","Such a long flight needs good preparation.","그런 긴 비행은 충분한 준비가 필요합니다."),
"part": ("/pɑːrt/","명사","부분","This is part of the tour package.","이것은 투어 패키지의 일부입니다."),
"again": ("/əˈɡɛn/","부사","다시","Can you say that again, please?","다시 한 번 말씀해 주시겠어요?"),
"help": ("/hɛlp/","동사","돕다","Can someone help me with my luggage?","짐 옮기는 것을 도와줄 수 있나요?"),
"every": ("/ˈɛvri/","형용사","모든, 매","The shuttle runs every 30 minutes.","셔틀은 30분마다 운행됩니다."),
"try": ("/traɪ/","동사","시도하다, 노력하다","Please try calling the front desk.","프런트 데스크에 전화해 보세요."),
"leave": ("/liːv/","동사","떠나다, 남기다","What time do we leave tomorrow?","우리 내일 몇 시에 출발하나요?"),
"hand": ("/hænd/","명사","손","Please hand me your boarding pass.","탑승권을 건네주세요."),
"turn": ("/tɜːrn/","동사","돌다, 돌리다","Turn left at the next corner.","다음 모퉁이에서 왼쪽으로 도세요."),
"show": ("/ʃoʊ/","동사","보여주다","Please show your passport.","여권을 보여주세요."),
"let": ("/lɛt/","동사","~하게 하다","Let me check your reservation.","예약을 확인해 보겠습니다."),
"begin": ("/bɪˈɡɪn/","동사","시작하다","The tour will begin at the main square.","투어는 중앙 광장에서 시작될 것입니다."),
"life": ("/laɪf/","명사","삶, 생명","Traveling enriches your life.","여행은 삶을 풍요롭게 합니다."),
"run": ("/rʌn/","동사","달리다, 운영하다","The trains run every 20 minutes.","기차는 20분마다 운행됩니다."),
"place": ("/pleɪs/","명사","장소","This is a great place to visit.","여기는 방문하기에 좋은 장소입니다."),
"off": ("/ɒf/","부사","떨어져, 꺼진","The flight has been called off.","항공편이 취소되었습니다."),
"always": ("/ˈɔːlweɪz/","부사","항상","Always keep your valuables in the safe.","항상 귀중품을 금고에 보관하세요."),
"end": ("/ɛnd/","명사","끝, 종료","The tour ends at the museum.","투어는 박물관에서 끝납니다."),
"small": ("/smɔːl/","형용사","작은","Do you have a smaller bag?","더 작은 가방이 있나요?"),
"number": ("/ˈnʌmbər/","명사","숫자, 번호","What is your room number?","객실 번호가 몇 호인가요?"),
"big": ("/bɪɡ/","형용사","큰","The hotel has a big conference room.","호텔에는 큰 회의실이 있습니다."),
"home": ("/hoʊm/","명사","집, 가정","I'm finally going home after two weeks abroad.","2주간의 해외 생활 끝에 드디어 집으로 돌아갑니다."),
"water": ("/ˈwɔːtər/","명사","물","Can I get a bottle of water?","물 한 병 주실 수 있나요?"),
"high": ("/haɪ/","형용사","높은","We have rooms on the high floors.","높은 층에 방이 있습니다."),
"different": ("/ˈdɪfrənt/","형용사","다른, 다양한","I'd like a different room, please.","다른 방으로 바꿔 주시겠어요?"),
"head": ("/hɛd/","동사","향하다","Head toward the departure gate.","출발 탑승구 쪽으로 향하세요."),
"move": ("/muːv/","동사","움직이다, 이동하다","Please move your luggage to the side.","짐을 옆으로 옮겨주세요."),
"large": ("/lɑːrdʒ/","형용사","큰, 거대한","Is there a large locker available?","큰 사물함이 있나요?"),
"few": ("/fjuː/","형용사","적은, 몇몇의","Only a few rooms are left.","방이 몇 개 남지 않았습니다."),
"house": ("/haʊs/","명사","집","I rented a beach house for the vacation.","휴가 동안 해변 하우스를 빌렸습니다."),
"kind": ("/kaɪnd/","명사","종류, 유형","What kind of room would you like?","어떤 종류의 방을 원하세요?"),
"world": ("/wɜːrld/","명사","세계, 세상","Travelers from all over the world visit here.","전 세계에서 여행객들이 이곳을 방문합니다."),
"under": ("/ˈʌndər/","전치사","~아래에","The luggage is under the bed.","짐이 침대 아래에 있습니다."),
"name": ("/neɪm/","명사","이름","What name is the reservation under?","예약이 어떤 이름으로 되어 있나요?"),
"school": ("/skuːl/","명사","학교","The school is near the hotel.","학교가 호텔 근처에 있습니다."),
"write": ("/raɪt/","동사","쓰다","Please write your name here.","여기에 이름을 써주세요."),
"read": ("/riːd/","동사","읽다","Please read the hotel rules carefully.","호텔 규정을 꼼꼼히 읽어보세요."),
"point": ("/pɔɪnt/","명사","점, 요점","Could you point me in the right direction?","올바른 방향을 가리켜 주시겠어요?"),
"state": ("/steɪt/","명사","상태, 국가","What state is the room in?","방 상태가 어떤가요?"),
"group": ("/ɡruːp/","명사","그룹, 집단","We are a group of ten tourists.","우리는 10명의 관광객 그룹입니다."),
"change": ("/tʃeɪndʒ/","동사","바꾸다, 변경하다","Can I change my room?","방을 바꿀 수 있나요?"),
"country": ("/ˈkʌntri/","명사","나라, 국가","Which country are you traveling to?","어느 나라로 여행하시나요?"),
"close": ("/kloʊs/","형용사","가까운","Is the beach close to the hotel?","해변이 호텔과 가까운가요?"),
"play": ("/pleɪ/","동사","놀다, 연주하다","Children can play in the hotel garden.","아이들은 호텔 정원에서 놀 수 있습니다."),
"question": ("/ˈkwɛstʃən/","명사","질문","Do you have any questions about your stay?","숙박에 대해 질문이 있으신가요?"),
"city": ("/ˈsɪti/","명사","도시","The city center is 5 km away.","도심은 5km 떨어져 있습니다."),
"live": ("/lɪv/","동사","살다","I live in Seoul and am visiting Tokyo.","저는 서울에 살고 도쿄를 방문 중입니다."),
"man": ("/mæn/","명사","남자, 사람","The man at the front desk was very helpful.","프런트 데스크의 남자가 매우 도움이 됐다."),
"woman": ("/ˈwʊmən/","명사","여자, 여성","A woman in uniform greeted us at the entrance.","제복을 입은 여성이 입구에서 우리를 맞이했습니다."),
"child": ("/tʃaɪld/","명사","아이","Children under 12 stay free.","12세 미만 아이는 무료로 숙박할 수 있습니다."),
"open": ("/ˈoʊpən/","동사","열다","The gift shop opens at 9 a.m.","기념품 가게는 오전 9시에 문을 엽니다."),
"night": ("/naɪt/","명사","밤","The rate is $100 per night.","1박 요금은 100달러입니다."),
"hold": ("/hoʊld/","동사","잡다, 들다","Please hold on while I transfer your call.","전화를 연결하는 동안 잠시 기다려주세요."),
"follow": ("/ˈfɒloʊ/","동사","따르다","Follow the signs to the exit.","출구 표지판을 따라가세요."),
"without": ("/wɪˈðaʊt/","전치사","~없이","You can't enter without a ticket.","티켓 없이는 입장할 수 없습니다."),
"next": ("/nɛkst/","형용사","다음의","The next shuttle leaves at noon.","다음 셔틀은 정오에 출발합니다."),
"stop": ("/stɒp/","동사","멈추다","Could you stop the car here, please?","여기서 차를 세워 주시겠어요?"),
"mean": ("/miːn/","동사","의미하다","What does this sign mean?","이 표지판은 무슨 뜻인가요?"),
"start": ("/stɑːrt/","동사","시작하다","The city tour starts at 9 a.m.","시티 투어는 오전 9시에 시작합니다."),
"set": ("/sɛt/","동사","설정하다, 놓다","Can you set a wake-up call for 6 a.m.?","오전 6시에 모닝콜을 설정해 주실 수 있나요?"),
"hear": ("/hɪər/","동사","듣다","I can't hear the announcement clearly.","안내 방송이 잘 들리지 않아요."),
"seem": ("/siːm/","동사","~처럼 보이다","It seems the train is running late.","기차가 늦게 운행되는 것 같습니다."),
"talk": ("/tɔːk/","동사","말하다, 이야기하다","Can I talk to the manager, please?","매니저와 이야기할 수 있을까요?"),
"stand": ("/stænd/","동사","서다","Please stand behind the yellow line.","노란 선 뒤에 서 주세요."),
"side": ("/saɪd/","명사","옆, 측면","The hotel entrance is on the side of the building.","호텔 입구는 건물 측면에 있습니다."),
"face": ("/feɪs/","명사","얼굴","The receptionist had a friendly face.","접수 담당자는 친절한 얼굴을 하고 있었다."),
"young": ("/jʌŋ/","형용사","젊은","Young travelers often prefer hostels.","젊은 여행객들은 종종 호스텔을 선호합니다."),
"bring": ("/brɪŋ/","동사","가져오다","Bring your passport to the counter.","카운터에 여권을 가져오세요."),
"though": ("/ðoʊ/","접속사","비록 ~일지라도","Though the room was small, it was clean.","방은 작았지만 깨끗했습니다."),
"body": ("/ˈbɒdi/","명사","몸, 신체","The spa offers various body treatments.","스파에서는 다양한 신체 관리 서비스를 제공합니다."),
"real": ("/riːl/","형용사","진짜의, 실제의","Is this a real leather bag?","이것은 진짜 가죽 가방인가요?"),
"sure": ("/ʃʊər/","형용사","확실한","Are you sure the flight is on time?","항공편이 정시에 있는 것이 확실한가요?"),
"enough": ("/ɪˈnʌf/","형용사","충분한","Is there enough time to catch the train?","기차를 타기에 충분한 시간이 있나요?"),
"ask": ("/ɑːsk/","동사","묻다, 요청하다","Feel free to ask any questions.","자유롭게 질문하세요."),
"feel": ("/fiːl/","동사","느끼다","Do you feel comfortable in your room?","객실이 편안하신가요?"),
"learn": ("/lɜːrn/","동사","배우다","I'd like to learn a few local phrases.","현지 표현 몇 가지를 배우고 싶습니다."),
"study": ("/ˈstʌdi/","동사","공부하다","I often study local maps before a trip.","여행 전에 자주 현지 지도를 공부합니다."),
"become": ("/bɪˈkʌm/","동사","~이 되다","Traveling can become addictive.","여행은 중독성이 생길 수 있습니다."),
"power": ("/ˈpaʊər/","명사","힘, 전력","Is there a power outlet near the desk?","책상 근처에 전원 콘센트가 있나요?"),
"problem": ("/ˈprɒbləm/","명사","문제","Is there a problem with my reservation?","제 예약에 문제가 있나요?"),
"fact": ("/fækt/","명사","사실","The fact is, there's only one room left.","사실은 방이 하나만 남아 있습니다."),
"family": ("/ˈfæməli/","명사","가족","We need a family room for four people.","4인 가족 객실이 필요합니다."),
"eye": ("/aɪ/","명사","눈","The eye-catching architecture attracted tourists.","눈길을 끄는 건축물이 관광객들을 끌어들였습니다."),
"against": ("/əˈɡɛnst/","전치사","~에 반대하여","Smoking is against the hotel policy.","흡연은 호텔 정책에 위반됩니다."),
"money": ("/ˈmʌni/","명사","돈","I need to exchange money at the bank.","은행에서 환전해야 합니다."),
"until": ("/ənˈtɪl/","접속사","~할 때까지","Wait here until the shuttle arrives.","셔틀이 올 때까지 여기서 기다리세요."),
"during": ("/ˈdjʊərɪŋ/","전치사","~동안","The pool is open during the day.","수영장은 낮 동안 운영됩니다."),
"since": ("/sɪns/","전치사","~이후로","I've been waiting since noon.","정오부터 기다리고 있었습니다."),
"already": ("/ɔːlˈrɛdi/","부사","이미","I've already paid the deposit.","이미 보증금을 냈습니다."),
"however": ("/haʊˈɛvər/","부사","그러나, 하지만","However, there is still a cancellation fee.","그러나 취소 수수료가 여전히 있습니다."),
"important": ("/ɪmˈpɔːrtənt/","형용사","중요한","It's important to keep your passport safe.","여권을 안전하게 보관하는 것이 중요합니다."),
"often": ("/ˈɒfən/","부사","자주","Flights are often delayed in bad weather.","나쁜 날씨에는 항공편이 자주 지연됩니다."),

# ─── NGSL Level 2 words ───────────────────────────────────────────────────
"age": ("/eɪdʒ/","명사","나이, 연령","What is the minimum age to rent a car?","렌터카를 빌리기 위한 최소 연령은 얼마인가요?"),
"low": ("/loʊ/","형용사","낮은","We found a hotel at a low price.","저렴한 가격의 호텔을 찾았습니다."),
"speak": ("/spiːk/","동사","말하다","Does anyone here speak Korean?","여기 한국어를 하시는 분이 있나요?"),
"within": ("/wɪˈðɪn/","전치사","~이내에","The hotel is within walking distance of the beach.","호텔은 해변까지 걸어갈 수 있는 거리 내에 있습니다."),
"process": ("/ˈprɒsɛs/","명사","과정, 절차","The check-in process takes about five minutes.","체크인 절차는 약 5분이 걸립니다."),
"public": ("/ˈpʌblɪk/","형용사","공공의, 대중의","The public transport is very convenient here.","이곳의 대중교통은 매우 편리합니다."),
"train": ("/treɪn/","명사","기차","The train to the airport runs every 15 minutes.","공항행 기차는 15분마다 운행됩니다."),
"clear": ("/klɪər/","형용사","명확한, 맑은","The weather is clear for our trip today.","오늘 여행 날씨가 맑습니다."),
"land": ("/lænd/","동사","착륙하다","The plane will land in 30 minutes.","비행기가 30분 후 착륙할 것입니다."),
"hand": ("/hænd/","명사","손","Please raise your hand if you need assistance.","도움이 필요하시면 손을 드세요."),
"stand": ("/stænd/","명사","가판대, 입장","There is a newspaper stand at the airport.","공항에 신문 가판대가 있습니다."),
"service": ("/ˈsɜːrvɪs/","명사","서비스","The hotel service was excellent.","호텔 서비스가 훌륭했습니다."),
"book": ("/bʊk/","동사","예약하다","I need to book two tickets.","티켓 두 장을 예약해야 합니다."),
"pay": ("/peɪ/","동사","지불하다","How would you like to pay?","어떻게 지불하시겠어요?"),
"car": ("/kɑːr/","명사","자동차","I rented a car at the airport.","공항에서 차를 빌렸습니다."),
"street": ("/striːt/","명사","거리","What street is the hotel on?","호텔이 어떤 거리에 있나요?"),
"road": ("/roʊd/","명사","도로","This road leads to the city center.","이 도로는 도심으로 이어집니다."),
"stay": ("/steɪ/","동사","머물다","How long will you stay?","얼마나 머무실 건가요?"),
"free": ("/friː/","형용사","무료의, 자유로운","Is Wi-Fi free at this hotel?","이 호텔에서 와이파이가 무료인가요?"),
"office": ("/ˈɒfɪs/","명사","사무소, 사무실","The tourist office is next to the station.","관광 안내소는 역 옆에 있습니다."),
"month": ("/mʌnθ/","명사","달, 월","I booked the hotel for next month.","다음 달 호텔을 예약했습니다."),
"wait": ("/weɪt/","동사","기다리다","Please wait here for the shuttle.","셔틀을 위해 여기서 기다려 주세요."),
"walk": ("/wɔːk/","동사","걷다","Let's walk to the beach.","해변까지 걸어갑시다."),
"spend": ("/spɛnd/","동사","보내다, 쓰다","How much do you plan to spend on the trip?","여행에 얼마를 쓸 계획인가요?"),
"area": ("/ˈɛəriə/","명사","지역, 구역","What is the safest area to stay?","머물기에 가장 안전한 지역이 어디인가요?"),
"center": ("/ˈsɛntər/","명사","중심, 센터","The information center is downtown.","안내 센터는 시내에 있습니다."),
"carry": ("/ˈkæri/","동사","나르다, 들다","Can you carry my bag to the room?","방까지 가방을 들어다 주시겠어요?"),
"offer": ("/ˈɒfər/","동사","제공하다","Does the hotel offer airport transfers?","호텔에서 공항 송영 서비스를 제공하나요?"),
"include": ("/ɪnˈkluːd/","동사","포함하다","Does the price include breakfast?","가격에 조식이 포함되어 있나요?"),
"return": ("/rɪˈtɜːrn/","동사","돌아오다, 반환하다","When do you return from your trip?","여행에서 언제 돌아오시나요?"),
"send": ("/sɛnd/","동사","보내다","Can you send a taxi to the hotel?","호텔로 택시를 보내주실 수 있나요?"),
"enter": ("/ˈɛntər/","동사","들어가다","Please enter through the main door.","정문으로 들어가세요."),
"city": ("/ˈsɪti/","명사","도시","The old city is a must-see attraction.","구시가지는 꼭 봐야 할 명소입니다."),
"money": ("/ˈmʌni/","명사","돈","I need to exchange money.","돈을 환전해야 합니다."),
"pass": ("/pɑːs/","동사","지나가다, 통과하다","Please pass through the security gate.","보안 게이트를 통과해 주세요."),
"open": ("/ˈoʊpən/","형용사","열린, 영업 중인","Is the restaurant open now?","지금 레스토랑이 영업 중인가요?"),
"report": ("/rɪˈpɔːrt/","동사","신고하다","Please report any issues to the front desk.","문제가 있으면 프런트 데스크에 신고해 주세요."),
"check": ("/tʃɛk/","동사","확인하다","Let me check your reservation.","예약을 확인해 보겠습니다."),
"window": ("/ˈwɪndoʊ/","명사","창문","Please keep the window closed.","창문을 닫아두세요."),
"morning": ("/ˈmɔːrnɪŋ/","명사","아침","Good morning! How can I help you?","안녕하세요! 무엇을 도와드릴까요?"),
"evening": ("/ˈiːvnɪŋ/","명사","저녁","The restaurant is open every evening.","레스토랑은 매일 저녁 운영됩니다."),
"miss": ("/mɪs/","동사","놓치다","I almost missed my flight.","항공편을 놓칠 뻔했습니다."),
"reach": ("/riːtʃ/","동사","도달하다","How long does it take to reach the center?","시내까지 얼마나 걸리나요?"),
"add": ("/æd/","동사","추가하다","Can I add breakfast to my reservation?","예약에 조식을 추가할 수 있나요?"),
"break": ("/breɪk/","명사","휴식","Let's take a short break here.","여기서 잠깐 휴식을 취합시다."),
"sign": ("/saɪn/","동사","서명하다","Please sign the registration form.","등록 양식에 서명해 주세요."),
"happen": ("/ˈhæpən/","동사","발생하다","What happened to my luggage?","내 짐에 무슨 일이 생겼나요?"),
"town": ("/taʊn/","명사","마을, 도심","The hotel is in the center of town.","호텔은 마을 중심부에 있습니다."),
"line": ("/laɪn/","명사","줄, 노선","The metro line goes directly to the airport.","지하철 노선이 공항으로 바로 연결됩니다."),
"type": ("/taɪp/","명사","유형, 종류","What type of room would you prefer?","어떤 유형의 방을 선호하세요?"),
"night": ("/naɪt/","명사","밤, 1박","The rate is $120 per night.","1박 요금은 120달러입니다."),
"week": ("/wiːk/","명사","주, 일주일","I'll be staying for a week.","1주일 동안 머물 예정입니다."),
"plan": ("/plæn/","명사","계획","What's the plan for tomorrow?","내일 계획이 어떻게 되나요?"),
"lose": ("/luːz/","동사","잃어버리다","I think I lost my room key.","객실 키를 잃어버린 것 같습니다."),
"hold": ("/hoʊld/","동사","잡다, 보류하다","Can you hold my bags for an hour?","한 시간 동안 짐을 맡아주실 수 있나요?"),
"provide": ("/prəˈvaɪd/","동사","제공하다","The hotel provides free towels and toiletries.","호텔에서 무료 수건과 세면도구를 제공합니다."),
"local": ("/ˈloʊkəl/","형용사","현지의","Ask the concierge for local restaurant recommendations.","컨시어지에게 현지 레스토랑을 추천받으세요."),
"hour": ("/ˈaʊər/","명사","시간","Check-in is available 24 hours a day.","체크인은 24시간 이용 가능합니다."),
"need": ("/niːd/","명사","필요","I have a special need — a ground floor room.","특별 요청이 있습니다 — 1층 방이 필요합니다."),
"share": ("/ʃɛər/","동사","공유하다","Can we share a taxi to the airport?","공항까지 택시를 같이 탈 수 있나요?"),
"late": ("/leɪt/","형용사","늦은","The flight arrived late.","항공편이 늦게 도착했습니다."),
"early": ("/ˈɜːrli/","형용사","이른","We have an early morning flight.","이른 아침 항공편이 있습니다."),
"next": ("/nɛkst/","형용사","다음의","When is the next bus to downtown?","시내행 다음 버스는 언제인가요?"),
"across": ("/əˈkrɒs/","전치사","맞은편에","The supermarket is across the street.","슈퍼마켓은 길 건너편에 있습니다."),
"point": ("/pɔɪnt/","동사","가리키다","Could you point me to the nearest exit?","가장 가까운 출구를 가리켜 주시겠어요?"),
"drive": ("/draɪv/","동사","운전하다","It takes 20 minutes to drive to the airport.","공항까지 운전하면 20분이 걸립니다."),
"south": ("/saʊθ/","명사","남쪽","The beach is to the south of the hotel.","해변은 호텔 남쪽에 있습니다."),
"north": ("/nɔːrθ/","명사","북쪽","Walk north for three blocks.","북쪽으로 세 블록 걸어가세요."),
"east": ("/iːst/","명사","동쪽","The shopping district is to the east.","쇼핑 지구는 동쪽에 있습니다."),
"west": ("/wɛst/","명사","서쪽","The sunset is beautiful to the west.","서쪽의 일몰이 아름답습니다."),
"floor": ("/flɔːr/","명사","층, 바닥","My room is on the 10th floor.","내 방은 10층에 있습니다."),
"receive": ("/rɪˈsiːv/","동사","받다","I didn't receive the confirmation email.","확인 이메일을 받지 못했습니다."),
"cost": ("/kɒst/","명사","비용","What is the total cost for three nights?","3박의 총 비용이 얼마인가요?"),
"allow": ("/əˈlaʊ/","동사","허락하다","Pets are not allowed in this hotel.","이 호텔에서는 반려동물이 허용되지 않습니다."),
"hour": ("/ˈaʊər/","명사","시간","We will arrive in two hours.","우리는 두 시간 후에 도착할 것입니다."),
"try": ("/traɪ/","동사","시도하다","Try the local cuisine while you're here.","여기 있는 동안 현지 음식을 시도해 보세요."),
"care": ("/kɛər/","동사","돌보다, 신경 쓰다","The hotel staff cares about your comfort.","호텔 직원은 고객의 편안함을 중요시합니다."),
"stand": ("/stænd/","동사","서다","Please stand in line for check-in.","체크인을 위해 줄을 서 주세요."),
"cover": ("/ˈkʌvər/","동사","덮다, 커버하다","Does the insurance cover lost luggage?","보험이 분실 수하물을 보장하나요?"),
"show": ("/ʃoʊ/","명사","공연","There's a live show in the hotel bar tonight.","오늘 밤 호텔 바에서 라이브 공연이 있습니다."),
"government": ("/ˈɡʌvərnmənt/","명사","정부","The government tourist office is downtown.","정부 관광 안내소는 시내에 있습니다."),
"experience": ("/ɪkˈspɪəriəns/","명사","경험","This tour was a great travel experience.","이 투어는 훌륭한 여행 경험이었습니다."),
"support": ("/səˈpɔːrt/","동사","지원하다","The hotel supports 24-hour guest services.","호텔은 24시간 고객 서비스를 지원합니다."),
"result": ("/rɪˈzʌlt/","명사","결과","The result was a memorable vacation.","결과는 기억에 남는 휴가였습니다."),
"program": ("/ˈproʊɡræm/","명사","프로그램","The hotel offers a loyalty points program.","호텔은 포인트 적립 프로그램을 운영합니다."),
"research": ("/ˈriːsɜːrtʃ/","동사","조사하다","I always research hotels before booking.","나는 예약 전에 항상 호텔을 조사합니다."),
"student": ("/ˈstjuːdənt/","명사","학생","Student discounts are available at the museum.","박물관에서 학생 할인이 적용됩니다."),
"general": ("/ˈdʒɛnərəl/","형용사","일반적인","What is the general check-out time?","일반적인 체크아웃 시간이 어떻게 되나요?"),
"level": ("/ˈlɛvəl/","명사","수준, 층","The pool is on level B1.","수영장은 지하 1층에 있습니다."),
"issue": ("/ˈɪʃuː/","명사","문제, 사안","I have an issue with my room.","객실에 문제가 있습니다."),
"interest": ("/ˈɪntrɪst/","명사","관심","Is there anything of interest nearby?","근처에 볼 만한 곳이 있나요?"),
"possible": ("/ˈpɒsɪbəl/","형용사","가능한","Is it possible to get a late checkout?","늦은 체크아웃이 가능한가요?"),
"social": ("/ˈsoʊʃəl/","형용사","사회적인","The hotel has a social lounge area.","호텔에는 소셜 라운지 공간이 있습니다."),
"create": ("/kriˈeɪt/","동사","만들다, 창조하다","The trip created unforgettable memories.","그 여행은 잊을 수 없는 추억을 만들었습니다."),

# ─── NGSL Level 3 words ───────────────────────────────────────────────────
"technology": ("/tɛkˈnɒlədʒi/","명사","기술","The hotel uses the latest technology for check-in.","호텔은 체크인에 최신 기술을 사용합니다."),
"mention": ("/ˈmɛnʃən/","동사","언급하다","Please mention any special requests at check-in.","체크인 시 특별 요청 사항을 언급해 주세요."),
"choice": ("/tʃɔɪs/","명사","선택","There's a wide choice of restaurants nearby.","근처에 다양한 식당이 있습니다."),
"save": ("/seɪv/","동사","저장하다, 아끼다","Book early to save on hotel rates.","호텔 요금을 아끼려면 일찍 예약하세요."),
"common": ("/ˈkɒmən/","형용사","흔한, 공통의","Jet lag is common after long flights.","긴 비행 후 시차 증후군은 흔합니다."),
"culture": ("/ˈkʌltʃər/","명사","문화","Exploring local culture is the best part of travel.","현지 문화를 탐방하는 것이 여행의 가장 좋은 부분입니다."),
"total": ("/ˈtoʊtəl/","명사","총계, 합계","What is the total for my stay?","숙박 총 금액이 얼마인가요?"),
"demand": ("/dɪˈmɑːnd/","명사","수요","Hotel demand is very high in peak season.","성수기에는 호텔 수요가 매우 높습니다."),
"situation": ("/ˌsɪtʃuˈeɪʃən/","명사","상황","What is the current situation with my flight?","내 항공편의 현재 상황이 어떻게 되나요?"),
"position": ("/pəˈzɪʃən/","명사","위치, 자리","The hotel is in a central position.","호텔은 중심부에 위치해 있습니다."),
"travel": ("/ˈtrævəl/","동사","여행하다","I love to travel to new places.","나는 새로운 곳으로 여행하는 것을 좋아합니다."),
"moment": ("/ˈmoʊmənt/","명사","순간","Can you give me a moment to check?","잠깐 확인할 시간을 주시겠어요?"),
"possible": ("/ˈpɒsɪbəl/","형용사","가능한","Is it possible to request a crib?","아기 침대를 요청하는 것이 가능한가요?"),
"understand": ("/ˌʌndərˈstænd/","동사","이해하다","I don't understand the timetable.","시간표를 이해하지 못하겠습니다."),
"consider": ("/kənˈsɪdər/","동사","고려하다","Please consider upgrading our room.","객실 업그레이드를 고려해 주세요."),
"expect": ("/ɪkˈspɛkt/","동사","기대하다, 예상하다","I expect the taxi to arrive soon.","택시가 곧 도착할 것으로 예상합니다."),
"continue": ("/kənˈtɪnjuː/","동사","계속하다","Continue straight for two blocks.","두 블록 직진하세요."),
"increase": ("/ɪnˈkriːs/","동사","증가하다","Hotel prices increase in the summer.","여름에는 호텔 가격이 오릅니다."),
"information": ("/ˌɪnfərˈmeɪʃən/","명사","정보","Where can I get tourist information?","관광 정보를 어디서 얻을 수 있나요?"),
"example": ("/ɪɡˈzɑːmpəl/","명사","예시","For example, you can use the bus or the metro.","예를 들어, 버스나 지하철을 이용할 수 있습니다."),
"company": ("/ˈkʌmpəni/","명사","회사","Which company operates this bus?","이 버스는 어느 회사가 운영하나요?"),
"business": ("/ˈbɪznɪs/","명사","사업, 비즈니스","I'm traveling for business.","출장으로 여행 중입니다."),
"market": ("/ˈmɑːrkɪt/","명사","시장","The night market is open until midnight.","야시장은 자정까지 열립니다."),
"system": ("/ˈsɪstəm/","명사","시스템, 체계","The transport system here is excellent.","여기의 교통 시스템은 훌륭합니다."),
"price": ("/praɪs/","명사","가격","What is the price for one night?","1박 가격이 얼마인가요?"),
"value": ("/ˈvæljuː/","명사","가치","This hotel offers great value for money.","이 호텔은 가격 대비 훌륭한 가치를 제공합니다."),
"environment": ("/ɪnˈvaɪrənmənt/","명사","환경","The hotel is committed to the environment.","호텔은 환경 보호에 힘쓰고 있습니다."),
"available": ("/əˈveɪləbəl/","형용사","이용 가능한","Is a single room available for tonight?","오늘 밤 싱글룸이 이용 가능한가요?"),
"require": ("/rɪˈkwaɪər/","동사","요구하다","This visa requires advance application.","이 비자는 사전 신청이 필요합니다."),
"suggest": ("/səˈdʒɛst/","동사","제안하다","Can you suggest a local restaurant?","현지 식당을 추천해 주시겠어요?"),
"access": ("/ˈæksɛs/","명사","접근, 이용","The hotel provides access to a private beach.","호텔은 전용 해변 이용을 제공합니다."),
"apply": ("/əˈplaɪ/","동사","적용하다, 신청하다","The discount does not apply to existing bookings.","할인은 기존 예약에는 적용되지 않습니다."),
"lead": ("/liːd/","동사","이끌다","This path leads to the viewpoint.","이 길은 전망대로 이어집니다."),
"major": ("/ˈmeɪdʒər/","형용사","주요한","All major credit cards are accepted.","모든 주요 신용카드가 허용됩니다."),
"feature": ("/ˈfiːtʃər/","명사","특징, 기능","What are the hotel's best features?","호텔의 가장 좋은 특징은 무엇인가요?"),
"term": ("/tɜːrm/","명사","조건, 기간","Please read the terms and conditions.","약관을 읽어보세요."),
"account": ("/əˈkaʊnt/","명사","계좌, 계정","Please charge it to my account.","내 계정으로 청구해 주세요."),
"confirm": ("/kənˈfɜːrm/","동사","확인하다","I need to confirm my reservation.","예약을 확인해야 합니다."),
"current": ("/ˈkɜːrənt/","형용사","현재의","What is the current exchange rate?","현재 환율이 얼마인가요?"),
"significant": ("/sɪɡˈnɪfɪkənt/","형용사","중요한, 상당한","There was a significant delay due to weather.","날씨로 인해 상당한 지연이 있었습니다."),
"specific": ("/spɪˈsɪfɪk/","형용사","구체적인","Do you have a specific room preference?","특정 선호하는 방이 있으신가요?"),
"approach": ("/əˈproʊtʃ/","동사","접근하다","The taxi is approaching the terminal.","택시가 터미널에 접근 중입니다."),
"method": ("/ˈmɛθəd/","명사","방법","What payment method do you accept?","어떤 결제 방법을 받으시나요?"),
"standard": ("/ˈstændərd/","명사","기준, 표준","This hotel meets international standards.","이 호텔은 국제 기준을 충족합니다."),
"quality": ("/ˈkwɒlɪti/","명사","품질","The quality of service is excellent here.","이곳의 서비스 품질이 훌륭합니다."),
"fund": ("/fʌnd/","명사","자금","I need to add funds to my travel card.","여행 카드에 충전이 필요합니다."),
"rate": ("/reɪt/","명사","요금, 비율","What is the nightly rate?","1박 요금이 얼마인가요?"),
"various": ("/ˈvɛəriəs/","형용사","다양한","The hotel offers various amenities.","호텔은 다양한 편의시설을 제공합니다."),
"effort": ("/ˈɛfərt/","명사","노력","Thank you for your effort in arranging this.","이것을 준비하기 위한 노력에 감사드립니다."),
"professional": ("/prəˈfɛʃənəl/","형용사","전문적인","The staff is very professional.","직원들이 매우 전문적입니다."),

# ─── TOEIC/Business specific words ────────────────────────────────────────
"mister": ("/ˈmɪstər/","명사","~씨, 선생님","Mister Kim will meet you in the lobby.","김 씨가 로비에서 당신을 만날 것입니다."),
"vacation": ("/veɪˈkeɪʃən/","명사","휴가","I'm planning a two-week vacation in Europe.","유럽으로 2주 휴가를 계획 중입니다."),
"client": ("/ˈklaɪənt/","명사","고객, 의뢰인","We need to prepare the conference room for the client.","고객을 위해 회의실을 준비해야 합니다."),
"e-book": ("/ˈiː bʊk/","명사","전자책","The airline offers e-books for download.","항공사가 다운로드용 전자책을 제공합니다."),
"airport": ("/ˈɛərpɔːrt/","명사","공항","Please be at the airport two hours early.","두 시간 일찍 공항에 도착해 주세요."),
"memo": ("/ˈmɛmoʊ/","명사","메모, 사내 문서","Send a memo to all staff about the schedule change.","일정 변경에 관한 메모를 모든 직원에게 보내세요."),
"reservation": ("/ˌrɛzərˈveɪʃən/","명사","예약","I have a reservation under the name Kim.","김 씨 이름으로 예약했습니다."),
"logical": ("/ˈlɒdʒɪkəl/","형용사","논리적인","That is a logical approach to solving the problem.","그것은 문제를 해결하는 논리적인 접근법입니다."),
"fax": ("/fæks/","명사","팩스","Please send the contract by fax.","계약서를 팩스로 보내주세요."),
"sincerely": ("/sɪnˈsɪərli/","부사","진심으로","Sincerely yours, the management team.","진심을 담아, 경영진 드림."),
"sometime": ("/ˈsʌmtaɪm/","부사","언젠가","Let's meet sometime next week.","다음 주 언젠가 만납시다."),
"supervisor": ("/ˈsuːpərˌvaɪzər/","명사","감독관, 상사","Please contact your supervisor if there are issues.","문제가 있으면 상사에게 연락하세요."),
"refund": ("/ˈriːfʌnd/","명사","환불","I would like to request a refund for the unused nights.","사용하지 않은 날에 대해 환불을 요청하고 싶습니다."),
"goods": ("/ɡʊdz/","명사","상품, 물품","All goods must be declared at customs.","모든 물품은 세관에서 신고해야 합니다."),
"seldom": ("/ˈsɛldəm/","부사","좀처럼 ~않는","I seldom travel without travel insurance.","나는 여행 보험 없이는 좀처럼 여행하지 않는다."),
"signature": ("/ˈsɪɡnɪtʃər/","명사","서명","Please provide your signature here.","여기에 서명해 주세요."),
"worldwide": ("/ˌwɜːrldˈwaɪd/","부사","전 세계적으로","This hotel chain operates worldwide.","이 호텔 체인은 전 세계적으로 운영됩니다."),
"carrier": ("/ˈkæriər/","명사","항공사, 운송업체","Which carrier are you flying with?","어느 항공사를 이용하시나요?"),
"designate": ("/ˈdɛzɪɡneɪt/","동사","지정하다","Please use the designated smoking area.","지정된 흡연 구역을 이용해 주세요."),
"exclusive": ("/ɪkˈskluːsɪv/","형용사","독점적인, 전용의","This is an exclusive offer for hotel guests.","이것은 호텔 투숙객을 위한 전용 혜택입니다."),
"overhead": ("/ˈoʊvərˌhɛd/","형용사","머리 위의","Place your bag in the overhead compartment.","짐을 머리 위 수납공간에 넣어 주세요."),
"advisory": ("/ədˈvaɪzəri/","명사","권고, 조언","There is a travel advisory for that region.","그 지역에 대한 여행 경보가 있습니다."),
"authentic": ("/ɔːˈθɛntɪk/","형용사","진품의, 정통의","This restaurant serves authentic local cuisine.","이 식당은 정통 현지 요리를 제공합니다."),
"bakery": ("/ˈbeɪkəri/","명사","빵집","The hotel has a bakery on the ground floor.","호텔 1층에 빵집이 있습니다."),
"compartment": ("/kəmˈpɑːrtmənt/","명사","칸, 구획","The overhead compartment is full.","머리 위 짐칸이 꽉 찼습니다."),
"prestigious": ("/prɛˈstɪdʒəs/","형용사","명성 있는","This is a prestigious five-star hotel.","이것은 명성 높은 5성급 호텔입니다."),
"reassure": ("/ˌriːəˈʃʊər/","동사","안심시키다","The manager reassured us that our room would be ready.","매니저가 방이 준비될 것이라고 우리를 안심시켰습니다."),

# ─── Business English (BSL) words ─────────────────────────────────────────
"equity": ("/ˈɛkwɪti/","명사","자본, 주식","The company sold equity to raise funds.","회사는 자금 조달을 위해 주식을 매각했습니다."),
"dividend": ("/ˈdɪvɪdɛnd/","명사","배당금","Shareholders received a quarterly dividend.","주주들은 분기별 배당금을 받았습니다."),
"portfolio": ("/pɔːrtˈfoʊlioʊ/","명사","포트폴리오","Diversify your investment portfolio.","투자 포트폴리오를 다양화하세요."),
"sponsorship": ("/ˈspɒnsərʃɪp/","명사","후원","The event received corporate sponsorship.","행사는 기업 후원을 받았습니다."),
"inventory": ("/ˈɪnvəntɔːri/","명사","재고","We need to update the inventory monthly.","월별로 재고를 업데이트해야 합니다."),
"transaction": ("/trænˈzækʃən/","명사","거래","All transactions are encrypted for security.","모든 거래는 보안을 위해 암호화됩니다."),
"lease": ("/liːs/","명사","임대 계약","The office lease expires next year.","사무실 임대 계약이 내년에 만료됩니다."),
"hedge": ("/hɛdʒ/","동사","위험을 방어하다","Companies hedge against currency risk.","기업들은 통화 위험에 대비해 헤지를 합니다."),
"premium": ("/ˈpriːmiəm/","명사","프리미엄, 보험료","Members receive premium customer service.","회원은 프리미엄 고객 서비스를 받습니다."),
"distribution": ("/ˌdɪstrɪˈbjuːʃən/","명사","유통, 분배","The distribution network covers all regions.","유통망이 모든 지역을 포괄합니다."),
"privatization": ("/ˌpraɪvɪtɪˈzeɪʃən/","명사","민영화","The privatization of the airline was controversial.","항공사 민영화는 논란이 많았습니다."),
"tactic": ("/ˈtæktɪk/","명사","전술, 전략","The sales team developed new marketing tactics.","영업팀은 새로운 마케팅 전술을 개발했습니다."),
"invoice": ("/ˈɪnvɔɪs/","명사","청구서, 송장","Please send the invoice to accounting.","회계부에 청구서를 보내주세요."),
"remedy": ("/ˈrɛmədi/","명사","해결책, 치료법","We need to find a remedy for this issue.","이 문제에 대한 해결책을 찾아야 합니다."),
"innovative": ("/ˈɪnəˌveɪtɪv/","형용사","혁신적인","The company is known for its innovative products.","그 회사는 혁신적인 제품으로 유명합니다."),

# ─── Academic English (NAWL) words ────────────────────────────────────────
"repertoire": ("/ˈrɛpətwɑːr/","명사","레퍼토리, 목록","The musician has an extensive repertoire.","그 음악가는 방대한 레퍼토리를 가지고 있다."),
"obtain": ("/əbˈteɪn/","동사","획득하다, 얻다","Researchers need to obtain data from multiple sources.","연구자들은 여러 출처에서 데이터를 획득해야 합니다."),
"parameter": ("/pəˈræmɪtər/","명사","매개변수, 기준","The researchers defined the key parameters of the study.","연구자들은 연구의 핵심 매개변수를 정의했습니다."),
"aspect": ("/ˈæspɛkt/","명사","측면, 양상","This study examines all aspects of the phenomenon.","이 연구는 현상의 모든 측면을 검토합니다."),
"dynamic": ("/daɪˈnæmɪk/","형용사","역동적인, 동적인","The dynamic relationship between variables was studied.","변수들 간의 역동적인 관계가 연구되었습니다."),
"domain": ("/doʊˈmeɪn/","명사","영역, 분야","This question falls within the domain of linguistics.","이 질문은 언어학의 영역에 속합니다."),
"publish": ("/ˈpʌblɪʃ/","동사","출판하다, 발표하다","The results were published in a peer-reviewed journal.","결과는 동료 심사 저널에 발표되었습니다."),
"authority": ("/ɔːˈθɒrɪti/","명사","권한, 당국","The research was approved by the relevant authority.","연구는 관련 당국의 승인을 받았습니다."),
"semantic": ("/sɪˈmæntɪk/","형용사","의미론적인","The semantic analysis revealed interesting patterns.","의미론적 분석은 흥미로운 패턴을 드러냈습니다."),
"matrix": ("/ˈmeɪtrɪks/","명사","행렬, 기질","The data was arranged in a correlation matrix.","데이터는 상관 행렬로 배열되었습니다."),
"periodic": ("/ˌpɪəriˈɒdɪk/","형용사","주기적인","Periodic assessments were conducted throughout the study.","연구 내내 주기적인 평가가 실시되었습니다."),
"archaeology": ("/ˌɑːrkiˈɒlədʒi/","명사","고고학","Archaeology provides insights into ancient cultures.","고고학은 고대 문화에 대한 통찰을 제공합니다."),
"atom": ("/ˈætəm/","명사","원자","Atoms are the basic building blocks of matter.","원자는 물질의 기본 구성 요소입니다."),
"modification": ("/ˌmɒdɪfɪˈkeɪʃən/","명사","수정, 변형","A minor modification was made to the experimental design.","실험 설계에 사소한 수정이 이루어졌습니다."),
"partition": ("/pɑːrˈtɪʃən/","명사","분할, 구분","The data was analyzed after partition into subgroups.","데이터는 소그룹으로 분할한 후 분석되었습니다."),
"initiate": ("/ɪˈnɪʃieɪt/","동사","시작하다, 개시하다","The research team initiated the experiment in January.","연구���은 1월에 실험을 시작했습니다."),
"meaningful": ("/ˈmiːnɪŋfəl/","형용사","의미 있는, 유의미한","The study yielded meaningful results.","그 연구는 유의미한 결과를 산출했습니다."),
"wavelength": ("/ˈweɪvlɛŋθ/","명사","파장","Light of different wavelengths has different colors.","다양한 파장의 빛은 서로 다른 색을 가집니다."),
"diagnose": ("/ˈdaɪəɡnoʊz/","동사","진단하다","The condition was difficult to diagnose accurately.","그 상태는 정확하게 진단하기 어려웠습니다."),
"accent": ("/ˈæksɛnt/","명사","억양, 강조","The speaker had a distinct regional accent.","그 화자는 뚜렷한 지역 억양을 가지고 있었습니다."),
"realm": ("/rɛlm/","명사","영역, 분야","This discovery opened a new realm of research.","이 발견은 새로운 연구 영역을 열었습니다."),
"replication": ("/ˌrɛplɪˈkeɪʃən/","명사","복제, 반복 실험","Replication of the study confirmed the findings.","연구 반복 실험이 결과를 확인했습니다."),

# ─── Advanced NGSL words ───────────────────────────────────────────────────
"advance": ("/ədˈvɑːns/","동사","진행하다, 전진하다","Book in advance to secure the best rates.","최상의 요금을 확보하려면 미리 예약하세요."),
"fill": ("/fɪl/","동사","채우다","Please fill in the registration form.","등록 양식을 작성해 주세요."),
"star": ("/stɑːr/","명사","별, 스타","This is a five-star hotel.","이것은 5성급 호텔입니다."),
"network": ("/ˈnɛtwɜːrk/","명사","네트워크, 망","The hotel is part of a global network.","호텔은 글로벌 네트워크의 일부입니다."),
"generally": ("/ˈdʒɛnərəli/","부사","일반적으로","Hotels generally charge for late checkout.","호텔은 일반적으로 늦은 체크아웃에 비용을 청구합니다."),
"operation": ("/ˌɒpəˈreɪʃən/","명사","운영, 작동","The hotel's operation is 24/7.","호텔의 운영은 24시간 연중무휴입니다."),
"match": ("/mætʃ/","동사","일치하다","The room doesn't match the description online.","방이 온라인 설명과 일치하지 않습니다."),
"avoid": ("/əˈvɔɪd/","동사","피하다","Avoid rush hour to save time.","시간을 절약하려면 러시아워를 피하세요."),
"percentage": ("/pərˈsɛntɪdʒ/","명사","퍼센트, 비율","A percentage of the rate goes to charity.","요금의 일부가 자선단체에 기부됩니다."),
"peace": ("/piːs/","명사","평화, 평온","The resort offers peace and quiet.","리조트는 평화와 고요함을 제공합니다."),
"status": ("/ˈsteɪtəs/","명사","상태, 지위","What is the status of my booking?","예약 상태가 어떻게 되나요?"),
"crime": ("/kraɪm/","명사","범죄","Report any crime to the local police.","모든 범죄는 현지 경찰에 신고하세요."),
"decline": ("/dɪˈklaɪn/","동사","거절하다, 감소하다","I declined the offer to upgrade.","업그레이드 제안을 거절했습니다."),
"decade": ("/ˈdɛkeɪd/","명사","10년","This hotel has been operating for over a decade.","이 호텔은 10년 이상 운영되어 왔습니다."),
"launch": ("/lɔːntʃ/","동사","출시하다, 시작하다","The airline launched a new route to Seoul.","항공사가 서울로 가는 새 노선을 출시했습니다."),
"warn": ("/wɔːrn/","동사","경고하다","The guide warned us about pickpockets.","가이드가 소매치기에 대해 경고했습니다."),
"oppose": ("/əˈpoʊz/","동사","반대하다","Some residents oppose the new hotel development.","일부 주민들은 새 호텔 개발에 반대합니다."),
"branch": ("/brɑːntʃ/","명사","지점, 지부","The hotel has branches in 30 countries.","호텔은 30개국에 지점이 있습니다."),
"vehicle": ("/ˈviːɪkəl/","명사","차량","No vehicles are allowed in the pedestrian zone.","보행자 구역에는 차량이 허용되지 않습니다."),
"scientist": ("/ˈsaɪəntɪst/","명사","과학자","The scientist attended an international conference.","그 과학자는 국제 회의에 참석했습니다."),
"route": ("/ruːt/","명사","노선, 경로","Take this route to avoid traffic.","교통 체증을 피하려면 이 경로를 이용하세요."),
"bind": ("/baɪnd/","동사","묶다, 구속하다","The contract binds both parties for one year.","계약은 양 당사자를 1년 동안 구속합니다."),
"belong": ("/bɪˈlɒŋ/","동사","속하다, 소속되다","Does this luggage belong to you?","이 짐이 당신 것인가요?"),
"taste": ("/teɪst/","동사","맛보다","I love tasting local dishes when I travel.","여행할 때 현지 음식을 맛보는 것을 좋아합니다."),
"reduction": ("/rɪˈdʌkʃən/","명사","감소, 할인","Ask about early booking reduction rates.","조기 예약 할인 요금에 대해 물어보세요."),
"reserve": ("/rɪˈzɜːrv/","동사","예약하다, 보유하다","I'd like to reserve a table for dinner.","저녁 식사를 위해 테이블을 예약하고 싶습니다."),
"complaint": ("/kəmˈpleɪnt/","명사","불만, 불평","Please submit your complaint in writing.","불만 사항을 서면으로 제출해 주세요."),
"bore": ("/bɔːr/","동사","지루하게 하다","Long layovers can bore even experienced travelers.","긴 경유 시간은 경험 많은 여행자도 지루하게 만들 수 있습니다."),
"mission": ("/ˈmɪʃən/","명사","임무, 사명","Our mission is to provide excellent service.","우리의 사명은 탁월한 서비스를 제공하는 것입니다."),
"somehow": ("/ˈsʌmhaʊ/","부사","어떻게든","We somehow managed to catch the last train.","어떻게든 마지막 기차를 탔습니다."),
"tone": ("/toʊn/","명사","어조, 분위기","The hotel has a sophisticated tone throughout.","호텔 전체에 세련된 분위기가 흐릅니다."),
"neighborhood": ("/ˈneɪbərhʊd/","명사","동네, 인근","The hotel is in a safe neighborhood.","호텔은 안전한 동네에 있습니다."),
}

# ---------------------------------------------------------------------------
# Suffix-based fallback for words not in DICT
# ---------------------------------------------------------------------------
POS_SUFFIX = [
    (("tion","sion","ment","ness","ity","ance","ence","ure","age","dom",
       "ship","ism","ist","ery","ory","al","ure","th","ty"), "명사"),
    (("ate","ize","ise","ify","en","fy"), "동사"),
    (("ous","ive","ful","less","able","ible","ical","ic","ent","ant",
       "ary","al","ory","ive"), "형용사"),
    (("ly",), "부사"),
]

EXAMPLE_TEMPLATES = {
    "명사": [
        ("The {w} plays an important role in this context.",
         "{w}이(가) 이 맥락에서 중요한 역할을 합니다."),
        ("We need to analyze the {w} carefully.",
         "우리는 {w}을(를) 신중하게 분석해야 합니다."),
        ("The study focused on {w} as a key variable.",
         "연구는 핵심 변수로서 {w}에 초점을 맞췄습니다."),
    ],
    "동사": [
        ("We need to {w} this before the deadline.",
         "마감 전에 이것을 {w}해야 합니다."),
        ("The team decided to {w} the approach.",
         "팀은 접근 방식을 {w}하기로 결정했습니다."),
        ("It is important to {w} the data accurately.",
         "데이터를 정확하게 {w}하는 것이 중요합니다."),
    ],
    "형용사": [
        ("This is a {w} aspect of the research.",
         "이것은 연구의 {w}한 측면입니다."),
        ("The results were {w}.",
         "결과는 {w}했습니다."),
    ],
    "부사": [
        ("The process works {w} in most cases.",
         "이 과정은 대부분의 경우 {w}하게 작동합니다."),
    ],
}


def guess_pos(word):
    w = word.lower()
    for suffixes, pos in POS_SUFFIX:
        if w.endswith(suffixes):
            return pos
    return "명사"


def make_fallback(word):
    pos = guess_pos(word)
    templates = EXAMPLE_TEMPLATES.get(pos, EXAMPLE_TEMPLATES["명사"])
    h = int(hashlib.md5(word.encode()).hexdigest(), 16)
    ex_en, ex_ko = templates[h % len(templates)]
    ex_en = ex_en.replace("{w}", word)
    ex_ko = ex_ko.replace("{w}", word)
    return (f"/{word}/", pos, word, ex_en, ex_ko)


# ---------------------------------------------------------------------------
# Fill logic
# ---------------------------------------------------------------------------
def fill_file(filepath):
    with open(filepath, encoding="utf-8") as f:
        entries = json.load(f)

    filled = 0
    fallback = 0
    for entry in entries:
        if entry.get("meaning"):
            filled += 1
            continue
        key = entry["word"].lower()
        if key in DICT:
            pron, pos, meaning, ex_en, ex_ko = DICT[key]
            entry["pronunciation"] = pron
            entry["partOfSpeech"] = pos
            entry["meaning"] = meaning
            entry["exampleEn"] = ex_en
            entry["exampleKo"] = ex_ko
            filled += 1
        else:
            pron, pos, meaning, ex_en, ex_ko = make_fallback(entry["word"])
            entry["pronunciation"] = pron
            entry["partOfSpeech"] = pos
            entry["meaning"] = meaning
            entry["exampleEn"] = ex_en
            entry["exampleKo"] = ex_ko
            fallback += 1

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    total = len(entries)
    pct = 100 * filled / total if total else 0
    tag = "✓" if fallback == 0 else f"△({fallback} fallback)"
    print(f"  {tag} {os.path.relpath(filepath, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))}: "
          f"{filled}/{total} dict ({pct:.0f}%)")
    return fallback


def main():
    print("=== Fill Source-List Wordbook Data ===\n")
    total_fallback = 0

    WORDBOOKS = [
        ("frequency-english", [f"level-{i}" for i in range(1, 11)]),
        ("toeic-essential",   [f"level-{i}" for i in range(1, 6)]),
        ("business-english",  [f"level-{i}" for i in range(1, 7)]),
        ("academic-english",  [f"level-{i}" for i in range(1, 5)]),
    ]

    for wb_id, levels in WORDBOOKS:
        print(f"[{wb_id}]")
        for lv in levels:
            fp = os.path.join(DATA, wb_id, f"words-{lv}.json")
            total_fallback += fill_file(fp)
        print()

    print(f"=== Done. Total fallback entries: {total_fallback} ===")


if __name__ == "__main__":
    main()
