#!/usr/bin/env python3
"""Patch fallback entries: business-L6 (216)"""
import json, glob

DICT18 = {
    "laser": ("/ˈleɪzər/", "명사", "레이저", "Laser-focused strategy worked.", "레이저처럼 집중된 전략이 통했다."),
    "smuggle": ("/ˈsmʌɡəl/", "동사", "밀수하다", "Goods were smuggled across borders.", "물품이 국경을 통해 밀수됐다."),
    "loop": ("/luːp/", "명사", "루프, 순환", "A feedback loop formed.", "피드백 루프가 형성됐다."),
    "proclaim": ("/prəˈkleɪm/", "동사", "선언하다, 공포하다", "A new policy was proclaimed.", "새 정책이 선언됐다."),
    "audio": ("/ˈɔːdɪoʊ/", "명사", "오디오, 음성", "Audio streaming revenue grew.", "오디오 스트리밍 수익이 증가했다."),
    "commence": ("/kəˈmens/", "동사", "시작하다", "Trading commenced at 9am.", "거래가 오전 9시에 시작됐다."),
    "skeptic": ("/ˈskeptɪk/", "명사", "회의론자", "Market skeptics were proven wrong.", "시장 회의론자들이 틀렸음이 증명됐다."),
    "bounce": ("/baʊns/", "동사", "반등하다", "Stocks bounced from lows.", "주가가 저점에서 반등했다."),
    "reformer": ("/rɪˈfɔːrmər/", "명사", "개혁가", "Economic reformers led change.", "경제 개혁가들이 변화를 이끌었다."),
    "endorsement": ("/ɪnˈdɔːrsmənt/", "명사", "지지, 배서", "A regulatory endorsement was given.", "규제 당국의 지지가 주어졌다."),
    "unwilling": ("/ʌnˈwɪlɪŋ/", "형용사", "꺼리는, 마지못한", "Investors were unwilling to sell.", "투자자들이 팔기를 꺼렸다."),
    "cheaply": ("/ˈtʃiːpli/", "부사", "저렴하게", "Capital was raised cheaply.", "자본이 저렴하게 조달됐다."),
    "enrich": ("/ɪnˈrɪtʃ/", "동사", "풍요롭게 하다", "Trade enriched both nations.", "무역이 양국을 풍요롭게 했다."),
    "prop": ("/prɒp/", "동사", "지지하다, 떠받치다", "The government propped up the bank.", "정부가 은행을 떠받쳤다."),
    "depositor": ("/dɪˈpɒzɪtər/", "명사", "예금자", "Depositors withdrew funds.", "예금자들이 자금을 인출했다."),
    "clout": ("/klaʊt/", "명사", "영향력", "Political clout was leveraged.", "정치적 영향력이 활용됐다."),
    "thumb": ("/θʌm/", "명사", "엄지손가락", "Rule of thumb estimates were used.", "경험 법칙 추정이 사용됐다."),
    "decree": ("/dɪˈkriː/", "명사", "포고령, 명령", "A presidential decree was issued.", "대통령 포고령이 발령됐다."),
    "collectively": ("/kəˈlektɪvli/", "부사", "집단적으로", "Banks acted collectively.", "은행들이 집단적으로 행동했다."),
    "conspiracy": ("/kənˈspɪrəsi/", "명사", "음모, 담합", "A price-fixing conspiracy emerged.", "가격 담합 음모가 드러났다."),
    "dioxide": ("/daɪˈɒksaɪd/", "명사", "이산화물", "Carbon dioxide emissions fell.", "이산화탄소 배출이 줄었다."),
    "enhancement": ("/ɪnˈhɑːnsmənt/", "명사", "강화, 개선", "Credit enhancement was used.", "신용 보강이 사용됐다."),
    "decentralize": ("/diːˈsentrəlaɪz/", "동사", "분권화하다", "Operations were decentralized.", "운영이 분권화됐다."),
    "explode": ("/ɪkˈsploʊd/", "동사", "폭발적으로 증가하다", "Demand exploded.", "수요가 폭발적으로 증가했다."),
    "pensioner": ("/ˈpenʃənər/", "명사", "연금 수령자", "Pensioners faced lower returns.", "연금 수령자들이 낮은 수익에 직면했다."),
    "unauthorize": ("/ʌnˈɔːθəraɪz/", "동사", "허가를 취소하다", "Transactions were unauthorized.", "거래가 허가되지 않았다."),
    "pin": ("/pɪn/", "동사", "고정하다", "Exchange rates were pinned.", "환율이 고정됐다."),
    "aluminum": ("/əˈluːmɪnəm/", "명사", "알루미늄", "Aluminum prices surged.", "알루미늄 가격이 급등했다."),
    "presume": ("/prɪˈzjuːm/", "동사", "추정하다, 가정하다", "It is presumed solvent.", "지급 능력이 있다고 추정된다."),
    "prudent": ("/ˈpruːdənt/", "형용사", "신중한", "Prudent risk management is essential.", "신중한 위험 관리가 필수적이다."),
    "census": ("/ˈsensəs/", "명사", "인구 조사", "Census data informed planning.", "인구 조사 데이터가 계획에 활용됐다."),
    "vow": ("/vaʊ/", "동사", "맹세하다", "The CEO vowed to cut costs.", "CEO가 비용 절감을 맹세했다."),
    "ineffective": ("/ˌɪnɪˈfektɪv/", "형용사", "효과 없는", "The policy proved ineffective.", "정책이 효과 없는 것으로 드러났다."),
    "adequately": ("/ˈædɪkwɪtli/", "부사", "충분히, 적절히", "Risks were not adequately disclosed.", "위험이 충분히 공개되지 않았다."),
    "prosper": ("/ˈprɒspər/", "동사", "번창하다", "The firm prospered.", "회사가 번창했다."),
    "testimony": ("/ˈtestɪmoʊni/", "명사", "증언", "Expert testimony was given.", "전문가 증언이 제공됐다."),
    "manipulation": ("/məˌnɪpjʊˈleɪʃən/", "명사", "조작", "Market manipulation was detected.", "시장 조작이 탐지됐다."),
    "cooperative": ("/koʊˈɒpərətɪv/", "명사", "협동조합", "A worker cooperative was formed.", "노동자 협동조합이 구성됐다."),
    "rigid": ("/ˈrɪdʒɪd/", "형용사", "경직된", "Rigid rules slowed growth.", "경직된 규정이 성장을 늦췄다."),
    "tenure": ("/ˈtenjər/", "명사", "재임 기간", "During his tenure profits grew.", "그의 재임 기간에 수익이 증가했다."),
    "milestone": ("/ˈmaɪlstoʊn/", "명사", "이정표, 중요 시점", "A revenue milestone was reached.", "수익 이정표에 도달했다."),
    "optimum": ("/ˈɒptɪməm/", "명사", "최적", "The optimum price was found.", "최적 가격이 발견됐다."),
    "subsection": ("/ˈsʌbˌsekʃən/", "명사", "소절, 하위 항목", "Subsection 3 applies here.", "제3항이 여기에 적용된다."),
    "formulation": ("/ˌfɔːrmjʊˈleɪʃən/", "명사", "수립, 공식화", "Policy formulation takes time.", "정책 수립에는 시간이 걸린다."),
    "exert": ("/ɪɡˈzɜːrt/", "동사", "가하다, 발휘하다", "Pressure was exerted on prices.", "압력이 가격에 가해졌다."),
    "expectancy": ("/ɪkˈspektənsi/", "명사", "기대, 예상", "Life expectancy rose.", "기대 수명이 올랐다."),
    "syndicate": ("/ˈsɪndɪkɪt/", "명사", "신디케이트, 연합", "A bank syndicate funded the deal.", "은행 신디케이트가 거래에 자금을 지원했다."),
    "unfavorable": ("/ʌnˈfeɪvərəbəl/", "형용사", "불리한", "Unfavorable conditions persist.", "불리한 조건이 지속된다."),
    "proprietorship": ("/prəˈpraɪətərʃɪp/", "명사", "개인 사업체", "A sole proprietorship was set up.", "개인 사업체가 설립됐다."),
    "franc": ("/fræŋk/", "명사", "프랑 (화폐)", "The Swiss franc rose.", "스위스 프랑이 상승했다."),
    "policyholder": ("/ˈpɒlɪsiˌhoʊldər/", "명사", "보험 계약자", "Policyholders received payouts.", "보험 계약자들이 지급을 받았다."),
    "sustainability": ("/səˌsteɪnəˈbɪlɪti/", "명사", "지속 가능성", "Sustainability goals were set.", "지속 가능성 목표가 설정됐다."),
    "supervisory": ("/ˌsuːpərˈvaɪzəri/", "형용사", "감독의", "A supervisory board was formed.", "감독 이사회가 구성됐다."),
    "sheer": ("/ʃɪər/", "형용사", "순전한, 엄청난", "The sheer scale impressed all.", "엄청난 규모가 모두를 놀라게 했다."),
    "electorate": ("/ɪˈlektərɪt/", "명사", "유권자", "The electorate rejected the plan.", "유권자들이 계획을 거부했다."),
    "realization": ("/ˌriːəlaɪˈzeɪʃən/", "명사", "실현, 인식", "Profit realization was recorded.", "수익 실현이 기록됐다."),
    "neo": ("/ˈniːoʊ/", "접두사", "신~, 새로운", "Neo-liberal policies dominated.", "신자유주의 정책이 지배했다."),
    "reinvestment": ("/ˌriːɪnˈvestmənt/", "명사", "재투자", "Dividend reinvestment grew.", "배당금 재투자가 증가했다."),
    "scratch": ("/skrætʃ/", "명사", "출발점, 처음부터", "Built from scratch.", "처음부터 구축됐다."),
    "dissent": ("/dɪˈsent/", "명사", "반대, 이견", "Board dissent was recorded.", "이사회 이견이 기록됐다."),
    "pit": ("/pɪt/", "명사", "거래 현장, 구덩이", "Traders shouted in the pit.", "트레이더들이 거래 현장에서 소리쳤다."),
    "intrigue": ("/ˈɪntriːɡ/", "명사", "음모, 흥미를 자아냄", "Corporate intrigue unfolded.", "기업 음모가 전개됐다."),
    "patch": ("/pætʃ/", "명사", "단기간, 수정", "A rough patch was endured.", "힘든 시기를 견뎌냈다."),
    "brave": ("/breɪv/", "형용사", "용감한", "A brave investment decision was made.", "용감한 투자 결정이 이루어졌다."),
    "pending": ("/ˈpendɪŋ/", "형용사", "계류 중인", "The merger is pending approval.", "합병이 승인을 기다리고 있다."),
    "scatter": ("/ˈskætər/", "동사", "분산시키다", "Investments were scattered.", "투자가 분산됐다."),
    "annum": ("/ˈænəm/", "명사", "연(年)", "5% per annum interest rate.", "연 5% 이자율."),
    "mar": ("/mɑːr/", "동사", "손상시키다", "Losses marred the report.", "손실이 보고서를 손상시켰다."),
    "restrain": ("/rɪˈstreɪn/", "동사", "억제하다, 제한하다", "Spending was restrained.", "지출이 억제됐다."),
    "configuration": ("/kənˌfɪɡjʊˈreɪʃən/", "명사", "구성, 형태", "A new system configuration.", "새로운 시스템 구성."),
    "reportedly": ("/rɪˈpɔːrtɪdli/", "부사", "보도에 따르면", "Reportedly, the firm is for sale.", "보도에 따르면, 회사가 매각 중이다."),
    "negotiator": ("/nɪˈɡoʊʃɪeɪtər/", "명사", "협상가", "A skilled negotiator was hired.", "숙련된 협상가가 고용됐다."),
    "offensive": ("/əˈfensɪv/", "명사", "공세", "A sales offensive was launched.", "영업 공세가 시작됐다."),
    "rape": ("/reɪp/", "명사", "유채꽃, 착취", "Rapeseed oil exports grew.", "유채유 수출이 증가했다."),
    "embody": ("/ɪmˈbɒdi/", "동사", "구현하다", "The plan embodies reform.", "계획이 개혁을 구현한다."),
    "deployment": ("/dɪˈplɔɪmənt/", "명사", "배치, 배포", "Capital deployment accelerated.", "자본 배치가 가속됐다."),
    "detection": ("/dɪˈtekʃən/", "명사", "탐지, 발견", "Fraud detection improved.", "사기 탐지가 향상됐다."),
    "bullet": ("/ˈbʊlɪt/", "명사", "총알, 일시 상환", "A bullet loan was issued.", "일시 상환 대출이 발행됐다."),
    "intelligent": ("/ɪnˈtelɪdʒənt/", "형용사", "지능적인", "Intelligent systems cut costs.", "지능형 시스템이 비용을 절감했다."),
    "conservation": ("/ˌkɒnsəˈveɪʃən/", "명사", "보존, 절약", "Energy conservation saved costs.", "에너지 절약이 비용을 줄였다."),
    "slim": ("/slɪm/", "형용사", "날씬한, 희박한", "Profit margins are slim.", "수익 마진이 희박하다."),
    "synergy": ("/ˈsɪnədʒi/", "명사", "시너지", "Synergies from the merger.", "합병의 시너지 효과."),
    "beam": ("/biːm/", "명사", "광선, 빔", "A laser beam was used.", "레이저 빔이 사용됐다."),
    "disguise": ("/dɪsˈɡaɪz/", "동사", "위장하다", "Losses were disguised as gains.", "손실이 이익으로 위장됐다."),
    "selective": ("/sɪˈlektɪv/", "형용사", "선택적인", "Selective disclosure occurred.", "선택적 공시가 이루어졌다."),
    "assertion": ("/əˈsɜːrʃən/", "명사", "주장, 확언", "Bold assertions were made.", "대담한 주장이 제기됐다."),
    "dictatorship": ("/dɪkˈteɪtərʃɪp/", "명사", "독재", "Economic dictatorship was imposed.", "경제 독재가 부과됐다."),
    "fraudulent": ("/ˈfrɔːdjʊlənt/", "형용사", "사기의, 부정직한", "Fraudulent activity was detected.", "사기 행위가 탐지됐다."),
    "constituent": ("/kənˈstɪtʃuənt/", "명사", "구성 요소, 유권자", "Index constituents were reviewed.", "지수 구성 요소가 검토됐다."),
    "fiduciary": ("/fɪˈdjuːʃɪɛri/", "명사", "수탁자, 신임 의무를 지닌", "Fiduciary duties were upheld.", "수탁 의무가 이행됐다."),
    "speculate": ("/ˈspekjʊleɪt/", "동사", "투기하다, 추측하다", "Traders speculated on oil.", "트레이더들이 석유에 투기했다."),
    "citizenship": ("/ˈsɪtɪzənʃɪp/", "명사", "시민권", "Corporate citizenship improved.", "기업 시민 정신이 향상됐다."),
    "rebound": ("/rɪˈbaʊnd/", "동사", "반등하다", "The economy rebounded strongly.", "경제가 강하게 반등했다."),
    "scorecard": ("/ˈskɔːrkɑːrd/", "명사", "성과 카드", "A balanced scorecard was used.", "균형 성과 카드가 사용됐다."),
    "ounce": ("/aʊns/", "명사", "온스", "Gold rose per ounce.", "금이 온스당 올랐다."),
    "plague": ("/pleɪɡ/", "동사", "괴롭히다", "Debt plagued the firm.", "부채가 회사를 괴롭혔다."),
    "killer": ("/ˈkɪlər/", "명사", "킬러, 강력한 제품", "A killer app dominated.", "킬러 앱이 지배했다."),
    "grave": ("/ɡreɪv/", "형용사", "심각한, 중대한", "Grave concerns were raised.", "심각한 우려가 제기됐다."),
    "contributor": ("/kənˈtrɪbjʊtər/", "명사", "기여자, 납세자", "Major contributors were rewarded.", "주요 기여자들이 보상받았다."),
    "cognitive": ("/ˈkɒɡnɪtɪv/", "형용사", "인지의", "Cognitive biases affect decisions.", "인지 편향이 의사결정에 영향을 미친다."),
    "negotiable": ("/nɪˈɡoʊʃɪəbəl/", "형용사", "협상 가능한, 양도 가능한", "The terms are negotiable.", "조건은 협상 가능하다."),
    "reconstruction": ("/ˌriːkənˈstrʌkʃən/", "명사", "재건", "Post-war reconstruction began.", "전후 재건이 시작됐다."),
    "restate": ("/ˌriːˈsteɪt/", "동사", "재작성하다, 수정 공시하다", "Earnings were restated.", "수익이 수정 공시됐다."),
    "rightly": ("/ˈraɪtli/", "부사", "당연히, 올바르게", "Rightly, costs were cut.", "당연히 비용이 삭감됐다."),
    "converge": ("/kənˈvɜːrdʒ/", "동사", "수렴하다", "Interest rates converged.", "금리가 수렴했다."),
    "sadly": ("/ˈsædli/", "부사", "안타깝게도", "Sadly, the firm went bankrupt.", "안타깝게도 회사가 파산했다."),
    "paramilitary": ("/ˌpærəˈmɪlɪtəri/", "명사", "준군사 조직", "Paramilitary groups seized resources.", "준군사 조직이 자원을 장악했다."),
    "incorrect": ("/ˌɪnkəˈrekt/", "형용사", "잘못된", "The data was incorrect.", "데이터가 잘못됐다."),
    "compulsory": ("/kəmˈpʌlsəri/", "형용사", "의무적인, 강제적인", "Compulsory insurance was introduced.", "의무 보험이 도입됐다."),
    "dismantle": ("/dɪsˈmæntəl/", "동사", "해체하다", "Regulations were dismantled.", "규정이 해체됐다."),
    "precision": ("/prɪˈsɪʒən/", "명사", "정밀도, 정확성", "Financial precision is required.", "재무적 정밀도가 필요하다."),
    "duly": ("/ˈdjuːli/", "부사", "정당하게, 제때에", "The payment was duly made.", "지급이 제때 이루어졌다."),
    "reformist": ("/rɪˈfɔːrmɪst/", "명사", "개혁주의자", "Reformist politicians won.", "개혁주의 정치인들이 이겼다."),
    "imminent": ("/ˈɪmɪnənt/", "형용사", "임박한", "A rate hike is imminent.", "금리 인상이 임박했다."),
    "sympathy": ("/ˈsɪmpəθi/", "명사", "공감, 동정", "Market sympathy was short-lived.", "시장의 공감은 오래가지 않았다."),
    "forecaster": ("/ˈfɔːrkæstər/", "명사", "예측가", "Forecasters revised estimates.", "예측가들이 추정치를 수정했다."),
    "conceal": ("/kənˈsiːl/", "동사", "숨기다", "Losses were concealed.", "손실이 숨겨졌다."),
    "unrelated": ("/ˌʌnrɪˈleɪtɪd/", "형용사", "무관한", "Unrelated diversification failed.", "무관한 다각화가 실패했다."),
    "clarity": ("/ˈklærɪti/", "명사", "명확성", "Regulatory clarity is needed.", "규제 명확성이 필요하다."),
    "rigorous": ("/ˈrɪɡərəs/", "형용사", "엄격한", "Rigorous testing was done.", "엄격한 테스트가 이루어졌다."),
    "flotation": ("/fləˈteɪʃən/", "명사", "주식 상장, 부유", "A stock market flotation occurred.", "주식 시장 상장이 이루어졌다."),
    "hitherto": ("/ˌhɪðəˈtuː/", "부사", "지금까지", "Hitherto unknown risks emerged.", "지금까지 알려지지 않은 위험이 나타났다."),
    "maneuver": ("/məˈnuːvər/", "명사", "책략, 기동", "A financial maneuver was executed.", "재무 책략이 실행됐다."),
    "prosperous": ("/ˈprɒspərəs/", "형용사", "번창하는", "A prosperous economy emerged.", "번창하는 경제가 나타났다."),
    "launder": ("/ˈlɔːndər/", "동사", "세탁하다 (자금)", "Money was laundered.", "돈이 세탁됐다."),
    "statistically": ("/stəˈtɪstɪkli/", "부사", "통계적으로", "The result is statistically significant.", "결과가 통계적으로 유의미하다."),
    "specialization": ("/ˌspeʃəlaɪˈzeɪʃən/", "명사", "전문화", "Specialization improves efficiency.", "전문화가 효율성을 향상시킨다."),
    "globally": ("/ˈɡloʊbəli/", "부사", "전 세계적으로", "Firms operate globally.", "기업들이 전 세계적으로 운영된다."),
    "cleric": ("/ˈklerɪk/", "명사", "성직자", "Clerics influenced economic policy.", "성직자들이 경제 정책에 영향을 미쳤다."),
    "pronounce": ("/prəˈnaʊns/", "동사", "발표하다, 선언하다", "The verdict was pronounced.", "평결이 선언됐다."),
    "unify": ("/ˈjuːnɪfaɪ/", "동사", "통일하다", "Markets were unified.", "시장이 통일됐다."),
    "dash": ("/dæʃ/", "명사", "분주한 움직임", "A dash for cash occurred.", "현금을 향한 분주한 움직임이 있었다."),
    "rein": ("/reɪn/", "명사", "고삐, 제한", "Tight reins on spending.", "지출에 엄격한 제한."),
    "dismissal": ("/dɪsˈmɪsəl/", "명사", "해고, 기각", "Wrongful dismissal was claimed.", "부당 해고가 주장됐다."),
    "empowerment": ("/ɪmˈpaʊərmənt/", "명사", "권한 부여", "Employee empowerment grew.", "직원 권한 부여가 증가했다."),
    "revival": ("/rɪˈvaɪvəl/", "명사", "부활, 회복", "An economic revival began.", "경제 부활이 시작됐다."),
    "nationalize": ("/ˈnæʃənəlaɪz/", "동사", "국유화하다", "The bank was nationalized.", "은행이 국유화됐다."),
    "swiftly": ("/ˈswɪftli/", "부사", "신속하게", "Action was taken swiftly.", "조치가 신속하게 취해졌다."),
    "nationalism": ("/ˈnæʃənəlɪzəm/", "명사", "민족주의", "Economic nationalism rose.", "경제 민족주의가 증가했다."),
    "void": ("/vɔɪd/", "형용사", "무효의", "The contract is void.", "계약이 무효이다."),
    "prejudice": ("/ˈpredʒʊdɪs/", "명사", "편견", "Without prejudice to rights.", "권리에 대한 편견 없이."),
    "enforceable": ("/ɪnˈfɔːrsəbəl/", "형용사", "강제 집행 가능한", "The clause is legally enforceable.", "조항이 법적으로 강제 집행 가능하다."),
    "instinct": ("/ˈɪnstɪŋkt/", "명사", "본능, 직관", "Business instinct was sharp.", "비즈니스 직관이 날카로웠다."),
    "dub": ("/dʌb/", "동사", "별명을 붙이다", "The firm was dubbed too big to fail.", "회사는 망하기엔 너무 크다는 별명이 붙었다."),
    "deliberate": ("/dɪˈlɪbərɪt/", "형용사", "의도적인, 신중한", "A deliberate strategy was chosen.", "의도적인 전략이 선택됐다."),
    "approximation": ("/əˌprɒksɪˈmeɪʃən/", "명사", "근사치", "A rough approximation was used.", "거친 근사치가 사용됐다."),
    "unsecured": ("/ˌʌnsɪˈkjʊərd/", "형용사", "무담보의", "Unsecured debt is riskier.", "무담보 부채가 더 위험하다."),
    "quotation": ("/kwoʊˈteɪʃən/", "명사", "견적, 인용", "A price quotation was issued.", "가격 견적이 발행됐다."),
    "mold": ("/moʊld/", "동사", "형성하다, 틀에 맞추다", "The strategy molded growth.", "전략이 성장을 형성했다."),
    "blast": ("/blɑːst/", "명사", "강타, 폭발", "A blast of bad news hit.", "나쁜 소식이 강타했다."),
    "alas": ("/əˈlæs/", "감탄사", "아, 슬프게도", "Alas, the deal collapsed.", "슬프게도, 거래가 무산됐다."),
    "impair": ("/ɪmˈpeər/", "동사", "손상시키다", "Losses impaired the balance sheet.", "손실이 재무상태표를 손상시켰다."),
    "testify": ("/ˈtestɪfaɪ/", "동사", "증언하다", "The CFO testified in court.", "CFO가 법원에서 증언했다."),
    "prod": ("/prɒd/", "동사", "자극하다, 촉구하다", "Investors prodded for change.", "투자자들이 변화를 촉구했다."),
    "liberalize": ("/ˈlɪbərəlaɪz/", "동사", "자유화하다", "Trade was liberalized.", "무역이 자유화됐다."),
    "bully": ("/ˈbʊli/", "동사", "협박하다", "Larger firms bullied suppliers.", "대형 기업들이 공급업체를 협박했다."),
    "persistent": ("/pəˈsɪstənt/", "형용사", "지속적인", "Persistent inflation was a concern.", "지속적인 인플레이션이 우려였다."),
    "catastrophe": ("/kəˈtæstrəfi/", "명사", "재앙", "A financial catastrophe unfolded.", "금융 재앙이 전개됐다."),
    "endless": ("/ˈendlɪs/", "형용사", "끝없는", "Endless regulations burdened firms.", "끝없는 규정이 기업에 부담을 줬다."),
    "revaluation": ("/ˌriːˌvæljʊˈeɪʃən/", "명사", "재평가, 평가절상", "Currency revaluation followed.", "통화 재평가가 뒤따랐다."),
    "swell": ("/swel/", "동사", "팽창하다, 증가하다", "Deficits swelled.", "적자가 팽창했다."),
    "worthy": ("/ˈwɜːrði/", "형용사", "가치 있는", "A worthy investment was found.", "가치 있는 투자가 발견됐다."),
    "resale": ("/ˈriːseɪl/", "명사", "재판매", "Resale value was high.", "재판매 가치가 높았다."),
    "progressive": ("/prəˈɡresɪv/", "형용사", "누진적인, 진보적인", "A progressive tax system.", "누진 세금 체계."),
    "corrective": ("/kəˈrektɪv/", "형용사", "수정적인, 교정적인", "Corrective action was taken.", "수정 조치가 취해졌다."),
    "genocide": ("/ˈdʒenəsaɪd/", "명사", "집단학살", "Economic genocide was alleged.", "경제적 집단학살이 주장됐다."),
    "legitimacy": ("/lɪˈdʒɪtɪməsi/", "명사", "합법성, 정당성", "The regime's legitimacy faltered.", "정권의 정당성이 흔들렸다."),
    "speculator": ("/ˈspekjʊleɪtər/", "명사", "투기꾼", "Speculators drove prices up.", "투기꾼들이 가격을 올렸다."),
    "inconsistent": ("/ˌɪnkənˈsɪstənt/", "형용사", "일관성 없는", "Inconsistent data confused analysts.", "일관성 없는 데이터가 분석가들을 혼란시켰다."),
    "plainly": ("/ˈpleɪnli/", "부사", "명백히", "Plainly, costs were too high.", "명백히 비용이 너무 높았다."),
    "equate": ("/ɪˈkweɪt/", "동사", "동일시하다", "Growth was equated with success.", "성장이 성공과 동일시됐다."),
    "unexpectedly": ("/ˌʌnɪkˈspektɪdli/", "부사", "예상치 못하게", "Profits rose unexpectedly.", "수익이 예상치 못하게 올랐다."),
    "timber": ("/ˈtɪmbər/", "명사", "목재", "Timber prices fell sharply.", "목재 가격이 급격히 하락했다."),
    "credential": ("/krɪˈdenʃəl/", "명사", "자격증, 증명서", "Professional credentials were checked.", "전문 자격증이 확인됐다."),
    "randomly": ("/ˈrændəmli/", "부사", "무작위로", "Samples were randomly selected.", "샘플이 무작위로 선정됐다."),
    "colonial": ("/kəˈloʊnɪəl/", "형용사", "식민지의", "Colonial trade patterns endured.", "식민지 무역 패턴이 지속됐다."),
    "underpin": ("/ˌʌndərˈpɪn/", "동사", "뒷받침하다", "Sound policy underpins growth.", "건전한 정책이 성장을 뒷받침한다."),
    "diary": ("/ˈdaɪəri/", "명사", "일지, 일정표", "The economic diary is full.", "경제 일정이 가득 차 있다."),
    "heir": ("/eər/", "명사", "상속인", "The heir took over the business.", "상속인이 사업을 이어받았다."),
    "genuinely": ("/ˈdʒenjʊɪnli/", "부사", "진정으로", "Genuinely good results emerged.", "진정으로 좋은 결과가 나타났다."),
    "severely": ("/sɪˈvɪərli/", "부사", "심각하게", "Profits were severely hit.", "수익이 심각하게 타격을 받았다."),
    "grim": ("/ɡrɪm/", "형용사", "암울한, 엄혹한", "A grim economic outlook.", "암울한 경제 전망."),
    "relational": ("/rɪˈleɪʃənəl/", "형용사", "관계적인", "Relational databases store data.", "관계형 데이터베이스가 데이터를 저장한다."),
    "brutal": ("/ˈbruːtəl/", "형용사", "냉혹한, 잔인한", "Brutal competition eliminated firms.", "냉혹한 경쟁이 기업을 제거했다."),
    "quasi": ("/ˈkweɪzaɪ/", "접두사", "유사한, 준~", "Quasi-government entities expanded.", "준정부 기관이 확장됐다."),
    "monopolist": ("/məˈnɒpəlɪst/", "명사", "독점자", "The monopolist set prices.", "독점자가 가격을 정했다."),
    "physically": ("/ˈfɪzɪkli/", "부사", "물리적으로", "Assets physically inspected.", "자산이 물리적으로 검사됐다."),
    "disposition": ("/ˌdɪspəˈzɪʃən/", "명사", "처분, 성향", "Asset disposition was planned.", "자산 처분이 계획됐다."),
    "histogram": ("/ˈhɪstəɡræm/", "명사", "히스토그램", "A return histogram was plotted.", "수익 히스토그램이 그려졌다."),
    "misunderstand": ("/ˌmɪsʌndəˈstænd/", "동사", "오해하다", "Risk was misunderstood.", "위험이 오해됐다."),
    "outgoing": ("/ˈaʊtɡoʊɪŋ/", "형용사", "나가는, 퇴임하는", "The outgoing CEO commented.", "퇴임하는 CEO가 논평했다."),
    "worksheet": ("/ˈwɜːrkʃiːt/", "명사", "워크시트", "The financial worksheet was updated.", "재무 워크시트가 업데이트됐다."),
    "intercept": ("/ˈɪntərsept/", "명사", "절편, 가로채기", "The regression intercept was zero.", "회귀 절편이 0이었다."),
    "dent": ("/dent/", "명사", "흠집, 타격", "A dent in profits was seen.", "수익에 타격이 발생했다."),
    "absorption": ("/əbˈzɔːrpʃən/", "명사", "흡수, 흡수 합병", "Market absorption was slow.", "시장 흡수가 느렸다."),
    "importer": ("/ɪmˈpɔːrtər/", "명사", "수입업자", "The importer faced tariffs.", "수입업자가 관세에 직면했다."),
    "peacekeeping": ("/ˈpiːskiːpɪŋ/", "명사", "평화유지", "Peacekeeping costs rose.", "평화유지 비용이 올랐다."),
    "continuity": ("/ˌkɒntɪˈnjuːɪti/", "명사", "연속성", "Business continuity was maintained.", "사업 연속성이 유지됐다."),
    "geography": ("/dʒiˈɒɡrəfi/", "명사", "지리학, 지역", "Expanding geography drove growth.", "지역 확장이 성장을 이끌었다."),
    "dismal": ("/ˈdɪzməl/", "형용사", "참담한, 암울한", "Dismal performance was reported.", "참담한 실적이 보고됐다."),
    "magnetic": ("/mæɡˈnetɪk/", "형용사", "자력의, 매력적인", "A magnetic personality helped.", "매력적인 성격이 도움이 됐다."),
    "generalize": ("/ˈdʒenərəlaɪz/", "동사", "일반화하다", "Results should not be generalized.", "결과를 일반화해서는 안 된다."),
    "confrontation": ("/ˌkɒnfrənˈteɪʃən/", "명사", "대결, 충돌", "A market confrontation followed.", "시장 대결이 이어졌다."),
    "demise": ("/dɪˈmaɪz/", "명사", "몰락, 소멸", "The demise of the firm.", "회사의 몰락."),
    "reversal": ("/rɪˈvɜːrsəl/", "명사", "역전, 반전", "A trend reversal occurred.", "추세 반전이 발생했다."),
    "tide": ("/taɪd/", "명사", "조류, 흐름", "The tide turned for markets.", "시장의 흐름이 바뀌었다."),
    "saver": ("/ˈseɪvər/", "명사", "저축자", "Savers suffered from low rates.", "저축자들이 낮은 금리로 고통받았다."),
    "tick": ("/tɪk/", "명사", "가격 최소 변동 폭", "Prices rose one tick.", "가격이 한 틱 올랐다."),
    "intensify": ("/ɪnˈtensɪfaɪ/", "동사", "심화되다, 강화되다", "Competition intensified.", "경쟁이 심화됐다."),
    "reluctance": ("/rɪˈlʌktəns/", "명사", "꺼림, 주저함", "Investor reluctance grew.", "투자자 주저함이 커졌다."),
    "aviation": ("/ˌeɪvɪˈeɪʃən/", "명사", "항공", "Aviation stocks recovered.", "항공 주식이 회복됐다."),
    "defy": ("/dɪˈfaɪ/", "동사", "거스르다, 무시하다", "Profits defied expectations.", "수익이 기대치를 거슬렀다."),
    "confer": ("/kənˈfɜːr/", "동사", "수여하다, 협의하다", "Rights were conferred by law.", "법에 의해 권리가 수여됐다."),
    "surveillance": ("/sɜːrˈveɪləns/", "명사", "감시, 모니터링", "Financial surveillance increased.", "금융 감시가 강화됐다."),
    "decimal": ("/ˈdesɪməl/", "명사", "소수, 십진법", "Move the decimal point.", "소수점을 이동하다."),
    "realizable": ("/ˈrɪəlaɪzəbəl/", "형용사", "실현 가능한", "Net realizable value was assessed.", "순 실현 가능 가치가 평가됐다."),
}


def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT18:
                    pron, pos, meaning, ex_en, ex_ko = DICT18[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")


if __name__ == "__main__":
    print("=== Patching with fill_more18.py ===\n")
    patch_files()
