#!/usr/bin/env python3
"""Fill remaining fallback entries: freq-L7(6) + freq-L1(9) + toeic-L1(3) + freq-L8(269)"""
import json, glob

DICT8 = {
    # freq-L7 remaining
    "hell":          ("/hɛl/", "명사", "지옥, 큰 고통", "What the hell is going on?", "도대체 무슨 일이야?"),
    "disk":          ("/dɪsk/", "명사", "디스크, 원반", "Save the file to a disk.", "파일을 디스크에 저장하세요."),
    "presidential":  ("/ˌprɛzɪˈdɛnʃəl/", "형용사", "대통령의", "The presidential election is next month.", "대통령 선거가 다음 달입니다."),
    "perfectly":     ("/ˈpɜːrfɪktli/", "부사", "완벽하게", "She speaks English perfectly.", "그녀는 영어를 완벽하게 말한다."),
    "educational":   ("/ˌɛdʒʊˈkeɪʃənəl/", "형용사", "교육적인", "This is an educational program.", "이것은 교육적인 프로그램이다."),
    "breast":        ("/brɛst/", "명사", "가슴, 유방", "Chicken breast is a healthy protein.", "닭가슴살은 건강한 단백질이다."),

    # freq-L1 remaining
    "form":          ("/fɔːrm/", "명사", "형태, 양식", "Please fill out this form.", "이 양식을 작성해 주세요."),
    "person":        ("/ˈpɜːrsən/", "명사", "사람, 개인", "She is a kind person.", "그녀는 친절한 사람이다."),
    "member":        ("/ˈmɛmbər/", "명사", "회원, 구성원", "He is a member of the team.", "그는 팀의 구성원이다."),
    "bad":           ("/bæd/", "형용사", "나쁜, 좋지 않은", "The weather is bad today.", "오늘 날씨가 나쁘다."),
    "whether":       ("/ˈwɛðər/", "접속사", "~인지 아닌지", "I don't know whether he is coming.", "그가 올지 모르겠다."),
    "present":       ("/ˈprɛzənt/", "형용사", "현재의, 참석한", "All members are present.", "모든 구성원이 참석했다."),
    "quite":         ("/kwaɪt/", "부사", "꽤, 상당히", "It is quite cold outside.", "밖이 꽤 춥다."),
    "although":      ("/ɔːlˈðoʊ/", "접속사", "비록 ~이지만", "Although tired, he kept working.", "피곤했지만 그는 계속 일했다."),
    "least":         ("/liːst/", "형용사", "가장 적은", "At least try once.", "적어도 한 번은 시도해봐."),

    # toeic-L1 remaining
    "unreal":        ("/ʌnˈriːəl/", "형용사", "비현실적인, 믿기 어려운", "The view was absolutely unreal.", "그 경치는 정말 믿기 어려울 정도였다."),
    "distractor":    ("/dɪˈstræktər/", "명사", "오답 선택지, 방해 요소", "Identify the distractors in the test.", "시험의 오답 선택지를 파악하세요."),
    "provider":      ("/prəˈvaɪdər/", "명사", "제공자, 공급자", "Choose a reliable service provider.", "신뢰할 수 있는 서비스 제공자를 선택하세요."),

    # freq-L8 (269 words)
    "rapidly":       ("/ˈræpɪdli/", "부사", "빠르게, 급속히", "Technology is changing rapidly.", "기술이 빠르게 변하고 있다."),
    "revolution":    ("/ˌrɛvəˈluːʃən/", "명사", "혁명, 혁신", "The industrial revolution changed society.", "산업혁명이 사회를 바꿨다."),
    "delight":       ("/dɪˈlaɪt/", "명사", "기쁨, 즐거움", "The children squealed with delight.", "아이들이 기뻐서 소리질렀다."),
    "spell":         ("/spɛl/", "동사", "철자를 쓰다, 맞춤법을 쓰다", "Can you spell your name?", "이름의 철자를 말해줄 수 있나요?"),
    "premise":       ("/ˈprɛmɪs/", "명사", "전제, 구내", "The argument is based on a false premise.", "그 논거는 잘못된 전제에 근거한다."),
    "lean":          ("/liːn/", "동사", "기대다, 기울다", "Lean against the wall.", "벽에 기대세요."),
    "dramatic":      ("/drəˈmætɪk/", "형용사", "극적인, 인상적인", "There was a dramatic change in sales.", "판매에 극적인 변화가 있었다."),
    "differ":        ("/ˈdɪfər/", "동사", "다르다, 차이가 있다", "Opinions differ on this issue.", "이 문제에 대해 의견이 다르다."),
    "grateful":      ("/ˈɡreɪtfəl/", "형용사", "감사하는", "I am grateful for your help.", "도움에 감사드립니다."),
    "protein":       ("/ˈproʊtiːn/", "명사", "단백질", "Eggs are a good source of protein.", "달걀은 단백질의 좋은 공급원이다."),
    "bike":          ("/baɪk/", "명사", "자전거", "I ride my bike to work.", "나는 자전거로 출근한다."),
    "distribute":    ("/dɪˈstrɪbjuːt/", "동사", "배포하다, 분배하다", "We will distribute the reports.", "우리는 보고서를 배포할 것이다."),
    "intellectual":  ("/ˌɪntəˈlɛktʃuəl/", "형용사", "지적인, 지성의", "He enjoys intellectual discussions.", "그는 지적인 토론을 즐긴다."),
    "derive":        ("/dɪˈraɪv/", "동사", "파생되다, 얻다", "This word derives from Latin.", "이 단어는 라틴어에서 파생됐다."),
    "crucial":       ("/ˈkruːʃəl/", "형용사", "결정적인, 중요한", "This meeting is crucial for the project.", "이 회의는 프로젝트에 매우 중요하다."),
    "unemployment":  ("/ˌʌnɪmˈplɔɪmənt/", "명사", "실업, 실업률", "Unemployment is rising in the region.", "그 지역의 실업률이 오르고 있다."),
    "wheel":         ("/wiːl/", "명사", "바퀴, 핸들", "The wheel needs to be replaced.", "바퀴를 교체해야 한다."),
    "crop":          ("/krɒp/", "명사", "농작물, 수확물", "The crop harvest was excellent.", "농작물 수확이 훌륭했다."),
    "minority":      ("/maɪˈnɒrɪti/", "명사", "소수, 소수집단", "Protect the rights of the minority.", "소수집단의 권리를 보호하라."),
    "origin":        ("/ˈɒrɪdʒɪn/", "명사", "기원, 출신", "What is the origin of this word?", "이 단어의 기원은 무엇인가?"),
    "interpretation":("/ɪnˌtɜːrprɪˈteɪʃən/", "명사", "해석, 설명", "There are many interpretations.", "여러 가지 해석이 있다."),
    "gentleman":     ("/ˈdʒɛntlmən/", "명사", "신사", "He is a true gentleman.", "그는 진정한 신사이다."),
    "drama":         ("/ˈdrɑːmə/", "명사", "드라마, 극", "She stars in a popular drama.", "그녀는 인기 드라마에 출연한다."),
    "landscape":     ("/ˈlændskeɪp/", "명사", "풍경, 경관", "The landscape is breathtaking.", "풍경이 숨막히게 아름답다."),
    "educate":       ("/ˈɛdʒʊkeɪt/", "동사", "교육하다", "We must educate our children.", "우리는 아이들을 교육해야 한다."),
    "toy":           ("/tɔɪ/", "명사", "장난감", "The child plays with toys.", "아이가 장난감으로 논다."),
    "fault":         ("/fɔːlt/", "명사", "잘못, 결함", "It was my fault.", "그것은 내 잘못이었다."),
    "exhibit":       ("/ɪɡˈzɪbɪt/", "동사", "전시하다, 보여주다", "The museum will exhibit new paintings.", "박물관이 새 그림을 전시할 것이다."),
    "minor":         ("/ˈmaɪnər/", "형용사", "작은, 사소한", "This is a minor problem.", "이것은 사소한 문제이다."),
    "hunt":          ("/hʌnt/", "동사", "사냥하다, 찾다", "They hunt for food.", "그들은 먹을 것을 찾는다."),
    "storm":         ("/stɔːrm/", "명사", "폭풍, 태풍", "A storm is approaching the coast.", "폭풍이 해안에 접근하고 있다."),
    "thick":         ("/θɪk/", "형용사", "두꺼운, 짙은", "The walls are thick.", "벽이 두껍다."),
    "achievement":   ("/əˈtʃiːvmənt/", "명사", "성취, 업적", "This is a great achievement.", "이것은 훌륭한 업적이다."),
    "dominate":      ("/ˈdɒmɪneɪt/", "동사", "지배하다, 압도하다", "They dominate the market.", "그들이 시장을 지배한다."),
    "prize":         ("/praɪz/", "명사", "상, 상금", "She won the first prize.", "그녀가 1등 상을 받았다."),
    "typically":     ("/ˈtɪpɪkli/", "부사", "일반적으로, 보통", "Classes typically start at 9 AM.", "수업은 보통 오전 9시에 시작한다."),
    "pension":       ("/ˈpɛnʃən/", "명사", "연금", "He receives a monthly pension.", "그는 월 연금을 받는다."),
    "wing":          ("/wɪŋ/", "명사", "날개, 날개 부분", "The bird spread its wings.", "새가 날개를 펼쳤다."),
    "laughter":      ("/ˈlæftər/", "명사", "웃음", "Laughter is the best medicine.", "웃음이 최고의 약이다."),
    "deeply":        ("/ˈdiːpli/", "부사", "깊이, 매우", "I am deeply sorry.", "정말 깊이 죄송합니다."),
    "recognition":   ("/ˌrɛkəɡˈnɪʃən/", "명사", "인정, 인식", "Her work received recognition.", "그녀의 작업이 인정받았다."),
    "electricity":   ("/ɪˌlɛkˈtrɪsɪti/", "명사", "전기", "The electricity was cut off.", "전기가 끊어졌다."),
    "assistance":    ("/əˈsɪstəns/", "명사", "도움, 지원", "I need your assistance.", "당신의 도움이 필요합니다."),
    "roof":          ("/ruːf/", "명사", "지붕", "The roof needs repair.", "지붕 수리가 필요하다."),
    "retirement":    ("/rɪˈtaɪərmənt/", "명사", "은퇴, 퇴직", "He celebrated his retirement.", "그는 은퇴를 축하했다."),
    "respectively":  ("/rɪˈspɛktɪvli/", "부사", "각각, 순서대로", "They scored 80 and 90, respectively.", "그들은 각각 80점과 90점을 받았다."),
    "variation":     ("/ˌvɛərɪˈeɪʃən/", "명사", "변화, 변형", "There is a variation in prices.", "가격에 변동이 있다."),
    "ultimately":    ("/ˈʌltɪmɪtli/", "부사", "궁극적으로, 결국", "It will ultimately succeed.", "그것은 결국 성공할 것이다."),
    "proof":         ("/pruːf/", "명사", "증거, 증명", "Do you have proof of that?", "그것에 대한 증거가 있나요?"),
    "soil":          ("/sɔɪl/", "명사", "토양, 흙", "The soil is fertile here.", "이곳의 토양은 비옥하다."),
    "smart":         ("/smɑːrt/", "형용사", "영리한, 스마트한", "She is a smart student.", "그녀는 영리한 학생이다."),
    "layer":         ("/ˈleɪər/", "명사", "층, 레이어", "Add another layer of paint.", "페인트를 한 겹 더 칠하세요."),
    "upset":         ("/ʌpˈsɛt/", "형용사", "화난, 속상한", "She was upset by the news.", "그녀는 그 소식에 속상해했다."),
    "tooth":         ("/tuːθ/", "명사", "이, 치아", "Brush your teeth twice a day.", "하루에 두 번 이를 닦으세요."),
    "representation":("/ˌrɛprɪzɛnˈteɪʃən/", "명사", "대표, 표현", "They demand fair representation.", "그들은 공정한 대표를 요구한다."),
    "preparation":   ("/ˌprɛpəˈreɪʃən/", "명사", "준비", "Good preparation is key.", "좋은 준비가 핵심이다."),
    "dispute":       ("/dɪˈspjuːt/", "명사", "분쟁, 논쟁", "They settled the dispute peacefully.", "그들은 분쟁을 평화롭게 해결했다."),
    "emphasis":      ("/ˈɛmfəsɪs/", "명사", "강조", "She placed emphasis on quality.", "그녀는 품질을 강조했다."),
    "edition":       ("/ɪˈdɪʃən/", "명사", "판, 호", "Buy the latest edition.", "최신 판을 구매하세요."),
    "silver":        ("/ˈsɪlvər/", "명사", "은, 은색", "The ring is made of silver.", "그 반지는 은으로 만들어졌다."),
    "entertainment": ("/ˌɛntəˈteɪnmənt/", "명사", "오락, 연예", "Movies are popular entertainment.", "영화는 인기 있는 오락이다."),
    "honest":        ("/ˈɒnɪst/", "형용사", "정직한", "Be honest with yourself.", "자신에게 솔직해지세요."),
    "undertake":     ("/ˌʌndərˈteɪk/", "동사", "맡다, 착수하다", "We will undertake this project.", "우리는 이 프로젝트를 맡을 것이다."),
    "retail":        ("/ˈriːteɪl/", "명사", "소매, 소매업", "The retail price is higher.", "소매 가격이 더 높다."),
    "wire":          ("/waɪər/", "명사", "전선, 철사", "Connect the wire carefully.", "전선을 조심스럽게 연결하세요."),
    "unlikely":      ("/ʌnˈlaɪkli/", "형용사", "있을 것 같지 않은", "It is unlikely to rain today.", "오늘 비가 올 것 같지 않다."),
    "gay":           ("/ɡeɪ/", "형용사", "동성애의, 게이의", "Gay rights are human rights.", "동성애자 권리는 인권이다."),
    "slight":        ("/slaɪt/", "형용사", "약간의, 가벼운", "There is a slight delay.", "약간의 지연이 있다."),
    "unknown":       ("/ʌnˈnoʊn/", "형용사", "알려지지 않은", "The cause is still unknown.", "원인은 아직 알려지지 않았다."),
    "zone":          ("/zoʊn/", "명사", "구역, 지대", "This is a no-parking zone.", "이곳은 주차 금지 구역이다."),
    "restrict":      ("/rɪˈstrɪkt/", "동사", "제한하다, 금지하다", "Access is restricted here.", "이곳의 출입은 제한된다."),
    "trace":         ("/treɪs/", "동사", "추적하다, 찾다", "Police traced the suspect.", "경찰이 용의자를 추적했다."),
    "inch":          ("/ɪntʃ/", "명사", "인치", "The screen is 15 inches wide.", "화면이 15인치 넓이다."),
    "equivalent":    ("/ɪˈkwɪvələnt/", "형용사", "동등한, 상당하는", "This is equivalent to a degree.", "이것은 학위에 상당한다."),
    "solid":         ("/ˈsɒlɪd/", "형용사", "단단한, 견고한", "The foundation is solid.", "기초가 견고하다."),
    "enterprise":    ("/ˈɛntərpraɪz/", "명사", "기업, 사업", "He started a new enterprise.", "그는 새 사업을 시작했다."),
    "elderly":       ("/ˈɛldərli/", "형용사", "나이 든, 연로한", "Help the elderly cross the street.", "노인이 길을 건너도록 도와주세요."),
    "owe":           ("/oʊ/", "동사", "빚지다, 신세 지다", "I owe you a favor.", "당신에게 신세를 졌다."),
    "governor":      ("/ˈɡʌvərnər/", "명사", "주지사, 총독", "The governor signed the law.", "주지사가 법안에 서명했다."),
    "uniform":       ("/ˈjuːnɪfɔːrm/", "명사", "제복, 유니폼", "Students wear uniforms.", "학생들은 교복을 입는다."),
    "port":          ("/pɔːrt/", "명사", "항구, 포트", "Ships arrive at the port.", "배들이 항구에 도착한다."),
    "pitch":         ("/pɪtʃ/", "명사", "음조, 경기장, 투구", "The pitch of his voice is high.", "그의 목소리 톤이 높다."),
    "arrival":       ("/əˈraɪvəl/", "명사", "도착", "The arrival time is 3 PM.", "도착 시간은 오후 3시이다."),
    "contemporary":  ("/kənˈtɛmpərəri/", "형용사", "현대의, 동시대의", "She likes contemporary art.", "그녀는 현대 미술을 좋아한다."),
    "gate":          ("/ɡeɪt/", "명사", "문, 게이트", "Please go to gate 12.", "12번 게이트로 가세요."),
    "ease":          ("/iːz/", "명사", "편안함, 쉬움", "She handled it with ease.", "그녀는 그것을 쉽게 처리했다."),
    "beer":          ("/bɪər/", "명사", "맥주", "Can I have a cold beer?", "차가운 맥주 한 잔 주세요?"),
    "specialist":    ("/ˈspɛʃəlɪst/", "명사", "전문가", "See a specialist for your back.", "허리 전문가를 만나세요."),
    "assure":        ("/əˈʃʊər/", "동사", "장담하다, 보장하다", "I assure you it is safe.", "그것이 안전하다고 장담합니다."),
    "profile":       ("/ˈproʊfaɪl/", "명사", "프로필, 윤곽", "Update your profile picture.", "프로필 사진을 업데이트하세요."),
    "mood":          ("/muːd/", "명사", "기분, 분위기", "She is in a good mood today.", "그녀는 오늘 기분이 좋다."),
    "episode":       ("/ˈɛpɪsoʊd/", "명사", "에피소드, 회", "I watched the latest episode.", "최신 에피소드를 봤다."),
    "crack":         ("/kræk/", "동사", "금이 가다, 깨다", "The wall has a crack.", "벽에 금이 갔다."),
    "numerous":      ("/ˈnjuːmərəs/", "형용사", "수많은", "There are numerous options.", "수많은 선택지가 있다."),
    "symptom":       ("/ˈsɪmptəm/", "명사", "증상", "What are your symptoms?", "증상이 무엇인가요?"),
    "virtually":     ("/ˈvɜːrtʃuəli/", "부사", "사실상, 거의", "It is virtually impossible.", "그것은 사실상 불가능하다."),
    "era":           ("/ˈɪərə/", "명사", "시대, 시기", "We live in a digital era.", "우리는 디지털 시대에 산다."),
    "coverage":      ("/ˈkʌvərɪdʒ/", "명사", "보도, 보험 범위", "The news coverage was extensive.", "뉴스 보도가 광범위했다."),
    "tension":       ("/ˈtɛnʃən/", "명사", "긴장, 갈등", "There is tension between them.", "그들 사이에 긴장이 있다."),
    "cable":         ("/ˈkeɪbəl/", "명사", "케이블, 전선", "Connect the cable to the TV.", "TV에 케이블을 연결하세요."),
    "sensitive":     ("/ˈsɛnsɪtɪv/", "형용사", "민감한, 예민한", "He is sensitive to criticism.", "그는 비판에 민감하다."),
    "nervous":       ("/ˈnɜːrvəs/", "형용사", "긴장한, 불안한", "I feel nervous before exams.", "시험 전에 긴장된다."),
    "input":         ("/ˈɪnpʊt/", "명사", "입력, 의견", "Your input is valuable.", "당신의 의견은 귀중합니다."),
    "isolate":       ("/ˈaɪsəleɪt/", "동사", "격리하다, 고립시키다", "Isolate the infected area.", "감염된 부위를 격리하세요."),
    "prisoner":      ("/ˈprɪzənər/", "명사", "죄수, 포로", "The prisoner was released.", "죄수가 석방됐다."),
    "eliminate":     ("/ɪˈlɪmɪneɪt/", "동사", "제거하다, 없애다", "We must eliminate waste.", "낭비를 제거해야 한다."),
    "tight":         ("/taɪt/", "형용사", "꽉 끼는, 팽팽한", "The lid is too tight.", "뚜껑이 너무 꽉 끼인다."),
    "wet":           ("/wɛt/", "형용사", "젖은", "My clothes are wet.", "내 옷이 젖었다."),
    "secondary":     ("/ˈsɛkəndəri/", "형용사", "이차적인, 중등의", "Education is a secondary priority.", "교육은 두 번째 우선순위다."),
    "welfare":       ("/ˈwɛlfeər/", "명사", "복지, 안녕", "Child welfare is important.", "아동 복지는 중요하다."),
    "recruit":       ("/rɪˈkruːt/", "동사", "모집하다, 채용하다", "We are recruiting new employees.", "우리는 새 직원을 모집 중이다."),
    "exclude":       ("/ɪkˈskluːd/", "동사", "제외하다, 배제하다", "Don't exclude anyone.", "누구도 배제하지 마세요."),
    "string":        ("/strɪŋ/", "명사", "끈, 문자열", "Tie it with a string.", "끈으로 묶으세요."),
    "cloud":         ("/klaʊd/", "명사", "구름, 클라우드", "Dark clouds are gathering.", "먹구름이 모이고 있다."),
    "persuade":      ("/pərˈsweɪd/", "동사", "설득하다", "He persuaded me to stay.", "그가 나를 설득해 머물게 했다."),
    "inspire":       ("/ɪnˈspaɪər/", "동사", "영감을 주다", "Her speech inspired everyone.", "그녀의 연설이 모두에게 영감을 줬다."),
    "grand":         ("/ɡrænd/", "형용사", "웅장한, 훌륭한", "It was a grand ceremony.", "그것은 웅장한 행사였다."),
    "hence":         ("/hɛns/", "접속사", "따라서, 이런 이유로", "He was late, hence the apology.", "그가 늦어서 사과했다."),
    "crew":          ("/kruː/", "명사", "승무원, 팀", "The crew prepared for takeoff.", "승무원들이 이륙을 준비했다."),
    "phenomenon":    ("/fɪˈnɒmɪnən/", "명사", "현상", "It is a natural phenomenon.", "그것은 자연 현상이다."),
    "pupil":         ("/ˈpjuːpəl/", "명사", "학생, 동공", "The pupil raised his hand.", "학생이 손을 들었다."),
    "restore":       ("/rɪˈstɔːr/", "동사", "회복하다, 복원하다", "They restored the old building.", "그들이 오래된 건물을 복원했다."),
    "formula":       ("/ˈfɔːrmjʊlə/", "명사", "공식, 방정식", "Apply the correct formula.", "올바른 공식을 적용하세요."),
    "alter":         ("/ˈɔːltər/", "동사", "변경하다, 바꾸다", "Can you alter the schedule?", "일정을 변경할 수 있나요?"),
    "perceive":      ("/pərˈsiːv/", "동사", "인식하다, 이해하다", "How do you perceive this?", "이것을 어떻게 인식하나요?"),
    "routine":       ("/ruːˈtiːn/", "명사", "일과, 루틴", "Exercise is part of my routine.", "운동은 내 일과의 일부이다."),
    "sink":          ("/sɪŋk/", "동사", "가라앉다, 침몰하다", "The ship began to sink.", "배가 가라앉기 시작했다."),
    "stare":         ("/stɛər/", "동사", "응시하다, 빤히 보다", "Don't stare at people.", "사람들을 빤히 쳐다보지 마세요."),
    "anymore":       ("/ˌɛniˈmɔːr/", "부사", "더 이상, 이제는", "I don't live there anymore.", "나는 더 이상 거기 살지 않는다."),
    "hero":          ("/ˈhɪəroʊ/", "명사", "영웅", "He is my hero.", "그는 내 영웅이다."),
    "supporter":     ("/səˈpɔːrtər/", "명사", "지지자, 후원자", "She has many supporters.", "그녀에게는 많은 지지자가 있다."),
    "convert":       ("/kənˈvɜːrt/", "동사", "전환하다, 개종하다", "Convert the file to PDF.", "파일을 PDF로 변환하세요."),
    "steady":        ("/ˈstɛdi/", "형용사", "안정된, 꾸준한", "Maintain a steady pace.", "안정된 속도를 유지하세요."),
    "meter":         ("/ˈmiːtər/", "명사", "미터, 계량기", "The room is 5 meters wide.", "방은 가로 5미터이다."),
    "truck":         ("/trʌk/", "명사", "트럭", "The truck delivered the goods.", "트럭이 물건을 배달했다."),
    "nose":          ("/noʊz/", "명사", "코", "She has a small nose.", "그녀는 코가 작다."),
    "beside":        ("/bɪˈsaɪd/", "전치사", "~옆에", "Sit beside me.", "내 옆에 앉으세요."),
    "sail":          ("/seɪl/", "동사", "항해하다, 떠나다", "We will sail at dawn.", "우리는 새벽에 출항한다."),
    "disaster":      ("/dɪˈzæstər/", "명사", "재해, 재난", "The flood was a natural disaster.", "홍수는 자연재해였다."),
    "pace":          ("/peɪs/", "명사", "속도, 페이스", "Walk at a comfortable pace.", "편안한 속도로 걷으세요."),
    "heavily":       ("/ˈhɛvɪli/", "부사", "심하게, 많이", "It was raining heavily.", "비가 심하게 왔다."),
    "devote":        ("/dɪˈvoʊt/", "동사", "헌신하다, 바치다", "She devoted her life to art.", "그녀는 삶을 예술에 바쳤다."),
    "terrorist":     ("/ˈtɛrərɪst/", "명사", "테러리스트", "The terrorist was arrested.", "테러리스트가 체포됐다."),
    "justify":       ("/ˈdʒʌstɪfaɪ/", "동사", "정당화하다", "Can you justify this decision?", "이 결정을 정당화할 수 있나요?"),
    "vital":         ("/ˈvaɪtəl/", "형용사", "필수적인, 중요한", "Sleep is vital for health.", "수면은 건강에 필수적이다."),
    "fascinate":     ("/ˈfæsɪneɪt/", "동사", "매혹하다, 매료시키다", "Science fascinates me.", "과학이 나를 매료시킨다."),
    "external":      ("/ɪkˈstɜːrnəl/", "형용사", "외부의, 외적인", "External factors matter.", "외부 요인이 중요하다."),
    "spare":         ("/spɛər/", "동사", "아끼다, 여분의", "Can you spare a moment?", "잠시 시간 있으신가요?"),
    "whenever":      ("/wɛnˈɛvər/", "접속사", "~할 때마다", "Call me whenever you need.", "필요할 때마다 전화하세요."),
    "depression":    ("/dɪˈprɛʃən/", "명사", "우울증, 불황", "Depression is a serious illness.", "우울증은 심각한 질병이다."),
    "guilty":        ("/ˈɡɪlti/", "형용사", "유죄의, 죄책감을 느끼는", "He was found guilty.", "그는 유죄 판결을 받았다."),
    "underlie":      ("/ˌʌndərˈlaɪ/", "동사", "근거가 되다, 밑에 있다", "Several factors underlie this.", "여러 요인이 이 밑에 있다."),
    "mom":           ("/mɒm/", "명사", "엄마", "My mom made dinner.", "엄마가 저녁을 만들었다."),
    "satisfaction":  ("/ˌsætɪsˈfækʃən/", "명사", "만족", "Customer satisfaction is key.", "고객 만족이 핵심이다."),
    "incorporate":   ("/ɪnˈkɔːrpəreɪt/", "동사", "통합하다, 포함시키다", "Incorporate feedback into the plan.", "피드백을 계획에 통합하세요."),
    "pour":          ("/pɔːr/", "동사", "붓다, 쏟아지다", "Pour the water into a glass.", "물을 잔에 부으세요."),
    "sweep":         ("/swiːp/", "동사", "쓸다, 휩쓸다", "Sweep the floor, please.", "바닥을 쓸어주세요."),
    "obligation":    ("/ˌɒblɪˈɡeɪʃən/", "명사", "의무, 책임", "You have an obligation to help.", "도울 의무가 있다."),
    "sir":           ("/sɜːr/", "명사", "선생님, 각하", "Yes, sir, I understand.", "네, 선생님, 알겠습니다."),
    "evaluate":      ("/ɪˈvæljueɪt/", "동사", "평가하다", "We will evaluate your work.", "우리는 당신의 작업을 평가할 것이다."),
    "anger":         ("/ˈæŋɡər/", "명사", "분노, 화", "He couldn't hide his anger.", "그는 분노를 숨길 수 없었다."),
    "pub":           ("/pʌb/", "명사", "술집, 퍼브", "Let's meet at the pub.", "퍼브에서 만나자."),
    "perception":    ("/pərˈsɛpʃən/", "명사", "인식, 지각", "Public perception matters.", "대중의 인식이 중요하다."),
    "naturally":     ("/ˈnætʃərəli/", "부사", "자연스럽게, 당연히", "It happened naturally.", "그것은 자연스럽게 일어났다."),
    "currency":      ("/ˈkʌrənsi/", "명사", "통화, 화폐", "The local currency is yen.", "현지 통화는 엔화이다."),
    "database":      ("/ˈdeɪtəbeɪs/", "명사", "데이터베이스", "The database stores all records.", "데이터베이스가 모든 기록을 저장한다."),
    "initially":     ("/ɪˈnɪʃəli/", "부사", "처음에, 초기에", "Initially, I was confused.", "처음에는 혼란스러웠다."),
    "territory":     ("/ˈtɛrɪtɔːri/", "명사", "영토, 지역", "This is new territory.", "이것은 새로운 영역이다."),
    "stream":        ("/striːm/", "명사", "개울, 흐름", "A stream flows through the park.", "공원을 통해 개울이 흐른다."),
    "rarely":        ("/ˈrɛərli/", "부사", "거의 ~하지 않는", "She rarely eats meat.", "그녀는 고기를 거의 먹지 않는다."),
    "height":        ("/haɪt/", "명사", "키, 높이", "What is your height?", "키가 얼마나 되나요?"),
    "apparent":      ("/əˈpærənt/", "형용사", "명백한, 외견상의", "The solution is apparent.", "해결책이 명백하다."),
    "western":       ("/ˈwɛstərn/", "형용사", "서부의, 서양의", "She loves western movies.", "그녀는 서부 영화를 좋아한다."),
    "expansion":     ("/ɪkˈspænʃən/", "명사", "확장, 팽창", "The company plans expansion.", "회사가 확장을 계획한다."),
    "constantly":    ("/ˈkɒnstəntli/", "부사", "끊임없이, 항상", "She is constantly improving.", "그녀는 끊임없이 발전하고 있다."),
    "muscle":        ("/ˈmʌsəl/", "명사", "근육", "Exercise builds muscle.", "운동은 근육을 키운다."),
    "scare":         ("/skɛər/", "동사", "겁주다, 놀라게 하다", "Don't scare the children.", "아이들을 놀라게 하지 마세요."),
    "badly":         ("/ˈbædli/", "부사", "심하게, 나쁘게", "He was badly injured.", "그는 심하게 부상을 입었다."),
    "everyday":      ("/ˈɛvrideɪ/", "형용사", "일상적인, 매일의", "These are everyday problems.", "이것들은 일상적인 문제들이다."),
    "boundary":      ("/ˈbaʊndəri/", "명사", "경계, 한계", "Respect other people's boundaries.", "타인의 경계를 존중하세요."),
    "ratio":         ("/ˈreɪʃioʊ/", "명사", "비율, 비", "The ratio is 2 to 1.", "비율은 2 대 1이다."),
    "essay":         ("/ˈɛseɪ/", "명사", "에세이, 논문", "Write a 500-word essay.", "500자 에세이를 작성하세요."),
    "scream":        ("/skriːm/", "동사", "비명 지르다, 소리치다", "She screamed in fear.", "그녀는 두려움에 비명을 질렀다."),
    "withdraw":      ("/wɪðˈdrɔː/", "동사", "철수하다, 인출하다", "Withdraw money from the bank.", "은행에서 돈을 인출하세요."),
    "pollution":     ("/pəˈluːʃən/", "명사", "오염", "Air pollution is a serious issue.", "대기 오염은 심각한 문제이다."),
    "disorder":      ("/dɪsˈɔːrdər/", "명사", "장애, 무질서", "She has an anxiety disorder.", "그녀는 불안 장애가 있다."),
    "furniture":     ("/ˈfɜːrnɪtʃər/", "명사", "가구", "We need new furniture.", "새 가구가 필요하다."),
    "symbol":        ("/ˈsɪmbəl/", "명사", "상징, 기호", "The dove is a symbol of peace.", "비둘기는 평화의 상징이다."),
    "demonstration": ("/ˌdɛmənˈstreɪʃən/", "명사", "시위, 시연", "Thousands joined the demonstration.", "수천 명이 시위에 참여했다."),
    "analyst":       ("/ˈænəlɪst/", "명사", "분석가", "The analyst predicted growth.", "분석가가 성장을 예측했다."),
    "platform":      ("/ˈplætfɔːrm/", "명사", "플랫폼, 단상", "The train is at platform 3.", "기차는 3번 플랫폼에 있다."),
    "steel":         ("/stiːl/", "명사", "강철", "The bridge is made of steel.", "다리는 강철로 만들어졌다."),
    "cake":          ("/keɪk/", "명사", "케이크", "She baked a birthday cake.", "그녀가 생일 케이크를 구웠다."),
    "transform":     ("/trænsˈfɔːrm/", "동사", "변화시키다, 변환하다", "Technology transformed our lives.", "기술이 우리 삶을 변화시켰다."),
    "wound":         ("/wuːnd/", "명사", "부상, 상처", "The wound needs treatment.", "상처를 치료해야 한다."),
    "restriction":   ("/rɪˈstrɪkʃən/", "명사", "제한, 규제", "Travel restrictions are lifted.", "여행 제한이 해제됐다."),
    "foundation":    ("/faʊnˈdeɪʃən/", "명사", "토대, 재단", "Build a strong foundation.", "강한 토대를 만드세요."),
    "designer":      ("/dɪˈzaɪnər/", "명사", "디자이너", "She is a fashion designer.", "그녀는 패션 디자이너이다."),
    "strain":        ("/streɪn/", "명사", "긴장, 압박", "The work caused mental strain.", "일이 정신적 압박을 유발했다."),
    "innovation":    ("/ˌɪnəˈveɪʃən/", "명사", "혁신", "Innovation drives progress.", "혁신이 발전을 이끈다."),
    "album":         ("/ˈælbəm/", "명사", "앨범", "The singer released a new album.", "가수가 새 앨범을 발매했다."),
    "singer":        ("/ˈsɪŋər/", "명사", "가수", "She is a talented singer.", "그녀는 재능 있는 가수이다."),
    "trail":         ("/treɪl/", "명사", "오솔길, 흔적", "Follow the hiking trail.", "등산로를 따라가세요."),
    "trap":          ("/træp/", "명사", "함정, 덫", "Don't fall into the trap.", "함정에 빠지지 마세요."),
    "loose":         ("/luːs/", "형용사", "느슨한, 헐렁한", "The bolt is loose.", "볼트가 느슨하다."),
    "extension":     ("/ɪkˈstɛnʃən/", "명사", "연장, 확장", "Request a deadline extension.", "마감 연장을 요청하세요."),
    "wealth":        ("/wɛlθ/", "명사", "부, 재산", "He inherited great wealth.", "그는 큰 재산을 물려받았다."),
    "gradually":     ("/ˈɡrædʒuəli/", "부사", "점진적으로, 서서히", "The pain gradually faded.", "통증이 서서히 사라졌다."),
    "tank":          ("/tæŋk/", "명사", "탱크, 저장 탱크", "The fuel tank is empty.", "연료 탱크가 비었다."),
    "evil":          ("/ˈiːvəl/", "형용사", "악한, 나쁜", "Fight against evil.", "악에 맞서 싸워라."),
    "remarkable":    ("/rɪˈmɑːrkəbəl/", "형용사", "놀라운, 주목할 만한", "She had a remarkable career.", "그녀는 놀라운 경력을 가졌다."),
    "tune":          ("/tjuːn/", "명사", "곡, 선율", "Hum a familiar tune.", "친숙한 곡을 흥얼거리세요."),
    "grass":         ("/ɡrɑːs/", "명사", "풀, 잔디", "Don't walk on the grass.", "잔디를 밟지 마세요."),
    "invitation":    ("/ˌɪnvɪˈteɪʃən/", "명사", "초대, 초청", "I received a wedding invitation.", "결혼식 초대를 받았다."),
    "transition":    ("/trænˈzɪʃən/", "명사", "전환, 이행", "The transition was smooth.", "전환이 순조로웠다."),
    "frighten":      ("/ˈfraɪtən/", "동사", "무섭게 하다, 겁주다", "Don't frighten the animals.", "동물들을 겁주지 마세요."),
    "bid":           ("/bɪd/", "동사", "입찰하다, 제시하다", "We bid for the contract.", "우리는 계약에 입찰했다."),
    "breed":         ("/briːd/", "동사", "번식하다, 기르다", "They breed horses.", "그들은 말을 사육한다."),
    "extraordinary": ("/ɪkˈstrɔːrdɪnəri/", "형용사", "비범한, 놀라운", "She has extraordinary talent.", "그녀는 비범한 재능을 가지고 있다."),
    "brilliant":     ("/ˈbrɪljənt/", "형용사", "훌륭한, 눈부신", "That is a brilliant idea.", "그것은 훌륭한 아이디어이다."),
    "adviser":       ("/ədˈvaɪzər/", "명사", "조언자, 고문", "He is a financial adviser.", "그는 재정 고문이다."),
    "stem":          ("/stɛm/", "명사", "줄기, 근원", "The stem of the plant is weak.", "식물의 줄기가 약하다."),
    "reverse":       ("/rɪˈvɜːrs/", "동사", "뒤집다, 후진하다", "Reverse the car slowly.", "천천히 후진하세요."),
    "mode":          ("/moʊd/", "명사", "방식, 모드", "Switch to silent mode.", "무음 모드로 바꾸세요."),
    "mirror":        ("/ˈmɪrər/", "명사", "거울", "Look in the mirror.", "거울을 보세요."),
    "awful":         ("/ˈɔːfəl/", "형용사", "끔찍한, 형편없는", "The weather was awful.", "날씨가 끔찍했다."),
    "pose":          ("/poʊz/", "동사", "자세를 취하다, 제기하다", "This poses a serious risk.", "이것은 심각한 위험을 제기한다."),
    "adjust":        ("/əˈdʒʌst/", "동사", "조정하다, 적응하다", "Adjust the temperature.", "온도를 조정하세요."),
    "creative":      ("/kriˈeɪtɪv/", "형용사", "창의적인", "She is a creative thinker.", "그녀는 창의적인 사상가이다."),
    "nowadays":      ("/ˈnaʊədeɪz/", "부사", "요즘, 현재", "Nowadays everyone uses smartphones.", "요즘 모두가 스마트폰을 사용한다."),
    "poem":          ("/ˈpoʊɪm/", "명사", "시", "She wrote a beautiful poem.", "그녀가 아름다운 시를 썼다."),
    "agricultural":  ("/ˌæɡrɪˈkʌltʃərəl/", "형용사", "농업의", "Agricultural land is decreasing.", "농업 토지가 감소하고 있다."),
    "competitor":    ("/kəmˈpɛtɪtər/", "명사", "경쟁자", "We beat our competitors.", "우리는 경쟁자들을 이겼다."),
    "alcohol":       ("/ˈælkəhɒl/", "명사", "알코올, 술", "Avoid alcohol before surgery.", "수술 전 술을 삼가세요."),
    "festival":      ("/ˈfɛstɪvəl/", "명사", "축제", "The music festival was amazing.", "음악 축제가 놀라웠다."),
    "vegetable":     ("/ˈvɛdʒɪtəbəl/", "명사", "채소, 야채", "Eat more vegetables.", "채소를 더 많이 드세요."),
    "van":           ("/væn/", "명사", "밴, 승합차", "They moved in a van.", "그들은 밴으로 이사했다."),
    "confident":     ("/ˈkɒnfɪdənt/", "형용사", "자신감 있는", "Be confident in yourself.", "자신을 믿으세요."),
    "planet":        ("/ˈplænɪt/", "명사", "행성", "Earth is a unique planet.", "지구는 독특한 행성이다."),
    "curve":         ("/kɜːrv/", "명사", "곡선, 커브", "The road has a sharp curve.", "도로에 급커브가 있다."),
    "knee":          ("/niː/", "명사", "무릎", "He injured his knee.", "그는 무릎을 다쳤다."),
    "overcome":      ("/ˌoʊvərˈkʌm/", "동사", "극복하다", "We can overcome any challenge.", "우리는 어떤 도전도 극복할 수 있다."),
    "web":           ("/wɛb/", "명사", "웹, 거미줄", "Search the web for information.", "웹에서 정보를 검색하세요."),
    "depth":         ("/dɛpθ/", "명사", "깊이, 심도", "The depth of the lake is 30m.", "호수의 깊이는 30미터이다."),
    "entrance":      ("/ˈɛntrəns/", "명사", "입구, 입장", "Use the main entrance.", "정문을 이용하세요."),
    "log":           ("/lɒɡ/", "명사", "통나무, 기록", "Check the activity log.", "활동 기록을 확인하세요."),
    "giant":         ("/ˈdʒaɪənt/", "형용사", "거대한", "A giant corporation bought them.", "거대 기업이 그들을 인수했다."),
    "god":           ("/ɡɒd/", "명사", "신", "They believe in one god.", "그들은 한 신을 믿는다."),
    "portion":       ("/ˈpɔːrʃən/", "명사", "부분, 몫", "Eat smaller portions.", "더 작은 양을 드세요."),
    "substance":     ("/ˈsʌbstəns/", "명사", "물질, 내용", "What is this substance?", "이것은 무슨 물질인가요?"),
    "extensive":     ("/ɪkˈstɛnsɪv/", "형용사", "광범위한, 대규모의", "She has extensive experience.", "그녀는 광범위한 경험이 있다."),
    "interpret":     ("/ɪnˈtɜːrprɪt/", "동사", "해석하다, 통역하다", "How do you interpret this?", "이것을 어떻게 해석하나요?"),
    "independence":  ("/ˌɪndɪˈpɛndəns/", "명사", "독립", "They celebrated independence.", "그들은 독립을 축하했다."),
    "sugar":         ("/ˈʃʊɡər/", "명사", "설탕", "Add a teaspoon of sugar.", "설탕 한 티스푼을 넣으세요."),
    "inner":         ("/ˈɪnər/", "형용사", "내부의, 마음속의", "Find your inner peace.", "내면의 평화를 찾으세요."),
    "harm":          ("/hɑːrm/", "명사", "해, 피해", "Do no harm.", "해를 끼치지 마세요."),
    "consult":       ("/kənˈsʌlt/", "동사", "상담하다, 참고하다", "Consult a doctor.", "의사에게 상담하세요."),
    "pink":          ("/pɪŋk/", "명사", "분홍색", "She wore a pink dress.", "그녀는 분홍 드레스를 입었다."),
    "shadow":        ("/ˈʃædoʊ/", "명사", "그림자", "A shadow fell over the room.", "방에 그림자가 드리웠다."),
    "strip":         ("/strɪp/", "동사", "벗기다, 제거하다", "Strip the old paint first.", "먼저 오래된 페인트를 벗겨내세요."),
    "smooth":        ("/smuːð/", "형용사", "매끄러운, 순조로운", "The ride was smooth.", "주행이 순조로웠다."),
    "intervention":  ("/ˌɪntərˈvɛnʃən/", "명사", "개입, 중재", "Early intervention is important.", "조기 개입이 중요하다."),
    "impress":       ("/ɪmˈprɛs/", "동사", "감동을 주다, 인상을 주다", "She impressed everyone.", "그녀가 모두에게 감동을 줬다."),
    "exam":          ("/ɪɡˈzæm/", "명사", "시험", "The exam is tomorrow.", "시험은 내일이다."),
    "vice":          ("/vaɪs/", "명사", "악덕, 부통령", "Gambling is a vice.", "도박은 악덕이다."),
    "radical":       ("/ˈrædɪkəl/", "형용사", "급진적인, 근본적인", "They proposed radical changes.", "그들은 급진적인 변화를 제안했다."),
    "similarly":     ("/ˈsɪmɪlərli/", "부사", "비슷하게, 마찬가지로", "Similarly, this applies here.", "마찬가지로, 이것도 여기 적용된다."),
    "behave":        ("/bɪˈheɪv/", "동사", "행동하다, 처신하다", "Behave yourself in class.", "수업 시간에 바르게 행동하세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT8:
                    pron, pos, meaning, ex_en, ex_ko = DICT8[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more8.py ===\n")
    patch_files()
