#!/usr/bin/env python3
"""Second-pass fill: covers freq-L2 (157 words), freq-L3 (top words), toeic, business, academic fallbacks."""
import json, glob, os

# word -> (pronunciation, partOfSpeech, meaning, exampleEn, exampleKo)
DICT2 = {
    # =========================================================
    # freq-L2 fallback words (157)
    # =========================================================
    "minute":      ("/ˈmɪnɪt/", "명사", "분, 잠깐", "Wait a minute, please.", "잠깐만 기다려 주세요."),
    "food":        ("/fuːd/", "명사", "음식, 식품", "This food is delicious.", "이 음식은 맛있어요."),
    "future":      ("/ˈfjuːtʃər/", "명사", "미래, 장래", "We should plan for the future.", "우리는 미래를 위해 계획해야 합니다."),
    "either":      ("/ˈiːðər/", "부사", "어느 쪽이든, 역시", "Either option works for me.", "어느 쪽이든 저에겐 괜찮습니다."),
    "ago":         ("/əˈɡoʊ/", "부사", "전에, 이전에", "He left two hours ago.", "그는 두 시간 전에 떠났습니다."),
    "per":         ("/pɜːr/", "전치사", "~마다, ~당", "It costs ten dollars per hour.", "시간당 10달러입니다."),
    "remain":      ("/rɪˈmeɪn/", "동사", "남다, 계속 ~이다", "Please remain seated.", "앉아 계세요."),
    "top":         ("/tɒp/", "명사", "꼭대기, 최고", "She reached the top of the mountain.", "그녀는 산 꼭대기에 올랐습니다."),
    "among":       ("/əˈmʌŋ/", "전치사", "~사이에, ~중에서", "He is popular among his classmates.", "그는 반 친구들 사이에서 인기가 있습니다."),
    "win":         ("/wɪn/", "동사", "이기다, 우승하다", "Our team won the championship.", "우리 팀이 챔피언십에서 우승했습니다."),
    "color":       ("/ˈkʌlər/", "명사", "색, 색깔", "What color is your car?", "당신의 자동차는 무슨 색인가요?"),
    "involve":     ("/ɪnˈvɒlv/", "동사", "포함하다, 수반하다", "The project involves many people.", "이 프로젝트는 많은 사람들이 관여합니다."),
    "period":      ("/ˈpɪəriəd/", "명사", "기간, 시기, 마침표", "This period of history is important.", "역사의 이 시기는 중요합니다."),
    "note":        ("/noʊt/", "명사", "메모, 노트", "Please take note of this.", "이것을 메모해 두세요."),
    "history":     ("/ˈhɪstəri/", "명사", "역사", "She studied history at university.", "그녀는 대학에서 역사를 공부했습니다."),
    "along":       ("/əˈlɒŋ/", "전치사", "~을 따라, 함께", "Walk along the river.", "강을 따라 걸으세요."),
    "sound":       ("/saʊnd/", "명사", "소리, 음", "I heard a strange sound.", "이상한 소리를 들었습니다."),
    "music":       ("/ˈmjuːzɪk/", "명사", "음악", "She loves listening to music.", "그녀는 음악 듣는 것을 좋아합니다."),
    "game":        ("/ɡeɪm/", "명사", "게임, 경기", "Let's play a game.", "게임을 합시다."),
    "political":   ("/pəˈlɪtɪkəl/", "형용사", "정치적인", "This is a political issue.", "이것은 정치적인 문제입니다."),
    "sale":        ("/seɪl/", "명사", "판매, 세일", "Everything is on sale today.", "오늘은 모든 것이 세일 중입니다."),
    "policy":      ("/ˈpɒləsi/", "명사", "정책, 방침", "The company has a strict policy.", "그 회사는 엄격한 정책을 가지고 있습니다."),
    "further":     ("/ˈfɜːrðər/", "부사", "더, 더 멀리", "We need to discuss this further.", "이에 대해 더 논의해야 합니다."),
    "appear":      ("/əˈpɪər/", "동사", "나타나다, ~처럼 보이다", "She appeared to be tired.", "그녀는 피곤해 보였습니다."),
    "toward":      ("/tɔːrd/", "전치사", "~쪽으로, ~를 향해", "He walked toward the door.", "그는 문 쪽으로 걸어갔습니다."),
    "team":        ("/tiːm/", "명사", "팀, 집단", "Our team works well together.", "우리 팀은 함께 잘 일합니다."),
    "easy":        ("/ˈiːzi/", "형용사", "쉬운, 편한", "This exercise is easy.", "이 운동은 쉽습니다."),
    "individual":  ("/ˌɪndɪˈvɪdʒuəl/", "명사", "개인, 개체", "Each individual is unique.", "각 개인은 독특합니다."),
    "black":       ("/blæk/", "형용사", "검은, 흑색의", "She wore a black dress.", "그녀는 검은 드레스를 입었습니다."),
    "sense":       ("/sɛns/", "명사", "감각, 의미", "This doesn't make sense.", "이것은 이해가 되지 않습니다."),
    "perhaps":     ("/pərˈhæps/", "부사", "아마도, 어쩌면", "Perhaps we can meet tomorrow.", "아마도 내일 만날 수 있을 것입니다."),
    "rule":        ("/ruːl/", "명사", "규칙, 규정", "Please follow the rules.", "규칙을 따라 주세요."),
    "produce":     ("/prəˈdjuːs/", "동사", "생산하다, 만들다", "This factory produces cars.", "이 공장은 자동차를 생산합니다."),
    "sell":        ("/sɛl/", "동사", "팔다, 판매하다", "They sell organic vegetables.", "그들은 유기농 채소를 팝니다."),
    "short":       ("/ʃɔːrt/", "형용사", "짧은, 키가 작은", "The meeting was short.", "회의가 짧았습니다."),
    "agree":       ("/əˈɡriː/", "동사", "동의하다, 찬성하다", "I agree with your opinion.", "저는 당신의 의견에 동의합니다."),
    "law":         ("/lɔː/", "명사", "법, 법률", "Everyone must obey the law.", "모든 사람은 법을 지켜야 합니다."),
    "everything":  ("/ˈɛvriθɪŋ/", "대명사", "모든 것", "Everything is ready.", "모든 것이 준비되었습니다."),
    "paper":       ("/ˈpeɪpər/", "명사", "종이, 논문", "Please write on this paper.", "이 종이에 써 주세요."),
    "human":       ("/ˈhjuːmən/", "명사", "인간, 사람", "Humans are social creatures.", "인간은 사회적 동물입니다."),
    "computer":    ("/kəmˈpjuːtər/", "명사", "컴퓨터", "I use a computer every day.", "저는 매일 컴퓨터를 사용합니다."),
    "staff":       ("/stæf/", "명사", "직원, 스태프", "The staff is very helpful.", "직원들이 매우 친절합니다."),
    "activity":    ("/ækˈtɪvɪti/", "명사", "활동, 행동", "Physical activity is important.", "신체 활동이 중요합니다."),
    "film":        ("/fɪlm/", "명사", "영화, 필름", "Have you seen this film?", "이 영화를 보셨나요?"),
    "war":         ("/wɔːr/", "명사", "전쟁", "War causes great suffering.", "전쟁은 큰 고통을 야기합니다."),
    "shop":        ("/ʃɒp/", "명사", "가게, 상점", "There's a nice coffee shop nearby.", "근처에 좋은 커피숍이 있습니다."),
    "above":       ("/əˈbʌv/", "전치사", "위에, ~이상으로", "The picture is above the desk.", "그림은 책상 위에 있습니다."),
    "design":      ("/dɪˈzaɪn/", "명사", "디자인, 설계", "I love the design of this product.", "저는 이 제품의 디자인이 마음에 듭니다."),
    "event":       ("/ɪˈvɛnt/", "명사", "행사, 사건", "The event starts at 7 PM.", "행사는 오후 7시에 시작합니다."),
    "special":     ("/ˈspɛʃəl/", "형용사", "특별한, 특수한", "Today is a special day.", "오늘은 특별한 날입니다."),
    "sometimes":   ("/ˈsʌmtaɪmz/", "부사", "때때로, 가끔", "I sometimes go for a walk.", "저는 때때로 산책을 갑니다."),
    "condition":   ("/kənˈdɪʃən/", "명사", "상태, 조건", "The car is in good condition.", "자동차가 좋은 상태입니다."),
    "choose":      ("/tʃuːz/", "동사", "선택하다, 고르다", "You can choose any color.", "어떤 색이든 선택할 수 있습니다."),
    "father":      ("/ˈfɑːðər/", "명사", "아버지, 아빠", "My father works hard.", "아버지는 열심히 일하십니다."),
    "decision":    ("/dɪˈsɪʒən/", "명사", "결정, 결심", "This is an important decision.", "이것은 중요한 결정입니다."),
    "table":       ("/ˈteɪbəl/", "명사", "테이블, 식탁", "Please set the table for dinner.", "저녁 식사를 위해 식탁을 준비해 주세요."),
    "certain":     ("/ˈsɜːrtən/", "형용사", "확실한, 특정한", "Are you certain about this?", "이것이 확실한가요?"),
    "forward":     ("/ˈfɔːrwərd/", "부사", "앞으로, 전방으로", "Please move forward.", "앞으로 나아가세요."),
    "main":        ("/meɪn/", "형용사", "주요한, 주된", "What is the main point?", "주요 요점이 무엇인가요?"),
    "die":         ("/daɪ/", "동사", "죽다, 사망하다", "All living things eventually die.", "모든 생명체는 결국 죽습니다."),
    "bear":        ("/bɛər/", "동사", "견디다, 참다", "I can't bear the heat.", "저는 더위를 견딜 수 없습니다."),
    "cut":         ("/kʌt/", "동사", "자르다, 줄이다", "Please cut the paper in half.", "종이를 반으로 잘라 주세요."),
    "describe":    ("/dɪˈskraɪb/", "동사", "묘사하다, 설명하다", "Can you describe what happened?", "무슨 일이 있었는지 묘사할 수 있나요?"),
    "himself":     ("/hɪmˈsɛlf/", "대명사", "그 자신, 그 스스로", "He did it himself.", "그는 혼자서 했습니다."),
    "especially":  ("/ɪˈspɛʃəli/", "부사", "특히, 특별히", "I love nature, especially the mountains.", "저는 자연, 특히 산을 좋아합니다."),
    "strong":      ("/strɒŋ/", "형용사", "강한, 튼튼한", "She has a strong will.", "그녀는 강한 의지를 가지고 있습니다."),
    "rise":        ("/raɪz/", "동사", "오르다, 상승하다", "Prices continue to rise.", "물가가 계속 오르고 있습니다."),
    "girl":        ("/ɡɜːrl/", "명사", "소녀, 여자아이", "The girl is reading a book.", "소녀가 책을 읽고 있습니다."),
    "maybe":       ("/ˈmeɪbi/", "부사", "아마도, 어쩌면", "Maybe we should try again.", "아마 우리는 다시 시도해야 할 것 같습니다."),
    "community":   ("/kəˈmjuːnɪti/", "명사", "공동체, 지역사회", "Our community works together.", "우리 공동체는 함께 일합니다."),
    "else":        ("/ɛls/", "부사", "그 밖에, 다른", "What else do you need?", "그 밖에 무엇이 필요한가요?"),
    "particular":  ("/pərˈtɪkjələr/", "형용사", "특정한, 특별한", "Do you have a particular preference?", "특별한 선호가 있나요?"),
    "role":        ("/roʊl/", "명사", "역할, 임무", "Everyone has an important role.", "모든 사람은 중요한 역할을 가지고 있습니다."),
    "join":        ("/dʒɔɪn/", "동사", "참여하다, 합류하다", "Would you like to join us?", "우리와 함께 하시겠어요?"),
    "difficult":   ("/ˈdɪfɪkəlt/", "형용사", "어려운, 힘든", "This problem is difficult.", "이 문제는 어렵습니다."),
    "please":      ("/pliːz/", "부사", "제발, 부탁합니다", "Please sit down.", "앉아 주세요."),
    "detail":      ("/ˈdiːteɪl/", "명사", "세부사항, 상세", "Please check the details.", "세부사항을 확인해 주세요."),
    "difference":  ("/ˈdɪfərəns/", "명사", "차이, 다름", "What is the difference?", "차이가 무엇인가요?"),
    "action":      ("/ˈækʃən/", "명사", "행동, 조치", "We need to take action.", "우리는 조치를 취해야 합니다."),
    "health":      ("/hɛlθ/", "명사", "건강", "Good health is important.", "좋은 건강이 중요합니다."),
    "eat":         ("/iːt/", "동사", "먹다", "I usually eat breakfast at 7.", "저는 보통 7시에 아침을 먹습니다."),
    "step":        ("/stɛp/", "명사", "걸음, 단계", "Take it one step at a time.", "한 번에 한 단계씩 해 나가세요."),
    "true":        ("/truː/", "형용사", "사실인, 진실한", "Is that true?", "그것이 사실인가요?"),
    "phone":       ("/foʊn/", "명사", "전화, 전화기", "My phone is out of battery.", "내 전화기 배터리가 다 됐습니다."),
    "themselves":  ("/ðəmˈsɛlvz/", "대명사", "그들 자신, 그들 스스로", "They did everything themselves.", "그들은 모든 것을 혼자 했습니다."),
    "draw":        ("/drɔː/", "동사", "그리다, 끌다", "She loves to draw.", "그녀는 그림 그리기를 좋아합니다."),
    "white":       ("/waɪt/", "형용사", "흰, 백색의", "He wore a white shirt.", "그는 흰 셔츠를 입었습니다."),
    "date":        ("/deɪt/", "명사", "날짜, 데이트", "What is today's date?", "오늘 날짜가 어떻게 되나요?"),
    "practice":    ("/ˈpræktɪs/", "명사", "연습, 실습", "Practice makes perfect.", "연습이 완벽을 만든다."),
    "model":       ("/ˈmɒdəl/", "명사", "모델, 모형", "This is a new model.", "이것은 새 모델입니다."),
    "raise":       ("/reɪz/", "동사", "올리다, 기르다", "Please raise your hand.", "손을 들어 주세요."),
    "customer":    ("/ˈkʌstəmər/", "명사", "고객, 손님", "The customer is always right.", "고객은 항상 옳습니다."),
    "front":       ("/frʌnt/", "명사", "앞, 정면", "Please come to the front.", "앞으로 나와 주세요."),
    "explain":     ("/ɪkˈspleɪn/", "동사", "설명하다", "Can you explain this?", "이것을 설명해 줄 수 있나요?"),
    "outside":     ("/ˌaʊtˈsaɪd/", "부사", "밖에, 바깥에", "Let's go outside.", "밖에 나가자."),
    "behind":      ("/bɪˈhaɪnd/", "전치사", "뒤에, 뒤쪽에", "The car is behind the house.", "자동차가 집 뒤에 있습니다."),
    "economic":    ("/ˌiːkəˈnɒmɪk/", "형용사", "경제적인", "Economic growth is slowing.", "경제 성장이 둔화되고 있습니다."),
    "site":        ("/saɪt/", "명사", "장소, 사이트", "This is a good site for camping.", "이곳은 캠핑하기 좋은 장소입니다."),
    "teacher":     ("/ˈtiːtʃər/", "명사", "선생님, 교사", "My teacher is very kind.", "저의 선생님은 매우 친절합니다."),
    "charge":      ("/tʃɑːrdʒ/", "명사", "요금, 담당", "What is the charge for this?", "이것의 요금이 얼마인가요?"),
    "finally":     ("/ˈfaɪnəli/", "부사", "마침내, 드디어", "We finally reached our goal.", "우리는 마침내 목표에 도달했습니다."),
    "claim":       ("/kleɪm/", "동사", "주장하다, 청구하다", "He claims to be an expert.", "그는 전문가라고 주장합니다."),
    "relationship":("/rɪˈleɪʃənʃɪp/", "명사", "관계, 사이", "They have a good relationship.", "그들은 좋은 관계를 가지고 있습니다."),
    "enjoy":       ("/ɪnˈdʒɔɪ/", "동사", "즐기다, 즐거워하다", "I enjoy reading books.", "저는 책 읽는 것을 즐깁니다."),
    "death":       ("/dɛθ/", "명사", "죽음, 사망", "He was sad about the death of his pet.", "그는 반려동물의 죽음에 슬퍼했습니다."),
    "nice":        ("/naɪs/", "형용사", "좋은, 멋진", "What a nice day!", "정말 좋은 날씨네요!"),
    "amount":      ("/əˈmaʊnt/", "명사", "양, 금액", "What is the total amount?", "총 금액이 얼마인가요?"),
    "improve":     ("/ɪmˈpruːv/", "동사", "개선하다, 향상시키다", "We need to improve our service.", "우리는 서비스를 개선해야 합니다."),
    "picture":     ("/ˈpɪktʃər/", "명사", "그림, 사진", "I took a picture of the sunset.", "일몰 사진을 찍었습니다."),
    "boy":         ("/bɔɪ/", "명사", "소년, 남자아이", "The boy is playing soccer.", "소년이 축구를 하고 있습니다."),
    "regard":      ("/rɪˈɡɑːrd/", "동사", "여기다, 간주하다", "I regard you as a friend.", "저는 당신을 친구로 여깁니다."),
    "organization":("/ˌɔːrɡənɪˈzeɪʃən/", "명사", "조직, 단체", "She works for a non-profit organization.", "그녀는 비영리 단체에서 일합니다."),
    "happy":       ("/ˈhæpi/", "형용사", "행복한, 기쁜", "Are you happy with the result?", "결과에 만족하시나요?"),
    "couple":      ("/ˈkʌpəl/", "명사", "두 개, 커플", "I'll be back in a couple of minutes.", "몇 분 후에 돌아오겠습니다."),
    "act":         ("/ækt/", "동사", "행동하다, 연기하다", "We must act quickly.", "우리는 빨리 행동해야 합니다."),
    "range":       ("/reɪndʒ/", "명사", "범위, 폭", "We offer a wide range of products.", "저희는 다양한 제품을 제공합니다."),
    "project":     ("/ˈprɒdʒɛkt/", "명사", "프로젝트, 계획", "This project is very important.", "이 프로젝트는 매우 중요합니다."),
    "round":       ("/raʊnd/", "형용사", "둥근, 원형의", "The table is round.", "테이블이 둥급니다."),
    "opportunity": ("/ˌɒpərˈtjuːnɪti/", "명사", "기회", "This is a great opportunity.", "이것은 좋은 기회입니다."),
    "accord":      ("/əˈkɔːrd/", "명사", "합의, 일치", "They reached an accord.", "그들은 합의에 도달했습니다."),
    "list":        ("/lɪst/", "명사", "목록, 리스트", "I made a shopping list.", "저는 쇼핑 목록을 만들었습니다."),
    "wish":        ("/wɪʃ/", "동사", "바라다, 원하다", "I wish you good luck.", "행운을 빕니다."),
    "therefore":   ("/ˈðɛrfɔːr/", "부사", "그러므로, 따라서", "He was tired, therefore he rested.", "그는 피곤했으므로 쉬었습니다."),
    "wear":        ("/wɛər/", "동사", "입다, 착용하다", "What should I wear today?", "오늘 무엇을 입을까요?"),
    "rest":        ("/rɛst/", "명사", "휴식, 나머지", "You should get some rest.", "좀 쉬어야 합니다."),
    "kid":         ("/kɪd/", "명사", "아이, 어린이", "The kids are playing outside.", "아이들이 밖에서 놀고 있습니다."),
    "industry":    ("/ˈɪndəstri/", "명사", "산업, 업계", "The technology industry is growing.", "기술 산업이 성장하고 있습니다."),
    "education":   ("/ˌɛdʒʊˈkeɪʃən/", "명사", "교육", "Education is the key to success.", "교육은 성공의 열쇠입니다."),
    "measure":     ("/ˈmɛʒər/", "동사", "측정하다, 재다", "Please measure the room.", "방을 재어 주세요."),
    "kill":        ("/kɪl/", "동사", "죽이다", "The cold weather killed the plants.", "추운 날씨가 식물을 죽였습니다."),
    "serve":       ("/sɜːrv/", "동사", "제공하다, 봉사하다", "They serve excellent food.", "그들은 훌륭한 음식을 제공합니다."),
    "likely":      ("/ˈlaɪkli/", "형용사", "~할 것 같은, 가능성 있는", "It's likely to rain today.", "오늘 비가 올 것 같습니다."),
    "certainly":   ("/ˈsɜːrtənli/", "부사", "확실히, 분명히", "This is certainly the best option.", "이것이 확실히 최선의 선택입니다."),
    "national":    ("/ˈnæʃənəl/", "형용사", "국가의, 전국적인", "Tomorrow is a national holiday.", "내일은 국가 공휴일입니다."),
    "itself":      ("/ɪtˈsɛlf/", "대명사", "그것 자체, 그 자신", "The problem solved itself.", "문제가 저절로 해결되었습니다."),
    "teach":       ("/tiːtʃ/", "동사", "가르치다, 교육하다", "She teaches English at school.", "그녀는 학교에서 영어를 가르칩니다."),
    "field":       ("/fiːld/", "명사", "분야, 들판", "She is an expert in her field.", "그녀는 자신의 분야 전문가입니다."),
    "security":    ("/sɪˈkjʊərɪti/", "명사", "보안, 안전", "Security is our top priority.", "보안이 우리의 최우선 사항입니다."),
    "benefit":     ("/ˈbɛnɪfɪt/", "명사", "혜택, 이익", "Exercise has many health benefits.", "운동에는 많은 건강 상의 이점이 있습니다."),
    "trade":       ("/treɪd/", "명사", "무역, 거래", "International trade is important.", "국제 무역은 중요합니다."),
    "risk":        ("/rɪsk/", "명사", "위험, 리스크", "There is a risk of failure.", "실패의 위험이 있습니다."),
    "news":        ("/njuːz/", "명사", "뉴스, 소식", "Have you heard the news?", "뉴스를 들었나요?"),
    "vote":        ("/voʊt/", "동사", "투표하다", "Please vote in the election.", "선거에서 투표해 주세요."),
    "percent":     ("/pərˈsɛnt/", "명사", "퍼센트, 백분율", "Prices went up by 5 percent.", "가격이 5퍼센트 올랐습니다."),
    "focus":       ("/ˈfoʊkəs/", "동사", "집중하다, 초점을 맞추다", "Please focus on the task.", "업무에 집중해 주세요."),
    "stage":       ("/steɪdʒ/", "명사", "단계, 무대", "We are in the final stage.", "우리는 마지막 단계에 있습니다."),
    "space":       ("/speɪs/", "명사", "공간, 우주", "We need more space.", "우리는 더 많은 공간이 필요합니다."),
    "instead":     ("/ɪnˈstɛd/", "부사", "대신에", "Let's go by train instead.", "대신 기차로 가자."),
    "realize":     ("/ˈriːəlaɪz/", "동사", "깨닫다, 실현하다", "I didn't realize it was so late.", "이렇게 늦은 줄 몰랐습니다."),
    "usually":     ("/ˈjuːʒuəli/", "부사", "보통, 대개", "I usually wake up at 6 AM.", "저는 보통 오전 6시에 일어납니다."),
    "data":        ("/ˈdeɪtə/", "명사", "데이터, 자료", "The data shows an increase.", "데이터는 증가를 보여줍니다."),
    "single":      ("/ˈsɪŋɡəl/", "형용사", "단 하나의, 독신의", "Not a single word was wrong.", "단 한 단어도 틀리지 않았습니다."),
    "address":     ("/əˈdrɛs/", "명사", "주소, 연설", "Please write your address here.", "여기에 주소를 써 주세요."),
    "performance": ("/pərˈfɔːrməns/", "명사", "성과, 공연", "His performance was excellent.", "그의 성과는 훌륭했습니다."),
    "chance":      ("/tʃæns/", "명사", "기회, 가능성", "Give me a chance to explain.", "설명할 기회를 주세요."),
    "accept":      ("/əkˈsɛpt/", "동사", "받아들이다, 수락하다", "I accept your apology.", "당신의 사과를 받아들이겠습니다."),
    "society":     ("/səˈsaɪəti/", "명사", "사회, 단체", "We live in a complex society.", "우리는 복잡한 사회에서 삽니다."),
    # =========================================================
    # freq-L3 fallback words (top 100)
    # =========================================================
    "material":    ("/məˈtɪəriəl/", "명사", "재료, 자료", "What material is this made of?", "이것은 무엇으로 만들어졌나요?"),
    "limit":       ("/ˈlɪmɪt/", "명사", "한계, 제한", "There is a time limit.", "시간 제한이 있습니다."),
    "listen":      ("/ˈlɪsən/", "동사", "듣다, 경청하다", "Please listen carefully.", "주의 깊게 들어 주세요."),
    "due":         ("/djuː/", "형용사", "~할 예정인, 지불 기한이 된", "The report is due tomorrow.", "보고서 제출 기한이 내일입니다."),
    "wrong":       ("/rɒŋ/", "형용사", "잘못된, 틀린", "Sorry, I was wrong.", "죄송합니다, 제가 틀렸습니다."),
    "foot":        ("/fʊt/", "명사", "발, 피트(단위)", "I hurt my foot.", "발을 다쳤습니다."),
    "attention":   ("/əˈtɛnʃən/", "명사", "주의, 관심", "Please pay attention.", "주의를 기울여 주세요."),
    "upon":        ("/əˈpɒn/", "전치사", "~위에, ~에 따라", "Once upon a time...", "옛날 옛적에..."),
    "complete":    ("/kəmˈpliːt/", "동사", "완료하다, 완성하다", "Please complete the form.", "양식을 작성해 주세요."),
    "lie":         ("/laɪ/", "동사", "눕다; 거짓말하다", "Don't lie to me.", "나에게 거짓말하지 마세요."),
    "pick":        ("/pɪk/", "동사", "고르다, 줍다", "Pick the best option.", "최선의 선택지를 고르세요."),
    "reduce":      ("/rɪˈdjuːs/", "동사", "줄이다, 감소시키다", "We need to reduce costs.", "비용을 줄여야 합니다."),
    "personal":    ("/ˈpɜːrsənəl/", "형용사", "개인적인, 사적인", "This is a personal matter.", "이것은 개인적인 문제입니다."),
    "ground":      ("/ɡraʊnd/", "명사", "땅, 근거", "The ground is wet.", "땅이 젖어 있습니다."),
    "animal":      ("/ˈænɪməl/", "명사", "동물", "There are many animals in the zoo.", "동물원에는 많은 동물이 있습니다."),
    "arrive":      ("/əˈraɪv/", "동사", "도착하다", "What time will you arrive?", "몇 시에 도착할 예정인가요?"),
    "patient":     ("/ˈpeɪʃənt/", "형용사", "인내심 있는", "Please be patient.", "참을성을 가져 주세요."),
    "century":     ("/ˈsɛntʃəri/", "명사", "세기, 100년", "We are in the 21st century.", "우리는 21세기에 살고 있습니다."),
    "evidence":    ("/ˈɛvɪdəns/", "명사", "증거, 근거", "There is strong evidence.", "강력한 증거가 있습니다."),
    "exist":       ("/ɪɡˈzɪst/", "동사", "존재하다", "Does life exist on other planets?", "다른 행성에 생명체가 존재할까요?"),
    "similar":     ("/ˈsɪmɪlər/", "형용사", "비슷한, 유사한", "These two are very similar.", "이 두 개는 매우 비슷합니다."),
    "fight":       ("/faɪt/", "동사", "싸우다, 투쟁하다", "We must fight for justice.", "우리는 정의를 위해 싸워야 합니다."),
    "leader":      ("/ˈliːdər/", "명사", "지도자, 리더", "She is a great leader.", "그녀는 훌륭한 지도자입니다."),
    "fine":        ("/faɪn/", "형용사", "좋은, 괜찮은", "I'm fine, thank you.", "저는 괜찮습니다, 감사합니다."),
    "former":      ("/ˈfɔːrmər/", "형용사", "전(前), 이전의", "He is the former president.", "그는 전 대통령입니다."),
    "contact":     ("/ˈkɒntækt/", "명사", "연락, 접촉", "Please contact me by email.", "이메일로 연락해 주세요."),
    "particularly":("/pərˈtɪkjələrli/", "부사", "특히, 각별히", "I particularly enjoy this.", "저는 이것을 특히 즐깁니다."),
    "wife":        ("/waɪf/", "명사", "아내, 부인", "His wife is a doctor.", "그의 아내는 의사입니다."),
    "sport":       ("/spɔːrt/", "명사", "스포츠, 운동", "What sport do you play?", "어떤 스포츠를 하시나요?"),
    "prepare":     ("/prɪˈpɛər/", "동사", "준비하다, 대비하다", "We need to prepare for the meeting.", "회의를 위해 준비해야 합니다."),
    "discuss":     ("/dɪˈskʌs/", "동사", "논의하다, 토론하다", "Let's discuss this tomorrow.", "내일 이것을 논의합시다."),
    "response":    ("/rɪˈspɒns/", "명사", "반응, 응답", "I'm waiting for a response.", "응답을 기다리고 있습니다."),
    "voice":       ("/vɔɪs/", "명사", "목소리, 의견", "She has a beautiful voice.", "그녀는 아름다운 목소리를 가지고 있습니다."),
    "piece":       ("/piːs/", "명사", "조각, 부분", "Can I have a piece of cake?", "케이크 한 조각 먹어도 될까요?"),
    "finish":      ("/ˈfɪnɪʃ/", "동사", "끝내다, 완료하다", "When will you finish the project?", "언제 프로젝트를 끝낼 예정인가요?"),
    "suppose":     ("/səˈpoʊz/", "동사", "생각하다, 추정하다", "I suppose you're right.", "당신이 옳다고 생각합니다."),
    "president":   ("/ˈprɛzɪdənt/", "명사", "대통령, 사장", "The president gave a speech.", "대통령이 연설을 했습니다."),
    "fire":        ("/faɪər/", "명사", "불, 화재", "There was a fire in the building.", "건물에 화재가 발생했습니다."),
    "compare":     ("/kəmˈpɛər/", "동사", "비교하다", "Let's compare the two options.", "두 가지 선택지를 비교해 봅시다."),
    "court":       ("/kɔːrt/", "명사", "법원, 코트", "The case went to court.", "사건이 법원으로 갔습니다."),
    "police":      ("/pəˈliːs/", "명사", "경찰", "Call the police!", "경찰을 불러요!"),
    "store":       ("/stɔːr/", "명사", "가게, 저장", "I need to go to the store.", "가게에 가야 합니다."),
    "poor":        ("/pɔːr/", "형용사", "가난한, 불쌍한", "She helps poor families.", "그녀는 가난한 가정을 돕습니다."),
    "knowledge":   ("/ˈnɒlɪdʒ/", "명사", "지식, 앎", "Knowledge is power.", "지식은 힘입니다."),
    "laugh":       ("/lɑːf/", "동사", "웃다, 웃음", "She laughed at his joke.", "그녀는 그의 농담에 웃었습니다."),
    "arm":         ("/ɑːrm/", "명사", "팔", "She broke her arm.", "그녀는 팔이 부러졌습니다."),
    "heart":       ("/hɑːrt/", "명사", "심장, 마음", "My heart beats fast.", "심장이 빨리 뜁니다."),
    "source":      ("/sɔːrs/", "명사", "출처, 원천", "What is your source?", "출처가 무엇인가요?"),
    "employee":    ("/ɪmˈplɔɪiː/", "명사", "직원, 종업원", "The employee was promoted.", "그 직원은 승진했습니다."),
    "manage":      ("/ˈmænɪdʒ/", "동사", "관리하다, 해내다", "She manages a large team.", "그녀는 큰 팀을 관리합니다."),
    "simply":      ("/ˈsɪmpli/", "부사", "단순히, 그냥", "Simply follow the instructions.", "그냥 지시를 따르세요."),
    "bank":        ("/bæŋk/", "명사", "은행, 둑", "The bank closes at 3 PM.", "은행은 오후 3시에 문을 닫습니다."),
    "firm":        ("/fɜːrm/", "명사", "회사, 사무소", "She works at a law firm.", "그녀는 법률 사무소에서 일합니다."),
    "cell":        ("/sɛl/", "명사", "세포, 감방", "The cell divides rapidly.", "세포가 빠르게 분열합니다."),
    "article":     ("/ˈɑːrtɪkəl/", "명사", "기사, 물건", "I read an interesting article.", "흥미로운 기사를 읽었습니다."),
    "fast":        ("/fɑːst/", "형용사", "빠른, 빨리", "She runs very fast.", "그녀는 매우 빠르게 달립니다."),
    "attack":      ("/əˈtæk/", "동사", "공격하다", "They plan to attack at dawn.", "그들은 새벽에 공격할 계획입니다."),
    "foreign":     ("/ˈfɒrɪn/", "형용사", "외국의, 이질적인", "I enjoy foreign food.", "저는 외국 음식을 즐깁니다."),
    "surprise":    ("/səˈpraɪz/", "명사", "놀라움, 깜짝 선물", "What a surprise!", "정말 놀랍네요!"),
    "factor":      ("/ˈfæktər/", "명사", "요인, 요소", "Many factors affect the result.", "많은 요소가 결과에 영향을 미칩니다."),
    "age":         ("/eɪdʒ/", "명사", "나이, 시대", "What is your age?", "나이가 어떻게 되시나요?"),
    "effect":      ("/ɪˈfɛkt/", "명사", "효과, 영향", "The medicine had a good effect.", "그 약이 좋은 효과를 냈습니다."),
    "below":       ("/bɪˈloʊ/", "전치사", "아래에, 이하의", "The temperature dropped below zero.", "기온이 영하로 떨어졌습니다."),
    "control":     ("/kənˈtroʊl/", "동사", "통제하다, 제어하다", "Please control your emotions.", "감정을 통제해 주세요."),
    "message":     ("/ˈmɛsɪdʒ/", "명사", "메시지, 전달", "Did you get my message?", "내 메시지를 받았나요?"),
    "hold":        ("/hoʊld/", "동사", "잡다, 유지하다", "Please hold the door.", "문을 잡아 주세요."),
    "exactly":     ("/ɪɡˈzæktli/", "부사", "정확히, 바로", "That's exactly what I meant.", "그것이 바로 제가 의미한 것입니다."),
    "clear":       ("/klɪər/", "형용사", "분명한, 맑은", "The instructions are clear.", "지시사항이 명확합니다."),
    "rather":      ("/ˈrɑːðər/", "부사", "오히려, 꽤", "I'd rather stay home.", "저는 집에 있는 게 낫겠습니다."),
    "view":        ("/vjuː/", "명사", "관점, 전망", "What is your view on this?", "이에 대한 당신의 관점은 무엇인가요?"),
    "together":    ("/təˈɡɛðər/", "부사", "함께, 같이", "Let's work together.", "함께 일합시다."),
    "concern":     ("/kənˈsɜːrn/", "명사", "걱정, 관심", "This is a matter of great concern.", "이것은 매우 걱정스러운 문제입니다."),
    "party":       ("/ˈpɑːrti/", "명사", "파티, 정당", "The party starts at 8.", "파티는 8시에 시작합니다."),
    "provide":     ("/prəˈvaɪd/", "동사", "제공하다, 공급하다", "We provide excellent service.", "저희는 우수한 서비스를 제공합니다."),
    "actually":    ("/ˈæktʃuəli/", "부사", "실제로, 사실은", "I actually enjoyed it.", "저는 실제로 즐겼습니다."),
    "charge":      ("/tʃɑːrdʒ/", "명사", "요금, 담당", "What is the charge for this?", "이것의 요금이 얼마인가요?"),
    "positive":    ("/ˈpɒzɪtɪv/", "형용사", "긍정적인, 양성의", "Stay positive!", "긍정적으로 생각하세요!"),
    "situation":   ("/ˌsɪtʃuˈeɪʃən/", "명사", "상황, 처지", "The situation is improving.", "상황이 나아지고 있습니다."),
    "standard":    ("/ˈstændərd/", "명사", "기준, 표준", "This meets the standard.", "이것은 기준을 충족합니다."),
    "prevent":     ("/prɪˈvɛnt/", "동사", "막다, 예방하다", "How can we prevent accidents?", "어떻게 사고를 예방할 수 있을까요?"),
    "approach":    ("/əˈproʊtʃ/", "명사", "접근법, 방법", "Let's try a new approach.", "새로운 접근법을 시도해 봅시다."),
    "report":      ("/rɪˈpɔːrt/", "명사", "보고서, 보도", "Please submit your report.", "보고서를 제출해 주세요."),
    "analysis":    ("/əˈnæləsɪs/", "명사", "분석", "The analysis shows positive results.", "분석 결과 긍정적인 결과가 나타납니다."),
    "increase":    ("/ɪnˈkriːs/", "동사", "증가하다, 늘리다", "Sales have increased this year.", "올해 매출이 증가했습니다."),
    "price":       ("/praɪs/", "명사", "가격, 요금", "The price is reasonable.", "가격이 합리적입니다."),
    "recently":    ("/ˈriːsəntli/", "부사", "최근에", "I recently moved here.", "저는 최근에 여기로 이사했습니다."),
    "describe":    ("/dɪˈskraɪb/", "동사", "묘사하다, 설명하다", "Can you describe what happened?", "무슨 일이 있었는지 묘사할 수 있나요?"),
    "necessary":   ("/ˈnɛsəsəri/", "형용사", "필요한, 필수적인", "Is this necessary?", "이것이 필요한가요?"),
    "development": ("/dɪˈvɛləpmənt/", "명사", "발전, 개발", "Economic development is key.", "경제 발전이 핵심입니다."),
    "effort":      ("/ˈɛfərt/", "명사", "노력, 수고", "Thank you for your effort.", "노력해 주셔서 감사합니다."),
    "various":     ("/ˈvɛəriəs/", "형용사", "다양한, 여러", "There are various options.", "다양한 선택지가 있습니다."),
    "impact":      ("/ˈɪmpækt/", "명사", "영향, 충격", "This has a big impact.", "이것은 큰 영향을 미칩니다."),
    "network":     ("/ˈnɛtwɜːrk/", "명사", "네트워크, 연결망", "We have a strong network.", "우리는 강력한 네트워크를 보유하고 있습니다."),
    "response":    ("/rɪˈspɒns/", "명사", "반응, 응답", "I'm waiting for a response.", "응답을 기다리고 있습니다."),
    "strategy":    ("/ˈstrætədʒi/", "명사", "전략, 방책", "We need a new strategy.", "새로운 전략이 필요합니다."),
    "technology":  ("/tɛkˈnɒlədʒi/", "명사", "기술, 테크놀로지", "Technology changes quickly.", "기술은 빠르게 변합니다."),
    "specific":    ("/spɪˈsɪfɪk/", "형용사", "특정한, 구체적인", "Can you be more specific?", "좀 더 구체적으로 말씀해 주시겠어요?"),
    "recently":    ("/ˈriːsəntli/", "부사", "최근에", "I recently moved here.", "저는 최근에 여기로 이사했습니다."),
    "opportunity": ("/ˌɒpərˈtjuːnɪti/", "명사", "기회", "This is a great opportunity.", "이것은 좋은 기회입니다."),
    # =========================================================
    # freq-L3 more words
    # =========================================================
    "serious":     ("/ˈsɪəriəs/", "형용사", "심각한, 진지한", "This is a serious problem.", "이것은 심각한 문제입니다."),
    "test":        ("/tɛst/", "명사", "시험, 검사", "I have a test tomorrow.", "내일 시험이 있습니다."),
    "appear":      ("/əˈpɪər/", "동사", "나타나다, 보이다", "A star appeared in the sky.", "하늘에 별이 나타났습니다."),
    "culture":     ("/ˈkʌltʃər/", "명사", "문화", "Korean culture is rich.", "한국 문화는 풍부합니다."),
    "environment": ("/ɪnˈvaɪrənmənt/", "명사", "환경", "We must protect the environment.", "우리는 환경을 보호해야 합니다."),
    "opinion":     ("/əˈpɪnjən/", "명사", "의견, 견해", "What is your opinion?", "당신의 의견은 무엇인가요?"),
    "understand":  ("/ˌʌndərˈstænd/", "동사", "이해하다", "Do you understand?", "이해하셨나요?"),
    "without":     ("/wɪˈðaʊt/", "전치사", "~없이", "I can't live without coffee.", "커피 없이는 살 수 없습니다."),
    "significant": ("/sɪɡˈnɪfɪkənt/", "형용사", "중요한, 의미 있는", "This is a significant change.", "이것은 중요한 변화입니다."),
    "popular":     ("/ˈpɒpjələr/", "형용사", "인기 있는, 대중적인", "This song is very popular.", "이 노래는 매우 인기 있습니다."),
    "available":   ("/əˈveɪləbəl/", "형용사", "이용 가능한, 구할 수 있는", "Is this product available?", "이 제품을 구입할 수 있나요?"),
    "level":       ("/ˈlɛvəl/", "명사", "수준, 레벨", "What level are you at?", "어떤 레벨이신가요?"),
    "require":     ("/rɪˈkwaɪər/", "동사", "필요로 하다, 요구하다", "This job requires experience.", "이 일은 경험이 필요합니다."),
    "together":    ("/təˈɡɛðər/", "부사", "함께, 같이", "Let's work together.", "함께 일합시다."),
    "recent":      ("/ˈriːsənt/", "형용사", "최근의, 새로운", "Have you read his recent book?", "그의 최근 책을 읽었나요?"),
    "follow":      ("/ˈfɒloʊ/", "동사", "따르다, 뒤따르다", "Please follow me.", "저를 따라오세요."),
    "indicate":    ("/ˈɪndɪkeɪt/", "동사", "나타내다, 가리키다", "Studies indicate positive results.", "연구들이 긍정적인 결과를 나타냅니다."),
    "increase":    ("/ɪnˈkriːs/", "동사", "증가하다, 늘리다", "Sales have increased this year.", "올해 매출이 증가했습니다."),
    "result":      ("/rɪˈzʌlt/", "명사", "결과, 성과", "What was the result?", "결과가 어떻게 됐나요?"),
    "continue":    ("/kənˈtɪnjuː/", "동사", "계속하다, 지속하다", "Please continue.", "계속하세요."),
    "process":     ("/ˈprɒsɛs/", "명사", "과정, 절차", "The process is complicated.", "과정이 복잡합니다."),
    "early":       ("/ˈɜːrli/", "부사", "일찍, 이른", "Please arrive early.", "일찍 도착해 주세요."),
    "local":       ("/ˈloʊkəl/", "형용사", "지역의, 현지의", "Try local food.", "현지 음식을 먹어 보세요."),
    "position":    ("/pəˈzɪʃən/", "명사", "위치, 직위", "What position do you hold?", "어떤 직위를 맡고 있나요?"),
    "natural":     ("/ˈnætʃərəl/", "형용사", "자연스러운, 천연의", "This is a natural process.", "이것은 자연스러운 과정입니다."),
    "general":     ("/ˈdʒɛnərəl/", "형용사", "일반적인, 전체적인", "In general, I agree.", "일반적으로 저는 동의합니다."),
    "apply":       ("/əˈplaɪ/", "동사", "지원하다, 적용하다", "I'd like to apply for this job.", "이 일자리에 지원하고 싶습니다."),
    "figure":      ("/ˈfɪɡjər/", "명사", "숫자, 인물, 형태", "The figure shows 50%.", "수치는 50%를 보여줍니다."),
    "meet":        ("/miːt/", "동사", "만나다, 충족하다", "Let's meet at the cafe.", "카페에서 만나자."),
    "support":     ("/səˈpɔːrt/", "동사", "지지하다, 지원하다", "I support your decision.", "저는 당신의 결정을 지지합니다."),
    "purpose":     ("/ˈpɜːrpəs/", "명사", "목적, 의도", "What is the purpose of this?", "이것의 목적이 무엇인가요?"),
    "direction":   ("/dɪˈrɛkʃən/", "명사", "방향, 지시", "Go in that direction.", "그 방향으로 가세요."),
    "line":        ("/laɪn/", "명사", "선, 줄, 노선", "Please wait in line.", "줄을 서 기다리세요."),
    "study":       ("/ˈstʌdi/", "명사", "공부, 연구", "My study is going well.", "공부가 잘 되고 있습니다."),
    "power":       ("/ˈpaʊər/", "명사", "힘, 전력, 권력", "Knowledge is power.", "지식은 힘입니다."),
    "increase":    ("/ˈɪnkriːs/", "명사", "증가, 상승", "There was an increase in sales.", "매출이 증가했습니다."),
    "success":     ("/səkˈsɛs/", "명사", "성공", "Wish you success!", "성공을 빕니다!"),
    "turn":        ("/tɜːrn/", "동사", "돌다, 변하다", "Turn left at the corner.", "모퉁이에서 왼쪽으로 도세요."),
    "example":     ("/ɪɡˈzɑːmpəl/", "명사", "예시, 보기", "Give me an example.", "예시를 들어 주세요."),
    "society":     ("/səˈsaɪəti/", "명사", "사회, 단체", "We live in a complex society.", "우리는 복잡한 사회에서 삽니다."),
    "quality":     ("/ˈkwɒlɪti/", "명사", "품질, 질", "The quality is excellent.", "품질이 훌륭합니다."),
    "likely":      ("/ˈlaɪkli/", "형용사", "~할 것 같은", "It's likely to rain.", "비가 올 것 같습니다."),
    "question":    ("/ˈkwɛstʃən/", "명사", "질문, 의문", "Do you have any questions?", "질문이 있으신가요?"),
    "issue":       ("/ˈɪʃuː/", "명사", "문제, 쟁점", "This is a major issue.", "이것은 주요 문제입니다."),
    "research":    ("/rɪˈsɜːrtʃ/", "명사", "연구, 조사", "She does research on climate.", "그녀는 기후에 관한 연구를 합니다."),
    "create":      ("/kriˈeɪt/", "동사", "만들다, 창조하다", "Let's create something new.", "새로운 것을 만들어 봅시다."),
    "type":        ("/taɪp/", "명사", "유형, 종류", "What type of food do you like?", "어떤 종류의 음식을 좋아하시나요?"),
    "available":   ("/əˈveɪləbəl/", "형용사", "이용 가능한", "Is this product available?", "이 제품을 구입할 수 있나요?"),
    "return":      ("/rɪˈtɜːrn/", "동사", "돌아오다, 반환하다", "Please return the book.", "책을 반납해 주세요."),
    "change":      ("/tʃeɪndʒ/", "동사", "바꾸다, 변하다", "Things change over time.", "시간이 지나면서 상황이 변합니다."),
    "official":    ("/əˈfɪʃəl/", "형용사", "공식적인, 관료의", "This is an official document.", "이것은 공식 문서입니다."),
    "difficult":   ("/ˈdɪfɪkəlt/", "형용사", "어려운", "This problem is difficult.", "이 문제는 어렵습니다."),
    "probably":    ("/ˈprɒbəbli/", "부사", "아마도, 십중팔구", "He's probably home by now.", "그는 지금쯤 집에 있을 것입니다."),
    "common":      ("/ˈkɒmən/", "형용사", "흔한, 공통의", "This is a common mistake.", "이것은 흔한 실수입니다."),
    "center":      ("/ˈsɛntər/", "명사", "중심, 센터", "The shopping center is nearby.", "쇼핑센터가 근처에 있습니다."),
    "charge":      ("/tʃɑːrdʒ/", "명사", "요금, 비용", "There's an extra charge.", "추가 요금이 있습니다."),
    "face":        ("/feɪs/", "명사", "얼굴, 직면하다", "He has a kind face.", "그는 친절한 얼굴을 하고 있습니다."),
    "program":     ("/ˈproʊɡræm/", "명사", "프로그램, 계획", "The program starts at noon.", "프로그램은 정오에 시작합니다."),
    "economic":    ("/ˌiːkəˈnɒmɪk/", "형용사", "경제적인", "Economic growth is key.", "경제 성장이 핵심입니다."),
    "record":      ("/ˈrɛkɔːrd/", "명사", "기록, 음반", "She broke the world record.", "그녀는 세계 기록을 깼습니다."),
    "suggest":     ("/səˈdʒɛst/", "동사", "제안하다, 시사하다", "May I suggest something?", "제안을 해도 될까요?"),
    "develop":     ("/dɪˈvɛləp/", "동사", "발전시키다, 개발하다", "We need to develop new skills.", "새로운 기술을 개발해야 합니다."),
    "major":       ("/ˈmeɪdʒər/", "형용사", "주요한, 중대한", "This is a major decision.", "이것은 중대한 결정입니다."),
    "force":       ("/fɔːrs/", "명사", "힘, 군대", "The police used force.", "경찰이 무력을 사용했습니다."),
    "structure":   ("/ˈstrʌktʃər/", "명사", "구조, 건물", "The structure is solid.", "구조가 견고합니다."),
    "including":   ("/ɪnˈkluːdɪŋ/", "전치사", "~을 포함하여", "Everyone, including me, agreed.", "나를 포함한 모든 사람이 동의했습니다."),
    "special":     ("/ˈspɛʃəl/", "형용사", "특별한", "Today is a special day.", "오늘은 특별한 날입니다."),
    "story":       ("/ˈstɔːri/", "명사", "이야기, 층", "Tell me a story.", "이야기를 들려주세요."),
    "hundred":     ("/ˈhʌndrəd/", "수사", "100, 백", "There are hundreds of options.", "수백 가지의 선택지가 있습니다."),
    "always":      ("/ˈɔːlweɪz/", "부사", "항상, 늘", "I always wake up early.", "저는 항상 일찍 일어납니다."),
    "already":     ("/ɔːlˈrɛdi/", "부사", "이미, 벌써", "I've already eaten.", "저는 이미 먹었습니다."),
    "able":        ("/ˈeɪbəl/", "형용사", "~할 수 있는, 능력 있는", "Are you able to come?", "올 수 있나요?"),
    # =========================================================
    # TOEIC L1 additional
    # =========================================================
    "invoice":     ("/ˈɪnvɔɪs/", "명사", "청구서, 송장", "Please send the invoice.", "청구서를 보내 주세요."),
    "shipment":    ("/ˈʃɪpmənt/", "명사", "선적, 화물", "The shipment arrived today.", "화물이 오늘 도착했습니다."),
    "conference":  ("/ˈkɒnfərəns/", "명사", "회의, 학회", "There is a conference next week.", "다음 주에 회의가 있습니다."),
    "approve":     ("/əˈpruːv/", "동사", "승인하다, 찬성하다", "The manager approved the plan.", "관리자가 계획을 승인했습니다."),
    "submit":      ("/səbˈmɪt/", "동사", "제출하다, 복종하다", "Please submit your application.", "지원서를 제출해 주세요."),
    "candidate":   ("/ˈkændɪdɪt/", "명사", "후보자, 지원자", "She is a strong candidate.", "그녀는 강력한 후보입니다."),
    "promotion":   ("/prəˈmoʊʃən/", "명사", "승진, 홍보", "He got a promotion.", "그는 승진했습니다."),
    "negotiate":   ("/nɪˈɡoʊʃieɪt/", "동사", "협상하다", "They negotiated the contract.", "그들은 계약을 협상했습니다."),
    "corporate":   ("/ˈkɔːrpərɪt/", "형용사", "기업의, 법인의", "This is a corporate event.", "이것은 기업 행사입니다."),
    "contract":    ("/ˈkɒntrækt/", "명사", "계약, 계약서", "Please sign the contract.", "계약서에 서명해 주세요."),
    "colleague":   ("/ˈkɒliːɡ/", "명사", "동료", "My colleague helped me.", "동료가 저를 도와주었습니다."),
    "agenda":      ("/əˈdʒɛndə/", "명사", "안건, 의제", "What's on the agenda today?", "오늘 의제가 무엇인가요?"),
    "budget":      ("/ˈbʌdʒɪt/", "명사", "예산", "We're over budget.", "예산을 초과했습니다."),
    "quarterly":   ("/ˈkwɔːrtərli/", "형용사", "분기별의", "Submit a quarterly report.", "분기별 보고서를 제출하세요."),
    "efficient":   ("/ɪˈfɪʃənt/", "형용사", "효율적인", "This method is very efficient.", "이 방법은 매우 효율적입니다."),
    "productive":  ("/prəˈdʌktɪv/", "형용사", "생산적인", "We had a productive meeting.", "생산적인 회의를 했습니다."),
    "negotiate":   ("/nɪˈɡoʊʃieɪt/", "동사", "협상하다", "Let's negotiate the terms.", "조건을 협상합시다."),
    "financial":   ("/faɪˈnænʃəl/", "형용사", "재정적인, 금융의", "The financial report is ready.", "재무 보고서가 준비되었습니다."),
    "headquarters":("/ˌhɛdˈkwɔːrtərz/", "명사", "본사, 본부", "The headquarters is in Seoul.", "본사는 서울에 있습니다."),
    "cooperation": ("/koʊˌɒpərˈeɪʃən/", "명사", "협력, 협조", "Thank you for your cooperation.", "협조해 주셔서 감사합니다."),
    "guarantee":   ("/ˌɡærənˈtiː/", "명사", "보증, 보장", "This comes with a guarantee.", "이것은 보증이 포함되어 있습니다."),
    "discount":    ("/ˈdɪskaʊnt/", "명사", "할인", "Is there a discount?", "할인이 있나요?"),
    "refund":      ("/ˈriːfʌnd/", "명사", "환불", "I'd like a refund.", "환불을 원합니다."),
    "purchase":    ("/ˈpɜːrtʃəs/", "동사", "구매하다, 사다", "I'd like to purchase this.", "이것을 구매하고 싶습니다."),
    "profit":      ("/ˈprɒfɪt/", "명사", "이익, 수익", "The company made a profit.", "회사가 수익을 올렸습니다."),
    "revenue":     ("/ˈrɛvɪnjuː/", "명사", "수익, 매출", "Revenue increased last quarter.", "지난 분기에 매출이 증가했습니다."),
    "expense":     ("/ɪkˈspɛns/", "명사", "비용, 지출", "Keep your expenses low.", "지출을 낮게 유지하세요."),
    "inventory":   ("/ˈɪnvəntɔːri/", "명사", "재고, 목록", "The inventory is low.", "재고가 부족합니다."),
    "supplier":    ("/səˈplaɪər/", "명사", "공급업체", "We need a new supplier.", "새로운 공급업체가 필요합니다."),
    "delivery":    ("/dɪˈlɪvəri/", "명사", "배달, 납품", "The delivery is on time.", "배달이 제때 도착합니다."),
    "account":     ("/əˈkaʊnt/", "명사", "계좌, 계정, 설명", "I'd like to open an account.", "계좌를 개설하고 싶습니다."),
    "transfer":    ("/ˈtrænsfɜːr/", "명사", "이동, 이체", "I need to transfer money.", "송금해야 합니다."),
    "reception":   ("/rɪˈsɛpʃən/", "명사", "프런트, 접수, 환영회", "Please register at the reception.", "프런트에서 등록해 주세요."),
    "assist":      ("/əˈsɪst/", "동사", "돕다, 지원하다", "How can I assist you?", "어떻게 도와드릴까요?"),
    "available":   ("/əˈveɪləbəl/", "형용사", "이용 가능한", "Is this product available?", "이 제품을 구입할 수 있나요?"),
    "deadline":    ("/ˈdɛdlaɪn/", "명사", "마감 기한", "The deadline is Friday.", "마감 기한이 금요일입니다."),
    "implement":   ("/ˈɪmplɪmɛnt/", "동사", "실행하다, 이행하다", "We will implement this plan.", "이 계획을 실행할 것입니다."),
    "resource":    ("/ˈriːsɔːrs/", "명사", "자원, 리소스", "We have limited resources.", "우리는 제한된 자원을 가지고 있습니다."),
    "objective":   ("/əbˈdʒɛktɪv/", "명사", "목표, 목적", "What is our main objective?", "우리의 주요 목표가 무엇인가요?"),
    "prior":       ("/ˈpraɪər/", "형용사", "이전의, 먼저의", "Prior experience is required.", "이전 경험이 필요합니다."),
    "relevant":    ("/ˈrɛlɪvənt/", "형용사", "관련된, 적절한", "Is this information relevant?", "이 정보가 관련이 있나요?"),
    "maintain":    ("/meɪnˈteɪn/", "동사", "유지하다, 주장하다", "We must maintain quality.", "품질을 유지해야 합니다."),
    "achieve":     ("/əˈtʃiːv/", "동사", "달성하다, 이루다", "I hope to achieve my goals.", "목표를 달성하기를 바랍니다."),
    "recognize":   ("/ˈrɛkəɡnaɪz/", "동사", "인식하다, 인정하다", "I didn't recognize him.", "저는 그를 알아보지 못했습니다."),
    # =========================================================
    # Business English additional
    # =========================================================
    "asset":       ("/ˈæsɛt/", "명사", "자산, 재산", "Knowledge is your greatest asset.", "지식은 가장 큰 자산입니다."),
    "liability":   ("/ˌlaɪəˈbɪlɪti/", "명사", "부채, 책임", "We have significant liabilities.", "상당한 부채가 있습니다."),
    "merger":      ("/ˈmɜːrdʒər/", "명사", "합병", "The merger was successful.", "합병이 성공적이었습니다."),
    "acquisition": ("/ˌækwɪˈzɪʃən/", "명사", "인수, 획득", "The acquisition was approved.", "인수가 승인되었습니다."),
    "shareholder": ("/ˈʃɛəhoʊldər/", "명사", "주주", "The shareholders approved.", "주주들이 승인했습니다."),
    "dividend":    ("/ˈdɪvɪdɛnd/", "명사", "배당금", "The company paid a dividend.", "회사가 배당금을 지급했습니다."),
    "turnover":    ("/ˈtɜːrnoʊvər/", "명사", "매출액, 직원 이직률", "Annual turnover increased.", "연간 매출이 증가했습니다."),
    "franchise":   ("/ˈfræntʃaɪz/", "명사", "프랜차이즈", "She owns a franchise.", "그녀는 프랜차이즈를 운영합니다."),
    "stakeholder": ("/ˈsteɪkhoʊldər/", "명사", "이해관계자", "All stakeholders were informed.", "모든 이해관계자에게 알렸습니다."),
    "outsource":   ("/ˈaʊtsɔːrs/", "동사", "외주를 주다", "We outsource IT services.", "IT 서비스는 외주를 줍니다."),
    "comply":      ("/kəmˈplaɪ/", "동사", "따르다, 준수하다", "We must comply with regulations.", "규정을 준수해야 합니다."),
    "benchmark":   ("/ˈbɛntʃmɑːrk/", "명사", "기준, 벤치마크", "This sets the benchmark.", "이것이 기준을 설정합니다."),
    "quarterly":   ("/ˈkwɔːrtərli/", "형용사", "분기별의", "Quarterly reviews are important.", "분기별 검토가 중요합니다."),
    "overhead":    ("/ˈoʊvərˌhɛd/", "명사", "간접비, 경비", "We need to cut overhead costs.", "간접비를 줄여야 합니다."),
    # =========================================================
    # Academic English additional
    # =========================================================
    "hypothesis":  ("/haɪˈpɒθɪsɪs/", "명사", "가설", "The hypothesis was proven.", "가설이 증명되었습니다."),
    "methodology": ("/ˌmɛθəˈdɒlədʒi/", "명사", "방법론", "The methodology was sound.", "방법론이 타당했습니다."),
    "empirical":   ("/ɛmˈpɪrɪkəl/", "형용사", "경험적인, 실증적인", "This is empirical evidence.", "이것은 경험적 증거입니다."),
    "theoretical": ("/ˌθɪərɪˈɛtɪkəl/", "형용사", "이론적인", "This is a theoretical framework.", "이것은 이론적 틀입니다."),
    "variable":    ("/ˈvɛriəbəl/", "명사", "변수", "There are many variables.", "많은 변수가 있습니다."),
    "paradigm":    ("/ˈpærədaɪm/", "명사", "패러다임, 사례", "A paradigm shift occurred.", "패러다임 전환이 일어났습니다."),
    "criterion":   ("/kraɪˈtɪəriən/", "명사", "기준, 척도", "What are the criteria?", "기준이 무엇인가요?"),
    "explicit":    ("/ɪkˈsplɪsɪt/", "형용사", "명시적인, 분명한", "Please be explicit.", "분명하게 말씀해 주세요."),
    "implicit":    ("/ɪmˈplɪsɪt/", "형용사", "암묵적인, 함축적인", "There is an implicit understanding.", "암묵적인 이해가 있습니다."),
    "correlate":   ("/ˈkɒrəleɪt/", "동사", "상관관계가 있다", "These two factors correlate.", "이 두 요소는 상관관계가 있습니다."),
    "prior":       ("/ˈpraɪər/", "형용사", "이전의, 먼저의", "Prior knowledge helps.", "이전 지식이 도움이 됩니다."),
    "findings":    ("/ˈfaɪndɪŋz/", "명사", "연구 결과, 발견", "The findings were surprising.", "연구 결과가 놀라웠습니다."),
    "abstract":    ("/ˈæbstrækt/", "명사", "요약, 초록", "Please read the abstract.", "요약을 읽어 주세요."),
    "publication": ("/ˌpʌblɪˈkeɪʃən/", "명사", "출판물, 발행", "The publication is available online.", "출판물은 온라인에서 이용 가능합니다."),
    "peer":        ("/pɪər/", "명사", "동료, 또래", "Peer review is important.", "동료 평가가 중요합니다."),
    "relevant":    ("/ˈrɛlɪvənt/", "형용사", "관련 있는, 적절한", "Is this topic relevant?", "이 주제가 관련 있나요?"),
    "significant": ("/sɪɡˈnɪfɪkənt/", "형용사", "중요한, 통계적으로 유의미한", "The results are significant.", "결과가 유의미합니다."),
    "assume":      ("/əˈsjuːm/", "동사", "가정하다, 추정하다", "Don't assume anything.", "아무것도 가정하지 마세요."),
    "conclude":    ("/kənˈkluːd/", "동사", "결론 짓다, 끝내다", "We can conclude that...", "우리는 ~라고 결론 지을 수 있습니다."),
    "furthermore": ("/ˈfɜːrðərmɔːr/", "부사", "더욱이, 게다가", "Furthermore, the data shows...", "더욱이, 데이터는 ~을 보여줍니다."),
    "whereas":     ("/wɛərˈæz/", "접속사", "반면에, ~인데도", "Whereas she studies, he relaxes.", "그녀는 공부하는 반면 그는 쉽니다."),
    "despite":     ("/dɪˈspaɪt/", "전치사", "~에도 불구하고", "Despite the rain, we went out.", "비에도 불구하고 외출했습니다."),
    "nevertheless":("/ˌnɛvərðəˈlɛs/", "부사", "그럼에도 불구하고", "Nevertheless, we continue.", "그럼에도 불구하고 계속합니다."),
    "acknowledge": ("/əkˈnɒlɪdʒ/", "동사", "인정하다, 인식하다", "We acknowledge the problem.", "우리는 문제를 인정합니다."),
    "notion":      ("/ˈnoʊʃən/", "명사", "개념, 관념", "What is your notion of success?", "성공에 대한 당신의 개념은 무엇인가요?"),
    "scope":       ("/skoʊp/", "명사", "범위, 영역", "This is within the scope.", "이것은 범위 안에 있습니다."),
    "framework":   ("/ˈfreɪmwɜːrk/", "명사", "체계, 틀", "We need a clear framework.", "명확한 체계가 필요합니다."),
    "distinction": ("/dɪˈstɪŋkʃən/", "명사", "구별, 차이", "There is an important distinction.", "중요한 구별이 있습니다."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            # Only patch if current meaning equals the word (fallback marker) or empty
            if entry.get("meaning", "") in ("", word):
                if key in DICT2:
                    pron, pos, meaning, ex_en, ex_ko = DICT2[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more.py ===\n")
    patch_files()
