#!/usr/bin/env python3
"""Fill TOEIC-L5 (248 words)"""
import json, glob

DICT14 = {
    "pastry":        ("/ˈpeɪstri/", "명사", "페이스트리, 파이", "Enjoy a fresh pastry.", "신선한 페이스트리를 드세요."),
    "personalize":   ("/ˈpɜːrsənəlaɪz/", "동사", "개인화하다", "Personalize your settings.", "설정을 개인화하세요."),
    "poorly":        ("/ˈpʊərli/", "부사", "형편없이, 안 좋게", "Poorly written report.", "형편없이 작성된 보고서."),
    "purser":        ("/ˈpɜːrsər/", "명사", "사무장, 출납원", "Ask the purser.", "사무장에게 물어보세요."),
    "resume":        ("/rɪˈzjuːm/", "동사", "재개하다", "Resume work.", "업무를 재개하세요."),
    "reunion":       ("/riːˈjuːniən/", "명사", "재회, 동창회", "Class reunion.", "동창회."),
    "revolutionize": ("/ˌrɛvəˈluːʃənaɪz/", "동사", "혁명적으로 바꾸다", "Revolutionize the industry.", "산업을 혁명적으로 바꾸세요."),
    "seafood":       ("/ˈsiːfuːd/", "명사", "해산물", "Fresh seafood.", "신선한 해산물."),
    "signify":       ("/ˈsɪɡnɪfaɪ/", "동사", "의미하다, 나타내다", "What does this signify?", "이것은 무엇을 의미하나요?"),
    "slot":          ("/slɒt/", "명사", "슬롯, 자리", "Time slot.", "시간 슬롯."),
    "steer":         ("/stɪər/", "동사", "조종하다, 이끌다", "Steer the conversation.", "대화를 이끄세요."),
    "sue":           ("/suː/", "동사", "고소하다", "Sue for damages.", "피해 보상을 청구하세요."),
    "superb":        ("/suːˈpɜːrb/", "형용사", "훌륭한, 최고의", "Superb service.", "훌륭한 서비스."),
    "traditionally": ("/trəˈdɪʃənəli/", "부사", "전통적으로", "Traditionally prepared.", "전통적으로 준비됐다."),
    "tremendous":    ("/trɪˈmɛndəs/", "형용사", "엄청난, 대단한", "Tremendous effort.", "엄청난 노력."),
    "underway":      ("/ˌʌndərˈweɪ/", "형용사", "진행 중인", "Construction is underway.", "건설이 진행 중이다."),
    "unpleasant":    ("/ʌnˈplɛzənt/", "형용사", "불쾌한", "Unpleasant smell.", "불쾌한 냄새."),
    "violin":        ("/ˌvaɪəˈlɪn/", "명사", "바이올린", "Play the violin.", "바이올린을 연주하세요."),
    "ward":          ("/wɔːrd/", "명사", "병동, 구역", "Hospital ward.", "병원 병동."),
    "worthwhile":    ("/ˌwɜːrθˈwaɪl/", "형용사", "가치 있는", "A worthwhile investment.", "가치 있는 투자."),
    "adapter":       ("/əˈdæptər/", "명사", "어댑터", "Power adapter.", "전원 어댑터."),
    "advisable":     ("/ədˈvaɪzəbəl/", "형용사", "바람직한, 권고되는", "It is advisable.", "바람직하다."),
    "archive":       ("/ˈɑːrkaɪv/", "명사", "기록 보관소", "Digital archive.", "디지털 기록 보관소."),
    "artistic":      ("/ɑːrˈtɪstɪk/", "형용사", "예술적인", "Artistic talent.", "예술적 재능."),
    "assurance":     ("/əˈʃʊərəns/", "명사", "보증, 확신", "Quality assurance.", "품질 보증."),
    "athletic":      ("/æθˈlɛtɪk/", "형용사", "운동의, 건강한", "Athletic performance.", "운동 능력."),
    "attire":        ("/əˈtaɪər/", "명사", "복장, 옷차림", "Business attire.", "비즈니스 복장."),
    "auditor":       ("/ˈɔːdɪtər/", "명사", "감사관", "External auditor.", "외부 감사관."),
    "bankruptcy":    ("/ˈbæŋkrʌptsi/", "명사", "파산", "File for bankruptcy.", "파산 신청을 하세요."),
    "bulk":          ("/bʌlk/", "명사", "대량, 주요 부분", "Buy in bulk.", "대량으로 구매하세요."),
    "butter":        ("/ˈbʌtər/", "명사", "버터", "Add butter.", "버터를 추가하세요."),
    "centimeter":    ("/ˈsɛntɪmiːtər/", "명사", "센티미터", "10 centimeters.", "10센티미터."),
    "circulate":     ("/ˈsɜːrkjʊleɪt/", "동사", "순환하다, 유통시키다", "Circulate the memo.", "메모를 유통시키세요."),
    "comb":          ("/koʊm/", "명사", "빗", "Use a comb.", "빗을 사용하세요."),
    "comfortably":   ("/ˈkʌmftəbli/", "부사", "편안하게", "Sit comfortably.", "편안하게 앉으세요."),
    "compliance":    ("/kəmˈplaɪəns/", "명사", "준수, 규정 준수", "Regulatory compliance.", "법규 준수."),
    "contraction":   ("/kənˈtrækʃən/", "명사", "수축, 축약", "Economic contraction.", "경기 수축."),
    "cookbook":      ("/ˈkʊkbʊk/", "명사", "요리책", "Follow the cookbook.", "요리책을 따라하세요."),
    "cushion":       ("/ˈkʊʃən/", "명사", "쿠션", "Soft cushion.", "부드러운 쿠션."),
    "dose":          ("/doʊs/", "명사", "복용량", "Daily dose.", "일일 복용량."),
    "drum":          ("/drʌm/", "명사", "드럼", "Play the drum.", "드럼을 치세요."),
    "embed":         ("/ɪmˈbɛd/", "동사", "삽입하다, 내장하다", "Embed the video.", "동영상을 삽입하세요."),
    "evacuate":      ("/ɪˈvækjueɪt/", "동사", "대피하다", "Evacuate the building.", "건물을 대피하세요."),
    "expedite":      ("/ˈɛkspɪdaɪt/", "동사", "신속히 처리하다", "Expedite the request.", "요청을 신속히 처리하세요."),
    "extinguisher":  ("/ɪkˈstɪŋɡwɪʃər/", "명사", "소화기", "Use the fire extinguisher.", "소화기를 사용하세요."),
    "familiarity":   ("/fəˌmɪliˈærɪti/", "명사", "친숙함", "Familiarity breeds comfort.", "친숙함이 편안함을 만든다."),
    "flaw":          ("/flɔː/", "명사", "흠, 결점", "Find the flaw.", "결점을 찾으세요."),
    "fluctuate":     ("/ˈflʌktʃueɪt/", "동사", "변동하다", "Prices fluctuate.", "가격이 변동한다."),
    "fluent":        ("/ˈfluːənt/", "형용사", "유창한", "Fluent in English.", "영어에 유창한."),
    "honestly":      ("/ˈɒnɪstli/", "부사", "솔직히", "Speak honestly.", "솔직하게 말하세요."),
    "housekeep":     ("/ˈhaʊskiːp/", "동사", "가사를 돌보다", "Housekeep daily.", "매일 가사를 돌보세요."),
    "hurricane":     ("/ˈhʌrɪkeɪn/", "명사", "허리케인", "Hurricane warning.", "허리케인 경보."),
    "hygiene":       ("/ˈhaɪdʒiːn/", "명사", "위생", "Good hygiene practice.", "좋은 위생 습관."),
    "integral":      ("/ˈɪntɪɡrəl/", "형용사", "필수적인, 통합적인", "Integral part.", "필수적인 부분."),
    "interactive":   ("/ˌɪntərˈæktɪv/", "형용사", "상호작용하는", "Interactive learning.", "상호작용 학습."),
    "interfere":     ("/ˌɪntərˈfɪər/", "동사", "간섭하다", "Don't interfere.", "간섭하지 마세요."),
    "kilogram":      ("/ˈkɪləɡræm/", "명사", "킬로그램", "Five kilograms.", "5킬로그램."),
    "layoff":        ("/ˈleɪɒf/", "명사", "해고, 일시 해고", "Mass layoff.", "대규모 해고."),
    "lightweight":   ("/ˈlaɪtweɪt/", "형용사", "가벼운", "Lightweight material.", "가벼운 소재."),
    "merit":         ("/ˈmɛrɪt/", "명사", "장점, 공로", "Judge on merit.", "장점으로 평가하세요."),
    "necklace":      ("/ˈnɛklɪs/", "명사", "목걸이", "Diamond necklace.", "다이아몬드 목걸이."),
    "needy":         ("/ˈniːdi/", "형용사", "어려운, 가난한", "Help the needy.", "어려운 사람들을 도우세요."),
    "overpay":       ("/ˌoʊvərˈpeɪ/", "동사", "과지불하다", "Don't overpay.", "과지불하지 마세요."),
    "pamphlet":      ("/ˈpæmflɪt/", "명사", "팸플릿", "Read the pamphlet.", "팸플릿을 읽으세요."),
    "partial":       ("/ˈpɑːrʃəl/", "형용사", "부분적인", "Partial payment.", "부분 지급."),
    "penalize":      ("/ˈpiːnəlaɪz/", "동사", "처벌하다, 벌점을 주다", "Penalize violations.", "위반에 벌칙을 주세요."),
    "pollute":       ("/pəˈluːt/", "동사", "오염시키다", "Don't pollute the river.", "강을 오염시키지 마세요."),
    "prescribe":     ("/prɪˈskraɪb/", "동사", "처방하다, 규정하다", "Prescribe medicine.", "약을 처방하세요."),
    "probable":      ("/ˈprɒbəbəl/", "형용사", "있을 것 같은", "Probable outcome.", "있을 것 같은 결과."),
    "prominent":     ("/ˈprɒmɪnənt/", "형용사", "저명한, 눈에 띄는", "Prominent figure.", "저명한 인물."),
    "rainfall":      ("/ˈreɪnfɔːl/", "명사", "강우량", "Annual rainfall.", "연간 강우량."),
    "relocation":    ("/ˌriːloʊˈkeɪʃən/", "명사", "이전, 이사", "Office relocation.", "사무실 이전."),
    "residence":     ("/ˈrɛzɪdəns/", "명사", "거주지", "Primary residence.", "주거지."),
    "retrieve":      ("/rɪˈtriːv/", "동사", "회수하다, 검색하다", "Retrieve the data.", "데이터를 검색하세요."),
    "rider":         ("/ˈraɪdər/", "명사", "탑승자, 기수", "Motorcycle rider.", "오토바이 탑승자."),
    "rubber":        ("/ˈrʌbər/", "명사", "고무", "Rubber gloves.", "고무 장갑."),
    "rug":           ("/rʌɡ/", "명사", "깔개, 러그", "Living room rug.", "거실 깔개."),
    "salespeople":   ("/ˈseɪlzpiːpəl/", "명사", "영업 직원들", "Train the salespeople.", "영업 직원들을 교육하세요."),
    "sharply":       ("/ˈʃɑːrpli/", "부사", "급격하게", "Prices fell sharply.", "가격이 급격히 하락했다."),
    "similarity":    ("/ˌsɪmɪˈlærɪti/", "명사", "유사점", "Find the similarity.", "유사점을 찾으세요."),
    "someday":       ("/ˈsʌmdeɪ/", "부사", "언젠가", "Someday you will succeed.", "언젠가 성공할 것이다."),
    "spectator":     ("/spɛkˈteɪtər/", "명사", "관중", "Cheering spectators.", "응원하는 관중."),
    "stereo":        ("/ˈstɛrioʊ/", "명사", "스테레오", "Stereo sound.", "스테레오 사운드."),
    "storeroom":     ("/ˈstɔːruːm/", "명사", "창고방", "Check the storeroom.", "창고방을 확인하세요."),
    "subsidize":     ("/ˈsʌbsɪdaɪz/", "동사", "보조금을 주다", "Subsidize housing.", "주택에 보조금을 주세요."),
    "suspicious":    ("/səˈspɪʃəs/", "형용사", "의심스러운", "Suspicious behavior.", "의심스러운 행동."),
    "tasty":         ("/ˈteɪsti/", "형용사", "맛있는", "Tasty food.", "맛있는 음식."),
    "terrific":      ("/təˈrɪfɪk/", "형용사", "엄청난, 훌륭한", "Terrific result.", "훌륭한 결과."),
    "underground":   ("/ˈʌndərɡraʊnd/", "형용사", "지하의", "Underground parking.", "지하 주차장."),
    "unpaid":        ("/ʌnˈpeɪd/", "형용사", "미지급의", "Unpaid leave.", "무급 휴가."),
    "volleyball":    ("/ˈvɒlɪbɔːl/", "명사", "배구", "Play volleyball.", "배구를 하세요."),
    "wheelchair":    ("/ˈwiːltʃɛər/", "명사", "휠체어", "Wheelchair accessible.", "휠체어 접근 가능."),
    "whoever":       ("/huːˈɛvər/", "대명사", "누구든지", "Whoever arrives first.", "먼저 도착하는 누구든지."),
    "wool":          ("/wʊl/", "명사", "양모", "Wool sweater.", "양모 스웨터."),
    "wrinkle":       ("/ˈrɪŋkəl/", "명사", "주름", "Iron out wrinkles.", "주름을 펴세요."),
    "accuracy":      ("/ˈækjʊrəsi/", "명사", "정확도", "Improve accuracy.", "정확도를 향상시키세요."),
    "anyhow":        ("/ˈɛnɪhaʊ/", "부사", "어쨌든, 어떻게든", "Anyhow, let's move on.", "어쨌든 계속 나아갑시다."),
    "appetizer":     ("/ˈæpɪtaɪzər/", "명사", "에피타이저", "Order an appetizer.", "에피타이저를 주문하세요."),
    "arc":           ("/ɑːrk/", "명사", "호, 아치", "An arc of light.", "빛의 호."),
    "audition":      ("/ɔːˈdɪʃən/", "명사", "오디션", "Go to an audition.", "오디션에 가세요."),
    "backpack":      ("/ˈbækpæk/", "명사", "배낭", "Pack a backpack.", "배낭을 싸세요."),
    "ballroom":      ("/ˈbɔːlruːm/", "명사", "무도회장", "Dance in a ballroom.", "무도회장에서 춤을 추세요."),
    "beneficial":    ("/ˌbɛnɪˈfɪʃəl/", "형용사", "유익한", "Beneficial effects.", "유익한 효과."),
    "biography":     ("/baɪˈɒɡrəfi/", "명사", "전기", "Read a biography.", "전기를 읽으세요."),
    "bound":         ("/baʊnd/", "형용사", "~행의, 의무가 있는", "Bound for London.", "런던 행."),
    "broom":         ("/bruːm/", "명사", "빗자루", "Sweep with a broom.", "빗자루로 쓸으세요."),
    "cheeseburger":  ("/ˈtʃiːzbɜːrɡər/", "명사", "치즈버거", "A cheeseburger.", "치즈버거."),
    "chilly":        ("/ˈtʃɪli/", "형용사", "쌀쌀한", "Chilly weather.", "쌀쌀한 날씨."),
    "circus":        ("/ˈsɜːrkəs/", "명사", "서커스", "Go to the circus.", "서커스에 가세요."),
    "compliment":    ("/ˈkɒmplɪmənt/", "명사", "칭찬", "Give a compliment.", "칭찬을 하세요."),
    "consignment":   ("/kənˈsaɪnmənt/", "명사", "위탁 판매", "On consignment.", "위탁으로."),
    "continental":   ("/ˌkɒntɪˈnɛntəl/", "형용사", "대륙의", "Continental breakfast.", "컨티넨털 조식."),
    "copyright":     ("/ˈkɒpɪraɪt/", "명사", "저작권", "Copyright protection.", "저작권 보호."),
    "countryside":   ("/ˈkʌntrisaɪd/", "명사", "시골", "Live in the countryside.", "시골에 살다."),
    "demolish":      ("/dɪˈmɒlɪʃ/", "동사", "철거하다", "Demolish the old building.", "오래된 건물을 철거하세요."),
    "departmental":  ("/ˌdiːpɑːrtˈmɛntəl/", "형용사", "부서의", "Departmental meeting.", "부서 회의."),
    "desperate":     ("/ˈdɛspərɪt/", "형용사", "절박한", "Desperate situation.", "절박한 상황."),
    "devastate":     ("/ˈdɛvəsteɪt/", "동사", "황폐화하다", "Devastate the community.", "지역사회를 황폐화하다."),
    "diagnostic":    ("/ˌdaɪəɡˈnɒstɪk/", "형용사", "진단의", "Diagnostic test.", "진단 검사."),
    "diagram":       ("/ˈdaɪəɡræm/", "명사", "다이어그램", "Draw a diagram.", "다이어그램을 그리세요."),
    "diamond":       ("/ˈdaɪəmənd/", "명사", "다이아몬드", "Diamond ring.", "다이아몬드 반지."),
    "disable":       ("/dɪsˈeɪbəl/", "동사", "비활성화하다", "Disable the alarm.", "알람을 비활성화하세요."),
    "disgust":       ("/dɪsˈɡʌst/", "명사", "혐오감", "Express disgust.", "혐오감을 표현하세요."),
    "donut":         ("/ˈdoʊnʌt/", "명사", "도넛", "Eat a donut.", "도넛을 먹으세요."),
    "doorman":       ("/ˈdɔːrmæn/", "명사", "도어맨", "The doorman helped.", "도어맨이 도왔다."),
    "electronically":("/ɪˌlɛkˈtrɒnɪkli/", "부사", "전자적으로", "Submit electronically.", "전자적으로 제출하세요."),
    "elevate":       ("/ˈɛlɪveɪt/", "동사", "높이다, 올리다", "Elevate standards.", "기준을 높이세요."),
    "engagement":    ("/ɪnˈɡeɪdʒmənt/", "명사", "약혼, 참여", "Customer engagement.", "고객 참여."),
    "enrollment":    ("/ɪnˈroʊlmənt/", "명사", "등록", "Course enrollment.", "강좌 등록."),
    "euro":          ("/ˈjʊəroʊ/", "명사", "유로", "Pay in euros.", "유로로 지불하세요."),
    "forbid":        ("/fərˈbɪd/", "동사", "금지하다", "Forbid smoking.", "흡연을 금지하세요."),
    "fork":          ("/fɔːrk/", "명사", "포크", "Use a fork.", "포크를 사용하세요."),
    "foster":        ("/ˈfɒstər/", "동사", "육성하다, 위탁 양육하다", "Foster creativity.", "창의성을 육성하세요."),
    "getaway":       ("/ˈɡɛtəweɪ/", "명사", "탈출, 여행", "Weekend getaway.", "주말 여행."),
    "gossip":        ("/ˈɡɒsɪp/", "명사", "소문, 잡담", "Avoid gossip.", "소문을 피하세요."),
    "hacker":        ("/ˈhækər/", "명사", "해커", "Protect against hackers.", "해커로부터 보호하세요."),
    "hardworking":   ("/ˌhɑːrdˈwɜːrkɪŋ/", "형용사", "열심히 일하는", "Hardworking employee.", "열심히 일하는 직원."),
    "impatient":     ("/ɪmˈpeɪʃənt/", "형용사", "참을성 없는", "Don't be impatient.", "참을성 없이 굴지 마세요."),
    "indirect":      ("/ˌɪndɪˈrɛkt/", "형용사", "간접적인", "Indirect approach.", "간접적인 접근."),
    "interpreter":   ("/ɪnˈtɜːrprɪtər/", "명사", "통역사", "Hire an interpreter.", "통역사를 고용하세요."),
    "intersection":  ("/ˌɪntərˈsɛkʃən/", "명사", "교차로", "At the intersection.", "교차로에서."),
    "irrelevant":    ("/ɪˈrɛlɪvənt/", "형용사", "관련 없는", "Irrelevant information.", "관련 없는 정보."),
    "jeans":         ("/dʒiːnz/", "명사", "청바지", "Wear jeans.", "청바지를 입으세요."),
    "journalism":    ("/ˈdʒɜːrnəlɪzəm/", "명사", "저널리즘", "Study journalism.", "저널리즘을 공부하세요."),
    "letterhead":    ("/ˈlɛtərhɛd/", "명사", "편지지 상단", "Company letterhead.", "회사 편지지."),
    "lifeguard":     ("/ˈlaɪfɡɑːrd/", "명사", "안전 요원", "Beach lifeguard.", "해변 안전 요원."),
    "modem":         ("/ˈmoʊdɛm/", "명사", "모뎀", "Internet modem.", "인터넷 모뎀."),
    "monument":      ("/ˈmɒnjʊmənt/", "명사", "기념비", "Historical monument.", "역사적 기념비."),
    "mosquito":      ("/məˈskiːtoʊ/", "명사", "모기", "Mosquito repellent.", "모기 퇴치제."),
    "obligate":      ("/ˈɒblɪɡeɪt/", "동사", "의무를 지우다", "Obligate to pay.", "지불 의무를 지우다."),
    "oblige":        ("/əˈblaɪdʒ/", "동사", "의무를 지우다", "Oblige to fulfill.", "이행 의무를 지우다."),
    "occurrence":    ("/əˈkɜːrəns/", "명사", "발생, 사건", "Rare occurrence.", "드문 발생."),
    "operational":   ("/ˌɒpəˈreɪʃənəl/", "형용사", "운영의", "Fully operational.", "완전히 운영 중."),
    "outage":        ("/ˈaʊtɪdʒ/", "명사", "정전, 서비스 중단", "Power outage.", "정전."),
    "overcrowd":     ("/ˌoʊvərˈkraʊd/", "동사", "과밀하게 만들다", "Don't overcrowd.", "과밀하게 하지 마세요."),
    "paralegal":     ("/ˌpærəˈliːɡəl/", "명사", "법률 보조인", "Work as a paralegal.", "법률 보조인으로 일하세요."),
    "partially":     ("/ˈpɑːrʃəli/", "부사", "부분적으로", "Partially complete.", "부분적으로 완료."),
    "pepper":        ("/ˈpɛpər/", "명사", "후추, 고추", "Add pepper.", "후추를 추가하세요."),
    "permanently":   ("/ˈpɜːrmənəntli/", "부사", "영구적으로", "Permanently closed.", "영구 폐쇄."),
    "plow":          ("/plaʊ/", "동사", "쟁기질하다", "Plow the field.", "밭을 갈아엎으세요."),
    "query":         ("/ˈkwɪəri/", "명사", "질문, 쿼리", "Submit a query.", "쿼리를 제출하세요."),
    "railway":       ("/ˈreɪlweɪ/", "명사", "철도", "Railway station.", "철도역."),
    "raincoat":      ("/ˈreɪnkoʊt/", "명사", "비옷", "Wear a raincoat.", "비옷을 입으세요."),
    "reconsider":    ("/ˌriːkənˈsɪdər/", "동사", "재고하다", "Please reconsider.", "다시 고려해주세요."),
    "redesign":      ("/ˌriːdɪˈzaɪn/", "동사", "재디자인하다", "Redesign the logo.", "로고를 재디자인하세요."),
    "rehearsal":     ("/rɪˈhɜːrsəl/", "명사", "리허설, 연습", "Final rehearsal.", "최종 리허설."),
    "relaxation":    ("/ˌriːlækˈseɪʃən/", "명사", "이완, 휴식", "Time for relaxation.", "휴식 시간."),
    "repetition":    ("/ˌrɛpɪˈtɪʃən/", "명사", "반복", "Practice through repetition.", "반복을 통해 연습하세요."),
    "retreat":       ("/rɪˈtriːt/", "명사", "후퇴, 연수", "Corporate retreat.", "기업 연수."),
    "salon":         ("/ˈsæloʊn/", "명사", "미용실", "Visit the salon.", "미용실을 방문하세요."),
    "satellite":     ("/ˈsætəlaɪt/", "명사", "위성", "Satellite communication.", "위성 통신."),
    "scenery":       ("/ˈsiːnəri/", "명사", "풍경", "Beautiful scenery.", "아름다운 풍경."),
    "serial":        ("/ˈsɪəriəl/", "명사", "연속물, 시리얼", "Serial number.", "일련 번호."),
    "sew":           ("/soʊ/", "동사", "바느질하다", "Sew the button.", "단추를 달으세요."),
    "sketch":        ("/skɛtʃ/", "동사", "스케치하다", "Sketch the design.", "디자인을 스케치하세요."),
    "smartphone":    ("/ˈsmɑːrtfoʊn/", "명사", "스마트폰", "Use a smartphone.", "스마트폰을 사용하세요."),
    "soar":          ("/sɔːr/", "동사", "솟아오르다, 급등하다", "Prices soar.", "가격이 급등한다."),
    "stimulus":      ("/ˈstɪmjʊləs/", "명사", "자극, 경기 부양책", "Economic stimulus.", "경기 부양책."),
    "stockbroker":   ("/ˈstɒkbroʊkər/", "명사", "주식 중개인", "Hire a stockbroker.", "주식 중개인을 고용하세요."),
    "tablecloth":    ("/ˈteɪbəlklɒθ/", "명사", "식탁보", "Clean tablecloth.", "깨끗한 식탁보."),
    "thirsty":       ("/ˈθɜːrsti/", "형용사", "목마른", "I am thirsty.", "목이 마르다."),
    "thrill":        ("/θrɪl/", "명사", "전율, 스릴", "Feel the thrill.", "스릴을 느끼세요."),
    "tile":          ("/taɪl/", "명사", "타일", "Ceramic tile.", "세라믹 타일."),
    "toiletry":      ("/ˈtɔɪlɪtri/", "명사", "세면도구", "Pack toiletries.", "세면도구를 챙기세요."),
    "trademark":     ("/ˈtreɪdmɑːrk/", "명사", "상표", "Register the trademark.", "상표를 등록하세요."),
    "tropical":      ("/ˈtrɒpɪkəl/", "형용사", "열대의", "Tropical climate.", "열대 기후."),
    "tuna":          ("/ˈtjuːnə/", "명사", "참치", "Tuna sandwich.", "참치 샌드위치."),
    "unemployed":    ("/ˌʌnɪmˈplɔɪd/", "형용사", "실직한", "Unemployed workers.", "실직한 노동자들."),
    "validate":      ("/ˈvælɪdeɪt/", "동사", "검증하다", "Validate the ticket.", "티켓을 검증하세요."),
    "vanilla":       ("/vəˈnɪlə/", "명사", "바닐라", "Vanilla ice cream.", "바닐라 아이스크림."),
    "willingness":   ("/ˈwɪlɪŋnɪs/", "명사", "의지, 자발성", "Show willingness.", "의지를 보여주세요."),
    "wristwatch":    ("/ˈrɪstwɒtʃ/", "명사", "손목시계", "Wear a wristwatch.", "손목시계를 착용하세요."),
    "abide":         ("/əˈbaɪd/", "동사", "지키다, 참다", "Abide by the rules.", "규칙을 지키세요."),
    "actively":      ("/ˈæktɪvli/", "부사", "능동적으로", "Actively participate.", "능동적으로 참여하세요."),
    "allergy":       ("/ˈælərʤi/", "명사", "알레르기", "Food allergy.", "식품 알레르기."),
    "apprehensive":  ("/ˌæprɪˈhɛnsɪv/", "형용사", "불안한, 걱정하는", "Apprehensive about changes.", "변화에 대해 불안한."),
    "automotive":    ("/ˌɔːtəˈmoʊtɪv/", "형용사", "자동차의", "Automotive industry.", "자동차 산업."),
    "bacteria":      ("/bækˈtɪəriə/", "명사", "박테리아", "Kill bacteria.", "박테리아를 죽이세요."),
    "broaden":       ("/ˈbrɔːdən/", "동사", "넓히다, 확장하다", "Broaden your knowledge.", "지식을 넓히세요."),
    "bulb":          ("/bʌlb/", "명사", "전구", "Change the bulb.", "전구를 교체하세요."),
    "cheer":         ("/tʃɪər/", "동사", "응원하다, 기운을 북돋우다", "Cheer the team.", "팀을 응원하세요."),
    "complication":  ("/ˌkɒmplɪˈkeɪʃən/", "명사", "합병증, 복잡성", "Medical complication.", "의료 합병증."),
    "considerate":   ("/kənˈsɪdərɪt/", "형용사", "배려하는", "Be considerate.", "배려하세요."),
    "daytime":       ("/ˈdeɪtaɪm/", "명사", "낮 시간", "Daytime hours.", "낮 시간."),
    "decoration":    ("/ˌdɛkəˈreɪʃən/", "명사", "장식", "Holiday decoration.", "휴일 장식."),
    "discard":       ("/dɪˈskɑːrd/", "동사", "버리다", "Discard old papers.", "오래된 서류를 버리세요."),
    "drastically":   ("/ˈdræstɪkli/", "부사", "급격하게", "Changed drastically.", "급격하게 변했다."),
    "erase":         ("/ɪˈreɪz/", "동사", "지우다", "Erase the mistake.", "실수를 지우세요."),
    "explorer":      ("/ɪkˈsplɔːrər/", "명사", "탐험가", "A bold explorer.", "대담한 탐험가."),
    "factual":       ("/ˈfæktʃuəl/", "형용사", "사실에 기반한", "Factual information.", "사실에 기반한 정보."),
    "fixture":       ("/ˈfɪkstʃər/", "명사", "고정 기구, 비품", "Light fixture.", "조명 기구."),
    "footwear":      ("/ˈfʊtwɛər/", "명사", "신발", "Appropriate footwear.", "적절한 신발."),
    "genre":         ("/ˈʒɑːnrə/", "명사", "장르", "Music genre.", "음악 장르."),
    "gymnasium":     ("/dʒɪmˈneɪziəm/", "명사", "체육관", "Use the gymnasium.", "체육관을 이용하세요."),
    "hereby":        ("/ˌhɪərˈbaɪ/", "부사", "이로써", "Hereby declared.", "이로써 선언한다."),
    "hesitation":    ("/ˌhɛzɪˈteɪʃən/", "명사", "망설임", "Without hesitation.", "망설임 없이."),
    "homemade":      ("/ˌhoʊmˈmeɪd/", "형용사", "집에서 만든", "Homemade cookies.", "집에서 만든 쿠키."),
    "hospitality":   ("/ˌhɒspɪˈtælɪti/", "명사", "환대, 접대", "Warm hospitality.", "따뜻한 환대."),
    "incoming":      ("/ˈɪnkʌmɪŋ/", "형용사", "들어오는", "Incoming mail.", "수신 메일."),
    "induction":     ("/ɪnˈdʌkʃən/", "명사", "유도, 취임", "Employee induction.", "직원 취임식."),
    "inspiration":   ("/ˌɪnspɪˈreɪʃən/", "명사", "영감", "Find inspiration.", "영감을 찾으세요."),
    "intently":      ("/ɪnˈtɛntli/", "부사", "열심히, 주의 깊게", "Listen intently.", "주의 깊게 들으세요."),
    "mower":         ("/ˈmoʊər/", "명사", "잔디 깎는 기계", "Lawn mower.", "잔디 깎는 기계."),
    "nutrition":     ("/njuːˈtrɪʃən/", "명사", "영양", "Good nutrition.", "좋은 영양."),
    "restatement":   ("/riːˈsteɪtmənt/", "명사", "재진술", "Financial restatement.", "재무 재진술."),
    "sedan":         ("/sɪˈdæn/", "명사", "세단", "Family sedan.", "가족용 세단."),
    "sunscreen":     ("/ˈsʌnskriːn/", "명사", "자외선 차단제", "Apply sunscreen.", "자외선 차단제를 바르세요."),
    "wellness":      ("/ˈwɛlnɪs/", "명사", "건강, 웰빙", "Wellness program.", "건강 프로그램."),
    "workbook":      ("/ˈwɜːrkbʊk/", "명사", "워크북, 연습장", "Fill in the workbook.", "워크북을 채우세요."),
    "bookcase":      ("/ˈbʊkkeɪs/", "명사", "책장", "Organize the bookcase.", "책장을 정리하세요."),
    "cleanliness":   ("/ˈklɛnlinɪs/", "명사", "청결", "Maintain cleanliness.", "청결을 유지하세요."),
    "contestant":    ("/kənˈtɛstənt/", "명사", "참가자", "The contestant won.", "참가자가 이겼다."),
    "ethics":        ("/ˈɛθɪks/", "명사", "윤리", "Business ethics.", "비즈니스 윤리."),
    "healthful":     ("/ˈhɛlθfəl/", "형용사", "건강에 좋은", "Healthful diet.", "건강에 좋은 식단."),
    "inefficient":   ("/ˌɪnɪˈfɪʃənt/", "형용사", "비효율적인", "Inefficient process.", "비효율적인 과정."),
    "liter":         ("/ˈliːtər/", "명사", "리터", "Two liters.", "2리터."),
    "recession":     ("/rɪˈsɛʃən/", "명사", "불황, 후퇴", "Economic recession.", "경기 불황."),
    "timeline":      ("/ˈtaɪmlaɪn/", "명사", "타임라인", "Project timeline.", "프로젝트 타임라인."),
    "unreliable":    ("/ˌʌnrɪˈlaɪəbəl/", "형용사", "믿을 수 없는", "Unreliable information.", "믿을 수 없는 정보."),
    "acclaim":       ("/əˈkleɪm/", "명사", "호평, 찬사", "Received acclaim.", "호평을 받았다."),
    "chronic":       ("/ˈkrɒnɪk/", "형용사", "만성적인", "Chronic disease.", "만성 질환."),
    "deteriorate":   ("/dɪˈtɪəriəreɪt/", "동사", "악화되다", "Conditions deteriorated.", "상황이 악화됐다."),
    "resemble":      ("/rɪˈzɛmbəl/", "동사", "닮다", "She resembles her mother.", "그녀는 어머니를 닮았다."),
    "unauthorized":  ("/ʌnˈɔːθəraɪzd/", "형용사", "무단의", "Unauthorized access.", "무단 접근."),
    "violate":       ("/ˈvaɪəleɪt/", "동사", "위반하다", "Violate the terms.", "약관을 위반하다."),
    "unplug":        ("/ʌnˈplʌɡ/", "동사", "플러그를 뽑다", "Unplug the device.", "기기의 플러그를 뽑으세요."),
    "videoconference":("/ˈvɪdiəʊˌkɒnfərəns/", "명사", "화상 회의", "Join the videoconference.", "화상 회의에 참가하세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT14:
                    pron, pos, meaning, ex_en, ex_ko = DICT14[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more14.py ===\n")
    patch_files()
