#!/usr/bin/env python3
"""Patch fallback entries: academic-L3 (105) + academic-L4 (119)"""
import json, glob

DICT20 = {
    # academic-L3 remaining
    "basin": ("/ˈbeɪsən/", "명사", "분지, 유역", "The river basin was studied.", "강 유역이 연구됐다."),
    "interestingly": ("/ˈɪntrɪstɪŋli/", "부사", "흥미롭게도", "Interestingly, results varied.", "흥미롭게도 결과가 다양했다."),
    "curriculum": ("/kəˈrɪkjʊləm/", "명사", "교육과정", "The curriculum was revised.", "교육과정이 개정됐다."),
    "displacement": ("/dɪsˈpleɪsmənt/", "명사", "변위, 이동", "Vertical displacement was measured.", "수직 변위가 측정됐다."),
    "coherent": ("/koʊˈhɪərənt/", "형용사", "일관된, 논리적인", "A coherent argument was made.", "일관된 논증이 제시됐다."),
    "civilization": ("/ˌsɪvəlaɪˈzeɪʃən/", "명사", "문명", "Ancient civilizations were studied.", "고대 문명이 연구됐다."),
    "bacterial": ("/bækˈtɪərɪəl/", "형용사", "박테리아의", "Bacterial infection was treated.", "박테리아 감염이 치료됐다."),
    "exponential": ("/ˌekspəˈnenʃəl/", "형용사", "지수적인", "Exponential growth was observed.", "지수적 성장이 관찰됐다."),
    "progression": ("/prəˈɡreʃən/", "명사", "진행, 발전", "Disease progression was tracked.", "질병 진행이 추적됐다."),
    "cylinder": ("/ˈsɪlɪndər/", "명사", "원통", "A cylinder volume formula applies.", "원통 부피 공식이 적용된다."),
    "sodium": ("/ˈsoʊdɪəm/", "명사", "나트륨", "Sodium intake affects blood pressure.", "나트륨 섭취가 혈압에 영향을 미친다."),
    "predominantly": ("/prɪˈdɒmɪnəntli/", "부사", "주로", "The sample was predominantly male.", "표본은 주로 남성이었다."),
    "oscillation": ("/ˌɒsɪˈleɪʃən/", "명사", "진동, 진폭", "Wave oscillation was measured.", "파동 진동이 측정됐다."),
    "impulse": ("/ˈɪmpʌls/", "명사", "충동, 충격", "Nerve impulses travel fast.", "신경 충동이 빠르게 이동한다."),
    "theorist": ("/ˈθɪərɪst/", "명사", "이론가", "The theorist proposed a model.", "이론가가 모델을 제안했다."),
    "crystal": ("/ˈkrɪstəl/", "명사", "결정, 크리스탈", "Crystal structures were analyzed.", "결정 구조가 분석됐다."),
    "nest": ("/nest/", "명사", "둥지, 집합", "Nested data structures were used.", "중첩된 데이터 구조가 사용됐다."),
    "fossil": ("/ˈfɒsəl/", "명사", "화석", "Fossil fuels must be reduced.", "화석 연료를 줄여야 한다."),
    "resistant": ("/rɪˈzɪstənt/", "형용사", "저항하는", "Drug resistant bacteria emerged.", "약물 내성 박테리아가 나타났다."),
    "dimensional": ("/daɪˈmenʃənəl/", "형용사", "차원의", "Three-dimensional modeling was used.", "3차원 모델링이 사용됐다."),
    "artifact": ("/ˈɑːrtɪfækt/", "명사", "인공물, 유물", "Historical artifacts were preserved.", "역사적 유물이 보존됐다."),
    "surgical": ("/ˈsɜːrdʒɪkəl/", "형용사", "외과의", "Surgical intervention was needed.", "외과적 개입이 필요했다."),
    "turbulent": ("/ˈtɜːrbjʊlənt/", "형용사", "격동적인, 난류의", "Turbulent flow was analyzed.", "난류 흐름이 분석됐다."),
    "quantum": ("/ˈkwɒntəm/", "명사", "양자", "Quantum mechanics is complex.", "양자 역학은 복잡하다."),
    "sediment": ("/ˈsedɪmənt/", "명사", "침전물", "Sediment layers were analyzed.", "침전물 층이 분석됐다."),
    "conserve": ("/kənˈsɜːrv/", "동사", "보존하다", "Energy must be conserved.", "에너지를 보존해야 한다."),
    "primer": ("/ˈpraɪmər/", "명사", "입문서, 프라이머", "A DNA primer was designed.", "DNA 프라이머가 설계됐다."),
    "terminology": ("/ˌtɜːrmɪˈnɒlədʒi/", "명사", "전문 용어", "Technical terminology was defined.", "기술 전문 용어가 정의됐다."),
    "vegetation": ("/ˌvedʒɪˈteɪʃən/", "명사", "식물, 초목", "Vegetation cover declined.", "식물 피복이 감소했다."),
    "triangle": ("/ˈtraɪæŋɡəl/", "명사", "삼각형", "The triangle inequality holds.", "삼각 부등식이 성립한다."),
    "reconstruct": ("/ˌriːkənˈstrʌkt/", "동사", "재구성하다", "Ancestral sequences were reconstructed.", "조상 서열이 재구성됐다."),
    "metabolism": ("/məˈtæbəlɪzəm/", "명사", "대사", "Cellular metabolism was measured.", "세포 대사가 측정됐다."),
    "motif": ("/moʊˈtiːf/", "명사", "모티프, 주제", "A recurring motif was identified.", "반복되는 모티프가 확인됐다."),
    "dissertation": ("/ˌdɪsəˈteɪʃən/", "명사", "논문", "A dissertation was submitted.", "논문이 제출됐다."),
    "susceptible": ("/səˈseptɪbəl/", "형용사", "취약한, 민감한", "Children are susceptible to illness.", "아이들이 질병에 취약하다."),
    "coronary": ("/ˈkɒrənəri/", "형용사", "관상동맥의", "Coronary disease was studied.", "관상동맥 질환이 연구됐다."),
    "inject": ("/ɪnˈdʒekt/", "동사", "주입하다", "Vaccine was injected.", "백신이 주입됐다."),
    "polar": ("/ˈpoʊlər/", "형용사", "극의, 양극의", "Polar coordinates were used.", "극좌표가 사용됐다."),
    "morality": ("/məˈrælɪti/", "명사", "도덕성", "Morality guides behavior.", "도덕성이 행동을 안내한다."),
    "communicative": ("/kəˈmjuːnɪkətɪv/", "형용사", "의사소통적인", "Communicative competence was assessed.", "의사소통 능력이 평가됐다."),
    "inferior": ("/ɪnˈfɪərɪər/", "형용사", "열등한", "Inferior goods were rejected.", "열등 재화가 거부됐다."),
    "elementary": ("/ˌelɪˈmentəri/", "형용사", "기본적인, 초등의", "Elementary particles were studied.", "기본 입자가 연구됐다."),
    "initiation": ("/ɪˌnɪʃɪˈeɪʃən/", "명사", "시작, 입문", "Initiation of transcription.", "전사의 시작."),
    "rotate": ("/roʊˈteɪt/", "동사", "회전하다", "The molecule rotates freely.", "분자가 자유롭게 회전한다."),
    "elevation": ("/ˌelɪˈveɪʃən/", "명사", "고도, 높이", "Elevation affects climate.", "고도가 기후에 영향을 미친다."),
    "atomic": ("/əˈtɒmɪk/", "형용사", "원자의", "Atomic mass was calculated.", "원자 질량이 계산됐다."),
    "trivial": ("/ˈtrɪvɪəl/", "형용사", "사소한", "The error was trivial.", "오류가 사소했다."),
    "profound": ("/prəˈfaʊnd/", "형용사", "심오한, 깊은", "Profound changes occurred.", "심오한 변화가 일어났다."),
    "ancestor": ("/ˈænsestər/", "명사", "조상", "Common ancestors were identified.", "공통 조상이 확인됐다."),
    "genetics": ("/dʒɪˈnetɪks/", "명사", "유전학", "Genetics explains inheritance.", "유전학이 유전을 설명한다."),
    "proton": ("/ˈproʊtɒn/", "명사", "양성자", "Protons carry positive charge.", "양성자가 양전하를 운반한다."),
    "phosphate": ("/ˈfɒsfeɪt/", "명사", "인산염", "Phosphate is essential for ATP.", "인산염이 ATP에 필수적이다."),
    "gravity": ("/ˈɡrævɪti/", "명사", "중력", "Gravity holds objects down.", "중력이 물체를 아래로 잡아당긴다."),
    "respiratory": ("/rɪˈspɪrətəri/", "형용사", "호흡의", "Respiratory function was tested.", "호흡 기능이 테스트됐다."),
    "elimination": ("/ɪˌlɪmɪˈneɪʃən/", "명사", "제거, 탈락", "Gaussian elimination was applied.", "가우시안 소거법이 적용됐다."),
    "trauma": ("/ˈtrɔːmə/", "명사", "외상, 트라우마", "Psychological trauma was treated.", "심리적 외상이 치료됐다."),
    "optical": ("/ˈɒptɪkəl/", "형용사", "광학의", "Optical instruments were used.", "광학 기구가 사용됐다."),
    "limb": ("/lɪm/", "명사", "팔다리, 가지", "Limb development was studied.", "팔다리 발달이 연구됐다."),
    "rationality": ("/ˌræʃəˈnælɪti/", "명사", "합리성", "Bounded rationality limits decisions.", "제한된 합리성이 의사결정을 제한한다."),
    "stereotype": ("/ˈsterɪətaɪp/", "명사", "고정관념", "Stereotypes affect behavior.", "고정관념이 행동에 영향을 미친다."),
    "slavery": ("/ˈsleɪvəri/", "명사", "노예제", "Slavery was abolished.", "노예제가 폐지됐다."),
    "anthropology": ("/ˌænθrəˈpɒlədʒi/", "명사", "인류학", "Cultural anthropology was studied.", "문화 인류학이 연구됐다."),
    "antibiotic": ("/ˌæntɪbaɪˈɒtɪk/", "명사", "항생제", "Antibiotic resistance grew.", "항생제 내성이 증가했다."),
    "sexuality": ("/ˌsekʃuˈælɪti/", "명사", "성정체성", "Human sexuality was studied.", "인간 성정체성이 연구됐다."),
    "axiom": ("/ˈæksɪəm/", "명사", "공리", "Mathematical axioms were stated.", "수학적 공리가 서술됐다."),
    "pest": ("/pest/", "명사", "해충", "Pest control was implemented.", "해충 방제가 시행됐다."),
    "fracture": ("/ˈfræktʃər/", "명사", "골절, 균열", "A stress fracture was found.", "스트레스 골절이 발견됐다."),
    "transplant": ("/ˈtrænsplɑːnt/", "명사", "이식", "Organ transplant was successful.", "장기 이식이 성공했다."),
    "epidemic": ("/ˌepɪˈdemɪk/", "명사", "유행병", "An epidemic was declared.", "유행병이 선언됐다."),
    "inversion": ("/ɪnˈvɜːrʒən/", "명사", "역전, 역순", "Temperature inversion occurred.", "기온 역전이 발생했다."),
    "epidemiology": ("/ˌepɪˌdiːmɪˈɒlədʒi/", "명사", "역학", "Epidemiology tracks disease spread.", "역학이 질병 확산을 추적한다."),
    "infectious": ("/ɪnˈfekʃəs/", "형용사", "전염성의", "An infectious disease spread.", "전염성 질환이 확산됐다."),
    "psychologist": ("/saɪˈkɒlədʒɪst/", "명사", "심리학자", "A psychologist conducted tests.", "심리학자가 테스트를 진행했다."),
    "trans": ("/træns/", "접두사", "가로질러, 변화", "Trans-membrane proteins exist.", "막관통 단백질이 존재한다."),
    "irrigation": ("/ˌɪrɪˈɡeɪʃən/", "명사", "관개", "Irrigation expanded crop yields.", "관개가 작물 수확량을 늘렸다."),
    "rehabilitation": ("/ˌriːəˌbɪlɪˈteɪʃən/", "명사", "재활", "Physical rehabilitation helped recovery.", "물리 재활이 회복을 도왔다."),
    "illusion": ("/ɪˈluːʒən/", "명사", "환상, 착각", "An optical illusion was created.", "착시 현상이 만들어졌다."),
    "bat": ("/bæt/", "명사", "박쥐", "Bat echolocation was studied.", "박쥐 반향정위가 연구됐다."),
    "fever": ("/ˈfiːvər/", "명사", "열, 발열", "A high fever developed.", "고열이 생겼다."),
    "paradox": ("/ˈpærədɒks/", "명사", "역설", "Jevons paradox was described.", "제번스의 역설이 설명됐다."),
    "kidney": ("/ˈkɪdni/", "명사", "신장", "Kidney function was measured.", "신장 기능이 측정됐다."),
    "predator": ("/ˈpredətər/", "명사", "포식자", "Predator-prey dynamics were modeled.", "포식자-피식자 역학이 모델링됐다."),
    "migrate": ("/maɪˈɡreɪt/", "동사", "이동하다, 이주하다", "Birds migrate seasonally.", "새들이 계절에 따라 이동한다."),
    "infinity": ("/ɪnˈfɪnɪti/", "명사", "무한대", "The series approaches infinity.", "급수가 무한대에 접근한다."),
    "shallow": ("/ˈʃæloʊ/", "형용사", "얕은", "Shallow water effects were studied.", "얕은 물의 효과가 연구됐다."),
    "fundamentally": ("/ˌfʌndəˈmentəli/", "부사", "근본적으로", "The theory is fundamentally flawed.", "이론이 근본적으로 결함이 있다."),
    "hepatitis": ("/ˌhepəˈtaɪtɪs/", "명사", "간염", "Hepatitis B vaccination is required.", "B형 간염 예방접종이 필요하다."),
    "contradictory": ("/ˌkɒntrəˈdɪktəri/", "형용사", "모순적인", "Contradictory evidence was found.", "모순적인 증거가 발견됐다."),
    "sensation": ("/senˈseɪʃən/", "명사", "감각, 센세이션", "Pain sensation was reduced.", "통증 감각이 감소됐다."),
    "prey": ("/preɪ/", "명사", "먹이", "Prey populations declined.", "먹이 개체수가 감소했다."),
    "cyclic": ("/ˈsɪklɪk/", "형용사", "순환적인", "Cyclic patterns were identified.", "순환적 패턴이 확인됐다."),
    "friction": ("/ˈfrɪkʃən/", "명사", "마찰", "Friction reduces efficiency.", "마찰이 효율을 줄인다."),
    "parenthesis": ("/pəˈrenθəsɪs/", "명사", "괄호", "Use parentheses correctly.", "괄호를 올바르게 사용하세요."),
    "noble": ("/ˈnoʊbəl/", "형용사", "고귀한, 비활성의", "Noble gases are stable.", "비활성 기체는 안정적이다."),
    "potassium": ("/pəˈtæsɪəm/", "명사", "칼륨", "Potassium is essential for nerves.", "칼륨이 신경에 필수적이다."),
    "reactive": ("/riˈæktɪv/", "형용사", "반응성이 있는", "Highly reactive elements were tested.", "반응성이 높은 원소가 테스트됐다."),
    "genetically": ("/dʒɪˈnetɪkli/", "부사", "유전적으로", "Genetically modified crops exist.", "유전자 변형 작물이 존재한다."),
    "realism": ("/ˈriːəlɪzəm/", "명사", "사실주의, 현실주의", "Economic realism prevailed.", "경제적 현실주의가 우세했다."),
    "chemotherapy": ("/ˌkiːmoʊˈθerəpi/", "명사", "화학요법", "Chemotherapy was administered.", "화학요법이 투여됐다."),
    "capillary": ("/ˈkæpɪləri/", "명사", "모세혈관", "Capillary action draws water up.", "모세관 작용이 물을 끌어올린다."),
    "alien": ("/ˈeɪlɪən/", "형용사", "외래의, 낯선", "Alien species disrupted ecosystems.", "외래종이 생태계를 교란했다."),
    "invert": ("/ɪnˈvɜːrt/", "동사", "역전시키다, 뒤집다", "The matrix was inverted.", "행렬이 역전됐다."),
    "thread": ("/θred/", "명사", "실, 스레드", "A thread of logic was followed.", "논리의 실마리가 따라졌다."),
    "clay": ("/kleɪ/", "명사", "점토", "Clay soil retains water.", "점토 토양이 물을 보유한다."),
    "dye": ("/daɪ/", "명사", "염료", "Fluorescent dyes were used.", "형광 염료가 사용됐다."),
    # academic-L4 remaining
    "secrete": ("/sɪˈkriːt/", "동사", "분비하다", "The gland secretes hormones.", "샘이 호르몬을 분비한다."),
    "hip": ("/hɪp/", "명사", "엉덩이", "Hip fractures are common.", "엉덩이 골절이 흔하다."),
    "plantation": ("/plænˈteɪʃən/", "명사", "농장, 플랜테이션", "Plantation crops included sugar.", "플랜테이션 작물에는 설탕이 포함됐다."),
    "onwards": ("/ˈɒnwədz/", "부사", "이후로, 앞으로", "From 2000 onwards, growth accelerated.", "2000년 이후로 성장이 가속됐다."),
    "helix": ("/ˈhiːlɪks/", "명사", "나선", "The DNA double helix was discovered.", "DNA 이중 나선이 발견됐다."),
    "domination": ("/ˌdɒmɪˈneɪʃən/", "명사", "지배, 독점", "Market domination was achieved.", "시장 지배가 달성됐다."),
    "undergraduate": ("/ˌʌndəˈɡrædʒʊɪt/", "명사", "학부생", "Undergraduate enrollment rose.", "학부 등록이 증가했다."),
    "soluble": ("/ˈsɒljʊbəl/", "형용사", "용해 가능한", "Soluble fiber aids digestion.", "수용성 섬유가 소화를 돕는다."),
    "innate": ("/ɪˈneɪt/", "형용사", "선천적인", "Innate immunity protects us.", "선천 면역이 우리를 보호한다."),
    "goat": ("/ɡoʊt/", "명사", "염소", "Goat milk is nutritious.", "염소 젖은 영양가가 있다."),
    "emit": ("/ɪˈmɪt/", "동사", "방출하다, 배출하다", "The process emits CO2.", "프로세스가 CO2를 배출한다."),
    "confound": ("/kənˈfaʊnd/", "동사", "혼동시키다, 교란하다", "Confounding variables were controlled.", "교란 변수가 통제됐다."),
    "degrade": ("/dɪˈɡreɪd/", "동사", "분해하다, 저하시키다", "Enzymes degrade molecules.", "효소가 분자를 분해한다."),
    "fungus": ("/ˈfʌŋɡəs/", "명사", "균류, 곰팡이", "Fungal infections were treated.", "균류 감염이 치료됐다."),
    "reservoir": ("/ˈrezəvwɑːr/", "명사", "저수지, 저장소", "A water reservoir was built.", "저수지가 건설됐다."),
    "footnote": ("/ˈfʊtnoʊt/", "명사", "각주", "A footnote clarified the point.", "각주가 내용을 명확히 했다."),
    "bodily": ("/ˈbɒdɪli/", "형용사", "신체의, 육체의", "Bodily functions were measured.", "신체 기능이 측정됐다."),
    "affirm": ("/əˈfɜːrm/", "동사", "확인하다, 단언하다", "The hypothesis was affirmed.", "가설이 확인됐다."),
    "urine": ("/ˈjʊərɪn/", "명사", "소변", "Urine samples were tested.", "소변 샘플이 테스트됐다."),
    "antiquity": ("/ænˈtɪkwɪti/", "명사", "고대", "In antiquity, trade routes formed.", "고대에 무역로가 형성됐다."),
    "toxic": ("/ˈtɒksɪk/", "형용사", "독성의", "Toxic substances were removed.", "독성 물질이 제거됐다."),
    "yeast": ("/jiːst/", "명사", "효모", "Yeast cells were cultured.", "효모 세포가 배양됐다."),
    "bleed": ("/bliːd/", "동사", "출혈하다", "The wound bled heavily.", "상처가 심하게 출혈했다."),
    "goodness": ("/ˈɡʊdnəs/", "명사", "선, 적합성", "Goodness of fit was tested.", "적합도가 테스트됐다."),
    "legend": ("/ˈledʒənd/", "명사", "범례, 전설", "The graph legend was labeled.", "그래프 범례가 표시됐다."),
    "abdominal": ("/æbˈdɒmɪnəl/", "형용사", "복부의", "Abdominal muscles were examined.", "복부 근육이 검사됐다."),
    "precipitation": ("/prɪˌsɪpɪˈteɪʃən/", "명사", "강수, 침전", "Annual precipitation was measured.", "연간 강수량이 측정됐다."),
    "founds": ("/faʊndz/", "동사", "설립하다", "The institute founds new research.", "연구소가 새 연구를 설립한다."),
    "interviewer": ("/ˈɪntəvjuːər/", "명사", "면접관", "The interviewer recorded responses.", "면접관이 응답을 기록했다."),
    "gut": ("/ɡʌt/", "명사", "장, 직관", "Gut microbiome was analyzed.", "장내 미생물군이 분석됐다."),
    "emperor": ("/ˈempərər/", "명사", "황제", "The emperor's policies influenced trade.", "황제의 정책이 무역에 영향을 미쳤다."),
    "altitude": ("/ˈæltɪtjuːd/", "명사", "고도", "High altitude affects performance.", "높은 고도가 성과에 영향을 미친다."),
    "chloride": ("/ˈklɔːraɪd/", "명사", "염화물", "Sodium chloride is table salt.", "염화나트륨이 식염이다."),
    "weave": ("/wiːv/", "동사", "엮다, 짜다", "Data was woven into a narrative.", "데이터가 이야기로 엮였다."),
    "precipitate": ("/prɪˈsɪpɪteɪt/", "동사", "유발하다, 침전시키다", "The event precipitated a crisis.", "사건이 위기를 유발했다."),
    "industrialization": ("/ɪnˌdʌstrɪəlaɪˈzeɪʃən/", "명사", "산업화", "Rapid industrialization occurred.", "급격한 산업화가 발생했다."),
    "conduction": ("/kənˈdʌkʃən/", "명사", "전도", "Heat conduction was measured.", "열 전도가 측정됐다."),
    "facet": ("/ˈfæsɪt/", "명사", "측면, 면", "Multiple facets were studied.", "다양한 측면이 연구됐다."),
    "splice": ("/splaɪs/", "동사", "접합하다", "Genes were spliced together.", "유전자가 함께 접합됐다."),
    "biodiversity": ("/ˌbaɪoʊdaɪˈvɜːrsɪti/", "명사", "생물 다양성", "Biodiversity declined sharply.", "생물 다양성이 크게 감소했다."),
    "tutor": ("/ˈtjuːtər/", "명사", "교사, 개인 지도 교사", "A tutor helped with studies.", "교사가 학습을 도왔다."),
    "fin": ("/fɪn/", "명사", "지느러미", "Fish fin structure was studied.", "물고기 지느러미 구조가 연구됐다."),
    "marble": ("/ˈmɑːrbəl/", "명사", "대리석", "Marble is a metamorphic rock.", "대리석은 변성암이다."),
    "pesticide": ("/ˈpestɪsaɪd/", "명사", "살충제", "Pesticide use was regulated.", "살충제 사용이 규제됐다."),
    "biologist": ("/baɪˈɒlədʒɪst/", "명사", "생물학자", "A biologist conducted the study.", "생물학자가 연구를 수행했다."),
    "connotation": ("/ˌkɒnəˈteɪʃən/", "명사", "함축 의미", "Cultural connotations differ.", "문화적 함축 의미가 다르다."),
    "snake": ("/sneɪk/", "명사", "뱀", "Snake venom was analyzed.", "뱀독이 분석됐다."),
    "flesh": ("/fleʃ/", "명사", "살, 과육", "Flesh wounds were examined.", "살 상처가 검사됐다."),
    "ghost": ("/ɡoʊst/", "명사", "유령", "Ghost genes were identified.", "유령 유전자가 확인됐다."),
    "marrow": ("/ˈmæroʊ/", "명사", "골수", "Bone marrow transplant helped.", "골수 이식이 도움이 됐다."),
    "surgeon": ("/ˈsɜːrdʒən/", "명사", "외과의사", "A surgeon performed the operation.", "외과의사가 수술을 집도했다."),
    "industrialize": ("/ɪnˈdʌstrɪəlaɪz/", "동사", "산업화하다", "Nations began to industrialize.", "국가들이 산업화하기 시작했다."),
    "denominator": ("/dɪˈnɒmɪneɪtər/", "명사", "분모", "The common denominator was found.", "공통 분모가 발견됐다."),
    "solvent": ("/ˈsɒlvənt/", "명사", "용매", "The solvent dissolved the compound.", "용매가 화합물을 용해했다."),
    "slab": ("/slæb/", "명사", "판, 슬라브", "Concrete slabs were poured.", "콘크리트 판이 타설됐다."),
    "naked": ("/ˈneɪkɪd/", "형용사", "맨눈의, 벌거벗은", "Visible to the naked eye.", "맨눈으로 보인다."),
    "powder": ("/ˈpaʊdər/", "명사", "분말, 가루", "Powder samples were analyzed.", "분말 샘플이 분석됐다."),
    "solute": ("/ˈsɒljuːt/", "명사", "용질", "Solute concentration was measured.", "용질 농도가 측정됐다."),
    "dissection": ("/dɪˈsekʃən/", "명사", "해부", "Lab dissection was performed.", "실험실 해부가 수행됐다."),
    "censor": ("/ˈsensər/", "동사", "검열하다", "Data was censored.", "데이터가 검열됐다."),
    "portrayal": ("/pɔːrˈtreɪəl/", "명사", "묘사, 표현", "Media portrayal was biased.", "미디어 묘사가 편향됐다."),
    "acidic": ("/əˈsɪdɪk/", "형용사", "산성의", "Acidic conditions were tested.", "산성 조건이 테스트됐다."),
    "uplift": ("/ˈʌplɪft/", "명사", "고양, 융기", "Tectonic uplift was measured.", "지각 융기가 측정됐다."),
    "flip": ("/flɪp/", "동사", "뒤집다", "The sign flipped to negative.", "부호가 음수로 뒤집혔다."),
    "congruent": ("/ˈkɒŋɡrʊənt/", "형용사", "합동의, 일치하는", "Congruent triangles were proven.", "합동 삼각형이 증명됐다."),
    "skip": ("/skɪp/", "동사", "건너뛰다", "The sequence was skipped.", "수열이 건너뛰어졌다."),
    "sword": ("/sɔːrd/", "명사", "검, 칼", "Swords were studied archaeologically.", "검이 고고학적으로 연구됐다."),
    "photographic": ("/ˌfoʊtəˈɡræfɪk/", "형용사", "사진의", "Photographic evidence was presented.", "사진 증거가 제시됐다."),
    "nicely": ("/ˈnaɪsli/", "부사", "잘, 깔끔하게", "The model fits nicely.", "모델이 잘 맞는다."),
    "quiz": ("/kwɪz/", "명사", "퀴즈", "A diagnostic quiz was given.", "진단 퀴즈가 제공됐다."),
    "watershed": ("/ˈwɔːtərʃed/", "명사", "분수령, 전환점", "A watershed moment occurred.", "전환점이 됐다."),
    "oxidize": ("/ˈɒksɪdaɪz/", "동사", "산화하다", "Iron oxidizes to form rust.", "철이 산화해 녹이 된다."),
    "mercury": ("/ˈmɜːrkjʊri/", "명사", "수은", "Mercury levels were tested.", "수은 수준이 테스트됐다."),
    "phenomenal": ("/fɪˈnɒmɪnəl/", "형용사", "놀라운, 비범한", "Phenomenal growth was observed.", "놀라운 성장이 관찰됐다."),
    "comma": ("/ˈkɒmə/", "명사", "쉼표", "Commas separate list items.", "쉼표가 목록 항목을 구분한다."),
    "bizarre": ("/bɪˈzɑːr/", "형용사", "기이한", "Bizarre results were obtained.", "기이한 결과가 얻어졌다."),
    "socialize": ("/ˈsoʊʃəlaɪz/", "동사", "사회화하다", "Children socialize at school.", "아이들이 학교에서 사회화한다."),
    "novice": ("/ˈnɒvɪs/", "명사", "초심자", "Novices learned quickly.", "초심자들이 빠르게 배웠다."),
    "enormously": ("/ɪˈnɔːrməsli/", "부사", "엄청나게", "The field grew enormously.", "분야가 엄청나게 성장했다."),
    "rope": ("/roʊp/", "명사", "밧줄, 로프", "Molecular ropes were formed.", "분자 로프가 형성됐다."),
    "mole": ("/moʊl/", "명사", "몰 (단위)", "One mole contains 6×10²³ molecules.", "1몰은 6×10²³개의 분자를 포함한다."),
    "bucket": ("/ˈbʌkɪt/", "명사", "양동이, 버킷", "Data was sorted into buckets.", "데이터가 버킷으로 분류됐다."),
    "deflection": ("/dɪˈflekʃən/", "명사", "편향, 굴절", "Beam deflection was calculated.", "빔 편향이 계산됐다."),
    "deceive": ("/dɪˈsiːv/", "동사", "속이다", "Misleading graphs deceive readers.", "오해를 유발하는 그래프가 독자를 속인다."),
    "syllabus": ("/ˈsɪləbəs/", "명사", "강의 계획서", "The syllabus was updated.", "강의 계획서가 업데이트됐다."),
    "factorial": ("/fækˈtɔːrɪəl/", "명사", "계승, 팩토리얼", "Factorial notation was used.", "계승 표기법이 사용됐다."),
    "lever": ("/ˈliːvər/", "명사", "지렛대", "Financial leverage acts as a lever.", "재무 레버리지가 지렛대 역할을 한다."),
    "descriptor": ("/dɪˈskrɪptər/", "명사", "서술자, 기술자", "Feature descriptors were extracted.", "특징 기술자가 추출됐다."),
    "underneath": ("/ˌʌndərˈniːθ/", "전치사", "아래에", "Beneath the surface, patterns exist.", "표면 아래에 패턴이 존재한다."),
    "herbicide": ("/ˈhɜːrbɪsaɪd/", "명사", "제초제", "Herbicide use declined.", "제초제 사용이 감소했다."),
    "rub": ("/rʌb/", "동사", "문지르다", "Friction is caused by rubbing.", "마찰은 문지름으로 발생한다."),
    "radar": ("/ˈreɪdɑːr/", "명사", "레이더", "Radar technology was applied.", "레이더 기술이 적용됐다."),
    "scripture": ("/ˈskrɪptʃər/", "명사", "경전", "Ancient scriptures were analyzed.", "고대 경전이 분석됐다."),
    "whichever": ("/wɪtʃˈevər/", "대명사", "어느 것이든", "Choose whichever method works.", "어느 방법이든 선택하세요."),
    "punch": ("/pʌntʃ/", "동사", "구멍을 뚫다", "Punched cards stored data.", "천공 카드가 데이터를 저장했다."),
    "postgraduate": ("/ˌpoʊstˈɡrædʒʊɪt/", "명사", "대학원생", "Postgraduate studies continued.", "대학원 학업이 계속됐다."),
    "artwork": ("/ˈɑːrtwɜːrk/", "명사", "예술 작품, 그림", "Scientific artwork was created.", "과학적 그림이 만들어졌다."),
    "pardon": ("/ˈpɑːrdən/", "명사", "용서, 사면", "Presidential pardon was granted.", "대통령 사면이 허락됐다."),
    "millimeter": ("/ˈmɪlɪmiːtər/", "명사", "밀리미터", "Precision to the millimeter.", "밀리미터 단위의 정밀도."),
    "incredible": ("/ɪnˈkredɪbəl/", "형용사", "놀라운", "Incredible results were achieved.", "놀라운 결과가 달성됐다."),
    "halfway": ("/ˌhɑːfˈweɪ/", "부사", "중간에", "Halfway through the experiment.", "실험 중간에."),
    "bang": ("/bæŋ/", "명사", "폭발, 충격", "The Big Bang theory was tested.", "빅뱅 이론이 테스트됐다."),
    "ridiculous": ("/rɪˈdɪkjʊləs/", "형용사", "터무니없는", "The assumption is ridiculous.", "가정이 터무니없다."),
    "volition": ("/vəˈlɪʃən/", "명사", "의지, 결의", "Free volition was studied.", "자유 의지가 연구됐다."),
    "aerosol": ("/ˈeərəsɒl/", "명사", "에어로졸", "Aerosol particles were measured.", "에어로졸 입자가 측정됐다."),
    "chess": ("/tʃes/", "명사", "체스", "Chess AI was developed.", "체스 AI가 개발됐다."),
    "terribly": ("/ˈterɪbli/", "부사", "끔찍하게, 몹시", "The model performed terribly.", "모델이 몹시 나쁘게 작동했다."),
    "unintelligible": ("/ˌʌnɪnˈtelɪdʒɪbəl/", "형용사", "이해할 수 없는", "The signal was unintelligible.", "신호가 이해할 수 없었다."),
    "circa": ("/ˈsɜːrkə/", "전치사", "약, ~경에", "The artifact dates to circa 500 AD.", "유물이 서기 500년경으로 추정된다."),
    "scroll": ("/skroʊl/", "명사", "두루마리, 스크롤", "Ancient scrolls were studied.", "고대 두루마리가 연구됐다."),
    "connector": ("/kəˈnektər/", "명사", "연결체", "A logical connector links clauses.", "논리적 연결어가 절을 연결한다."),
    "incredibly": ("/ɪnˈkredɪbli/", "부사", "믿을 수 없을 정도로", "Incredibly precise measurements.", "믿을 수 없을 정도로 정밀한 측정."),
    "hawk": ("/hɔːk/", "명사", "매", "Hawk behavior was observed.", "매의 행동이 관찰됐다."),
    "handout": ("/ˈhændaʊt/", "명사", "유인물", "Lecture handouts were distributed.", "강의 유인물이 배부됐다."),
    "applause": ("/əˈplɔːz/", "명사", "박수", "The presentation received applause.", "발표가 박수를 받았다."),
    "demonstrator": ("/ˈdemənstreɪtər/", "명사", "시연자, 시위자", "Lab demonstrators guided students.", "실험실 시연자들이 학생을 지도했다."),
    "sneeze": ("/sniːz/", "동사", "재채기하다", "Sneezing spreads pathogens.", "재채기가 병원균을 퍼뜨린다."),
    "sniff": ("/snɪf/", "동사", "냄새를 맡다", "Dogs sniff for chemicals.", "개들이 화학물질 냄새를 맡는다."),
    "descendent": ("/dɪˈsendənt/", "명사", "후손", "Modern humans are descendants.", "현대 인류가 후손이다."),
}


def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT20:
                    pron, pos, meaning, ex_en, ex_ko = DICT20[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")


if __name__ == "__main__":
    print("=== Patching with fill_more20.py ===\n")
    patch_files()
