#!/usr/bin/env python3
"""Fill freq-L10 (273 words)"""
import json, glob

DICT10 = {
    "penalty":       ("/ˈpɛnəlti/", "명사", "벌칙, 패널티", "Pay the penalty for being late.", "지각에 대한 벌칙을 내세요."),
    "chamber":       ("/ˈtʃeɪmbər/", "명사", "방, 의회 의사당", "The upper chamber voted yes.", "상원이 찬성 투표를 했다."),
    "fancy":         ("/ˈfænsi/", "형용사", "고급스러운, 화려한", "They stayed at a fancy hotel.", "그들은 고급 호텔에 묵었다."),
    "poetry":        ("/ˈpoʊɪtri/", "명사", "시, 시집", "She loves reading poetry.", "그녀는 시 읽기를 좋아한다."),
    "chat":          ("/tʃæt/", "동사", "잡담하다, 채팅하다", "Let's chat over coffee.", "커피를 마시며 이야기해요."),
    "clothing":      ("/ˈkloʊðɪŋ/", "명사", "의류, 옷", "Donate old clothing.", "오래된 의류를 기부하세요."),
    "evolve":        ("/ɪˈvɒlv/", "동사", "진화하다, 발전하다", "Technology evolves rapidly.", "기술은 빠르게 발전한다."),
    "sake":          ("/seɪk/", "명사", "위함, 이익", "Do it for your health's sake.", "건강을 위해 하세요."),
    "shelf":         ("/ʃɛlf/", "명사", "선반", "Put the books on the shelf.", "선반에 책을 올려두세요."),
    "boost":         ("/buːst/", "동사", "높이다, 강화하다", "Boost your confidence.", "자신감을 높이세요."),
    "tail":          ("/teɪl/", "명사", "꼬리", "The dog wagged its tail.", "개가 꼬리를 흔들었다."),
    "possession":    ("/pəˈzɛʃən/", "명사", "소유, 소유물", "Valuable possessions.", "귀중한 소유물."),
    "abortion":      ("/əˈbɔːrʃən/", "명사", "낙태, 임신 중절", "Abortion laws vary by country.", "낙태법은 나라마다 다르다."),
    "curious":       ("/ˈkjʊəriəs/", "형용사", "호기심이 많은", "Children are naturally curious.", "아이들은 자연스럽게 호기심이 많다."),
    "wooden":        ("/ˈwʊdən/", "형용사", "나무로 만든", "A wooden table.", "나무 테이블."),
    "boom":          ("/buːm/", "명사", "호황, 급성장", "A boom in tourism.", "관광업의 호황."),
    "tale":          ("/teɪl/", "명사", "이야기, 동화", "Tell me a tale.", "이야기를 들려주세요."),
    "maintenance":   ("/ˈmeɪntənəns/", "명사", "유지, 보수", "Regular maintenance is required.", "정기적인 유지 보수가 필요하다."),
    "consequently":  ("/ˈkɒnsɪkwəntli/", "부사", "결과적으로, 따라서", "Consequently, we changed plans.", "결과적으로 계획을 변경했다."),
    "pot":           ("/pɒt/", "명사", "냄비, 단지", "Boil water in a pot.", "냄비에 물을 끓이세요."),
    "cow":           ("/kaʊ/", "명사", "소, 암소", "The cow is grazing.", "소가 풀을 뜯고 있다."),
    "strengthen":    ("/ˈstrɛŋθən/", "동사", "강화하다", "Strengthen the relationship.", "관계를 강화하세요."),
    "whilst":        ("/waɪlst/", "접속사", "~하는 동안", "Read whilst listening.", "들으면서 읽으세요."),
    "constraint":    ("/kənˈstreɪnt/", "명사", "제약, 구속", "Work within constraints.", "제약 안에서 일하세요."),
    "fold":          ("/foʊld/", "동사", "접다, 折다", "Fold the paper in half.", "종이를 반으로 접으세요."),
    "bin":           ("/bɪn/", "명사", "쓰레기통, 통", "Throw it in the bin.", "쓰레기통에 버리세요."),
    "undergo":       ("/ˌʌndərˈɡoʊ/", "동사", "겪다, 받다", "Undergo surgery.", "수술을 받으세요."),
    "potentially":   ("/pəˈtɛnʃəli/", "부사", "잠재적으로", "It is potentially dangerous.", "잠재적으로 위험하다."),
    "pretend":       ("/prɪˈtɛnd/", "동사", "~인 척하다", "Don't pretend to know.", "아는 척하지 마세요."),
    "diversity":     ("/daɪˈvɜːrsɪti/", "명사", "다양성", "Embrace diversity.", "다양성을 수용하세요."),
    "allege":        ("/əˈlɛdʒ/", "동사", "주장하다, 혐의를 제기하다", "He alleged fraud.", "그는 사기 혐의를 제기했다."),
    "pride":         ("/praɪd/", "명사", "자부심, 긍지", "Take pride in your work.", "자신의 일에 자부심을 가지세요."),
    "intense":       ("/ɪnˈtɛns/", "형용사", "강렬한, 극심한", "Intense heat outside.", "밖이 극심하게 덥다."),
    "inquiry":       ("/ɪnˈkwaɪəri/", "명사", "문의, 조사", "Submit an inquiry.", "문의를 제출하세요."),
    "resign":        ("/rɪˈzaɪn/", "동사", "사임하다, 사직하다", "He resigned from his position.", "그는 자리에서 사임했다."),
    "craft":         ("/krɑːft/", "명사", "공예, 기술", "She is skilled in crafts.", "그녀는 공예에 능숙하다."),
    "strict":        ("/strɪkt/", "형용사", "엄격한, 엄밀한", "The rules are strict.", "규칙이 엄격하다."),
    "concrete":      ("/ˈkɒnkriːt/", "형용사", "구체적인, 콘크리트의", "Give concrete examples.", "구체적인 예를 들어주세요."),
    "shell":         ("/ʃɛl/", "명사", "껍데기, 조개껍질", "Pick up shells on the beach.", "해변에서 조개껍질을 줍는다."),
    "damn":          ("/dæm/", "감탄사", "제기랄, 빌어먹을", "Damn, I forgot my key.", "제기랄, 열쇠를 잊었다."),
    "distinct":      ("/dɪˈstɪŋkt/", "형용사", "뚜렷한, 별개의", "There is a distinct difference.", "뚜렷한 차이가 있다."),
    "humor":         ("/ˈhjuːmər/", "명사", "유머, 웃음", "Use humor in presentations.", "발표에서 유머를 사용하세요."),
    "limitation":    ("/ˌlɪmɪˈteɪʃən/", "명사", "한계, 제한", "Know your limitations.", "자신의 한계를 알세요."),
    "indication":    ("/ˌɪndɪˈkeɪʃən/", "명사", "징표, 표시", "No indication of improvement.", "개선의 표시가 없다."),
    "stability":     ("/stəˈbɪlɪti/", "명사", "안정성", "Political stability is key.", "정치적 안정이 핵심이다."),
    "wise":          ("/waɪz/", "형용사", "현명한", "It is wise to save money.", "돈을 저축하는 것이 현명하다."),
    "neglect":       ("/nɪˈɡlɛkt/", "동사", "방치하다, 소홀히 하다", "Don't neglect your health.", "건강을 소홀히 하지 마세요."),
    "compose":       ("/kəmˈpoʊz/", "동사", "작성하다, 구성하다", "Compose an email.", "이메일을 작성하세요."),
    "jail":          ("/dʒeɪl/", "명사", "감옥", "He was sent to jail.", "그는 감옥에 보내졌다."),
    "shelter":       ("/ˈʃɛltər/", "명사", "피난처, 쉼터", "Find shelter from the rain.", "비를 피할 곳을 찾으세요."),
    "mere":          ("/mɪər/", "형용사", "단순한, 불과한", "A mere misunderstanding.", "단순한 오해이다."),
    "carbon":        ("/ˈkɑːrbən/", "명사", "탄소", "Reduce carbon emissions.", "탄소 배출을 줄이세요."),
    "regulate":      ("/ˈrɛɡjʊleɪt/", "동사", "규제하다, 조절하다", "Regulate body temperature.", "체온을 조절하세요."),
    "cheese":        ("/tʃiːz/", "명사", "치즈", "Add cheese to the pizza.", "피자에 치즈를 추가하세요."),
    "trigger":       ("/ˈtrɪɡər/", "동사", "촉발하다, 유발하다", "Stress can trigger illness.", "스트레스가 질병을 유발할 수 있다."),
    "pipe":          ("/paɪp/", "명사", "파이프, 관", "The water pipe burst.", "수도 파이프가 터졌다."),
    "destruction":   ("/dɪˈstrʌkʃən/", "명사", "파괴, 붕괴", "Avoid environmental destruction.", "환경 파괴를 피하세요."),
    "guitar":        ("/ɡɪˈtɑːr/", "명사", "기타", "He plays the guitar.", "그는 기타를 연주한다."),
    "flag":          ("/flæɡ/", "명사", "깃발, 국기", "The flag flew in the wind.", "깃발이 바람에 날렸다."),
    "piano":         ("/piˈænoʊ/", "명사", "피아노", "She practices piano daily.", "그녀는 매일 피아노를 연습한다."),
    "magic":         ("/ˈmædʒɪk/", "명사", "마법, 마술", "The trick was pure magic.", "그 트릭은 순수한 마술이었다."),
    "mystery":       ("/ˈmɪstəri/", "명사", "미스터리, 수수께끼", "It remains a mystery.", "그것은 여전히 수수께끼이다."),
    "ski":           ("/skiː/", "동사", "스키를 타다", "I love to ski in winter.", "겨울에 스키 타는 것을 좋아한다."),
    "whisper":       ("/ˈwɪspər/", "동사", "속삭이다", "She whispered in his ear.", "그녀가 그의 귀에 속삭였다."),
    "rear":          ("/rɪər/", "명사", "뒤, 후방", "Move to the rear of the bus.", "버스 뒤쪽으로 이동하세요."),
    "menu":          ("/ˈmɛnjuː/", "명사", "메뉴", "Look at the menu.", "메뉴를 보세요."),
    "species":       ("/ˈspiːʃiːz/", "명사", "종, 생물 종", "Many species are endangered.", "많은 종이 멸종 위기에 처해있다."),
    "moon":          ("/muːn/", "명사", "달", "The moon is full tonight.", "오늘 밤 보름달이다."),
    "presumably":    ("/prɪˈzjuːməbli/", "부사", "아마도, 추정컨대", "He is presumably at home.", "그는 아마도 집에 있을 것이다."),
    "bless":         ("/blɛs/", "동사", "축복하다", "God bless you.", "신이 당신을 축복하시기를."),
    "airline":       ("/ˈɛərlaɪn/", "명사", "항공사", "Choose a budget airline.", "저가 항공사를 선택하세요."),
    "amendment":     ("/əˈmɛndmənt/", "명사", "수정, 개정", "Pass a constitutional amendment.", "헌법 개정안을 통과시키세요."),
    "grandmother":   ("/ˈɡrænˌmʌðər/", "명사", "할머니", "My grandmother is 80.", "내 할머니는 80세이다."),
    "jury":          ("/ˈdʒʊəri/", "명사", "배심원단", "The jury reached a verdict.", "배심원단이 평결에 도달했다."),
    "civilian":      ("/sɪˈvɪliən/", "명사", "민간인", "Protect civilian lives.", "민간인의 생명을 보호하세요."),
    "composition":   ("/ˌkɒmpəˈzɪʃən/", "명사", "구성, 작품", "The composition is beautiful.", "작품이 아름답다."),
    "coin":          ("/kɔɪn/", "명사", "동전", "Toss a coin.", "동전을 던지세요."),
    "regardless":    ("/rɪˈɡɑːrdlɪs/", "부사", "상관없이, 어쨌든", "Proceed regardless.", "어쨌든 진행하세요."),
    "scan":          ("/skæn/", "동사", "스캔하다, 훑어보다", "Scan the document.", "문서를 스캔하세요."),
    "bunch":         ("/bʌntʃ/", "명사", "다발, 무리", "A bunch of flowers.", "꽃 한 다발."),
    "racial":        ("/ˈreɪʃəl/", "형용사", "인종의, 인종적인", "Oppose racial discrimination.", "인종 차별에 반대하세요."),
    "greet":         ("/ɡriːt/", "동사", "인사하다, 맞이하다", "Greet guests at the door.", "문 앞에서 손님을 맞이하세요."),
    "hopefully":     ("/ˈhoʊpfəli/", "부사", "바라건대, 희망적으로", "Hopefully it will work.", "바라건대 잘 될 것이다."),
    "sanction":      ("/ˈsæŋkʃən/", "명사", "제재, 승인", "Impose economic sanctions.", "경제 제재를 부과하세요."),
    "trick":         ("/trɪk/", "명사", "속임수, 트릭", "Don't fall for that trick.", "그 속임수에 속지 마세요."),
    "paragraph":     ("/ˈpærəɡrɑːf/", "명사", "단락, 문단", "Write a short paragraph.", "짧은 단락을 작성하세요."),
    "maker":         ("/ˈmeɪkər/", "명사", "제조자, 만드는 사람", "The maker of this product.", "이 제품의 제조자."),
    "chocolate":     ("/ˈtʃɒklɪt/", "명사", "초콜릿", "I love dark chocolate.", "나는 다크 초콜릿을 좋아한다."),
    "stimulate":     ("/ˈstɪmjʊleɪt/", "동사", "자극하다, 촉진하다", "Stimulate economic growth.", "경제 성장을 촉진하세요."),
    "belt":          ("/bɛlt/", "명사", "벨트, 허리띠", "Fasten your seat belt.", "안전벨트를 매세요."),
    "potato":        ("/pəˈteɪtoʊ/", "명사", "감자", "Boil the potatoes.", "감자를 삶으세요."),
    "narrative":     ("/ˈnærətɪv/", "명사", "서술, 이야기", "Change the narrative.", "이야기를 바꾸세요."),
    "tissue":        ("/ˈtɪʃuː/", "명사", "조직, 화장지", "Use a tissue.", "화장지를 사용하세요."),
    "barely":        ("/ˈbɛərli/", "부사", "간신히, 겨우", "She barely made it.", "그녀는 간신히 해냈다."),
    "invent":        ("/ɪnˈvɛnt/", "동사", "발명하다", "Who invented the telephone?", "전화기를 발명한 사람은 누구인가요?"),
    "tourism":       ("/ˈtʊərɪzəm/", "명사", "관광", "Tourism supports the economy.", "관광이 경제를 지원한다."),
    "pro":           ("/proʊ/", "명사", "전문가, 프로", "She is a real pro.", "그녀는 진짜 전문가이다."),
    "stair":         ("/stɛər/", "명사", "계단", "Take the stairs.", "계단을 이용하세요."),
    "hesitate":      ("/ˈhɛzɪteɪt/", "동사", "망설이다, 주저하다", "Don't hesitate to ask.", "질문하는 것을 망설이지 마세요."),
    "shine":         ("/ʃaɪn/", "동사", "빛나다, 빛을 발하다", "The sun shines brightly.", "태양이 밝게 빛난다."),
    "motivation":    ("/ˌmoʊtɪˈveɪʃən/", "명사", "동기, 동기부여", "Find your motivation.", "동기를 찾으세요."),
    "romantic":      ("/roʊˈmæntɪk/", "형용사", "낭만적인", "It was a romantic evening.", "낭만적인 저녁이었다."),
    "firmly":        ("/ˈfɜːrmli/", "부사", "단호하게, 확실히", "Hold firmly to the rope.", "밧줄을 단단히 잡으세요."),
    "interior":      ("/ɪnˈtɪəriər/", "명사", "내부, 인테리어", "The interior is modern.", "내부가 현대적이다."),
    "stomach":       ("/ˈstʌmək/", "명사", "배, 위", "My stomach is upset.", "배가 아프다."),
    "nowhere":       ("/ˈnoʊwɛər/", "부사", "아무 데도 없는", "There's nowhere to go.", "갈 곳이 없다."),
    "pray":          ("/preɪ/", "동사", "기도하다", "Pray for peace.", "평화를 위해 기도하세요."),
    "championship":  ("/ˈtʃæmpiənʃɪp/", "명사", "선수권 대회, 챔피언십", "Win the championship.", "챔피언십에서 우승하세요."),
    "servant":       ("/ˈsɜːrvənt/", "명사", "하인, 공무원", "A public servant.", "공무원."),
    "immigrant":     ("/ˈɪmɪɡrənt/", "명사", "이민자", "Immigrants contribute to society.", "이민자들은 사회에 기여한다."),
    "excess":        ("/ˈɛksɛs/", "명사", "초과, 과잉", "Avoid excess sugar.", "과도한 설탕을 피하세요."),
    "complexity":    ("/kəmˈplɛksɪti/", "명사", "복잡성", "Reduce the complexity.", "복잡성을 줄이세요."),
    "surprisingly":  ("/səˈpraɪzɪŋli/", "부사", "놀랍게도", "Surprisingly, it worked.", "놀랍게도 효과가 있었다."),
    "extract":       ("/ɪkˈstrækt/", "동사", "추출하다, 뽑아내다", "Extract the data.", "데이터를 추출하세요."),
    "implementation":("/ˌɪmplɪmɛnˈteɪʃən/", "명사", "실행, 구현", "Oversee the implementation.", "실행을 감독하세요."),
    "bias":          ("/ˈbaɪəs/", "명사", "편견, 편향", "Remove unconscious bias.", "무의식적 편견을 제거하세요."),
    "differently":   ("/ˈdɪfərəntli/", "부사", "다르게, 달리", "Think differently.", "다르게 생각하세요."),
    "catalog":       ("/ˈkætəlɒɡ/", "명사", "목록, 카탈로그", "Browse the product catalog.", "제품 카탈로그를 검색하세요."),
    "continuous":    ("/kənˈtɪnjuəs/", "형용사", "지속적인, 연속적인", "Continuous improvement is key.", "지속적인 개선이 핵심이다."),
    "golden":        ("/ˈɡoʊldən/", "형용사", "황금의, 귀중한", "A golden opportunity.", "황금 같은 기회."),
    "stamp":         ("/stæmp/", "명사", "우표, 도장", "Put a stamp on the envelope.", "봉투에 우표를 붙이세요."),
    "guideline":     ("/ˈɡaɪdlaɪn/", "명사", "지침, 안내", "Follow the guidelines.", "지침을 따르세요."),
    "envelope":      ("/ˈɛnvəloʊp/", "명사", "봉투", "Seal the envelope.", "봉투를 봉인하세요."),
    "knife":         ("/naɪf/", "명사", "칼, 나이프", "Use a sharp knife.", "날카로운 칼을 사용하세요."),
    "biological":    ("/ˌbaɪəˈlɒdʒɪkəl/", "형용사", "생물학적인", "Biological diversity matters.", "생물학적 다양성이 중요하다."),
    "consume":       ("/kənˈsjuːm/", "동사", "소비하다, 먹다", "Consume less energy.", "에너지를 덜 소비하세요."),
    "luxury":        ("/ˈlʌkʃəri/", "명사", "사치, 럭셔리", "This is a luxury item.", "이것은 사치품이다."),
    "weekly":        ("/ˈwiːkli/", "형용사", "주간의, 매주의", "A weekly meeting.", "주간 회의."),
    "wherever":      ("/wɛərˈɛvər/", "접속사", "어디에서든", "Work wherever you want.", "원하는 곳 어디서든 일하세요."),
    "bite":          ("/baɪt/", "동사", "물다, 깨물다", "Don't bite your nails.", "손톱을 물어뜯지 마세요."),
    "printer":       ("/ˈprɪntər/", "명사", "프린터", "The printer is out of ink.", "프린터 잉크가 다 됐다."),
    "firstly":       ("/ˈfɜːrstli/", "부사", "첫째로, 우선", "Firstly, check the data.", "첫째로, 데이터를 확인하세요."),
    "anxious":       ("/ˈæŋkʃəs/", "형용사", "불안한, 걱정하는", "She felt anxious before the test.", "그녀는 시험 전에 불안했다."),
    "adventure":     ("/ədˈvɛntʃər/", "명사", "모험", "Life is an adventure.", "삶은 모험이다."),
    "fence":         ("/fɛns/", "명사", "울타리", "Build a fence.", "울타리를 세우세요."),
    "exhaust":       ("/ɪɡˈzɔːst/", "동사", "지치게 하다, 소진하다", "The work exhausted her.", "일이 그녀를 지치게 했다."),
    "attraction":    ("/əˈtrækʃən/", "명사", "매력, 명소", "A major tourist attraction.", "주요 관광 명소."),
    "ocean":         ("/ˈoʊʃən/", "명사", "바다, 대양", "The Pacific Ocean is vast.", "태평양은 광대하다."),
    "quietly":       ("/ˈkwaɪətli/", "부사", "조용히", "Speak quietly.", "조용히 말하세요."),
    "castle":        ("/ˈkɑːsəl/", "명사", "성", "Visit the old castle.", "오래된 성을 방문하세요."),
    "veteran":       ("/ˈvɛtərən/", "명사", "베테랑, 참전 용사", "Honor the veterans.", "참전 용사를 예우하세요."),
    "reflection":    ("/rɪˈflɛkʃən/", "명사", "반사, 성찰", "Take time for reflection.", "성찰할 시간을 가지세요."),
    "nerve":         ("/nɜːrv/", "명사", "신경, 용기", "It took a lot of nerve.", "많은 용기가 필요했다."),
    "determination": ("/dɪˌtɜːrmɪˈneɪʃən/", "명사", "결심, 결단력", "She showed great determination.", "그녀는 대단한 결단력을 보였다."),
    "altogether":    ("/ˌɔːltəˈɡɛðər/", "부사", "전체적으로, 완전히", "Altogether, it was a success.", "전체적으로 성공이었다."),
    "fiction":       ("/ˈfɪkʃən/", "명사", "소설, 허구", "She writes science fiction.", "그녀는 공상과학 소설을 쓴다."),
    "carpet":        ("/ˈkɑːrpɪt/", "명사", "카펫, 융단", "Clean the carpet.", "카펫을 청소하세요."),
    "cluster":       ("/ˈklʌstər/", "명사", "무리, 집단", "A cluster of stars.", "별들의 무리."),
    "confusion":     ("/kənˈfjuːʒən/", "명사", "혼란, 혼동", "Avoid confusion.", "혼란을 피하세요."),
    "hurry":         ("/ˈhʌri/", "동사", "서두르다", "Hurry up!", "서두르세요!"),
    "logic":         ("/ˈlɒdʒɪk/", "명사", "논리", "Use logic.", "논리를 사용하세요."),
    "controversial": ("/ˌkɒntrəˈvɜːrʃəl/", "형용사", "논란이 되는", "It is a controversial topic.", "그것은 논란이 되는 주제이다."),
    "raw":           ("/rɔː/", "형용사", "날것의, 가공되지 않은", "Raw vegetables are healthy.", "생야채는 건강하다."),
    "grammar":       ("/ˈɡræmər/", "명사", "문법", "Study English grammar.", "영어 문법을 공부하세요."),
    "revise":        ("/rɪˈvaɪz/", "동사", "수정하다, 복습하다", "Revise the essay.", "에세이를 수정하세요."),
    "hint":          ("/hɪnt/", "명사", "힌트, 암시", "Give me a hint.", "힌트를 주세요."),
    "hook":          ("/hʊk/", "명사", "고리, 갈고리", "Hang it on the hook.", "고리에 걸어두세요."),
    "bell":          ("/bɛl/", "명사", "종, 벨", "Ring the bell.", "종을 울리세요."),
    "liquid":        ("/ˈlɪkwɪd/", "명사", "액체", "Drink plenty of liquid.", "수분을 충분히 섭취하세요."),
    "panic":         ("/ˈpænɪk/", "명사", "공황, 패닉", "Don't panic.", "당황하지 마세요."),
    "uncle":         ("/ˈʌŋkəl/", "명사", "삼촌, 큰아버지", "My uncle lives in Seoul.", "삼촌은 서울에 산다."),
    "rice":          ("/raɪs/", "명사", "쌀, 밥", "Cook steamed rice.", "흰밥을 지어주세요."),
    "slope":         ("/sloʊp/", "명사", "경사면, 비탈", "The slope is steep.", "경사가 가파르다."),
    "happiness":     ("/ˈhæpinɪs/", "명사", "행복", "Find true happiness.", "진정한 행복을 찾으세요."),
    "genuine":       ("/ˈdʒɛnjuɪn/", "형용사", "진정한, 진짜의", "A genuine smile.", "진정한 미소."),
    "vessel":        ("/ˈvɛsəl/", "명사", "배, 혈관", "The vessel sailed at dawn.", "배가 새벽에 출항했다."),
    "verb":          ("/vɜːrb/", "명사", "동사", "Identify the verb.", "동사를 식별하세요."),
    "reckon":        ("/ˈrɛkən/", "동사", "생각하다, 여기다", "I reckon she'll agree.", "그녀가 동의할 것으로 생각한다."),
    "silly":         ("/ˈsɪli/", "형용사", "어리석은, 바보같은", "Don't be silly.", "바보같이 굴지 마세요."),
    "transportation":("/ˌtrænspɔːrˈteɪʃən/", "명사", "교통, 운송", "Use public transportation.", "대중교통을 이용하세요."),
    "harbor":        ("/ˈhɑːrbər/", "명사", "항구, 항만", "Ships dock in the harbor.", "배들이 항구에 정박한다."),
    "comedy":        ("/ˈkɒmədi/", "명사", "코미디, 희극", "Watch a comedy film.", "코미디 영화를 보세요."),
    "chase":         ("/tʃeɪs/", "동사", "뒤쫓다, 추격하다", "Chase your dreams.", "꿈을 좇으세요."),
    "storage":       ("/ˈstɔːrɪdʒ/", "명사", "저장, 창고", "We need more storage.", "더 많은 저장 공간이 필요하다."),
    "universe":      ("/ˈjuːnɪvɜːrs/", "명사", "우주", "The universe is expanding.", "우주가 팽창하고 있다."),
    "horrible":      ("/ˈhɒrɪbəl/", "형용사", "끔찍한, 소름 끼치는", "The smell is horrible.", "냄새가 끔찍하다."),
    "sheep":         ("/ʃiːp/", "명사", "양", "The sheep graze on the hill.", "양들이 언덕에서 풀을 뜯는다."),
    "lover":         ("/ˈlʌvər/", "명사", "애인, 열렬한 팬", "She is a music lover.", "그녀는 음악 애호가이다."),
    "rat":           ("/ræt/", "명사", "쥐", "There is a rat in the kitchen.", "부엌에 쥐가 있다."),
    "portrait":      ("/ˈpɔːrtrɪt/", "명사", "초상화", "Paint a portrait.", "초상화를 그리세요."),
    "innocent":      ("/ˈɪnəsənt/", "형용사", "무고한, 결백한", "He was proven innocent.", "그는 무고함이 증명됐다."),
    "substitute":    ("/ˈsʌbstɪtjuːt/", "동사", "대체하다", "Substitute sugar with honey.", "설탕을 꿀로 대체하세요."),
    "supplement":    ("/ˈsʌplɪmənt/", "명사", "보충제, 부록", "Take vitamin supplements.", "비타민 보충제를 복용하세요."),
    "adjustment":    ("/əˈdʒʌstmənt/", "명사", "조정, 적응", "Make necessary adjustments.", "필요한 조정을 하세요."),
    "reasonably":    ("/ˈriːzənəbli/", "부사", "합리적으로", "Priced reasonably.", "합리적으로 가격이 책정됐다."),
    "filter":        ("/ˈfɪltər/", "동사", "걸러내다, 필터하다", "Filter the results.", "결과를 필터하세요."),
    "flexible":      ("/ˈflɛksɪbəl/", "형용사", "유연한", "Be flexible with plans.", "계획에 유연하세요."),
    "tent":          ("/tɛnt/", "명사", "텐트", "Set up the tent.", "텐트를 설치하세요."),
    "precise":       ("/prɪˈsaɪs/", "형용사", "정확한, 엄밀한", "Be precise in your answer.", "답변에 정확히 하세요."),
    "distant":       ("/ˈdɪstənt/", "형용사", "먼, 거리가 있는", "A distant memory.", "먼 기억."),
    "stranger":      ("/ˈstreɪndʒər/", "명사", "낯선 사람", "Don't talk to strangers.", "낯선 사람에게 말하지 마세요."),
    "shade":         ("/ʃeɪd/", "명사", "그늘, 색조", "Sit in the shade.", "그늘에 앉으세요."),
    "grain":         ("/ɡreɪn/", "명사", "곡물, 알갱이", "Whole grains are nutritious.", "통곡물은 영양이 풍부하다."),
    "situate":       ("/ˈsɪtʃueɪt/", "동사", "위치시키다", "The office is situated downtown.", "사무실은 시내에 위치한다."),
    "summarize":     ("/ˈsʌməraɪz/", "동사", "요약하다", "Summarize the key points.", "핵심 사항을 요약하세요."),
    "leap":          ("/liːp/", "동사", "뛰다, 도약하다", "Take a leap of faith.", "믿음으로 도약하세요."),
    "snap":          ("/snæp/", "동사", "딱 소리를 내다, 급히 사진 찍다", "Snap a quick photo.", "빠르게 사진을 찍으세요."),
    "probability":   ("/ˌprɒbəˈbɪlɪti/", "명사", "확률", "The probability is high.", "확률이 높다."),
    "leather":       ("/ˈlɛðər/", "명사", "가죽", "A leather jacket.", "가죽 재킷."),
    "uncertainty":   ("/ʌnˈsɜːrtənti/", "명사", "불확실성", "Manage uncertainty.", "불확실성을 관리하세요."),
    "swear":         ("/swɛər/", "동사", "맹세하다, 욕하다", "I swear to tell the truth.", "진실을 말할 것을 맹세한다."),
    "refugee":       ("/ˌrɛfjʊˈdʒiː/", "명사", "난민", "Help the refugees.", "난민들을 도우세요."),
    "shore":         ("/ʃɔːr/", "명사", "해안, 기슭", "Walk along the shore.", "해안을 따라 걸으세요."),
    "monthly":       ("/ˈmʌnθli/", "형용사", "월간의, 매월의", "Monthly payment.", "월 납부."),
    "comprise":      ("/kəmˈpraɪz/", "동사", "구성하다, 포함하다", "The team comprises 10 members.", "팀은 10명으로 구성된다."),
    "stir":          ("/stɜːr/", "동사", "젓다, 움직이다", "Stir the soup.", "수프를 저으세요."),
    "excitement":    ("/ɪkˈsaɪtmənt/", "명사", "흥분, 흥미", "Full of excitement.", "흥분으로 가득 찼다."),
    "sigh":          ("/saɪ/", "동사", "한숨 쉬다", "She sighed with relief.", "그녀는 안도의 한숨을 쉬었다."),
    "pregnancy":     ("/ˈprɛɡnənsi/", "명사", "임신", "Maintain health during pregnancy.", "임신 중 건강을 유지하세요."),
    "experimental":  ("/ɪkˌspɛrɪˈmɛntəl/", "형용사", "실험적인", "An experimental treatment.", "실험적인 치료."),
    "institutional": ("/ˌɪnstɪˈtjuːʃənəl/", "형용사", "기관의, 제도적인", "Institutional support.", "기관의 지원."),
    "slice":         ("/slaɪs/", "명사", "조각", "A slice of bread.", "빵 한 조각."),
    "wander":        ("/ˈwɒndər/", "동사", "돌아다니다, 헤매다", "Wander through the streets.", "거리를 돌아다니다."),
    "empire":        ("/ˈɛmpaɪər/", "명사", "제국", "The Roman Empire.", "로마 제국."),
    "subsequently":  ("/ˈsʌbsɪkwəntli/", "부사", "그 후에, 뒤이어", "Subsequently, he left.", "그 후에 그가 떠났다."),
    "gentle":        ("/ˈdʒɛntəl/", "형용사", "부드러운, 온화한", "A gentle touch.", "부드러운 손길."),
    "attendance":    ("/əˈtɛndəns/", "명사", "출석, 참석", "Check the attendance.", "출석을 확인하세요."),
    "ownership":     ("/ˈoʊnərʃɪp/", "명사", "소유권", "Transfer ownership.", "소유권을 이전하세요."),
    "qualification": ("/ˌkwɒlɪfɪˈkeɪʃən/", "명사", "자격, 자격증", "Check the qualifications.", "자격을 확인하세요."),
    "suspend":       ("/səˈspɛnd/", "동사", "중단하다, 정직시키다", "Suspend the service.", "서비스를 중단하세요."),
    "functional":    ("/ˈfʌŋkʃənəl/", "형용사", "기능적인", "A functional design.", "기능적인 디자인."),
    "voluntary":     ("/ˈvɒləntəri/", "형용사", "자발적인", "Voluntary participation.", "자발적인 참여."),
    "pale":          ("/peɪl/", "형용사", "창백한, 연한", "She looked pale.", "그녀는 창백해 보였다."),
    "stain":         ("/steɪn/", "명사", "얼룩", "Remove the stain.", "얼룩을 제거하세요."),
    "athlete":       ("/ˈæθliːt/", "명사", "운동선수", "She is a professional athlete.", "그녀는 전문 운동선수이다."),
    "organic":       ("/ɔːrˈɡænɪk/", "형용사", "유기농의", "Buy organic food.", "유기농 식품을 구매하세요."),
    "tongue":        ("/tʌŋ/", "명사", "혀", "Learn a foreign tongue.", "외국어를 배우세요."),
    "server":        ("/ˈsɜːrvər/", "명사", "서버", "The server is down.", "서버가 다운됐다."),
    "structural":    ("/ˈstrʌktʃərəl/", "형용사", "구조적인", "Structural damage.", "구조적 손상."),
    "website":       ("/ˈwɛbsaɪt/", "명사", "웹사이트", "Visit our website.", "우리 웹사이트를 방문하세요."),
    "fool":          ("/fuːl/", "명사", "바보", "Don't be a fool.", "바보같이 굴지 마세요."),
    "alongside":     ("/əˌlɒŋˈsaɪd/", "전치사", "~옆에, 나란히", "Work alongside your team.", "팀과 나란히 일하세요."),
    "unite":         ("/juːˈnaɪt/", "동사", "합치다, 단결하다", "Unite for a common goal.", "공동 목표를 위해 단결하세요."),
    "gently":        ("/ˈdʒɛntli/", "부사", "부드럽게, 조심스럽게", "Hold the baby gently.", "아기를 부드럽게 안아주세요."),
    "compute":       ("/kəmˈpjuːt/", "동사", "계산하다", "Compute the total cost.", "총 비용을 계산하세요."),
    "wipe":          ("/waɪp/", "동사", "닦다", "Wipe the table.", "테이블을 닦으세요."),
    "weird":         ("/wɪərd/", "형용사", "이상한", "That is really weird.", "그것은 정말 이상하다."),
    "gaze":          ("/ɡeɪz/", "동사", "응시하다", "Gaze at the stars.", "별을 응시하세요."),
    "fade":          ("/feɪd/", "동사", "바래다, 사라지다", "Colors fade in sunlight.", "색이 햇빛에 바란다."),
    "cough":         ("/kɒf/", "동사", "기침하다", "Cover your mouth when you cough.", "기침할 때 입을 가리세요."),
    "royal":         ("/ˈrɔɪəl/", "형용사", "왕실의, 왕족의", "A royal wedding.", "왕실 결혼식."),
    "curtain":       ("/ˈkɜːrtən/", "명사", "커튼", "Draw the curtains.", "커튼을 치세요."),
    "mayor":         ("/meɪər/", "명사", "시장", "The mayor gave a speech.", "시장이 연설을 했다."),
    "darkness":      ("/ˈdɑːrknɪs/", "명사", "어둠", "Fear the darkness.", "어둠을 두려워하다."),
    "aunt":          ("/ɑːnt/", "명사", "이모, 고모", "My aunt bakes great cookies.", "이모는 쿠키를 잘 굽는다."),
    "tournament":    ("/ˈtʊənəmənt/", "명사", "토너먼트, 대회", "Win the tennis tournament.", "테니스 토너먼트에서 우승하세요."),
    "registration":  ("/ˌrɛdʒɪˈstreɪʃən/", "명사", "등록", "Complete the registration.", "등록을 완료하세요."),
    "fragment":      ("/ˈfræɡmənt/", "명사", "파편, 조각", "A fragment of glass.", "유리 파편."),
    "listener":      ("/ˈlɪsənər/", "명사", "청취자", "Be a good listener.", "좋은 청취자가 되세요."),
    "immigration":   ("/ˌɪmɪˈɡreɪʃən/", "명사", "이민, 출입국", "Immigration policy reform.", "이민 정책 개혁."),
    "tender":        ("/ˈtɛndər/", "형용사", "부드러운, 사랑스러운", "A tender touch.", "부드러운 손길."),
    "density":       ("/ˈdɛnsɪti/", "명사", "밀도, 밀집도", "Population density.", "인구 밀도."),
    "ugly":          ("/ˈʌɡli/", "형용사", "못생긴, 추한", "It looks ugly.", "못생겨 보인다."),
    "module":        ("/ˈmɒdjuːl/", "명사", "모듈, 단원", "Complete each module.", "각 모듈을 완성하세요."),
    "faithfully":    ("/ˈfeɪθfəli/", "부사", "충실하게", "Serve faithfully.", "충실하게 봉사하세요."),
    "autumn":        ("/ˈɔːtəm/", "명사", "가을", "Autumn leaves are beautiful.", "가을 나뭇잎은 아름답다."),
    "cheek":         ("/tʃiːk/", "명사", "뺨", "She kissed his cheek.", "그녀가 그의 뺨에 키스했다."),
    "attachment":    ("/əˈtætʃmənt/", "명사", "첨부, 애착", "Send the attachment.", "첨부 파일을 보내세요."),
    "holder":        ("/ˈhoʊldər/", "명사", "보유자, 홀더", "Card holder.", "카드 보유자."),
    "solar":         ("/ˈsoʊlər/", "형용사", "태양의", "Solar energy is clean.", "태양 에너지는 깨끗하다."),
    "grin":          ("/ɡrɪn/", "동사", "씩 웃다", "She grinned with joy.", "그녀는 기쁨에 씩 웃었다."),
    "rose":          ("/roʊz/", "명사", "장미", "Red roses are romantic.", "빨간 장미는 낭만적이다."),
    "noun":          ("/naʊn/", "명사", "명사", "Identify the noun.", "명사를 식별하세요."),
    "fortunate":     ("/ˈfɔːrtʃənɪt/", "형용사", "운이 좋은", "I am fortunate to be here.", "여기 있어서 운이 좋다."),
    "alright":       ("/ɔːlˈraɪt/", "형용사", "괜찮은", "Is everything alright?", "모든 것이 괜찮나요?"),
    "lazy":          ("/ˈleɪzi/", "형용사", "게으른", "Don't be lazy.", "게으르지 마세요."),
    "hello":         ("/həˈloʊ/", "감탄사", "안녕하세요", "Say hello to everyone.", "모두에게 인사하세요."),
    "hunger":        ("/ˈhʌŋɡər/", "명사", "굶주림, 배고픔", "End world hunger.", "세계 기아를 끝내세요."),
    "insure":        ("/ɪnˈʃʊər/", "동사", "보험에 들다", "Insure your car.", "자동차 보험에 가입하세요."),
    "ashamed":       ("/əˈʃeɪmd/", "형용사", "부끄러운, 창피한", "I feel ashamed.", "부끄럽다."),
    "found":         ("/faʊnd/", "동사", "설립하다", "He founded the company.", "그는 회사를 설립했다."),
    "blog":          ("/blɒɡ/", "명사", "블로그", "Start a blog.", "블로그를 시작하세요."),
    "thirst":        ("/θɜːrst/", "명사", "갈증", "Quench your thirst.", "갈증을 해소하세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT10:
                    pron, pos, meaning, ex_en, ex_ko = DICT10[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more10.py ===\n")
    patch_files()
