#!/usr/bin/env python3
"""Fill freq-L9 (279 words)"""
import json, glob

DICT9 = {
    "loud":          ("/laʊd/", "형용사", "큰 소리의, 시끄러운", "The music is too loud.", "음악이 너무 시끄럽다."),
    "dimension":     ("/dɪˈmɛnʃən/", "명사", "차원, 측면", "Consider all dimensions.", "모든 차원을 고려하세요."),
    "subsequent":    ("/ˈsʌbsɪkwənt/", "형용사", "그 이후의, 차후의", "Subsequent events proved it.", "그 이후의 사건들이 그것을 증명했다."),
    "infection":     ("/ɪnˈfɛkʃən/", "명사", "감염, 전염", "Prevent infection by washing hands.", "손을 씻어서 감염을 예방하세요."),
    "jacket":        ("/ˈdʒækɪt/", "명사", "재킷, 외투", "Wear a warm jacket.", "따뜻한 재킷을 입으세요."),
    "efficiency":    ("/ɪˈfɪʃənsi/", "명사", "효율성", "Improve energy efficiency.", "에너지 효율성을 향상시키세요."),
    "dirty":         ("/ˈdɜːrti/", "형용사", "더러운, 지저분한", "Wash your dirty hands.", "더러운 손을 씻으세요."),
    "statistic":     ("/stəˈtɪstɪk/", "명사", "통계", "The statistics are alarming.", "통계가 놀랍다."),
    "regularly":     ("/ˈrɛɡjʊlərli/", "부사", "정기적으로", "Exercise regularly.", "규칙적으로 운동하세요."),
    "resort":        ("/rɪˈzɔːrt/", "명사", "리조트, 수단", "They stayed at a mountain resort.", "그들은 산 리조트에 묵었다."),
    "iron":          ("/ˈaɪərn/", "명사", "철, 다리미", "The fence is made of iron.", "울타리는 철로 만들어졌다."),
    "broadcast":     ("/ˈbrɔːdkæst/", "동사", "방송하다", "The event will be broadcast live.", "행사가 생방송될 것이다."),
    "membership":    ("/ˈmɛmbərʃɪp/", "명사", "회원 자격, 회원권", "Apply for membership today.", "오늘 회원 신청을 하세요."),
    "bread":         ("/brɛd/", "명사", "빵", "Buy a loaf of bread.", "빵 한 덩어리를 사세요."),
    "blind":         ("/blaɪnd/", "형용사", "눈이 먼, 맹목적인", "She is blind in one eye.", "그녀는 한쪽 눈이 보이지 않는다."),
    "pure":          ("/pjʊər/", "형용사", "순수한, 깨끗한", "Drink pure water.", "순수한 물을 마시세요."),
    "bloody":        ("/ˈblʌdi/", "형용사", "피투성이의", "He had a bloody nose.", "그는 코피가 났다."),
    "ally":          ("/ˈælaɪ/", "명사", "동맹국, 협력자", "Find allies in the project.", "프로젝트에서 협력자를 찾으세요."),
    "quantity":      ("/ˈkwɒntɪti/", "명사", "양, 수량", "Order the correct quantity.", "올바른 수량을 주문하세요."),
    "bend":          ("/bɛnd/", "동사", "구부리다, 굽히다", "Bend your knees.", "무릎을 구부리세요."),
    "mature":        ("/məˈtʃʊər/", "형용사", "성숙한", "She is very mature for her age.", "그녀는 나이에 비해 매우 성숙하다."),
    "briefly":       ("/ˈbriːfli/", "부사", "간단히, 잠깐", "Let me briefly explain.", "간단히 설명하겠습니다."),
    "alarm":         ("/əˈlɑːrm/", "명사", "경보, 알람", "Set the alarm for 7 AM.", "오전 7시에 알람을 맞춰두세요."),
    "disturb":       ("/dɪˈstɜːrb/", "동사", "방해하다, 불안하게 하다", "Please do not disturb.", "방해하지 마세요."),
    "sustain":       ("/səˈsteɪn/", "동사", "유지하다, 지속하다", "Sustain economic growth.", "경제 성장을 유지하세요."),
    "flood":         ("/flʌd/", "명사", "홍수", "The flood damaged many homes.", "홍수가 많은 집을 파괴했다."),
    "poverty":       ("/ˈpɒvərti/", "명사", "빈곤, 가난", "Reduce poverty worldwide.", "전 세계적으로 빈곤을 줄이세요."),
    "crazy":         ("/ˈkreɪzi/", "형용사", "미친, 열정적인", "You're crazy about music.", "당신은 음악에 미쳐있다."),
    "cite":          ("/saɪt/", "동사", "인용하다, 언급하다", "Cite your sources.", "출처를 인용하세요."),
    "newly":         ("/ˈnjuːli/", "부사", "새로, 최근에", "She is newly married.", "그녀는 최근에 결혼했다."),
    "parallel":      ("/ˈpærəlɛl/", "형용사", "평행한, 유사한", "The roads run parallel.", "도로들이 평행하게 달린다."),
    "gender":        ("/ˈdʒɛndər/", "명사", "성별", "Gender equality is important.", "성 평등이 중요하다."),
    "sponsor":       ("/ˈspɒnsər/", "동사", "후원하다", "They sponsor local events.", "그들은 지역 행사를 후원한다."),
    "boot":          ("/buːt/", "명사", "부츠, 장화", "Wear boots in the snow.", "눈 속에서는 부츠를 신으세요."),
    "accurate":      ("/ˈækjʊrɪt/", "형용사", "정확한", "Give accurate information.", "정확한 정보를 주세요."),
    "dealer":        ("/ˈdiːlər/", "명사", "판매상, 딜러", "Buy from an authorized dealer.", "공식 딜러에서 구매하세요."),
    "button":        ("/ˈbʌtən/", "명사", "버튼, 단추", "Press the power button.", "전원 버튼을 누르세요."),
    "burden":        ("/ˈbɜːrdən/", "명사", "부담, 짐", "Share the burden.", "부담을 나누세요."),
    "desert":        ("/ˈdɛzərt/", "명사", "사막", "The Sahara is a desert.", "사하라는 사막이다."),
    "mate":          ("/meɪt/", "명사", "친구, 배우자", "He is my best mate.", "그는 내 가장 친한 친구이다."),
    "occasionally":  ("/əˈkeɪʒənəli/", "부사", "가끔, 때때로", "I occasionally visit.", "나는 가끔 방문한다."),
    "bowl":          ("/boʊl/", "명사", "그릇, 볼", "Pour soup into a bowl.", "그릇에 수프를 부으세요."),
    "discovery":     ("/dɪˈskʌvəri/", "명사", "발견", "It was an amazing discovery.", "그것은 놀라운 발견이었다."),
    "resistance":    ("/rɪˈzɪstəns/", "명사", "저항, 내성", "Build resistance to disease.", "질병에 대한 저항력을 기르세요."),
    "bath":          ("/bæθ/", "명사", "목욕, 욕조", "Take a hot bath.", "뜨거운 물로 목욕하세요."),
    "frequency":     ("/ˈfriːkwənsi/", "명사", "빈도, 주파수", "Increase the frequency of calls.", "통화 빈도를 높이세요."),
    "criticize":     ("/ˈkrɪtɪsaɪz/", "동사", "비판하다", "Don't criticize without facts.", "사실 없이 비판하지 마세요."),
    "tap":           ("/tæp/", "동사", "두드리다, 탭하다", "Tap the screen to continue.", "계속하려면 화면을 탭하세요."),
    "philosophy":    ("/fɪˈlɒsəfi/", "명사", "철학", "What is your philosophy?", "당신의 철학은 무엇인가요?"),
    "lip":           ("/lɪp/", "명사", "입술", "Apply lip balm.", "립밤을 바르세요."),
    "attribute":     ("/ˈætrɪbjuːt/", "명사", "특성, 속성", "List your key attributes.", "주요 특성을 나열하세요."),
    "apologize":     ("/əˈpɒlədʒaɪz/", "동사", "사과하다", "I apologize for the error.", "실수에 대해 사과드립니다."),
    "approval":      ("/əˈpruːvəl/", "명사", "승인, 찬성", "Get approval before starting.", "시작 전에 승인을 받으세요."),
    "grab":          ("/ɡræb/", "동사", "잡다, 움켜쥐다", "Grab a seat.", "자리를 잡으세요."),
    "entitle":       ("/ɪnˈtaɪtəl/", "동사", "자격을 주다, 제목을 붙이다", "You are entitled to a refund.", "환불 받을 자격이 있습니다."),
    "lend":          ("/lɛnd/", "동사", "빌려주다", "Can you lend me a pen?", "펜 좀 빌려줄 수 있나요?"),
    "involvement":   ("/ɪnˈvɒlvmənt/", "명사", "참여, 개입", "Her involvement is crucial.", "그녀의 참여가 중요하다."),
    "exposure":      ("/ɪkˈspoʊʒər/", "명사", "노출, 폭로", "Reduce exposure to the sun.", "햇빛 노출을 줄이세요."),
    "conventional":  ("/kənˈvɛnʃənəl/", "형용사", "전통적인, 관습적인", "Use conventional methods.", "전통적인 방법을 사용하세요."),
    "digital":       ("/ˈdɪdʒɪtəl/", "형용사", "디지털의", "We live in a digital world.", "우리는 디지털 세상에 산다."),
    "translate":     ("/trænsˈleɪt/", "동사", "번역하다", "Translate the document.", "문서를 번역하세요."),
    "edit":          ("/ˈɛdɪt/", "동사", "편집하다, 수정하다", "Edit the draft carefully.", "초안을 신중하게 편집하세요."),
    "formation":     ("/fɔːrˈmeɪʃən/", "명사", "형성, 구성", "Cloud formation is interesting.", "구름 형성은 흥미롭다."),
    "deposit":       ("/dɪˈpɒzɪt/", "동사", "예금하다, 맡기다", "Deposit money in the bank.", "은행에 돈을 예금하세요."),
    "pleasant":      ("/ˈplɛzənt/", "형용사", "즐거운, 기분 좋은", "It was a pleasant surprise.", "그것은 즐거운 놀라움이었다."),
    "overseas":      ("/ˌoʊvərˈsiːz/", "부사", "해외에서, 해외로", "He works overseas.", "그는 해외에서 일한다."),
    "advocate":      ("/ˈædvəkeɪt/", "동사", "옹호하다, 지지하다", "She advocates for equality.", "그녀는 평등을 옹호한다."),
    "establishment": ("/ɪˈstæblɪʃmənt/", "명사", "설립, 기관", "The establishment resisted change.", "기관이 변화에 저항했다."),
    "summary":       ("/ˈsʌməri/", "명사", "요약", "Write a brief summary.", "간단한 요약을 작성하세요."),
    "rough":         ("/rʌf/", "형용사", "거친, 대략적인", "Rough seas ahead.", "앞에 거친 바다가 있다."),
    "pen":           ("/pɛn/", "명사", "펜", "Sign with a pen.", "펜으로 서명하세요."),
    "recovery":      ("/rɪˈkʌvəri/", "명사", "회복", "She made a full recovery.", "그녀는 완전히 회복했다."),
    "seal":          ("/siːl/", "동사", "봉인하다, 도장을 찍다", "Seal the envelope tightly.", "봉투를 단단히 봉인하세요."),
    "tube":          ("/tjuːb/", "명사", "튜브, 관", "Squeeze the toothpaste tube.", "치약 튜브를 짜세요."),
    "tower":         ("/ˈtaʊər/", "명사", "탑", "The Eiffel Tower is in Paris.", "에펠탑은 파리에 있다."),
    "characterize":  ("/ˈkærɪktəraɪz/", "동사", "특징짓다, 묘사하다", "How would you characterize it?", "어떻게 특징지을 수 있나요?"),
    "specify":       ("/ˈspɛsɪfaɪ/", "동사", "명시하다, 지정하다", "Specify your requirements.", "요구 사항을 명시하세요."),
    "exact":         ("/ɪɡˈzækt/", "형용사", "정확한, 엄밀한", "What is the exact time?", "정확한 시간이 몇 시인가요?"),
    "spin":          ("/spɪn/", "동사", "돌다, 회전하다", "The wheel started to spin.", "바퀴가 돌기 시작했다."),
    "operator":      ("/ˈɒpəreɪtər/", "명사", "운영자, 교환원", "Contact the operator.", "교환원에게 연락하세요."),
    "infant":        ("/ˈɪnfənt/", "명사", "유아, 갓난아이", "The infant is sleeping.", "유아가 자고 있다."),
    "dig":           ("/dɪɡ/", "동사", "파다, 굴착하다", "Dig a hole in the ground.", "땅에 구멍을 파세요."),
    "drag":          ("/dræɡ/", "동사", "끌다, 드래그하다", "Drag and drop the file.", "파일을 끌어서 놓으세요."),
    "mount":         ("/maʊnt/", "동사", "올라타다, 오르다", "Mount the horse carefully.", "말에 조심스럽게 올라타세요."),
    "wrap":          ("/ræp/", "동사", "포장하다, 감싸다", "Wrap the gift nicely.", "선물을 예쁘게 포장하세요."),
    "anticipate":    ("/ænˈtɪsɪpeɪt/", "동사", "예상하다, 기대하다", "Anticipate problems in advance.", "미리 문제를 예상하세요."),
    "dependent":     ("/dɪˈpɛndənt/", "형용사", "의존하는", "Children are dependent on parents.", "아이들은 부모에게 의존한다."),
    "specialize":    ("/ˈspɛʃəlaɪz/", "동사", "전공하다, 전문화하다", "She specializes in tax law.", "그녀는 세법을 전공한다."),
    "angle":         ("/ˈæŋɡəl/", "명사", "각도, 관점", "Consider it from another angle.", "다른 각도에서 생각해보세요."),
    "chicken":       ("/ˈtʃɪkɪn/", "명사", "닭, 닭고기", "Grilled chicken is healthy.", "구운 닭고기는 건강하다."),
    "anxiety":       ("/æŋˈzaɪɪti/", "명사", "불안, 걱정", "Reduce anxiety through meditation.", "명상으로 불안을 줄이세요."),
    "virus":         ("/ˈvaɪrəs/", "명사", "바이러스", "The virus spread quickly.", "바이러스가 빠르게 퍼졌다."),
    "precisely":     ("/prɪˈsaɪsli/", "부사", "정확하게", "That is precisely the point.", "그것이 바로 요점이다."),
    "rival":         ("/ˈraɪvəl/", "명사", "경쟁자, 라이벌", "They are business rivals.", "그들은 사업 경쟁자이다."),
    "offense":       ("/əˈfɛns/", "명사", "위반, 공격", "That was a serious offense.", "그것은 심각한 위반이었다."),
    "detect":        ("/dɪˈtɛkt/", "동사", "감지하다, 발견하다", "Detect the error early.", "오류를 일찍 감지하세요."),
    "teenager":      ("/ˈtiːneɪdʒər/", "명사", "십 대", "Teenagers need guidance.", "십 대는 지도가 필요하다."),
    "admire":        ("/ədˈmaɪər/", "동사", "감탄하다, 경탄하다", "I admire your courage.", "당신의 용기에 감탄합니다."),
    "moderate":      ("/ˈmɒdərɪt/", "형용사", "적당한, 온건한", "Exercise at a moderate pace.", "적당한 속도로 운동하세요."),
    "surgery":       ("/ˈsɜːrdʒəri/", "명사", "수술", "He needs emergency surgery.", "그는 응급 수술이 필요하다."),
    "musician":      ("/mjuːˈzɪʃən/", "명사", "음악가", "She is a talented musician.", "그녀는 재능 있는 음악가이다."),
    "significance":  ("/sɪɡˈnɪfɪkəns/", "명사", "중요성, 의의", "The significance is clear.", "중요성이 명확하다."),
    "shower":        ("/ˈʃaʊər/", "명사", "샤워", "Take a cold shower.", "차가운 물로 샤워하세요."),
    "illegal":       ("/ɪˈliːɡəl/", "형용사", "불법의", "Parking here is illegal.", "여기 주차는 불법이다."),
    "charity":       ("/ˈtʃærɪti/", "명사", "자선, 자선 단체", "Donate to a charity.", "자선 단체에 기부하세요."),
    "universal":     ("/ˌjuːnɪˈvɜːrsəl/", "형용사", "보편적인, 세계적인", "It is a universal truth.", "그것은 보편적인 진리이다."),
    "cigarette":     ("/ˌsɪɡəˈrɛt/", "명사", "담배", "Smoking cigarettes is harmful.", "담배 흡연은 해롭다."),
    "constitute":    ("/ˈkɒnstɪtjuːt/", "동사", "구성하다, ~에 해당하다", "Women constitute half the workforce.", "여성이 노동력의 절반을 구성한다."),
    "adequate":      ("/ˈædɪkwɪt/", "형용사", "충분한, 적절한", "Ensure adequate rest.", "충분한 휴식을 취하세요."),
    "consultant":    ("/kənˈsʌltənt/", "명사", "컨설턴트, 자문", "Hire a management consultant.", "경영 컨설턴트를 고용하세요."),
    "historian":     ("/hɪˈstɔːriən/", "명사", "역사가", "The historian wrote a book.", "역사가가 책을 썼다."),
    "cousin":        ("/ˈkʌzən/", "명사", "사촌", "My cousin lives abroad.", "내 사촌은 해외에 산다."),
    "visual":        ("/ˈvɪʒuəl/", "형용사", "시각의, 시각적인", "Use visual aids.", "시각 자료를 사용하세요."),
    "stupid":        ("/ˈstjuːpɪd/", "형용사", "어리석은, 바보 같은", "Don't make stupid mistakes.", "어리석은 실수를 하지 마세요."),
    "keen":          ("/kiːn/", "형용사", "열성적인, 예리한", "She is keen to learn.", "그녀는 배우는 데 열성적이다."),
    "ethnic":        ("/ˈɛθnɪk/", "형용사", "민족의, 인종의", "Respect ethnic diversity.", "민족적 다양성을 존중하세요."),
    "twin":          ("/twɪn/", "명사", "쌍둥이", "She has a twin sister.", "그녀는 쌍둥이 자매가 있다."),
    "clinical":      ("/ˈklɪnɪkəl/", "형용사", "임상의, 진료의", "Clinical trials are ongoing.", "임상 시험이 진행 중이다."),
    "eastern":       ("/ˈiːstərn/", "형용사", "동부의, 동양의", "Eastern cultures are fascinating.", "동양 문화는 매력적이다."),
    "forecast":      ("/ˈfɔːrkæst/", "명사", "예보, 예측", "Check the weather forecast.", "날씨 예보를 확인하세요."),
    "segment":       ("/ˈsɛɡmənt/", "명사", "부분, 구획", "Target a specific market segment.", "특정 시장 부문을 타겟으로 삼으세요."),
    "custom":        ("/ˈkʌstəm/", "명사", "관습, 풍습", "Respect local customs.", "지역 관습을 존중하세요."),
    "adapt":         ("/əˈdæpt/", "동사", "적응하다, 조정하다", "Adapt to the new environment.", "새 환경에 적응하세요."),
    "sand":          ("/sænd/", "명사", "모래", "The beach is covered in sand.", "해변이 모래로 덮여 있다."),
    "cap":           ("/kæp/", "명사", "모자, 상한선", "Wear a cap outside.", "밖에서 모자를 쓰세요."),
    "prompt":        ("/prɒmpt/", "형용사", "신속한, 즉각적인", "Prompt action is needed.", "신속한 조치가 필요하다."),
    "charm":         ("/tʃɑːrm/", "명사", "매력, 매혹", "She has natural charm.", "그녀는 자연스러운 매력이 있다."),
    "react":         ("/riˈækt/", "동사", "반응하다", "How did you react?", "어떻게 반응했나요?"),
    "lecture":       ("/ˈlɛktʃər/", "명사", "강의, 강연", "Attend the morning lecture.", "오전 강의에 참석하세요."),
    "venture":       ("/ˈvɛntʃər/", "명사", "모험, 사업", "Start a new venture.", "새로운 사업을 시작하세요."),
    "compound":      ("/ˈkɒmpaʊnd/", "명사", "화합물, 복합체", "It is a chemical compound.", "그것은 화학 화합물이다."),
    "rescue":        ("/ˈrɛskjuː/", "동사", "구출하다, 구조하다", "They rescued the survivors.", "그들이 생존자들을 구조했다."),
    "mess":          ("/mɛs/", "명사", "혼란, 엉망", "Clean up this mess.", "이 엉망을 치우세요."),
    "preference":    ("/ˈprɛfərəns/", "명사", "선호, 취향", "What is your preference?", "선호하는 것이 무엇인가요?"),
    "comprehensive": ("/ˌkɒmprɪˈhɛnsɪv/", "형용사", "포괄적인, 종합적인", "A comprehensive review is needed.", "포괄적인 검토가 필요하다."),
    "incentive":     ("/ɪnˈsɛntɪv/", "명사", "동기, 유인책", "Offer an incentive.", "유인책을 제공하세요."),
    "league":        ("/liːɡ/", "명사", "리그, 연맹", "They won the league.", "그들이 리그에서 우승했다."),
    "dialog":        ("/ˈdaɪəlɒɡ/", "명사", "대화", "Open a dialog box.", "대화 상자를 여세요."),
    "cream":         ("/kriːm/", "명사", "크림", "Add cream to the coffee.", "커피에 크림을 추가하세요."),
    "rapid":         ("/ˈræpɪd/", "형용사", "빠른, 신속한", "Rapid growth was expected.", "빠른 성장이 예상됐다."),
    "cancel":        ("/ˈkænsəl/", "동사", "취소하다", "Cancel the reservation.", "예약을 취소하세요."),
    "regret":        ("/rɪˈɡrɛt/", "동사", "후회하다", "I regret the decision.", "그 결정을 후회한다."),
    "dismiss":       ("/dɪsˈmɪs/", "동사", "해고하다, 무시하다", "Don't dismiss the idea.", "아이디어를 무시하지 마세요."),
    "margin":        ("/ˈmɑːrdʒɪn/", "명사", "여백, 마진", "Write notes in the margin.", "여백에 메모를 적으세요."),
    "beneath":       ("/bɪˈniːθ/", "전치사", "~아래에", "Look beneath the surface.", "표면 아래를 보세요."),
    "opponent":      ("/əˈpoʊnənt/", "명사", "반대자, 상대방", "Respect your opponent.", "상대방을 존중하세요."),
    "resist":        ("/rɪˈzɪst/", "동사", "저항하다, 참다", "Resist the temptation.", "유혹을 참으세요."),
    "capability":    ("/ˌkeɪpəˈbɪlɪti/", "명사", "능력, 역량", "Improve your capabilities.", "역량을 향상시키세요."),
    "absolute":      ("/ˈæbsəluːt/", "형용사", "절대적인, 완전한", "That is the absolute truth.", "그것이 절대적인 진실이다."),
    "correspond":    ("/ˌkɒrɪˈspɒnd/", "동사", "상응하다, 통신하다", "The results correspond with data.", "결과가 데이터와 상응한다."),
    "stroke":        ("/stroʊk/", "명사", "뇌졸중, 획", "He had a stroke.", "그는 뇌졸중에 걸렸다."),
    "dare":          ("/dɛər/", "동사", "감히 ~하다", "Don't you dare.", "감히 그러지 마세요."),
    "barrier":       ("/ˈbæriər/", "명사", "장벽, 방해물", "Remove barriers to entry.", "진입 장벽을 없애세요."),
    "rid":           ("/rɪd/", "동사", "없애다, 제거하다", "Get rid of bad habits.", "나쁜 습관을 없애세요."),
    "divorce":       ("/dɪˈvɔːrs/", "명사", "이혼", "They went through a divorce.", "그들은 이혼 과정을 겪었다."),
    "ruin":          ("/ˈruːɪn/", "동사", "망치다, 파괴하다", "Don't ruin the moment.", "순간을 망치지 마세요."),
    "bury":          ("/ˈbɛri/", "동사", "묻다, 매장하다", "Bury the seed in the soil.", "씨앗을 흙에 묻으세요."),
    "counsel":       ("/ˈkaʊnsəl/", "동사", "상담하다, 조언하다", "Counsel the students.", "학생들에게 상담을 해주세요."),
    "tendency":      ("/ˈtɛndənsi/", "명사", "경향, 추세", "There is a tendency to procrastinate.", "미루는 경향이 있다."),
    "frequent":      ("/ˈfriːkwənt/", "형용사", "잦은, 빈번한", "He makes frequent mistakes.", "그는 잦은 실수를 한다."),
    "motor":         ("/ˈmoʊtər/", "명사", "모터, 엔진", "The motor needs repair.", "모터 수리가 필요하다."),
    "survival":      ("/sərˈvaɪvəl/", "명사", "생존", "Survival skills are important.", "생존 기술은 중요하다."),
    "counter":       ("/ˈkaʊntər/", "동사", "반박하다, 맞서다", "Counter the argument.", "주장에 반박하세요."),
    "possess":       ("/pəˈzɛs/", "동사", "소유하다, 가지다", "He possesses great talent.", "그는 훌륭한 재능을 가지고 있다."),
    "permission":    ("/pərˈmɪʃən/", "명사", "허가, 허락", "Ask for permission first.", "먼저 허락을 구하세요."),
    "valley":        ("/ˈvæli/", "명사", "계곡, 골짜기", "The valley is beautiful.", "계곡이 아름답다."),
    "float":         ("/floʊt/", "동사", "떠다니다, 부유하다", "The boat floats on water.", "배가 물 위에 떠 있다."),
    "mad":           ("/mæd/", "형용사", "화가 난, 미친", "Don't get mad at me.", "나한테 화내지 마세요."),
    "greatly":       ("/ˈɡreɪtli/", "부사", "크게, 대단히", "She greatly influenced me.", "그녀는 나에게 크게 영향을 미쳤다."),
    "visible":       ("/ˈvɪzɪbəl/", "형용사", "눈에 보이는", "The stars are visible.", "별들이 보인다."),
    "electric":      ("/ɪˈlɛktrɪk/", "형용사", "전기의", "Buy an electric car.", "전기차를 구매하세요."),
    "impressive":    ("/ɪmˈprɛsɪv/", "형용사", "인상적인", "The result is impressive.", "결과가 인상적이다."),
    "evolution":     ("/ˌiːvəˈluːʃən/", "명사", "진화, 발전", "Darwin studied evolution.", "다윈은 진화를 연구했다."),
    "awareness":     ("/əˈwɛərnɪs/", "명사", "인식, 의식", "Raise public awareness.", "대중의 인식을 높이세요."),
    "violent":       ("/ˈvaɪələnt/", "형용사", "폭력적인", "Violence is never the answer.", "폭력은 절대 해결책이 아니다."),
    "slave":         ("/sleɪv/", "명사", "노예", "Slavery was abolished.", "노예제가 폐지됐다."),
    "wealthy":       ("/ˈwɛlθi/", "형용사", "부유한", "He comes from a wealthy family.", "그는 부유한 가정 출신이다."),
    "architecture":  ("/ˈɑːrkɪtɛktʃər/", "명사", "건축", "Roman architecture is impressive.", "로마 건축은 인상적이다."),
    "acceptable":    ("/əkˈsɛptəbəl/", "형용사", "수용 가능한", "This is not acceptable.", "이것은 용납될 수 없다."),
    "journal":       ("/ˈdʒɜːrnəl/", "명사", "일기, 학술지", "Keep a daily journal.", "매일 일기를 쓰세요."),
    "coal":          ("/koʊl/", "명사", "석탄", "Coal is a fossil fuel.", "석탄은 화석 연료이다."),
    "measurement":   ("/ˈmɛʒərmənt/", "명사", "측정, 치수", "Take accurate measurements.", "정확한 측정을 하세요."),
    "random":        ("/ˈrændəm/", "형용사", "무작위의", "Choose a random number.", "임의의 숫자를 선택하세요."),
    "successfully":  ("/səkˈsɛsfəli/", "부사", "성공적으로", "Complete the task successfully.", "과제를 성공적으로 완료하세요."),
    "depress":       ("/dɪˈprɛs/", "동사", "우울하게 하다, 저하시키다", "Bad news depresses everyone.", "나쁜 소식은 모두를 우울하게 한다."),
    "illustration":  ("/ˌɪləˈstreɪʃən/", "명사", "삽화, 예시", "The book has beautiful illustrations.", "책에 아름다운 삽화가 있다."),
    "burst":         ("/bɜːrst/", "동사", "터지다, 터뜨리다", "The pipe burst overnight.", "밤새 파이프가 터졌다."),
    "privilege":     ("/ˈprɪvɪlɪdʒ/", "명사", "특권, 특전", "It's a privilege to be here.", "이곳에 있는 것은 특권이다."),
    "buyer":         ("/ˈbaɪər/", "명사", "구매자", "Find the right buyer.", "적절한 구매자를 찾으세요."),
    "mutual":        ("/ˈmjuːtʃuəl/", "형용사", "상호의, 공동의", "Mutual respect is essential.", "상호 존중이 필수적이다."),
    "rail":          ("/reɪl/", "명사", "레일, 난간", "Hold onto the rail.", "난간을 잡으세요."),
    "motivate":      ("/ˈmoʊtɪveɪt/", "동사", "동기를 부여하다", "Motivate your team.", "팀에게 동기를 부여하세요."),
    "laboratory":    ("/ˈlæbrətɔːri/", "명사", "실험실", "Work in the laboratory.", "실험실에서 작업하세요."),
    "mortgage":      ("/ˈmɔːrɡɪdʒ/", "명사", "주택 담보 대출", "Apply for a mortgage.", "주택 담보 대출을 신청하세요."),
    "passion":       ("/ˈpæʃən/", "명사", "열정, 열의", "Follow your passion.", "열정을 따르세요."),
    "champion":      ("/ˈtʃæmpiən/", "명사", "챔피언, 우승자", "She is the reigning champion.", "그녀는 현직 챔피언이다."),
    "fulfill":       ("/fʊlˈfɪl/", "동사", "이행하다, 충족시키다", "Fulfill your obligations.", "의무를 이행하세요."),
    "dust":          ("/dʌst/", "명사", "먼지", "Wipe away the dust.", "먼지를 닦으세요."),
    "dedicate":      ("/ˈdɛdɪkeɪt/", "동사", "헌정하다, 전념하다", "Dedicate time to learning.", "배움에 시간을 바치세요."),
    "roughly":       ("/ˈrʌfli/", "부사", "대략, 거칠게", "It costs roughly $100.", "대략 100달러이다."),
    "skirt":         ("/skɜːrt/", "명사", "치마", "She wore a long skirt.", "그녀는 긴 치마를 입었다."),
    "province":      ("/ˈprɒvɪns/", "명사", "지방, 주", "He is from a northern province.", "그는 북부 지방 출신이다."),
    "march":         ("/mɑːrtʃ/", "동사", "행진하다", "They march every day.", "그들은 매일 행진한다."),
    "evaluation":    ("/ɪˌvæljuˈeɪʃən/", "명사", "평가", "The evaluation was positive.", "평가가 긍정적이었다."),
    "compromise":    ("/ˈkɒmprəmaɪz/", "동사", "타협하다", "We must compromise.", "우리는 타협해야 한다."),
    "accomplish":    ("/əˈkɒmplɪʃ/", "동사", "달성하다, 성취하다", "Accomplish your goals.", "목표를 달성하세요."),
    "weakness":      ("/ˈwiːknɪs/", "명사", "약점, 단점", "Identify your weaknesses.", "약점을 파악하세요."),
    "announcement":  ("/əˈnaʊnsmənt/", "명사", "공고, 발표", "Read the announcement.", "공고를 읽으세요."),
    "salt":          ("/sɔːlt/", "명사", "소금", "Add a pinch of salt.", "소금을 한 꼬집 넣으세요."),
    "glance":        ("/ɡlɑːns/", "동사", "흘끗 보다", "She glanced at her watch.", "그녀는 시계를 흘끗 봤다."),
    "opera":         ("/ˈɒpərə/", "명사", "오페라", "She loves the opera.", "그녀는 오페라를 좋아한다."),
    "contest":       ("/ˈkɒntɛst/", "명사", "대회, 경연", "Enter the singing contest.", "노래 대회에 참가하세요."),
    "brush":         ("/brʌʃ/", "동사", "솔질하다, 빗다", "Brush your hair.", "머리를 빗으세요."),
    "embarrass":     ("/ɪmˈbærəs/", "동사", "당황하게 하다", "Don't embarrass me.", "나를 당황하게 하지 마세요."),
    "gallery":       ("/ˈɡæləri/", "명사", "갤러리, 화랑", "Visit the art gallery.", "미술관을 방문하세요."),
    "genetic":       ("/dʒɪˈnɛtɪk/", "형용사", "유전의", "Genetic research is advancing.", "유전 연구가 발전하고 있다."),
    "aggressive":    ("/əˈɡrɛsɪv/", "형용사", "공격적인", "Don't be aggressive.", "공격적이지 마세요."),
    "chest":         ("/tʃɛst/", "명사", "가슴, 상자", "His chest hurts.", "가슴이 아프다."),
    "format":        ("/ˈfɔːrmæt/", "명사", "형식, 포맷", "Use the correct format.", "올바른 형식을 사용하세요."),
    "literary":      ("/ˈlɪtərəri/", "형용사", "문학의, 문어적인", "She has a literary style.", "그녀는 문학적인 문체가 있다."),
    "govern":        ("/ˈɡʌvərn/", "동사", "통치하다, 지배하다", "The laws govern behavior.", "법이 행동을 지배한다."),
    "embrace":       ("/ɪmˈbreɪs/", "동사", "포옹하다, 수용하다", "Embrace the change.", "변화를 수용하세요."),
    "praise":        ("/preɪz/", "동사", "칭찬하다", "Praise good work.", "좋은 작업을 칭찬하세요."),
    "silent":        ("/ˈsaɪlənt/", "형용사", "조용한, 침묵의", "The room was completely silent.", "방은 완전히 조용했다."),
    "pump":          ("/pʌmp/", "동사", "펌프질하다, 주입하다", "Pump air into the tire.", "타이어에 공기를 주입하세요."),
    "publisher":     ("/ˈpʌblɪʃər/", "명사", "출판사, 발행인", "The publisher accepted the book.", "출판사가 책을 받아들였다."),
    "celebration":   ("/ˌsɛlɪˈbreɪʃən/", "명사", "축하, 기념식", "Join the celebration.", "축하 행사에 참여하세요."),
    "golf":          ("/ɡɒlf/", "명사", "골프", "He plays golf every weekend.", "그는 매주 주말에 골프를 친다."),
    "compensation":  ("/ˌkɒmpɛnˈseɪʃən/", "명사", "보상, 보상금", "Receive fair compensation.", "공정한 보상을 받으세요."),
    "classical":     ("/ˈklæsɪkəl/", "형용사", "고전의", "She plays classical music.", "그녀는 클래식 음악을 연주한다."),
    "weigh":         ("/weɪ/", "동사", "무게를 재다, 무게가 나가다", "Weigh the ingredients carefully.", "재료를 조심스럽게 무게를 재세요."),
    "versus":        ("/ˈvɜːrsəs/", "전치사", "~대, ~에 대항하여", "Team A versus Team B.", "A팀 대 B팀."),
    "deficit":       ("/ˈdɛfɪsɪt/", "명사", "적자, 부족", "Reduce the budget deficit.", "예산 적자를 줄이세요."),
    "modify":        ("/ˈmɒdɪfaɪ/", "동사", "수정하다, 변형하다", "Modify the design slightly.", "디자인을 약간 수정하세요."),
    "flash":         ("/flæʃ/", "동사", "번쩍이다, 보이다", "A message flashed on screen.", "화면에 메시지가 번쩍였다."),
    "friendship":    ("/ˈfrɛndʃɪp/", "명사", "우정", "Cherish your friendships.", "우정을 소중히 여기세요."),
    "profession":    ("/prəˈfɛʃən/", "명사", "직업, 전문직", "Choose a profession you love.", "좋아하는 직업을 선택하세요."),
    "literally":     ("/ˈlɪtərəli/", "부사", "글자 그대로, 정말로", "It was literally amazing.", "그것은 정말로 놀라웠다."),
    "equation":      ("/ɪˈkweɪʒən/", "명사", "방정식, 등식", "Solve the equation.", "방정식을 풀으세요."),
    "gesture":       ("/ˈdʒɛstʃər/", "명사", "몸짓, 제스처", "A kind gesture means a lot.", "친절한 몸짓은 많은 것을 의미한다."),
    "entertain":     ("/ˌɛntərˈteɪn/", "동사", "즐겁게 하다, 접대하다", "Entertain the guests.", "손님들을 즐겁게 해주세요."),
    "fantastic":     ("/fænˈtæstɪk/", "형용사", "환상적인, 훌륭한", "The show was fantastic.", "공연이 환상적이었다."),
    "assign":        ("/əˈsaɪn/", "동사", "할당하다, 배정하다", "Assign tasks to team members.", "팀원들에게 업무를 할당하세요."),
    "inflation":     ("/ɪnˈfleɪʃən/", "명사", "인플레이션, 물가 상승", "Inflation is rising.", "인플레이션이 오르고 있다."),
    "historic":      ("/hɪˈstɒrɪk/", "형용사", "역사적인", "This is a historic moment.", "이것은 역사적인 순간이다."),
    "injure":        ("/ˈɪndʒər/", "동사", "다치게 하다", "He injured his arm.", "그는 팔을 다쳤다."),
    "remote":        ("/rɪˈmoʊt/", "형용사", "원격의, 먼", "Work in a remote location.", "원격 위치에서 일하다."),
    "therapy":       ("/ˈθɛrəpi/", "명사", "치료, 요법", "Physical therapy helps recovery.", "물리 치료가 회복에 도움이 된다."),
    "orange":        ("/ˈɒrɪndʒ/", "명사", "오렌지, 주황색", "Peel the orange.", "오렌지를 벗기세요."),
    "twist":         ("/twɪst/", "동사", "비틀다, 꼬다", "Twist the cap off.", "뚜껑을 비틀어 여세요."),
    "personnel":     ("/ˌpɜːrsəˈnɛl/", "명사", "직원, 인원", "All personnel must attend.", "모든 직원이 참석해야 한다."),
    "imagination":   ("/ɪˌmædʒɪˈneɪʃən/", "명사", "상상력", "Use your imagination.", "상상력을 발휘하세요."),
    "disagree":      ("/ˌdɪsəˈɡriː/", "동사", "동의하지 않다", "I disagree with that.", "그것에 동의하지 않는다."),
    "throat":        ("/θroʊt/", "명사", "목구멍", "She has a sore throat.", "그녀는 인후통이 있다."),
    "insight":       ("/ˈɪnsaɪt/", "명사", "통찰력, 이해", "Share your insights.", "통찰력을 공유하세요."),
    "tackle":        ("/ˈtækəl/", "동사", "다루다, 해결하다", "Tackle the problem directly.", "문제를 직접 다루세요."),
    "forever":       ("/fərˈɛvər/", "부사", "영원히", "This moment will last forever.", "이 순간은 영원히 지속된다."),
    "exceed":        ("/ɪkˈsiːd/", "동사", "초과하다, 능가하다", "Exceed customer expectations.", "고객 기대를 초과하세요."),
    "expenditure":   ("/ɪkˈspɛndɪtʃər/", "명사", "지출, 비용", "Reduce unnecessary expenditure.", "불필요한 지출을 줄이세요."),
    "joy":           ("/dʒɔɪ/", "명사", "기쁨, 즐거움", "Fill your life with joy.", "삶을 기쁨으로 채우세요."),
    "pregnant":      ("/ˈprɛɡnənt/", "형용사", "임신한", "She is six months pregnant.", "그녀는 임신 6개월이다."),
    "reliable":      ("/rɪˈlaɪəbəl/", "형용사", "신뢰할 수 있는", "Choose a reliable partner.", "신뢰할 수 있는 파트너를 선택하세요."),
    "gear":          ("/ɡɪər/", "명사", "기어, 장비", "Shift to a higher gear.", "높은 기어로 바꾸세요."),
    "click":         ("/klɪk/", "동사", "클릭하다", "Click the button.", "버튼을 클릭하세요."),
    "poet":          ("/ˈpoʊɪt/", "명사", "시인", "Shakespeare was a great poet.", "셰익스피어는 위대한 시인이었다."),
    "fortune":       ("/ˈfɔːrtʃən/", "명사", "운, 재산", "Good fortune comes to those who wait.", "기다리는 자에게 행운이 온다."),
    "ceremony":      ("/ˈsɛrɪmoʊni/", "명사", "의식, 행사", "Attend the graduation ceremony.", "졸업식에 참석하세요."),
    "pile":          ("/paɪl/", "명사", "더미, 쌓음", "A pile of books.", "책 더미."),
    "pig":           ("/pɪɡ/", "명사", "돼지", "Pigs are intelligent animals.", "돼지는 똑똑한 동물이다."),
    "mixture":       ("/ˈmɪkstʃər/", "명사", "혼합, 혼합물", "Stir the mixture.", "혼합물을 저으세요."),
    "automatically": ("/ˌɔːtəˈmætɪkli/", "부사", "자동으로", "It saves automatically.", "자동으로 저장된다."),
    "scholar":       ("/ˈskɒlər/", "명사", "학자", "She is a respected scholar.", "그녀는 존경받는 학자이다."),
    "psychological": ("/ˌsaɪkəˈlɒdʒɪkəl/", "형용사", "심리적인", "Psychological support is needed.", "심리적 지원이 필요하다."),
    "dramatically":  ("/drəˈmætɪkli/", "부사", "극적으로, 대폭", "Sales increased dramatically.", "판매가 극적으로 증가했다."),
    "stake":         ("/steɪk/", "명사", "지분, 말뚝", "There is a lot at stake.", "많은 것이 걸려 있다."),
    "creature":      ("/ˈkriːtʃər/", "명사", "생명체, 동물", "Every creature has a purpose.", "모든 생명체는 목적이 있다."),
    "partnership":   ("/ˈpɑːrtnərʃɪp/", "명사", "파트너십, 협력", "Build a strong partnership.", "강한 파트너십을 구축하세요."),
    "participation": ("/pɑːrˌtɪsɪˈpeɪʃən/", "명사", "참여, 참가", "Participation is encouraged.", "참여를 장려합니다."),
    "clause":        ("/klɔːz/", "명사", "절, 조항", "Read each clause carefully.", "각 조항을 주의 깊게 읽으세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT9:
                    pron, pos, meaning, ex_en, ex_ko = DICT9[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more9.py ===\n")
    patch_files()
