#!/usr/bin/env python3
"""Fourth-pass fill: freq-L4 (251 words), freq-L5 (top), TOEIC-L1 (183 words)."""
import json, glob

DICT4 = {
    # =========================================================
    # freq-L4 (251 fallback words)
    # =========================================================
    "seat":        ("/siːt/", "명사", "좌석, 자리", "Please take your seat.", "자리에 앉아 주세요."),
    "throw":       ("/θroʊ/", "동사", "던지다", "Please throw the ball.", "공을 던지세요."),
    "task":        ("/tɑːsk/", "명사", "과제, 임무", "Complete the task on time.", "제때 과제를 완료하세요."),
    "normal":      ("/ˈnɔːrməl/", "형용사", "정상적인, 보통의", "This is normal behavior.", "이것은 정상적인 행동입니다."),
    "goal":        ("/ɡoʊl/", "명사", "목표, 골", "What is your goal?", "당신의 목표는 무엇인가요?"),
    "associate":   ("/əˈsoʊʃieɪt/", "동사", "연관시키다", "I associate summer with travel.", "저는 여름을 여행과 연관 짓습니다."),
    "blue":        ("/bluː/", "형용사", "파란, 푸른", "The sky is blue.", "하늘이 파랗습니다."),
    "box":         ("/bɒks/", "명사", "상자, 박스", "Put it in the box.", "상자에 넣으세요."),
    "huge":        ("/hjuːdʒ/", "형용사", "거대한, 막대한", "It was a huge success.", "엄청난 성공이었습니다."),
    "instance":    ("/ˈɪnstəns/", "명사", "예, 사례", "For instance, we can use...", "예를 들어, 우리는 ~을 사용할 수 있습니다."),
    "style":       ("/staɪl/", "명사", "스타일, 방식", "I like your style.", "당신의 스타일이 마음에 듭니다."),
    "refer":       ("/rɪˈfɜːr/", "동사", "언급하다, 참조하다", "Please refer to page 5.", "5페이지를 참조해 주세요."),
    "cold":        ("/koʊld/", "형용사", "추운, 차가운", "It's very cold today.", "오늘은 매우 춥습니다."),
    "push":        ("/pʊʃ/", "동사", "밀다, 밀치다", "Push the button.", "버튼을 미세요."),
    "quarter":     ("/ˈkwɔːrtər/", "명사", "4분의 1, 분기", "It's a quarter past three.", "3시 15분입니다."),
    "baby":        ("/ˈbeɪbi/", "명사", "아기, 아이", "The baby is sleeping.", "아기가 자고 있습니다."),
    "successful":  ("/səkˈsɛsfəl/", "형용사", "성공적인", "She had a successful career.", "그녀는 성공적인 커리어를 가졌습니다."),
    "sing":        ("/sɪŋ/", "동사", "노래하다", "She loves to sing.", "그녀는 노래하는 것을 좋아합니다."),
    "doubt":       ("/daʊt/", "명사", "의심, 의혹", "I have some doubts.", "몇 가지 의심이 듭니다."),
    "competition": ("/ˌkɒmpɪˈtɪʃən/", "명사", "경쟁, 대회", "The competition was tough.", "경쟁이 치열했습니다."),
    "theory":      ("/ˈθɪəri/", "명사", "이론, 학설", "It's just a theory.", "그것은 그냥 이론일 뿐입니다."),
    "propose":     ("/prəˈpoʊz/", "동사", "제안하다, 청혼하다", "I propose we try a new method.", "새 방법을 시도해 보자고 제안합니다."),
    "reference":   ("/ˈrɛfərəns/", "명사", "참고, 참조", "Please check the reference.", "참고 자료를 확인해 주세요."),
    "argument":    ("/ˈɑːrɡjəmənt/", "명사", "주장, 논쟁", "Make a strong argument.", "강력한 주장을 하세요."),
    "adult":       ("/ˈædʌlt/", "명사", "성인, 어른", "This movie is for adults only.", "이 영화는 성인 전용입니다."),
    "fly":         ("/flaɪ/", "동사", "날다, 비행하다", "The bird can fly high.", "새가 높이 날 수 있습니다."),
    "document":    ("/ˈdɒkjəmənt/", "명사", "문서, 서류", "Please sign this document.", "이 문서에 서명해 주세요."),
    "pattern":     ("/ˈpætərn/", "명사", "패턴, 양식", "I see a pattern here.", "여기서 패턴이 보입니다."),
    "application": ("/ˌæplɪˈkeɪʃən/", "명사", "지원서, 응용 프로그램", "Submit your application by Monday.", "월요일까지 지원서를 제출하세요."),
    "hot":         ("/hɒt/", "형용사", "뜨거운, 더운", "Be careful, it's hot.", "조심하세요, 뜨겁습니다."),
    "obviously":   ("/ˈɒbviəsli/", "부사", "명백히, 분명히", "This is obviously wrong.", "이것은 명백히 틀렸습니다."),
    "unclear":     ("/ʌnˈklɪər/", "형용사", "불분명한, 불명확한", "The instructions are unclear.", "지시사항이 불명확합니다."),
    "bill":        ("/bɪl/", "명사", "청구서, 법안", "Please pay the bill.", "계산서를 지불해 주세요."),
    "search":      ("/sɜːrtʃ/", "동사", "검색하다, 찾다", "Search for the information.", "정보를 검색하세요."),
    "separate":    ("/ˈsɛpərɪt/", "형용사", "분리된, 별개의", "Please keep them separate.", "따로 보관해 주세요."),
    "central":     ("/ˈsɛntrəl/", "형용사", "중심의, 핵심적인", "This is the central issue.", "이것이 핵심 문제입니다."),
    "career":      ("/kəˈrɪər/", "명사", "직업, 커리어", "She has a great career.", "그녀는 훌륭한 커리어를 가지고 있습니다."),
    "anyway":      ("/ˈɛniweɪ/", "부사", "어쨌든, 그래도", "Anyway, let's get started.", "어쨌든, 시작합시다."),
    "speech":      ("/spiːtʃ/", "명사", "연설, 말", "She gave a great speech.", "그녀는 훌륭한 연설을 했습니다."),
    "dog":         ("/dɒɡ/", "명사", "개, 강아지", "I have a pet dog.", "저는 애완견이 있습니다."),
    "officer":     ("/ˈɒfɪsər/", "명사", "경찰관, 장교", "The officer helped us.", "경찰관이 우리를 도와주었습니다."),
    "throughout":  ("/θruːˈaʊt/", "전치사", "~전반에 걸쳐, 내내", "It rained throughout the day.", "하루 종일 비가 왔습니다."),
    "oil":         ("/ɔɪl/", "명사", "기름, 석유", "Check the oil level.", "기름 수준을 확인하세요."),
    "dress":       ("/drɛs/", "명사", "드레스, 옷", "She wore a beautiful dress.", "그녀는 아름다운 드레스를 입었습니다."),
    "guess":       ("/ɡɛs/", "동사", "추측하다", "Can you guess the answer?", "답을 추측할 수 있나요?"),
    "fun":         ("/fʌn/", "명사", "재미, 즐거움", "Learning can be fun.", "배우는 것은 재미있을 수 있습니다."),
    "disease":     ("/dɪˈziːz/", "명사", "질병, 병", "Exercise can prevent disease.", "운동이 질병을 예방할 수 있습니다."),
    "balance":     ("/ˈbæləns/", "명사", "균형, 잔액", "Maintain a work-life balance.", "일과 생활의 균형을 유지하세요."),
    "damage":      ("/ˈdæmɪdʒ/", "명사", "손상, 피해", "The storm caused damage.", "폭풍이 피해를 일으켰습니다."),
    "basis":       ("/ˈbeɪsɪs/", "명사", "기초, 근거", "On a daily basis.", "매일 기준으로."),
    "author":      ("/ˈɔːθər/", "명사", "저자, 작가", "She is a famous author.", "그녀는 유명한 작가입니다."),
    "encourage":   ("/ɪnˈkɜːrɪdʒ/", "동사", "격려하다, 장려하다", "Please encourage your team.", "팀을 격려해 주세요."),
    "hair":        ("/hɛər/", "명사", "머리카락, 헤어", "She has long hair.", "그녀는 긴 머리카락을 가지고 있습니다."),
    "male":        ("/meɪl/", "형용사", "남성의, 수컷의", "Is it male or female?", "수컷인가요 암컷인가요?"),
    "operate":     ("/ˈɒpəreɪt/", "동사", "운영하다, 작동하다", "How does this machine operate?", "이 기계는 어떻게 작동하나요?"),
    "reflect":     ("/rɪˈflɛkt/", "동사", "반영하다, 반성하다", "Please reflect on your actions.", "자신의 행동을 반성해 주세요."),
    "exercise":    ("/ˈɛksərsaɪz/", "명사", "운동, 연습", "Daily exercise is important.", "매일 운동이 중요합니다."),
    "useful":      ("/ˈjuːsfəl/", "형용사", "유용한, 쓸모 있는", "This tool is very useful.", "이 도구는 매우 유용합니다."),
    "restaurant":  ("/ˈrɛstərɒnt/", "명사", "식당, 레스토랑", "Let's go to a restaurant.", "식당에 가자."),
    "income":      ("/ˈɪnkʌm/", "명사", "소득, 수입", "Her income has increased.", "그녀의 소득이 증가했습니다."),
    # freq-L4 continued...
    "connect":     ("/kəˈnɛkt/", "동사", "연결하다", "Connect the cable.", "케이블을 연결하세요."),
    "interview":   ("/ˈɪntərvjuː/", "명사", "면접, 인터뷰", "She passed the interview.", "그녀는 면접에 합격했습니다."),
    "magazine":    ("/ˌmæɡəˈziːn/", "명사", "잡지", "I read the magazine.", "잡지를 읽었습니다."),
    "network":     ("/ˈnɛtwɜːrk/", "명사", "네트워크, 방송망", "Build your network.", "인적 네트워크를 구축하세요."),
    "prefer":      ("/prɪˈfɜːr/", "동사", "더 좋아하다, 선호하다", "I prefer tea to coffee.", "저는 커피보다 차를 선호합니다."),
    "vehicle":     ("/ˈviːɪkəl/", "명사", "차량, 탈것", "What type of vehicle is it?", "어떤 종류의 차량인가요?"),
    "airport":     ("/ˈɛərpɔːrt/", "명사", "공항", "The airport is very busy.", "공항이 매우 붐빕니다."),
    "medicine":    ("/ˈmɛdɪsɪn/", "명사", "약, 의학", "Take this medicine after meals.", "식후에 이 약을 복용하세요."),
    "shoulder":    ("/ˈʃoʊldər/", "명사", "어깨", "She has a sore shoulder.", "그녀는 어깨가 아픕니다."),
    "museum":      ("/mjuːˈziːəm/", "명사", "박물관, 미술관", "Let's visit the museum.", "박물관을 방문합시다."),
    "apartment":   ("/əˈpɑːrtmənt/", "명사", "아파트", "I live in an apartment.", "저는 아파트에 삽니다."),
    "university":  ("/ˌjuːnɪˈvɜːrsɪti/", "명사", "대학교", "She studies at a university.", "그녀는 대학교에서 공부합니다."),
    "citizen":     ("/ˈsɪtɪzən/", "명사", "시민", "Every citizen has rights.", "모든 시민은 권리가 있습니다."),
    "cultural":    ("/ˈkʌltʃərəl/", "형용사", "문화적인", "It's a cultural event.", "문화 행사입니다."),
    "democratic":  ("/ˌdɛməˈkrætɪk/", "형용사", "민주적인", "This is a democratic society.", "이것은 민주적인 사회입니다."),
    "responsibility":("/rɪˌspɒnsɪˈbɪlɪti/", "명사", "책임", "Take responsibility for your actions.", "행동에 책임을 지세요."),
    "recognize":   ("/ˈrɛkəɡnaɪz/", "동사", "알아보다, 인정하다", "I didn't recognize you.", "당신을 알아보지 못했습니다."),
    "describe":    ("/dɪˈskraɪb/", "동사", "묘사하다", "Can you describe the person?", "그 사람을 묘사해 줄 수 있나요?"),
    "importance":  ("/ɪmˈpɔːrtəns/", "명사", "중요성", "Understand the importance.", "중요성을 이해하세요."),
    "concern":     ("/kənˈsɜːrn/", "명사", "걱정, 우려", "This is a major concern.", "이것은 주요 우려 사항입니다."),
    "imagine":     ("/ɪˈmædʒɪn/", "동사", "상상하다", "Imagine a better world.", "더 좋은 세상을 상상해 보세요."),
    "consider":    ("/kənˈsɪdər/", "동사", "고려하다, 생각하다", "Please consider this carefully.", "이것을 신중하게 고려해 주세요."),
    "collect":     ("/kəˈlɛkt/", "동사", "수집하다, 모으다", "She collects stamps.", "그녀는 우표를 수집합니다."),
    "aware":       ("/əˈwɛər/", "형용사", "알고 있는, 의식하는", "Are you aware of the rules?", "규칙을 알고 있나요?"),
    "interested":  ("/ˈɪntrɪstɪd/", "형용사", "관심 있는", "Are you interested?", "관심 있으신가요?"),
    "responsible": ("/rɪˈspɒnsɪbəl/", "형용사", "책임감 있는", "Be responsible.", "책임감을 가지세요."),
    "complex":     ("/ˈkɒmplɛks/", "형용사", "복잡한", "This is very complex.", "이것은 매우 복잡합니다."),
    "additional":  ("/əˈdɪʃənəl/", "형용사", "추가적인", "Additional information is needed.", "추가 정보가 필요합니다."),
    "active":      ("/ˈæktɪv/", "형용사", "활동적인, 적극적인", "Stay active and healthy.", "활동적이고 건강하게 지내세요."),
    "replace":     ("/rɪˈpleɪs/", "동사", "교체하다, 대체하다", "We need to replace this.", "이것을 교체해야 합니다."),
    "improve":     ("/ɪmˈpruːv/", "동사", "개선하다", "How can we improve this?", "어떻게 개선할 수 있을까요?"),
    "interview":   ("/ˈɪntərvjuː/", "명사", "인터뷰, 면접", "I have a job interview.", "취업 면접이 있습니다."),
    "expect":      ("/ɪkˈspɛkt/", "동사", "기대하다, 예상하다", "I expect results.", "결과를 기대합니다."),
    "responsible": ("/rɪˈspɒnsɪbəl/", "형용사", "책임 있는", "You are responsible for this.", "당신이 이것에 책임이 있습니다."),
    "maintain":    ("/meɪnˈteɪn/", "동사", "유지하다", "Maintain a positive attitude.", "긍정적인 태도를 유지하세요."),
    "require":     ("/rɪˈkwaɪər/", "동사", "필요로 하다", "This requires patience.", "이것은 인내가 필요합니다."),
    "develop":     ("/dɪˈvɛləp/", "동사", "개발하다, 발전하다", "Develop new skills.", "새로운 기술을 개발하세요."),
    "explain":     ("/ɪkˈspleɪn/", "동사", "설명하다", "Please explain clearly.", "명확하게 설명해 주세요."),
    "opinion":     ("/əˈpɪnjən/", "명사", "의견", "Share your opinion.", "의견을 공유해 주세요."),
    "surprise":    ("/səˈpraɪz/", "명사", "놀라움", "What a surprise!", "놀랍네요!"),
    "negative":    ("/ˈnɛɡətɪv/", "형용사", "부정적인", "Avoid negative thinking.", "부정적인 생각을 피하세요."),
    "manage":      ("/ˈmænɪdʒ/", "동사", "관리하다", "Manage your time well.", "시간을 잘 관리하세요."),
    "network":     ("/ˈnɛtwɜːrk/", "명사", "네트워크", "Build your network.", "네트워크를 구축하세요."),
    "cultural":    ("/ˈkʌltʃərəl/", "형용사", "문화적인", "Cultural differences exist.", "문화적 차이가 있습니다."),
    "significant": ("/sɪɡˈnɪfɪkənt/", "형용사", "중요한", "This is significant.", "이것은 중요합니다."),
    # =========================================================
    # freq-L5 top fallback words
    # =========================================================
    "consumer":    ("/kənˈsjuːmər/", "명사", "소비자", "The consumer is always right.", "소비자는 항상 옳습니다."),
    "favor":       ("/ˈfeɪvər/", "명사", "호의, 부탁", "Can you do me a favor?", "부탁 하나 들어줄 수 있나요?"),
    "dry":         ("/draɪ/", "형용사", "건조한, 마른", "Keep this dry.", "이것을 건조하게 유지하세요."),
    "institution": ("/ˌɪnstɪˈtjuːʃən/", "명사", "기관, 제도", "She works at an institution.", "그녀는 기관에서 일합니다."),
    "spot":        ("/spɒt/", "명사", "장소, 지점", "This is a good spot.", "이곳은 좋은 장소입니다."),
    "eventually":  ("/ɪˈvɛntʃuəli/", "부사", "결국, 마침내", "We will eventually succeed.", "우리는 결국 성공할 것입니다."),
    "heat":        ("/hiːt/", "명사", "열, 더위", "The heat is unbearable.", "더위가 견딜 수 없을 정도입니다."),
    "importance":  ("/ɪmˈpɔːrtəns/", "명사", "중요성", "The importance cannot be overstated.", "중요성은 아무리 강조해도 지나치지 않습니다."),
    "distance":    ("/ˈdɪstəns/", "명사", "거리, 멀리", "What is the distance?", "거리가 얼마나 되나요?"),
    "guide":       ("/ɡaɪd/", "명사", "안내서, 가이드", "Use the guide to navigate.", "안내서를 이용하여 탐색하세요."),
    "grant":       ("/ɡrɑːnt/", "명사", "보조금, 허가", "She received a research grant.", "그녀는 연구 보조금을 받았습니다."),
    "taxi":        ("/ˈtæksi/", "명사", "택시", "Let's take a taxi.", "택시를 타자."),
    "feed":        ("/fiːd/", "동사", "먹이다, 공급하다", "Feed the information into the system.", "정보를 시스템에 입력하세요."),
    "pain":        ("/peɪn/", "명사", "고통, 아픔", "She is in pain.", "그녀는 고통을 느끼고 있습니다."),
    "sector":      ("/ˈsɛktər/", "명사", "부문, 분야", "The public sector is growing.", "공공 부문이 성장하고 있습니다."),
    "mistake":     ("/mɪˈsteɪk/", "명사", "실수, 잘못", "Everyone makes mistakes.", "모든 사람은 실수를 합니다."),
    "ensure":      ("/ɪnˈʃʊər/", "동사", "확실히 하다", "Ensure the safety of all.", "모든 사람의 안전을 확실히 하세요."),
    "satisfy":     ("/ˈsætɪsfaɪ/", "동사", "만족시키다", "We aim to satisfy customers.", "고객을 만족시키는 것을 목표로 합니다."),
    "chief":       ("/tʃiːf/", "명사", "우두머리, 수장", "He is the chief officer.", "그는 수석 책임자입니다."),
    "cool":        ("/kuːl/", "형용사", "시원한, 멋진", "The weather is cool.", "날씨가 시원합니다."),
    "expert":      ("/ˈɛkspɜːrt/", "명사", "전문가", "She is an expert in her field.", "그녀는 분야의 전문가입니다."),
    "wave":        ("/weɪv/", "명사", "파도, 물결", "Ride the wave of change.", "변화의 물결을 타세요."),
    "labor":       ("/ˈleɪbər/", "명사", "노동, 노력", "Labor costs have increased.", "인건비가 증가했습니다."),
    "surface":     ("/ˈsɜːrfɪs/", "명사", "표면, 겉면", "The surface is smooth.", "표면이 매끄럽습니다."),
    "library":     ("/ˈlaɪbrəri/", "명사", "도서관", "I borrowed a book from the library.", "도서관에서 책을 빌렸습니다."),
    "excellent":   ("/ˈɛksələnt/", "형용사", "훌륭한, 우수한", "The food was excellent.", "음식이 훌륭했습니다."),
    "edge":        ("/ɛdʒ/", "명사", "가장자리, 우위", "Be careful near the edge.", "가장자리 근처에서 조심하세요."),
    "audience":    ("/ˈɔːdiəns/", "명사", "청중, 관객", "The audience was excited.", "청중이 흥분했습니다."),
    "lift":        ("/lɪft/", "동사", "들어 올리다", "Can you lift this box?", "이 상자를 들 수 있나요?"),
    "procedure":   ("/prəˈsiːdʒər/", "명사", "절차, 과정", "Follow the procedure.", "절차를 따르세요."),
    "global":      ("/ˈɡloʊbəl/", "형용사", "전 세계적인, 국제적인", "This is a global issue.", "이것은 전 세계적인 문제입니다."),
    "struggle":    ("/ˈstrʌɡəl/", "동사", "고군분투하다, 애쓰다", "I struggled to understand.", "이해하려고 애썼습니다."),
    "select":      ("/sɪˈlɛkt/", "동사", "선택하다, 고르다", "Please select an option.", "선택지를 선택해 주세요."),
    "extent":      ("/ɪkˈstɛnt/", "명사", "정도, 범위", "To a great extent.", "상당한 정도까지."),
    "river":       ("/ˈrɪvər/", "명사", "강", "The river is beautiful.", "강이 아름답습니다."),
    "annual":      ("/ˈænjuəl/", "형용사", "연간의, 매년의", "Annual revenue increased.", "연간 매출이 증가했습니다."),
    "fully":       ("/ˈfʊli/", "부사", "완전히, 충분히", "I fully understand.", "완전히 이해합니다."),
    "contrast":    ("/ˈkɒntrɑːst/", "명사", "대조, 대비", "There is a stark contrast.", "뚜렷한 대조가 있습니다."),
    "roll":        ("/roʊl/", "동사", "굴리다, 구르다", "Roll the dice.", "주사위를 굴리세요."),
    "reality":     ("/riˈælɪti/", "명사", "현실", "Face reality.", "현실을 직시하세요."),
    "photograph":  ("/ˈfoʊtəɡrɑːf/", "명사", "사진", "Take a photograph.", "사진을 찍으세요."),
    "artist":      ("/ˈɑːrtɪst/", "명사", "예술가, 화가", "She is a talented artist.", "그녀는 재능 있는 예술가입니다."),
    "conflict":    ("/ˈkɒnflɪkt/", "명사", "갈등, 분쟁", "There is a conflict of interest.", "이해충돌이 있습니다."),
    "presence":    ("/ˈprɛzəns/", "명사", "존재, 참석", "Thank you for your presence.", "참석해 주셔서 감사합니다."),
    "crowd":       ("/kraʊd/", "명사", "군중, 무리", "A large crowd gathered.", "많은 군중이 모였습니다."),
    "corner":      ("/ˈkɔːrnər/", "명사", "모퉁이, 코너", "Turn left at the corner.", "모퉁이에서 왼쪽으로 도세요."),
    "shift":       ("/ʃɪft/", "동사", "이동하다, 교대하다", "There's been a shift in plans.", "계획에 변화가 생겼습니다."),
    "category":    ("/ˈkætɪɡəri/", "명사", "카테고리, 범주", "Select a category.", "카테고리를 선택하세요."),
    "secretary":   ("/ˈsɛkrɪtəri/", "명사", "비서, 장관", "Please contact my secretary.", "제 비서에게 연락해 주세요."),
    "defense":     ("/dɪˈfɛns/", "명사", "방어, 방위", "A good defense is important.", "좋은 방어가 중요합니다."),
    "quick":       ("/kwɪk/", "형용사", "빠른, 신속한", "Be quick!", "빨리 하세요!"),
    # =========================================================
    # TOEIC L1 (183 fallback words)
    # =========================================================
    "receipt":     ("/rɪˈsiːt/", "명사", "영수증", "Keep your receipt.", "영수증을 보관하세요."),
    "outdoor":     ("/ˈaʊtdɔːr/", "형용사", "야외의", "I enjoy outdoor activities.", "저는 야외 활동을 즐깁니다."),
    "suitcase":    ("/ˈsuːtkeɪs/", "명사", "여행 가방", "My suitcase is too heavy.", "여행 가방이 너무 무겁습니다."),
    "occupation":  ("/ˌɒkjʊˈpeɪʃən/", "명사", "직업, 직종", "What is your occupation?", "직업이 무엇인가요?"),
    "postpone":    ("/poʊstˈpoʊn/", "동사", "연기하다, 미루다", "We had to postpone the meeting.", "회의를 연기해야 했습니다."),
    "umbrella":    ("/ʌmˈbrɛlə/", "명사", "우산", "Don't forget your umbrella.", "우산을 잊지 마세요."),
    "cellphone":   ("/ˈsɛlfoʊn/", "명사", "휴대폰", "My cellphone is dead.", "휴대폰 배터리가 다 됐습니다."),
    "merchandise": ("/ˈmɜːrtʃəndaɪz/", "명사", "상품, 제품", "The merchandise is on display.", "상품이 전시되어 있습니다."),
    "receptionist":("/rɪˈsɛpʃənɪst/", "명사", "접수원", "Ask the receptionist.", "접수원에게 물어보세요."),
    "dentist":     ("/ˈdɛntɪst/", "명사", "치과 의사", "I need to see a dentist.", "치과에 가야 합니다."),
    "identification":("/aɪˌdɛntɪfɪˈkeɪʃən/", "명사", "신분증, 확인", "Show your identification.", "신분증을 보여 주세요."),
    "coupon":      ("/ˈkuːpɒn/", "명사", "쿠폰, 할인권", "Use this coupon for 10% off.", "이 쿠폰을 사용하면 10% 할인됩니다."),
    "depart":      ("/dɪˈpɑːrt/", "동사", "출발하다, 떠나다", "The train will depart at noon.", "기차는 정오에 출발합니다."),
    "reschedule":  ("/ˌriːˈʃɛdjuːl/", "동사", "일정을 변경하다", "Can we reschedule?", "일정을 변경할 수 있나요?"),
    "renovation":  ("/ˌrɛnəˈveɪʃən/", "명사", "보수, 개조", "The renovation is complete.", "보수 공사가 완료되었습니다."),
    "upgrade":     ("/ˈʌpɡreɪd/", "명사", "업그레이드, 향상", "I'd like to upgrade my seat.", "좌석을 업그레이드하고 싶습니다."),
    "dine":        ("/daɪn/", "동사", "식사하다", "Let's dine out tonight.", "오늘 밤 외식합시다."),
    "passport":    ("/ˈpɑːspɔːrt/", "명사", "여권", "Don't forget your passport.", "여권을 잊지 마세요."),
    "coworker":    ("/ˈkoʊwɜːrkər/", "명사", "동료, 함께 일하는 사람", "My coworker is very helpful.", "제 동료는 매우 도움이 됩니다."),
    "upcoming":    ("/ˈʌpkʌmɪŋ/", "형용사", "다가오는, 곧 있을", "The upcoming event is exciting.", "다가오는 행사가 기대됩니다."),
    "appliance":   ("/əˈplaɪəns/", "명사", "가전제품, 기기", "The appliance is broken.", "가전제품이 고장났습니다."),
    "instructor":  ("/ɪnˈstrʌktər/", "명사", "강사, 교관", "The instructor was helpful.", "강사가 도움이 되었습니다."),
    "keyboard":    ("/ˈkiːbɔːrd/", "명사", "키보드", "This keyboard is comfortable.", "이 키보드는 편합니다."),
    "supermarket": ("/ˈsuːpərmɑːrkɪt/", "명사", "슈퍼마켓", "Let's go to the supermarket.", "슈퍼마켓에 가자."),
    "valid":       ("/ˈvælɪd/", "형용사", "유효한, 타당한", "Is your passport valid?", "여권이 유효한가요?"),
    "admission":   ("/ədˈmɪʃən/", "명사", "입장, 입학", "Admission is free.", "입장료가 무료입니다."),
    "laptop":      ("/ˈlæptɒp/", "명사", "노트북 컴퓨터", "I work on my laptop.", "노트북으로 일합니다."),
    "assignment":  ("/əˈsaɪnmənt/", "명사", "과제, 임무", "Submit your assignment.", "과제를 제출하세요."),
    "exit":        ("/ˈɛɡzɪt/", "명사", "출구, 비상구", "Use the emergency exit.", "비상구를 이용하세요."),
    "cruise":      ("/kruːz/", "명사", "크루즈 여행", "We went on a cruise.", "우리는 크루즈 여행을 갔습니다."),
    "mall":        ("/mɔːl/", "명사", "쇼핑몰", "Meet me at the mall.", "쇼핑몰에서 만나자."),
    "medication":  ("/ˌmɛdɪˈkeɪʃən/", "명사", "약, 의약품", "Take your medication.", "약을 드세요."),
    "recycle":     ("/ˌriːˈsaɪkəl/", "동사", "재활용하다", "Please recycle the paper.", "종이를 재활용해 주세요."),
    "renew":       ("/rɪˈnjuː/", "동사", "갱신하다, 새롭게 하다", "Renew your membership.", "멤버십을 갱신하세요."),
    "tenant":      ("/ˈtɛnənt/", "명사", "세입자, 임차인", "The tenant pays monthly.", "세입자는 매월 임차료를 냅니다."),
    "departure":   ("/dɪˈpɑːrtʃər/", "명사", "출발, 이탈", "Check the departure time.", "출발 시간을 확인하세요."),
    "fitness":     ("/ˈfɪtnɪs/", "명사", "건강, 체력", "Maintain your fitness.", "건강을 유지하세요."),
    "expire":      ("/ɪkˈspaɪər/", "동사", "만료되다, 기한이 끝나다", "When does it expire?", "언제 만료되나요?"),
    "calendar":    ("/ˈkælɪndər/", "명사", "달력, 일정", "Check your calendar.", "일정을 확인하세요."),
    "donation":    ("/doʊˈneɪʃən/", "명사", "기부, 기증", "Thank you for your donation.", "기부해 주셔서 감사합니다."),
    "feedback":    ("/ˈfiːdbæk/", "명사", "피드백, 의견", "Please give me feedback.", "피드백을 주세요."),
    "shortly":     ("/ˈʃɔːrtli/", "부사", "곧, 잠시 후", "I'll be there shortly.", "곧 거기 도착할 것입니다."),
    "snack":       ("/snæk/", "명사", "간식", "I need a snack.", "간식이 필요합니다."),
    "warehouse":   ("/ˈwɛəhaʊs/", "명사", "창고", "The warehouse is full.", "창고가 가득 찼습니다."),
    "beverage":    ("/ˈbɛvərɪdʒ/", "명사", "음료", "What beverage would you like?", "어떤 음료를 원하시나요?"),
    "aisle":       ("/aɪl/", "명사", "통로, 복도", "Please use the aisle.", "통로를 이용해 주세요."),
    "mechanic":    ("/mɪˈkænɪk/", "명사", "정비사, 기계공", "Call a mechanic.", "정비사를 부르세요."),
    "sweater":     ("/ˈswɛtər/", "명사", "스웨터", "Wear a sweater.", "스웨터를 입으세요."),
    "itinerary":   ("/aɪˈtɪnərəri/", "명사", "여행 일정", "Check the itinerary.", "여행 일정을 확인하세요."),
    "workplace":   ("/ˈwɜːrkpleɪs/", "명사", "직장, 일터", "A safe workplace is important.", "안전한 직장이 중요합니다."),
    "convenience": ("/kənˈviːniəns/", "명사", "편의, 편리함", "For your convenience...", "편의를 위해..."),
    "baggage":     ("/ˈbæɡɪdʒ/", "명사", "짐, 수하물", "Claim your baggage here.", "여기서 짐을 찾으세요."),
    "certificate": ("/səˈtɪfɪkɪt/", "명사", "증명서, 자격증", "Show your certificate.", "증명서를 보여 주세요."),
    "gym":         ("/dʒɪm/", "명사", "헬스장, 체육관", "I go to the gym every day.", "저는 매일 헬스장에 갑니다."),
    "highway":     ("/ˈhaɪweɪ/", "명사", "고속도로", "Take the highway.", "고속도로를 이용하세요."),
    "jewelry":     ("/ˈdʒuːəlri/", "명사", "보석, 귀금속", "She loves wearing jewelry.", "그녀는 보석 착용을 좋아합니다."),
    "overtime":    ("/ˈoʊvərtaɪm/", "명사", "초과 근무", "I worked overtime today.", "오늘 초과 근무를 했습니다."),
    "battery":     ("/ˈbætəri/", "명사", "배터리", "The battery is low.", "배터리가 부족합니다."),
    "outstanding": ("/ˌaʊtˈstændɪŋ/", "형용사", "뛰어난, 미지불된", "She did an outstanding job.", "그녀는 뛰어난 일을 했습니다."),
    "briefcase":   ("/ˈbriːfkeɪs/", "명사", "서류 가방", "He carries a briefcase.", "그는 서류 가방을 들고 다닙니다."),
    "dessert":     ("/dɪˈzɜːrt/", "명사", "디저트, 후식", "What's for dessert?", "디저트는 무엇인가요?"),
    "inquire":     ("/ɪnˈkwaɪər/", "동사", "문의하다", "Please inquire at the desk.", "안내 데스크에 문의해 주세요."),
    "overnight":   ("/ˌoʊvərˈnaɪt/", "형용사", "하룻밤의, 야간의", "Is there overnight parking?", "야간 주차가 있나요?"),
    "venue":       ("/ˈvɛnjuː/", "명사", "장소, 행사장", "The venue is downtown.", "행사장이 시내에 있습니다."),
    "commuter":    ("/kəˈmjuːtər/", "명사", "통근자", "She is a daily commuter.", "그녀는 매일 통근합니다."),
    "newsletter":  ("/ˈnjuːzlɛtər/", "명사", "뉴스레터", "Subscribe to our newsletter.", "뉴스레터를 구독하세요."),
    "advisor":     ("/ədˈvaɪzər/", "명사", "조언자, 고문", "Consult your advisor.", "고문에게 상담하세요."),
    "cloudy":      ("/ˈklaʊdi/", "형용사", "흐린, 구름 낀", "It's cloudy today.", "오늘 흐립니다."),
    "photographer":("/fəˈtɒɡrəfər/", "명사", "사진사, 포토그래퍼", "She is a professional photographer.", "그녀는 전문 사진사입니다."),
    "password":    ("/ˈpɑːswɜːrd/", "명사", "비밀번호", "Don't share your password.", "비밀번호를 공유하지 마세요."),
    "stadium":     ("/ˈsteɪdiəm/", "명사", "경기장, 스타디움", "The stadium holds 50,000 fans.", "경기장에는 5만 명의 팬이 들어갑니다."),
    "terminal":    ("/ˈtɜːrmɪnəl/", "명사", "터미널, 종착역", "Go to Terminal 2.", "터미널 2로 가세요."),
    "weekday":     ("/ˈwiːkdeɪ/", "명사", "평일", "The office is open on weekdays.", "사무실은 평일에 문을 엽니다."),
    "bonus":       ("/ˈboʊnəs/", "명사", "보너스, 추가 지급", "She received a bonus.", "그녀는 보너스를 받았습니다."),
    "download":    ("/ˈdaʊnloʊd/", "동사", "다운로드하다", "Download the app.", "앱을 다운로드하세요."),
    "waitress":    ("/ˈweɪtrɪs/", "명사", "여종업원", "Ask the waitress.", "여종업원에게 물어보세요."),
    "shuttle":     ("/ˈʃʌtəl/", "명사", "셔틀버스", "Take the shuttle bus.", "셔틀버스를 타세요."),
    "stationery":  ("/ˈsteɪʃənəri/", "명사", "문구류, 편지지", "Buy some stationery.", "문구류를 사세요."),
    "subscribe":   ("/səbˈskraɪb/", "동사", "구독하다", "Subscribe to the channel.", "채널을 구독하세요."),
    "flavor":      ("/ˈfleɪvər/", "명사", "맛, 향", "What flavor do you like?", "어떤 맛을 좋아하나요?"),
    "picnic":      ("/ˈpɪknɪk/", "명사", "소풍, 피크닉", "Let's have a picnic.", "소풍을 가자."),
    "recipe":      ("/ˈrɛsɪpi/", "명사", "레시피, 요리법", "Share the recipe.", "레시피를 공유해 주세요."),
    "refreshment": ("/rɪˈfrɛʃmənt/", "명사", "다과, 음료", "Refreshments will be served.", "다과가 제공될 것입니다."),
    "paperwork":   ("/ˈpeɪpərwɜːrk/", "명사", "서류 작업", "There's a lot of paperwork.", "서류 작업이 많습니다."),
    "installation":("/ˌɪnstəˈleɪʃən/", "명사", "설치", "Installation is free.", "설치는 무료입니다."),
    "bargain":     ("/ˈbɑːrɡɪn/", "명사", "좋은 거래, 할인 상품", "That's a bargain!", "저렴한 가격이네요!"),
    "commute":     ("/kəˈmjuːt/", "동사", "통근하다", "I commute by subway.", "지하철로 통근합니다."),
    "coordinate":  ("/koʊˈɔːrdɪneɪt/", "동사", "조율하다, 조정하다", "Let's coordinate our schedules.", "일정을 조율합시다."),
    "productivity":("/ˌprɒdʌkˈtɪvɪti/", "명사", "생산성", "Increase your productivity.", "생산성을 높이세요."),
    "relocate":    ("/ˌriːloʊˈkeɪt/", "동사", "이전하다, 이사하다", "The company will relocate.", "회사가 이전할 것입니다."),
    "trainee":     ("/treɪˈniː/", "명사", "훈련생, 연수생", "She is a new trainee.", "그녀는 새 연수생입니다."),
    "verify":      ("/ˈvɛrɪfaɪ/", "동사", "확인하다, 검증하다", "Please verify your identity.", "신원을 확인해 주세요."),
    "automobile":  ("/ˈɔːtəmoʊbiːl/", "명사", "자동차", "The automobile industry is large.", "자동차 산업은 규모가 큽니다."),
    "questionnaire":("/ˌkwɛstʃəˈnɛər/", "명사", "설문지", "Fill in the questionnaire.", "설문지를 작성해 주세요."),
    "lately":      ("/ˈleɪtli/", "부사", "최근에, 요즘", "I've been busy lately.", "요즘 바빴습니다."),
    "machinery":   ("/məˈʃiːnəri/", "명사", "기계류", "The machinery needs repair.", "기계류가 수리가 필요합니다."),
    "presenter":   ("/prɪˈzɛntər/", "명사", "발표자, 진행자", "The presenter was excellent.", "발표자가 훌륭했습니다."),
    "donate":      ("/doʊˈneɪt/", "동사", "기부하다", "Please donate to the cause.", "이 사업에 기부해 주세요."),
    "audit":       ("/ˈɔːdɪt/", "명사", "감사, 회계 감사", "The audit was successful.", "감사가 성공적으로 이루어졌습니다."),
    "contractor":  ("/ˈkɒntræktər/", "명사", "계약자, 도급업자", "Hire a reliable contractor.", "믿을 수 있는 계약자를 고용하세요."),
    "prohibit":    ("/prəˈhɪbɪt/", "동사", "금지하다", "Smoking is prohibited here.", "여기서는 흡연이 금지됩니다."),
    "supervise":   ("/ˈsuːpərvaɪz/", "동사", "감독하다", "She supervises the team.", "그녀는 팀을 감독합니다."),
    "accommodate": ("/əˈkɒmədeɪt/", "동사", "수용하다, 편의를 봐주다", "Can you accommodate us?", "저희를 수용할 수 있나요?"),
    "affordable":  ("/əˈfɔːrdəbəl/", "형용사", "저렴한, 부담 없는", "The price is affordable.", "가격이 저렴합니다."),
    "annoy":       ("/əˈnɔɪ/", "동사", "짜증나게 하다", "The noise is annoying.", "소음이 짜증납니다."),
    "quit":        ("/kwɪt/", "동사", "그만두다, 포기하다", "Don't quit.", "포기하지 마세요."),
    "captain":     ("/ˈkæptɪn/", "명사", "선장, 기장, 주장", "The captain gave orders.", "선장이 명령을 내렸습니다."),
    "availability":("/əˌveɪləˈbɪlɪti/", "명사", "가용성, 이용 가능 여부", "Check the availability.", "이용 가능 여부를 확인하세요."),
    "hike":        ("/haɪk/", "동사", "하이킹하다, 걷다", "Let's go for a hike.", "하이킹하러 가자."),
    "midnight":    ("/ˈmɪdnaɪt/", "명사", "자정, 한밤중", "The party ends at midnight.", "파티는 자정에 끝납니다."),
    "rainy":       ("/ˈreɪni/", "형용사", "비가 오는, 우기의", "It's a rainy day.", "비가 오는 날입니다."),
    "unhappy":     ("/ʌnˈhæpi/", "형용사", "불행한, 불만족스러운", "She is unhappy with the result.", "그녀는 결과에 불만족합니다."),
    "courier":     ("/ˈkʊriər/", "명사", "택배 서비스, 전달자", "Send it by courier.", "택배로 보내세요."),
    "dock":        ("/dɒk/", "명사", "부두, 도크", "The ship is at the dock.", "배가 부두에 있습니다."),
    "lamp":        ("/læmp/", "명사", "램프, 전등", "Turn on the lamp.", "램프를 켜세요."),
    # =========================================================
    # freq-L6 top fallback words
    # =========================================================
    "tonight":     ("/təˈnaɪt/", "부사", "오늘 밤", "Are you free tonight?", "오늘 밤 시간 있나요?"),
    "fashion":     ("/ˈfæʃən/", "명사", "패션, 유행", "She's interested in fashion.", "그녀는 패션에 관심이 있습니다."),
    "danger":      ("/ˈdeɪndʒər/", "명사", "위험", "There is danger ahead.", "앞에 위험이 있습니다."),
    "army":        ("/ˈɑːrmi/", "명사", "군대", "He served in the army.", "그는 군대에서 복무했습니다."),
    "dangerous":   ("/ˈdeɪndʒərəs/", "형용사", "위험한", "This road is dangerous.", "이 도로는 위험합니다."),
    "decrease":    ("/dɪˈkriːs/", "동사", "감소하다, 줄다", "Sales decreased last month.", "지난달 매출이 감소했습니다."),
    "hurt":        ("/hɜːrt/", "동사", "상처를 입히다, 아프다", "My knee hurts.", "무릎이 아픕니다."),
    "editor":      ("/ˈɛdɪtər/", "명사", "편집자", "The editor reviewed the article.", "편집자가 기사를 검토했습니다."),
    "normally":    ("/ˈnɔːrməli/", "부사", "일반적으로, 보통", "Normally, I wake up at 7.", "보통 7시에 일어납니다."),
    "sight":       ("/saɪt/", "명사", "시야, 관광지", "It's a beautiful sight.", "아름다운 광경입니다."),
    "generate":    ("/ˈdʒɛnəreɪt/", "동사", "발생시키다, 만들다", "Generate new ideas.", "새로운 아이디어를 만들어 내세요."),
    "gift":        ("/ɡɪft/", "명사", "선물, 재능", "Thank you for the gift.", "선물 감사합니다."),
    "deny":        ("/dɪˈnaɪ/", "동사", "부정하다, 거절하다", "She denied the accusation.", "그녀는 혐의를 부정했습니다."),
    "guest":       ("/ɡɛst/", "명사", "손님, 게스트", "Welcome our guests.", "손님들을 환영합니다."),
    "quote":       ("/kwoʊt/", "명사", "인용문, 견적", "Give me a quote.", "견적을 주세요."),
    "climb":       ("/klaɪm/", "동사", "오르다, 등반하다", "We climbed the mountain.", "우리는 산을 올랐습니다."),
    "violence":    ("/ˈvaɪələns/", "명사", "폭력", "Violence is never the answer.", "폭력은 절대 답이 아닙니다."),
    "minister":    ("/ˈmɪnɪstər/", "명사", "장관, 목사", "The minister gave a speech.", "장관이 연설을 했습니다."),
    "mainly":      ("/ˈmeɪnli/", "부사", "주로, 대체로", "I mainly work from home.", "저는 주로 재택근무를 합니다."),
    "mouth":       ("/maʊθ/", "명사", "입", "Open your mouth.", "입을 여세요."),
    "noise":       ("/nɔɪz/", "명사", "소음, 잡음", "Please reduce the noise.", "소음을 줄여 주세요."),
    "manner":      ("/ˈmænər/", "명사", "방식, 태도", "Act in a professional manner.", "전문적인 태도로 행동하세요."),
    "gun":         ("/ɡʌn/", "명사", "총, 권총", "The police officer had a gun.", "경찰관은 총을 가지고 있었습니다."),
    "square":      ("/skwɛər/", "명사", "광장, 정사각형", "Meet me at the town square.", "마을 광장에서 만나자."),
    "occasion":    ("/əˈkeɪʒən/", "명사", "경우, 행사", "On this special occasion.", "이 특별한 경우에."),
    "familiar":    ("/fəˈmɪliər/", "형용사", "친숙한, 잘 아는", "This looks familiar.", "이것이 익숙해 보입니다."),
    "ignore":      ("/ɪɡˈnɔːr/", "동사", "무시하다", "Don't ignore the warning.", "경고를 무시하지 마세요."),
    "destroy":     ("/dɪˈstrɔɪ/", "동사", "파괴하다", "Don't destroy the environment.", "환경을 파괴하지 마세요."),
    "affair":      ("/əˈfɛər/", "명사", "일, 사건", "It's a private affair.", "그것은 사적인 일입니다."),
    "civil":       ("/ˈsɪvəl/", "형용사", "시민의, 문명의", "We need civil dialogue.", "시민적 대화가 필요합니다."),
    "locate":      ("/loʊˈkeɪt/", "동사", "찾다, 위치를 정하다", "Can you locate the file?", "파일을 찾을 수 있나요?"),
    "temperature": ("/ˈtɛmprɪtʃər/", "명사", "온도, 기온", "What is the temperature?", "기온이 어떻게 되나요?"),
    "gold":        ("/ɡoʊld/", "명사", "금, 황금", "Gold is valuable.", "금은 귀중합니다."),
    "domestic":    ("/dəˈmɛstɪk/", "형용사", "국내의, 가정의", "It's a domestic flight.", "국내선 비행입니다."),
    "load":        ("/loʊd/", "명사", "짐, 부하", "The load is too heavy.", "짐이 너무 무겁습니다."),
    "troop":       ("/truːp/", "명사", "군대, 병력", "Troops were deployed.", "부대가 배치되었습니다."),
    "technical":   ("/ˈtɛknɪkəl/", "형용사", "기술적인", "This is a technical issue.", "이것은 기술적인 문제입니다."),
    "remind":      ("/rɪˈmaɪnd/", "동사", "상기시키다", "Remind me of the meeting.", "회의를 상기시켜 주세요."),
    "arrangement": ("/əˈreɪndʒmənt/", "명사", "배열, 준비", "Make arrangements.", "준비하세요."),
    "skin":        ("/skɪn/", "명사", "피부, 껍질", "Take care of your skin.", "피부를 관리하세요."),
    "prison":      ("/ˈprɪzən/", "명사", "감옥, 교도소", "He went to prison.", "그는 감옥에 갔습니다."),
    "acquire":     ("/əˈkwaɪər/", "동사", "얻다, 취득하다", "Acquire new skills.", "새로운 기술을 습득하세요."),
    "fairly":      ("/ˈfɛərli/", "부사", "꽤, 공평하게", "This is fairly easy.", "이것은 꽤 쉽습니다."),
    "wood":        ("/wʊd/", "명사", "나무, 목재", "The table is made of wood.", "테이블은 목재로 만들어졌습니다."),
    "participate": ("/pɑːrˈtɪsɪpeɪt/", "동사", "참여하다, 참가하다", "Everyone should participate.", "모든 사람이 참여해야 합니다."),
    "tough":       ("/tʌf/", "형용사", "힘든, 거친", "It's a tough decision.", "힘든 결정입니다."),
    "representative":("/ˌrɛprɪˈzɛntətɪv/", "명사", "대표자", "Meet our representative.", "저희 대표자를 만나세요."),
    "capacity":    ("/kəˈpæsɪti/", "명사", "용량, 능력", "The room has a capacity of 50.", "방 수용 인원은 50명입니다."),
    "border":      ("/ˈbɔːrdər/", "명사", "국경, 경계", "Cross the border.", "국경을 넘으세요."),
    "assessment":  ("/əˈsɛsmənt/", "명사", "평가, 사정", "Complete the assessment.", "평가를 완료하세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT4:
                    pron, pos, meaning, ex_en, ex_ko = DICT4[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more3.py ===\n")
    patch_files()
