#!/usr/bin/env python3
"""Fill travel-english word data (pronunciation, meaning, examples)."""
import json, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, "src", "data", "travel-english")

WORDS = {
# ── airport ──────────────────────────────────────────────────────────────
"airport": ("/ˈɛərpɔːrt/","명사","공항","I arrived at the airport two hours before departure.","나는 출발 2시간 전에 공항에 도착했다."),
"flight": ("/flaɪt/","명사","항공편","My flight to London departs at 7 a.m.","런던행 내 항공편은 오전 7시에 출발한다."),
"boarding pass": ("/ˈbɔːrdɪŋ pæs/","명사","탑승권","Please have your boarding pass ready at the gate.","탑승구에서 탑승권을 준비해 주세요."),
"gate": ("/ɡeɪt/","명사","탑승구","The flight to Paris departs from gate 12.","파리행 항공편은 12번 탑승구에서 출발합니다."),
"terminal": ("/ˈtɜːrmɪnəl/","명사","터미널","Which terminal does my airline use?","제 항공사는 어느 터미널을 사용하나요?"),
"departure": ("/dɪˈpɑːrtʃər/","명사","출발","The departure time has been moved up by one hour.","출발 시간이 한 시간 앞당겨졌다."),
"arrival": ("/əˈraɪvəl/","명사","도착","Check the arrivals board for updates.","도착 안내판에서 업데이트를 확인하세요."),
"check-in": ("/ˈtʃɛk ɪn/","명사","체크인, 탑승 수속","Online check-in is available 24 hours before the flight.","온라인 체크인은 항공편 24시간 전부터 가능합니다."),
"baggage": ("/ˈbæɡɪdʒ/","명사","수하물","Your baggage allowance is 23 kilograms.","수하물 허용 무게는 23킬로그램입니다."),
"luggage": ("/ˈlʌɡɪdʒ/","명사","짐, 수하물","I need to claim my luggage at belt three.","3번 벨트에서 짐을 찾아야 해요."),
"carry-on": ("/ˈkæri ɒn/","명사","기내 반입 수하물","The carry-on bag must fit in the overhead bin.","기내 반입 가방은 머리 위 짐칸에 들어가야 합니다."),
"overhead bin": ("/ˈoʊvərˌhɛd bɪn/","명사","머리 위 짐칸","Please stow your bag in the overhead bin.","가방을 머리 위 짐칸에 넣어 주세요."),
"seat belt": ("/ˈsiːt bɛlt/","명사","안전벨트","Please fasten your seat belt during takeoff.","이륙 중에는 안전벨트를 착용해 주세요."),
"aisle": ("/aɪl/","명사","통로, 복도 좌석","I prefer an aisle seat so I can stretch my legs.","저는 다리를 뻗을 수 있는 복도 좌석을 선호해요."),
"window seat": ("/ˈwɪndoʊ siːt/","명사","창가 좌석","She always books a window seat for the view.","그녀는 경치를 보기 위해 항상 창가 좌석을 예약한다."),
"passport": ("/ˈpæspɔːrt/","명사","여권","Make sure your passport is valid for at least six months.","여권의 유효기간이 최소 6개월 이상인지 확인하세요."),
"visa": ("/ˈviːzə/","명사","비자","Do I need a visa to enter this country?","이 나라에 입국하려면 비자가 필요한가요?"),
"customs": ("/ˈkʌstəmz/","명사","세관","You must declare all goods at customs.","세관에서 모든 물품을 신고해야 합니다."),
"immigration": ("/ˌɪmɪˈɡreɪʃən/","명사","출입국 심사","The immigration queue was very long today.","오늘 출입국 심사 줄이 매우 길었다."),
"declaration": ("/ˌdɛkləˈreɪʃən/","명사","세관 신고","Fill out the customs declaration form on the plane.","비행기에서 세관 신고서를 작성하세요."),
"duty-free": ("/ˌdjuːti ˈfriː/","형용사","면세의","I bought some perfume at the duty-free shop.","나는 면세점에서 향수를 샀다."),
"transit": ("/ˈtrænzɪt/","명사","경유","Passengers in transit do not need to clear customs.","경유 승객은 세관을 통과할 필요가 없습니다."),
"layover": ("/ˈleɪˌoʊvər/","명사","경유 대기 시간","We have a four-hour layover in Dubai.","우리는 두바이에서 4시간 경유 대기가 있다."),
"connecting flight": ("/kəˈnɛktɪŋ flaɪt/","명사","연결 항공편","I missed my connecting flight because of the delay.","지연으로 인해 연결 항공편을 놓쳤다."),
"delay": ("/dɪˈleɪ/","명사","지연, 연착","The flight was delayed by two hours due to weather.","항공편이 날씨로 인해 두 시간 지연되었다."),
"cancel": ("/ˈkænsəl/","동사","취소하다","The airline cancelled the flight due to a storm.","항공사가 폭풍으로 인해 항공편을 취소했다."),
"boarding": ("/ˈbɔːrdɪŋ/","명사","탑승","Boarding begins 45 minutes before departure.","탑승은 출발 45분 전에 시작됩니다."),
"takeoff": ("/ˈteɪkˌɔːf/","명사","이륙","The pilot announced takeoff would be in ten minutes.","기장이 10분 후 이륙한다고 발표했다."),
"landing": ("/ˈlændɪŋ/","명사","착륙","The landing was smooth despite the turbulence.","난기류에도 불구하고 착륙은 부드러웠다."),
"turbulence": ("/ˈtɜːrbjʊləns/","명사","난기류","Please remain seated during turbulence.","난기류 동안에는 자리에 앉아 계세요."),
"pilot": ("/ˈpaɪlət/","명사","조종사","The pilot welcomed us aboard the aircraft.","기장이 항공기에 탑승한 우리를 환영했다."),
"flight attendant": ("/flaɪt əˈtɛndənt/","명사","승무원","The flight attendant showed us the safety procedures.","승무원이 안전 절차를 보여주었다."),
"announcement": ("/əˈnaʊnsmənt/","명사","안내 방송","There was an announcement about the gate change.","탑승구 변경에 대한 안내 방송이 있었다."),
"security check": ("/sɪˈkjʊərɪti tʃɛk/","명사","보안 검색","All passengers must pass through the security check.","모든 승객은 보안 검색을 통과해야 합니다."),
"metal detector": ("/ˈmɛtəl dɪˈtɛktər/","명사","금속 탐지기","Remove your belt before going through the metal detector.","금속 탐지기를 통과하기 전에 벨트를 제거하세요."),
"scanner": ("/ˈskænər/","명사","스캐너, 검색 장치","Put your laptop in the scanner tray separately.","노트북은 스캐너 트레이에 따로 넣으세요."),
"prohibited": ("/prəˈhɪbɪtɪd/","형용사","금지된","Sharp objects are prohibited in carry-on bags.","날카로운 물체는 기내 반입 가방에 금지되어 있습니다."),
"liquid": ("/ˈlɪkwɪd/","명사","액체","Liquids over 100ml are not allowed in carry-on luggage.","100ml 초과 액체는 기내 반입이 허용되지 않습니다."),
"restriction": ("/rɪˈstrɪkʃən/","명사","제한, 규제","There are weight restrictions on checked baggage.","위탁 수하물에는 무게 제한이 있습니다."),
"baggage claim": ("/ˈbæɡɪdʒ kleɪm/","명사","수하물 찾는 곳","Head to baggage claim on level one.","1층 수하물 찾는 곳으로 가세요."),
"conveyor belt": ("/kənˈveɪər bɛlt/","명사","컨베이어 벨트","Your suitcase will come out on conveyor belt number three.","여러분의 여행 가방은 3번 컨베이어 벨트로 나올 것입니다."),
"lost luggage": ("/lɒst ˈlʌɡɪdʒ/","명사","분실 수하물","I need to report lost luggage to the airline desk.","항공사 데스크에 분실 수하물을 신고해야 합니다."),
"airline": ("/ˈɛərˌlaɪn/","명사","항공사","Which airline are you flying with?","어느 항공사를 이용하시나요?"),
"ticket": ("/ˈtɪkɪt/","명사","항공권, 티켓","I booked my ticket online three months ago.","3개월 전에 온라인으로 항공권을 예매했다."),
"round trip": ("/ˈraʊnd trɪp/","명사","왕복 여행","A round trip ticket is often cheaper than two one-ways.","왕복 항공권이 편도 두 장보다 저렴한 경우가 많다."),
"one-way": ("/ˈwʌnˌweɪ/","형용사","편도의","I bought a one-way ticket because my return date is uncertain.","귀국일이 불확실해서 편도 항공권을 샀다."),
"economy class": ("/ɪˈkɒnəmi klɑːs/","명사","이코노미석","Economy class seats are more affordable but less comfortable.","이코노미석은 더 저렴하지만 덜 편안하다."),
"business class": ("/ˈbɪznɪs klɑːs/","명사","비즈니스석","Business class comes with wider seats and better meals.","비즈니스석에는 더 넓은 좌석과 더 나은 식사가 제공된다."),
"first class": ("/fɜːrst klɑːs/","명사","퍼스트 클래스","First class passengers board before everyone else.","퍼스트 클래스 승객은 다른 모든 승객보다 먼저 탑승한다."),
"upgrade": ("/ˈʌpɡreɪd/","동사","업그레이드하다","I was lucky to get a free upgrade to business class.","운 좋게 비즈니스석으로 무료 업그레이드를 받았다."),
"reservation": ("/ˌrɛzərˈveɪʃən/","명사","예약","I made a reservation for two seats in economy.","이코노미석 두 자리를 예약했다."),
"confirm": ("/kənˈfɜːrm/","동사","확인하다","Please confirm your booking at least 24 hours before departure.","출발 24시간 전까지 예약을 확인해 주세요."),
"itinerary": ("/aɪˈtɪnəreri/","명사","여행 일정표","My travel itinerary includes stops in three countries.","내 여행 일정표에는 세 나라 경유가 포함되어 있다."),
"travel agency": ("/ˈtrævəl ˈeɪdʒənsi/","명사","여행사","The travel agency arranged everything for our trip.","여행사가 우리 여행의 모든 것을 준비해 주었다."),
"bus": ("/bʌs/","명사","버스","Take the airport bus to the city center.","시내 중심으로 가는 공항 버스를 타세요."),
"taxi": ("/ˈtæksi/","명사","택시","A taxi from the airport to downtown costs about 30 dollars.","공항에서 시내까지 택시 요금은 약 30달러입니다."),
"subway": ("/ˈsʌbˌweɪ/","명사","지하철","The subway is the fastest way to get to the airport.","지하철이 공항에 가는 가장 빠른 방법이다."),
"train": ("/treɪn/","명사","기차","The express train to the airport runs every 15 minutes.","공항행 급행열차는 15분마다 운행된다."),
"platform": ("/ˈplætfɔːrm/","명사","플랫폼, 승강장","The train to downtown leaves from platform 4.","시내행 열차는 4번 플랫폼에서 출발한다."),
"station": ("/ˈsteɪʃən/","명사","역","Is there a train station near the airport?","공항 근처에 기차역이 있나요?"),
"fare": ("/fɛər/","명사","요금","What is the bus fare to the city center?","시내 중심까지 버스 요금이 얼마인가요?"),
"transfer": ("/ˈtrænsfɜːr/","명사","환승","You need to transfer at the central station.","중앙역에서 환승해야 합니다."),
"route": ("/ruːt/","명사","노선, 경로","Which bus route goes to the hotel district?","호텔 지구로 가는 버스 노선이 어떻게 되나요?"),
"schedule": ("/ˈskɛdʒuːl/","명사","시간표, 일정","Check the train schedule on the board.","안내판에서 기차 시간표를 확인하세요."),
"timetable": ("/ˈtaɪmˌteɪbəl/","명사","시간표","Download the timetable app for real-time updates.","실시간 업데이트를 위해 시간표 앱을 다운로드하세요."),
"express": ("/ɪkˈsprɛs/","형용사","급행의","The express train takes only 30 minutes.","급행열차는 30분밖에 걸리지 않는다."),
"local train": ("/ˈloʊkəl treɪn/","명사","완행열차","The local train stops at every station.","완행열차는 모든 역에 정차한다."),
"stop": ("/stɒp/","명사","정류장","Get off at the third stop from here.","여기서 세 번째 정류장에서 내리세요."),
"destination": ("/ˌdɛstɪˈneɪʃən/","명사","목적지","What is your final destination?","최종 목적지가 어디인가요?"),
"map": ("/mæp/","명사","지도","Can I get a map of the city at the information desk?","안내 데스크에서 도시 지도를 받을 수 있나요?"),
"direction": ("/dɪˈrɛkʃən/","명사","방향, 길 안내","Could you give me directions to the nearest hotel?","가장 가까운 호텔로 가는 길을 알려주실 수 있나요?"),
"traffic": ("/ˈtræfɪk/","명사","교통 (체증)","Heavy traffic made us late for the flight.","심한 교통 체증으로 항공편에 늦었다."),
"rush hour": ("/ˈrʌʃ ˌaʊər/","명사","러시아워, 출퇴근 시간","Avoid the subway during rush hour if possible.","가능하면 출퇴근 시간에는 지하철을 피하세요."),
"parking": ("/ˈpɑːrkɪŋ/","명사","주차","Long-term parking at the airport is expensive.","공항 장기 주차는 비싸다."),
"rental car": ("/ˈrɛntəl kɑːr/","명사","렌터카","I picked up a rental car at the airport.","공항에서 렌터카를 받았다."),
"driver": ("/ˈdraɪvər/","명사","운전기사, 운전자","The driver will hold a sign with your name.","기사가 당신의 이름이 적힌 표지판을 들고 있을 것입니다."),
"highway": ("/ˈhaɪˌweɪ/","명사","고속도로","Take the highway for the fastest route to the airport.","공항까지 가장 빠른 경로로 고속도로를 이용하세요."),
"toll": ("/toʊl/","명사","통행료","Do you have cash for the highway toll?","고속도로 통행료를 낼 현금이 있나요?"),
"gas station": ("/ɡæs ˈsteɪʃən/","명사","주유소","Fill up the rental car at a gas station before returning it.","반납 전에 주유소에서 렌터카를 주유하세요."),
"fuel": ("/fjuːəl/","명사","연료","The fuel gauge is nearly empty.","연료 게이지가 거의 비어 있다."),
"accident": ("/ˈæksɪdənt/","명사","사고","There was an accident on the highway, causing delays.","고속도로에서 사고가 있어 지연이 발생했다."),
"speed limit": ("/ˈspiːd ˌlɪmɪt/","명사","제한 속도","The speed limit on this road is 60 km/h.","이 도로의 제한 속도는 시속 60킬로미터입니다."),
"intersection": ("/ˌɪntərˈsɛkʃən/","명사","교차로","Turn left at the next intersection.","다음 교차로에서 좌회전하세요."),
"crosswalk": ("/ˈkrɔːsˌwɔːk/","명사","횡단보도","Always use the crosswalk to cross the street safely.","안전하게 길을 건너려면 항상 횡단보도를 이용하세요."),
"sidewalk": ("/ˈsaɪdˌwɔːk/","명사","인도, 보도","Keep to the sidewalk when walking near traffic.","차량 통행 근처에서는 인도를 따라 걷세요."),
"bridge": ("/brɪdʒ/","명사","다리","Cross the bridge and turn right.","다리를 건너 오른쪽으로 돌아세요."),
"tunnel": ("/ˈtʌnəl/","명사","터널","The road goes through a long tunnel under the mountain.","도로는 산 아래 긴 터널을 통과한다."),
"ferry": ("/ˈfɛri/","명사","여객선, 페리","We took the ferry to the island.","우리는 페리를 타고 섬으로 갔다."),
"harbor": ("/ˈhɑːrbər/","명사","항구","The cruise ship is docked at the harbor.","크루즈선이 항구에 정박해 있다."),
"cruise": ("/kruːz/","명사","크루즈 여행","We booked a seven-day cruise in the Mediterranean.","우리는 지중해 7일 크루즈를 예약했다."),
"bicycle": ("/ˈbaɪsɪkəl/","명사","자전거","You can rent a bicycle to explore the city.","자전거를 빌려 도시를 탐방할 수 있습니다."),
"scooter": ("/ˈskuːtər/","명사","스쿠터","Renting a scooter is a popular way to see the island.","스쿠터 대여는 섬을 구경하는 인기 있는 방법이다."),
"helmet": ("/ˈhɛlmɪt/","명사","헬멧","Wearing a helmet is required by law here.","이곳에서는 헬멧 착용이 법으로 규정되어 있다."),
"navigation": ("/ˌnævɪˈɡeɪʃən/","명사","내비게이션, 길 안내","Turn on navigation before driving in an unfamiliar city.","낯선 도시에서 운전하기 전에 내비게이션을 켜세요."),
"GPS": ("/ˌdʒiː piː ˈɛs/","명사","GPS, 위성항법장치","The GPS told me to take the next exit.","GPS가 다음 출구를 이용하라고 했다."),
"detour": ("/ˈdiːtʊər/","명사","우회로","The road is closed; follow the detour signs.","도로가 폐쇄되었으니 우회 표지판을 따라가세요."),
"pedestrian": ("/pəˈdɛstriən/","명사","보행자","This street is pedestrian-only on weekends.","이 거리는 주말에는 보행자 전용입니다."),
"departure lounge": ("/dɪˈpɑːrtʃər laʊndʒ/","명사","출국 라운지","Relax in the departure lounge until your gate is announced.","탑승구가 발표될 때까지 출국 라운지에서 쉬세요."),
"arrival hall": ("/əˈraɪvəl hɔːl/","명사","도착 홀","Meet me in the arrival hall after you clear customs.","세관을 통과한 후 도착 홀에서 만납시다."),
"check-out": ("/ˈtʃɛk ˌaʊt/","명사","체크아웃, 수속 완료","Check-out closes 30 minutes before the flight.","탑승 수속은 항공편 30분 전에 마감된다."),
"trolley": ("/ˈtrɒli/","명사","짐 카트","Use a trolley to carry your heavy bags through the airport.","무거운 짐을 공항 안에서 옮길 때 카트를 이용하세요."),
"porter": ("/ˈpɔːrtər/","명사","짐꾼, 포터","The porter helped us carry our luggage to the taxi.","포터가 택시까지 짐을 옮기는 것을 도와주었다."),
"e-ticket": ("/ˈiː ˌtɪkɪt/","명사","전자 항공권","Show your e-ticket on your phone at the check-in counter.","체크인 카운터에서 휴대폰의 전자 항공권을 보여주세요."),
"mobile boarding": ("/ˈmoʊbəl ˈbɔːrdɪŋ/","명사","모바일 탑승","Mobile boarding passes are accepted at all gates.","모바일 탑승권은 모든 탑승구에서 허용됩니다."),

# ── hotel ─────────────────────────────────────────────────────────────────
"hotel": ("/hoʊˈtɛl/","명사","호텔","The hotel is located right in the city center.","호텔은 도심 바로 한가운데 위치해 있다."),
"check-in": ("/ˈtʃɛk ɪn/","동사","체크인하다","Check-in time is from 3 p.m.","체크인 시간은 오후 3시부터입니다."),
"check-out": ("/ˈtʃɛk ˌaʊt/","동사","체크아웃하다","Please check out by 11 a.m.","오전 11시까지 체크아웃해 주세요."),
"front desk": ("/frʌnt dɛsk/","명사","프런트 데스크","Ask the front desk for an extra pillow.","프런트 데스크에 베개를 하나 더 요청하세요."),
"lobby": ("/ˈlɒbi/","명사","로비","We agreed to meet in the hotel lobby at noon.","우리는 정오에 호텔 로비에서 만나기로 했다."),
"room key": ("/ruːm kiː/","명사","객실 키","I left my room key inside the room.","객실 키를 방 안에 두고 나왔다."),
"key card": ("/ˈkiː kɑːrd/","명사","키 카드","Tap your key card on the reader to unlock the door.","문을 열려면 리더기에 키 카드를 대세요."),
"single room": ("/ˈsɪŋɡəl ruːm/","명사","싱글룸","I booked a single room for one night.","하룻밤 싱글룸을 예약했다."),
"double room": ("/ˈdʌbəl ruːm/","명사","더블룸","The double room has a king-size bed.","더블룸에는 킹사이즈 침대가 있다."),
"suite": ("/swiːt/","명사","스위트룸","They stayed in a suite with a sea view.","그들은 바다 전망 스위트룸에 묵었다."),
"twin room": ("/twɪn ruːm/","명사","트윈룸","Can I book a twin room for two adults?","성인 두 명을 위한 트윈룸을 예약할 수 있나요?"),
"bed": ("/bɛd/","명사","침대","The bed was extremely comfortable.","침대가 매우 편안했다."),
"pillow": ("/ˈpɪloʊ/","명사","베개","Could I get an extra pillow, please?","베개를 하나 더 주실 수 있나요?"),
"blanket": ("/ˈblæŋkɪt/","명사","담요","It was cold, so I asked for an extra blanket.","추웠기 때문에 담요를 하나 더 요청했다."),
"mattress": ("/ˈmætrɪs/","명사","매트리스","The mattress in this room is very firm.","이 객실의 매트리스는 매우 단단하다."),
"sheet": ("/ʃiːt/","명사","시트","Please change the bed sheets.","침대 시트를 교체해 주세요."),
"towel": ("/ˈtaʊəl/","명사","수건","There are fresh towels in the bathroom.","욕실에 신선한 수건이 있습니다."),
"bathrobe": ("/ˈbæθroʊb/","명사","목욕 가운","The hotel provided a comfortable bathrobe.","호텔에서 편안한 목욕 가운을 제공했다."),
"slippers": ("/ˈslɪpərz/","명사","슬리퍼","There is a pair of slippers under the bed.","침대 아래에 슬리퍼 한 켤레가 있다."),
"mini bar": ("/ˈmɪni bɑːr/","명사","미니바","Drinks from the mini bar will be charged to your room.","미니바의 음료는 객실 요금에 추가됩니다."),
"room service": ("/ruːm ˈsɜːrvɪs/","명사","룸서비스","I ordered room service because I was too tired to go out.","너무 피곤해서 외출하지 않고 룸서비스를 주문했다."),
"wake-up call": ("/ˈweɪk ʌp kɔːl/","명사","모닝콜","Can you arrange a wake-up call for 6 a.m., please?","오전 6시에 모닝콜을 요청할 수 있을까요?"),
"do not disturb": ("/duː nɒt dɪˈstɜːrb/","명사","방해 금지","Hang the do-not-disturb sign on the door handle.","문 손잡이에 방해 금지 표지를 걸어 두세요."),
"housekeeping": ("/ˈhaʊsˌkiːpɪŋ/","명사","객실 청소 서비스","Housekeeping will clean your room every morning.","객실 청소 서비스가 매일 아침 방을 청소할 것입니다."),
"laundry": ("/ˈlɔːndri/","명사","세탁 서비스","The hotel offers same-day laundry service.","호텔은 당일 세탁 서비스를 제공합니다."),
"dry cleaning": ("/ˌdraɪ ˈkliːnɪŋ/","명사","드라이클리닝","Is there a dry-cleaning service available?","드라이클리닝 서비스가 가능한가요?"),
"iron": ("/ˈaɪərn/","명사","다리미","There is an iron in the wardrobe.","옷장 안에 다리미가 있습니다."),
"hanger": ("/ˈhæŋər/","명사","옷걸이","Use the hangers in the closet for your clothes.","옷장의 옷걸이를 이용해 옷을 걸어 두세요."),
"wardrobe": ("/ˈwɔːrdroʊb/","명사","옷장","You can store your luggage in the wardrobe.","옷장에 짐을 보관할 수 있습니다."),
"air conditioning": ("/ɛr kənˈdɪʃənɪŋ/","명사","에어컨","Please adjust the air conditioning using the remote.","리모컨으로 에어컨을 조절해 주세요."),
"heater": ("/ˈhiːtər/","명사","히터","The heater in the room doesn't seem to be working.","객실의 히터가 작동하지 않는 것 같다."),
"thermostat": ("/ˈθɜːrməstæt/","명사","온도 조절기","Set the thermostat to your preferred temperature.","온도 조절기를 원하는 온도로 설정하세요."),
"Wi-Fi": ("/ˈwaɪ faɪ/","명사","와이파이","What is the Wi-Fi password for the hotel?","호텔 와이파이 비밀번호가 무엇인가요?"),
"outlet": ("/ˈaʊtlɛt/","명사","콘센트","The outlet near the desk is the most convenient.","책상 옆 콘센트가 가장 편리하다."),
"adapter": ("/əˈdæptər/","명사","어댑터","Do you have a universal power adapter?","범용 전원 어댑터가 있나요?"),
"bathroom": ("/ˈbæθruːm/","명사","욕실","The bathroom has both a shower and a bathtub.","욕실에는 샤워기와 욕조가 모두 있다."),
"shower": ("/ˈʃaʊər/","명사","샤워기, 샤워","The hot water in the shower is not working.","샤워기의 온수가 나오지 않는다."),
"bathtub": ("/ˈbæθtʌb/","명사","욕조","I love relaxing in the bathtub after a long trip.","긴 여행 후 욕조에서 쉬는 것을 좋아한다."),
"toilet": ("/ˈtɔɪlɪt/","명사","변기, 화장실","The toilet is clogged and needs maintenance.","변기가 막혀 수리가 필요합니다."),
"hot water": ("/hɒt ˈwɔːtər/","명사","온수","There is no hot water in the bathroom.","욕실에 온수가 나오지 않는다."),
"hairdryer": ("/ˈhɛərˌdraɪər/","명사","헤어드라이어","The hairdryer is in the top drawer.","헤어드라이어는 맨 위 서랍 안에 있습니다."),
"shampoo": ("/ʃæmˈpuː/","명사","샴푸","The hotel provides shampoo and conditioner.","호텔에서 샴푸와 컨디셔너를 제공합니다."),
"soap": ("/soʊp/","명사","비누","There is a bar of soap by the sink.","세면대 옆에 비누가 있습니다."),
"toiletries": ("/ˈtɔɪlɪtriz/","명사","세면도구","The hotel provides complimentary toiletries.","호텔에서 무료 세면도구를 제공합니다."),
"amenities": ("/əˈmiːnɪtiz/","명사","편의시설","The hotel has excellent amenities including a pool and gym.","호텔에는 수영장과 체육관을 포함한 훌륭한 편의시설이 있다."),
"elevator": ("/ˈɛlɪˌveɪtər/","명사","엘리베이터","Take the elevator to the 10th floor.","엘리베이터를 타고 10층으로 올라가세요."),
"stairs": ("/stɛrz/","명사","계단","The stairs are at the end of the corridor.","계단은 복도 끝에 있습니다."),
"floor": ("/flɔːr/","명사","층","My room is on the fifth floor.","내 방은 5층에 있다."),
"corridor": ("/ˈkɒrɪdɔːr/","명사","복도","Walk down the corridor and turn left.","복도를 따라 걸어가다 왼쪽으로 돌아세요."),
"emergency exit": ("/ɪˈmɜːrdʒənsi ˈɛɡzɪt/","명사","비상구","The emergency exit is at the end of the hall.","비상구는 복도 끝에 있습니다."),
"fire escape": ("/ˈfaɪər ɪˌskeɪp/","명사","화재 비상구","The fire escape is clearly marked on each floor.","화재 비상구는 각 층에 명확히 표시되어 있다."),
"safe": ("/seɪf/","명사","금고","Store your valuables in the room safe.","귀중품은 객실 금고에 보관하세요."),
"deposit box": ("/dɪˈpɒzɪt bɒks/","명사","보관함","The front desk has a safe deposit box for valuables.","프런트 데스크에 귀중품 보관함이 있습니다."),
"parking": ("/ˈpɑːrkɪŋ/","명사","주차","Free parking is available for hotel guests.","호텔 투숙객에게 무료 주차가 제공됩니다."),
"valet parking": ("/ˈvæleɪ ˈpɑːrkɪŋ/","명사","대리 주차","The hotel offers valet parking for an additional fee.","호텔에서는 추가 요금으로 대리 주차 서비스를 제공합니다."),
"bellboy": ("/ˈbɛlˌbɔɪ/","명사","벨보이","The bellboy will bring your luggage to your room.","벨보이가 짐을 객실로 가져다 드릴 것입니다."),
"concierge": ("/ˌkɒnsiˈɛərʒ/","명사","컨시어지","Ask the concierge for restaurant recommendations.","컨시어지에게 식당 추천을 요청하세요."),
"porter": ("/ˈpɔːrtər/","명사","포터","The porter helped carry our heavy suitcases.","포터가 무거운 여행 가방을 들어주었다."),
"tip": ("/tɪp/","명사","팁, 봉사료","It is customary to tip the bellboy.","벨보이에게 팁을 주는 것이 관례입니다."),
"receipt": ("/rɪˈsiːt/","명사","영수증","I need a receipt for my expense report.","경비 보고서를 위해 영수증이 필요합니다."),
"bill": ("/bɪl/","명사","청구서","Can I see the bill before I check out?","체크아웃 전에 청구서를 볼 수 있을까요?"),
"rate": ("/reɪt/","명사","요금, 숙박비","What is the nightly rate for a double room?","더블룸의 1박 요금이 얼마인가요?"),
"discount": ("/ˈdɪskaʊnt/","명사","할인","Do you offer a discount for long stays?","장기 투숙 할인이 있나요?"),
"complimentary": ("/ˌkɒmplɪˈmɛntəri/","형용사","무료의","Breakfast is complimentary for all guests.","모든 투숙객에게 조식이 무료로 제공됩니다."),
"breakfast": ("/ˈbrɛkfəst/","명사","아침 식사","Breakfast is served from 7 to 10 a.m.","조식은 오전 7시부터 10시까지 제공됩니다."),
"buffet": ("/ˈbʌfeɪ/","명사","뷔페","The buffet has a wide selection of local dishes.","뷔페에는 다양한 현지 음식이 있다."),
"swimming pool": ("/ˈswɪmɪŋ puːl/","명사","수영장","The outdoor swimming pool is heated year-round.","야외 수영장은 연중 온수로 운영됩니다."),
"gym": ("/dʒɪm/","명사","체육관","The hotel gym is open 24 hours a day.","호텔 체육관은 24시간 운영됩니다."),
"spa": ("/spɑː/","명사","스파","Book a spa treatment in advance.","스파 트리트먼트는 미리 예약하세요."),
"sauna": ("/ˈsɔːnə/","명사","사우나","Enjoy the sauna on the top floor.","최상층의 사우나를 즐기세요."),
"balcony": ("/ˈbælkəni/","명사","발코니","The room has a private balcony with a sea view.","객실에는 바다 전망의 개인 발코니가 있다."),
"view": ("/vjuː/","명사","전망","I'd like a room with a mountain view, please.","산 전망의 객실을 원합니다."),
"ocean view": ("/ˈoʊʃən vjuː/","명사","바다 전망","An ocean-view room costs a bit more.","바다 전망 객실은 조금 더 비싸다."),
"city view": ("/ˈsɪti vjuː/","명사","도시 전망","The city-view room is perfect for night scenes.","도시 전망 객실은 야경 감상에 안성맞춤이다."),
"noise complaint": ("/nɔɪz kəmˈpleɪnt/","명사","소음 불만","I need to make a noise complaint about room 302.","302호실에 대한 소음 불만을 제기해야 합니다."),
"maintenance": ("/ˈmeɪntənəns/","명사","유지 보수","I'll send someone from maintenance right away.","지금 바로 유지 보수 담당자를 보내겠습니다."),
"repair": ("/rɪˈpɛər/","명사","수리","The shower needs repair.","샤워기 수리가 필요합니다."),
"clogged": ("/klɒɡd/","형용사","막힌","The drain is clogged.","배수구가 막혀 있습니다."),
"leak": ("/liːk/","명사","누수","There is a leak in the bathroom ceiling.","욕실 천장에서 누수가 있다."),
"upgrade": ("/ˈʌpɡreɪd/","명사","업그레이드","Is it possible to upgrade to a suite?","스위트룸으로 업그레이드가 가능한가요?"),
"late check-out": ("/leɪt ˈtʃɛk ˌaʊt/","명사","늦은 체크아웃","Can I arrange a late check-out until 2 p.m.?","오후 2시까지 늦은 체크아웃을 요청할 수 있나요?"),
"early check-in": ("/ˈɜːrli ˈtʃɛk ɪn/","명사","조기 체크인","Early check-in is available if your room is ready.","객실이 준비된 경우 조기 체크인이 가능합니다."),
"luggage storage": ("/ˈlʌɡɪdʒ ˈstɔːrɪdʒ/","명사","짐 보관 서비스","Can you store my luggage until my flight this evening?","오늘 저녁 항공편까지 짐을 맡아주실 수 있나요?"),
"lost and found": ("/lɒst ænd faʊnd/","명사","분실물 센터","I left my glasses in the room — is there a lost and found?","방에 안경을 두고 왔는데 분실물 센터가 있나요?"),
"non-smoking room": ("/nɒn ˈsmoʊkɪŋ ruːm/","명사","금연 객실","Please book me a non-smoking room.","금연 객실로 예약해 주세요."),
"crib": ("/krɪb/","명사","아기 침대","Can we have a crib for our baby?","아기용 침대를 이용할 수 있나요?"),
"fully booked": ("/ˈfʊli bʊkt/","형용사","만실인","The hotel is fully booked for this weekend.","이번 주말에 호텔이 만실입니다."),
"available": ("/əˈveɪləbəl/","형용사","이용 가능한","Is the room available from Friday?","금요일부터 객실 이용이 가능한가요?"),
"guest": ("/ɡɛst/","명사","투숙객","All guests receive a complimentary breakfast.","모든 투숙객은 무료 조식을 받습니다."),
"identity card": ("/aɪˈdɛntɪti kɑːrd/","명사","신분증","Please present your identity card at check-in.","체크인 시 신분증을 제시해 주세요."),
"extend stay": ("/ɪkˈstɛnd steɪ/","명사","투숙 연장","I would like to extend my stay by one more night.","하룻밤 더 투숙을 연장하고 싶습니다."),
"overcharge": ("/ˌoʊvərˈtʃɑːrdʒ/","동사","과다 청구하다","I think there's been an overcharge on my bill.","청구서에 과다 청구가 있는 것 같습니다."),
"refund": ("/ˈriːfʌnd/","명사","환불","I'd like a refund for the unused nights.","사용하지 않은 날짜에 대해 환불을 받고 싶습니다."),
"bed bug": ("/ˈbɛd bʌɡ/","명사","빈대","I found a bed bug in my room and need to change rooms.","객실에서 빈대를 발견했는데 방을 바꿔야 합니다."),

# ── restaurant ────────────────────────────────────────────────────────────
"restaurant": ("/ˈrɛstərɒnt/","명사","식당, 레스토랑","Can you recommend a good restaurant nearby?","근처에 좋은 식당을 추천해 주실 수 있나요?"),
"menu": ("/ˈmɛnjuː/","명사","메뉴","May I see the menu, please?","메뉴판을 볼 수 있을까요?"),
"order": ("/ˈɔːrdər/","동사","주문하다","Are you ready to order?","주문하실 준비가 되셨나요?"),
"appetizer": ("/ˈæpɪtaɪzər/","명사","애피타이저","We started with a light appetizer.","우리는 가벼운 애피타이저로 시작했다."),
"main course": ("/meɪn kɔːrs/","명사","메인 요리","I'll have the grilled salmon as my main course.","메인 요리로 그릴 연어를 주문하겠습니다."),
"dessert": ("/dɪˈzɜːrt/","명사","디저트","I'd like a slice of chocolate cake for dessert.","디저트로 초콜릿 케이크 한 조각을 주세요."),
"beverage": ("/ˈbɛvərɪdʒ/","명사","음료","Would you like a beverage with your meal?","식사와 함께 음료를 드시겠어요?"),
"water": ("/ˈwɔːtər/","명사","물","Could I get a glass of water, please?","물 한 잔 주실 수 있을까요?"),
"juice": ("/dʒuːs/","명사","주스","I'll start with a glass of orange juice.","오렌지 주스 한 잔으로 시작하겠습니다."),
"coffee": ("/ˈkɒfi/","명사","커피","Could I have a black coffee, please?","블랙 커피 한 잔 주시겠어요?"),
"tea": ("/tiː/","명사","차","I'd prefer green tea after the meal.","식사 후에는 녹차를 마시고 싶습니다."),
"wine": ("/waɪn/","명사","와인","Could we see the wine list?","와인 리스트를 볼 수 있을까요?"),
"beer": ("/bɪər/","명사","맥주","I'll have a cold beer, please.","시원한 맥주 한 잔 부탁합니다."),
"cocktail": ("/ˈkɒkteɪl/","명사","칵테일","This restaurant serves excellent cocktails.","이 식당은 훌륭한 칵테일을 제공한다."),
"soft drink": ("/sɒft drɪŋk/","명사","탄산음료, 청량음료","I'd like a cola or another soft drink.","콜라나 다른 청량음료를 마시고 싶습니다."),
"ice": ("/aɪs/","명사","얼음","Could I have my drink with no ice?","음료에 얼음 없이 주실 수 있나요?"),
"straw": ("/strɔː/","명사","빨대","Do you have paper straws?","종이 빨대가 있나요?"),
"napkin": ("/ˈnæpkɪn/","명사","냅킨","Could I have an extra napkin?","냅킨을 하나 더 주실 수 있나요?"),
"plate": ("/pleɪt/","명사","접시","The portions are so large they barely fit on the plate.","양이 너무 많아 접시에 거의 다 담기지 않는다."),
"bowl": ("/boʊl/","명사","그릇","The soup comes in a large bowl.","수프는 큰 그릇에 나옵니다."),
"cup": ("/kʌp/","명사","컵","May I have a cup of hot water?","따뜻한 물 한 컵 주실 수 있나요?"),
"glass": ("/ɡlɑːs/","명사","유리잔","Bring us a glass of sparkling water, please.","탄산수 한 잔 가져다 주세요."),
"fork": ("/fɔːrk/","명사","포크","Could I get a fork? I dropped mine.","포크 하나 주실 수 있나요? 제 것을 떨어뜨렸어요."),
"knife": ("/naɪf/","명사","나이프","I need a sharper knife to cut this steak.","이 스테이크를 자르려면 더 날카로운 나이프가 필요해요."),
"spoon": ("/spuːn/","명사","숟가락","Is there a spoon for the soup?","수프용 숟가락이 있나요?"),
"chopsticks": ("/ˈtʃɒpˌstɪks/","명사","젓가락","Do you know how to use chopsticks?","젓가락 사용법을 아세요?"),
"tray": ("/treɪ/","명사","쟁반","The waiter carried everything on a large tray.","웨이터는 큰 쟁반에 모든 것을 담아 날랐다."),
"table": ("/ˈteɪbəl/","명사","테이블","We'd like a table for four, please.","4인용 테이블 부탁합니다."),
"chair": ("/tʃɛər/","명사","의자","Is this chair taken?","이 의자 자리가 있나요?"),
"booth": ("/buːð/","명사","부스 좌석","We prefer a booth for more privacy.","우리는 더 프라이빗한 부스 좌석을 선호한다."),
"waiter": ("/ˈweɪtər/","명사","남자 웨이터","Excuse me, waiter — could we get the check?","실례합니다, 웨이터 — 계산서 주실 수 있나요?"),
"waitress": ("/ˈweɪtrɪs/","명사","여자 웨이트리스","The waitress was very friendly and helpful.","여자 웨이트리스가 매우 친절하고 도움이 됐다."),
"chef": ("/ʃɛf/","명사","주방장","The chef personally prepared this dish.","주방장이 이 요리를 직접 준비했습니다."),
"cashier": ("/kæˈʃɪər/","명사","계산원","Pay the cashier at the front counter.","앞쪽 카운터에서 계산원에게 지불하세요."),
"host": ("/hoʊst/","명사","안내 직원","The host will seat you shortly.","안내 직원이 곧 자리를 안내해 드릴 것입니다."),
"waiting list": ("/ˈweɪtɪŋ lɪst/","명사","대기 명단","We were put on the waiting list for 20 minutes.","우리는 20분 대기 명단에 올랐다."),
"seat": ("/siːt/","명사","자리","Is this seat taken?","이 자리 있나요?"),
"outdoor seating": ("/ˈaʊtdɔːr ˈsiːtɪŋ/","명사","야외 좌석","I prefer outdoor seating on nice days.","날씨가 좋을 때는 야외 좌석을 선호합니다."),
"smoking section": ("/ˈsmoʊkɪŋ ˈsɛkʃən/","명사","흡연석","Does this restaurant have a smoking section?","이 식당에 흡연석이 있나요?"),
"non-smoking": ("/nɒn ˈsmoʊkɪŋ/","형용사","금연의","We'd like a table in the non-smoking area.","금연 구역의 테이블로 부탁합니다."),
"bill": ("/bɪl/","명사","계산서","Could we have the bill, please?","계산서 주실 수 있나요?"),
"check": ("/tʃɛk/","명사","계산서 (미국식)","Can we get the check when you have a moment?","시간이 되실 때 계산서 주실 수 있나요?"),
"tip": ("/tɪp/","명사","팁","We left a 15% tip for the great service.","훌륭한 서비스에 15% 팁을 남겼다."),
"service charge": ("/ˈsɜːrvɪs tʃɑːrdʒ/","명사","봉사료","A 10% service charge is automatically added.","봉사료 10%가 자동으로 추가됩니다."),
"split the bill": ("/splɪt ðə bɪl/","동사","더치페이하다","Shall we split the bill?","더치페이할까요?"),
"takeout": ("/ˈteɪkˌaʊt/","명사","포장 음식","I'd like to place a takeout order.","포장 주문을 하고 싶습니다."),
"delivery": ("/dɪˈlɪvəri/","명사","배달","Do you offer food delivery to hotels?","호텔로 음식 배달을 해주시나요?"),
"dine-in": ("/daɪn ɪn/","형용사","매장 내 식사의","This discount is for dine-in customers only.","이 할인은 매장 내 식사 고객에게만 적용됩니다."),
"buffet": ("/ˈbʌfeɪ/","명사","뷔페","The hotel restaurant offers a Sunday brunch buffet.","호텔 레스토랑은 일요일 브런치 뷔페를 제공합니다."),
"brunch": ("/brʌntʃ/","명사","브런치","Let's go for brunch on Sunday morning.","일요일 아침에 브런치 먹으러 가자."),
"portion": ("/ˈpɔːrʃən/","명사","1인분, 양","The portion size here is very generous.","이곳의 1인분 양이 매우 많다."),
"serving": ("/ˈsɜːrvɪŋ/","명사","1회 제공량","Each serving contains 300 calories.","1회 제공량에는 300칼로리가 들어 있습니다."),
"ingredient": ("/ɪnˈɡriːdiənt/","명사","재료","What are the main ingredients in this dish?","이 요리의 주요 재료가 무엇인가요?"),
"spicy": ("/ˈspaɪsi/","형용사","매운","Is this dish very spicy?","이 요리가 많이 맵나요?"),
"mild": ("/maɪld/","형용사","순한, 자극적이지 않은","I'd prefer something mild, not too spicy.","매운 것보다 순한 것을 원합니다."),
"sweet": ("/swiːt/","형용사","달콤한","This dessert is too sweet for me.","이 디저트는 저에게 너무 달콤합니다."),
"sour": ("/saʊər/","형용사","신","The sauce has a pleasantly sour taste.","소스가 기분 좋게 신맛이 난다."),
"salty": ("/ˈsɔːlti/","형용사","짠","The soup is a bit too salty for my taste.","수프가 제 입맛에는 조금 너무 짭니다."),
"bitter": ("/ˈbɪtər/","형용사","쓴","Dark chocolate has a slightly bitter taste.","다크 초콜릿은 약간 쓴맛이 난다."),
"savory": ("/ˈseɪvəri/","형용사","고소한, 풍미 있는","The stew has a rich, savory flavor.","스튜는 풍부하고 고소한 맛이 난다."),
"bland": ("/blænd/","형용사","맛이 없는, 싱거운","The pasta was a bit bland without seasoning.","파스타가 양념 없이 조금 싱거웠다."),
"fresh": ("/frɛʃ/","형용사","신선한","The vegetables here are always fresh.","여기의 채소는 항상 신선합니다."),
"raw": ("/rɔː/","형용사","날것의","I prefer my tuna raw, like in sashimi.","저는 생선회처럼 날것의 참치를 선호합니다."),
"grilled": ("/ɡrɪld/","형용사","구운","I'll have the grilled chicken salad.","구운 닭고기 샐러드를 주문하겠습니다."),
"fried": ("/fraɪd/","형용사","튀긴","The fried calamari was perfectly crispy.","튀긴 오징어 링이 완벽하게 바삭했다."),
"baked": ("/beɪkt/","형용사","구운 (오븐)","The baked potato comes with sour cream.","구운 감자에는 사워크림이 곁들여 나옵니다."),
"steamed": ("/stiːmd/","형용사","찐","I'd like the dumplings steamed, not fried.","만두를 튀기지 말고 쪄주세요."),
"roasted": ("/ˈroʊstɪd/","형용사","로스팅한","The roasted vegetables make a great side dish.","로스팅한 채소는 훌륭한 사이드 디시가 된다."),
"boiled": ("/bɔɪld/","형용사","삶은","I'll have a boiled egg with my breakfast.","아침 식사로 삶은 달걀을 주세요."),
"vegetarian": ("/ˌvɛdʒɪˈtɛəriən/","형용사","채식주의의","Do you have vegetarian options on the menu?","메뉴에 채식주의자를 위한 옵션이 있나요?"),
"vegan": ("/ˈviːɡən/","형용사","완전 채식주의의","Is there anything vegan on the menu?","메뉴에 비건 음식이 있나요?"),
"gluten-free": ("/ˈɡluːtən friː/","형용사","글루텐 프리의","I need a gluten-free option due to an intolerance.","불내증 때문에 글루텐 프리 옵션이 필요합니다."),
"allergy": ("/ˈælərdʒi/","명사","알레르기","I have a severe nut allergy.","저는 심한 견과류 알레르기가 있습니다."),
"dairy-free": ("/ˈdɛəri friː/","형용사","유제품 무첨가의","Does this dish contain dairy? I'm dairy-free.","이 요리에 유제품이 들어가나요? 저는 유제품을 먹지 않습니다."),
"organic": ("/ɔːrˈɡænɪk/","형용사","유기농의","All vegetables used here are organic.","여기서 사용하는 모든 채소는 유기농입니다."),
"signature dish": ("/ˈsɪɡnɪtʃər dɪʃ/","명사","대표 메뉴","What is your signature dish?","이 식당의 대표 메뉴는 무엇인가요?"),
"side dish": ("/saɪd dɪʃ/","명사","사이드 디시","Which side dish comes with the steak?","스테이크에 어떤 사이드 디시가 나오나요?"),
"salad": ("/ˈsæləd/","명사","샐러드","I'll have the Caesar salad as a starter.","시저 샐러드를 에피타이저로 주세요."),
"soup": ("/suːp/","명사","수프","The soup of the day is tomato basil.","오늘의 수프는 토마토 바질입니다."),
"pasta": ("/ˈpæstə/","명사","파스타","The carbonara pasta is excellent here.","이곳의 카르보나라 파스타가 매우 훌륭하다."),
"steak": ("/steɪk/","명사","스테이크","How would you like your steak cooked?","스테이크를 어떻게 익혀 드릴까요?"),
"seafood": ("/ˈsiːfuːd/","명사","해산물","This restaurant specializes in fresh seafood.","이 식당은 신선한 해산물을 전문으로 합니다."),
"well-done": ("/ˌwɛl ˈdʌn/","형용사","완전히 익힌","I'd like my steak well-done, please.","스테이크를 완전히 익혀 주세요."),
"medium rare": ("/ˈmiːdiəm rɛər/","형용사","미디엄 레어로 익힌","The chef recommends the steak medium rare.","주방장은 미디엄 레어로 익힌 스테이크를 추천합니다."),
"rare": ("/rɛər/","형용사","덜 익힌","I prefer my steak rare.","스테이크를 덜 익히는 것을 선호합니다."),
"sauce": ("/sɔːs/","명사","소스","What sauce comes with the dish?","요리에 어떤 소스가 곁들여지나요?"),
"condiment": ("/ˈkɒndɪmənt/","명사","조미료, 양념","The table has salt, pepper, and other condiments.","테이블에 소금, 후추와 다른 조미료가 있습니다."),
"refill": ("/ˈriːfɪl/","명사","리필","Do you offer free refills on soft drinks?","청량음료 무료 리필이 되나요?"),
"doggy bag": ("/ˈdɒɡi bæɡ/","명사","남은 음식 포장 봉투","Could I have a doggy bag for the leftovers?","남은 음식을 포장해 주실 수 있나요?"),
"sold out": ("/soʊld aʊt/","형용사","품절된","I'm sorry, the lobster is sold out tonight.","죄송하지만 오늘 저녁 바닷가재는 품절입니다."),
"complimentary": ("/ˌkɒmplɪˈmɛntəri/","형용사","서비스로 제공되는","The bread basket is complimentary.","빵 바구니는 서비스로 제공됩니다."),
"last order": ("/lɑːst ˈɔːrdər/","명사","라스트 오더","Last order is at 10 p.m.","라스트 오더는 오후 10시입니다."),
"bon appétit": ("/ˌbɒn æpɪˈtiː/","감탄사","맛있게 드세요","The waiter smiled and said 'Bon appétit!'","웨이터가 미소 지으며 '맛있게 드세요!'라고 말했다."),

# ── shopping ──────────────────────────────────────────────────────────────
"shop": ("/ʃɒp/","명사","가게","There are many interesting shops in the old town.","구시가지에 흥미로운 가게들이 많이 있다."),
"store": ("/stɔːr/","명사","상점","The department store is open until 9 p.m.","백화점은 오후 9시까지 열려 있다."),
"shopping mall": ("/ˈʃɒpɪŋ mɔːl/","명사","쇼핑몰","The shopping mall has over 200 stores.","쇼핑몰에는 200개 이상의 상점이 있다."),
"market": ("/ˈmɑːrkɪt/","명사","시장","The local market sells fresh produce every morning.","지역 시장에서 매일 아침 신선한 농산물을 팝니다."),
"price": ("/praɪs/","명사","가격","What is the price of this item?","이 물건의 가격이 얼마인가요?"),
"cost": ("/kɒst/","명사","비용","How much does this cost?","이것은 얼마인가요?"),
"expensive": ("/ɪkˈspɛnsɪv/","형용사","비싼","That watch is too expensive for me.","그 시계는 나에게 너무 비싸다."),
"cheap": ("/tʃiːp/","형용사","저렴한","I found a cheap but good souvenir.","저렴하지만 좋은 기념품을 찾았다."),
"bargain": ("/ˈbɑːrɡɪn/","명사","할인 상품, 흥정","I got a real bargain at the flea market.","벼룩시장에서 정말 저렴하게 샀다."),
"sale": ("/seɪl/","명사","세일","Everything is on sale this weekend.","이번 주말에는 모든 것이 세일 중이다."),
"discount": ("/ˈdɪskaʊnt/","명사","할인","Is there a discount for students?","학생 할인이 있나요?"),
"coupon": ("/ˈkuːpɒn/","명사","쿠폰","I have a coupon for 20% off.","20% 할인 쿠폰이 있습니다."),
"cash": ("/kæʃ/","명사","현금","Do you accept cash?","현금으로 결제할 수 있나요?"),
"credit card": ("/ˈkrɛdɪt kɑːrd/","명사","신용카드","I'll pay by credit card.","신용카드로 결제하겠습니다."),
"debit card": ("/ˈdɛbɪt kɑːrd/","명사","직불카드","I'll use my debit card for this purchase.","이 구매는 직불카드로 결제할게요."),
"contactless payment": ("/ˈkɒntæktlɪs ˈpeɪmənt/","명사","비접촉 결제","Do you accept contactless payment?","비접촉 결제가 가능한가요?"),
"exchange rate": ("/ɪksˈtʃeɪndʒ reɪt/","명사","환율","What is today's exchange rate?","오늘 환율이 어떻게 되나요?"),
"currency": ("/ˈkɜːrənsi/","명사","통화","What currency should I use here?","여기서는 어떤 통화를 사용해야 하나요?"),
"ATM": ("/ˌeɪ tiː ˈɛm/","명사","ATM, 현금자동인출기","Is there an ATM nearby?","근처에 ATM이 있나요?"),
"withdraw": ("/wɪðˈdrɔː/","동사","인출하다","I need to withdraw some cash.","현금을 좀 인출해야 합니다."),
"dollar": ("/ˈdɒlər/","명사","달러","Do you accept US dollars here?","여기서 미국 달러를 받나요?"),
"euro": ("/ˈjʊəroʊ/","명사","유로","Prices are listed in euros.","가격은 유로로 표시됩니다."),
"pound": ("/paʊnd/","명사","파운드","I need to exchange dollars for pounds.","달러를 파운드로 환전해야 합니다."),
"size": ("/saɪz/","명사","사이즈","What size do you need?","몇 사이즈가 필요하세요?"),
"small": ("/smɔːl/","형용사","작은","Do you have this in a small?","이것 스몰 사이즈 있나요?"),
"medium": ("/ˈmiːdiəm/","형용사","중간 크기의","I'm usually a medium.","저는 보통 미디엄 사이즈입니다."),
"large": ("/lɑːrdʒ/","형용사","큰","Do you have this shirt in large?","이 셔츠 라지 사이즈 있나요?"),
"extra large": ("/ˈɛkstrə lɑːrdʒ/","형용사","특대 사이즈의","I need extra large in this style.","이 스타일에서 특대 사이즈가 필요합니다."),
"fitting room": ("/ˈfɪtɪŋ ruːm/","명사","탈의실","Where is the fitting room?","탈의실이 어디에 있나요?"),
"try on": ("/traɪ ɒn/","동사","입어보다","May I try this on?","이것을 입어봐도 될까요?"),
"fit": ("/fɪt/","동사","맞다","Does this dress fit you well?","이 원피스가 잘 맞나요?"),
"tight": ("/taɪt/","형용사","꽉 맞는","These jeans are a bit tight.","이 청바지가 조금 꽉 맞는다."),
"loose": ("/luːs/","형용사","헐렁한","The jacket is a bit loose around the shoulders.","재킷이 어깨 부분이 조금 헐렁하다."),
"color": ("/ˈkʌlər/","명사","색상","Do you have this in a different color?","다른 색상도 있나요?"),
"style": ("/staɪl/","명사","스타일","I'm looking for a classic style.","클래식한 스타일을 찾고 있습니다."),
"brand": ("/brænd/","명사","브랜드","Is this a local brand?","이것은 현지 브랜드인가요?"),
"quality": ("/ˈkwɒlɪti/","명사","품질","The quality is excellent for the price.","가격에 비해 품질이 훌륭하다."),
"material": ("/məˈtɪəriəl/","명사","소재, 재질","What material is this jacket made of?","이 재킷은 어떤 소재로 만들어졌나요?"),
"cotton": ("/ˈkɒtən/","명사","면, 면화","I prefer cotton shirts in the summer.","여름에는 면 셔츠를 선호합니다."),
"silk": ("/sɪlk/","명사","실크, 비단","This is made from pure silk.","이것은 순수 실크로 만들어졌습니다."),
"leather": ("/ˈlɛðər/","명사","가죽","These are genuine leather shoes.","이것은 진짜 가죽 신발입니다."),
"wool": ("/wʊl/","명사","울, 양모","This scarf is made of merino wool.","이 스카프는 메리노 울로 만들어졌습니다."),
"souvenir": ("/ˌsuːvəˈnɪər/","명사","기념품","I bought a souvenir magnet for my fridge.","냉장고 자석 기념품을 샀다."),
"gift": ("/ɡɪft/","명사","선물","I'm looking for a gift for my friend.","친구에게 줄 선물을 찾고 있습니다."),
"bag": ("/bæɡ/","명사","가방","Could I have a bag for my purchases?","구매한 물건을 담을 가방을 주실 수 있나요?"),
"plastic bag": ("/ˈplæstɪk bæɡ/","명사","비닐봉지","Do you have a plastic bag?","비닐봉지가 있나요?"),
"gift wrap": ("/ɡɪft ræp/","명사","선물 포장","Could you gift-wrap this for me?","선물 포장을 해주실 수 있나요?"),
"shoes": ("/ʃuːz/","명사","신발","I'm looking for a pair of comfortable shoes.","편안한 신발 한 켤레를 찾고 있습니다."),
"boots": ("/buːts/","명사","부츠","These leather boots look great.","이 가죽 부츠가 정말 멋져 보인다."),
"sneakers": ("/ˈsniːkərz/","명사","운동화","I need a pair of running sneakers.","달리기용 운동화 한 켤레가 필요합니다."),
"accessories": ("/əkˈsɛsəriz/","명사","액세서리","The accessories section is on the third floor.","액세서리 코너는 3층에 있습니다."),
"jewelry": ("/ˈdʒuːəlri/","명사","보석류, 장신구","She bought beautiful jewelry at the market.","그녀는 시장에서 아름다운 장신구를 샀다."),
"necklace": ("/ˈnɛklɪs/","명사","목걸이","I bought a silver necklace as a souvenir.","기념품으로 은 목걸이를 샀다."),
"bracelet": ("/ˈbreɪslɪt/","명사","팔찌","The handmade bracelets are very popular.","수제 팔찌가 매우 인기 있다."),
"sunglasses": ("/ˈsʌnˌɡlɑːsɪz/","명사","선글라스","I need to buy sunglasses for the beach.","해변을 위한 선글라스를 구입해야 합니다."),
"hat": ("/hæt/","명사","모자","This straw hat is perfect for the summer.","이 밀짚모자는 여름에 딱이다."),
"wallet": ("/ˈwɒlɪt/","명사","지갑","I bought a leather wallet as a gift.","선물로 가죽 지갑을 샀다."),
"backpack": ("/ˈbækˌpæk/","명사","백팩, 배낭","I need a lightweight backpack for traveling.","여행용 가벼운 백팩이 필요합니다."),
"suitcase": ("/ˈsuːtˌkeɪs/","명사","여행 가방","I bought a new suitcase for the trip.","여행을 위해 새 여행 가방을 샀다."),
"refund": ("/ˈriːfʌnd/","명사","환불","Can I get a refund if the item is defective?","물건이 불량이면 환불받을 수 있나요?"),
"return": ("/rɪˈtɜːrn/","동사","반품하다","I'd like to return this shirt.","이 셔츠를 반품하고 싶습니다."),
"exchange": ("/ɪksˈtʃeɪndʒ/","동사","교환하다","Can I exchange this for a different size?","다른 사이즈로 교환할 수 있나요?"),
"warranty": ("/ˈwɒrənti/","명사","보증","Does this product come with a warranty?","이 제품에 보증이 포함되어 있나요?"),
"defective": ("/dɪˈfɛktɪv/","형용사","결함이 있는","The item I bought turned out to be defective.","내가 산 물건이 결함이 있는 것으로 판명됐다."),
"tax-free": ("/tæks friː/","형용사","세금 면제의","Is this item tax-free for tourists?","이 물건은 관광객에게 세금이 면제되나요?"),
"duty-free": ("/ˌdjuːti ˈfriː/","형용사","면세의","I bought this perfume duty-free at the airport.","이 향수를 공항 면세점에서 샀다."),
"customs declaration": ("/ˈkʌstəmz ˌdɛkləˈreɪʃən/","명사","세관 신고","You must fill out a customs declaration if buying over the limit.","한도를 초과하여 구매하는 경우 세관 신고서를 작성해야 합니다."),
"import limit": ("/ˈɪmpɔːrt ˈlɪmɪt/","명사","반입 한도","Alcohol has a strict import limit per person.","주류에는 1인당 엄격한 반입 한도가 있습니다."),
"shipping": ("/ˈʃɪpɪŋ/","명사","배송","International shipping takes about two weeks.","국제 배송은 약 2주가 걸립니다."),
"delivery": ("/dɪˈlɪvəri/","명사","배달, 배송","Do you offer home delivery?","가정 배송 서비스가 있나요?"),
"fragile": ("/ˈfrædʒaɪl/","형용사","깨지기 쉬운","Please label this package as fragile.","이 소포에 '취급 주의' 라벨을 붙여 주세요."),
"aisle": ("/aɪl/","명사","매장 통로","The electronics are in aisle five.","전자제품은 5번 통로에 있습니다."),
"shelf": ("/ʃɛlf/","명사","선반","Put it back on the shelf, please.","선반에 다시 올려놓아 주세요."),
"counter": ("/ˈkaʊntər/","명사","카운터","Pay at the counter by the exit.","출구 옆 카운터에서 결제하세요."),
"checkout": ("/ˈtʃɛkˌaʊt/","명사","계산대","There's a long queue at the checkout.","계산대에 줄이 길다."),
"barcode": ("/ˈbɑːrkoʊd/","명사","바코드","The cashier will scan the barcode.","계산원이 바코드를 스캔할 것입니다."),
"queue": ("/kjuː/","명사","줄, 대기","The queue for this shop is around the block.","이 가게 줄이 블록을 돌아갈 만큼 길다."),
"vendor": ("/ˈvɛndər/","명사","판매상","Many street vendors sell local crafts.","많은 노점상이 현지 공예품을 판다."),
"haggle": ("/ˈhæɡəl/","동사","흥정하다","In some markets, you can haggle over the price.","일부 시장에서는 가격을 흥정할 수 있다."),
"negotiation": ("/nɪˌɡoʊʃiˈeɪʃən/","명사","협상, 흥정","Price negotiation is common at street markets.","가격 협상은 노점 시장에서 흔하다."),
"in stock": ("/ɪn stɒk/","형용사","재고 있는","Is this model still in stock?","이 모델이 아직 재고가 있나요?"),
"sold out": ("/soʊld aʊt/","형용사","매진된","I'm afraid this item is sold out.","죄송하지만 이 물건은 매진되었습니다."),
"order online": ("/ˈɔːrdər ˈɒnlaɪn/","동사","온라인 주문하다","You can order online and pick it up in store.","온라인으로 주문하고 매장에서 수령할 수 있습니다."),
"pickup": ("/ˈpɪkˌʌp/","명사","픽업, 수령","Your order is ready for pickup.","주문하신 물건을 수령하실 수 있습니다."),
"tracking number": ("/ˈtrækɪŋ ˈnʌmbər/","명사","운송장 번호","Here is your tracking number to follow the delivery.","배송을 추적할 수 있는 운송장 번호입니다."),

# ── sightseeing ───────────────────────────────────────────────────────────
"museum": ("/mjuːˈziːəm/","명사","박물관","The national museum is free on Sundays.","국립 박물관은 일요일에 무료입니다."),
"art gallery": ("/ɑːrt ˈɡæləri/","명사","미술관","The contemporary art gallery opens at 10 a.m.","현대 미술관은 오전 10시에 문을 엽니다."),
"exhibition": ("/ˌɛksɪˈbɪʃən/","명사","전시회","There is a special photography exhibition this month.","이달에 특별 사진 전시회가 있습니다."),
"temple": ("/ˈtɛmpəl/","명사","사원, 절","The ancient temple is a popular tourist site.","고대 사원은 인기 있는 관광지입니다."),
"cathedral": ("/kəˈθiːdrəl/","명사","대성당","The gothic cathedral took 200 years to build.","고딕 대성당을 짓는 데 200년이 걸렸다."),
"church": ("/tʃɜːrtʃ/","명사","교회","The small church dates back to the 12th century.","이 작은 교회는 12세기로 거슬러 올라간다."),
"monument": ("/ˈmɒnjumənt/","명사","기념비, 기념물","The war monument stands in the center of town.","전쟁 기념비가 마을 중심부에 서 있다."),
"landmark": ("/ˈlændmɑːrk/","명사","랜드마크, 명소","The Eiffel Tower is one of the most famous landmarks.","에펠탑은 가장 유명한 랜드마크 중 하나이다."),
"palace": ("/ˈpælɪs/","명사","궁전","The royal palace is open to visitors on weekdays.","왕궁은 평일에 관광객에게 개방됩니다."),
"castle": ("/ˈkɑːsəl/","명사","성","The hilltop castle offers a stunning view.","언덕 위의 성에서 멋진 전망을 볼 수 있다."),
"ruins": ("/ˈruːɪnz/","명사","유적","The ancient ruins attract thousands of visitors.","고대 유적은 수천 명의 방문객을 끌어들인다."),
"statue": ("/ˈstætʃuː/","명사","조각상","There is a bronze statue in the main square.","중앙 광장에 청동 조각상이 있다."),
"fountain": ("/ˈfaʊntɪn/","명사","분수","Toss a coin into the fountain for good luck.","행운을 빌며 분수에 동전을 던지세요."),
"bridge": ("/brɪdʒ/","명사","다리 (건축물)","Walk across the old stone bridge for a great view.","멋진 전망을 위해 오래된 돌다리를 건너세요."),
"tower": ("/ˈtaʊər/","명사","탑","The observation tower gives a 360-degree view.","전망대 탑에서 360도 전망을 볼 수 있다."),
"square": ("/skwɛər/","명사","광장","The main square is surrounded by historic buildings.","중앙 광장은 역사적인 건물들로 둘러싸여 있다."),
"park": ("/pɑːrk/","명사","공원","Let's have a picnic in the city park.","도시 공원에서 소풍을 즐깁시다."),
"garden": ("/ˈɡɑːrdən/","명사","정원","The botanical garden has over a thousand plant species.","식물원에는 천 가지 이상의 식물 종이 있다."),
"beach": ("/biːtʃ/","명사","해변","The hotel is within walking distance of the beach.","호텔은 해변에서 걸어서 갈 수 있는 거리에 있다."),
"mountain": ("/ˈmaʊntɪn/","명사","산","The mountain offers excellent hiking trails.","그 산에는 훌륭한 하이킹 코스가 있다."),
"lake": ("/leɪk/","명사","호수","The crystal-clear lake is perfect for swimming.","맑고 투명한 호수는 수영하기에 안성맞춤입니다."),
"river": ("/ˈrɪvər/","명사","강","Take a boat ride along the river for great views.","강을 따라 보트를 타며 멋진 경치를 즐기세요."),
"waterfall": ("/ˈwɔːtərfɔːl/","명사","폭포","The waterfall is a 30-minute hike from the village.","폭포는 마을에서 30분 하이킹 거리에 있다."),
"cave": ("/keɪv/","명사","동굴","The guided cave tour takes about one hour.","가이드 동굴 투어는 약 한 시간이 걸린다."),
"island": ("/ˈaɪlənd/","명사","섬","The island is accessible only by ferry.","그 섬은 페리로만 접근할 수 있다."),
"cliff": ("/klɪf/","명사","절벽","Stand back from the cliff edge for your safety.","안전을 위해 절벽 가장자리에서 물러나세요."),
"valley": ("/ˈvæli/","명사","계곡","The green valley looks beautiful in spring.","봄에 녹색 계곡이 아름답게 보인다."),
"forest": ("/ˈfɒrɪst/","명사","숲","Walk through the ancient forest on this trail.","이 산책로를 따라 오래된 숲을 걸어보세요."),
"volcano": ("/vɒlˈkeɪnoʊ/","명사","화산","The dormant volcano is a popular hiking destination.","휴화산은 인기 있는 하이킹 목적지입니다."),
"sunrise": ("/ˈsʌnˌraɪz/","명사","일출","Wake up early to catch the sunrise from the summit.","정상에서 일출을 보려면 일찍 일어나세요."),
"sunset": ("/ˈsʌnsɛt/","명사","일몰","The sunset from this beach is absolutely breathtaking.","이 해변에서 보는 일몰은 정말 숨막히게 아름답습니다."),
"scenery": ("/ˈsiːnəri/","명사","경치","The mountain scenery is spectacular.","산의 경치가 장관입니다."),
"viewpoint": ("/ˈvjuːpɔɪnt/","명사","전망대","There is a viewpoint at the top of the hill.","언덕 꼭대기에 전망대가 있다."),
"panorama": ("/ˌpænəˈrɑːmə/","명사","파노라마, 전경","The panorama from the top is unforgettable.","꼭대기에서 보는 전경은 잊을 수 없습니다."),
"photograph": ("/ˈfoʊtəɡrɑːf/","동사","사진 찍다","May I photograph the artwork?","작품을 사진 찍어도 되나요?"),
"camera": ("/ˈkæmərə/","명사","카메라","Don't forget to bring your camera.","카메라를 챙기는 것을 잊지 마세요."),
"tourist": ("/ˈtʊərɪst/","명사","관광객","The town is very popular with tourists.","그 마을은 관광객들에게 매우 인기가 있다."),
"guided tour": ("/ˈɡaɪdɪd tʊər/","명사","가이드 투어","A guided tour is included in the ticket price.","가이드 투어가 입장료에 포함되어 있습니다."),
"audio guide": ("/ˈɔːdiəʊ ɡaɪd/","명사","오디오 가이드","You can rent an audio guide at the entrance.","입구에서 오디오 가이드를 빌릴 수 있습니다."),
"admission fee": ("/ədˈmɪʃən fiː/","명사","입장료","The admission fee is ten dollars per person.","입장료는 1인당 10달러입니다."),
"entrance ticket": ("/ˈɛntrəns ˈtɪkɪt/","명사","입장권","Buy your entrance tickets online in advance.","입장권을 온라인으로 미리 구매하세요."),
"opening hours": ("/ˈoʊpənɪŋ ˈaʊərz/","명사","운영 시간","The museum's opening hours are 9 a.m. to 6 p.m.","박물관 운영 시간은 오전 9시부터 오후 6시까지입니다."),
"closed": ("/kloʊzd/","형용사","문 닫은","The gallery is closed on Mondays.","갤러리는 월요일에 문을 닫습니다."),
"student discount": ("/ˈstjuːdənt ˈdɪskaʊnt/","명사","학생 할인","Show your student ID for a discount.","학생 할인을 받으려면 학생증을 보여주세요."),
"map": ("/mæp/","명사","지도","Pick up a free map at the information center.","안내 센터에서 무료 지도를 받으세요."),
"directions": ("/dɪˈrɛkʃənz/","명사","길 안내","Excuse me, could you give me directions to the castle?","실례합니다, 성까지 가는 길을 알려주실 수 있나요?"),
"left": ("/lɛft/","방향","왼쪽","Turn left at the traffic lights.","신호등에서 왼쪽으로 도세요."),
"right": ("/raɪt/","방향","오른쪽","The museum is on the right side of the street.","박물관은 길 오른편에 있습니다."),
"straight ahead": ("/streɪt əˈhɛd/","부사","앞으로 곧장","Go straight ahead for two blocks.","두 블록 앞으로 곧장 가세요."),
"turn": ("/tɜːrn/","동사","돌다","Turn right at the corner.","모퉁이에서 오른쪽으로 도세요."),
"block": ("/blɒk/","명사","블록","Walk two blocks north and you'll see it.","북쪽으로 두 블록 걸으면 보일 것입니다."),
"corner": ("/ˈkɔːrnər/","명사","모퉁이","The café is on the corner.","그 카페는 모퉁이에 있습니다."),
"across from": ("/əˈkrɒs frɒm/","전치사","~의 맞은편에","The hotel is across from the train station.","호텔은 기차역 맞은편에 있습니다."),
"next to": ("/nɛkst tuː/","전치사","~옆에","The pharmacy is next to the supermarket.","약국은 슈퍼마켓 옆에 있습니다."),
"nearby": ("/ˌnɪərˈbaɪ/","부사","근처에","Is there a good restaurant nearby?","근처에 좋은 식당이 있나요?"),
"distance": ("/ˈdɪstəns/","명사","거리","The hotel is within walking distance of the city center.","호텔은 도심에서 걸어서 갈 수 있는 거리에 있습니다."),
"walking": ("/ˈwɔːkɪŋ/","명사","걷기, 도보","This area is great for walking.","이 지역은 도보 여행하기에 좋습니다."),
"lost": ("/lɒst/","형용사","길을 잃은","I'm lost. Can you help me find my way?","길을 잃었습니다. 길 찾는 것을 도와주실 수 있나요?"),
"information center": ("/ˌɪnfərˈmeɪʃən ˈsɛntər/","명사","관광 안내소","Stop by the information center for maps and tips.","지도와 여행 정보를 위해 관광 안내소에 들르세요."),
"brochure": ("/ˈbroʊʃər/","명사","관광 안내 책자","Pick up a brochure at the tourist office.","관광 안내소에서 안내 책자를 가져가세요."),
"itinerary": ("/aɪˈtɪnəreri/","명사","여행 일정","Our itinerary includes a visit to the old town.","여행 일정에 구시가지 방문이 포함되어 있다."),
"booking": ("/ˈbʊkɪŋ/","명사","예약","I have a booking for the night tour.","나이트 투어를 예약했습니다."),
"police": ("/pəˈliːs/","명사","경찰","Call the police if you feel unsafe.","안전하지 않다고 느끼면 경찰을 부르세요."),
"police station": ("/pəˈliːs ˈsteɪʃən/","명사","경찰서","The nearest police station is two blocks away.","가장 가까운 경찰서는 두 블록 떨어져 있습니다."),
"hospital": ("/ˈhɒspɪtəl/","명사","병원","Take me to the nearest hospital, please.","가장 가까운 병원으로 데려다 주세요."),
"ambulance": ("/ˈæmbjʊləns/","명사","구급차","Call an ambulance immediately!","즉시 구급차를 불러주세요!"),
"pharmacy": ("/ˈfɑːrməsi/","명사","약국","I need to find a pharmacy for my medication.","약을 살 약국을 찾아야 합니다."),
"doctor": ("/ˈdɒktər/","명사","의사","I need to see a doctor as soon as possible.","가능한 빨리 의사를 만나야 합니다."),
"emergency": ("/ɪˈmɜːrdʒənsi/","명사","응급 상황","In an emergency, dial the local emergency number.","응급 상황에서는 현지 응급 번호로 전화하세요."),
"accident": ("/ˈæksɪdənt/","명사","사고","I need to report an accident.","사고를 신고해야 합니다."),
"help": ("/hɛlp/","감탄사","도와주세요!","Help! Someone stole my bag!","도와주세요! 누군가 내 가방을 훔쳐 갔어요!"),
"danger": ("/ˈdeɪndʒər/","명사","위험","Be aware of the danger signs in this area.","이 지역의 위험 표지판에 주의하세요."),
"safe": ("/seɪf/","형용사","안전한","Is it safe to walk here at night?","밤에 여기서 걷는 것이 안전한가요?"),
"embassy": ("/ˈɛmbəsi/","명사","대사관","Contact your embassy if you lose your passport.","여권을 잃어버리면 대사관에 연락하세요."),
"consulate": ("/ˈkɒnsjʊlɪt/","명사","영사관","The consulate can issue an emergency travel document.","영사관에서 긴급 여행 서류를 발급해 드릴 수 있습니다."),
"travel insurance": ("/ˈtrævəl ɪnˈʃʊərəns/","명사","여행 보험","Always buy travel insurance before your trip.","여행 전에 항상 여행 보험에 가입하세요."),
"stolen": ("/ˈstoʊlən/","형용사","도난당한","My passport has been stolen.","내 여권이 도난당했습니다."),
"first aid": ("/ˌfɜːrst ˈeɪd/","명사","응급 처치","The first-aid kit is near the reception desk.","응급 처치 키트는 접수 데스크 근처에 있습니다."),
"allergy": ("/ˈælərdʒi/","명사","알레르기","I have a bee sting allergy.","저는 벌에 쏘이면 알레르기가 있습니다."),
"medicine": ("/ˈmɛdɪsɪn/","명사","약","I forgot to pack my medicine.","약 챙기는 것을 깜빡했습니다."),
"prescription": ("/prɪˈskrɪpʃən/","명사","처방전","Do you need a prescription for this medicine?","이 약은 처방전이 필요한가요?"),
"heritage site": ("/ˈhɛrɪtɪdʒ saɪt/","명사","세계 문화유산","This area is a UNESCO heritage site.","이 지역은 유네스코 세계 문화유산입니다."),
"architecture": ("/ˈɑːrkɪtɛktʃər/","명사","건축 (양식)","The city is known for its beautiful architecture.","그 도시는 아름다운 건축 양식으로 유명합니다."),
"ancient": ("/ˈeɪnʃənt/","형용사","고대의","These ancient walls were built two thousand years ago.","이 고대 성벽은 2000년 전에 세워졌습니다."),
"historic": ("/hɪˈstɒrɪk/","형용사","역사적인","The historic district is full of interesting sites.","역사 지구는 흥미로운 명소들로 가득합니다."),
"local festival": ("/ˈloʊkəl ˈfɛstɪvəl/","명사","지역 축제","The local festival takes place every summer.","지역 축제는 매년 여름에 열립니다."),
"traditional market": ("/trəˈdɪʃənəl ˈmɑːrkɪt/","명사","전통 시장","Visit the traditional market for authentic local food.","진짜 현지 음식을 맛보려면 전통 시장을 방문하세요."),
"crowd": ("/kraʊd/","명사","군중, 붐비는 사람들","The popular attractions get very crowded on holidays.","인기 명소들은 공휴일에 매우 붐빈다."),
"queue": ("/kjuː/","명사","줄","There's a long queue to enter the museum.","박물관 입장을 위한 줄이 깁니다."),
"cable car": ("/ˈkeɪbəl kɑːr/","명사","케이블카","Take the cable car to the mountain top.","케이블카를 타고 산 정상으로 올라가세요."),
"pedestrian zone": ("/pəˈdɛstriən zoʊn/","명사","보행자 전용 구역","The old town center is a pedestrian zone.","구시가지 중심부는 보행자 전용 구역입니다."),
}


def fill_file(filepath, topic_prefix):
    with open(filepath, encoding="utf-8") as f:
        entries = json.load(f)

    updated = 0
    for entry in entries:
        word = entry["word"]
        key = word.lower()
        if key in WORDS:
            pron, pos, meaning, ex_en, ex_ko = WORDS[key]
            entry["pronunciation"] = pron
            entry["partOfSpeech"] = pos
            entry["meaning"] = meaning
            entry["exampleEn"] = ex_en
            entry["exampleKo"] = ex_ko
            updated += 1

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    total = len(entries)
    missing = total - updated
    status = "✓" if missing == 0 else "△"
    print(f"  {status} {os.path.basename(filepath)}: {updated}/{total} filled"
          + (f" ({missing} missing)" if missing else ""))
    return missing


def main():
    print("=== Fill Travel English Word Data ===\n")
    total_missing = 0
    for topic in ["airport", "hotel", "restaurant", "shopping", "sightseeing"]:
        fp = os.path.join(DATA, f"words-{topic}.json")
        total_missing += fill_file(fp, f"travel-{topic}")

    if total_missing:
        print(f"\n⚠  {total_missing} words still missing data.")
    else:
        print("\n✅ All travel-english words filled successfully!")


if __name__ == "__main__":
    main()
