#!/usr/bin/env python3
"""Seventh-pass fill: freq-L5 remaining (117) + freq-L6 remaining (120)."""
import json, glob

DICT7 = {
    # =========================================================
    # freq-L5 remaining (117)
    # =========================================================
    "ticket":      ("/ˈtɪkɪt/", "명사", "티켓, 표", "Buy a ticket online.", "온라인으로 티켓을 구매하세요."),
    "meal":        ("/miːl/", "명사", "식사", "Enjoy your meal.", "식사를 즐기세요."),
    "bag":         ("/bæɡ/", "명사", "가방", "Don't forget your bag.", "가방을 잊지 마세요."),
    "repeat":      ("/rɪˈpiːt/", "동사", "반복하다", "Please repeat that.", "다시 한 번 말씀해 주세요."),
    "equal":       ("/ˈiːkwəl/", "형용사", "동등한, 같은", "All people are equal.", "모든 사람은 평등합니다."),
    "expression":  ("/ɪkˈsprɛʃən/", "명사", "표현, 표정", "She has a kind expression.", "그녀는 친절한 표정을 하고 있습니다."),
    "plus":        ("/plʌs/", "접속사", "게다가, 더하기", "One plus one equals two.", "1 더하기 1은 2입니다."),
    "extremely":   ("/ɪkˈstriːmli/", "부사", "극도로, 매우", "It's extremely cold.", "매우 춥습니다."),
    "owner":       ("/ˈoʊnər/", "명사", "소유자, 주인", "The owner locked the door.", "주인이 문을 잠갔습니다."),
    "plane":       ("/pleɪn/", "명사", "비행기", "Take the plane.", "비행기를 타세요."),
    "commercial":  ("/kəˈmɜːrʃəl/", "형용사", "상업적인", "This is a commercial area.", "이것은 상업 지역입니다."),
    "lady":        ("/ˈleɪdi/", "명사", "숙녀, 여성", "Ladies and gentlemen.", "신사 숙녀 여러분."),
    "duty":        ("/ˈdjuːti/", "명사", "의무, 관세", "Do your duty.", "의무를 다하세요."),
    "strength":    ("/strɛŋθ/", "명사", "강점, 힘", "Know your strengths.", "자신의 강점을 파악하세요."),
    "arrange":     ("/əˈreɪndʒ/", "동사", "준비하다, 배열하다", "Arrange a meeting.", "회의를 준비하세요."),
    "scheme":      ("/skiːm/", "명사", "계획, 제도", "A new welfare scheme.", "새 복지 제도."),
    "payment":     ("/ˈpeɪmənt/", "명사", "지불, 납부", "Make a payment.", "납부하세요."),
    "unfortunately":("/ʌnˈfɔːrtʃənətli/", "부사", "불행히도, 안타깝게도", "Unfortunately, we can't help.", "안타깝게도 도와드릴 수 없습니다."),
    "brief":       ("/briːf/", "형용사", "짧은, 간략한", "Give a brief summary.", "간략한 요약을 해주세요."),
    "bird":        ("/bɜːrd/", "명사", "새", "A bird flew by.", "새 한 마리가 날아갔습니다."),
    "demonstrate": ("/ˈdɛmənstreɪt/", "동사", "시연하다, 증명하다", "Demonstrate how it works.", "어떻게 작동하는지 시연하세요."),
    "contribution":("/ˌkɒntrɪˈbjuːʃən/", "명사", "기여, 공헌", "Thank you for your contribution.", "기여해 주셔서 감사합니다."),
    "appreciate":  ("/əˈpriːʃieɪt/", "동사", "감사하다, 인정하다", "I really appreciate it.", "정말 감사합니다."),
    "chapter":     ("/ˈtʃæptər/", "명사", "장, 챕터", "Read the first chapter.", "첫 번째 장을 읽으세요."),
    "secret":      ("/ˈsiːkrɪt/", "명사", "비밀", "Can you keep a secret?", "비밀을 지킬 수 있나요?"),
    "apparently":  ("/əˈpærəntli/", "부사", "분명히, 듣기로는", "Apparently, she already left.", "듣기로는 그녀가 이미 떠났다고 합니다."),
    "novel":       ("/ˈnɒvəl/", "명사", "소설", "She wrote a bestselling novel.", "그녀는 베스트셀러 소설을 썼습니다."),
    "union":       ("/ˈjuːnjən/", "명사", "연합, 노동조합", "The union voted to strike.", "노동조합이 파업을 결의했습니다."),
    "burn":        ("/bɜːrn/", "동사", "불태우다, 타다", "Don't burn yourself.", "화상을 입지 마세요."),
    "trend":       ("/trɛnd/", "명사", "경향, 트렌드", "Follow the latest trend.", "최신 트렌드를 따라가세요."),
    "initial":     ("/ɪˈnɪʃəl/", "형용사", "초기의, 처음의", "The initial response was positive.", "초기 반응이 긍정적이었습니다."),
    "pleasure":    ("/ˈplɛʒər/", "명사", "기쁨, 즐거움", "It's my pleasure.", "제 기쁨입니다."),
    "suggestion":  ("/səˈdʒɛstʃən/", "명사", "제안, 암시", "Do you have any suggestions?", "제안이 있으신가요?"),
    "critical":    ("/ˈkrɪtɪkəl/", "형용사", "비판적인, 중요한", "This is a critical issue.", "이것은 중요한 문제입니다."),
    "gather":      ("/ˈɡæðər/", "동사", "모이다, 모으다", "We gathered for lunch.", "우리는 점심을 먹기 위해 모였습니다."),
    "mostly":      ("/ˈmoʊstli/", "부사", "주로, 대부분", "I mostly work from home.", "주로 재택근무를 합니다."),
    "earth":       ("/ɜːrθ/", "명사", "지구, 흙", "The earth is our home.", "지구는 우리의 집입니다."),
    "pop":         ("/pɒp/", "동사", "터지다, 잠깐 나타나다", "Pop in any time.", "언제든지 들르세요."),
    "essential":   ("/ɪˈsɛnʃəl/", "형용사", "필수적인", "Water is essential for life.", "물은 생명에 필수적입니다."),
    "desire":      ("/dɪˈzaɪər/", "명사", "욕구, 바람", "She has a desire to learn.", "그녀는 배우고자 하는 욕구가 있습니다."),
    "promote":     ("/prəˈmoʊt/", "동사", "홍보하다, 승진시키다", "Promote healthy habits.", "건강한 습관을 홍보하세요."),
    "currently":   ("/ˈkɜːrəntli/", "부사", "현재, 요즘", "I'm currently busy.", "저는 현재 바쁩니다."),
    "employ":      ("/ɪmˈplɔɪ/", "동사", "고용하다", "They employ 500 workers.", "그들은 500명의 직원을 고용합니다."),
    "path":        ("/pɑːθ/", "명사", "경로, 길", "Follow the path.", "경로를 따르세요."),
    "topic":       ("/ˈtɒpɪk/", "명사", "주제, 화제", "What is the topic today?", "오늘 주제가 무엇인가요?"),
    "beach":       ("/biːtʃ/", "명사", "해변, 바닷가", "Let's go to the beach.", "해변에 가자."),
    "attract":     ("/əˈtrækt/", "동사", "끌어당기다, 매력적이다", "The city attracts visitors.", "그 도시는 방문자를 끌어들입니다."),
    "engage":      ("/ɪnˈɡeɪdʒ/", "동사", "참여하다, 약혼하다", "Engage with your audience.", "청중과 교류하세요."),
    "powerful":    ("/ˈpaʊərfəl/", "형용사", "강력한, 영향력 있는", "She gave a powerful speech.", "그녀는 강력한 연설을 했습니다."),
    "flower":      ("/ˈflaʊər/", "명사", "꽃", "She loves flowers.", "그녀는 꽃을 좋아합니다."),
    "crisis":      ("/ˈkraɪsɪs/", "명사", "위기", "Handle the crisis calmly.", "위기를 침착하게 처리하세요."),
    "settle":      ("/ˈsɛtəl/", "동사", "해결하다, 정착하다", "Let's settle this now.", "이것을 지금 해결합시다."),
    "boat":        ("/boʊt/", "명사", "보트, 배", "Take the boat.", "보트를 타세요."),
    "aid":         ("/eɪd/", "명사", "도움, 지원", "First aid is important.", "응급처치가 중요합니다."),
    "fan":         ("/fæn/", "명사", "팬, 선풍기", "She is a big fan.", "그녀는 열렬한 팬입니다."),
    "kitchen":     ("/ˈkɪtʃɪn/", "명사", "주방, 부엌", "Cook in the kitchen.", "주방에서 요리하세요."),
    "twice":       ("/twaɪs/", "부사", "두 번, 두 배로", "Take it twice a day.", "하루에 두 번 복용하세요."),
    "fresh":       ("/frɛʃ/", "형용사", "신선한, 상쾌한", "Buy fresh vegetables.", "신선한 채소를 사세요."),
    "delay":       ("/dɪˈleɪ/", "명사", "지연, 연기", "Sorry for the delay.", "지연에 대해 죄송합니다."),
    "safety":      ("/ˈseɪfti/", "명사", "안전", "Safety first.", "안전이 최우선입니다."),
    "engineer":    ("/ˌɛndʒɪˈnɪər/", "명사", "엔지니어, 기사", "She is a software engineer.", "그녀는 소프트웨어 엔지니어입니다."),
    "quiet":       ("/ˈkwaɪət/", "형용사", "조용한", "Please be quiet.", "조용히 해 주세요."),
    "insurance":   ("/ɪnˈʃʊərəns/", "명사", "보험", "Have health insurance.", "건강보험에 가입하세요."),
    "nurse":       ("/nɜːrs/", "명사", "간호사", "The nurse was kind.", "간호사가 친절했습니다."),
    "divide":      ("/dɪˈvaɪd/", "동사", "나누다, 분리하다", "Divide the tasks equally.", "업무를 균등하게 나누세요."),
    "length":      ("/lɛŋθ/", "명사", "길이", "What is the length?", "길이가 어떻게 되나요?"),
    "investigation":("/ɪnˌvɛstɪˈɡeɪʃən/", "명사", "조사, 수사", "An investigation is underway.", "조사가 진행 중입니다."),
    "package":     ("/ˈpækɪdʒ/", "명사", "소포, 패키지", "The package arrived.", "소포가 도착했습니다."),
    "somewhere":   ("/ˈsʌmwɛər/", "부사", "어딘가에", "Let's go somewhere nice.", "어딘가 좋은 곳에 가자."),
    "expand":      ("/ɪkˈspænd/", "동사", "확장하다, 팽창하다", "Expand your business.", "사업을 확장하세요."),
    "commit":      ("/kəˈmɪt/", "동사", "헌신하다, 저지르다", "Commit to your goals.", "목표에 헌신하세요."),
    "obvious":     ("/ˈɒbviəs/", "형용사", "명확한, 분명한", "The answer is obvious.", "답이 명확합니다."),
    "jump":        ("/dʒʌmp/", "동사", "점프하다, 뛰어오르다", "Jump at the opportunity.", "기회를 잡으세요."),
    "weapon":      ("/ˈwɛpən/", "명사", "무기", "Lay down your weapons.", "무기를 내려놓으세요."),
    "relatively":  ("/ˈrɛlɪtɪvli/", "부사", "비교적, 상대적으로", "It's relatively easy.", "비교적 쉽습니다."),
    "host":        ("/hoʊst/", "명사", "주최자, 호스트", "She is an excellent host.", "그녀는 훌륭한 호스트입니다."),
    "winter":      ("/ˈwɪntər/", "명사", "겨울", "It's cold in winter.", "겨울에는 춥습니다."),
    "district":    ("/ˈdɪstrɪkt/", "명사", "구역, 지역", "She lives in the downtown district.", "그녀는 시내 지역에 삽니다."),
    "broad":       ("/brɔːd/", "형용사", "넓은, 폭넓은", "She has broad knowledge.", "그녀는 폭넓은 지식을 가지고 있습니다."),
    "tire":        ("/ˈtaɪər/", "명사", "타이어", "Check the tire pressure.", "타이어 압력을 확인하세요."),
    "spring":      ("/sprɪŋ/", "명사", "봄, 샘물", "Spring is beautiful.", "봄은 아름답습니다."),
    "spirit":      ("/ˈspɪrɪt/", "명사", "정신, 영혼", "Keep your spirits up.", "기운을 내세요."),
    "lunch":       ("/lʌntʃ/", "명사", "점심 식사", "Let's have lunch together.", "함께 점심을 먹자."),
    "actual":      ("/ˈæktʃuəl/", "형용사", "실제의, 진짜의", "What is the actual cost?", "실제 비용이 얼마인가요?"),
    "pool":        ("/puːl/", "명사", "수영장, 공유", "Swim in the pool.", "수영장에서 수영하세요."),
    "battle":      ("/ˈbætəl/", "명사", "전투, 싸움", "Fight the battle.", "싸움에서 이기세요."),
    "tradition":   ("/trəˈdɪʃən/", "명사", "전통", "Respect your traditions.", "전통을 존중하세요."),
    "cash":        ("/kæʃ/", "명사", "현금", "Do you accept cash?", "현금을 받으시나요?"),
    "hardly":      ("/ˈhɑːrdli/", "부사", "거의 ~않다", "I can hardly hear you.", "거의 들리지 않습니다."),
    "coach":       ("/koʊtʃ/", "명사", "코치, 감독", "The coach motivated the team.", "코치가 팀을 동기부여했습니다."),
    "experiment":  ("/ɪkˈspɛrɪmənt/", "명사", "실험", "Conduct an experiment.", "실험을 수행하세요."),
    "consideration":("/kənˌsɪdəˈreɪʃən/", "명사", "고려, 배려", "Take into consideration.", "고려하세요."),
    "strange":     ("/streɪndʒ/", "형용사", "이상한, 낯선", "That's strange.", "이상합니다."),
    "code":        ("/koʊd/", "명사", "코드, 암호", "Enter the code.", "코드를 입력하세요."),
    "possibly":    ("/ˈpɒsɪbli/", "부사", "아마도, 혹시", "Can you possibly help?", "혹시 도와줄 수 있나요?"),
    "threat":      ("/θrɛt/", "명사", "위협, 위험", "Address the threat.", "위협에 대처하세요."),
    "accident":    ("/ˈæksɪdənt/", "명사", "사고", "There was an accident.", "사고가 있었습니다."),
    "impossible":  ("/ɪmˈpɒsɪbəl/", "형용사", "불가능한", "Nothing is impossible.", "불가능한 것은 없습니다."),
    "enable":      ("/ɪˈneɪbəl/", "동사", "가능하게 하다", "This enables better communication.", "이것이 더 나은 소통을 가능하게 합니다."),
    "afraid":      ("/əˈfreɪd/", "형용사", "두려운, 무서운", "Don't be afraid.", "두려워하지 마세요."),
    "religious":   ("/rɪˈlɪdʒəs/", "형용사", "종교적인", "She is a religious person.", "그녀는 종교적인 사람입니다."),
    "cancer":      ("/ˈkænsər/", "명사", "암", "Cancer research is advancing.", "암 연구가 발전하고 있습니다."),
    "convince":    ("/kənˈvɪns/", "동사", "납득시키다, 설득하다", "Try to convince him.", "그를 설득해 보세요."),
    "vary":        ("/ˈvɛəri/", "동사", "다양하다, 변화하다", "Prices vary by region.", "가격은 지역마다 다릅니다."),
    "environmental":("/ɪnˌvaɪrənˈmɛntəl/", "형용사", "환경적인", "Environmental issues are important.", "환경 문제가 중요합니다."),
    "sun":         ("/sʌn/", "명사", "태양", "The sun is shining.", "태양이 빛나고 있습니다."),
    "blow":        ("/bloʊ/", "동사", "불다, 날리다", "The wind blows hard.", "바람이 세게 붑니다."),
    "volume":      ("/ˈvɒljuːm/", "명사", "음량, 양", "Turn up the volume.", "음량을 높이세요."),
    "location":    ("/loʊˈkeɪʃən/", "명사", "위치, 장소", "Share your location.", "위치를 공유하세요."),
    "invest":      ("/ɪnˈvɛst/", "동사", "투자하다", "Invest in your future.", "미래에 투자하세요."),
    "proceed":     ("/prəˈsiːd/", "동사", "진행하다, 나아가다", "Please proceed.", "진행해 주세요."),
    "wash":        ("/wɒʃ/", "동사", "씻다, 세탁하다", "Wash your hands.", "손을 씻으세요."),
    "actor":       ("/ˈæktər/", "명사", "배우", "He is a famous actor.", "그는 유명한 배우입니다."),
    "glad":        ("/ɡlæd/", "형용사", "기쁜, 반가운", "I'm glad to meet you.", "만나서 반갑습니다."),
    "tape":        ("/teɪp/", "명사", "테이프", "Use tape to seal it.", "테이프로 밀봉하세요."),
    "opposite":    ("/ˈɒpəzɪt/", "형용사", "반대의, 맞은편의", "Walk in the opposite direction.", "반대 방향으로 걸으세요."),
    "murder":      ("/ˈmɜːrdər/", "명사", "살인", "The murder was solved.", "살인 사건이 해결되었습니다."),
    # =========================================================
    # freq-L6 remaining (120)
    # =========================================================
    "root":        ("/ruːt/", "명사", "뿌리, 근원", "Get to the root of the problem.", "문제의 근원을 찾아보세요."),
    "factory":     ("/ˈfæktəri/", "명사", "공장", "She works at a factory.", "그녀는 공장에서 일합니다."),
    "channel":     ("/ˈtʃænəl/", "명사", "채널, 경로", "Which channel?", "어떤 채널인가요?"),
    "investigate": ("/ɪnˈvɛstɪɡeɪt/", "동사", "조사하다, 수사하다", "Please investigate the matter.", "문제를 조사해 주세요."),
    "recommendation":("/ˌrɛkəmɛnˈdeɪʃən/", "명사", "추천, 권고", "Follow the recommendation.", "추천 사항을 따르세요."),
    "rank":        ("/ræŋk/", "명사", "계급, 순위", "She reached a high rank.", "그녀는 높은 직급에 올랐습니다."),
    "typical":     ("/ˈtɪpɪkəl/", "형용사", "전형적인, 대표적인", "This is a typical example.", "이것은 전형적인 예입니다."),
    "friendly":    ("/ˈfrɛndli/", "형용사", "친절한, 우호적인", "She is very friendly.", "그녀는 매우 친절합니다."),
    "resident":    ("/ˈrɛzɪdənt/", "명사", "주민, 거주자", "Local residents protested.", "지역 주민들이 항의했습니다."),
    "provision":   ("/prəˈvɪʒən/", "명사", "공급, 조항", "There is a provision for this.", "이에 대한 조항이 있습니다."),
    "concentrate": ("/ˈkɒnsəntreɪt/", "동사", "집중하다", "Concentrate on your work.", "일에 집중하세요."),
    "plenty":      ("/ˈplɛnti/", "대명사", "충분히, 풍부하게", "There is plenty of time.", "시간이 충분히 있습니다."),
    "export":      ("/ˈɛkspɔːrt/", "동사", "수출하다", "They export goods worldwide.", "그들은 전 세계로 상품을 수출합니다."),
    "entirely":    ("/ɪnˈtaɪərli/", "부사", "완전히, 전적으로", "I entirely agree.", "전적으로 동의합니다."),
    "strongly":    ("/ˈstrɒŋli/", "부사", "강하게, 강력히", "I strongly recommend it.", "강력히 추천합니다."),
    "bridge":      ("/brɪdʒ/", "명사", "다리, 교량", "Cross the bridge.", "다리를 건너세요."),
    "consist":     ("/kənˈsɪst/", "동사", "구성되다, 이루어지다", "The team consists of 10 members.", "팀은 10명으로 구성됩니다."),
    "graduate":    ("/ˈɡrædʒuɪt/", "동사", "졸업하다", "She graduated last year.", "그녀는 작년에 졸업했습니다."),
    "brand":       ("/brænd/", "명사", "브랜드, 상표", "Which brand do you prefer?", "어떤 브랜드를 선호하시나요?"),
    "moral":       ("/ˈmɒrəl/", "형용사", "도덕적인", "Have moral values.", "도덕적 가치를 가지세요."),
    "insist":      ("/ɪnˈsɪst/", "동사", "주장하다, 고집하다", "He insists on being right.", "그는 자신이 맞다고 주장합니다."),
    "combination": ("/ˌkɒmbɪˈneɪʃən/", "명사", "조합, 결합", "A winning combination.", "승리의 조합."),
    "abuse":       ("/əˈbjuːs/", "명사", "남용, 학대", "Avoid drug abuse.", "약물 남용을 피하세요."),
    "ice":         ("/aɪs/", "명사", "얼음", "Add ice to the drink.", "음료에 얼음을 넣으세요."),
    "principal":   ("/ˈprɪnsɪpəl/", "명사", "교장, 주요 인물", "The school principal spoke.", "교장 선생님이 말씀하셨습니다."),
    "master":      ("/ˈmɑːstər/", "동사", "마스터하다, 숙달하다", "Master the basics first.", "기초를 먼저 숙달하세요."),
    "definitely":  ("/ˈdɛfɪnɪtli/", "부사", "분명히, 틀림없이", "I will definitely come.", "반드시 올 것입니다."),
    "session":     ("/ˈsɛʃən/", "명사", "세션, 회의", "Attend the morning session.", "오전 세션에 참석하세요."),
    "grade":       ("/ɡreɪd/", "명사", "등급, 학년", "She got a good grade.", "그녀는 좋은 성적을 받았습니다."),
    "predict":     ("/prɪˈdɪkt/", "동사", "예측하다", "Predict the outcome.", "결과를 예측하세요."),
    "previously":  ("/ˈpriːviəsli/", "부사", "이전에, 앞서", "As mentioned previously.", "앞서 언급했듯이."),
    "protection":  ("/prəˈtɛkʃən/", "명사", "보호", "Seek protection.", "보호를 구하세요."),
    "largely":     ("/ˈlɑːrdʒli/", "부사", "대체로, 주로", "It is largely successful.", "대체로 성공적입니다."),
    "wed":         ("/wɛd/", "동사", "결혼하다", "They were wed last year.", "그들은 작년에 결혼했습니다."),
    "rent":        ("/rɛnt/", "명사", "임대료, 렌트", "Pay the rent on time.", "제때 임대료를 내세요."),
    "shot":        ("/ʃɒt/", "명사", "총격, 사진, 시도", "Take a shot.", "한 번 해보세요."),
    "appearance":  ("/əˈpɪərəns/", "명사", "외모, 모습", "First impressions matter.", "첫인상이 중요합니다."),
    "reasonable":  ("/ˈriːzənəbəl/", "형용사", "합리적인", "That's a reasonable price.", "합리적인 가격입니다."),
    "till":        ("/tɪl/", "전치사", "~까지", "Wait till tomorrow.", "내일까지 기다리세요."),
    "theme":       ("/θiːm/", "명사", "주제, 테마", "What is the theme?", "주제가 무엇인가요?"),
    "judgment":    ("/ˈdʒʌdʒmənt/", "명사", "판단, 판결", "Use good judgment.", "좋은 판단력을 사용하세요."),
    "odd":         ("/ɒd/", "형용사", "이상한, 홀수의", "That's an odd idea.", "이상한 생각입니다."),
    "loan":        ("/loʊn/", "명사", "대출, 빌려줌", "Apply for a loan.", "대출을 신청하세요."),
    "definition":  ("/ˌdɛfɪˈnɪʃən/", "명사", "정의, 의미", "What is the definition?", "정의가 무엇인가요?"),
    "elect":       ("/ɪˈlɛkt/", "동사", "선출하다", "They elected a new leader.", "그들은 새 지도자를 선출했습니다."),
    "atmosphere":  ("/ˈætməsfɪər/", "명사", "분위기, 대기", "The atmosphere is great here.", "여기 분위기가 좋습니다."),
    "farmer":      ("/ˈfɑːrmər/", "명사", "농부", "The farmer grows crops.", "농부가 작물을 재배합니다."),
    "comparison":  ("/kəmˈpærɪsən/", "명사", "비교", "Make a comparison.", "비교를 해보세요."),
    "characteristic":("/ˌkærɪktəˈrɪstɪk/", "명사", "특성, 특징", "What are his characteristics?", "그의 특징은 무엇인가요?"),
    "license":     ("/ˈlaɪsəns/", "명사", "면허, 허가", "Show your license.", "면허를 보여 주세요."),
    "rely":        ("/rɪˈlaɪ/", "동사", "의존하다, 믿다", "You can rely on me.", "저를 믿으세요."),
    "narrow":      ("/ˈnæroʊ/", "형용사", "좁은", "The road is narrow.", "도로가 좁습니다."),
    "succeed":     ("/səkˈsiːd/", "동사", "성공하다", "Work hard to succeed.", "성공하기 위해 열심히 일하세요."),
    "identity":    ("/aɪˈdɛntɪti/", "명사", "정체성, 신원", "Protect your identity.", "신원을 보호하세요."),
    "desk":        ("/dɛsk/", "명사", "책상, 안내 데스크", "Sit at your desk.", "책상에 앉으세요."),
    "permit":      ("/pɜːrmɪt/", "동사", "허용하다, 허가하다", "Permit me to explain.", "설명할 기회를 주세요."),
    "seriously":   ("/ˈsɪəriəsli/", "부사", "진지하게, 심각하게", "Take this seriously.", "이것을 진지하게 받아들이세요."),
    "wild":        ("/waɪld/", "형용사", "야생의, 거친", "She loves wild animals.", "그녀는 야생 동물을 좋아합니다."),
    "empty":       ("/ˈɛmpti/", "형용사", "빈, 텅 빈", "The room is empty.", "방이 비어 있습니다."),
    "commission":  ("/kəˈmɪʃən/", "명사", "수수료, 위원회", "She earns a commission.", "그녀는 수수료를 받습니다."),
    "unique":      ("/juːˈniːk/", "형용사", "독특한, 유일한", "She has a unique style.", "그녀는 독특한 스타일을 가지고 있습니다."),
    "association": ("/əˌsoʊsiˈeɪʃən/", "명사", "협회, 연관", "Join the association.", "협회에 가입하세요."),
    "instrument":  ("/ˈɪnstrəmənt/", "명사", "악기, 도구", "Play an instrument.", "악기를 연주하세요."),
    "investor":    ("/ɪnˈvɛstər/", "명사", "투자자", "Attract investors.", "투자자를 유치하세요."),
    "practical":   ("/ˈpræktɪkəl/", "형용사", "실용적인", "This is a practical solution.", "이것은 실용적인 해결책입니다."),
    "tea":         ("/tiː/", "명사", "차", "Would you like some tea?", "차 드실래요?"),
    "lovely":      ("/ˈlʌvli/", "형용사", "사랑스러운, 멋진", "What a lovely day!", "정말 멋진 날이네요!"),
    "soft":        ("/sɒft/", "형용사", "부드러운, 연한", "The pillow is soft.", "베개가 부드럽습니다."),
    "row":         ("/roʊ/", "명사", "줄, 행", "Sit in the front row.", "앞줄에 앉으세요."),
    "youth":       ("/juːθ/", "명사", "청소년, 젊음", "Invest in the youth.", "청소년에 투자하세요."),
    "lock":        ("/lɒk/", "동사", "잠그다", "Lock the door.", "문을 잠그세요."),
    "fuel":        ("/fjuːəl/", "명사", "연료", "Fill up with fuel.", "연료를 가득 채우세요."),
    "expectation": ("/ˌɛkspɛkˈteɪʃən/", "명사", "기대, 예상", "Exceed expectations.", "기대를 뛰어넘으세요."),
    "employment":  ("/ɪmˈplɔɪmənt/", "명사", "고용, 취업", "Find employment.", "취업하세요."),
    "celebrate":   ("/ˈsɛlɪbreɪt/", "동사", "축하하다", "Let's celebrate!", "축하하자!"),
    "breath":      ("/brɛθ/", "명사", "숨, 호흡", "Take a deep breath.", "깊게 숨을 쉬세요."),
    "increasingly":("/ɪnˈkriːsɪŋli/", "부사", "점점 더, 갈수록", "Life is increasingly busy.", "삶이 갈수록 바빠지고 있습니다."),
    "bottle":      ("/ˈbɒtəl/", "명사", "병, 보틀", "Fill the bottle with water.", "병에 물을 채우세요."),
    "ourselves":   ("/aʊərˈsɛlvz/", "대명사", "우리 자신", "We did it ourselves.", "우리 스스로 했습니다."),
    "sheet":       ("/ʃiːt/", "명사", "시트, 종이 한 장", "Write it on this sheet.", "이 종이에 쓰세요."),
    "engine":      ("/ˈɛndʒɪn/", "명사", "엔진, 기관", "The engine needs repair.", "엔진 수리가 필요합니다."),
    "conservative":("/kənˈsɜːrvətɪv/", "형용사", "보수적인", "She has conservative values.", "그녀는 보수적인 가치관을 가지고 있습니다."),
    "journey":     ("/ˈdʒɜːrni/", "명사", "여정, 여행", "Enjoy the journey.", "여정을 즐기세요."),
    "opposition":  ("/ˌɒpəˈzɪʃən/", "명사", "반대, 야당", "Face the opposition.", "반대에 직면하세요."),
    "relief":      ("/rɪˈliːf/", "명사", "안도, 구제", "What a relief!", "정말 안도됩니다!"),
    "debt":        ("/dɛt/", "명사", "부채, 빚", "Pay off your debt.", "빚을 갚으세요."),
    "honor":       ("/ˈɒnər/", "명사", "명예, 영광", "It is an honor to meet you.", "만나서 영광입니다."),
    "outcome":     ("/ˈaʊtkʌm/", "명사", "결과, 성과", "What was the outcome?", "결과가 어떻게 됐나요?"),
    "blame":       ("/bleɪm/", "동사", "비난하다, 탓하다", "Don't blame others.", "다른 사람을 탓하지 마세요."),
    "explanation": ("/ˌɛksplɪˈneɪʃən/", "명사", "설명", "Give me an explanation.", "설명해 주세요."),
    "arise":       ("/əˈraɪz/", "동사", "발생하다, 생기다", "Problems may arise.", "문제가 발생할 수 있습니다."),
    "musical":     ("/ˈmjuːzɪkəl/", "형용사", "음악적인", "She has musical talent.", "그녀는 음악적 재능이 있습니다."),
    "recover":     ("/rɪˈkʌvər/", "동사", "회복하다, 되찾다", "She recovered quickly.", "그녀는 빨리 회복했습니다."),
    "dad":         ("/dæd/", "명사", "아빠", "My dad is a doctor.", "아빠는 의사입니다."),
    "stretch":     ("/strɛtʃ/", "동사", "뻗다, 스트레칭하다", "Stretch before exercising.", "운동 전에 스트레칭하세요."),
    "declare":     ("/dɪˈklɛər/", "동사", "선언하다, 신고하다", "Declare your income.", "소득을 신고하세요."),
    "retire":      ("/rɪˈtaɪər/", "동사", "은퇴하다", "He plans to retire at 65.", "그는 65세에 은퇴할 계획입니다."),
    "tiny":        ("/ˈtaɪni/", "형용사", "아주 작은", "It's a tiny mistake.", "아주 작은 실수입니다."),
    "careful":     ("/ˈkɛərfəl/", "형용사", "조심스러운, 신중한", "Be careful!", "조심하세요!"),
    "suitable":    ("/ˈsuːtɪbəl/", "형용사", "적합한, 적절한", "Is this suitable?", "이것이 적합한가요?"),
    "native":      ("/ˈneɪtɪv/", "형용사", "원주민의, 토착의", "She is a native speaker.", "그녀는 원어민입니다."),
    "fruit":       ("/fruːt/", "명사", "과일", "Eat fresh fruit daily.", "매일 신선한 과일을 드세요."),
    "analyze":     ("/ˈænəlaɪz/", "동사", "분석하다", "Analyze the data.", "데이터를 분석하세요."),
    "witness":     ("/ˈwɪtnɪs/", "명사", "목격자, 증인", "She was a witness.", "그녀는 목격자였습니다."),
    "mail":        ("/meɪl/", "명사", "우편, 메일", "Check your mail.", "우편물을 확인하세요."),
    "terrible":    ("/ˈtɛrɪbəl/", "형용사", "끔찍한, 심한", "What a terrible day!", "정말 끔찍한 날이네요!"),
    "researcher":  ("/rɪˈsɜːrtʃər/", "명사", "연구자", "She is a researcher.", "그녀는 연구자입니다."),
    "ordinary":    ("/ˈɔːrdɪnəri/", "형용사", "보통의, 일반적인", "It was an ordinary day.", "보통 날이었습니다."),
    "selection":   ("/sɪˈlɛkʃən/", "명사", "선택, 선발", "A wide selection.", "폭넓은 선택."),
    "anywhere":    ("/ˈɛniwɛər/", "부사", "어디든, 어디에나", "I can work anywhere.", "어디서나 일할 수 있습니다."),
    "mental":      ("/ˈmɛntəl/", "형용사", "정신적인", "Mental health matters.", "정신 건강이 중요합니다."),
    "participant": ("/pɑːrˈtɪsɪpənt/", "명사", "참가자, 참여자", "Welcome all participants.", "모든 참가자를 환영합니다."),
    "vision":      ("/ˈvɪʒən/", "명사", "시력, 비전", "Have a clear vision.", "명확한 비전을 가지세요."),
    "personality": ("/ˌpɜːrsəˈnælɪti/", "명사", "성격, 개성", "She has a great personality.", "그녀는 훌륭한 성격을 가지고 있습니다."),
    "specifically": ("/spɪˈsɪfɪkli/", "부사", "구체적으로", "Speak specifically.", "구체적으로 말씀해 주세요."),
    "fat":         ("/fæt/", "형용사", "뚱뚱한, 살찐", "Reduce fat intake.", "지방 섭취를 줄이세요."),
    "entry":       ("/ˈɛntri/", "명사", "입장, 항목", "No entry.", "입장 불가."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT7:
                    pron, pos, meaning, ex_en, ex_ko = DICT7[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more6.py ===\n")
    patch_files()
