#!/usr/bin/env python3
"""Sixth-pass fill: freq-L5 (206 words) + freq-L6 (210 words)."""
import json, glob

DICT6 = {
    # =========================================================
    # freq-L5 (206 remaining)
    # =========================================================
    "horse":       ("/hɔːrs/", "명사", "말, 경마", "She loves riding horses.", "그녀는 말 타기를 좋아합니다."),
    "excite":      ("/ɪkˈsaɪt/", "동사", "흥분시키다, 설레게 하다", "The news excited everyone.", "그 소식이 모든 사람을 흥분시켰습니다."),
    "reader":      ("/ˈriːdər/", "명사", "독자, 읽는 사람", "She is an avid reader.", "그녀는 열렬한 독자입니다."),
    "camp":        ("/kæmp/", "명사", "캠프, 야영지", "We set up camp by the lake.", "호수 옆에 캠프를 설치했습니다."),
    "email":       ("/ˈiːmeɪl/", "명사", "이메일", "Send me an email.", "이메일을 보내 주세요."),
    "advertise":   ("/ˈædvərtaɪz/", "동사", "광고하다", "They advertise on TV.", "그들은 TV에 광고합니다."),
    "surround":    ("/səˈraʊnd/", "동사", "둘러싸다, 에워싸다", "Mountains surround the city.", "산들이 도시를 둘러싸고 있습니다."),
    "gas":         ("/ɡæs/", "명사", "가스, 기름", "Don't run out of gas.", "가스를 다 쓰지 마세요."),
    "net":         ("/nɛt/", "명사", "그물, 인터넷", "Surf the net.", "인터넷을 검색하세요."),
    "cook":        ("/kʊk/", "동사", "요리하다", "She loves to cook.", "그녀는 요리하는 것을 좋아합니다."),
    "spread":      ("/sprɛd/", "동사", "퍼지다, 펴다", "The news spread quickly.", "뉴스가 빠르게 퍼졌습니다."),
    "nuclear":     ("/ˈnjuːkliər/", "형용사", "핵의, 원자력의", "Nuclear energy is controversial.", "원자력 에너지는 논쟁적입니다."),
    "scale":       ("/skeɪl/", "명사", "규모, 저울", "The scale of the project.", "프로젝트의 규모."),
    "driver":      ("/ˈdraɪvər/", "명사", "운전자, 드라이버", "The driver was careful.", "운전자가 조심했습니다."),
    "ball":        ("/bɔːl/", "명사", "공, 볼", "Kick the ball.", "공을 차세요."),
    "cry":         ("/kraɪ/", "동사", "울다, 외치다", "The baby began to cry.", "아기가 울기 시작했습니다."),
    "introduction":("/ˌɪntrəˈdʌkʃən/", "명사", "소개, 도입", "Let me make an introduction.", "소개를 해드리겠습니다."),
    "requirement": ("/rɪˈkwaɪərmənt/", "명사", "요구사항, 필요조건", "Meet all the requirements.", "모든 요구사항을 충족하세요."),
    "senior":      ("/ˈsiːniər/", "형용사", "선임의, 고참의", "She is a senior manager.", "그녀는 시니어 매니저입니다."),
    "photo":       ("/ˈfoʊtoʊ/", "명사", "사진", "Take a photo.", "사진을 찍으세요."),
    "refuse":      ("/rɪˈfjuːz/", "동사", "거부하다, 거절하다", "I refuse to give up.", "포기하기를 거부합니다."),
    "transport":   ("/ˈtrænspɔːrt/", "명사", "운송, 교통", "Public transport is affordable.", "대중교통은 저렴합니다."),
    "emerge":      ("/ɪˈmɜːrdʒ/", "동사", "나타나다, 부상하다", "New trends are emerging.", "새로운 트렌드가 부상하고 있습니다."),
    "map":         ("/mæp/", "명사", "지도", "Check the map.", "지도를 확인하세요."),
    "concept":     ("/ˈkɒnsɛpt/", "명사", "개념, 아이디어", "It's a new concept.", "새로운 개념입니다."),
    "island":      ("/ˈaɪlənd/", "명사", "섬", "She lives on an island.", "그녀는 섬에 삽니다."),
    "reform":      ("/rɪˈfɔːrm/", "동사", "개혁하다, 개선하다", "Reform the education system.", "교육 제도를 개혁하세요."),
    "neither":     ("/ˈnaɪðər/", "대명사", "어느 것도 ~않다", "Neither option is good.", "어느 선택지도 좋지 않습니다."),
    "football":    ("/ˈfʊtbɔːl/", "명사", "축구, 미식축구", "He watches football every Sunday.", "그는 매주 일요일 축구를 봅니다."),
    "survive":     ("/sərˈvaɪv/", "동사", "살아남다, 견디다", "We will survive this.", "우리는 이것을 견딜 것입니다."),
    "flight":      ("/flaɪt/", "명사", "비행, 항공편", "My flight is at noon.", "비행기가 정오에 있습니다."),
    "left":        ("/lɛft/", "명사", "왼쪽", "Turn left here.", "여기서 왼쪽으로 도세요."),
    "solve":       ("/sɒlv/", "동사", "해결하다, 풀다", "Solve the problem.", "문제를 해결하세요."),
    "neighbor":    ("/ˈneɪbər/", "명사", "이웃", "My neighbor is friendly.", "내 이웃은 친절합니다."),
    "background":  ("/ˈbækɡraʊnd/", "명사", "배경, 경력", "Tell me your background.", "배경을 말씀해 주세요."),
    "technique":   ("/tɛkˈniːk/", "명사", "기술, 기법", "She has good technique.", "그녀는 좋은 기술을 가지고 있습니다."),
    "traffic":     ("/ˈtræfɪk/", "명사", "교통, 트래픽", "Traffic is heavy today.", "오늘 교통이 혼잡합니다."),
    "improvement": ("/ɪmˈpruːvmənt/", "명사", "개선, 향상", "There is room for improvement.", "개선의 여지가 있습니다."),
    "tool":        ("/tuːl/", "명사", "도구, 수단", "This is a useful tool.", "이것은 유용한 도구입니다."),
    "consequence": ("/ˈkɒnsɪkwəns/", "명사", "결과, 결말", "Consider the consequences.", "결과를 고려하세요."),
    "circumstance":("/ˈsɜːrkəmstæns/", "명사", "상황, 환경", "Under the circumstances.", "상황을 고려할 때."),
    "smoke":       ("/smoʊk/", "명사", "연기", "I can smell smoke.", "연기 냄새가 납니다."),
    "reaction":    ("/riˈækʃən/", "명사", "반응", "What was your reaction?", "반응이 어땠나요?"),
    "rain":        ("/reɪn/", "명사", "비", "It's going to rain.", "비가 올 것입니다."),
    "busy":        ("/ˈbɪzi/", "형용사", "바쁜", "I'm very busy today.", "오늘 매우 바쁩니다."),
    "lesson":      ("/ˈlɛsən/", "명사", "수업, 교훈", "Learn your lesson.", "교훈을 얻으세요."),
    "brain":       ("/breɪn/", "명사", "뇌, 두뇌", "Use your brain.", "뇌를 사용하세요."),
    "mass":        ("/mæs/", "명사", "대중, 질량", "Mass media is powerful.", "대중 매체는 강력합니다."),
    "funny":       ("/ˈfʌni/", "형용사", "재미있는, 우스운", "That joke is funny.", "저 농담은 재미있습니다."),
    "contribute":  ("/kənˈtrɪbjuːt/", "동사", "기여하다, 기부하다", "Please contribute to the team.", "팀에 기여해 주세요."),
    "failure":     ("/ˈfeɪljər/", "명사", "실패, 고장", "Failure teaches us a lesson.", "실패는 교훈을 줍니다."),
    "schedule":    ("/ˈʃɛdjuːl/", "명사", "일정, 계획표", "Check your schedule.", "일정을 확인하세요."),
    "speaker":     ("/ˈspiːkər/", "명사", "연설가, 스피커", "She is an excellent speaker.", "그녀는 훌륭한 연설가입니다."),
    "bottom":      ("/ˈbɒtəm/", "명사", "바닥, 맨 아래", "At the bottom of the page.", "페이지 맨 아래에."),
    "adopt":       ("/əˈdɒpt/", "동사", "채택하다, 입양하다", "Adopt a new approach.", "새 접근법을 채택하세요."),
    "combine":     ("/kəmˈbaɪn/", "동사", "결합하다, 합치다", "Combine your efforts.", "노력을 합치세요."),
    "mountain":    ("/ˈmaʊntɪn/", "명사", "산", "Let's climb the mountain.", "산을 오릅시다."),
    "waste":       ("/weɪst/", "동사", "낭비하다", "Don't waste your time.", "시간을 낭비하지 마세요."),
    "hide":        ("/haɪd/", "동사", "숨다, 숨기다", "Where are you hiding?", "어디에 숨어 있나요?"),
    "marriage":    ("/ˈmærɪdʒ/", "명사", "결혼", "Their marriage is strong.", "그들의 결혼은 견고합니다."),
    "stone":       ("/stoʊn/", "명사", "돌, 석재", "The stone wall is beautiful.", "돌담이 아름답습니다."),
    "sum":         ("/sʌm/", "명사", "합계, 금액", "Calculate the sum.", "합계를 계산하세요."),
    "monitor":     ("/ˈmɒnɪtər/", "동사", "모니터링하다, 감시하다", "Monitor the progress.", "진행을 모니터링하세요."),
    "soldier":     ("/ˈsoʊldʒər/", "명사", "군인, 병사", "The soldier was brave.", "군인은 용감했습니다."),
    "finance":     ("/ˈfaɪnæns/", "명사", "재정, 금융", "Manage your finances well.", "재정을 잘 관리하세요."),
    "hate":        ("/heɪt/", "동사", "싫어하다, 혐오하다", "I hate being late.", "늦는 것을 싫어합니다."),
    "egg":         ("/ɛɡ/", "명사", "달걀, 알", "How do you like your eggs?", "달걀을 어떻게 해드릴까요?"),
    "concert":     ("/ˈkɒnsɜːrt/", "명사", "콘서트, 음악회", "I love going to concerts.", "콘서트에 가는 것을 좋아합니다."),
    "shock":       ("/ʃɒk/", "명사", "충격, 쇼크", "It came as a shock.", "충격으로 다가왔습니다."),
    "comfortable": ("/ˈkʌmftəbəl/", "형용사", "편안한", "Make yourself comfortable.", "편히 계세요."),
    "usual":       ("/ˈjuːʒuəl/", "형용사", "보통의, 평소의", "As usual, she arrived early.", "평소처럼 그녀는 일찍 도착했습니다."),
    "carefully":   ("/ˈkɛərfəli/", "부사", "조심스럽게, 신중하게", "Read carefully.", "조심스럽게 읽으세요."),
    "pack":        ("/pæk/", "동사", "짐을 싸다, 포장하다", "Pack your bags.", "짐을 싸세요."),
    "recall":      ("/rɪˈkɔːl/", "동사", "기억하다, 회수하다", "I can't recall his name.", "그의 이름이 기억나지 않습니다."),
    "wine":        ("/waɪn/", "명사", "와인", "Would you like some wine?", "와인을 드시겠어요?"),
    "camera":      ("/ˈkæmərə/", "명사", "카메라", "Take a camera.", "카메라를 가져가세요."),
    "swim":        ("/swɪm/", "동사", "수영하다", "Can you swim?", "수영할 수 있나요?"),
    "manufacture": ("/ˌmænjʊˈfæktʃər/", "동사", "제조하다, 생산하다", "They manufacture cars.", "그들은 자동차를 제조합니다."),
    "theater":     ("/ˈθɪətər/", "명사", "극장", "Let's go to the theater.", "극장에 가자."),
    "cycle":       ("/ˈsaɪkəl/", "명사", "주기, 자전거", "Break the cycle.", "주기를 끊으세요."),
    "coffee":      ("/ˈkɒfi/", "명사", "커피", "I drink coffee every morning.", "저는 매일 아침 커피를 마십니다."),
    "totally":     ("/ˈtoʊtəli/", "부사", "완전히, 전혀", "I totally understand.", "완전히 이해합니다."),
    "visitor":     ("/ˈvɪzɪtər/", "명사", "방문자, 관광객", "Welcome all visitors.", "모든 방문자를 환영합니다."),
    "freedom":     ("/ˈfriːdəm/", "명사", "자유", "Freedom is precious.", "자유는 소중합니다."),
    "construction":("/kənˈstrʌkʃən/", "명사", "건설, 공사", "The construction is ongoing.", "공사가 진행 중입니다."),
    "dear":        ("/dɪər/", "형용사", "소중한, 친애하는", "Dear customer.", "친애하는 고객 여러분."),
    "moreover":    ("/mɔːrˈoʊvər/", "부사", "더욱이, 게다가", "Moreover, the price is low.", "더욱이 가격도 저렴합니다."),
    "onto":        ("/ˈɒntuː/", "전치사", "~위로, ~에", "Step onto the platform.", "플랫폼으로 올라서세요."),
    "historical":  ("/hɪˈstɒrɪkəl/", "형용사", "역사적인", "This is a historical site.", "이것은 역사적인 장소입니다."),
    # more freq-L5
    "judge":       ("/dʒʌdʒ/", "동사", "판단하다", "Don't judge a book by its cover.", "겉모습으로 판단하지 마세요."),
    "expert":      ("/ˈɛkspɜːrt/", "명사", "전문가", "She is a language expert.", "그녀는 언어 전문가입니다."),
    "confirm":     ("/kənˈfɜːrm/", "동사", "확인하다, 확정하다", "Please confirm your booking.", "예약을 확인해 주세요."),
    "impact":      ("/ˈɪmpækt/", "명사", "영향", "It had a big impact.", "큰 영향을 미쳤습니다."),
    "option":      ("/ˈɒpʃən/", "명사", "선택, 옵션", "Choose the best option.", "최선의 선택을 하세요."),
    "hotel":       ("/hoʊˈtɛl/", "명사", "호텔", "Book a hotel room.", "호텔 방을 예약하세요."),
    "park":        ("/pɑːrk/", "동사", "주차하다", "Park the car here.", "여기에 주차하세요."),
    "mistake":     ("/mɪˈsteɪk/", "명사", "실수", "I made a mistake.", "실수를 했습니다."),
    "guess":       ("/ɡɛs/", "동사", "추측하다", "Guess the answer.", "답을 추측하세요."),
    "deliver":     ("/dɪˈlɪvər/", "동사", "배달하다", "Deliver the package.", "소포를 배달하세요."),
    "benefit":     ("/ˈbɛnɪfɪt/", "동사", "이득을 얻다", "Everyone benefits.", "모든 사람이 이득을 얻습니다."),
    "ensure":      ("/ɪnˈʃʊər/", "동사", "보장하다", "Ensure accuracy.", "정확성을 보장하세요."),
    "strategy":    ("/ˈstrætədʒi/", "명사", "전략", "Develop a strategy.", "전략을 개발하세요."),
    "maintain":    ("/meɪnˈteɪn/", "동사", "유지하다", "Maintain quality.", "품질을 유지하세요."),
    # =========================================================
    # freq-L6 (210 remaining)
    # =========================================================
    "bomb":        ("/bɒm/", "명사", "폭탄", "The bomb squad arrived.", "폭탄 처리반이 도착했습니다."),
    "council":     ("/ˈkaʊnsəl/", "명사", "의회, 위원회", "The city council met.", "시의회가 열렸습니다."),
    "anybody":     ("/ˈɛnibɒdi/", "대명사", "누구든지", "Can anybody help?", "누구든지 도와줄 수 있나요?"),
    "bedroom":     ("/ˈbɛdruːm/", "명사", "침실", "The bedroom is clean.", "침실이 깨끗합니다."),
    "basically":   ("/ˈbeɪsɪkli/", "부사", "기본적으로, 본질적으로", "It's basically correct.", "기본적으로 맞습니다."),
    "belief":      ("/bɪˈliːf/", "명사", "믿음, 신념", "It is my firm belief.", "제 확고한 믿음입니다."),
    "switch":      ("/swɪtʃ/", "동사", "바꾸다, 전환하다", "Switch to a healthier diet.", "더 건강한 식단으로 바꾸세요."),
    "tear":        ("/tɪər/", "명사", "눈물", "She wiped her tears.", "그녀는 눈물을 닦았습니다."),
    "shake":       ("/ʃeɪk/", "동사", "흔들다, 악수하다", "Shake hands with him.", "그와 악수하세요."),
    "shoe":        ("/ʃuː/", "명사", "신발", "These shoes are comfortable.", "이 신발은 편합니다."),
    "ought":       ("/ɔːt/", "조동사", "~해야 한다, 당연히 ~이다", "You ought to try harder.", "더 열심히 해야 합니다."),
    "ad":          ("/æd/", "명사", "광고", "I saw an interesting ad.", "흥미로운 광고를 봤습니다."),
    "fee":         ("/fiː/", "명사", "요금, 수수료", "There is a registration fee.", "등록비가 있습니다."),
    "hall":        ("/hɔːl/", "명사", "홀, 복도", "Meet in the hall.", "홀에서 만나세요."),
    "regulation":  ("/ˌrɛɡjʊˈleɪʃən/", "명사", "규정, 규제", "Follow the regulations.", "규정을 따르세요."),
    "escape":      ("/ɪˈskeɪp/", "동사", "탈출하다, 피하다", "We need to escape.", "탈출해야 합니다."),
    "studio":      ("/ˈstjuːdioʊ/", "명사", "스튜디오", "She works in a studio.", "그녀는 스튜디오에서 일합니다."),
    "proper":      ("/ˈprɒpər/", "형용사", "적절한, 올바른", "Use proper grammar.", "올바른 문법을 사용하세요."),
    "relax":       ("/rɪˈlæks/", "동사", "긴장을 풀다, 쉬다", "Just relax.", "그냥 쉬세요."),
    "tourist":     ("/ˈtʊərɪst/", "명사", "관광객", "The city attracts many tourists.", "그 도시는 많은 관광객을 유치합니다."),
    "component":   ("/kəmˈpoʊnənt/", "명사", "구성요소, 부품", "This is a key component.", "이것은 핵심 구성요소입니다."),
    "afford":      ("/əˈfɔːrd/", "동사", "~할 여유가 있다", "I can't afford it.", "그것을 살 여유가 없습니다."),
    "lawyer":      ("/ˈlɔɪər/", "명사", "변호사", "Consult a lawyer.", "변호사에게 상담하세요."),
    "suspect":     ("/ˈsʌspɛkt/", "동사", "의심하다", "I suspect something is wrong.", "뭔가 잘못됐다는 의심이 듭니다."),
    "cup":         ("/kʌp/", "명사", "컵, 잔", "Would you like a cup of tea?", "차 한 잔 드시겠어요?"),
    "description": ("/dɪˈskrɪpʃən/", "명사", "묘사, 설명", "Give a brief description.", "간단히 설명해 주세요."),
    "confidence":  ("/ˈkɒnfɪdəns/", "명사", "자신감, 확신", "Have confidence in yourself.", "자신감을 가지세요."),
    "industrial":  ("/ɪnˈdʌstriəl/", "형용사", "산업의", "This is an industrial area.", "이것은 산업 지역입니다."),
    "complain":    ("/kəmˈpleɪn/", "동사", "불평하다, 항의하다", "She complained about the noise.", "그녀는 소음에 대해 불평했습니다."),
    "perspective": ("/pərˈspɛktɪv/", "명사", "관점, 시각", "Consider another perspective.", "다른 관점을 고려하세요."),
    "error":       ("/ˈɛrər/", "명사", "오류, 실수", "Fix the error.", "오류를 수정하세요."),
    "arrest":      ("/əˈrɛst/", "동사", "체포하다", "The police made an arrest.", "경찰이 체포했습니다."),
    "assess":      ("/əˈsɛs/", "동사", "평가하다, 사정하다", "Assess the situation.", "상황을 평가하세요."),
    "register":    ("/ˈrɛdʒɪstər/", "동사", "등록하다", "Please register online.", "온라인으로 등록해 주세요."),
    "signal":      ("/ˈsɪɡnəl/", "명사", "신호", "Wait for the signal.", "신호를 기다리세요."),
    "finger":      ("/ˈfɪŋɡər/", "명사", "손가락", "She injured her finger.", "그녀는 손가락을 다쳤습니다."),
    "explore":     ("/ɪkˈsplɔːr/", "동사", "탐험하다, 탐구하다", "Let's explore new ideas.", "새로운 아이디어를 탐구합시다."),
    "leadership":  ("/ˈliːdərʃɪp/", "명사", "리더십, 지도력", "She shows great leadership.", "그녀는 훌륭한 리더십을 보여줍니다."),
    "commitment":  ("/kəˈmɪtmənt/", "명사", "헌신, 약속", "Show commitment to your work.", "일에 헌신하세요."),
    "wake":        ("/weɪk/", "동사", "깨다, 일어나다", "Wake up early.", "일찍 일어나세요."),
    "necessarily": ("/ˌnɛsɪˈsɛrɪli/", "부사", "반드시, 필연적으로", "Not necessarily.", "반드시 그런 것은 아닙니다."),
    "bright":      ("/braɪt/", "형용사", "밝은, 영리한", "The future looks bright.", "미래가 밝아 보입니다."),
    "frame":       ("/freɪm/", "명사", "틀, 프레임", "The picture frame is broken.", "액자가 부러졌습니다."),
    "slowly":      ("/ˈsloʊli/", "부사", "천천히", "Speak slowly, please.", "천천히 말씀해 주세요."),
    "bond":        ("/bɒnd/", "명사", "유대, 결속", "Build strong bonds.", "강한 유대를 구축하세요."),
    "hire":        ("/haɪər/", "동사", "고용하다", "We need to hire more staff.", "더 많은 직원을 고용해야 합니다."),
    "hole":        ("/hoʊl/", "명사", "구멍", "There is a hole in the roof.", "지붕에 구멍이 있습니다."),
    "tie":         ("/taɪ/", "동사", "묶다, 비기다", "Tie your shoes.", "신발 끈을 묶으세요."),
    "internal":    ("/ɪnˈtɜːrnəl/", "형용사", "내부의, 국내의", "This is an internal matter.", "이것은 내부 문제입니다."),
    "chain":       ("/tʃeɪn/", "명사", "사슬, 체인", "It's a chain reaction.", "연쇄 반응입니다."),
    "literature":  ("/ˈlɪtərɪtʃər/", "명사", "문학", "She studied English literature.", "그녀는 영문학을 공부했습니다."),
    "victim":      ("/ˈvɪktɪm/", "명사", "피해자, 희생자", "Help the victims.", "피해자들을 도우세요."),
    "threaten":    ("/ˈθrɛtən/", "동사", "위협하다", "Don't threaten others.", "다른 사람을 위협하지 마세요."),
    "division":    ("/dɪˈvɪʒən/", "명사", "분열, 부서", "She leads the sales division.", "그녀는 영업부를 이끌고 있습니다."),
    "secure":      ("/sɪˈkjʊər/", "형용사", "안전한, 보안된", "Is this connection secure?", "이 연결이 안전한가요?"),
    "amaze":       ("/əˈmeɪz/", "동사", "놀라게 하다", "Her performance amazed everyone.", "그녀의 공연이 모든 사람을 놀라게 했습니다."),
    "device":      ("/dɪˈvaɪs/", "명사", "장치, 기기", "This device is new.", "이 기기는 새것입니다."),
    "birth":       ("/bɜːrθ/", "명사", "출생, 탄생", "Happy birthday!", "생일 축하합니다!"),
    "forest":      ("/ˈfɒrɪst/", "명사", "숲, 산림", "Walk in the forest.", "숲속을 걸으세요."),
    "label":       ("/ˈleɪbəl/", "명사", "라벨, 꼬리표", "Read the label.", "라벨을 읽으세요."),
    "fellow":      ("/ˈfɛloʊ/", "명사", "동료, 친구", "He is a good fellow.", "그는 좋은 친구입니다."),
    "chemical":    ("/ˈkɛmɪkəl/", "형용사", "화학적인", "Avoid chemical exposure.", "화학물질 노출을 피하세요."),
    "capture":     ("/ˈkæptʃər/", "동사", "포착하다, 포획하다", "Capture the moment.", "순간을 포착하세요."),
    "tip":         ("/tɪp/", "명사", "팁, 조언", "Here is a useful tip.", "유용한 팁입니다."),
    "peak":        ("/piːk/", "명사", "정점, 최고점", "At the peak of her career.", "커리어의 정점에서."),
    "chairman":    ("/ˈtʃɛərmən/", "명사", "의장, 회장", "He is the chairman.", "그는 의장입니다."),
    "proportion":  ("/prəˈpɔːrʃən/", "명사", "비율, 부분", "A large proportion.", "큰 비율."),
    "ear":         ("/ɪər/", "명사", "귀", "Speak into my ear.", "제 귀에 대고 말씀해 주세요."),
    "disappear":   ("/ˌdɪsəˈpɪər/", "동사", "사라지다", "Where did it disappear?", "어디로 사라졌나요?"),
    "shout":       ("/ʃaʊt/", "동사", "소리치다", "Don't shout.", "소리치지 마세요."),
    "yard":        ("/jɑːrd/", "명사", "마당, 야드", "Play in the yard.", "마당에서 놀아요."),
    "constant":    ("/ˈkɒnstənt/", "형용사", "지속적인, 일정한", "Constant practice helps.", "꾸준한 연습이 도움이 됩니다."),
    "significantly":("/sɪɡˈnɪfɪkəntli/", "부사", "현저하게, 크게", "Sales grew significantly.", "매출이 크게 성장했습니다."),
    "hill":        ("/hɪl/", "명사", "언덕", "Walk up the hill.", "언덕을 올라가세요."),
    "considerable":("/kənˈsɪdərəbəl/", "형용사", "상당한, 많은", "She has considerable experience.", "그녀는 상당한 경험을 가지고 있습니다."),
    "instruction": ("/ɪnˈstrʌkʃən/", "명사", "지시, 사용법", "Follow the instructions.", "지시사항을 따르세요."),
    "intelligence":("/ɪnˈtɛlɪdʒəns/", "명사", "지능, 정보", "Use your intelligence.", "지능을 활용하세요."),
    "ideal":       ("/aɪˈdɪəl/", "형용사", "이상적인", "This is ideal.", "이것은 이상적입니다."),
    "folk":        ("/foʊk/", "명사", "사람들, 민속의", "Local folk songs.", "지역 민요."),
    "surely":      ("/ˈʃʊərli/", "부사", "분명히, 확실히", "Surely you understand.", "분명히 이해하시겠죠."),
    "guard":       ("/ɡɑːrd/", "명사", "경비원, 경호원", "The guard is on duty.", "경비원이 근무 중입니다."),
    "cat":         ("/kæt/", "명사", "고양이", "She has a pet cat.", "그녀는 애완 고양이가 있습니다."),
    "somewhat":    ("/ˈsʌmwɒt/", "부사", "다소, 약간", "It was somewhat difficult.", "다소 어려웠습니다."),
    "kiss":        ("/kɪs/", "동사", "키스하다, 입을 맞추다", "Kiss your loved ones.", "사랑하는 사람에게 키스하세요."),
    "presentation":("/ˌprɛzənˈteɪʃən/", "명사", "발표, 프레젠테이션", "Give a great presentation.", "훌륭한 발표를 하세요."),
    "joint":       ("/dʒɔɪnt/", "형용사", "공동의, 합동의", "This is a joint effort.", "공동 노력입니다."),
    "compete":     ("/kəmˈpiːt/", "동사", "경쟁하다", "We must compete globally.", "전 세계적으로 경쟁해야 합니다."),
    "poll":        ("/poʊl/", "명사", "여론조사, 투표", "Take part in the poll.", "여론조사에 참여하세요."),
    "weak":        ("/wiːk/", "형용사", "약한, 미약한", "The signal is weak.", "신호가 약합니다."),
    "faith":       ("/feɪθ/", "명사", "신뢰, 믿음", "Have faith in yourself.", "자신을 믿으세요."),
    # more freq-L6
    "suit":        ("/suːt/", "동사", "적합하다, 맞다", "Does this time suit you?", "이 시간이 적합한가요?"),
    "deny":        ("/dɪˈnaɪ/", "동사", "부정하다", "He denied everything.", "그는 모든 것을 부정했습니다."),
    "normally":    ("/ˈnɔːrməli/", "부사", "보통, 일반적으로", "Normally it takes an hour.", "보통 1시간 걸립니다."),
    "sight":       ("/saɪt/", "명사", "시야, 볼거리", "The sight is beautiful.", "볼거리가 아름답습니다."),
    "tonight":     ("/təˈnaɪt/", "부사", "오늘 밤", "What's on tonight?", "오늘 밤에 무엇이 있나요?"),
    "mainly":      ("/ˈmeɪnli/", "부사", "주로", "It's mainly my fault.", "주로 내 잘못입니다."),
    "afford":      ("/əˈfɔːrd/", "동사", "여유가 있다", "I can afford it now.", "이제 여유가 있습니다."),
    "domestic":    ("/dəˈmɛstɪk/", "형용사", "국내의", "Domestic flights only.", "국내선만 있습니다."),
    "load":        ("/loʊd/", "동사", "싣다, 로드하다", "Load the data.", "데이터를 로드하세요."),
    "technical":   ("/ˈtɛknɪkəl/", "형용사", "기술적인", "It's a technical error.", "기술적인 오류입니다."),
    "arrangement": ("/əˈreɪndʒmənt/", "명사", "준비, 협정", "Make arrangements.", "준비를 하세요."),
    "prison":      ("/ˈprɪzən/", "명사", "감옥", "He was sent to prison.", "그는 감옥에 보내졌습니다."),
    "acquire":     ("/əˈkwaɪər/", "동사", "획득하다", "Acquire new skills.", "새 기술을 습득하세요."),
    "fairly":      ("/ˈfɛərli/", "부사", "꽤, 공정하게", "It's fairly simple.", "꽤 간단합니다."),
    "wood":        ("/wʊd/", "명사", "나무, 목재", "The cabin is made of wood.", "오두막은 목재로 만들어졌습니다."),
    "participate": ("/pɑːrˈtɪsɪpeɪt/", "동사", "참가하다", "Please participate.", "참가해 주세요."),
    "tough":       ("/tʌf/", "형용사", "어려운, 강인한", "Life can be tough.", "인생이 힘들 수 있습니다."),
    "capacity":    ("/kəˈpæsɪti/", "명사", "용량, 수용 인원", "Full capacity.", "최대 수용량."),
    "border":      ("/ˈbɔːrdər/", "명사", "국경", "Cross the border.", "국경을 넘으세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath) as f:
            entries = json.load(f)
        patched = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT6:
                    pron, pos, meaning, ex_en, ex_ko = DICT6[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    patched += 1
        if patched:
            with open(filepath, "w") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{patched} patched")
            total += patched
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more5.py ===\n")
    patch_files()
