#!/usr/bin/env python3
"""Patch fallback entries: business-L4 (200) + business-L5 (208)"""
import json, glob

DICT17 = {
    # business-L4
    "endowment": ("/ɪnˈdaʊmənt/", "명사", "기금, 기부금", "The endowment fund grew.", "기금이 성장했다."),
    "disability": ("/ˌdɪsəˈbɪlɪti/", "명사", "장애, 장애 수당", "Disability insurance was claimed.", "장애 보험금이 청구됐다."),
    "governmental": ("/ˌɡʌvənˈmentəl/", "형용사", "정부의", "Governmental support was given.", "정부 지원이 제공됐다."),
    "competence": ("/ˈkɒmpɪtəns/", "명사", "역량, 능력", "Core competence was identified.", "핵심 역량이 확인됐다."),
    "slash": ("/slæʃ/", "동사", "대폭 삭감하다", "Costs were slashed by 30%.", "비용이 30% 대폭 삭감됐다."),
    "logistics": ("/ləˈdʒɪstɪks/", "명사", "물류", "Supply chain logistics improved.", "공급망 물류가 개선됐다."),
    "scarce": ("/skeərs/", "형용사", "희소한, 부족한", "Capital is scarce now.", "지금 자본이 희소하다."),
    "restraint": ("/rɪˈstreɪnt/", "명사", "자제, 억제", "Wage restraint was imposed.", "임금 억제가 부과됐다."),
    "follower": ("/ˈfɒloʊər/", "명사", "추종자, 후발주자", "Market followers copied the leader.", "시장 후발주자들이 선두를 따라했다."),
    "torture": ("/ˈtɔːrtʃər/", "명사", "고문, 고통", "The negotiation was torture.", "협상이 고통스러웠다."),
    "crunch": ("/krʌntʃ/", "명사", "위기, 압박", "A credit crunch occurred.", "신용 위기가 발생했다."),
    "receiver": ("/rɪˈsiːvər/", "명사", "수신자, 법정관리인", "A receiver was appointed.", "법정관리인이 선임됐다."),
    "overlap": ("/ˌoʊvərˈlæp/", "명사", "겹침, 중복", "There is overlap between divisions.", "부서 간 중복이 있다."),
    "encyclopedia": ("/ɪnˌsaɪkləˈpiːdɪə/", "명사", "백과사전", "The business encyclopedia was consulted.", "비즈니스 백과사전을 참고했다."),
    "lump": ("/lʌmp/", "명사", "일괄, 덩어리", "A lump sum was paid.", "일괄 지급됐다."),
    "momentum": ("/moʊˈmentəm/", "명사", "모멘텀, 추진력", "Growth momentum continued.", "성장 모멘텀이 계속됐다."),
    "probe": ("/proʊb/", "명사", "조사, 탐침", "A regulatory probe began.", "규제 조사가 시작됐다."),
    "aversion": ("/əˈvɜːrʒən/", "명사", "혐오, 기피", "Risk aversion increased.", "위험 기피가 증가했다."),
    "reconcile": ("/ˈrekənsaɪl/", "동사", "화해하다, 조정하다", "Accounts were reconciled.", "회계가 조정됐다."),
    "indirectly": ("/ˌɪndɪˈrektli/", "부사", "간접적으로", "Taxes affect prices indirectly.", "세금이 가격에 간접적으로 영향을 미친다."),
    "yuan": ("/juːˈɑːn/", "명사", "위안화", "The yuan appreciated.", "위안화가 절상됐다."),
    "namely": ("/ˈneɪmli/", "부사", "즉, 다시 말해", "Two options exist, namely A and B.", "두 가지 옵션이 있는데, 즉 A와 B이다."),
    "liberty": ("/ˈlɪbərti/", "명사", "자유, 자유권", "Economic liberty was enshrined.", "경제적 자유가 명시됐다."),
    "decent": ("/ˈdiːsənt/", "형용사", "적절한, 상당한", "A decent return was achieved.", "적절한 수익이 달성됐다."),
    "appetite": ("/ˈæpɪtaɪt/", "명사", "욕구, 식욕", "Investor appetite for risk grew.", "투자자 위험 선호도가 높아졌다."),
    "tobacco": ("/təˈbækoʊ/", "명사", "담배", "Tobacco stocks were sold.", "담배 주식이 매도됐다."),
    "unpopular": ("/ʌnˈpɒpjʊlər/", "형용사", "인기 없는", "The tax was unpopular.", "그 세금은 인기가 없었다."),
    "confine": ("/kənˈfaɪn/", "동사", "제한하다, 국한하다", "Growth was confined to one sector.", "성장이 한 섹터에만 국한됐다."),
    "quantify": ("/ˈkwɒntɪfaɪ/", "동사", "정량화하다", "Risk must be quantified.", "위험을 정량화해야 한다."),
    "persist": ("/pəˈsɪst/", "동사", "지속하다", "Inflation persisted.", "인플레이션이 지속됐다."),
    "gauge": ("/ɡeɪdʒ/", "동사", "측정하다, 평가하다", "Analysts gauged market conditions.", "분석가들이 시장 상황을 평가했다."),
    "corn": ("/kɔːrn/", "명사", "옥수수, 곡물", "Corn prices hit a record high.", "옥수수 가격이 사상 최고가를 기록했다."),
    "skeptical": ("/ˈskeptɪkəl/", "형용사", "회의적인", "Analysts were skeptical.", "분석가들이 회의적이었다."),
    "legislative": ("/ˈledʒɪslətɪv/", "형용사", "입법의", "Legislative changes were proposed.", "입법 변경이 제안됐다."),
    "independently": ("/ˌɪndɪˈpendəntli/", "부사", "독립적으로", "Companies operate independently.", "회사들이 독립적으로 운영된다."),
    "negligence": ("/ˈneɡlɪdʒəns/", "명사", "과실, 태만", "Negligence was alleged.", "과실이 주장됐다."),
    "determinant": ("/dɪˈtɜːrmɪnənt/", "명사", "결정 요인", "Price is a key determinant.", "가격이 핵심 결정 요인이다."),
    "redeem": ("/rɪˈdiːm/", "동사", "상환하다, 되찾다", "Bonds were redeemed at par.", "채권이 액면가로 상환됐다."),
    "tribunal": ("/traɪˈbjuːnəl/", "명사", "법정, 재판소", "A trade tribunal was convened.", "무역 재판소가 소집됐다."),
    "chunk": ("/tʃʌŋk/", "명사", "덩어리, 상당한 양", "A large chunk of budget was cut.", "예산의 상당 부분이 삭감됐다."),
    "proprietary": ("/prəˈpraɪətəri/", "형용사", "독점적인, 전매의", "Proprietary technology was sold.", "독점 기술이 매각됐다."),
    "icon": ("/ˈaɪkɒn/", "명사", "아이콘, 상징", "She became an industry icon.", "그녀는 산업의 아이콘이 됐다."),
    "intermediate": ("/ˌɪntəˈmiːdɪɪt/", "형용사", "중간의", "Intermediate goods were taxed.", "중간재에 세금이 부과됐다."),
    "steep": ("/stiːp/", "형용사", "가파른, 급격한", "A steep decline followed.", "급격한 하락이 이어졌다."),
    "acid": ("/ˈæsɪd/", "명사", "산, 산성", "Acid test measures liquidity.", "산성 테스트가 유동성을 측정한다."),
    "safeguard": ("/ˈseɪfɡɑːrd/", "명사", "보호 장치, 보호책", "Trade safeguards were imposed.", "무역 보호 장치가 부과됐다."),
    "loom": ("/luːm/", "동사", "위협적으로 다가오다", "Recession loomed large.", "경기침체가 크게 위협했다."),
    "uranium": ("/jʊˈreɪnɪəm/", "명사", "우라늄", "Uranium prices surged.", "우라늄 가격이 급등했다."),
    "deductible": ("/dɪˈdʌktɪbəl/", "형용사", "공제 가능한", "Expenses are tax deductible.", "비용이 세금 공제 가능하다."),
    "conceptual": ("/kənˈseptʃuəl/", "형용사", "개념적인", "A conceptual framework was built.", "개념적 프레임워크가 구축됐다."),
    "assault": ("/əˈsɔːlt/", "명사", "공격, 공세", "A market assault was launched.", "시장 공세가 시작됐다."),
    "optimism": ("/ˈɒptɪmɪzəm/", "명사", "낙관주의", "Optimism returned to markets.", "낙관주의가 시장에 돌아왔다."),
    "painful": ("/ˈpeɪnfəl/", "형용사", "고통스러운", "Painful reforms were enacted.", "고통스러운 개혁이 시행됐다."),
    "ruler": ("/ˈruːlər/", "명사", "지배자, 통치자", "The market ruler set prices.", "시장 지배자가 가격을 정했다."),
    "faction": ("/ˈfækʃən/", "명사", "파벌, 분파", "A board faction emerged.", "이사회 파벌이 생겨났다."),
    "null": ("/nʌl/", "형용사", "무효의, 널", "The contract was null and void.", "계약이 무효가 됐다."),
    "forge": ("/fɔːrdʒ/", "동사", "구축하다, 위조하다", "A partnership was forged.", "파트너십이 구축됐다."),
    "rig": ("/rɪɡ/", "동사", "조작하다", "Markets were rigged.", "시장이 조작됐다."),
    "accountable": ("/əˈkaʊntəbəl/", "형용사", "책임이 있는", "Executives are accountable.", "임원들이 책임이 있다."),
    "super": ("/ˈsuːpər/", "형용사", "초~, 슈퍼", "Super profits were taxed.", "초과 이익에 세금이 부과됐다."),
    "abolish": ("/əˈbɒlɪʃ/", "동사", "폐지하다", "The tax was abolished.", "그 세금이 폐지됐다."),
    "predetermine": ("/ˌpriːdɪˈtɜːrmɪn/", "동사", "미리 결정하다", "Outcomes were predetermined.", "결과가 미리 결정됐다."),
    "inherit": ("/ɪnˈherɪt/", "동사", "상속하다, 물려받다", "The CEO inherited a deficit.", "CEO가 적자를 물려받았다."),
    "analytical": ("/ˌænəˈlɪtɪkəl/", "형용사", "분석적인", "Analytical skills are valued.", "분석적 능력이 중시된다."),
    "congressional": ("/kənˈɡreʃənəl/", "형용사", "의회의", "Congressional approval was needed.", "의회 승인이 필요했다."),
    "spy": ("/spaɪ/", "명사", "스파이, 정보원", "Corporate spy was caught.", "기업 스파이가 잡혔다."),
    "fiber": ("/ˈfaɪbər/", "명사", "섬유, 광섬유", "Fiber optic cables were laid.", "광섬유 케이블이 설치됐다."),
    "stall": ("/stɔːl/", "동사", "정체하다, 미루다", "Growth stalled last quarter.", "지난 분기에 성장이 정체됐다."),
    "lure": ("/lʊər/", "동사", "유인하다", "Low taxes lure investors.", "낮은 세금이 투자자를 유인한다."),
    "populist": ("/ˈpɒpjʊlɪst/", "명사", "포퓰리스트", "Populist policies increased spending.", "포퓰리스트 정책이 지출을 늘렸다."),
    "contemplate": ("/ˈkɒntəmpleɪt/", "동사", "숙고하다", "Merger options were contemplated.", "합병 옵션이 숙고됐다."),
    "socially": ("/ˈsoʊʃəli/", "부사", "사회적으로", "Socially responsible investing grew.", "사회적 책임 투자가 성장했다."),
    "raid": ("/reɪd/", "명사", "습격, 대규모 매입", "A dawn raid on shares occurred.", "주식 새벽 매집이 발생했다."),
    "diplomacy": ("/dɪˈploʊməsi/", "명사", "외교", "Trade diplomacy was needed.", "무역 외교가 필요했다."),
    "liquidate": ("/ˈlɪkwɪdeɪt/", "동사", "청산하다", "Assets were liquidated.", "자산이 청산됐다."),
    "rocket": ("/ˈrɒkɪt/", "동사", "급등하다", "Profits rocketed.", "수익이 급등했다."),
    "debenture": ("/dɪˈbentʃər/", "명사", "사채, 무담보 채권", "Debentures were issued.", "사채가 발행됐다."),
    "collar": ("/ˈkɒlər/", "명사", "칼라, 한도", "An interest rate collar was set.", "금리 칼라가 설정됐다."),
    "outperform": ("/ˌaʊtpəˈfɔːrm/", "동사", "초과 성과를 내다", "The fund outperformed the index.", "펀드가 지수를 초과했다."),
    "optimize": ("/ˈɒptɪmaɪz/", "동사", "최적화하다", "Processes were optimized.", "프로세스가 최적화됐다."),
    "broadband": ("/ˈbrɔːdbænd/", "명사", "광대역, 브로드밴드", "Broadband investment increased.", "광대역 투자가 늘었다."),
    "reactor": ("/riˈæktər/", "명사", "반응로, 원자로", "Nuclear reactor costs rose.", "원자로 비용이 올랐다."),
    "equality": ("/ɪˈkwɒlɪti/", "명사", "평등", "Gender equality improved.", "성평등이 향상됐다."),
    "entail": ("/ɪnˈteɪl/", "동사", "수반하다", "The deal entails risk.", "거래가 위험을 수반한다."),
    "attributable": ("/əˈtrɪbjʊtəbəl/", "형용사", "~에 기인하는", "Losses attributable to fraud.", "사기에 기인한 손실."),
    "revolutionary": ("/ˌrevəˈluːʃənəri/", "형용사", "혁명적인", "Revolutionary technology emerged.", "혁명적인 기술이 등장했다."),
    "carmaker": ("/ˈkɑːrmeɪkər/", "명사", "자동차 제조사", "The carmaker cut production.", "자동차 제조사가 생산을 줄였다."),
    "discretionary": ("/dɪˈskreʃənəri/", "형용사", "임의적인, 재량적인", "Discretionary spending fell.", "재량 지출이 감소했다."),
    "reconciliation": ("/ˌrekənsɪlɪˈeɪʃən/", "명사", "화해, 조정", "Account reconciliation was done.", "회계 조정이 이루어졌다."),
    "directive": ("/dɪˈrektɪv/", "명사", "지침, 명령", "EU directives must be followed.", "EU 지침을 따라야 한다."),
    "mutually": ("/ˈmjuːtʃuəli/", "부사", "상호 간에", "The agreement is mutually beneficial.", "협정이 상호 이익이 된다."),
    "viable": ("/ˈvaɪəbəl/", "형용사", "실현 가능한, 생존 가능한", "A viable business model was found.", "실현 가능한 사업 모델이 발견됐다."),
    "subprime": ("/ˌsʌbˈpraɪm/", "형용사", "서브프라임의", "Subprime loans caused the crisis.", "서브프라임 대출이 위기를 초래했다."),
    "refusal": ("/rɪˈfjuːzəl/", "명사", "거절, 거부", "Refusal to pay was noted.", "지급 거절이 기록됐다."),
    "geographic": ("/ˌdʒiːəˈɡræfɪk/", "형용사", "지리적인", "Geographic diversification is key.", "지리적 다각화가 핵심이다."),
    "consortium": ("/kənˈsɔːrtiəm/", "명사", "컨소시엄, 연합", "A consortium bid was submitted.", "컨소시엄 입찰이 제출됐다."),
    "speculative": ("/ˈspekjʊlətɪv/", "형용사", "투기적인", "Speculative investments rose.", "투기적 투자가 증가했다."),
    "policeman": ("/pəˈliːsmən/", "명사", "경찰관", "Market policeman enforced rules.", "시장 감시자가 규정을 집행했다."),
    "historically": ("/hɪˈstɒrɪkli/", "부사", "역사적으로", "Historically, rates were lower.", "역사적으로 금리가 더 낮았다."),
    "amortize": ("/ˈæmətaɪz/", "동사", "상각하다", "The debt was amortized.", "부채가 상각됐다."),
    "exploration": ("/ˌekspləˈreɪʃən/", "명사", "탐구, 탐사", "Oil exploration costs rose.", "석유 탐사 비용이 올랐다."),
    "deliberately": ("/dɪˈlɪbərɪtli/", "부사", "의도적으로", "Prices were deliberately kept low.", "가격이 의도적으로 낮게 유지됐다."),
    "mill": ("/mɪl/", "명사", "공장, 제분소", "The steel mill closed.", "철강 공장이 문을 닫았다."),
    "loser": ("/ˈluːzər/", "명사", "패자, 손실자", "Market losers were identified.", "시장 패자들이 확인됐다."),
    "subjective": ("/səbˈdʒektɪv/", "형용사", "주관적인", "Valuations can be subjective.", "평가가 주관적일 수 있다."),
    "builder": ("/ˈbɪldər/", "명사", "건설업자", "Home builders benefited.", "주택 건설업자들이 혜택을 받았다."),
    "mainland": ("/ˈmeɪnlænd/", "명사", "본토", "Mainland China demand grew.", "본토 중국 수요가 증가했다."),
    "peaceful": ("/ˈpiːsfəl/", "형용사", "평화적인", "A peaceful transition occurred.", "평화적 전환이 이루어졌다."),
    "importantly": ("/ɪmˈpɔːrtəntli/", "부사", "중요하게", "Most importantly, margins held.", "가장 중요하게, 마진이 유지됐다."),
    "backward": ("/ˈbækwərd/", "형용사", "후진의, 역방향의", "Backward integration was pursued.", "후방 통합이 추구됐다."),
    "counterparty": ("/ˈkaʊntərpɑːrti/", "명사", "거래 상대방", "Counterparty risk was assessed.", "거래 상대방 위험이 평가됐다."),
    "overwhelm": ("/ˌoʊvərˈwelm/", "동사", "압도하다", "Demand overwhelmed supply.", "수요가 공급을 압도했다."),
    "consistency": ("/kənˈsɪstənsi/", "명사", "일관성", "Consistency in results matters.", "결과의 일관성이 중요하다."),
    "unprecedented": ("/ʌnˈpresɪdentɪd/", "형용사", "전례 없는", "Unprecedented growth was seen.", "전례 없는 성장이 목격됐다."),
    "declaration": ("/ˌdekləˈreɪʃən/", "명사", "선언", "A tax declaration was filed.", "세금 신고가 제출됐다."),
    "retention": ("/rɪˈtenʃən/", "명사", "유지, 보유", "Customer retention improved.", "고객 유지율이 향상됐다."),
    "harsh": ("/hɑːrʃ/", "형용사", "가혹한", "Harsh penalties were imposed.", "가혹한 처벌이 부과됐다."),
    "contend": ("/kənˈtend/", "동사", "주장하다, 경쟁하다", "Analysts contend rates will rise.", "분석가들은 금리가 오를 것이라고 주장한다."),
    "covariance": ("/koʊˈveərɪəns/", "명사", "공분산", "Covariance between assets matters.", "자산 간 공분산이 중요하다."),
    "jointly": ("/ˈdʒɔɪntli/", "부사", "공동으로", "Assets are jointly owned.", "자산이 공동으로 소유된다."),
    "exclusion": ("/ɪkˈskluːʒən/", "명사", "배제, 제외", "Tax exclusions were listed.", "세금 제외 항목이 나열됐다."),
    "bomber": ("/ˈbɒmər/", "명사", "폭격기", "Defense bomber contract won.", "방위 폭격기 계약을 수주했다."),
    "viewer": ("/ˈvjuːər/", "명사", "시청자, 관람자", "Viewer numbers grew.", "시청자 수가 증가했다."),
    "spur": ("/spɜːr/", "동사", "자극하다, 촉진하다", "Low rates spur investment.", "낮은 금리가 투자를 자극한다."),
    "prospectus": ("/prəˈspektəs/", "명사", "투자 설명서", "A prospectus was filed.", "투자 설명서가 제출됐다."),
    "conscious": ("/ˈkɒnʃəs/", "형용사", "의식적인, 자각하는", "Investors are cost conscious.", "투자자들이 비용을 의식한다."),
    "robot": ("/ˈroʊbɒt/", "명사", "로봇", "Robots replaced workers.", "로봇이 노동자를 대체했다."),
    "buffer": ("/ˈbʌfər/", "명사", "완충재, 버퍼", "A capital buffer was maintained.", "자본 완충재가 유지됐다."),
    "infect": ("/ɪnˈfekt/", "동사", "감염시키다, 영향을 주다", "Bad debt infected the bank.", "부실 채권이 은행에 영향을 미쳤다."),
    "formulate": ("/ˈfɔːrmjʊleɪt/", "동사", "수립하다, 만들다", "Policy was formulated.", "정책이 수립됐다."),
    "socialist": ("/ˈsoʊʃəlɪst/", "명사", "사회주의자", "Socialist policies raised taxes.", "사회주의 정책이 세금을 올렸다."),
    "browser": ("/ˈbraʊzər/", "명사", "브라우저", "A browser-based platform launched.", "브라우저 기반 플랫폼이 출시됐다."),
    "cyclical": ("/ˈsɪklɪkəl/", "형용사", "경기순환의", "Cyclical stocks outperformed.", "경기순환주가 초과 성과를 냈다."),
    "exaggerate": ("/ɪɡˈzædʒəreɪt/", "동사", "과장하다", "Risks were exaggerated.", "위험이 과장됐다."),
    "cartel": ("/kɑːrˈtel/", "명사", "카르텔", "A cartel fixed prices.", "카르텔이 가격을 담합했다."),
    "triumph": ("/ˈtraɪʌmf/", "명사", "승리, 대성공", "The deal was a triumph.", "거래가 대성공이었다."),
    "rationale": ("/ˌræʃəˈnɑːl/", "명사", "근거, 이유", "The rationale for cuts.", "삭감 근거."),
    "processor": ("/ˈprɒsesər/", "명사", "프로세서, 처리자", "A payment processor handled transactions.", "결제 처리업체가 거래를 처리했다."),
    "divert": ("/daɪˈvɜːrt/", "동사", "전환하다, 유용하다", "Funds were diverted.", "자금이 전용됐다."),
    "delegation": ("/ˌdelɪˈɡeɪʃən/", "명사", "대표단, 위임", "A trade delegation visited.", "무역 대표단이 방문했다."),
    "arguably": ("/ˈɑːrɡjʊəbli/", "부사", "아마도, 틀림없이", "It is arguably the best option.", "아마도 최선의 옵션이다."),
    "ordinate": ("/ˈɔːrdɪnɪt/", "명사", "세로좌표", "Values on the ordinate axis.", "세로좌표 축의 값들."),
    "casualty": ("/ˈkæʒuəlti/", "명사", "사상자, 피해자", "Markets were a casualty of the war.", "시장이 전쟁의 피해자가 됐다."),
    "verdict": ("/ˈvɜːrdɪkt/", "명사", "평결, 결론", "A guilty verdict was returned.", "유죄 평결이 내려졌다."),
    "dot": ("/dɒt/", "명사", "점, 닷컴", "The dot-com bubble burst.", "닷컴 버블이 터졌다."),
    "distinctive": ("/dɪˈstɪŋktɪv/", "형용사", "뚜렷한, 독특한", "A distinctive brand identity.", "뚜렷한 브랜드 아이덴티티."),
    "inflationary": ("/ɪnˈfleɪʃənəri/", "형용사", "인플레이션을 유발하는", "Inflationary pressure increased.", "인플레이션 압력이 증가했다."),
    "tort": ("/tɔːrt/", "명사", "불법행위", "Tort liability was established.", "불법행위 책임이 확정됐다."),
    "positively": ("/ˈpɒzɪtɪvli/", "부사", "긍정적으로", "Markets reacted positively.", "시장이 긍정적으로 반응했다."),
    "constituency": ("/kənˈstɪtʃuənsi/", "명사", "선거구, 지지층", "The business constituency voted.", "비즈니스 지지층이 투표했다."),
    "explosion": ("/ɪkˈsplouʒən/", "명사", "폭발, 급증", "An explosion of demand occurred.", "수요 급증이 발생했다."),
    "liberalization": ("/ˌlɪbərəlaɪˈzeɪʃən/", "명사", "자유화", "Trade liberalization expanded.", "무역 자유화가 확대됐다."),
    "buyout": ("/ˈbaɪaʊt/", "명사", "인수, 바이아웃", "A leveraged buyout was completed.", "차입 인수가 완료됐다."),
    "separation": ("/ˌsepəˈreɪʃən/", "명사", "분리", "The separation of duties.", "직무 분리."),
    "dissolve": ("/dɪˈzɒlv/", "동사", "해산하다, 녹이다", "The partnership was dissolved.", "파트너십이 해산됐다."),
    "remarkably": ("/rɪˈmɑːrkəbli/", "부사", "놀랍게도", "Results improved remarkably.", "결과가 놀랍게도 개선됐다."),
    "spark": ("/spɑːrk/", "동사", "불러일으키다", "The news sparked a rally.", "소식이 반등을 불러일으켰다."),
    "migration": ("/maɪˈɡreɪʃən/", "명사", "이주, 이동", "Data migration was completed.", "데이터 이동이 완료됐다."),
    "dip": ("/dɪp/", "명사", "소폭 하락", "A brief dip in prices.", "가격의 소폭 하락."),
    "slogan": ("/ˈsloʊɡən/", "명사", "슬로건, 구호", "A catchy slogan boosted sales.", "인상적인 슬로건이 판매를 높였다."),
    "competitiveness": ("/kəmˈpetɪtɪvnəs/", "명사", "경쟁력", "Export competitiveness declined.", "수출 경쟁력이 하락했다."),
    "inclusion": ("/ɪnˈkluːʒən/", "명사", "포용, 포함", "Financial inclusion improved.", "금융 포용이 향상됐다."),
    "copper": ("/ˈkɒpər/", "명사", "구리", "Copper prices rose sharply.", "구리 가격이 급등했다."),
    "poison": ("/ˈpɔɪzən/", "명사", "독약", "A poison pill defense was used.", "독소 조항 방어가 사용됐다."),
    "justification": ("/ˌdʒʌstɪfɪˈkeɪʃən/", "명사", "정당화, 근거", "No justification was given.", "어떤 근거도 제시되지 않았다."),
    "outright": ("/ˈaʊtraɪt/", "형용사", "완전한, 노골적인", "An outright majority was won.", "완전한 과반수를 얻었다."),
    "stance": ("/stæns/", "명사", "입장, 태도", "The hawkish stance continued.", "매파적 입장이 계속됐다."),
    "fringe": ("/frɪndʒ/", "명사", "변두리, 부가 혜택", "Fringe benefits were cut.", "부가 혜택이 삭감됐다."),
    "bitter": ("/ˈbɪtər/", "형용사", "쓴, 격렬한", "A bitter takeover battle.", "격렬한 인수 전쟁."),
    "wheat": ("/wiːt/", "명사", "밀", "Wheat futures rose.", "밀 선물이 올랐다."),
    "hostility": ("/hɒˈstɪlɪti/", "명사", "적대감, 적의", "Board hostility was intense.", "이사회 적대감이 강했다."),
    "enlargement": ("/ɪnˈlɑːrdʒmənt/", "명사", "확대, 확장", "EU enlargement continued.", "EU 확대가 계속됐다."),
    "hub": ("/hʌb/", "명사", "허브, 중심지", "Singapore is a financial hub.", "싱가포르는 금융 허브이다."),
    "trim": ("/trɪm/", "동사", "삭감하다, 줄이다", "Costs were trimmed.", "비용이 삭감됐다."),
    "lesser": ("/ˈlesər/", "형용사", "덜한, 하위의", "A lesser evil was chosen.", "덜 나쁜 것이 선택됐다."),
    "republic": ("/rɪˈpʌblɪk/", "명사", "공화국", "The republic issued bonds.", "공화국이 채권을 발행했다."),
    "forthcoming": ("/ˌfɔːrθˈkʌmɪŋ/", "형용사", "곧 있을, 예정된", "Forthcoming earnings were positive.", "예정된 실적이 긍정적이었다."),
    "denounce": ("/dɪˈnaʊns/", "동사", "비난하다, 규탄하다", "The policy was denounced.", "정책이 규탄됐다."),
    "artificial": ("/ˌɑːrtɪˈfɪʃəl/", "형용사", "인공적인", "Artificial intelligence transformed finance.", "인공지능이 금융을 변화시켰다."),
    "trait": ("/treɪt/", "명사", "특성, 특징", "Leadership traits were assessed.", "리더십 특성이 평가됐다."),
    "protester": ("/prəˈtestər/", "명사", "시위자", "Protesters blocked the entrance.", "시위자들이 입구를 막았다."),
    "portray": ("/pɔːrˈtreɪ/", "동사", "묘사하다, 나타내다", "Media portrayed losses unfairly.", "미디어가 손실을 불공정하게 묘사했다."),
    "echo": ("/ˈekoʊ/", "동사", "반향하다, 되풀이하다", "The speech echoed concerns.", "연설이 우려를 반영했다."),
    "haul": ("/hɔːl/", "명사", "수익, 기간", "Over the long haul, returns improve.", "장기간에 걸쳐 수익이 개선된다."),
    "financially": ("/faɪˈnænʃəli/", "부사", "재정적으로", "The firm is financially sound.", "회사가 재정적으로 건전하다."),
    "maximization": ("/ˌmæksɪmaɪˈzeɪʃən/", "명사", "극대화", "Profit maximization is the goal.", "이익 극대화가 목표이다."),
    "bureaucrat": ("/ˈbjʊərəkræt/", "명사", "관료", "Bureaucrats delayed approvals.", "관료들이 승인을 늦췄다."),
    "competency": ("/ˈkɒmpɪtənsi/", "명사", "역량, 능력", "Core competency analysis done.", "핵심 역량 분석이 이루어졌다."),
    "dissolution": ("/ˌdɪsəˈluːʃən/", "명사", "해산, 해체", "Company dissolution was ordered.", "회사 해산이 명령됐다."),
    "distortion": ("/dɪˈstɔːrʃən/", "명사", "왜곡", "Market distortions were corrected.", "시장 왜곡이 수정됐다."),
    "continually": ("/kənˈtɪnjuəli/", "부사", "계속적으로", "Prices continually increased.", "가격이 계속적으로 증가했다."),
    "coordination": ("/koʊˌɔːrdɪˈneɪʃən/", "명사", "조율, 조정", "Policy coordination was needed.", "정책 조율이 필요했다."),
    "awkward": ("/ˈɔːkwərd/", "형용사", "어색한, 불편한", "An awkward silence followed.", "어색한 침묵이 이어졌다."),
    "slack": ("/slæk/", "명사", "여유, 느슨함", "Economic slack was evident.", "경제적 여유가 명백했다."),
    "drift": ("/drɪft/", "동사", "표류하다, 서서히 변하다", "Rates drifted lower.", "금리가 서서히 낮아졌다."),
    "vaccine": ("/ˈvæksiːn/", "명사", "백신", "Vaccine stocks surged.", "백신 주식이 급등했다."),
    "particle": ("/ˈpɑːrtɪkəl/", "명사", "입자", "Fine particle emissions fell.", "미세 입자 배출이 줄었다."),
    "emergence": ("/ɪˈmɜːrdʒəns/", "명사", "출현, 부상", "The emergence of fintech.", "핀테크의 부상."),
    "interference": ("/ˌɪntəˈfɪərəns/", "명사", "간섭", "Government interference grew.", "정부 간섭이 증가했다."),
    "indifference": ("/ɪnˈdɪfərəns/", "명사", "무관심", "Market indifference to the news.", "소식에 대한 시장 무관심."),
    # business-L5
    "petty": ("/ˈpeti/", "형용사", "사소한, 하찮은", "Petty cash was misused.", "소액 현금이 남용됐다."),
    "convergence": ("/kənˈvɜːrdʒəns/", "명사", "수렴, 융합", "Industry convergence continued.", "산업 융합이 계속됐다."),
    "worsen": ("/ˈwɜːrsən/", "동사", "악화되다", "Conditions worsened sharply.", "상황이 크게 악화됐다."),
    "rejection": ("/rɪˈdʒekʃən/", "명사", "거절, 기각", "The bid faced rejection.", "입찰이 기각됐다."),
    "reorganization": ("/ˌriːˌɔːrɡənaɪˈzeɪʃən/", "명사", "구조 재편", "A corporate reorganization began.", "기업 구조 재편이 시작됐다."),
    "mitigate": ("/ˈmɪtɪɡeɪt/", "동사", "완화하다", "Risks were mitigated.", "위험이 완화됐다."),
    "successive": ("/səkˈsesɪv/", "형용사", "연속적인", "Successive losses alarmed investors.", "연속적인 손실이 투자자들을 놀라게 했다."),
    "blend": ("/blend/", "명사", "혼합", "A blend of strategies was used.", "전략의 혼합이 사용됐다."),
    "simplicity": ("/sɪmˈplɪsɪti/", "명사", "단순성", "Simplicity drives good design.", "단순성이 좋은 디자인을 이끈다."),
    "static": ("/ˈstætɪk/", "형용사", "정적인, 변화 없는", "The market remained static.", "시장이 정적인 상태를 유지했다."),
    "deregulation": ("/ˌdiːˌreɡjʊˈleɪʃən/", "명사", "규제 완화", "Deregulation boosted competition.", "규제 완화가 경쟁을 촉진했다."),
    "computerize": ("/kəmˈpjuːtəraɪz/", "동사", "전산화하다", "Records were computerized.", "기록이 전산화됐다."),
    "succession": ("/səkˈseʃən/", "명사", "계승, 승계", "CEO succession was planned.", "CEO 승계가 계획됐다."),
    "royalty": ("/ˈrɔɪəlti/", "명사", "로열티, 사용료", "Royalties were paid monthly.", "로열티가 매월 지급됐다."),
    "classroom": ("/ˈklɑːsruːm/", "명사", "교실", "Online classroom usage grew.", "온라인 교실 이용이 증가했다."),
    "spectacular": ("/spekˈtækjʊlər/", "형용사", "놀라운, 훌륭한", "Spectacular growth was reported.", "놀라운 성장이 보고됐다."),
    "macro": ("/ˈmækroʊ/", "형용사", "거시적인", "Macro risks are rising.", "거시적 위험이 증가하고 있다."),
    "flourish": ("/ˈflʌrɪʃ/", "동사", "번성하다", "Small firms flourished.", "소기업들이 번성했다."),
    "insurgent": ("/ɪnˈsɜːrdʒənt/", "명사", "반군, 반란자", "Insurgent activity disrupted supply.", "반군 활동이 공급을 방해했다."),
    "script": ("/skrɪpt/", "명사", "각본, 스크립트", "The sales script was updated.", "영업 스크립트가 업데이트됐다."),
    "relevance": ("/ˈreləvəns/", "명사", "관련성, 타당성", "Market relevance was questioned.", "시장 관련성이 의문시됐다."),
    "complement": ("/ˈkɒmplɪment/", "명사", "보완물", "The product is a complement.", "제품이 보완물이다."),
    "oral": ("/ˈɔːrəl/", "형용사", "구두의, 구술의", "An oral agreement was made.", "구두 합의가 이루어졌다."),
    "setup": ("/ˈsetʌp/", "명사", "설정, 구성", "The setup costs were high.", "설정 비용이 높았다."),
    "notable": ("/ˈnoʊtəbəl/", "형용사", "주목할 만한", "Notable gains were made.", "주목할 만한 성과가 이루어졌다."),
    "tranche": ("/trɑːnʃ/", "명사", "트란쉐, 분할 발행", "The first tranche was sold.", "첫 번째 트란쉐가 매각됐다."),
    "numerical": ("/njuːˈmerɪkəl/", "형용사", "수치의, 수량의", "Numerical targets were set.", "수치 목표가 설정됐다."),
    "policymaker": ("/ˈpɒlɪsiˌmeɪkər/", "명사", "정책 입안자", "Policymakers met to discuss rates.", "정책 입안자들이 금리 논의에 모였다."),
    "technically": ("/ˈteknɪkli/", "부사", "기술적으로", "Technically, they defaulted.", "기술적으로는 채무불이행이다."),
    "organ": ("/ˈɔːrɡən/", "명사", "기관, 조직", "A regulatory organ was created.", "규제 기관이 설립됐다."),
    "cheat": ("/tʃiːt/", "동사", "속이다", "Companies cheated on taxes.", "기업들이 세금을 속였다."),
    "utilization": ("/ˌjuːtɪlaɪˈzeɪʃən/", "명사", "활용률", "Capacity utilization rose.", "설비 활용률이 올랐다."),
    "tumble": ("/ˈtʌmbəl/", "동사", "급락하다", "Stocks tumbled on the news.", "주가가 소식에 급락했다."),
    "baseline": ("/ˈbeɪslaɪn/", "명사", "기준선, 기초치", "Baseline data was established.", "기준 데이터가 확립됐다."),
    "template": ("/ˈtemplɪt/", "명사", "템플릿, 틀", "A reporting template was created.", "보고 템플릿이 만들어졌다."),
    "instability": ("/ˌɪnstəˈbɪlɪti/", "명사", "불안정성", "Political instability hurt markets.", "정치적 불안정이 시장을 해쳤다."),
    "obituary": ("/əˈbɪtʃuəri/", "명사", "부고, 사망 기사", "An industry obituary was written.", "산업 부고가 쓰였다."),
    "peso": ("/ˈpeɪsoʊ/", "명사", "페소", "The peso weakened sharply.", "페소가 크게 약세를 보였다."),
    "denominate": ("/dɪˈnɒmɪneɪt/", "동사", "~표시로 나타내다", "Bonds denominated in dollars.", "달러 표시 채권."),
    "shortfall": ("/ˈʃɔːrtfɔːl/", "명사", "부족분, 적자", "A revenue shortfall emerged.", "수익 부족분이 발생했다."),
    "originate": ("/əˈrɪdʒɪneɪt/", "동사", "발생하다, 시작되다", "The loan was originated locally.", "대출이 현지에서 시작됐다."),
    "bureaucratic": ("/ˌbjʊərəˈkrætɪk/", "형용사", "관료적인", "Bureaucratic red tape slows deals.", "관료적 형식주의가 거래를 늦춘다."),
    "stochastic": ("/stəˈkæstɪk/", "형용사", "확률적인", "Stochastic models were used.", "확률적 모델이 사용됐다."),
    "kidnap": ("/ˈkɪdnæp/", "동사", "납치하다", "A CEO was kidnapped.", "CEO가 납치됐다."),
    "prevention": ("/prɪˈvenʃən/", "명사", "예방", "Fraud prevention improved.", "사기 예방이 향상됐다."),
    "redundancy": ("/rɪˈdʌndənsi/", "명사", "잉여 인원, 정리해고", "Redundancies were announced.", "정리해고가 발표됐다."),
    "dictator": ("/ˈdɪkteɪtər/", "명사", "독재자", "The market dictator set prices.", "시장 독재자가 가격을 정했다."),
    "dual": ("/djuːəl/", "형용사", "이중의", "A dual listing was planned.", "이중 상장이 계획됐다."),
    "brick": ("/brɪk/", "명사", "벽돌, 오프라인 매장", "Brick and mortar stores declined.", "오프라인 매장이 감소했다."),
    "internally": ("/ɪnˈtɜːrnəli/", "부사", "내부적으로", "Promotions were handled internally.", "승진이 내부적으로 처리됐다."),
    "erode": ("/ɪˈroʊd/", "동사", "침식하다, 약화시키다", "Profits eroded over time.", "수익이 시간이 지나면서 약화됐다."),
    "refinance": ("/ˌriːfaɪˈnæns/", "동사", "차환하다", "The debt was refinanced.", "부채가 차환됐다."),
    "tribal": ("/ˈtraɪbəl/", "형용사", "부족의", "Tribal conflicts disrupted supply.", "부족 갈등이 공급을 방해했다."),
    "empower": ("/ɪmˈpaʊər/", "동사", "권한을 부여하다", "Employees were empowered.", "직원들에게 권한이 부여됐다."),
    "oversight": ("/ˈoʊvərsaɪt/", "명사", "감독, 실수", "Regulatory oversight increased.", "규제 감독이 강화됐다."),
    "transparent": ("/trænsˈpærənt/", "형용사", "투명한", "Reporting must be transparent.", "보고가 투명해야 한다."),
    "predictor": ("/prɪˈdɪktər/", "명사", "예측 변수", "GDP is a strong predictor.", "GDP가 강력한 예측 변수이다."),
    "dominance": ("/ˈdɒmɪnəns/", "명사", "우세, 지배력", "Market dominance was achieved.", "시장 지배력이 달성됐다."),
    "segmentation": ("/ˌseɡmenˈteɪʃən/", "명사", "세분화", "Market segmentation was key.", "시장 세분화가 핵심이었다."),
    "hugely": ("/ˈhjuːdʒli/", "부사", "엄청나게", "The deal was hugely profitable.", "거래가 엄청나게 수익성이 있었다."),
    "arbitrary": ("/ˈɑːrbɪtrəri/", "형용사", "임의적인", "Arbitrary decisions hurt morale.", "임의적인 결정이 사기를 해쳤다."),
    "seemingly": ("/ˈsiːmɪŋli/", "부사", "겉보기에는", "Seemingly minor risks accumulated.", "겉보기에는 사소한 위험이 누적됐다."),
    "wholesaler": ("/ˈhoʊlseɪlər/", "명사", "도매업자", "Wholesalers cut margins.", "도매업자들이 마진을 줄였다."),
    "renewable": ("/rɪˈnjuːəbəl/", "형용사", "재생 가능한", "Renewable energy investment grew.", "재생에너지 투자가 증가했다."),
    "bilateral": ("/ˌbaɪˈlætərəl/", "형용사", "양자 간의", "A bilateral trade deal was signed.", "양자 무역 협정이 체결됐다."),
    "cotton": ("/ˈkɒtən/", "명사", "면화", "Cotton futures fell.", "면화 선물이 하락했다."),
    "intensity": ("/ɪnˈtensɪti/", "명사", "강도, 집중도", "Competition intensity rose.", "경쟁 강도가 높아졌다."),
    "routinely": ("/ruːˈtiːnli/", "부사", "일상적으로", "Audits are routinely performed.", "감사가 일상적으로 수행된다."),
    "displace": ("/dɪˈspleɪs/", "동사", "대체하다, 몰아내다", "Automation displaced workers.", "자동화가 노동자를 대체했다."),
    "immune": ("/ɪˈmjuːn/", "형용사", "면역이 있는, 영향받지 않는", "No sector is immune to risk.", "어떤 섹터도 위험에서 면역이 없다."),
    "obscure": ("/əbˈskjʊər/", "형용사", "모호한, 잘 알려지지 않은", "Obscure accounting rules hid losses.", "모호한 회계 규정이 손실을 감췄다."),
    "mobility": ("/moʊˈbɪlɪti/", "명사", "이동성, 유동성", "Labor mobility increased.", "노동 이동성이 증가했다."),
    "precedent": ("/ˈpresɪdənt/", "명사", "선례", "A legal precedent was set.", "법적 선례가 세워졌다."),
    "elaborate": ("/ɪˈlæbərɪt/", "형용사", "정교한", "An elaborate scheme was uncovered.", "정교한 계획이 드러났다."),
    "reprint": ("/ˌriːˈprɪnt/", "동사", "재인쇄하다", "The report was reprinted.", "보고서가 재인쇄됐다."),
    "bull": ("/bʊl/", "명사", "강세장, 황소", "A bull market emerged.", "강세장이 나타났다."),
    "clone": ("/kloʊn/", "동사", "복제하다", "Products were cloned cheaply.", "제품이 저렴하게 복제됐다."),
    "extremist": ("/ɪkˈstriːmɪst/", "명사", "극단주의자", "Extremist groups affected markets.", "극단주의 단체들이 시장에 영향을 미쳤다."),
    "peg": ("/peɡ/", "명사", "고정환율, 못", "The currency peg was maintained.", "통화 고정환율이 유지됐다."),
    "idle": ("/ˈaɪdəl/", "형용사", "유휴의, 놀고 있는", "Idle capacity was a problem.", "유휴 설비가 문제였다."),
    "allegedly": ("/əˈledʒɪdli/", "부사", "주장에 따르면", "Funds were allegedly misused.", "자금이 주장에 따르면 남용됐다."),
    "annualize": ("/ˈænjʊəlaɪz/", "동사", "연율화하다", "Returns were annualized.", "수익이 연율화됐다."),
    "turmoil": ("/ˈtɜːrmɔɪl/", "명사", "혼란, 격동", "Market turmoil erupted.", "시장 혼란이 터졌다."),
    "reinforcement": ("/ˌriːɪnˈfɔːrsmənt/", "명사", "강화, 보강", "Positive reinforcement helped.", "긍정적 강화가 도움이 됐다."),
    "wary": ("/ˈweəri/", "형용사", "경계하는", "Investors are wary of risk.", "투자자들이 위험을 경계한다."),
    "credible": ("/ˈkredɪbəl/", "형용사", "신뢰할 수 있는", "A credible plan was needed.", "신뢰할 수 있는 계획이 필요했다."),
    "woe": ("/woʊ/", "명사", "불행, 고통", "Financial woes continued.", "재정적 고통이 계속됐다."),
    "capita": ("/ˈkæpɪtə/", "명사", "일인당", "GDP per capita rose.", "일인당 GDP가 올랐다."),
    "underestimate": ("/ˌʌndərˈestɪmeɪt/", "동사", "과소평가하다", "Risks were underestimated.", "위험이 과소평가됐다."),
    "tolerate": ("/ˈtɒləreɪt/", "동사", "참다, 견디다", "No misconduct was tolerated.", "어떤 비위도 용납되지 않았다."),
    "casino": ("/kəˈsiːnoʊ/", "명사", "카지노", "Financial markets as casino.", "도박판 같은 금융 시장."),
    "downside": ("/ˈdaʊnsaɪd/", "명사", "하방 위험, 단점", "The downside risk is limited.", "하방 위험이 제한적이다."),
    "fragile": ("/ˈfrædʒaɪl/", "형용사", "취약한, 깨지기 쉬운", "The recovery is fragile.", "회복이 취약하다."),
    "invade": ("/ɪnˈveɪd/", "동사", "침략하다, 침입하다", "New firms invaded the market.", "새 기업들이 시장에 침입했다."),
    "steam": ("/stiːm/", "명사", "기세, 힘", "The economy lost steam.", "경제가 기세를 잃었다."),
    "subtle": ("/ˈsʌtəl/", "형용사", "미묘한", "Subtle changes in prices.", "가격의 미묘한 변화."),
    "hydrogen": ("/ˈhaɪdrədʒən/", "명사", "수소", "Hydrogen fuel investment surged.", "수소 연료 투자가 급증했다."),
    "replicate": ("/ˈreplɪkeɪt/", "동사", "복제하다, 재현하다", "The model was replicated.", "모델이 재현됐다."),
    "crush": ("/krʌʃ/", "동사", "압도하다, 뭉개다", "Competition crushed margins.", "경쟁이 마진을 압도했다."),
    "thereafter": ("/ˌðeərˈæftər/", "부사", "그 이후에", "Rates fell and thereafter rose.", "금리가 하락하고 그 이후에 올랐다."),
    "breakthrough": ("/ˈbreɪkθruː/", "명사", "돌파구", "A technology breakthrough occurred.", "기술 돌파구가 생겼다."),
    "rhetoric": ("/ˈretərɪk/", "명사", "수사, 언변", "Trade rhetoric escalated.", "무역 언변이 고조됐다."),
    "delta": ("/ˈdeltə/", "명사", "델타, 변화량", "Option delta was calculated.", "옵션 델타가 계산됐다."),
    "marketable": ("/ˈmɑːrkɪtəbəl/", "형용사", "시장성 있는", "Marketable securities were sold.", "시장성 있는 증권이 매각됐다."),
    "conjunction": ("/kənˈdʒʌŋkʃən/", "명사", "결합, 접속사", "In conjunction with partners.", "파트너들과 함께."),
    "overhaul": ("/ˈoʊvərhɔːl/", "명사", "전면 개편", "A system overhaul was needed.", "시스템 전면 개편이 필요했다."),
    "sensor": ("/ˈsensər/", "명사", "센서", "IoT sensor data was analyzed.", "IoT 센서 데이터가 분석됐다."),
    "doubtful": ("/ˈdaʊtfəl/", "형용사", "의심스러운, 불확실한", "Doubtful debts were written off.", "의심스러운 채권이 대손 처리됐다."),
    "ideological": ("/ˌaɪdɪəˈlɒdʒɪkəl/", "형용사", "이념적인", "Ideological differences emerged.", "이념적 차이가 드러났다."),
    "grasp": ("/ɡrɑːsp/", "동사", "파악하다, 이해하다", "Analysts grasped the implications.", "분석가들이 함의를 파악했다."),
    "injection": ("/ɪnˈdʒekʃən/", "명사", "주입, 투입", "A cash injection was needed.", "현금 투입이 필요했다."),
    "bracket": ("/ˈbrækɪt/", "명사", "범주, 구간", "The tax bracket increased.", "세금 구간이 증가했다."),
    "outrage": ("/ˈaʊtreɪdʒ/", "명사", "분노", "Public outrage followed.", "공분이 이어졌다."),
    "hurdle": ("/ˈhɜːrdəl/", "명사", "장애물, 기준 수익률", "The hurdle rate is 8%.", "기준 수익률이 8%이다."),
    "coincide": ("/ˌkoʊɪnˈsaɪd/", "동사", "일치하다", "The dates coincide.", "날짜가 일치한다."),
    "commentator": ("/ˈkɒmənteɪtər/", "명사", "논평가", "Market commentators disagreed.", "시장 논평가들이 의견을 달리했다."),
    "premier": ("/ˈprɪmɪər/", "명사", "수상, 총리", "The premier announced reforms.", "수상이 개혁을 발표했다."),
    "insurgency": ("/ɪnˈsɜːrdʒənsi/", "명사", "반란, 봉기", "Insurgency disrupted supply lines.", "반란이 공급망을 방해했다."),
    "incline": ("/ɪnˈklaɪn/", "동사", "기울어지다, 경향이 있다", "Markets inclined upward.", "시장이 상향으로 기울었다."),
    "averse": ("/əˈvɜːrs/", "형용사", "싫어하는, 기피하는", "Investors are risk averse.", "투자자들이 위험을 기피한다."),
    "enlarge": ("/ɪnˈlɑːrdʒ/", "동사", "확대하다", "The fund was enlarged.", "펀드가 확대됐다."),
    "ethanol": ("/ˈeθənɒl/", "명사", "에탄올", "Ethanol subsidies were cut.", "에탄올 보조금이 삭감됐다."),
    "fairness": ("/ˈfeərnəs/", "명사", "공정성", "Fairness in pricing matters.", "가격 책정의 공정성이 중요하다."),
    "dependency": ("/dɪˈpendənsi/", "명사", "의존성", "Oil dependency was reduced.", "석유 의존성이 줄었다."),
    "prepayment": ("/ˌpriːˈpeɪmənt/", "명사", "선불, 조기 상환", "Prepayment penalties applied.", "조기 상환 페널티가 적용됐다."),
    "externality": ("/ˌekstɜːrˈnælɪti/", "명사", "외부성", "Negative externalities were taxed.", "부정적 외부성에 세금이 부과됐다."),
    "helicopter": ("/ˈhelɪkɒptər/", "명사", "헬리콥터", "Helicopter money was discussed.", "헬리콥터 머니가 논의됐다."),
    "perpetual": ("/pəˈpetʃuəl/", "형용사", "영구적인", "Perpetual bonds were issued.", "영구채가 발행됐다."),
    "ration": ("/ˈræʃən/", "동사", "배급하다", "Credit was rationed.", "신용이 배급됐다."),
    "mosque": ("/mɒsk/", "명사", "모스크", "Islamic finance grew.", "이슬람 금융이 성장했다."),
    "inability": ("/ˌɪnəˈbɪlɪti/", "명사", "무능, 불가능", "Inability to repay caused default.", "상환 불가능이 채무불이행을 초래했다."),
    "discriminate": ("/dɪˈskrɪmɪneɪt/", "동사", "차별하다", "Laws prevent discriminating.", "법이 차별을 방지한다."),
    "analytic": ("/ˌænəˈlɪtɪk/", "형용사", "분석적인", "Analytic tools improved decisions.", "분석 도구가 의사결정을 향상시켰다."),
    "proliferation": ("/prəˌlɪfəˈreɪʃən/", "명사", "확산, 급증", "Fintech proliferation accelerated.", "핀테크 확산이 가속됐다."),
    "autonomous": ("/ɔːˈtɒnəməs/", "형용사", "자율적인", "Autonomous vehicles changed logistics.", "자율주행차가 물류를 변화시켰다."),
    "prone": ("/proʊn/", "형용사", "~하기 쉬운", "Small firms are prone to failure.", "소기업은 실패하기 쉽다."),
    "inefficiency": ("/ˌɪnɪˈfɪʃənsi/", "명사", "비효율성", "Inefficiency was addressed.", "비효율성이 해결됐다."),
    "downgrade": ("/ˈdaʊnɡreɪd/", "동사", "강등하다, 하향 조정하다", "Moody's downgraded the bond.", "무디스가 채권을 강등했다."),
    "ideology": ("/ˌaɪdɪˈɒlədʒi/", "명사", "이념", "Market ideology shaped policy.", "시장 이념이 정책을 형성했다."),
    "greenhouse": ("/ˈɡriːnhaʊs/", "명사", "온실", "Greenhouse emissions fell.", "온실가스 배출이 줄었다."),
    "plead": ("/pliːd/", "동사", "간청하다, 변론하다", "The firm pleaded not guilty.", "회사가 무죄를 변론했다."),
    "openly": ("/ˈoʊpənli/", "부사", "공개적으로", "Managers openly discussed risks.", "매니저들이 공개적으로 위험을 논의했다."),
    "elastic": ("/ɪˈlæstɪk/", "형용사", "탄력적인", "Demand is highly elastic.", "수요가 매우 탄력적이다."),
    "oust": ("/aʊst/", "동사", "물러나게 하다", "The CEO was ousted.", "CEO가 물러나게 됐다."),
    "entrant": ("/ˈentrənt/", "명사", "신규 진입자", "New entrants disrupted the market.", "신규 진입자들이 시장을 교란시켰다."),
    "underwriter": ("/ˈʌndərˌraɪtər/", "명사", "인수자, 보증인", "The underwriter set the price.", "인수자가 가격을 정했다."),
    "cattle": ("/ˈkætəl/", "명사", "소, 가축", "Cattle futures rose sharply.", "소 선물이 급등했다."),
    "newcomer": ("/ˈnjuːˌkʌmər/", "명사", "신참자, 신규 기업", "A newcomer disrupted the sector.", "신규 기업이 업종을 교란시켰다."),
    "prolong": ("/prəˈlɒŋ/", "동사", "연장하다", "The crisis was prolonged.", "위기가 연장됐다."),
    "salvage": ("/ˈsælvɪdʒ/", "동사", "구하다, 만회하다", "Analysts tried to salvage the deal.", "분석가들이 거래를 살리려 했다."),
    "pursuant": ("/pəˈsjuːənt/", "형용사", "따라서", "Pursuant to the contract terms.", "계약 조건에 따라."),
    "appropriately": ("/əˈproʊprɪɪtli/", "부사", "적절하게", "Risk must be appropriately managed.", "위험이 적절하게 관리되어야 한다."),
    "accusation": ("/ˌækjʊˈzeɪʃən/", "명사", "고발, 비난", "Accusations of fraud were made.", "사기 고발이 제기됐다."),
    "entrepreneurial": ("/ˌɒntrəprəˈnɜːrɪəl/", "형용사", "기업가적인", "An entrepreneurial spirit drives growth.", "기업가 정신이 성장을 이끈다."),
    "devaluation": ("/ˌdiːˌvæljʊˈeɪʃən/", "명사", "평가절하", "Currency devaluation followed.", "통화 평가절하가 뒤따랐다."),
    "outlay": ("/ˈaʊtleɪ/", "명사", "지출, 경비", "Capital outlay rose sharply.", "자본 지출이 급등했다."),
    "simulate": ("/ˈsɪmjʊleɪt/", "동사", "모의실험하다", "Scenarios were simulated.", "시나리오가 모의실험됐다."),
    "precious": ("/ˈpreʃəs/", "형용사", "귀중한", "Precious metals gained.", "귀금속이 올랐다."),
    "regain": ("/rɪˈɡeɪn/", "동사", "되찾다", "Markets regained lost ground.", "시장이 잃었던 자리를 되찾았다."),
    "differentiation": ("/ˌdɪfərenʃɪˈeɪʃən/", "명사", "차별화", "Product differentiation is key.", "제품 차별화가 핵심이다."),
    "restrictive": ("/rɪˈstrɪktɪv/", "형용사", "제한적인", "Restrictive covenants applied.", "제한적 약정이 적용됐다."),
    "deed": ("/diːd/", "명사", "증서, 행위", "The property deed was transferred.", "부동산 증서가 이전됐다."),
    "competent": ("/ˈkɒmpɪtənt/", "형용사", "유능한, 적격의", "A competent manager was hired.", "유능한 매니저가 채용됐다."),
    "horror": ("/ˈhɒrər/", "명사", "공포", "The financial horror unfolded.", "금융 공포가 전개됐다."),
    "occasional": ("/əˈkeɪʒənəl/", "형용사", "간헐적인", "Occasional losses are expected.", "간헐적인 손실이 예상된다."),
    "globe": ("/ɡloʊb/", "명사", "지구, 세계", "Firms operate across the globe.", "기업들이 세계 전역에서 운영된다."),
    "sovereignty": ("/ˈsɒvrɪnti/", "명사", "주권", "Sovereignty over resources mattered.", "자원에 대한 주권이 중요했다."),
    "asylum": ("/əˈsaɪləm/", "명사", "망명, 피난처", "Financial asylum was sought.", "금융 피난처가 모색됐다."),
    "isolation": ("/ˌaɪsəˈleɪʃən/", "명사", "고립", "Economic isolation hurt growth.", "경제적 고립이 성장을 해쳤다."),
    "overstate": ("/ˌoʊvərˈsteɪt/", "동사", "과장하다", "Risks were overstated.", "위험이 과장됐다."),
    "hypothetical": ("/ˌhaɪpəˈθetɪkəl/", "형용사", "가상의", "A hypothetical scenario was tested.", "가상의 시나리오가 테스트됐다."),
    "deprive": ("/dɪˈpraɪv/", "동사", "빼앗다, 박탈하다", "The crisis deprived millions.", "위기가 수백만 명을 박탈했다."),
    "investigator": ("/ɪnˈvestɪɡeɪtər/", "명사", "조사자", "Investigators examined records.", "조사자들이 기록을 검토했다."),
    "explosive": ("/ɪkˈsploʊsɪv/", "형용사", "폭발적인", "Explosive growth was seen.", "폭발적인 성장이 목격됐다."),
    "tactical": ("/ˈtæktɪkəl/", "형용사", "전술적인", "A tactical retreat was made.", "전술적 후퇴가 이루어졌다."),
    "psychology": ("/saɪˈkɒlədʒi/", "명사", "심리학", "Market psychology shifted.", "시장 심리가 변했다."),
    "reap": ("/riːp/", "동사", "거두다, 수확하다", "Investors reaped rewards.", "투자자들이 보상을 거뒀다."),
    "disposable": ("/dɪˈspoʊzəbəl/", "형용사", "처분 가능한", "Disposable income fell.", "가처분 소득이 감소했다."),
    "arbitration": ("/ˌɑːrbɪˈtreɪʃən/", "명사", "중재", "Arbitration was initiated.", "중재가 시작됐다."),
    "boycott": ("/ˈbɔɪkɒt/", "명사", "불매운동", "A consumer boycott began.", "소비자 불매운동이 시작됐다."),
    "discrete": ("/dɪˈskriːt/", "형용사", "별개의, 불연속적인", "Discrete events drove losses.", "별개의 사건들이 손실을 초래했다."),
    "gloomy": ("/ˈɡluːmi/", "형용사", "침울한, 암울한", "A gloomy outlook emerged.", "암울한 전망이 나타났다."),
    "unpredictable": ("/ˌʌnprɪˈdɪktəbəl/", "형용사", "예측 불가능한", "Markets are unpredictable.", "시장은 예측 불가능하다."),
    "accumulation": ("/əˌkjuːmjʊˈleɪʃən/", "명사", "축적, 누적", "Debt accumulation continued.", "부채 축적이 계속됐다."),
    "disastrous": ("/dɪˈzɑːstrəs/", "형용사", "재앙적인", "A disastrous merger followed.", "재앙적인 합병이 뒤따랐다."),
    "dissident": ("/ˈdɪsɪdənt/", "명사", "반체제 인사", "Dissident shareholders voted.", "반체제 주주들이 투표했다."),
    "prototype": ("/ˈproʊtətaɪp/", "명사", "프로토타입, 원형", "A prototype was tested.", "프로토타입이 테스트됐다."),
    "defensive": ("/dɪˈfensɪv/", "형용사", "방어적인", "Defensive stocks outperformed.", "방어주가 초과 성과를 냈다."),
    "communism": ("/ˈkɒmjʊnɪzəm/", "명사", "공산주의", "Communism collapsed globally.", "공산주의가 전 세계적으로 붕괴됐다."),
    "drain": ("/dreɪn/", "동사", "고갈시키다", "Costs drained reserves.", "비용이 준비금을 고갈시켰다."),
    "frustration": ("/frʌˈstreɪʃən/", "명사", "좌절", "Investor frustration grew.", "투자자 좌절감이 높아졌다."),
    "fret": ("/fret/", "동사", "걱정하다", "Markets fretted over the data.", "시장이 데이터를 걱정했다."),
    "undervalue": ("/ˌʌndərˈvæljuː/", "동사", "과소평가하다", "The stock was undervalued.", "주식이 과소평가됐다."),
    "diligence": ("/ˈdɪlɪdʒəns/", "명사", "성실, 실사", "Due diligence was conducted.", "실사가 진행됐다."),
    "outweigh": ("/ˌaʊtˈweɪ/", "동사", "더 중요하다", "Benefits outweigh the risks.", "혜택이 위험보다 더 중요하다."),
    "undoubtedly": ("/ʌnˈdaʊtɪdli/", "부사", "의심할 여지없이", "Markets undoubtedly recovered.", "시장이 의심할 여지없이 회복됐다."),
    "composite": ("/ˈkɒmpəzɪt/", "명사", "복합 지수", "The composite index rose.", "복합 지수가 올랐다."),
    "micro": ("/ˈmaɪkroʊ/", "형용사", "미시적인", "Micro-level data was analyzed.", "미시적 수준의 데이터가 분석됐다."),
    "amongst": ("/əˈmʌŋst/", "전치사", "~사이에", "Amongst peers, performance varied.", "동료들 사이에서 성과가 다양했다."),
    "congressman": ("/ˈkɒŋɡrəsmən/", "명사", "하원의원", "The congressman proposed cuts.", "하원의원이 삭감을 제안했다."),
    "ratify": ("/ˈrætɪfaɪ/", "동사", "비준하다", "The treaty was ratified.", "조약이 비준됐다."),
    "eventual": ("/ɪˈventʃuəl/", "형용사", "최종적인, 결국의", "The eventual outcome was positive.", "최종 결과가 긍정적이었다."),
    "vague": ("/veɪɡ/", "형용사", "모호한", "The guidance was vague.", "지침이 모호했다."),
    "correspondent": ("/ˌkɒrɪˈspɒndənt/", "명사", "특파원, 통신 은행", "A correspondent bank was used.", "통신 은행이 활용됐다."),
    "doom": ("/duːm/", "명사", "파국, 운명", "Doom and gloom forecasts.", "파국과 암울한 예측들."),
    "rage": ("/reɪdʒ/", "명사", "분노", "Investor rage was intense.", "투자자 분노가 강렬했다."),
    "myth": ("/mɪθ/", "명사", "신화, 미신", "The growth myth was exposed.", "성장 신화가 드러났다."),
    "synthetic": ("/sɪnˈθetɪk/", "형용사", "합성의", "Synthetic bonds were created.", "합성 채권이 만들어졌다."),
}


def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT17:
                    pron, pos, meaning, ex_en, ex_ko = DICT17[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")


if __name__ == "__main__":
    print("=== Patching with fill_more17.py ===\n")
    patch_files()
