#!/usr/bin/env python3
"""Fill freq-L4 last 1 word + freq-L8 last 1 + TOEIC-L2 (239 words) part 1"""
import json, glob

DICT11 = {
    # freq-L4/L8 stragglers
    "sex":           ("/sɛks/", "명사", "성별, 성관계", "Discuss sex education.", "성교육에 대해 논의하세요."),

    # TOEIC-L2 (239 words)
    "grocery":       ("/ˈɡroʊsəri/", "명사", "식료품", "Buy groceries at the store.", "가게에서 식료품을 구매하세요."),
    "homework":      ("/ˈhoʊmwɜːrk/", "명사", "숙제", "Finish your homework.", "숙제를 끝내세요."),
    "memorandum":    ("/ˌmɛməˈrændəm/", "명사", "메모, 비망록", "Send an internal memorandum.", "내부 메모를 보내세요."),
    "photocopier":   ("/ˈfoʊtəˌkɒpiər/", "명사", "복사기", "The photocopier is broken.", "복사기가 고장났다."),
    "suite":         ("/swiːt/", "명사", "스위트룸, 조화", "Reserve a hotel suite.", "호텔 스위트룸을 예약하세요."),
    "thorough":      ("/ˈθʌrə/", "형용사", "철저한, 꼼꼼한", "Do a thorough review.", "철저한 검토를 하세요."),
    "bookstore":     ("/ˈbʊkstɔːr/", "명사", "서점", "Visit the bookstore.", "서점을 방문하세요."),
    "cater":         ("/ˈkeɪtər/", "동사", "음식을 공급하다, 충족시키다", "We cater for all dietary needs.", "모든 식이 요구를 충족합니다."),
    "dental":        ("/ˈdɛntəl/", "형용사", "치과의", "Schedule a dental appointment.", "치과 예약을 잡으세요."),
    "duration":      ("/djʊˈreɪʃən/", "명사", "기간, 지속 시간", "The duration of the course.", "과정의 기간."),
    "lounge":        ("/laʊndʒ/", "명사", "라운지, 휴게실", "Wait in the lounge.", "라운지에서 기다리세요."),
    "painter":       ("/ˈpeɪntər/", "명사", "화가, 페인트공", "Hire a house painter.", "집 페인트공을 고용하세요."),
    "patron":        ("/ˈpeɪtrən/", "명사", "고객, 후원자", "Thank our valued patrons.", "소중한 고객님들께 감사드립니다."),
    "prescription":  ("/prɪˈskrɪpʃən/", "명사", "처방전", "Fill the prescription.", "처방전을 받으세요."),
    "salad":         ("/ˈsæləd/", "명사", "샐러드", "Toss a fresh salad.", "신선한 샐러드를 만드세요."),
    "stack":         ("/stæk/", "명사", "더미, 스택", "Stack the papers neatly.", "서류를 가지런히 쌓으세요."),
    "delegate":      ("/ˈdɛlɪɡɪt/", "명사", "대표자, 대리인", "Send a delegate.", "대표자를 보내세요."),
    "salesperson":   ("/ˈseɪlzˌpɜːrsən/", "명사", "영업 사원", "Meet the new salesperson.", "새 영업 사원을 만나세요."),
    "calculator":    ("/ˈkælkjʊleɪtər/", "명사", "계산기", "Use a calculator.", "계산기를 사용하세요."),
    "completion":    ("/kəmˈpliːʃən/", "명사", "완료, 완성", "Upon completion, submit it.", "완료 후 제출하세요."),
    "defect":        ("/ˈdiːfɛkt/", "명사", "결함, 흠", "Report any product defect.", "제품 결함을 신고하세요."),
    "garbage":       ("/ˈɡɑːrbɪdʒ/", "명사", "쓰레기", "Take out the garbage.", "쓰레기를 버리세요."),
    "omit":          ("/oʊˈmɪt/", "동사", "빠뜨리다, 생략하다", "Don't omit important details.", "중요한 세부 사항을 빠뜨리지 마세요."),
    "spite":         ("/spaɪt/", "명사", "앙심, 악의", "In spite of the rain.", "비에도 불구하고."),
    "bathroom":      ("/ˈbæθruːm/", "명사", "욕실, 화장실", "Where is the bathroom?", "화장실이 어디인가요?"),
    "cab":           ("/kæb/", "명사", "택시", "Call a cab.", "택시를 부르세요."),
    "correspondence":("/ˌkɒrɪˈspɒndəns/", "명사", "서신, 통신", "Reply to all correspondence.", "모든 서신에 답장하세요."),
    "ladder":        ("/ˈlædər/", "명사", "사다리, 사다리꼴", "Climb the corporate ladder.", "사내 사다리를 오르세요."),
    "photography":   ("/fəˈtɒɡrəfi/", "명사", "사진 촬영, 사진술", "She loves photography.", "그녀는 사진 찍기를 좋아한다."),
    "sculpture":     ("/ˈskʌlptʃər/", "명사", "조각", "The sculpture is beautiful.", "조각이 아름답다."),
    "anniversary":   ("/ˌænɪˈvɜːrsəri/", "명사", "기념일", "Happy anniversary!", "기념일 축하합니다!"),
    "buffet":        ("/ˈbʊfeɪ/", "명사", "뷔페", "Enjoy the buffet.", "뷔페를 즐기세요."),
    "defective":     ("/dɪˈfɛktɪv/", "형용사", "결함 있는", "Return defective items.", "결함 있는 물건을 반환하세요."),
    "ice cream":     ("/ˈaɪs kriːm/", "명사", "아이스크림", "Buy chocolate ice cream.", "초콜릿 아이스크림을 사세요."),
    "leak":          ("/liːk/", "동사", "새다, 유출되다", "The pipe is leaking.", "파이프에서 물이 새고 있다."),
    "occupancy":     ("/ˈɒkjʊpənsi/", "명사", "점유율, 객실 수용률", "Maximum occupancy is 50.", "최대 수용 인원은 50명이다."),
    "proficiency":   ("/prəˈfɪʃənsi/", "명사", "능숙함, 숙달", "Demonstrate language proficiency.", "언어 능숙도를 보여주세요."),
    "renewal":       ("/rɪˈnjuːəl/", "명사", "갱신, 연장", "Apply for contract renewal.", "계약 갱신을 신청하세요."),
    "urgent":        ("/ˈɜːrdʒənt/", "형용사", "긴급한, 시급한", "This is urgent.", "이것은 긴급하다."),
    "annually":      ("/ˈænjuəli/", "부사", "매년, 연간", "Review salaries annually.", "매년 급여를 검토하세요."),
    "basketball":    ("/ˈbɑːskɪtbɔːl/", "명사", "농구", "Play basketball after school.", "방과 후 농구를 하세요."),
    "delete":        ("/dɪˈliːt/", "동사", "삭제하다", "Delete the file.", "파일을 삭제하세요."),
    "illogical":     ("/ɪˈlɒdʒɪkəl/", "형용사", "비논리적인", "The argument is illogical.", "논거가 비논리적이다."),
    "pet":           ("/pɛt/", "명사", "반려동물", "She has a pet cat.", "그녀는 고양이를 키운다."),
    "textbook":      ("/ˈtɛkstbʊk/", "명사", "교과서", "Buy the required textbook.", "필수 교과서를 구매하세요."),
    "accurately":    ("/ˈækjʊrɪtli/", "부사", "정확하게", "Report the data accurately.", "데이터를 정확하게 보고하세요."),
    "cabin":         ("/ˈkæbɪn/", "명사", "객실, 오두막", "Book a mountain cabin.", "산속 오두막을 예약하세요."),
    "conductor":     ("/kənˈdʌktər/", "명사", "지휘자, 차장", "The orchestra conductor.", "오케스트라 지휘자."),
    "inspector":     ("/ɪnˈspɛktər/", "명사", "검사관, 감독관", "The inspector checked the site.", "검사관이 현장을 점검했다."),
    "intern":        ("/ˈɪntɜːrn/", "명사", "인턴", "Hire a summer intern.", "여름 인턴을 채용하세요."),
    "semester":      ("/sɪˈmɛstər/", "명사", "학기", "Spring semester begins.", "봄 학기가 시작된다."),
    "confirmation":  ("/ˌkɒnfərˈmeɪʃən/", "명사", "확인, 확인서", "Send a booking confirmation.", "예약 확인서를 보내세요."),
    "congratulation":("/kənˌɡrætʃʊˈleɪʃən/", "명사", "축하", "Congratulations on your success.", "성공을 축하합니다."),
    "expertise":     ("/ˌɛkspɜːrˈtiːz/", "명사", "전문 지식", "Share your expertise.", "전문 지식을 공유하세요."),
    "graph":         ("/ɡræf/", "명사", "그래프, 도표", "Draw a bar graph.", "막대 그래프를 그리세요."),
    "taker":         ("/ˈteɪkər/", "명사", "수험자, 받는 사람", "The test taker.", "시험 응시자."),
    "utility":       ("/juːˈtɪlɪti/", "명사", "유틸리티, 공공요금", "Pay the utility bills.", "공과금을 납부하세요."),
    "banker":        ("/ˈbæŋkər/", "명사", "은행가", "He works as a banker.", "그는 은행가로 일한다."),
    "behalf":        ("/bɪˈhæf/", "명사", "~을 대신하여", "On behalf of the team.", "팀을 대신하여."),
    "minimize":      ("/ˈmɪnɪmaɪz/", "동사", "최소화하다", "Minimize the risks.", "위험을 최소화하세요."),
    "optional":      ("/ˈɒpʃənəl/", "형용사", "선택적인", "Attendance is optional.", "참석은 선택 사항이다."),
    "paycheck":      ("/ˈpeɪtʃɛk/", "명사", "급여 수표", "Receive a monthly paycheck.", "월 급여를 받으세요."),
    "polite":        ("/pəˈlaɪt/", "형용사", "예의 바른", "Be polite to customers.", "고객에게 예의 바르게 하세요."),
    "protective":    ("/prəˈtɛktɪv/", "형용사", "보호하는", "Wear protective gear.", "보호 장비를 착용하세요."),
    "seller":        ("/ˈsɛlər/", "명사", "판매자", "Best seller of the year.", "올해의 베스트셀러."),
    "sidewalk":      ("/ˈsaɪdwɔːk/", "명사", "보도, 인도", "Walk on the sidewalk.", "보도 위를 걸으세요."),
    "sightsee":      ("/ˈsaɪtsiː/", "동사", "관광하다", "Go sightseeing downtown.", "시내를 관광하세요."),
    "soup":          ("/suːp/", "명사", "수프", "Have hot soup.", "따뜻한 수프를 드세요."),
    "transit":       ("/ˈtrænzɪt/", "명사", "통과, 운송", "Public transit system.", "대중 교통 시스템."),
    "wallet":        ("/ˈwɒlɪt/", "명사", "지갑", "Lost my wallet.", "지갑을 잃어버렸다."),
    "cashier":       ("/kæˈʃɪər/", "명사", "계산원", "Pay the cashier.", "계산원에게 계산하세요."),
    "casual":        ("/ˈkæʒuəl/", "형용사", "편안한, 캐주얼한", "Dress casually.", "편안하게 입으세요."),
    "drill":         ("/drɪl/", "명사", "드릴, 훈련", "Practice fire drill.", "화재 훈련을 연습하세요."),
    "fountain":      ("/ˈfaʊntɪn/", "명사", "분수", "Meet at the fountain.", "분수에서 만나세요."),
    "juice":         ("/dʒuːs/", "명사", "주스", "Drink fresh orange juice.", "신선한 오렌지 주스를 마시세요."),
    "lane":          ("/leɪn/", "명사", "차선, 골목", "Stay in your lane.", "차선을 유지하세요."),
    "popularity":    ("/ˌpɒpjʊˈlærɪti/", "명사", "인기", "The app's popularity grew.", "앱의 인기가 높아졌다."),
    "poster":        ("/ˈpoʊstər/", "명사", "포스터", "Hang the poster.", "포스터를 붙이세요."),
    "promptly":      ("/ˈprɒmptli/", "부사", "신속하게, 즉시", "Respond promptly.", "신속하게 응답하세요."),
    "retailer":      ("/ˈriːteɪlər/", "명사", "소매업자", "Partner with local retailers.", "지역 소매업자와 협력하세요."),
    "vacancy":       ("/ˈveɪkənsi/", "명사", "공석, 빈자리", "Fill the vacancy.", "공석을 채우세요."),
    "bench":         ("/bɛntʃ/", "명사", "벤치", "Sit on the bench.", "벤치에 앉으세요."),
    "cumulative":    ("/ˈkjuːmjʊlətɪv/", "형용사", "누적적인", "Cumulative effect.", "누적 효과."),
    "directory":     ("/dɪˈrɛktəri/", "명사", "디렉토리, 안내서", "Check the phone directory.", "전화번호부를 확인하세요."),
    "disposal":      ("/dɪˈspoʊzəl/", "명사", "처리, 처분", "Waste disposal.", "폐기물 처리."),
    "housekeeper":   ("/ˈhaʊskiːpər/", "명사", "가정부, 객실 담당 직원", "The housekeeper cleaned the room.", "가정부가 방을 청소했다."),
    "internship":    ("/ˈɪntɜːrnʃɪp/", "명사", "인턴십", "Apply for an internship.", "인턴십에 지원하세요."),
    "knowledgeable": ("/ˈnɒlɪdʒəbəl/", "형용사", "지식이 많은", "A knowledgeable staff.", "지식이 풍부한 직원."),
    "organizer":     ("/ˈɔːrɡənaɪzər/", "명사", "주최자, 정리함", "Contact the event organizer.", "행사 주최자에게 연락하세요."),
    "overdue":       ("/ˌoʊvərˈdjuː/", "형용사", "기한이 지난, 연체된", "The payment is overdue.", "결제가 연체됐다."),
    "prediction":    ("/prɪˈdɪkʃən/", "명사", "예측, 예언", "Make a prediction.", "예측을 하세요."),
    "subscriber":    ("/səbˈskraɪbər/", "명사", "구독자", "Gain new subscribers.", "새 구독자를 얻으세요."),
    "booklet":       ("/ˈbʊklɪt/", "명사", "소책자", "Read the instruction booklet.", "안내 소책자를 읽으세요."),
    "conditioner":   ("/kənˈdɪʃənər/", "명사", "컨디셔너, 에어컨", "Apply hair conditioner.", "헤어 컨디셔너를 바르세요."),
    "enroll":        ("/ɪnˈroʊl/", "동사", "등록하다, 입학하다", "Enroll in the course.", "강좌에 등록하세요."),
    "frustrate":     ("/frʌˈstreɪt/", "동사", "좌절시키다", "Don't let it frustrate you.", "그것이 당신을 좌절시키지 않게 하세요."),
    "garment":       ("/ˈɡɑːrmənt/", "명사", "의복, 의류", "Quality garments.", "품질 좋은 의류."),
    "orientation":   ("/ˌɔːriɛnˈteɪʃən/", "명사", "오리엔테이션, 방향", "Attend the employee orientation.", "직원 오리엔테이션에 참석하세요."),
    "outlet":        ("/ˈaʊtlɛt/", "명사", "콘센트, 할인 매장", "Plug into the outlet.", "콘센트에 꽂으세요."),
    "packet":        ("/ˈpækɪt/", "명사", "패킷, 작은 봉지", "Open the packet.", "봉지를 여세요."),
    "plumber":       ("/ˈplʌmər/", "명사", "배관공", "Call a plumber.", "배관공을 부르세요."),
    "specification": ("/ˌspɛsɪfɪˈkeɪʃən/", "명사", "사양, 명세서", "Read the specifications.", "사양서를 읽으세요."),
    "auto":          ("/ˈɔːtoʊ/", "명사", "자동차, 자동", "Auto insurance.", "자동차 보험."),
    "decorate":      ("/ˈdɛkəreɪt/", "동사", "장식하다", "Decorate the office.", "사무실을 장식하세요."),
    "deduction":     ("/dɪˈdʌkʃən/", "명사", "공제, 추론", "Tax deduction.", "세금 공제."),
    "definite":      ("/ˈdɛfɪnɪt/", "형용사", "명확한, 확실한", "Give a definite answer.", "명확한 답을 주세요."),
    "economical":    ("/ˌiːkəˈnɒmɪkəl/", "형용사", "경제적인, 절약형의", "Economical fuel consumption.", "경제적인 연료 소비."),
    "efficiently":   ("/ɪˈfɪʃəntli/", "부사", "효율적으로", "Work efficiently.", "효율적으로 일하세요."),
    "flyer":         ("/ˈflaɪər/", "명사", "전단지", "Distribute flyers.", "전단지를 배포하세요."),
    "generous":      ("/ˈdʒɛnərəs/", "형용사", "관대한, 너그러운", "She is generous.", "그녀는 관대하다."),
    "interrupt":     ("/ˌɪntəˈrʌpt/", "동사", "방해하다, 끊다", "Don't interrupt.", "방해하지 마세요."),
    "oven":          ("/ˈʌvən/", "명사", "오븐", "Preheat the oven.", "오븐을 예열하세요."),
    "pant":          ("/pænt/", "명사", "바지", "Iron the pants.", "바지를 다려라."),
    "profitable":    ("/ˈprɒfɪtəbəl/", "형용사", "수익성 있는", "A profitable business.", "수익성 있는 사업."),
    "refrigerator":  ("/rɪˈfrɪdʒəreɪtər/", "명사", "냉장고", "Stock the refrigerator.", "냉장고를 채우세요."),
    "reimburse":     ("/ˌriːɪmˈbɜːrs/", "동사", "상환하다, 변제하다", "Reimburse the expenses.", "비용을 상환하세요."),
    "showroom":      ("/ˈʃoʊruːm/", "명사", "전시장", "Visit the car showroom.", "자동차 전시장을 방문하세요."),
    "vegetarian":    ("/ˌvɛdʒɪˈtɛəriən/", "명사", "채식주의자", "I am vegetarian.", "저는 채식주의자입니다."),
    "administrator": ("/ədˈmɪnɪstreɪtər/", "명사", "관리자", "Contact the administrator.", "관리자에게 연락하세요."),
    "broker":        ("/ˈbroʊkər/", "명사", "중개인, 브로커", "Hire a real estate broker.", "부동산 중개인을 고용하세요."),
    "cancellation":  ("/ˌkænsəˈleɪʃən/", "명사", "취소", "No cancellation fee.", "취소 수수료 없음."),
    "confidential":  ("/ˌkɒnfɪˈdɛnʃəl/", "형용사", "기밀의", "Keep it confidential.", "기밀로 유지하세요."),
    "jet":           ("/dʒɛt/", "명사", "제트기", "Travel by jet.", "제트기로 여행하세요."),
    "realistic":     ("/ˌriːəˈlɪstɪk/", "형용사", "현실적인", "Be realistic.", "현실적으로 생각하세요."),
    "thoroughly":    ("/ˈθʌrəli/", "부사", "철저하게", "Check thoroughly.", "철저하게 확인하세요."),
    "trash":         ("/træʃ/", "명사", "쓰레기", "Empty the trash.", "쓰레기를 비우세요."),
    "usage":         ("/ˈjuːsɪdʒ/", "명사", "사용, 용법", "Data usage is high.", "데이터 사용량이 높다."),
    "windy":         ("/ˈwɪndi/", "형용사", "바람이 많이 부는", "It is very windy today.", "오늘 바람이 많이 분다."),
    "automate":      ("/ˈɔːtəmeɪt/", "동사", "자동화하다", "Automate the process.", "과정을 자동화하세요."),
    "ferry":         ("/ˈfɛri/", "명사", "페리, 나룻배", "Take the ferry.", "페리를 타세요."),
    "finalize":      ("/ˈfaɪnəlaɪz/", "동사", "마무리하다, 확정하다", "Finalize the contract.", "계약을 확정하세요."),
    "incur":         ("/ɪnˈkɜːr/", "동사", "초래하다, 발생하다", "Incur additional costs.", "추가 비용이 발생하다."),
    "instruct":      ("/ɪnˈstrʌkt/", "동사", "지시하다, 가르치다", "Instruct the staff.", "직원들에게 지시하세요."),
    "loyal":         ("/ˈlɔɪəl/", "형용사", "충성스러운", "Loyal customers.", "충성 고객."),
    "luncheon":      ("/ˈlʌntʃən/", "명사", "오찬, 점심 식사", "Business luncheon.", "비즈니스 오찬."),
    "microphone":    ("/ˈmaɪkrəfoʊn/", "명사", "마이크", "Test the microphone.", "마이크를 테스트하세요."),
    "overview":      ("/ˈoʊvərˌvjuː/", "명사", "개요", "Give a brief overview.", "간략한 개요를 주세요."),
    "projector":     ("/prəˈdʒɛktər/", "명사", "프로젝터", "Set up the projector.", "프로젝터를 설치하세요."),
    "shortage":      ("/ˈʃɔːrtɪdʒ/", "명사", "부족, 결핍", "A labor shortage.", "인력 부족."),
    "spacious":      ("/ˈspeɪʃəs/", "형용사", "넓은, 공간이 많은", "A spacious office.", "넓은 사무실."),
    "accomplishment":("/əˈkɒmplɪʃmənt/", "명사", "성취, 업적", "List your accomplishments.", "업적을 나열하세요."),
    "accustom":      ("/əˈkʌstəm/", "동사", "익숙하게 하다", "Accustom yourself to change.", "변화에 익숙해지세요."),
    "clinic":        ("/ˈklɪnɪk/", "명사", "클리닉, 진료소", "Visit the dental clinic.", "치과 진료소를 방문하세요."),
    "desktop":       ("/ˈdɛsktɒp/", "명사", "데스크톱", "Save to the desktop.", "데스크톱에 저장하세요."),
    "jog":           ("/dʒɒɡ/", "동사", "조깅하다", "Jog every morning.", "매일 아침 조깅하세요."),
    "leisure":       ("/ˈlɛʒər/", "명사", "여가, 레저", "Leisure time is important.", "여가 시간이 중요하다."),
    "nap":           ("/næp/", "명사", "낮잠", "Take a short nap.", "잠깐 낮잠을 자세요."),
    "reinforce":     ("/ˌriːɪnˈfɔːrs/", "동사", "강화하다, 보강하다", "Reinforce the message.", "메시지를 강화하세요."),
    "sender":        ("/ˈsɛndər/", "명사", "발신자", "Return to sender.", "발신자에게 반송하세요."),
    "vacuum":        ("/ˈvækjuːm/", "동사", "진공청소기로 청소하다", "Vacuum the carpet.", "카펫을 진공청소기로 청소하세요."),
    "wireless":      ("/ˈwaɪərləs/", "형용사", "무선의", "Connect to wireless.", "무선에 연결하세요."),
    "yearly":        ("/ˈjɪərli/", "형용사", "연간의, 매년의", "Yearly review.", "연간 검토."),
    "appreciation":  ("/əˌpriːʃɪˈeɪʃən/", "명사", "감사, 이해", "Show appreciation.", "감사를 표현하세요."),
    "cargo":         ("/ˈkɑːrɡoʊ/", "명사", "화물", "Ship the cargo.", "화물을 운송하세요."),
    "cooperate":     ("/koʊˈɒpəreɪt/", "동사", "협력하다", "Cooperate with the team.", "팀과 협력하세요."),
    "distract":      ("/dɪˈstrækt/", "동사", "산만하게 하다", "Don't distract others.", "다른 사람들을 산만하게 하지 마세요."),
    "exemption":     ("/ɪɡˈzɛmpʃən/", "명사", "면제", "Tax exemption.", "세금 면제."),
    "furnish":       ("/ˈfɜːrnɪʃ/", "동사", "가구를 비치하다, 제공하다", "Furnish the apartment.", "아파트에 가구를 비치하세요."),
    "hourly":        ("/ˈaʊərli/", "형용사", "시간당의", "Hourly wage.", "시간당 임금."),
    "laundry":       ("/ˈlɔːndri/", "명사", "빨래, 세탁", "Do the laundry.", "빨래를 하세요."),
    "mandatory":     ("/ˈmændətɔːri/", "형용사", "의무적인", "Attendance is mandatory.", "출석은 의무이다."),
    "mechanical":    ("/mɪˈkænɪkəl/", "형용사", "기계적인", "Mechanical issue.", "기계적인 문제."),
    "pharmacy":      ("/ˈfɑːrməsi/", "명사", "약국", "Buy medicine at the pharmacy.", "약국에서 약을 사세요."),
    "promotional":   ("/prəˈmoʊʃənəl/", "형용사", "판촉의", "Promotional material.", "판촉 자료."),
    "residential":   ("/ˌrɛzɪˈdɛnʃəl/", "형용사", "주거의", "Residential area.", "주거 지역."),
    "scholarship":   ("/ˈskɒlərʃɪp/", "명사", "장학금", "Apply for a scholarship.", "장학금에 지원하세요."),
    "seeker":        ("/ˈsiːkər/", "명사", "구직자, 추구하는 사람", "Job seeker.", "구직자."),
    "temporarily":   ("/ˈtɛmpərɛrɪli/", "부사", "일시적으로", "Temporarily closed.", "일시 휴업."),
    "towel":         ("/ˈtaʊəl/", "명사", "수건", "Dry off with a towel.", "수건으로 닦으세요."),
    "unattended":    ("/ˌʌnəˈtɛndɪd/", "형용사", "무인의, 방치된", "Don't leave bags unattended.", "가방을 방치하지 마세요."),
    "accessible":    ("/əkˈsɛsɪbəl/", "형용사", "접근 가능한", "Accessible to all.", "모두에게 접근 가능하다."),
    "afterward":     ("/ˈæftərwərd/", "부사", "그 후에, 나중에", "Let's talk afterward.", "나중에 이야기하자."),
    "apology":       ("/əˈpɒlədʒi/", "명사", "사과", "Offer a sincere apology.", "진심 어린 사과를 하세요."),
    "assemble":      ("/əˈsɛmbəl/", "동사", "조립하다, 모으다", "Assemble the team.", "팀을 모으세요."),
    "automatic":     ("/ˌɔːtəˈmætɪk/", "형용사", "자동적인", "Automatic payment.", "자동 결제."),
    "boardroom":     ("/ˈbɔːrdruːm/", "명사", "이사회실", "Meet in the boardroom.", "이사회실에서 만나세요."),
    "carpenter":     ("/ˈkɑːrpəntər/", "명사", "목수", "Hire a skilled carpenter.", "숙련된 목수를 고용하세요."),
    "caterer":       ("/ˈkeɪtərər/", "명사", "출장 음식 업체", "Book a caterer.", "출장 음식 업체를 예약하세요."),
    "classify":      ("/ˈklæsɪfaɪ/", "동사", "분류하다", "Classify the documents.", "문서를 분류하세요."),
    "consultation":  ("/ˌkɒnsəlˈteɪʃən/", "명사", "상담, 협의", "Free consultation.", "무료 상담."),
    "durable":       ("/ˈdjʊərəbəl/", "형용사", "내구성 있는", "Durable materials.", "내구성 있는 소재."),
    "glove":         ("/ɡlʌv/", "명사", "장갑", "Wear protective gloves.", "보호 장갑을 착용하세요."),
    "hardware":      ("/ˈhɑːrdwɛər/", "명사", "하드웨어, 철물", "Hardware store.", "철물점."),
    "malfunction":   ("/ˌmælfʌŋkʃən/", "명사", "오작동", "Report a malfunction.", "오작동을 신고하세요."),
    "outdated":      ("/ˌaʊtˈdeɪtɪd/", "형용사", "구식의", "Outdated software.", "구식 소프트웨어."),
    "patience":      ("/ˈpeɪʃəns/", "명사", "인내, 참을성", "Have patience.", "참을성을 가지세요."),
    "postcard":      ("/ˈpoʊstkɑːrd/", "명사", "엽서", "Send a postcard.", "엽서를 보내세요."),
    "prospective":   ("/prəˈspɛktɪv/", "형용사", "잠재적인, 예비의", "Prospective clients.", "잠재 고객."),
    "revision":      ("/rɪˈvɪʒən/", "명사", "수정, 개정", "Final revision.", "최종 수정."),
    "strictly":      ("/ˈstrɪktli/", "부사", "엄격하게", "Follow the rules strictly.", "규칙을 엄격하게 따르세요."),
    "tomato":        ("/təˈmɑːtoʊ/", "명사", "토마토", "Add tomatoes to the salad.", "샐러드에 토마토를 넣으세요."),
    "tray":          ("/treɪ/", "명사", "쟁반", "Carry the tray carefully.", "쟁반을 조심스럽게 들고 가세요."),
    "vendor":        ("/ˈvɛndər/", "명사", "판매상", "Choose the best vendor.", "최고의 판매상을 선택하세요."),
    "withdrawal":    ("/wɪðˈdrɔːəl/", "명사", "인출, 철수", "Cash withdrawal.", "현금 인출."),
    "anytime":       ("/ˈɛnɪtaɪm/", "부사", "언제든지", "Call me anytime.", "언제든지 전화하세요."),
    "badge":         ("/bædʒ/", "명사", "배지, 명찰", "Wear your badge.", "명찰을 착용하세요."),
    "brake":         ("/breɪk/", "명사", "브레이크", "Apply the brakes.", "브레이크를 밟으세요."),
    "calculation":   ("/ˌkælkjʊˈleɪʃən/", "명사", "계산", "Double-check the calculation.", "계산을 재확인하세요."),
    "coordinator":   ("/koʊˈɔːrdɪneɪtər/", "명사", "코디네이터", "Event coordinator.", "행사 코디네이터."),
    "costly":        ("/ˈkɒstli/", "형용사", "값비싼", "A costly mistake.", "값비싼 실수."),
    "equip":         ("/ɪˈkwɪp/", "동사", "갖추다, 장비를 갖추다", "Equip the team.", "팀에 장비를 갖추세요."),
    "excursion":     ("/ɪkˈskɜːrʃən/", "명사", "소풍, 여행", "Day excursion.", "당일 여행."),
    "graphic":       ("/ˈɡræfɪk/", "형용사", "그래픽의, 생생한", "Graphic design.", "그래픽 디자인."),
    "inexperience":  ("/ˌɪnɪkˈspɪəriəns/", "명사", "경험 부족", "Inexperience caused mistakes.", "경험 부족이 실수를 낳았다."),
    "lengthy":       ("/ˈlɛŋθi/", "형용사", "긴, 장황한", "A lengthy process.", "긴 과정."),
    "librarian":     ("/laɪˈbrɛəriən/", "명사", "사서", "Ask the librarian.", "사서에게 물어보세요."),
    "meantime":      ("/ˈmiːntaɪm/", "명사", "그 동안", "In the meantime.", "그 동안에."),
    "merge":         ("/mɜːrdʒ/", "동사", "합병하다, 합치다", "Merge the two companies.", "두 회사를 합병하세요."),
    "performer":     ("/pərˈfɔːrmər/", "명사", "공연자", "A talented performer.", "재능 있는 공연자."),
    "pharmacist":    ("/ˈfɑːrməsɪst/", "명사", "약사", "Ask the pharmacist.", "약사에게 물어보세요."),
    "pizza":         ("/ˈpiːtsə/", "명사", "피자", "Order a pizza.", "피자를 주문하세요."),
    "resignation":   ("/ˌrɛzɪɡˈneɪʃən/", "명사", "사임, 사직", "Submit a resignation letter.", "사직서를 제출하세요."),
    "reviewer":      ("/rɪˈvjuːər/", "명사", "검토자, 평가자", "The reviewer gave feedback.", "검토자가 피드백을 줬다."),
    "terminate":     ("/ˈtɜːrmɪneɪt/", "동사", "종료하다, 해고하다", "Terminate the contract.", "계약을 종료하세요."),
    "translation":   ("/trænsˈleɪʃən/", "명사", "번역", "Accurate translation.", "정확한 번역."),
    "unfamiliar":    ("/ˌʌnfəˈmɪliər/", "형용사", "익숙하지 않은", "Unfamiliar territory.", "익숙하지 않은 영역."),
    "actress":       ("/ˈæktrɪs/", "명사", "여배우", "Famous actress.", "유명한 여배우."),
    "adjacent":      ("/əˈdʒeɪsənt/", "형용사", "인접한", "Adjacent buildings.", "인접한 건물들."),
    "alternate":     ("/ˈɔːltərneɪt/", "동사", "교대하다, 번갈아 하다", "Alternate between tasks.", "업무를 번갈아 하세요."),
    "congratulate":  ("/kənˈɡrætʃʊleɪt/", "동사", "축하하다", "Congratulate the winner.", "우승자를 축하하세요."),
    "escort":        ("/ˈɛskɔːrt/", "동사", "호위하다, 안내하다", "Escort the VIP.", "VIP를 안내하세요."),
    "inexpensive":   ("/ˌɪnɪkˈspɛnsɪv/", "형용사", "저렴한", "Inexpensive option.", "저렴한 선택지."),
    "mask":          ("/mɑːsk/", "명사", "마스크, 가면", "Wear a face mask.", "마스크를 착용하세요."),
    "purchaser":     ("/ˈpɜːrtʃɪsər/", "명사", "구매자", "Original purchaser.", "원래 구매자."),
    "purse":         ("/pɜːrs/", "명사", "지갑, 핸드백", "She lost her purse.", "그녀가 핸드백을 잃었다."),
    "realtor":       ("/ˈriːəltər/", "명사", "부동산 중개인", "Hire a realtor.", "부동산 중개인을 고용하세요."),
    "rearrange":     ("/ˌriːəˈreɪndʒ/", "동사", "재배치하다", "Rearrange the furniture.", "가구를 재배치하세요."),
    "reopen":        ("/ˌriːˈoʊpən/", "동사", "재개업하다", "The store will reopen.", "가게가 다시 열 것이다."),
    "soap":          ("/soʊp/", "명사", "비누", "Use soap to wash.", "비누로 씻으세요."),
    "spokesperson":  ("/ˈspoʊkspɜːrsən/", "명사", "대변인", "Company spokesperson.", "회사 대변인."),
    "superior":      ("/suːˈpɪəriər/", "형용사", "우수한, 상급의", "Superior quality.", "우수한 품질."),
    "airfare":       ("/ˈɛərfɛər/", "명사", "항공 요금", "Round-trip airfare.", "왕복 항공 요금."),
    "bake":          ("/beɪk/", "동사", "굽다", "Bake a cake.", "케이크를 구우세요."),
    "businessperson":("/ˈbɪznɪspɜːrsən/", "명사", "사업가", "A skilled businessperson.", "숙련된 사업가."),
    "considerably":  ("/kənˈsɪdərəbli/", "부사", "상당히", "Considerably better.", "상당히 더 낫다."),
    "faulty":        ("/ˈfɔːlti/", "형용사", "결함 있는", "Faulty equipment.", "결함 있는 장비."),
    "hobby":         ("/ˈhɒbi/", "명사", "취미", "What is your hobby?", "취미가 무엇인가요?"),
    "informal":      ("/ɪnˈfɔːrməl/", "형용사", "격식 없는", "Informal meeting.", "격식 없는 회의."),
    "kilometer":     ("/ˈkɪlɒmiːtər/", "명사", "킬로미터", "Run 5 kilometers.", "5킬로미터를 달리세요."),
}

def patch_files():
    files = sorted(glob.glob("src/data/**/*.json", recursive=True))
    total = 0
    for filepath in files:
        with open(filepath, encoding="utf-8") as f:
            entries = json.load(f)
        changed = 0
        for entry in entries:
            word = entry.get("word", "")
            key = word.lower()
            if entry.get("meaning", "") in ("", word):
                if key in DICT11:
                    pron, pos, meaning, ex_en, ex_ko = DICT11[key]
                    entry["pronunciation"] = pron
                    entry["partOfSpeech"] = pos
                    entry["meaning"] = meaning
                    entry["exampleEn"] = ex_en
                    entry["exampleKo"] = ex_ko
                    changed += 1
        if changed:
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(entries, f, ensure_ascii=False, indent=2)
            print(f"  ✓ {filepath}: +{changed} patched")
        total += changed
    print(f"\n=== Done. Total patched: {total} ===")

if __name__ == "__main__":
    print("=== Patching with fill_more11.py ===\n")
    patch_files()
